### ISSUE TITLE
Incorporate Experience Standards into the Design System

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1001]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add Design System component label (such as `va-alert`)
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
The CollabCycle team points teams going through the cycle at the [Experience Standards ](https://vfs.atlassian.net/wiki/spaces/CC/pages/1683980311/VA.gov+experience+standards) criteria. This issue is to track work to design and implement a way for VFS teams to find relevant guidance in the Design System for all applicable items in the Experience Standards.

## Details
Here is how I recommend we go about this, but open to other ideas:

1. Duplicate the Experience Standards into the Design System, breaking the one table up into distinct pages. It is a great set of criteria and teams should be referencing it. Also, both the DST and CollabCycle teams should be ensuring the System backs the Standards and vice-versa.
2. Start by linking each major section of the Standards to the relevant Design System section. For example, Color, typography and visual elements should at the least link to Color and Typography sections of the System. This may require creating new sections that have broad guidance. For example, "Assistive tech and device support" might require a broad a11y page that perhaps highlights the importance of a11y and expectations around research and usability testing.
3. 1 and 2 would get us to a MVP. From there we should ensure that each individual criteria links to the relevant guidance in the System. Each item should, when necessary, be discussed in greater detail. That may be as simple as linking from "Link and button labels" > "Your content uses correct and consistent labels across links, entry points, navigation components, and H1s." to a section of guidance, in this case: Link > Content considerations and Button > Content considerations (or into the Content style guide). As this is being done we should ensure that each item in the Standards criteria has a specific piece of guidance that speaks to it in the System guidance. There is no point in linking the two together if they don't support one another.
4. Finally, we may at this time want to implement a numbering system or index in the Design System for guidance in order to connect each item as well as give the CollabCycle team a way to reference a specific piece of guidance.

## Tasks
- [ ] Write or update documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Documentation is published on design.va.gov

**Comment by GnatalieH** [comment]
I would love to help out with this work, FWIW. I remember Mikki and Meg showing me these experience standards when I first joined the DST.

**Comment by seanasewell** [comment]
@GnatalieH Are you working on any other tickets? I am working on separating symbols and front facing components sketch file. It's a big task. I know this one is assigned to me but if you want to tackle it, I don't mind at all.

**Comment by GnatalieH** [comment]
@seanasewell I don't this this work is scheduled for our next sprint. I just happened to see this ticket in the backlog and commented on it. Let's chat when I return after Labor Day. I want to help you on that big task, too. Thanks!

**Comment by humancompanion-usds** [comment]
This is done: https://design.va.gov/about/experience-standards/

I may move these to Foundations instead as "About" is a bit of catch-all at the moment.
