### ISSUE TITLE
Add links to bug report template to design.va.gov pages

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1003]
## Description
It seems that the link to file a bug from design.va.gov was dropped. Other teams are using the experimental design template for filing a bug which leads to confusion for everyone. 

## Details
Add link to Bug report to the following pages on design.va.gov:
- For Developers
- For Designers
- Contributing to the Design System
- All component pages

(https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=caw310&labels=vsp-design-system-team&template=bug_template.md&title=) 

## Tasks
- [ ] Add link to Bug report issue template to For Developers
- [ ] Add link to Bug report issue template to For Designers
- [ ] Add link to Bug report issue template to Contributing to the Design System
- [ ] Add link to Bug report issue template to each component page

## Acceptance Criteria
- [ ] There is a link to Bug report template on For Developers
- [ ] There is a link to Bug report template on For Developers
- [ ] There is a link to Bug report template on Contributing to the Design System
- [ ] There is a link to Bug report template on all component pages

**Comment by humancompanion-usds** [comment]
There remains a link from the Feedback page to file a GitHub issue. However, one problem is when you get to that list it is now overwhelming because all of the internal issue templates. Filing a Bug is still towards the top, but I would suggest we namespace our internal templates (i.e. "_internal-[name]") so they sort to the bottom.

My [latest pull request](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/998) does add a link to file a bug to the Contribution page. I've also just now updated the Feedback page. We could add a link to Feedback in the footer as well.

**Comment by k80bowman** [comment]
I like the idea about namespacing the templates. I have a few other things I want to do with them as well, I can take care of that. Thank you for adding the link to the Contribution page and updating the Feedback page.

**Comment by humancompanion-usds** [comment]
There is a link to submit a bug in the header. Closing due to age.

![Image](https://github.com/user-attachments/assets/e9349530-bc50-4718-9187-f6de249ec2e5)
