### ISSUE TITLE
Banner & full-width Alert - Audit

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1005]
## Description
Audit of banner (sitewide and promo) and full-width alert instances. Identify as many instances of this component or pattern in use on VA.gov and share with the Design System Team.

## Tasks
- [ ] Work with engineers, the Governance team, and the sitewide team to find examples of this type of component
- [ ] Add screenshots of component usage examples to a Mural board, including links to sources
- [ ] Add link to Mural board as a comment in this ticket and to the component design ticket if applicable

## Acceptance Criteria
- [ ] Component usage examples have been collected on a Mural board and a link to the board has been added to this ticket

**Comment by humancompanion-usds** [comment]
Here is the Mural link:
https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1656518038765?sender=u9ae4d29a0ed5c3d2753a7824&key=0db4a381-f941-48ff-8fc6-cfca1257388d

**Comment by mmiddaugh** [comment]
I assume you are aware of the following, but just in case: 
- [Banner components for alerts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/banners/banner-alerts.md)
- [Double banner on VAMC page example from Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/banners/examples/vamc-double-banners-032521.png)

**Comment by GnatalieH** [comment]
I see this ticket is assigned to me, but I believe the audits are done according to the links in this ticket. Please advise, @humancompanion-usds.

**Comment by humancompanion-usds** [comment]
We've got an audit.

**Comment by mmiddaugh** [comment]
[Alert and banner events.xlsx](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/9134365/Alert.and.banner.events.xlsx)
