### ISSUE TITLE
Patterns > Forms > Contact Information - Update documentation

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1006]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add Design System component label (such as `va-alert`)
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
Update documentation and guidance for Contact information in Patterns > Forms on design.va.gov. We currently tell teams to use an anti-pattern of confirming an email address outside of the account creation process. In practice, we seem to pre-populate this field and use of this pattern in that instance is ill-advised. 

The Debt team has already removed the extra confirmation field:
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/30740

There is a Slack thread referenced in that issue that has the full discussion.

## Details
We'll need to capture a new screenshot and update the guidance here:
https://design.va.gov/patterns/forms/contact-information#email-address

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Pattern documentation is updated on design.va.gov

**Comment by humancompanion-usds** [comment]
Updated URL: https://design.va.gov/patterns/ask-users-for/email-address

* Update screenshot to not include the confirmation field.
* Remove validate email addresses and replace with "Prepopulate email address from Profile whenever possible" as this makes it easier for users as they have one less field to complete.

**Comment by taylojill** [comment]
## Usage

### When to use this pattern

* **When you need to collect an email address.** For example, for contact information.
 
## Examples






![Image](https://user-images.githubusercontent.com/97645218/207418647-1fa27543-974f-4ca8-8c04-81833ab6b166.png)





## How to design and build 

### How this pattern works

- **If possible, tell users why you want their email address.** Users need to know that the VA won’t abuse their email. An example message is: *We may use your contact information so we can get in touch with you if we have questions about your application.*
- **Prepopulate email address from Profile whenever possible.** This makes it easier for users as they have one less field to complete.*

## Content considerations

### Error message templates for email addresses

**Comment by taylojill** [comment]
Hi @humancompanion-usds I submitted a draft for your review for #1006. Natalie provided the example screen shot and I updated the statement about using the prepopulated email address. Also, under Content considerations, I wasn't sure, but removed the error message content as it no longer applied if field is prepopulated. I look forward to your feedback!

**Comment by GnatalieH** [comment]
@taylojill I got this info from the VAOS Designer who helped me get the screenshot in case it helps with the Content considerations...

"And here's the error validation for that page (the screenshot):

Error messages

Phone - input empty
Please enter a phone number

Phone - input invalid
Please enter a valid 10-digit phone number (with or without dashes)

Email - input empty
Please provide a response

Email - input invalid
Please enter a valid email address

There's also a character limit on email addresses, I need to dig up that message."

**Comment by taylojill** [comment]
Hi @GnatalieH Thank you! I added error messages for the phone number inputs. Question, would there be an error message if the prepopulated email address went beyond the character limit?

**Comment by GnatalieH** [comment]
That's a great question, @taylojill. I'll ask about that.

**Comment by humancompanion-usds** [comment]
Looks good @taylojill. We should probably speak to the anti-pattern of adding an email confirmation field and why we think that's no longer necessary. The short story there is that 1. It's unnecessary if we're using the email from Profile, which we should be. and 2. It's not terribly useful for catching errors as most users copy and paste and don't review their initial entry.

Otherwise this is good to go. Work with @GnatalieH  to make the PR to the existing pattern.

**Comment by taylojill** [comment]
Will do @humancompanion-usds Thanks!

**Comment by GnatalieH** [comment]
@taylojill I added you to the Slack thread where the VAOS Designer, Peter Russso, chimes in re: pre-polulated email validation error. [Here's the link to the thread](https://dsva.slack.com/archives/C0NGDDXME/p1670949662412619).

**Comment by taylojill** [comment]
Thank you @GnatalieH

**Comment by humancompanion-usds** [comment]
Updated: https://design.va.gov/patterns/ask-users-for/email-address
