### ISSUE TITLE
 Mobile friendly expandable alert - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1010]
## Description
Create design for Mobile friendly expandable alert. 

See this DSC for additional info. 
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/476

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding design issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this design and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
[add links to any tickets or documents with details about the design]
[add links to any research documents related to the component]

## Tasks
- [x] Review DST backlog for outstanding design issues with this component, if necessary
- [x] Create designs for component
- [x] Update Sketch library
- [x] Review designs with PO and/or DSC
- [x] Review designs with an accessibility specialist
- [x] Review designs with DST members (Carol can help schedule this)
- [x] Address any comments from reviews, if necessary
- [x] Comment on this ticket with any accessibility considerations engineers may need to know
- [x] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by GnatalieH** [comment]
[Here is the link ](https://www.sketch.com/s/789c144c-98c6-4350-b9d5-9acb6112069d/p/9496B366-71D9-4EAE-BDC9-A5D9BBE07CC5) to my Sketch symbols, so far. I left a question for @seanasewell and @humancompanion-usds in our team's Slack channel regarding how to best build these symbols.

This one may carry over to the next sprint because it has so many Sketch assets and ended up becoming a bit more complex than I anticipated. FYI @k80bowman and @caw310. Thanks.
