### ISSUE TITLE
Mobile-friendly, expandable alert - Documentation update

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1011]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add Design System component label (such as `va-alert`)
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
Update documentation and guidance for Mobile-friendly, expandable alert on design.va.gov. When adding a new component, use the [component documentation template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/_components/template.md).

## Details
[add links to any design documents]

[add link to Sketch component page]

Be sure to use the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option. If this is a new component that has not yet gone through Staging Review, use the "Use with Caution: Candidate" label.

## Tasks
- [x] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [x] Request documentation draft review
- [x] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by andresriveratoro** [comment]
The Storybook examples are in. Reassigning to @humancompanion-usds

**Comment by humancompanion-usds** [comment]
Okay, this is one where development got out ahead of design and I wasn't paying careful enough attention to what was in here. Talked to Allison about this component. The use case the team tested for is for information we need to alert a user about when they reach a page or form flow. Thus unlike an Alert, it is not due to user action. Therefore we think the only valid variations are info and warning. Error and success should be handled by our standard Alert component. 

Thus we need to circle back around with the team that generated this component for us and ask them for valid use cases where they have used these other variations. If there are none then we need to remove them. If there are some then I need to review them and they may need to return to DSC.

Sorry, I should have caught this sooner. The documentation that was written for this for the "experiment" is largely copy and pasting from Alert which was inappropriate. Allison indicated this was one of the first experimental components. Thus it seems like the process was not yet very robust.

**Comment by k80bowman** [comment]
This component is currently in use in two places:
- The [facility-locator application](https://github.com/department-of-veterans-affairs/vets-website/blob/d96726162e27fdfaa173102bd23b028c98c5915c/src/applications/facility-locator/components/search-results-items/common/LocationCovidStatus.jsx#L46-L58) uses it for an info alert
- The [health care application](https://github.com/department-of-veterans-affairs/vets-website/blob/9da87cc28994b7ff13eabc4bc3322729e1b916ec/src/applications/hca/components/FormAlerts/index.jsx#L33-L41) uses it for a success alert

**Comment by GnatalieH** [comment]
[Here is the link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/QMQAY8/a/nRdbRGg/r/kj01RA) to the Sketch page for Alert - expandable. I haven't yet starred the release, so only editors/contributors to the Sketch file can see it right now.

**Comment by humancompanion-usds** [comment]
@caw310 - I marked this as fixed with my PR but now that I look at it I'm not sure @SarahKay8 had a chance to look at this. If that's true, please reopen and assign to Sarah. Thanks!

**Comment by caw310** [comment]
@SarahKay8 , please run a11y tests on this.

**Comment by SarahKay8** [comment]
Will do

**Comment by SarahKay8** [comment]
Hey team. I don't have any additional feedback for current considerations. Moving to review/QA pipeline
