### ISSUE TITLE
[Sketch discovery work] - Can we use a shape symbol for red error-state borders on form fields?

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1015]
## Description
We need to update the error state form assets in the Sketch library to use a 4px (rather than 2px) red border. @seanasewell brought up the idea of using a shape symbol that would work globally for the error states, rather than having to make changes to every asset in the future. After we do this work, we should complete #960 in one sprint.

## Details
Create a 4px square/rectangular shape symbol and test it to make sure it works with the following components:

- Date input
- Memorable date
- Number input
- Select box
- Text input
- Textarea

## Tasks
- [x] Review DST backlog for outstanding design issues with this component, if necessary
- [x] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by GnatalieH** [comment]
Closing because we made a decision:

We'll move forward by implementing layer styles for input field, which will be a nested symbol we'll include in:

- Date input
- Memorable date
- Number input
- Select box
- Text input
- Textarea

This update should be handled in work for issue #960.
