### ISSUE TITLE
Delete Banner, CollapsiblePanel, PromoBanner, and TextArea React components from component-library

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1016]
## Description
The Banner, CollapsiblePanel, PromoBanner, and TextArea React components are no longer used in vets-website and we need to remove them from the component-library repo. We will need to remove the React TextArea Storybook story as well.

## Tasks
- [x] Double check that none of these components are used in vets-website (just to be safe)
- [x] Delete the TextArea Storybook story
- [x] Delete the Banner, CollapsiblePanel, PromoBanner, and TextArea React components from the component-library repo

## Acceptance Criteria
- [x] The Banner, CollapsiblePanel, PromoBanner, and TextArea React components have been removed from the component-library repo.
