### ISSUE TITLE
Create documentation about the new token library

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1020]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Description
We need to add some documentation about the new token library:
- Documentation about contributing to it
- Documentation about using it

## Details
Documentation about contributing should probably go in the package README. Documentation about usage should go on design.va.gov.

## Tasks
- [ ] Add documentation to the package README about contributing to the token library
- [ ] Add documentation to design.va.gov about using the token library

## Acceptance Criteria
- [ ] Documentation is available about contributing to and using the token library

**Comment by caw310** [comment]
We are not quite ready to draft documentation on the new token library so moving back to reviewed/needs prioritizing.
