### ISSUE TITLE
Publish the design token library to NPM

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1021]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Description
We want teams to be able to use the VADS design token library independently of other design system resources. 

This ticket is dependent on the work in #1017 and #1019.

## Details
It might be good to reach out to the Lighthouse team (Brent Schneider) and the Console UI team (John Chapin) and make sure that CSS variables would work well for them.

## Tasks
- [ ] Figure out the best way to publish the design token library (CSS variables?)
- [ ] Create a package for the design token library and publish it to NPM

## Acceptance Criteria
- [ ] The VADS design token library is published to NPM as a separate package.

**Comment by bkjohnson** [comment]
Since we have been using the `component-library` repo to make Github releases for a single package, when we start doing this we may want to use [the semantic-release monorepo plugin](https://github.com/pmowrer/semantic-release-monorepo)

**Comment by andresriveratoro** [comment]
We are closing this in favor of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1068
