### ISSUE TITLE
Discovery: Determine what we need to bring to the new CSS library beyond utility classes and element selectors

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1023]
## Description
Go through the shame file and other non-utility and non-element selectors in Formation and determine if there are other things that need to be transferred to the new CSS library. 

## Details
We aren't planning on bringing over any of the modules. It would be good to document them, however, so that we can plan to make web components out of them.

## Tasks
- [ ] Review Formation to determine what else needs to be brought over to the new CSS library.
- [ ] Create a plan for addressing everything that needs to be brought over
- [ ] Review plan with the engineering team
- [ ] Write tickets to complete the plan

## Acceptance Criteria
- [ ] A comment has been added to this ticket with a list of additional features that need to be brought from Formation to the new CSS library
- [ ] A comment has been added to this ticket with a plan for addressing the features listed above
- [ ] The plan has been reviewed with the engineering team
- [ ] Tickets have been written for completing the plan

**Comment by k80bowman** [comment]
As noted in #188, it would be useful to have a `.nowrap` class.

**Comment by bkjohnson** [comment]
USWDS3 has a [`.text-no-wrap` utility already](https://designsystem.digital.gov/utilities/text-styles/) that we could provide.

---

As seen in the file comments on https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/855, here are the styles in formation which we may want to bring over into our new library:

- `.va-introtext`
- `.va-crisis-line` [and friends](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/a49016986d4bfe5692afae48dae08878b150ee26/packages/formation/sass/site/_m-crisis-line.scss#L1-L118)
  - This may be better off as a DS component, or not part of the DS at all and purely a `vets-website` thing


Everything else could be covered by existing utilities, or they were USWDS tweaks/fixes or styling changes to grid-based things like `.row` and `.column`.

**Comment by humancompanion-usds** [comment]
.va-introtext perhaps maps to .usa-intro? You can see it in action here: https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?id=pages-documentation-page--documentation-page&args=&viewMode=story

I would like to make the VA Crisis Line element a web-component. I've seen, thru the CollabCycle, at least one team grab it and use it elsewhere. If we put it in the DS we can better govern the use of it. Also, our example in the Modal component is out of date both for that component and the modal itself. We should get those components in sync with production.

**Comment by k80bowman** [comment]
I added Crisis Line to the list of components we'd like to add in our [Airtable](https://airtable.com/appF4FJKBeNVNGrlm/tblOlEnERCgZTiNF4/viw0nKV3yQiY3IonD?blocks=hide).

@bkjohnson could you take a look at `.usa-intro` and see if that would match up with `.va-introtext`?

**Comment by bkjohnson** [comment]
Through the `typeset` mixin, [`.usa-intro` will set](https://github.com/uswds/uswds/blob/f2752b236c3f9fc477eac17d76033838abbbc281/packages/usa-intro/src/styles/_usa-intro.scss#L3-L11):

- `line-height`
- `font-family`
- `font-size`
- `font-weight`
- `max-width`

Those are the same properties that [`.va-introtext` is setting](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/a49016986d4bfe5692afae48dae08878b150ee26/packages/formation/sass/base/_va.scss#L363-L373). However, since we have the nested styling for `p` tags within `.va-introtext`, we would probably want [app code like this](https://github.com/department-of-veterans-affairs/vets-website/blob/f5d1b8b53f1b05ef9885510f3d026dad937130b5/src/applications/coronavirus-vaccination/components/Introduction.jsx#L39-L46) to remove the inner `p` tags.

**Comment by k80bowman** [comment]
It looks like in most cases with the nested `p` tag it shouldn't be very difficult to remove. But there is at least [one case where the app has multiple nested `p` tags](https://github.com/department-of-veterans-affairs/vets-website/blob/139b98eb9c2f94fdeee841098607bb2b52163a7f/src/applications/coronavirus-screener/containers/App.jsx), which would be more difficult.
