### ISSUE TITLE
Discovery: What is the best implementation plan for CSS type (element/tag) selectors?

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1025]
## Description
We have a set of CSS type selectors in the Formation CSS library and we need to figure out the best way to bring them over to the new CSS library without causing too much disruption when we begin the migration process in the vets-website repository.

## Details
Because these are type selectors and not class selectors, we can't have frontend teams adopt them intentionally. Once the new CSS library package is imported into vets-website, it will conflict and could potentially override the type selectors in Formation. There's also the issue of the `!important` rules on some of the type selectors in Formation. Switching to a version without the `!important`s could cause some problems with application styles.

## Tasks
- [ ] Explore what it will take to migrate from the Formation type selectors to the v3-based type selectors in vets-website
- [ ] Outline a plan for implementing the type selectors in the new CSS library that will be the least disruptive for vets-website applications
- [ ] Present plan to DST engineers
- [ ] Create a ticket (or tickets) for implementing the type selectors with the details of this plan

## Acceptance Criteria
- [ ] A plan for implementing the type selectors in the new CSS library has been created and reviewed with the DST engineering team
- [ ] Any necessary tickets for implementing the plan have been created.

**Comment by bkjohnson** [comment]
[Here is an example](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/3ccc9d7277e0d5813aa16f4d3e1a4b1181c2bb01/packages/formation/sass/base/_va.scss#L1-L16) of the kinds of global tag styling that formation is applying that we will need to decide how we want to handle once va.gov is no longer using `formation`.

**Comment by bkjohnson** [comment]
Here are some questions for us to answer?

1. Is there a reason for anyone to use a `<table>` directly? We already discourage using tables for layout reasons, and we have a responsive table component. If the answer is no, then we don't have to include [these table styles](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/modules/_m-table.scss).
1. With USWDS3, do we still have a reason to [normalize the `dl` tag](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/_normalize.scss) even though [USWDS v3 does not](https://github.com/uswds/uswds/blob/908c436e971ae96e6b2aeb192f7a64daae435ad5/packages/uswds-elements/lib/_normalize.scss)?
1. Do we expect or want to encourage use of the plain `<button>` element? If so, we may need [the background color styling](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/modules/_m-button.scss#L5-L10)

Additionally, there are some styles that are applied directly to tags that are children of certain classes, [like this one](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L949-L971). Some of those parent classes are used and some aren't. My recommendation is to do an audit and removed CSS classes that we can confirm as being unused in `vets-website` and `content-build` and then evaluate what needs to be moved over based on what's left.

Without cleaning things up and being able to take a better look, here are styles that seem like good candidates to bring into our new CSS library:

- [`article > h1` margin](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L309-L311)
- [`hr` styles](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L190-L194)
- [this chunk](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L72-L183) on `ul`, `ol`, and more styling
- Most of [these `html` and `body` styles](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L1-L17), minus the font-size ones.
    - We found out that these font size changes from formation interfered with uswds3 typography.

We could copy those styles into [this unused stylesheet](https://github.com/department-of-veterans-affairs/component-library/blob/8afb4a34a512725db1baa50b1c81c0d76658a7b2/packages/css-library/src/stylesheets/elements.scss), unless USWDS provides something that we can import instead.

**Comment by caw310** [comment]
Adding comment to clarify that this issue was transferred to Andrew in December due to unanticipated team changes.

**Comment by caw310** [comment]
@Andrew565 , please write new ticket or tickets for this work breaking it into smaller pieces. Please link to this so we don't lose what Brooks wrote up.

**Comment by jamigibbs** [comment]
### Follow-up Notes

> 1. Is there a reason for anyone to use a `<table>` directly? We already discourage using tables for layout reasons, and we have a responsive table component. If the answer is no, then we don't have to include these table styles.

No and I don't think we need to bring this over. There are a [few instances of `table`](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-website%20%3Ctable&type=code) but they all look like they can be updated to use `va-table` instead

> 2. With USWDS3, do we still have a reason to [normalize the dl tag](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/_normalize.scss) even though USWDS v3 does not?

No and I don't even think that stylesheet is being used at all. We are just importing normalize [directly in Formation](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/dc5a3dc66ca057ec897f189578be08b3ee1f2db1/packages/formation/sass/core.scss#L7
).

> 3. Do we expect or want to encourage use of the plain `<button>` element? If so, we may need the [background color styling](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/modules/_m-button.scss#L5-L10)

I looked at some of the uses of `button` and it seems like all of these could just be using `va-button` now.

- For forms that require a `type=submit`, the [submit prop](https://design.va.gov/storybook/?path=/docs/components-va-button--primary) can be used.
- And there are no uses of `[type='image']`, `[type='reset']`, 

We can create a new ESLint rule to prefer the va-button component [similar to the one we have for telephone](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/lib/rules/prefer-telephone-component.js) as a follow-up to point teams in the right direction.

### Outline a plan for implementing the type selectors in the new CSS library that will be the least disruptive for vets-website applications

1. Duplicate the identified selectors from Formation into the CSS Library. The [elements.scss](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/elements.scss) file seems like a good place but we may want to organize any parent class > child tag styles differently.
2. Normalize.css -  [Formation is loading it from USWDS v1](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/core.scss#L7). We will need to make sure it's loaded [from USWDS v3](https://github.com/uswds/uswds/blob/develop/packages/uswds-elements/lib/_normalize.scss) via CSS Library or somewhere.
3. These selectors will be in both Formation and CSS Library for a time until a cut-off happens. What should happen is that, because they are the same styles, there shouldn't be any visual difference.

### Follow-up Tickets

- [ ] Add the identified selectors to the CSS Library [elements.scss stylesheet](https://github.com/department-of-veterans-affairs/component-library/blob/8afb4a34a512725db1baa50b1c81c0d76658a7b2/packages/css-library/src/stylesheets/elements.scss).
  - [article > h1](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L309-L311)
  - [hr](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L190-L194)
  - [abbr, a, headings, ol/ul, figure, etc](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L190-L194)
  - [html and body (**except font-size**)](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L1-L17)
  - [mobile typography h1, h2](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/mobile-typography.scss#L7-L15)
  - [print header, footer, nav](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-print.scss#L7-L9)
  - [print a[href]](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-print.scss#L23-L30)
- [ ] Audit and remove CSS classes that are parent class > child tag. Some of those parent classes are used and some aren't. If confirmed as being unused in `vets-website` and `content-build`, then evaluate what needs to be moved over based on what's still needed. Here is [an example of parent class > child tag styles](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L332-L352) where the classes `feature-list` and `va-list--feature` are not found/used any more so we don't need to bring that over.
- [ ] Convert any remaining `<table>` tags to `va-table`
- [ ] Create an ESLint Rule to use va-button instead of button ([telephone rule example](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/lib/rules/prefer-telephone-component.js))
