### ISSUE TITLE
Discovery: Using USWDS v3 resources in the va-accordion web component

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1035]
## Description
Attempt to use USWDS CSS and JS resources to the extent possible in our va-accordion web component. The purpose of this discovery is both to determine to what extent we can use USWDS resources in the accordion web component and to determine how we handle using USWDS resources in a complex component which varies from the USWDS implementation.

## Details
The accordion component is complex, so this work is going to be difficult. The ideal is that we are able to import CSS and JS directly from the USWDS accordion component and use them in our web component. There may need to be some variation from the USWDS resources as we have a single-select variation with multi-select as the default. We also have an expand all/close all button, which USWDS does not.

## Tasks
- [ ] Attempt to use USWDS CSS and JS resources in the va-accordion web component
- [ ] Write up the results and add them as a comment to this ticket
- [ ] Present results to the DS team

## Acceptance Criteria
- [ ] Develop a better understanding of how we use USWDS resources in complex components and present to the DS team

**Comment by bkjohnson** [comment]
In order to use USWDS3 resources as much as possible for our accordion web component it looks like we would need to build the `<va-accordion-item>` without a shadow DOM. This is because the `usa-accordion` JS has a function that accepts a button and [uses `.closest()` to look at its parents until a match is found for a selector](https://github.com/uswds/uswds/blob/846e45b50662851a6d37f20726d9d20dd415a3fa/packages/usa-accordion/src/index.js#L35). With a shadow DOM boundary in place, this JS wouldn't be able to find the element with the `usa-accordion` class.

I also haven't been able to get the font-size to be what I want it to be so that the other `rem` units produce the expected result, so some more work would probably have to be done around that. USWDS3 also uses different fonts so I think we would have to load those onto the page or modify the CSS.

Another thing worth mentioning is that when we use USWDS JS to manage things like toggling the accordion items open and closed, we are no longer getting built-in analytics events firing. These would have to be added some other way in order to preserve functionality.

**Comment by k80bowman** [comment]
It sounds to me like it may not be worth using the USWDS JS. It wasn't written with web components in mind, and I hate to lose the shadow DOM (and to have to do some gymnastics around getting analytics to fire). I would be OK with just sticking with using USWDS CSS.

AS for the font issues, do you have any recommendations about how we could resolve that? Is that something that was a problem with textarea?

**Comment by bkjohnson** [comment]
I didn't really notice the font-sizing issues with the textarea, and I'm still not quite sure why they were happening here. We may need to modify the base size or resort to adding custom CSS to set the font-size to be what we want it to be.

Also, using the SVG assets worked, but I wasn't able to get things setup so that the build would look in the USWDS SVG directory _and_ our own one, but I figured that if we're going to be using USWDS assets anyway then we won't need our own SVG assets. If we do at some point then I'm sure there will be a way - as a last resort we could copy files from one location to another so that USWDS SVGs and ours were all in the same place and easy to find.
