### ISSUE TITLE
Discovery: Using USWDS v3 resources in the va-textarea component

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1036]
## Description
Attempt to use USWDS CSS resources to the extent possible in our va-textarea web component. The purpose of this discovery is both to determine to what extent we can use USWDS resources in the textarea web component and to determine how we handle using USWDS resources in a simple component which varies slightly from the USWDS implementation.

## Details
The textarea component is relatively simple. The ideal is that we are able to import CSS and JS directly from the [USWDS textarea component](https://github.com/uswds/uswds/tree/develop/packages/usa-textarea) and use them in our web component. There may need to be some variation from the USWDS resources as our textarea component has a max-width and the USWDS component does not.

## Tasks
- [x]  Attempt to use USWDS CSS resources in the va-textarea web component
- [x] Write up the results and add them as a comment to this ticket
- [ ] Present results to the DS team

## Acceptance Criteria
- [ ] Develop a better understanding of how we use USWDS resources in simple components and present to the DS team

**Comment by bkjohnson** [comment]
I've left more detailed comments as review on https://github.com/department-of-veterans-affairs/component-library/pull/493, but the summary is:

- We can add configuration that will let us import specific USWDS3 packages
  - Being specific with the imports allows us to minimize the bundle size
- USWDS3 classes offer a lot, but aren't quite comprehensive enough to meet all our needs. This is likely to vary by component
  - Other than importing entire packages, we can also use the provided mixins and functions
- Customization is also possible, but tokens can only be chosen from pre-determined values
  - Unless we have a good reason to use our own colors, like for possible contrast issues, I think it's easiest to use USWDS color tokens for everything

**Comment by k80bowman** [comment]
How do you feel about doing this with the rest of our components that have USWDS equivalents? Do you think it will make maintenance easier or more difficult over time?

**Comment by bkjohnson** [comment]
I think it makes sense to do this with the rest of our components so that we can use as much from USWDS3 as possible and have to write little to none of our own CSS. I think this will make maintenance easier over time as long as we "stay within the lines" of USWDS.
