### ISSUE TITLE
Button Pair - Announcement

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1045]
## Description
Add an item to the monthly [What's New update Confluence page](https://vfs.atlassian.net/wiki/spaces/DST/pages/2301100061/Monthly+DS+Updates+to+What+s+New) that says the Link web component is ready for use. It should include a link to the component on design.va.gov.

## Details
Dependent on the completion of development, the creation of Sketch artifacts and component page, and documentation for the component on design.va.gov.

Sample announcement:
> The new [[component name] component](link to component on design.va.gov) is now available in the Design System. Guidance and design resources are now available on design.va.gov, in Storybook, and in the Sketch Pattern Library.

## Tasks
- [x] Craft component announcement (be sure to add appropriate links)
- [x] Add announcement to the monthly What's New update Confluence page

## Acceptance Criteria
- [x] Component announcement has been added to the monthly What's New update Confluence page

**Comment by GnatalieH** [comment]
Thanks for doing these awesome issue templates, @k80bowman! I noticed two Slack channels you may want to add to the bullet list for announcements:

#platform-design
#platform-design-system

Thanks!

**Comment by k80bowman** [comment]
We can absolutely add those. Thank you!

**Comment by GnatalieH** [comment]
@k80bowman just our public channel is fine. Thanks!

**Comment by andresriveratoro** [comment]
This has been added to the [July 2022 DS updates confluence page](https://vfs.atlassian.net/wiki/spaces/DST/pages/2301493271/July+2022+Design+System+updates).

![Screen Shot 2022-08-12 at 11 15 57](https://user-images.githubusercontent.com/36863582/184386122-41524055-c805-4ed8-9ca1-5f24ee1cfafd.png)
