### ISSUE TITLE
Announce deprecation of Date and RadioButtons React components

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1046]
## Description
Once all backlog tickets related to these two components have been resolved, we need to announce that we are fully deprecating the Date and RadioButtons React components. These two are already marked as deprecated in Storybook. RadioButtons does not seem to have an ESLint rule, so we should add that.

## Details
Depending on the result of department-of-veterans-affairs/va.gov-team#40212, the Date component may not be in use in vets-website anymore. If it is not, we can probably just delete it from the repo, rather than going through the full deprecation process. 

**Update** the Date component is no longer used and will be deleted as part of department-of-veterans-affairs/va.gov-team#40212. There is no need to announce its deprecation.

The RadioButtons React component is used widely and I don't believe we have an ESLint rule for it. So we will need to add one and set it to a warning.

Once the ESLint rule is in place, we want to announce that we will be fully deprecating these components. We encourage people to migrate to the web component version as soon as possible, and for the next six weeks (three sprints) the ESLint rules for these components will be kept as a warning and the component documentation on Storybook will still be available. After six weeks (three sprints), we will change the ESLint rule to an error and remove the component documentation from Storybook. The component will still be part of the component-library package at that point, but we will be actively reaching out to teams to encourage them to upgrade to the web component.

## Tasks
- [x] Check if Date React component is still in use
    - [x] If it is not, we can delete it from the component library
- [x] Create ESLint rule for the RadioButtons React component
- [ ] Make announcement about deprecating the RadioButtons (and Date, if necessary) React component. Post in the following channels:
    - #vfs-all-teams
    - #vfs-engineers
    - #vfs-frontend
    - #design
    - #cms-design
    - #cms-team

## Acceptance Criteria
- [x] Date React component has been removed from the component library if it is no longer in use
- [x] ESLint warning rule has been created for the RadioButtons react component
- [ ] Deprecation announcement has been posted in the specified channels

**Comment by caw310** [comment]
Waiting for response from Check-in team on whether they will use date component.

**Comment by bkjohnson** [comment]
No fix needed for the React Date component, the check-in team [will be using Memorable Date](https://dsva.slack.com/archives/C01DBGX4P45/p1660336214515849?thread_ts=1660236756.190719&cid=C01DBGX4P45) web component.

**Comment by k80bowman** [comment]
We can move forward with this and announce the deprecation of RadioButtons without waiting for the React Date component to be deleted.

**Comment by k80bowman** [comment]
Announcement text:
> :change-announcement: The VA Design System Team is in the process of deprecating the [RadioButtons React component](https://design.va.gov/storybook/?path=/docs/components-radiobuttons--aria-describedby). We encourage all teams using the RadioButtons React component to instead upgrade to the [va-radio web component](https://design.va.gov/storybook/?path=/docs/components-va-radio--default). We currently have an ESLint warning in place to encourage this upgrade as well.
>
>**On Thursday, September 29th, we will be changing the ESLint warning to an ESLint error for any changed files. We will also be removing documentation about the React VaRadio component from Storybook and reaching out to any teams still using the component and request that they upgrade to the web component**
>
>If your team has any issues upgrading to the web component, please reach out to the Design System Team in the #vfs-platform-support channel.

**Comment by k80bowman** [comment]
Announced in the #platform-design-system, #vfs-all-teams, and #design channels. Created ticket (#1114) for the next step in the deprecation process.
