### ISSUE TITLE
File Input web component: Migration

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1048]
## Description
Create an ESLint rule for the FileInput component. It is only used in three places in vets-website, so it might be worth reaching out to those teams and encouraging them to migrate as well.

## Tasks
- [x] Create an ESLint rule (warning) for the FileInput React component
- [x] Notify teams using this component and encourage them to migrate to the web component version

## Acceptance Criteria
- [x] An ESLint warning rule exists for the FileInput component and the appropriate teams have been contacted.

**Comment by jamigibbs** [comment]
These are the three apps identified as using the React version of FileInput:

- lgy-coe: https://depo-platform-documentation.scrollhelp.site/getting-started/lgy-coe
- claim-status-tool: https://depo-platform-documentation.scrollhelp.site/getting-started/claim-status-tool
- financial-status-report-fsr: https://depo-platform-documentation.scrollhelp.site/getting-started/financial-status-report-fsr

**Comment by jamigibbs** [comment]
Additional info about the teams/codeowners for the apps using FileInput:

- **lgy-coe**: https://depo-platform-documentation.scrollhelp.site/getting-started/lgy-coe
  - https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/lgy/coe/status/components/DocumentUploader/DocumentUploader.jsx
  - Slack: `#benefits-team-1`

- **claim-status-tool**: https://depo-platform-documentation.scrollhelp.site/getting-started/claim-status-tool 
  - https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/components/AddFilesForm.jsx
  -  Slack: `#benefits-team-1`

- **financial-status-report-fsr**: https://depo-platform-documentation.scrollhelp.site/getting-started/financial-status-report-fsr 
  - https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/components/FileUploader.jsx
  - Slack: `#benefits-team-2`

**Comment by jamigibbs** [comment]
- #benefits-team-1 notified: https://dsva.slack.com/archives/C5AGLBNRK/p1663698922492659
- #benefits-team-2 notified: https://dsva.slack.com/archives/CPE4AJ6Q0/p1663699332712819
- #vfs-change-announcements: https://dsva.slack.com/archives/C03R5SBELQM/p1663696954185639
