### ISSUE TITLE
OMB Info web component: Migration

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1049]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Description
Create an ESLint rule for the OMB info component. It is used extensively in vets-website, so it would help to have a migration assist.

## Tasks
- [ ] Add ESLint warning rule for the OMB info component with migration assistance

## Acceptance Criteria
- [ ] ESLint warning rule has been created for the OMB info component

**Comment by andresriveratoro** [comment]
I've submitted a support request to Release Tools to publish the latest version of eslint-plugin to npm.
