### ISSUE TITLE
A11y audit of form library working demo - Accessibility review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1052]
## Issue Description
The FLT has asked for an A11y audit of form library working demo

## Tasks
- [ ] Full accessibility review of the FL working demo
- [ ] Write up an a11y testing checklist or plan
- [ ] Test the FL working demo using a11y software 
- [ ] Compile a list of issues
- [ ] Sync with DK, Angela and Tiffany on their a11y audit of the FL working demo
- [ ] Write up tickets for issues you have identified and assign them to either DST or FLT

## Acceptance Criteria
- [ ] Create checklist or use an existing checklist for the a11y audit
- [ ] List of issues has been compiled
- [ ] Met with other a11y specialists to sync up on findings
- [ ] Tickets with issues found have been written up for the teams

**Comment by caw310** [comment]
This has dependency on FLT having their demo ready for the a11y audit.

**Comment by caw310** [comment]
@SarahKay8 here are the instructions from Karen on filing issues. 

If tickets directly in GitHub, please add in the va-forms-system-core repository (https://github.com/department-of-veterans-affairs/va-forms-system-core/issues)
⁃ Assign to the Accessibility Issues (FL and VAFSC) pipeline
⁃ Add labels: VA Forms System Core, relevant accessibility labels
⁃ Add epic: VAFSC Accessibility Support
⁃ Here is what that looks like: https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/482

**Comment by SarahKay8** [comment]
Primary testing done. Ready for review
