### ISSUE TITLE
Develop research plan to test double box-shadow for focus styling 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1057]
## Description
Develop research plan to test double box-shadow for focus styling. 

## Details
The research plan is related to this request that came through DSC. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/654
From the ticket, Natalie got input on types of participants to include. 
The groups that would probably be most impacted are:

- Colorblind users
- Low vision users / people who routinely use screen magnification
- Sighted keyboard-only users
- Voice command software users (eg. Dragon NaturallySpeaking)

## Tasks
- [ ] Draft a research plan with steps and questions for user testing
- [ ] Work with Perigean to have them recruit participants for user testing 
- [ ] Have Matt (and possibly Josh) review research plan 

## Acceptance Criteria
- [ ] Research plan has been written up
- [ ] Sign off from Matt on research plan
- [ ] Participants have been identified 
- [ ] Test sessions have been scheduled

**Comment by GnatalieH** [comment]
@caw310 and @SarahKay8 I'm moving this ticket to In Progress because I'm working on the tasks to test.

**Comment by GnatalieH** [comment]
Closing out as completed after reviewing yesterday with @caw310, @SarahKay8 and @naomimarcussen.
