### ISSUE TITLE
Create prototype to test double box-shadow for focus styling

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1058]
## Description
Create prototype to test double box-shadow for focus styling

## Details
Need a working prototype to test double box-shadow for focus styling. 
Here's ticket to previous work that was done. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/654

## Tasks
- [ ] Identify a simple page to be used to test double box-shadow for focus styling
- [ ] Create a prototype
- [ ] Show to Matt, Natalie and Sarah for feedback

## Acceptance Criteria
- [ ] Prototype is ready to be used for testing 
- [ ] Can be accessed by participants easily

**Comment by caw310** [comment]
Here is some additional information about what is needed for the prototype. 

Create a prototype that contains the content from the COVID-19 vaccines at VA page.  
https://www.va.gov/health-care/covid-19-vaccine/
Required information and fields on the page: 
- VA header that links to VA.gov homepage
- Leftside navigation only needs the COVID-19 vaccines at VA section
- COVID-19 vaccines at VA information 
    - On this page & links below related to COVID-19 vaccines
    - Latest updates on booster shots and additional doses section in blue. 
    - Must have Learn when and how to get booster shots and additional doses link. 
    - Must have More information about getting your vaccine at VA with the accordions

Mural board has screenshot with additional info. https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1659041249104/a198df75672887214741df357ab90220236e9fdf?sender=u851998f98038e0f1e2da4592

COVID-19 Vaccine info page
https://www.va.gov/health-care/covid-19-vaccine/
