### ISSUE TITLE
Web components are not announcing alert and status messages without receiving focus

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1062]
## Description
We have two documented instances of our web components not announcing alert and status messages without receiving focus. This is an accessibility issue and it is also causing teams to switch back to the React versions of those components.

Instead of handling these one-by-one, I thought it would be better to handle them together. It would be good to check other components for similar issues as well.

## Details
The three components we have reports for are:
- [Segmented progress bar](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27413)
- [Select](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41813)

These issues may be difficult to check because they probably need to be tested in context on a page rather than in isolation in Storybook.

Whichever engineer picks up this task should work closely with @SarahKay8, she may have some ideas on how to resolve this.

## Tasks
- [x] Address alert and status message announcement issues for the Segmented Progress Bar and Select web components
- [x] Check other web components that could have similar issues and fix any you find

## Acceptance Criteria
- [ ] Alert and status message announcement issues have been addressed for the Segmented Progress Bar and Select web components
- [ ] Alert and status message announcement issues have been addressed for all web components likely to have problems

**Comment by k80bowman** [comment]
Could be an aria-live issue. Other components to look at include:
- progress bar
- alert
