### ISSUE TITLE
Double-box shadow for focus styling - Accessibility review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1064]
## Issue Description
We need to conduct a full accessibility review of the double-box shadow for focus styling component. See this ticket for additional information. 
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/654

Accessibility testing of the double-box shadow for focus styling with these components
Double-box shadow on white and dark background for the following components: 
- Action links (primar, secondary, reverse)✔️
- Accordion (closed and open) ✔️
- Additional info (closed and open)✔️
- Back to top✔️
- Breadcrumb 
- Button (primary and secondary)✔️
- Checkbox ✔️
- Header (desktop and mobile)✔️
- Radio button✔️
- Search input (input, button, list item)✔️
- Select box (closed, list item)✔️
- Text input (including number input)
- Text link

## Tasks
- [ ] Full accessibility review of the components is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] If necessary, discuss any accessibility issues found with the engineer who developed the component
- [ ] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [ ] Component has been reviewed for accessibility issues
- [ ] Any accessibility issues have been addressed

**Comment by SarahKay8** [comment]
Manual testing complete
