### ISSUE TITLE
Discovery: Loading fonts as part of the new CSS library

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1075]
## Description
We received this message from Tim Wright in Slack:
> Any thoughts about moving the font-face declarations from uswds into our design system - at least until we’re set up with uswds v3? Asking because I was running some performance tests and the fonts are pretty large, but we don’t really have control over how they load (specifically adding font-display: swap;). Thought it might be nice to pull that in and make some loading tweaks

Since we are currently working on the new CSS library and hope to start on the migration once it's done, I'm not sure I want to add this to Formation, but we should look into adding them to the new library. This discovery is to figure out the best way to do that, or determine if we even should.

## Tasks
- [ ] Explore adding the font declarations to the new CSS library
- [ ] Provide recommendations for if/how we should do it as a comment on this ticket

## Acceptance Criteria
- [ ] Recommendations for if/how to add fonts to the CSS library have been added to this ticket

**Comment by k80bowman** [comment]
We should go ahead and see what we can do in the Formation library, as noted in #1178, as part of this ticket as well.

**Comment by bkjohnson** [comment]
At the moment we're using the `style-dictionary` and `sass` binaries to build files that end up in the `dist/` directory. Adding font files to a directory like `src/assets/fonts` wouldn't be included in the existing build, so we essentially need to copy font files from the source directory to the build directory as part of the build process.

Since our CSS library doesn't have any JS in it, I think using a bundler like webpack, rollup, esbuild, etc. is a bit overkill even though some or all of them have functionality or plugins for copying files from a source directory to the build output directory. Here are some other options:

## Using yarn scripts to do the copying

This could result in the `package.json` looking something like:

```json
    "scripts": {
      "clean": "rm -rf dist",
      "copy-assets": "yarn clean && cp -r src/assets/fonts dist",
      "build": "yarn copy-assets && sass --load-path=../../node_modules/@uswds/uswds/packages/ src/stylesheets:dist/",
    },
```

With other scripts added for things like linting this may eventually be hard to get a complete idea of what is happening in what order, and also maintenance could be a chore later. Yarn scripts are often alphabetized so you can easily find the one you're looking for and see what it does, and alphabetization would mean that we couldn't "stack" the scripts in build order for easy sequential reading. Having to jump around the scripts dictionary to figure out what happens next sounds annoying if we're chaining multiple things together. And newer versions of yarn [don't support arbitrary `pre` or `post` scripts](https://yarnpkg.com/advanced/lifecycle-scripts).

> In particular, we intentionally don't support arbitrary `pre` and `post` hooks for user-defined scripts (such as `prestart`).

This does seem like the simplest approach and we could choose something else later if we found that it was cumbersome.

## Using a full on bash script to do everything

I _personally_ don't like bash scripts because I think the syntax is unfriendly to write/read and they are even more difficult to test. Anything more than stringing a couple of commands together seems like a pain and I'd like to not open that door if we can avoid it. I also think that future folks who get onboarded to the DST are more likely to be familiar with JS syntax than bash syntax, so sticking with the npm ecosystem seems like a good idea.

## Using [zx](https://github.com/google/zx)

I haven't tried it out but it's been on my radar. It seems like it has the benefits of being a typical NodeJS file for scripting, but easier integration for running shell commands since running bash commands in Node [is awkward and typically leads to workarounds of some kind](https://github.com/department-of-veterans-affairs/vets-website/blob/e812d5448522116e6d7d9a545cfaf1010e8e0d05/script/utils.js).

## Using gulp to do the copying

This would be a JS file, and gulp has an [API](https://gulpjs.com/docs/en/api/src) for copying files from one location to another.

---

For the next part I'll see if I can rely more on USWDS for this.

**Comment by bkjohnson** [comment]
For the `font-display: swap` declaration, we can do that but we would have to do it by declaring our `@font-face`s manually. When we use USWDS they set [`font-display: fallback;`](https://github.com/uswds/uswds/blob/8d2c7716890606e342877e916d1622eb8f1eaa0b/packages/uswds-core/src/styles/mixins/general/font-face.scss#L19), so we may want to make a feature request to have that be configurable by a setting variable.

**Comment by bkjohnson** [comment]
Another note on `font-display: swap` - [that will give us FOUT](https://css-tricks.com/almanac/properties/f/font-display/) which might not be a good user experience even if it ticks performance boxes.

**Comment by bkjohnson** [comment]
Discovery is finished.
