### ISSUE TITLE
Create a list of the a11y tests done for components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1082]
## Description
Create a confluence page with a list of the tests run when doing a11y review on a component. 

## Details
Create the confluence page from the the Accessibility Information section in the DST confluence space.  https://vfs.atlassian.net/wiki/spaces/DST/pages/2042986534/Accessibility+Information?atlOrigin=eyJpIjoiYTkwNDBlYjM1MzM0NDU1ZDhiOTgxMTg3NWIwNTkzNmQiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ 

## Tasks
- [x] Write a list of the a11y tests that are run when doing an a11y review for a new or updated component
- [ ] Share with the DST 

## Acceptance Criteria
- [ ] Page has been reviewed and shared with DST

**Comment by SarahKay8** [comment]
Ready for review

**Comment by caw310** [comment]
Reviewed with team during stand up. This is a great document! Thanks @SarahKay8

**Comment by GnatalieH** [comment]
Seriously, this checklist is awesome, @SarahKay8. It's well formatted and so easy to understand, as well as comprehensive! As Matt was saying, we'll be implementing a checklist for Components, and this is a great document to use for comparison.

**Comment by SarahKay8** [comment]
@GnatalieH @caw310 Thanks for your feedback, ladies!
