### ISSUE TITLE
Clean up Alert and Banner Storybook examples

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1089]
## Description
As part of the effort to reconcile the Alert and Banner components, we need to do some clean-up in Storybook for these two components (see #816 for context).

## Tasks
- [ ] Remove full-width Alert from Storybook and design.va.gov (if it hasn't already been removed).
    - keep the option in the component, we use it for va-banner. We just don't want to encourage its use outside of that context.
- [ ] Update the Storybook Banner examples to use language from [Content messages dictionary](https://design.va.gov/content-style-guide/error-messages/).
- [ ] Update the Storybook Banner examples to show more than just error.

## Acceptance Criteria
- [ ] Full-width alert is no longer shown in Storybook or design.va.gov
- [ ] The Banner examples use language from the Content messages directory and the examples show all major variations

**Comment by humancompanion-usds** [comment]
Let's use this example instead: 
![Audit Banner   full-width Alert (1)](https://user-images.githubusercontent.com/52176351/187243649-efddcfd7-d56d-4b73-a5ef-9cba1d694101.png)

This is a better example of "Preparing a Veteran to visit a VA facility", which is a prime use today of the banner component. I'll try to find us another example as well.
