### ISSUE TITLE
Discovery: Aligning colors with USWDS

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1090]
## Description
As part of the discovery work in #1036, we discovered that some of the colors we are using (notably the red we use for errors) does not match any colors in USWDS. We'd like to take a look at all of the colors we are using and document if there are any others that we would need to align.

## Tasks
- [ ] Document the colors we use in our Design System components
- [ ] List any colors we would need to align with USWDS and determine which USWDS colors would be closest
- [ ] Present to the rest of the DST and make a decision about how to proceed (continue using our colors or align with USWDS)

## Acceptance Criteria
- [ ] Any colors we use in DS components that are not included in USWDS have been identified and a decision has been made about whether we want to continue using them or align with USWDS.

**Comment by caw310** [comment]
We need to analyze each component and make a decision on color to be used.

**Comment by jamigibbs** [comment]
Closing this ticket based on discovery being complete but created #1172 for deciding which USWDS colors to use for each component.
