### ISSUE TITLE
Fix height issues with calc-max-height

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1093]
## Description
A problem with the calc-max-height CSS function in the Alert - Expandable component has been reported (#904 - Issue 3). 

In certain situations, the `--calc-max-height:calc(192px + 2rem);` incorrectly calculates the height.

<details><summary>Screenshot</summary>

<img width="928" alt="Locations___VA_Alaska_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/170291173-c8a05d6d-0832-45c5-8e82-d53d30763e3a.png">

</details>

This seems to happen when the `alert-body` is longer, like the "Levels high" variant in [Alaska](https://www.va.gov/alaska-health-care/locations/). It doesn't happen the Low variant (eg [Memphis](https://www.va.gov/memphis-health-care/locations/). It's only happening on the Locations List page, but not on the indivdidual facility pages. 

We use the same height calculation for this component, va-alert, and va-additional-info, so if it is breaking here it could be breaking in those as well.

## Tasks
- [ ] Determine why this issues is happening in the Alert - Expandable component
- [ ] Determine if the same problem is happening in the Alert and Additional Info web components
- [ ] Fix the problem

## Acceptance Criteria
- [ ] Height is calculated correctly in the Alert - Expandable, Alert, and Additional Info components
