### ISSUE TITLE
Repurpose background-only Alert with icon, informational for highlighting content

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1094]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
Had a fruitful discussion with @DanielleThierryUSDSVA where we decided a few things, the first of which is this new issue.

We agreed that there is a need to move away from Alerts being used to highlight information on static pages. In particular, Warning alerts don't belong outside of user feedback. We also agreed that we could use another component to sit alongside Featured Content, which is for highlighting eligibility requirements. For that I suggested we repurpose the Alert - Background-only with icon informational component for strictly this purpose. We agreed and now will determine if that's possible in Drupal. I'm going to create a new issue to track this.

## Details
Informational style of background-only with icon will be reserved for content pages and highlighting important information. We may use Warning, may not. We won't use error or success. Those will remain for inline user feedback in forms, exclusively.

## Tasks
- [ ] Update examples in Sketch
- [ ] Update examples in Storybook
- [ ] Update examples in guidance
- [ ] Clarify usage of each state (info, warning, alert, success) for background-only alert

## Acceptance Criteria
- [ ] Updated guidance
- [ ] Updated assets in Sketch and Storybook

**Comment by humancompanion-usds** [comment]
Met with Danielle and we made some plans but, unfortunately, those plans were spoiled as the CMS doesn't have the background-only Alert variation. We did come up with some additional guidelines to add to Alert, but we agree that it would be better to use the background-only Alert variation. For now, we'll just use the standard info and warning Alert styles.

New content consideration:
* If the highlighted content changes the content of the page (e.g. Debt page that Danielle cited) then use the warning variant of Alert. 
* If the highlighted content is an update to the content of the page that also appears within the page (i.e. it's repeated further down; e.g. COVID vaccine page) then use the info variant of the Alert.

**Comment by humancompanion-usds** [comment]
I've revised the title here to reflect what we need to do. Leaving the CMS aside for the moment, we need to define some components that can provide a hierarchy of content highlights. Right now we just have Alerts and Featured Content. We need other ways to highlight particular pieces of content. Alternatively, we could relax the rules around those 2 components but, I sense we'd prefer to add other mechanisms and reserve Alert and Featured Content for what they were intended for.
