### ISSUE TITLE
[Alerts] - Make alerts dismissible by default and update Sketch library accordingly

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1098]
## Description
Alerts should be dismissible by default by using the close icon in the upper right corner.

## Details
This work should include updating background only alerts with and without an icon. We have an example of a dismissible full-width Informational alert already in Sketch.

## Tasks
- [ ] Audit current [alert assets in Sketch library](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/dM89mm/p/5E24F540-2558-488C-BD6D-823F4A2F5607/canvas)
- [ ] Update background only alert symbols to include a close icon that can be overridden in case a Designer needs to make it non-dismissible
- [ ] Talk to @humancompanion-usds to find out if the close icon should be added to any alerts that are not background only

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by bkjohnson** [comment]
I think we would want to use a different prop as well so that we can preserve the default falsey behavior. Something like `permanent`.

**Comment by humancompanion-usds** [comment]
RIP Sketch. This has been done in Figma.
