### ISSUE TITLE
Prepare for usability testing of double-box focus styling 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1099]
## Description
Do prep work for usability testing of double-box focus styling. 

## Tasks
- [x] Create screener questionnaire
- [x] Post message to recruit participants with screener questionnaire
- [x] Update Calendly invite with revised dates and time slots
- [ ] Send out Calendly invite to participants who meet our criteria
- [x] Prepare note taking mural board 

## Acceptance Criteria
- [x] Conversation guide is finalized
- [x] Calendly invite updated 
- [x] Screener questionnaire responses reviewed and eligible participants identified
- [ ] Calendly link sent to eligible participants
- [x] Mural board set up
