### ISSUE TITLE
Indicate which components have been internationalized

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1101]
## Description

Some of our components (form controls and `<va-accordion>`) have translation support at the moment and some don't, including ones which should have that feature. It would be good if we had an indicator on the documentation page showing which components have this feature and for which languages.

## Details

Our components use the `component` layout. One possible solution would be to modify the layout to look for `languages` in the frontmatter, similar to how we indicate the maturity status:

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/a15ed7da8352b844ed7fc15127436711ec332d18/src/_layouts/component.html#L33-L35

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/a15ed7da8352b844ed7fc15127436711ec332d18/src/_components/accordion.md?plain=1#L6

If we could add something like this to the frontmatter:

```yaml
languages:
  - english
  - español
```

We may be able to end up with documentation like this:

![Screenshot of a proof of concept component page, where a badge is added next to the maturity indicator. There is a globe icon with the text "English, Spanish" next to it.](https://user-images.githubusercontent.com/2008881/184199833-deb535c6-b0f6-4da4-b21c-e25018c95321.png)

---

Another option could be to include this in the component's source code [using a custom doc tag](https://stenciljs.com/docs/docs-json#custom-jsdocs-tags) so that it ends up in `component-docs.json`, and then our documentation build could parse the language info out of that like we are [currently doing to build the props table](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/a15ed7da8352b844ed7fc15127436711ec332d18/src/_includes/component-docs.html#L1).

## Tasks
- [ ] Determine the best way to indicate internationalization support
    - In documentation files, or
    - In the source code, or
    - Using some kind of automated detection
- [x] Update the `component` layout
- [x] Add language indicators to the appropriate components

## Acceptance Criteria
- [ ] Component documentation indicates whether or not it has built-in internationalization

**Comment by humancompanion-usds** [comment]
Agree about the front matter being a potential place to capture the "checklist" of things that are, or are not, "done" in regards to a component. However, I'd like to extend this beyond just i18n and include a bunch of things. Therefore I'm leaning towards making a JSON data file in the _data dir of the Jekyll site that would track the state of the "checklist". Let me get cracking on a checklist draft.
