### ISSUE TITLE
Create a checklist to track how complete a component is 

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1102]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
We need a way to track how "complete" a component is in terms of the component itself, which may include functionality and the level of testing we did on it, as well as the design assets that describe it, which include Sketch, Storybook, and design.va.gov. For each of these there are levels of "completeness" that we want to track. Because we want to make this information transparent to teams using the components, so that they can have confidence in what is and isn't true about the meta-state of the component and prepare accordingly, we want to show this "checklist" on the component page itself. 

## Details

This idea is inspired by Adobe's Design System Spectrum and their documentation on components (example of [https://spectrum.adobe.com/page/button/#Design-checklist](button design checklist)).

## Tasks
- [ ] Define what would do into each part of the checklist
- [ ] Start tracking it per component either in front matter or a separate JSON file
- [ ] Design and display the information on the component pages

## Acceptance Criteria
- [ ] A way for users of the Design System to see the current "meta-state" of a component

**Comment by humancompanion-usds** [comment]
First draft. This is probably more than we even want to track but, I wanted to get all the possibilities into one place.

## Guidance

- [ ]  **Usage.** Includes a full set of examples, when, and when not, to use the pattern as well as how the pattern works. Optionally: behavior and interaction details, choosing between variations, placement, design principles, and instances of the component in production. 
- [ ] **Code usage.** Properties table inherited from component-library.
- [ ]  **Content considerations.** Plain language and information architecture considerations are called out and are clear in the design.
- [ ]  **Accessibility considerations.** Highlights a11y concerns that were explicitly found in research and/or have been incorporated into the design. Points out important implementation details if not already captured in the web-component.
- [ ]  **Internationalization guidelines.** Describes the level of i18n support.

## Code assets (Storybook, Forms System, USWDS)

- [ ]  **Defined variations.** Includes all variations (style, size, orientation, optional iconography, selection, error state, etc.)
- [ ]  **All interactive states depicted.** Includes all interactive states that are applicable (hover, down, focus, keyboard focus, disabled).
- [ ]  **All breakpoints depicted.** Mobile through desktop is shown.
- [ ]  **Internationalization.** Describes i18n attributes.
- [ ]  **Design tokens.** All design attributes (color, typography, layout, etc.) are available as design tokens.

## Visual assets (Sketch, UXPin, etc.)

- [ ]  **All breakpoints depicted.** Mobile through desktop is shown.
- [ ]  **Defined variations.** Includes all variations (style, size, orientation, optional iconography, selection, error state, etc.)
- [ ]  **All interactive states depicted.** Includes all interactive states that are applicable (hover, down, focus, keyboard focus, disabled).
- [ ]  **Form library.** Component is available in a UXPin Forms library.
- [ ]  **Alt color themes.** Works properly on dark backgrounds, Windows high-contrast mode, or OS dark themes.

## Accessibility

- [ ]  **Accessible use of color.** Color is not used as the only visual means of conveying information (WCAG 2.0 1.4.1).
- [ ]  **Accessible contrast for text.** Text has a contrast ratio of at least 4.5:1 for small text and at least 3:1 for large text (WCAG 2.0 1.4.3).
- [ ]  **Accessible contrast for UI components.** Visual information required to identify components and states (except inactive components) has a contrast ratio of at least 3:1 (WCAG 2.1 1.4.11).
- [ ]  **Keyboard interactions.** Follows WCAG 2.0 standards for keyboard accessibility guidelines and includes a description of the keyboard interactions. All interactive elements can be selected and activated using the keyboard.
- [ ]  **Content zoom tested.** Component has been tested with the display set to 400% at 1280px viewport width to ensure that the component does not have overlapping text or elements and all interactive elements still operate.
- [ ]  **Tested in screenreader.** Tested with a screen reader to ensure there are no issues with reading order, spelling, dynamic content, and interactive elements.

**Comment by caw310** [comment]
This is a really good list. Some questions that come to mind. 
- How do we want to represent this on each component page? Full list with check boxes? Percentage or number of items addressed for each component? 
- Create a separate page on design.va.gov with this list and explanation and then just check off the high level on each component page?

**Comment by humancompanion-usds** [comment]
I forgot to add the "maturity" elements:

### Maturity
* **Research.** Have we conducted, and linked to, research on this component? Are there any additional usability tests or other research that directly or indirectly covered this component?
* **Stability.** Is it in production and for how long? Are there any significant issues filed against it (how solid are the usability & accessibility?)
* **Adoption.** How many teams have adopted this component? How widely is it used across VA.gov?

**Comment by humancompanion-usds** [comment]
@caw310 - Answers to your questions:

**Tracking** comes down to 2 options for me: Airtable or a JSON data file in the design system. I'm leaning towards the latter because users of the system need to see this and having to manually dump data from airtable into the design system seems like an extra step. It also builds a dependency on Airtable and I'd rather not do that.

**Visual representation**. I'm going to create the data file and then mock this up this week. At the moment I'm leaning towards an accordion for each major section with some indicator in the drawer face of the accordion. That could be our maturity model symbols or a percentage of completeness. The contents of each accordion would be the details and description of each item in the list with or without a checkmark. I'll come up with some math to determine what percentage of checks result in a symbol or just show the percentage complete.
