### ISSUE TITLE
[Banner] - Add Banner to Sketch

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1103]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add Design System component label (such as `va-alert`)
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
Add Sketch artifacts for Banner. No audit is necessary as that has already been done. Guidance is up-to-date though examples that are real will be added to Storybook. Please use examples from this audit and, ideally, work with content folks to improve them: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1656518038765/145a2eb03b4b7ee1e3f8cd7db1f3a8af7572e5bb?sender=u9ae4d29a0ed5c3d2753a7824

## Details
I believe @k80bowman created an issue for Storybook updates for Banner. @seanasewell just did Banner - Maintenance which can largely be copied. However, the informational style exists for Banner in addition to warning.

## Tasks
- [ ] Create designs for component in Sketch
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack
