### ISSUE TITLE
[Pattern] Help users to know how their information is updated

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1109]
## Description
This ticket is continuing the work started in #702. 

## Details
[Here is a link](https://www.sketch.com/s/789c144c-98c6-4350-b9d5-9acb6112069d/a/ag3xoJD) to the flow diagram for this pattern. I believe two patterns that were prioritized during the workshop -- Help a user to... "Review their changes" and "Understand the impact of changing their information" -- can be be resolved under one umbrella pattern: "Help a user to...Review and update information".

## Tasks
- [ ] Write pattern documentation for design.va.gov -- use the flow diagram for guidance and include it in the documentation
- [ ] Coordinate with Content specialist for Content considerations
- [ ] Coordinate with a11y specialist for accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Pattern documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
This is 1 of 3 high priorities from DSC.

**Comment by humancompanion-usds** [comment]
Next step is for me to reach out to Robin about this.
