### ISSUE TITLE
Add analytics tracking for new web components to vets-website

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1110]
## Description
We had several new web components that did not have analytics tracking enabled through vets-website. We need to set that up by adding the new tags from the [data dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics-data-dictionary) to [component-library-analytics-setup.js
](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js).

## Details
[Analytics request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45510)

## Tasks
- [ ] Add tags from the data dictionary to vets-website
- [ ] Once this is merged, find a URL for each and provide to analytics team in the ticket linked to above for the analytics team to test
- [ ] Once all analytics are working, we can close this ticket

## Acceptance Criteria
- [ ] Analytics have been enabled and verified for new web components listed in the analytics request ticket

**Comment by k80bowman** [comment]
I've created a couple of draft PRs, one in `vets-website` to add the analytics tracking and one in `component-library` to add analytics details. I still need some info from the analytics team to finish this work, though. I have a meeting to discuss this with them on Monday.

**Comment by k80bowman** [comment]
Meeting moved to Tuesday.

**Comment by humancompanion-usds** [comment]
@k80bowman - Given that we are doing other analytics work soon (https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1175) perhaps we could do this at, or around, the same time?

**Comment by k80bowman** [comment]
Potentially, it depends on when I get all the analytics information I need for this work from Michelle. The GA4 work can be completed without waiting on that.

**Comment by k80bowman** [comment]
@jamigibbs I have added the analytics details for va-link to my draft PRs (linked above). I did not add any details for va-banner, we still need the details from Michelle for the banner close button click. I asked for those in the analytics ticket and let her know that I was passing this work off to you.

**Comment by humancompanion-usds** [comment]
Jami to do QA on this.

**Comment by Andrew565** [comment]
Approved.
