### ISSUE TITLE
Move to deprecation phase 2 - RadioButtons React component

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1114]
## Description
**This issue should not be worked on until September 29th, 2022**

We need to move the RadioButtons React component to phase 2 of the [deprecation process](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components).

This means we need to check to see if the component is still being used in vets-website. If it is, we need to update the ESLint rule to be an error instead of a warning, remove the Storybook story for the component (but leave it in the component-library repo), create a ticket for following up with the teams still using the component, and announce that in 6 weeks/3 sprints we will be deprecating the component completely and advise teams to upgrade to the web component ASAP.

If it is no longer being used, we can remove the ESLint rule altogether and remove the component from the component library.

## Tasks
- [ ] Check if the component is still being used in vets-website
- [x] If it is...
    - [x] Set ESLint rule to an error
    - [x] Remove deprecated component from Storybook (but keep the component in the component-library repo)
    - [x] Create a ticket for advancing to [deprecation phase 3](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components) in 6 weeks.
    - [ ] Announce full deprecation of the component in 6 weeks
- [ ] If it is not...
    - [ ] Remove the deprecated component from the component library and Storybook
    - [ ] Remove the ESLint rule

## Acceptance Criteria
- [ ] Deprecated component has either been removed entirely (if no longer in use) or moved to the next stage of the deprecation process.

**Comment by k80bowman** [comment]
We will need to resolve #1096 before we can work on this ticket.
