### ISSUE TITLE
[Pattern] Help a user keep a record of submitted information

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1121]
## Description
In a recent DSC workshop on patterns, two people voted to include the following:

- Help a user to download a copy of a form they just completed

This isn't high-priority, but worthy of getting on the DST backlog (per Matt). This pattern was also identified and voted on in a workshop with VFS teams.

## Tasks
- [ ] Write or update pattern documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Pattern documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
Given that USWDS is working on this I'm inclined to wait to see what they have to say about it. It also only received 2 votes.

**Comment by humancompanion-usds** [comment]
The USWDS pattern is now available:
https://designsystem.digital.gov/patterns/complete-a-complex-form/keep-a-record/

**Comment by allison0034** [comment]
FYI @shiragoodman this is something I am helping DS with.

**Comment by humancompanion-usds** [comment]
We had a duplicate issue here (issue #197) that we were using for tracking. We just published this pattern:

https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information

Let us know if you have any updates to recommend.
