### ISSUE TITLE
[Pattern] Ask users for files

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1122]
## Description
This pattern was recently identified and voted on in DSC and VFS workshops on patterns. Here is the original request:

- Help a user to upload documents (beware of "scan", think about "convert")

## Details
The Content team has approved the button label "Upload file" rather than "Upload document" in order to have it apply to more use cases, such as uploading an image. In addition, we don't encourage batch file uploads on VA.gov because they are not mobile friendly and are prone to errors. We should be mindful of these details when wording our pattern title and the documentation.

## Tasks
- [ ] Write or update pattern documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Pattern documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
We have this: https://design.va.gov/patterns/ask-users-for/files

* Needs a When to use this pattern
* This should get updated to remove the layout details when we have File upload added as a component.

**Comment by GnatalieH** [comment]
A part of me thinks this pattern should live as "Help users to...upload a file". I realize the "Ask users for..." section _does_ deal mostly with forms-related stuff.

**Comment by humancompanion-usds** [comment]
Made final changes and deployed.
