### ISSUE TITLE
Discovery: Can consumers hook into our analytics event

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1123]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Details
_Stub, add more detail_

Is it possible for app teams to add more data to our analytics events that will then get picked up by the site-wide handler in `vets-website`?

## Tasks
- [ ] 

## Acceptance Criteria
- [ ]
