### ISSUE TITLE
Separate design library symbols and designer facing components into two files

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/vets-design-system-documentation#1124]
## Description

As a designer, I want to be able to quickly scan what symbols and patterns are available to me so that I can use them in my working design file. I would also like to be able to copy those symbols and paste them directly in my working design file. 

As someone who manages the design system Sketch library, I want to be able to lock the file so that it can only be accessible by a few people. This will limit the amount of accidental changes occurring in the design system Sketch library file.

## Tasks

- [X] Create a new designer facing component file 
- [ ] Create a page for each component in our design library  
- [ ] Insert component from design system library into corresponding component page ensuring that the styles are not accidentally copied over into local library from the design system library
- [ ] Create a list of all the new URLs for the new component page and add them below
- [ ] Update design.va.gov with new component page URLs
- [ ] Lock design system pattern library file for anyone outside of DST

## Acceptance Criteria

- [ ] Design library symbols and designer facing components are separated into two files
- [ ] design.va.gov has been updated to reflect new component page URLs
- [ ] Design system pattern library is locked for anyone outside of DST

**Comment by GnatalieH** [comment]
@seanasewell for posterity's sake, I wanted to ask you a couple of questions:

- Are there any considerations we should take in terms of finishing this ticket and planning the alignment of the VA Sketch library with the USWDS library? I know that separating our components from the symbols file is one step in the right direction. Anything we should note as we move forward?
- I know we will need to plug in new Sketch URLs on design.va.gov Component pages as this work is completed. Is there anything else we should be aware of that might break the Designer experience as they work with our documentation and library?
- In your opinion, what is the most effective way to train existing and new Designers how to use the soon to be split component and library files? They will still be able to access their symbols if they've added the VA Pattern library, that won't change. But now we will have a Component file (using VA Pattern library symbols) and Designers can open that up to copy and past components without having to worry about accidentally editing the master symbol file. Amirite?

Thanks Sean! CC @humancompanion-usds

**Comment by humancompanion-usds** [comment]
This issue has been inactive for over two years and appears to be superseded by more recent events and updates. To keep our backlog manageable and relevant, we are closing this issue. If you believe this issue is still relevant and requires further attention, please feel free to reopen it or create a new issue with updated details.

Thank you for your understanding and contributions!
