### ISSUE TITLE
[Pattern] Help users to stay informed of their application status - Audit

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1128]
## Description
Audit of  application status pattern. Identify as many instances of this pattern in use on VA.gov and share with the Design System Team.

## Tasks
- [ ] Work with engineers and the Governance team to find examples of this type of pattern
- [ ] Use the [Test User Dashboard](https://depo-platform-documentation.scrollhelp.site/developer-docs/test-user-dashboard-guide) to complete education, healthcare, and disability applications; capture screenshots from these applications
- [ ] Add screenshots of pattern usage examples to a Mural board, including links to sources
- [ ] Gather feedback on findings from the DST (Carol can help schedule a session for this). Questions to ask include:
    - Are any changes to current implementations needed?
    - Are there any variations that can be consolidated?
    - Are there any accessibility considerations that should be taken into account as part of the design?
- [ ] Respond to feedback from DST
- [ ] Add link to Mural board as a comment in this ticket and to the pattern design ticket if applicable

## Acceptance Criteria
- [ ] Pattern usage examples have been collected on a Mural board and a link to the board has been added to this ticket
- [ ] Audit findings have been shared with the DST and all feedback has been addressed.

**Comment by GnatalieH** [comment]
Here is the [Mural board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1661355714382/20b034bd9720885de162064c435f5a86f4222449?sender=u851998f98038e0f1e2da4592) I created for this audit. Screenshots to be added.

**Comment by taylojill** [comment]
@humancompanion-usds and @GnatalieH  I am currently grabbing screenshots for the application status pattern.

**Comment by caw310** [comment]
Will carry over into the next sprint for review and sign off.

**Comment by GnatalieH** [comment]
[Here is the Mural board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1661355714382/20b034bd9720885de162064c435f5a86f4222449?sender=u851998f98038e0f1e2da4592) for this audit.

**Comment by GnatalieH** [comment]
Closing as the audit portion of this work is complete.
