### ISSUE TITLE
Create shared search library

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1129]
## Description
There was a request for Experimental Design [Search Result Card] that was discussed in the 8/05/22 DSC meeting. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1085

Action items from that meeting were:
- Create template for Search shared library in Search 
- Set up time with Aslan to talk through how they create things in Sketch. 
- Document shared libraries 

## Tasks
- [x] Create template for Search shared library in Search
- [x] Set up time with Aslan to talk through how to create things in Sketch
- [x] Draft documentation on share libraries

## Acceptance Criteria
- [x] Shared search library created
- [x] Had meeting with Aslan to talk through how to create things in Sketch
- [x] Documentation written on shared libraries

**Comment by GnatalieH** [comment]
@humancompanion-usds was the intention of this ticket to create a shared library with items that relate to search, only? I don't think I was in the meeting where this ticket was discussed. Because, there are a couple of potentially reusable patterns that stem from the [Experimental design request](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1085) created by @jcklpe, and one pattern is not directly related to search, rather the facility locations page.

**Example 1: facilities search results card**
![image](https://user-images.githubusercontent.com/88347129/188931596-36300a70-8e32-4d8a-98ef-93249d20e970.png)

I have created this asset in Sketch.

**Examples 2: facility locations page cards**
![image](https://user-images.githubusercontent.com/88347129/188931748-2553dc5a-f91e-40ee-be58-2c1e60e0cc96.png)

I have not yet created this asset because I wanted to make sure that we want to include it in the library, if the library is meant for search-specific items. This is more of a Facilities-specific pattern. It still could be useful for other Designers on the Facilities team.

**Comment by humancompanion-usds** [comment]
@GnatalieH - Anything related to Search could be included, regardless of what kind of page it appears on. Facilities patterns are germane here as examples of search results on VA.gov. Aslan's request was the use case that generated this response so starting with those is a great first step.

**Comment by GnatalieH** [comment]
Thanks @humancompanion-usds. I referenced the Experimental ticket, chatted with Aslan yesterday and got his clarification. I just wanted to make sure we were all on the same page. Thanks!

**Comment by GnatalieH** [comment]
[Here is a link](https://www.sketch.com/s/ab0f611b-c15c-42c4-ab71-1158ff6e01c6) to the Sketch Search library. FYI @humancompanion-usds and @jcklpe

**Comment by humancompanion-usds** [comment]
This looks good. I have some comments:

* Do we need to create artboards for Symbols? Does Sketch do that automatically when you generate a Symbol? I ask because I'm thinking that we could use a plugin to keep symbols organized and I'm wondering if it does that if they are on artboards or not.
* We should include Aslan's contact info (email address) and perhaps establish a cadence for discussion, rather than review. Perhaps every Friday afternoon? We should talk to him about when he can put aside some time. More importantly, I don't want that to seem like a review. Contributors don't really have to present the work, just walk Aslan through it. 
* We probably want folks to leave their name, team name, and email address somewhere on their artboards, or near them, and perhaps a date so we know who contributed what and when. We'll probably need to reach back out to them to learn more about the component at some point.
* Let's tighten up the naming and pages. I see the symbols are "Search patterns". Are these patterns or components?

**Comment by GnatalieH** [comment]
@humancompanion-usds Sketch [describes symbols](https://www.sketch.com/blog/2022/01/31/create-symbols-sketch/) as a special kind of artboard, so regarding your first bullet point, the answer is "yes". I'm working on the other feedback items you listed, thanks!

**Comment by GnatalieH** [comment]
@humancompanion-usds I have addressed your feedback and updated the Sketch file accordingly. I set a meeting for this Thursday with you, me, and @jcklpe, as I couldn't find an earlier day to meet that worked for everyone. Thanks.

**Comment by humancompanion-usds** [comment]
@GnatalieH - I added a PR that adds your contribution readme as well as additional documentation:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1209

Once you've reviewed that and I push it out we can simplify the README to point folks there and then list Megan's contact info. I think we can add our Slack channel as well just as a back-up. Thanks.

**Comment by humancompanion-usds** [comment]
Also, I'd like to add search results for find a form and the default VA.gov search. Then we can close this out.

**Comment by GnatalieH** [comment]
@humancompanion-usds I approved your PR, and will add the find-a-form results to the library. By default VA.gov search, do you mean the global search in the header? Thanks.

**Comment by humancompanion-usds** [comment]
@GnatalieH - We need to add search results. From this page: https://www.va.gov/search/?query=prescriptions&t=false these results:

![Screen Shot 2022-09-21 at 11 54 28 AM](https://user-images.githubusercontent.com/52176351/191552466-e5b5f5fc-496c-4906-87b0-82c8276f30b7.png)

Also, the README should be revised.

**Comment by GnatalieH** [comment]
@humancompanion-usds OK thanks for that example. Now I see what you mean. I'm on it now.

**Comment by GnatalieH** [comment]
Okey dokey, I think I made all of your requested updates, @humancompanion-usds:

- Updated [Readme page](https://www.sketch.com/s/ab0f611b-c15c-42c4-ab71-1158ff6e01c6/a/dl8J2b9). FWIW, I couldn't find any way of adding a hotspot to an external ink in Sketch.
- Added a generic search result symbol near the bottom of the [Search results page](https://www.sketch.com/s/ab0f611b-c15c-42c4-ab71-1158ff6e01c6/v/xe1OJW/a/OmDoMZm/r/dqYaj9). I only used one result so Designers can add and remove results as needed. If I used two results in the symbol, a Designer wouldn't be able to hide one.

If these updates look good to you I'll close out the ticket. Thanks!

**Comment by humancompanion-usds** [comment]
Looks good. Almost there. Two things to consider:

1. We might want to make the link go specifically to https://design.va.gov/about/for-designers/design-libraries#contributing-to-a-shared-library There is a bit about the maintainer before that and I don't want folks to miss the part that is most relevant to them.
2. We might want to put each variation within Search results onto a separate artboard. I say this because we've essentially told contributors to create an artboard per symbol and each of those variations of search result are their own symbol. That would make it easier for the maintainer to just copy the contribution onto the page for a component. If that sounds good to you good ahead and proceed with that change and if not let's discuss over Slack.

Final steps are for Carol or I to announce the existence of this new library to VFS teams and to close the issue Aslan opened, letting him know this now exists.

**Comment by GnatalieH** [comment]
@humancompanion-usds I made the changes you suggested, thanks. I placed each variation of search results on its own artboard, except when there is a sub-variation (facility locator card with and without an alert, for example) I put both symbols on the same artboard. It seems better organized than putting everything on a unique artboard, but I can do that if you'd like.

**Comment by humancompanion-usds** [comment]
Looks great @GnatalieH - thanks!
