### ISSUE TITLE
Add slot documentation for components

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1136]
## Description

None of our components have any specific documentation on what slots are available. We should add that to Storybook and design.va.gov

## Details

[Slack discussion](https://dsva.slack.com/archives/G01BJ3ESXL4/p1660840993097779) on how to [document slots in Stencil](https://stenciljs.com/docs/docs-json#slots).

## Tasks
- [ ] Update components to use the `@slot` docComment tag
- [ ] Parse out slot information from `component-docs.json` in Storybook
- [ ] Parse out slot information from `component-docs.json` in design.va.gov

## Acceptance Criteria
- [ ] Components with slots have documentation on which slots are available and what they are used for

**Comment by humancompanion-usds** [comment]
This issue has been inactive for over two years and appears to be superseded by more recent events and updates. To keep our backlog manageable and relevant, we are closing this issue. If you believe this issue is still relevant and requires further attention, please feel free to reopen it or create a new issue with updated details.

Thank you for your understanding and contributions!
