### ISSUE TITLE
Improve build and tests scripts in component-library

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1138]
## Issue Description

At the moment, our `component-library` has some scripts that could be better. The `build` script uses babel as part of a "homemade" way of building the files, and the `test` script uses a combination of `webpack` and babel. It would be easier to maintain these if they both built the code the same way.

Additionally, there are lots of dependencies related to testing. Some of them include:

- babel
- chai
- enzyme
- karma
- mocha
- sinon

See if we can reduce these dependencies as well

---
## Tasks
- [ ] Investigate how the `build` and `test` scripts work
- [ ] Find ways to unify the processes
- [ ] Try to reduce testing dependencies

**Comment by caw310** [comment]
@Andrew565 @jamigibbs - can we close this?

**Comment by jamigibbs** [comment]
@caw310 We still have components in the react-components package but we are making solid ground on deprecating them so this work probably won't be necessary any more.
