### ISSUE TITLE
Decide which USWDS colors to use for VA.gov Design System components

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1172]
## Description
As part of the discovery work in #1090, we observed that some components could be better displayed using the closest mapping USWDS color, or, its corresponding USWDS component color.

The purpose of this task is to analyze each component and make a decision on which colors should be used.

## Tasks
- [ ] Review all of the existing web components and determine which USWDS color(s) should be mapped to that component.
- [ ] Document which USWDS color(s) should be assigned to each component.

## Acceptance Criteria
- [ ] A decision has been made for each component for which colors to use (the existing VA.gov color, the closest mapping USWDS color, or the corresponding USWDS component color).

**Comment by caw310** [comment]
Google sheet with decisions on addressing color differences. 
https://docs.google.com/spreadsheets/d/1Joslf0M_ivuFol9Boy8QTQfTW9skyLQIcwKccNWrVkw/edit?usp=sharing

**Comment by GnatalieH** [comment]
Hi @humancompanion-usds. Late last week I finished documenting the color mappings from v1->v2 in our [spreadsheet](https://docs.google.com/spreadsheets/d/1Joslf0M_ivuFol9Boy8QTQfTW9skyLQIcwKccNWrVkw/edit#gid=0). I highlighted the colors that were different from what I chose. I agree with the USWDS conversions in almost all of the cases, but added notes where I think further discussion is warranted.

**Comment by GnatalieH** [comment]
I'd like to close this out today if possible. Is that OK @humancompanion-usds?

**Comment by caw310** [comment]
As discussed on Friday during standup, Natalie will create a new tab in the google sheet with color breakdown for the components we are migrating in Q4 2022 which are: radio button, memorable date, text input and banner.
