### ISSUE TITLE
Google Analytics 4 setup

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1174]
## Description
Configure our [Google Analytics code in vets-website
](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js) to send data to both GA3 and GA4. Use one or two of our components to test that the connection is working.

## Details
- We want to make sure that both GA3 and GA4 are receiving the data for now. Eventually we will remove the GA3 code, but not yet.
- Please reach out to @michelle-dooley with any questions and for help confirming that the connections are working.
- The Analytics team has created [a table with information about the GA4 mappings](https://docs.google.com/spreadsheets/d/1XDceQQVK6IGOl8R1OzhbncSc1Hrs37IEyQblW_Spk-Y/edit#gid=1403781092) for our components. This information, and more, is also available in their [Confluence docs](https://vfs.atlassian.net/wiki/spaces/AT/pages/2193686721/Component+System+Library+Updates).
- We will add the mappings for the rest of the components once this initial work is done.

## Tasks
- [ ] Configure our analytics setup in vets-website to send data to both GA3 and GA4. Set up mappings for one or two components to test.
- [ ] Confirm with @michelle-dooley that the connections are working

## Acceptance Criteria
- [ ] The component library analytics setup in vets-website sends analytics data to both GA3 and GA4.

**Comment by humancompanion-usds** [comment]
Jami is seeing the information correctly in the analytics dashboard.
