### ISSUE TITLE
Add GA4 component mappings

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1175]
## Description
Once the setup in #1174 is complete, we need to add the GA4 mappings for the rest of our components to [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js) in vets-website.

## Details
- Please reach out to @michelle-dooley with any questions and for help confirming that the connections are working. 
- The Analytics team has created [a table with information about the GA4 mappings](https://docs.google.com/spreadsheets/d/1XDceQQVK6IGOl8R1OzhbncSc1Hrs37IEyQblW_Spk-Y/edit#gid=1403781092) for our components. This information, and more, is also available in their [Confluence docs](https://vfs.atlassian.net/wiki/spaces/AT/pages/2193686721/Component+System+Library+Updates).

## Tasks
- [ ] Add GA4 component mappings to vets-website
- [ ] Confirm with @michelle-dooley that mappings are working

## Acceptance Criteria
- [ ] GA4 is receiving data for all of our current components

**Comment by jamigibbs** [comment]
GA4 planning reference spreadsheet: https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=2089299676

**Comment by caw310** [comment]
Closing as we're breaking up the GA4 component mapping into smaller batches of components.
