### ISSUE TITLE
Discovery: Catalog differences in functionality and structure between our web components and USWDS components

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1177]
## Description
[This airtable](https://airtable.com/appF4FJKBeNVNGrlm/tblRMaKxvyPn6F0qe/viw6WoPXgF8g0sNFy?blocks=hide) has a catalog of our components and their USWDS counterparts. We need to go through that list and determine how each of our web components differs from its USWDS counterpart in terms of functionality and structure.

This comes out of a discussion about whether or not we should be using the JS from USWDS in our web components. It's looking increasingly like it might be better to use our JS instead of trying to fit their JS to our components, but we need to understand what the differences are before we make a decision.

## Details
I've added a column to the Airtable for recording the differences between the VA web component and the USWDS component. We only need to look at our web components vs. their equivalent components, we do not need to analyze our React components.

## Tasks
- [ ] Analyze the differences in structure and functionality between our web components and the equivalent USWDS components
- [ ] Add this analysis to the airtable column labeled "Differences between VA and USWDS"
- [ ] Discuss the analysis with the DST

## Acceptance Criteria
- [ ] Analysis of structural and functionality differences between our web components and their equivalent USWDS components has been added to the airtable.
- [ ] Analysis has been discussed with the DST

**Comment by k80bowman** [comment]
Completed analysis of components @humancompanion-usds determined that we would want to adopt from USWDS ([airtable](https://airtable.com/appF4FJKBeNVNGrlm/tblRMaKxvyPn6F0qe/viwNb9nb3qUoZt6Vm?blocks=hide)). Will move on to components we might want to adopt from USWDS next.

**Comment by k80bowman** [comment]
Closing this. We decided separately that we will not be using the JS from the USWDS. More of this type of analysis will be completed as we work to align our components with theirs.
