### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1178]
## Description
[Ensure text remains visible during webfont load
](https://web.dev/font-display/?utm_source=lighthouse&utm_medium=devtools)

## Details
Looks like we can add ```font-display: swap;``` to https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/base/_b-font-faces.scss and potentially save 2.4 seconds of loading time.

## Tasks
- [ ] Add font-display: swap; as detailed above.
- [ ] Determine if error goes away, or not

## Acceptance Criteria
- [ ] Google Lighthouse report on homepage stops reporting "Ensure text remains visible during webfont load"

**Comment by humancompanion-usds** [comment]
This is actually a duplicate of issue #1075 so closing in favor of that work.
