### ISSUE TITLE
Discovery: measuring component usage on VA.gov

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1179]
## Description
We'd like to find a way of measuring component usage on VA.gov itself, rather than only in the code the way we measure it now.

## Tasks
- [ ] Identify different ways of achieving this goal and research them
- [ ] If any are successful, write up issues to formally implement them

## Acceptance Criteria
- [ ] Either it has been determined that this is not possible or a way has been identified and issues for implementation have been created

**Comment by k80bowman** [comment]
The first idea I’ve looked into is searching the rendered HTML pages that go out for the daily deploy for our components. Unfortunately what I found is not all that promising.
- First, we can definitely check for web component usage on the static pages. We can search the rendered HTML files for our web component tags.
- We probably won’t be able to find the React components on the static pages. The React code is rendered on the client and many of our React components don’t have unique identifying classes or ids
- We would only be able to use this method to find web components that appear on the home pages for each application. Again, the React code is rendered on the client (though for performance reasons it really should be rendered on the server, but that’s a whole other can of worms), so there is no way for us to search a rendered version of application pages in order to find our components.

**Comment by k80bowman** [comment]
The second idea I've looked into is using Cypress to check site pages for our web components. Again, the React components are going to be more difficult because not all of them have unique identifying classes or IDs (though we could add those if we want). I spoke with Peter Hill about this idea briefly and he thought it could work.
- Scanning the static pages should be relatively easy. I say _relatively_ easy because this still requires setting up Cypress tests that will scan for each of our components and count them. But, the QA team already has code that uses the sitemap to understand, divvy up, and inject Axe into each of the static pages for a11y testing and we could take advantage of that.
- Scanning the app pages will be more difficult. Peter is going to think about this a little more and see if he and/or his team have any ideas on how we could easily accomplish this. It would probably be good to take a look at some of the app Cypress tests to see if they have any tricks we could use.

**Comment by k80bowman** [comment]
I heard back from the Peter Hill on the QA Standards team. They discussed my idea to use Cypress and thought it might be a bit clunky and could break a lot. We definitely don't want to implement something that is going to need a lot of maintenance. They recommended using Google Analytics, which @humancompanion-usds and I have discussed previously as well. This may be our best option, but I want to check with the analytics team and get their perspective as well.

If we did implement this, we would need to make sure that each of our components is firing an analytics event on component load. Right now some of them do, but others only fire on interaction.

**Comment by k80bowman** [comment]
I did some discovery on using Google Analytics to track this. It is possible, as can be seen [here](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-pages/a50123418w177519031p176188361/_u.date00=20220801&_u.date01=20220831&explorer-table.secSegmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22loading-indicator-displayed%22,0%5D%5D/) (will need GA access to view that link). This shows pages that rendered the loading indicator component over the month of August. I used the loading indicator as an example since it is the only component we have right now that fires a GA event when it appears on the page.

There is a limitation here, though, and it shows up especially well with the loading indicator. There are lots of applications that use the loading indicator (both the React and web component versions), but the GA data only shows two of them. So if we use the GA data, we would definitely need to look at it alongside the component usage data we already collect. Together they give a more complete picture of how our components are used, but I would not look at the GA data in a vacuum.

Other limitations I can think of are:
- If there is an application that is not used frequently. If we look at the GA data month-to-month, that might not cause too many issues, but if we increase the frequency we could have situations where it looks like an app has added a new usage of a component when really it has been there for a while, it's just no one loaded the page that contains it during the previous time period.
- We are not sending the component name to GA and our web components and React components use the same event labels, so we currently have no way just from GA of knowing if what we are seeing is a React component or a web component. This may not matter much long-term, and we could potentially find a way of fixing this. This information would be helpful in prioritizing our deprecation efforts, however.

I've added information about our analytics events to the Design System Airtable and created a [view](https://airtable.com/appF4FJKBeNVNGrlm/tblRMaKxvyPn6F0qe/viwcoAfcKeIo9vjot?blocks=hide) to more easily see it. Breaking that down a bit, we can see:
- 17 components currently have analytics events that are fired and recorded in GA
- Only one component currently has an event that is fired when it appears on the page
- 8 of our components have events that are firing, but not being captured by GA (we have a ticket where we are working through these currently to add them to GA)
- 13 of our components are not firing any analytics events at all

In order for this to work, we would need all components in use on the site to have analytics events that are fired when the component appears on the page and recorded in GA. This work would not be terribly difficult on our end, but could take quite a bit of time given the reduced capacity of the Analytics and Insights team.

**Comment by k80bowman** [comment]
@humancompanion-usds it looks to me like our best option would be to set up Google Analytics to capture data on our components and use that alongside the data we currently collect on component usage in the `vets-website` and `content-build` repositories. Are there any other questions I can answer about this? Are there any other avenues you can think of for me to research?
