### ISSUE TITLE
Form components error messaging - Audit

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1182]
## Description
Conduct an audit of the error messaging used with form components on VA.gov. Identify as many different types of error messages in form components in use on VA.gov as possible and share with the Design System Team.

## Tasks
- [ ] Work with engineers and the Governance team to find examples of form component error messaging
- [ ] Add screenshots of component usage examples to a Mural board, including links to sources
- [ ] Present findings to the DST
- [ ] Work with the DST to determine what steps will be necessary to bring error messaging into alignment
- [ ] Add link to Mural board as a comment in this ticket and to the component design ticket if applicable

## Acceptance Criteria
- [ ] Error messaging examples have been collected on a Mural board and a link to the board has been added to this ticket
- [ ] Audit findings have been shared with the DST and a plan to move forward has been created.

**Comment by bkjohnson** [comment]
This is related to an existing issue if not a duplicate: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/386

**Comment by k80bowman** [comment]
I'd say they're related, but this is focused on design system components while #386 is focused on the forms library, where there may be less flexibility with error messaging.
