### ISSUE TITLE
Discovery: What breaks if we switch from a 768px breakpoint to a 640px or 880px breakpoint

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1183]
## Description
As part of our work bringing the USWDS grid properties into the new CSS Library, we discovered that we need to use their breakpoints rather than our won. However, we use a 768px breakpoint, while the closest options offered by USWDS are 640px and 880px. We need to find out where the 768px breakpoint is being used and whether (and/or how badly) using 640px or 880px would break things. This includes our own design system components and other frontend applications. This may require reaching out to app teams and working with them.

As we do this discovery, it would be good to add screenshots with links to the sources to a Mural board.

## Tasks
- [ ] Find examples of areas of VA.gov that use the 768px breakpoint
- [ ] Find out what would happen if those areas were changed to the 640px or 880px breakpoints. Take screenshots and add those and links to a Mural board
- [ ] Present results to the DST

## Acceptance Criteria
- [ ] We have a good understanding of what would break and how if we switched to using a 640px or 880px breakpoint

**Comment by humancompanion-usds** [comment]
We decided to go ahead and add the 640px breakpoint and leave 768px for some period of time. I did do some digging into analytics to see what screen resolutions users have. Results below.

### Desktop usage
<img width="851" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWw0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99939643f3fc0448db64c4006e7910d11f6a2ef5/Screenshot%202024-04-19%20at%209.19.26%E2%80%AFAM.png" alt="Screenshot 2024-04-19 at 9.19.26 AM.png" />


### Mobile usage by screen resolution
<img width="798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVI0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a94c8462a78c9b956effbfe366996b47daac6869/Screenshot%202024-04-19%20at%209.14.12%E2%80%AFAM.png" alt="Screenshot 2024-04-19 at 9.14.12 AM.png" />

**Comment by humancompanion-usds** [comment]
The USWDS supports the following breakpoints:

$theme-utility-breakpoints: (
  'card':              false,   // 160px
  'card-lg':           false,   // 240px
  'mobile':            false,   // 320px
  'mobile-lg':         true,    // 480px
  'tablet':            true,    // 640px
  'tablet-lg':         false,   // 880px
  'desktop':           true,    // 1024px
  'desktop-lg':        false,   // 1200px
  'widescreen':        false,   // 1400px
);

### Recommendations

1. Potentially turn on tablet-lg (880px) as 30% of our users would get the 880px breakpoint at landscape view on their mobile or tablet. 
2. Targeting the desktop-lg 1200px breakpoint doesn't seem necessary based on this data but may be necessary from a design perspective.
3. Potentially turn on the widescreen breakpoint in future (1400px) as that would give designers the ability to change the design for 26% of users and the gulf between 1024px and 1400px is significant.
