### ISSUE TITLE
Discovery: What do we do about design.va.gov if we’re consuming a USWDS component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1200]
## Description
Research what we could do about design.va.gov if we are consuming USWDS components. 
Do we point to their guidance directly? 
How do we handle documentation? 

## Tasks
- [ ] Research options for how we handle component guidance when using a USWDS component
- [ ] Write up options of how we might handle guidance
- [ ] Present options to the DST for discussion 

## Acceptance Criteria
- [ ] Research findings and options are posted in this ticket
- [ ] Findings are presented to the DST

**Comment by humancompanion-usds** [comment]
![IMG_7750.jpg](https://images.zenhubusercontent.com/623c98bb27734da1243c0bb5/c72b4d13-faf5-4832-aca9-0edaed7b2026)

@GnatalieH - Above is the rough sketch I did. To recap, we resolved to:

* Add USWDS v3 components to our guidance once we're through the pilot. Radio button would be the first of these.
* Add USWDS v3 examples and guidance within each existing section for components. This would start by pointing at the appropriate sub-section of the USWDS guidance and then right below that list any diffs or additions from their guidance rather than copying and repeating what they've said.
* We need a mock-up of what the future state could look like when the diff from our guidance to USWDS is very light. Let's see how odd that might look and determine if there is an alternate design.

**Comment by GnatalieH** [comment]
Thank you, @humancompanion-usds, this is perfect.

**Comment by GnatalieH** [comment]
@humancompanion-usds what is "v2" in your sketch? We have the VA radio button and its variations and we have the USWDS radio button and its variations. I'm not sure what v2 is referring to. Thanks.

**Comment by GnatalieH** [comment]
[Here is a link](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1269#issuecomment-1384522148) to my comment in the Radio button documentation ticket which describes the process of combining content from VADS and USWDS documentation sites and my thoughts about how to move forward.

**Comment by caw310** [comment]
Closing as we have identified how to document converted components.
