### ISSUE TITLE
Remove 6 unused React components

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1205]
## Description
The following React components are no longer used in `vets-website` and can be removed from the `component-library` repository:
- HelpMenu
- IconHelp
- AcceptTermsPrompt
- PrivacyAgreement
- Banner
- CollapsiblePanel

This work would complete part of department-of-veterans-affairs/component-library#333

## Details
Before removing the components, double check the component usage report and the vets-website repository to make sure no one has added a usage of these components.

Delete the files for the components in the react-components package, the Storybook file in the storybook package, and any references to these components in the `additional-docs.js` file in the storybook package.

It would be good to have separate PRs for each of these removals, but we should only bump the package one major version for all six (instead of one major version each). Just as Brooks did with the removals of the [Date](https://github.com/department-of-veterans-affairs/component-library/pull/502), [NumberInput](https://github.com/department-of-veterans-affairs/component-library/pull/528), and [MonthYear](https://github.com/department-of-veterans-affairs/component-library/pull/527) component, all PRs should have the `major` label attached to the PR, but only one of the PRs should have a version bump.

## Tasks
- [ ] Remove the React components listed above from the react-components package
- [ ] Remove the Storybook stories for the React components listed above
- [ ] Remove references to the components above from the storybook `additional-docs.js` file

## Acceptance Criteria
- [ ] All six React components listed above have been removed from the `component-library` repository.

**Comment by bkjohnson** [comment]
`Banner` and `CollapsiblePanel` are already removed. https://github.com/department-of-veterans-affairs/component-library/pull/478

![image](https://user-images.githubusercontent.com/2008881/190730251-e84b68ef-19a7-422d-a4f2-f3076cca5436.png)

**Comment by k80bowman** [comment]
oof, thanks. I'll remove them from this ticket.
