### ISSUE TITLE
Move File input in Storybook to component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1206]
## Description
Move File input web component from under development to components section in Storybook since development is complete. 
https://design.va.gov/storybook/?path=/docs/components-va-file-input--default

## Tasks
- [ ] Move File input web component from under development to components in Storybook
- [ ] Move React component version of File input to deprecated

## Acceptance Criteria
- [ ] File input listed in components in the left side nav in storybook
- [ ]  React component version of File input is listed as deprecated in Storybook
