### ISSUE TITLE
Modify the content-build to exclude the default web component loader on certain applications.

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1211]
## Description

More and more VFS applications are becoming yarn workspaces and gaining the ability to continuously deploy. The yarn workspace means that they can manage their own dependencies if they choose to. At the moment we are building and including the same script for defining our web components on all pages.

- [the script](https://github.com/department-of-veterans-affairs/vets-website/blob/1dd91dbf9c1c07b21d77de115d5537f19ac552a1/src/platform/site-wide/wc-loader.js)
- [where it gets built as `web-components.js`](https://github.com/department-of-veterans-affairs/vets-website/blob/1dd91dbf9c1c07b21d77de115d5537f19ac552a1/config/webpack.config.js#L63)
- [where it gets included on every page](https://github.com/department-of-veterans-affairs/content-build/blob/e3d6b7438a078733d693768d32b36a52edd7f9e6/src/site/includes/header.html#L46)

If we modify the content build to not include certain global assets (CSS & JS) on every page, then the applications could declare and include a smaller subset of dependencies, thus reducing their bundle size & scripting time.

## Details

Part of this will involve creating a [new build output in Stencil](https://stenciljs.com/docs/custom-elements) so that teams can only import the components that they know they will need. We will need to figure out how this will work in `vets-website`.

## Tasks
- [x] Figure out which assets/dependencies are appropriate for app teams to define themselves
    - `formation`, `component-library`, etc.
- [x] Modify the `component-library` build to export the `dist-custom-elements` target.
- [ ] Update `check-in` app to use a smaller subset of site-wide assets for hopeful performance benefits

## Acceptance Criteria
- [ ] Certain VFS teams can declare their own "site-wide" versions of dependencies and choose a smaller subset

**Comment by caw310** [comment]
Adding comment to clarify that this issue was transferred to Andrew in December due to unanticipated team changes.

**Comment by Andrew565** [comment]
Clarifying point: The 'related' PR #1402 does not affect the work on this ticket.

**Comment by caw310** [comment]
This will carry over into sprint 19 so Andrew can complete work started by Brooks.

**Comment by caw310** [comment]
Final PR related to this ticket was merged in by check-in team so closing.
