### ISSUE TITLE
Remove unused JS in Check-in Experience apps

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1212]
## Description

This isn't really a Design System issue, but the bundle size could be reduced by removing unused JS. For example, the `hasMoreAppointmentsToCheckInto` function.

![Screenshot of a ripgrep search for "hasMoreAppointmentsToCheckInto", showing that it's only used in the file it's defined & exported and in the test file.](https://user-images.githubusercontent.com/2008881/191134517-ca6ea24c-0d9a-4ccb-b97d-65dcf4737818.png)

And another const:

![Screenshot of a ripgrep search for "addressFormFields", showing that it's only used when defined and exported.](https://user-images.githubusercontent.com/2008881/191135292-475d97de-28ac-4471-99a5-87b142ba1d6b.png)

## Tasks
- [ ] Identify all unused `check-in` app JS
- [ ] Remove unused JS
- [ ] Measure the bundle size before & after to get a percentage of bundle size reduction.
