### ISSUE TITLE
Formation Deprecation - Step 1 - Rename & archive existing design-system repo

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1218]
## Description

There is an old [`design-system` repo](https://github.com/department-of-veterans-affairs/design-system):

![Screenshot of the old Github repo](https://user-images.githubusercontent.com/2008881/191854697-58796faf-64e2-4d40-967b-9642007374ea.png)

We should rename it to `design-system-OLD` or something similar, then archive it.

## Details
Renaming it is so that we can have a `design-system` repo for our _current_ DST monorepo. Github's [documentation on renaming says](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository):

> Warning: If you create a new repository under your account in the future, do not reuse the original name of the renamed repository. If you do, redirects to the renamed repository will break.

So if we reused the `design-system` name then we would break the redirect to `design-system-OLD`, but that seems fine.

## Tasks
- [ ] Rename existing `design-system` repo
- [ ] Archive renamed repo

## Acceptance Criteria
- [ ] old design-system repo is archived

**Comment by caw310** [comment]
@Andrew565 @jamigibbs  do we still want to do this?

**Comment by jamigibbs** [comment]
@caw310 Yes, I think we should still do this.

**Comment by Andrew565** [comment]
Agreed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1218?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
Issue filed for requesting a name change for the above repo - https://github.com/department-of-veterans-affairs/github-user-requests/issues/18759

**Comment by micahchiang** [comment]
Issue has been completed, so closing this ticket.
