### ISSUE TITLE
Move documentation repo into component-library monorepo as package

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1219]
## Description

In an effort to consolidate to a single repo, we should move the Jekyll/npm package [`vets-design-system-documentation`](https://github.com/department-of-veterans-affairs/vets-design-system-documentation) into the `component-library` repo as a package.

## Tasks
- [ ] Create a new `documentation` package in `component-library` repo
- [ ] Move src and config files into new package
- [ ] Move [`deploy` Github action file](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/d49033be00fe43aa16396272c31db4600a17c3e0/.github/workflows/deploy.yml) into `component-library` root `.github` directory
    - This should be updated to only deploy to dev until we can confirm that things still work
- [ ] Update links to point to new location
- [ ] Update `design-system-documentation` README file to point to new location

## Acceptance Criteria
- [ ] documentation repo lives as a package in the DST monorepo

**Comment by humancompanion-usds** [comment]
I see now that this is related to #1220. Why do we need a single repo? Don't we push and publish components and documentation for them on different timelines? Is the goal to unify that?
