### ISSUE TITLE
Migrate remaining issues to monorepo & archive documentation repo

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1220]
## Description

For tracking issues in a single place, the team monorepo makes the most sense. We should use a script to migrate any remaining issues 

## Details
The [Github CLI](https://cli.github.com/manual/gh_alias_set) has an `alias` command and it also accepts [extensions](https://cli.github.com/manual/gh_extension) which can allow for more powerful scripting. We could use one of those to come up with a script/command to:

1. Use [`gh issue list`](https://cli.github.com/manual/gh_issue_list) to get a list of open issues
2. Loop through the list
3. Use [`gh issue transfer`](https://cli.github.com/manual/gh_issue_transfer) to transfer each issue to the `component-library` repo

## Tasks
- [ ] Come up with a script to migrate any remaining open issues in `vets-design-system-documentation` to `component-library` repo

## Acceptance Criteria
- [ ] Issues are migrated to `component-library`
- [ ] Archive `vets-design-system-documentation`

**Comment by humancompanion-usds** [comment]
Let's discuss. I got explicit permission from Chelen to keep our issues in this repo. The acceptance criteria here are not acceptable to me unless there are missing details. Are you just talking about moving component related issues or all issues to component-library? We need this repo to publish design.va.gov.

**Comment by caw310** [comment]
closing as no longer relevant.
