### ISSUE TITLE
Replace React design system components in the old forms library with web components

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1240]
## Description
As part of our efforts to decrease reliance on our React components, we should replace the React design system components used in the old/current forms library with web component versions of those components.

On the face this work sounds simple, but this will probably require us to update some application tests. Please reach out to the platform QA people for help with updating any necessary Cypress tests.

## Details
The following React design system components are currently being used in the forms system:
- Checkbox
    - [forms/PrivacyAgreement.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/platform/forms/components/PrivacyAgreement.jsx)
    - [forms/PreSubmitSection.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/93cd0f64b7e9ae9199776ce299a477ec0c871fc7/src/platform/forms/components/review/PreSubmitSection.jsx)
    - [forms-system/FormSignature](https://github.com/department-of-veterans-affairs/vets-website/blob/86fcb26c690ec366e4ed4d60b382264e53a433f8/src/platform/forms-system/src/js/components/FormSignature.jsx)
- LoadingIndicator
    - [forms/save-in-progress/ApplicationStatus.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/48b2f509e811112bbd5c5941c81db90693f08c8f/src/platform/forms/save-in-progress/ApplicationStatus.jsx)
    - [forms/save-in-progress/RoutedSavableApp.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/0692a1322139821575d06b0423b4a6483bb271d5/src/platform/forms/save-in-progress/RoutedSavableApp.jsx)
- ProgressButton
    - [forms/save-in-progress/ApplicationStatus.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/48b2f509e811112bbd5c5941c81db90693f08c8f/src/platform/forms/save-in-progress/ApplicationStatus.jsx)
    - [forms/save-in-progress/FormStartControls.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/24c0e02eb60aa695547b17cde96707053956a494/src/platform/forms/save-in-progress/FormStartControls.jsx)
    - [forms/save-in-progress/SaveInProgressErrorPage.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/platform/forms/save-in-progress/SaveInProgressErrorPage.jsx)
- Modal
    - [forms/save-in-progress/ApplicationStatus.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/48b2f509e811112bbd5c5941c81db90693f08c8f/src/platform/forms/save-in-progress/ApplicationStatus.jsx)
    - [forms/save-in-progress/FormSignInModal.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/platform/forms/save-in-progress/FormSignInModal.jsx)
    - [forms/save-in-progress/FormStartControls.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/24c0e02eb60aa695547b17cde96707053956a494/src/platform/forms/save-in-progress/FormStartControls.jsx)
- AlertBox
    - [forms/save-in-progress/DownTimeMessage.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/platform/forms/save-in-progress/DowntimeMessage.jsx)
- Select
    - [forms/save-in-progress/SaveInProgressDevModal.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/c7ec6c3d47436c1fa2f9c87699fbfa4a84476d9b/src/platform/forms/save-in-progress/SaveInProgressDevModal.jsx)
- TextInput
    - [forms-system/FormSignature](https://github.com/department-of-veterans-affairs/vets-website/blob/86fcb26c690ec366e4ed4d60b382264e53a433f8/src/platform/forms-system/src/js/components/FormSignature.jsx)
- AdditionalInfo
    - [forms-system/directDeposit.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/ee4d7c86cbabefc7e56944b39b72ecb50e5fcf59/src/platform/forms-system/src/js/definitions/content/directDeposit.jsx)
- Telephone
    - [forms-system/directDeposit.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/ee4d7c86cbabefc7e56944b39b72ecb50e5fcf59/src/platform/forms-system/src/js/definitions/content/directDeposit.jsx)

## Tasks
- [ ] Replace React design system components in the current/old forms system with web components
- [ ] Fix any failing tests
- [ ] Spot check applications to make sure the components are functioning as expected

## Acceptance Criteria
- [ ] React design system components used in the current/old forms system are replaced with design system web components, all tests are passing, and form applications have been spot checked to make sure everything is working properly.
