### ISSUE TITLE
USWDS v3 - Radio button - Design

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1243]
## Description
We need to incorporate the designs for the [USWDS Radio Button component](https://designsystem.digital.gov/components/radio-buttons/) into the VA Sketch library. 

Prior to completing this addition, there should be some discussion with the team about how we want to manage including the USWDS resources into the Sketch library (how we want to organize things, especially for components where there are design differences between the current VA version and the USWDS version).

## Tasks
- [ ] Incorporate designs for USWDS Radio button into our radio button 
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by GnatalieH** [comment]
@humancompanion-usds thanks! I went ahead and made the changes you requested and added a couple of radio group examples (default and tile). I updated the [component page](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/l9GRl4/a/QbLxoR7) in the main VA Pattern library file. I haven't yet removed the the VA Radio button symbols, but I copied them to the Archive page and will delete the symbols (so only groups remain) when I get your OK. Right now just the error state is in question. Thanks!

**Comment by humancompanion-usds** [comment]
@GnatalieH - I was able to get the radio buttons into an error state in the browser but adding the error message broke the layout so I don't have a screenshot for you. Work with Brooks or Jami this week once the code is merged in for Tile and ask them to create an error state in Storybook that you can reference to create the same in Sketch. We should show this variation in an error state in Storybook.

**Comment by caw310** [comment]
To close out this ticket, Natalie needs to see the error state to create asset for Sketch library.

**Comment by GnatalieH** [comment]
@humancompanion-usds I was able to add the error states thanks to @jhonnyoddball. I also re-added the VA Radio button symbols and artboard. [Please review here](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/AF7CD21C-2DF3-4CA4-B678-473A929B9615/canvas) and let me know what ya think. Thanks!

**Comment by humancompanion-usds** [comment]
Looks good. Let's talk this week about how we want to communicate what is coming and these additions. We may want to create a single page that holds all of the USWDS v3 items with a big note on what they are, a warning not to use them yet, etc.
