### ISSUE TITLE
Get analytics config for the loading event for all components and add to component library

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1251]
## Description
Based on discovery completed as part of #1179.

This ticket should be completed first.

We need to work with the Analytics team to get the Google Analytics 4 configuration for the loading event for all of our components. The GA4 setup work is being completed as part of #1174. Then we need to add these events to our components.

## Details
This is going to be a larger ticket, more because we may need to wait a bit on the Analytics team to get this information for us. @jamigibbs has suggested that maybe we should provide the event details ourselves, given what we know about GA4 configurations, and then have the analytics team set it up for us. If we go that route, we should provide not only the details that need to be included in the component, but in the component-library-analytics-setup.js file in `vets-website` as well.

The Loading Indicator web component is currently our only component with a loading event. It can be used as a model.

## Tasks
- [ ] Construct analytics configs for loading events for each of our components (web and React)
- [ ] Work with the Analytics team to add the configs to Google Analytics (target GA4, no need to do GA3 at all)
- [ ] Add analytics configs to our components

## Acceptance Criteria
- [ ] Each of our web components and our remaining React components fires an analytics event on load
- [ ] Google Analytics is set up to receive and record those events

**Comment by caw310** [comment]
@Andrew565 @jamigibbs - can we closet this since we've add GA4 to components?

**Comment by jamigibbs** [comment]
@caw310 👍
