### ISSUE TITLE
Add loading event analytics configs to component-library-analytics-setup.js

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1252]
## Description
Depends on #1251. Based on discovery completed as part of #1179.

Once we have the loading event analytics configurations set up in Google Analytics and in our component files, we need to add the configs to the [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/05c5ce2e798567ca2f4be32e5961856224f5c8d3/src/platform/site-wide/component-library-analytics-setup.js) file in the `vets-website` repo to capture the loading events and send them to GA. We'll need to work with the Analytics team to test that these events are all working.

## Details
We should have all the config details we need from #1251. To help the analytics team out, it might be good to propose a plan for testing whether these are working. As noted in #1251, we should only target GA4 with this data. No need to send the data to GA3.

## Tasks
- [ ] Add the configs for the loading events for each of our components to the [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/05c5ce2e798567ca2f4be32e5961856224f5c8d3/src/platform/site-wide/component-library-analytics-setup.js) file in the `vets-website` repo.
- [ ] Verify with the Analytics team that the events are firing and GA is receiving them

## Acceptance Criteria
- [ ] Analytics loading events for each of our web and React components are being received by GA4.

**Comment by caw310** [comment]
@Andrew565 @jamigibbs - can we close this since we've add GA4 to components?
