### ISSUE TITLE
Add loading event data to DS DOMO dashboard from GA

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1253]
## Description
Depends on #1252. Based on discovery completed as part of #1179.

Once the data is being sent to Google Analytics, we need to work with the Analytics team to automatically send that data to DOMO. Once the data is accessible in DOMO, we then need to create a view/chart for it in our [Design System dashboard](https://va-gov.domo.com/page/1537522750).

## Details
The [Platform Analytics and Insights documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights) may have some useful info on how all of this works.

You'll want to discuss with the DST what reporting interval would be most useful.

## Tasks
- [ ] Coordinate with the Analytics team to add the data from the component loading events to DOMO
- [ ] Set up a view/chart for the data in the Design System DOMO dashboard

## Acceptance Criteria
- [ ] The component loading events data is accessible in DOMO from the Design System dashboard

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
