### ISSUE TITLE
Fix the maturity scale indicators in the design.va.gov sidenav

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1255]
## Description
The way the sidenav on design.va.gov is built, the maturity scale indicators for component subpages represent the maturity scale for the parent page, rather than the child page. This means we end up in situations like the one pictured below where the sidenav indicator does not match the component maturity level.
![image](https://user-images.githubusercontent.com/12739849/193832604-8b8e5e25-d195-42cf-9aea-bed3dcffa3d5.png)

We also would like to, as much as possible, rely on a single source of truth for the maturity scale information. For our web components, this data is stored with the component in the `component-library` and is accessible through the `src/_data/component-docs.json` file, which fetches this information on site build. We need to, for our components that are web components, depend on this data for the maturity scale information, rather than maintaining it in the component yaml frontmatter.

## Tasks
- [ ] Fix the design.va.gov sidenav so that the component subpages have the correct maturity scale indicators
- [ ] Update the web component maturity scale indicators and tags to depend on the data in component-docs.json.

## Acceptance Criteria
- [ ] The design.va.gov sidenav has the correct maturity scale indicators for component subpages
- [ ] There is a single source of truth for the web component maturity scale statuses

**Comment by humancompanion-usds** [comment]
I accidentally removed status indicators for patterns.
