### ISSUE TITLE
Re-set telephone eslint rule to error and add 6-digit length to telephone-contact rule

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1257]
## Description
After we initially set the prefer-telephone-component eslint rule to error, we heard from a couple of teams that they weren't able to use the component for some of their telephone elements because it doesn't support SMS numbers. In order to unblock teams, we changed the eslint rule to a warning. Once #1246 is complete, however, the component will support SMS numbers and we should change the prefer-telephone-component eslint rule back to an error.

We will also need to update the telephone-contact-3-or-10-digits rule to accept 6-digit numbers as well (and probably re-name it).

## Tasks
- [ ] Set prefer-telephone-component eslint rule to error
- [ ] update telephone-contact-3-or-10-digits rule to accept 6-digit numbers

## Acceptance Criteria
- [ ] Teams are once again required to update their telephone number elements to use the va-telephone component in vets-website.
