### ISSUE TITLE
USWDS v3 - Text input - Design

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1259]
## Description
We need to incorporate the designs for the [USWDS Text Input component](https://designsystem.digital.gov/components/text-input/) into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There are some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not. @humancompanion-usds has already noted that we wouldn't have any need for the success state, for example.

Especially with this component, since it is so simple, it may turn out that there are no design differences between the two versions. If that is the case, there is no need to update Sketch or maintain a separate version of this component.

## Tasks
- [ ] Audit differences between the USWDS version and ours and present to the DST
- [ ] Incorporate designs for USWDS Radio button into our radio group and single components in Sketch
- [ ] Review designs with PO
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Where necessary, USWDS Text input designs have been incorporated into our Sketch library
- [ ] Designs have been presented to the DST

**Comment by GnatalieH** [comment]
@humancompanion-usds this is ready to review. [Here is the link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/52Z2bpp).

**Comment by humancompanion-usds** [comment]
Feedback was to show the current state alongside the future USWDS v3-based state here and in Radio Button (which we've now confirmed is also v3 only).

**Comment by GnatalieH** [comment]
@humancompanion-usds I've re-added the VA version of this component, which you can [review here](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/04A043C5-65CA-43BB-88F2-E17EF8B12D7D/canvas). Thanks!

**Comment by humancompanion-usds** [comment]
@GnatalieH - Looks good. Let's make them match-up. Looks like we just need to add Hint text variations to the VA artboard and drop the disabled example (archive it). Also, the last example need to be renamed Open Error with Focus and added to the VA version as well. After that feel free to close this out. Thanks!

**Comment by GnatalieH** [comment]
Thanks @humancompanion-usds. We do not actually have hint text variation in the VA DS. Well, we do but it's what we call the Text input with Additional info. So I didn't want to add it to the VA assets if it doesn't exist in our coded components. Do you still want me to add it to the VA assets?

**Comment by humancompanion-usds** [comment]
Thanks, @GnatalieH. I understand. @caw310 - We should fix this. Additional info cannot be the only option for hint text. In fact, I updated our guidance last week to capture the 3 different levels: https://design.va.gov/components/form/#hint-text
These need to be supported by the web component and shown in Sketch. Thanks.

**Comment by caw310** [comment]
I will take a look and write up tickets for updating the web component.

**Comment by GnatalieH** [comment]
@humancompanion-usds I added hint text and hint text-error variations to the symbols for VA Text input.
