### ISSUE TITLE
Conversion to USWDS v3 - Memorable Date - Design

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1268]
## Description
We need to incorporate the designs for the [USWDS Memorable Date component](https://designsystem.digital.gov/components/memorable-date/) into the VA Sketch library. This component is already based on the USWDS component, so there may not be anything to do here. But we should at least do a quick audit and double check.

## Tasks
- [ ] Audit differences between the USWDS version and ours and present to the DST
- [ ] Incorporate designs for USWDS Radio button into our radio group and single components in Sketch
- [ ] Review designs with PO
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Where necessary, USWDS Text input designs have been incorporated into our Sketch library
- [ ] Designs have been presented to the DST

**Comment by GnatalieH** [comment]
@caw310 can I present my work on this so far during the extended standup on Wednesday?

**Comment by GnatalieH** [comment]
@SarahKay8 here is a synopsis of what @jhonnyoddball and I discussed today:

- Radio button and Checkbox in USWDS components use a `legend`. The `label` is used on the radio button/checkbox option itself.
- Other USWDS form components, like Text input, use label(s).
- What are the a11y implications of using one or the other, or both together?

@jamigibbs also noted similar things in her recent [audit of hint text](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1249). Her screenshots and comments on the ticket provide a lot of additional context. 

We should define and document a proper way to code USWDS-inherited form components with the following variations (you can see all but Checkbox [mocked up here in Sketch](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/447FB6DA-215E-4F15-A71B-94B7686DA614/canvas):

**Text input**

Label
Text input

Label
Hint text
Text input

Label
Error message
Text input

Label
Hint text
Error message
Text input

Label
Additional info
Text input

Label
Additional info
Error message
Text input

**Radio button and Checkbox group**

Legend
Option + label

Legend
Error message
Option + label

_Tile variation_

Legend
Option + label
Hint text (within the option's tile)

Legend
Error message
Option + label
Hint text (within the option's tile)

**Memorable date**

FYI [the USWDS documentation](https://designsystem.digital.gov/components/memorable-date/) suggests using Text input for the Day and Year fields.

Label
Hint text
Month Select box | Day Text input | Year Text input

Label
Hint text
Error message
Month Select box | Day Text input | Year Text input

We may want to audit other USWDS form components, depending on what our team's roadmap looks like.

FYI @Andrew565 and @humancompanion-usds

**Comment by GnatalieH** [comment]
[Here are my mockups](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/AxeE0LR), ready for review @jhonnyoddball and @humancompanion-usds. FYI this component is not responsive as far as I can tell. I made my mockups the same specs as the developed component on the [USWDS website](https://designsystem.digital.gov/components/memorable-date/).

**Comment by GnatalieH** [comment]
[Here are my mockups](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/AxeE0LR), ready for review @jhonnyoddball and @humancompanion-usds. FYI this component is not responsive as far as I can tell. I made my mockups the same specs as the developed component on the [USWDS website](https://designsystem.digital.gov/components/memorable-date/).

**Comment by SarahKay8** [comment]
@GnatalieH 

So a `label` is specific to an input within a form - i.e USWDS text input whereas a `legend` applies to a `fieldset `such as USWDS radio buttons and checkboxes. In a form you can group together controls using `fieldset` elements and you can then use the `legend `element to give a caption to that group of elements. Whereas you will use the `label` element to add a caption to an individual control.

**Comment by SarahKay8** [comment]
In a form you can group together controls using fieldset elements and you can then use the legend element to give a caption to that group of elements.
Whereas you will use the label element to add a caption to an individual control.



@GnatalieH 

For memorable date, the legend provides its parent fieldset with an accessible name.

the name in this example is “Date of Birth" 

if the description was included in the legend, the name would become “date of birth For example: January 19 2000”


Labels are used on USWDS Text Input because these are individual controls.

**Comment by GnatalieH** [comment]
I'm going to close this ticket because the design portion of the work is done. However, I'd like to point out that @SarahKay8 recommended in her [a11y review](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1301) of this component to NOT use the dropdown menu. I've created assets with three text inputs in addition to the assets with a dropdown menu. @humancompanion-usds should weigh in when he returns from vacation about how we want to move forward.
