### ISSUE TITLE
Banner - Official Gov site - Design

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1275]
## Description
Create design for Banner - Official Gov site component and/or update Sketch artifacts for Banner - Official Gov site. This component will be based on the [USWDS Banner component](https://designsystem.digital.gov/components/banner/).

## Details
[add links to any tickets or documents with details about the design]
[add links to any research documents related to the component]

## Tasks
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by GnatalieH** [comment]
Mockups are here and ready for review @humancompanion-usds:

- [Mobile](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/jgGRmr0)
- [Desktop](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/l1mpave)

I created open/closed variations in mobile and desktop sizes with default and focus states for each variation.

**Comment by humancompanion-usds** [comment]
Looks good. Approved!
