### ISSUE TITLE
Add Tagalog and Spanish translations to several components

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1282]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add Design System component label (such as `va-alert`)
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
Add the following Tagalog translations to the following components:

#### Tagalog
{
  "error": "Error",
  "required:": "Kailangan",
  "max-x-characters": "Pinakamarami ang {{number}} character",
  "date-of-birth": "Petsa ng Kapanganakan",
  "month": "Buwan",
  "day": "Araw",
  "year": "Taon",
  "please-enter-a-year-between-x-and-y": "Mangyaring ilagay ang taon sa pagitan ng {{year1}} at {{year2}}",
  "collapse-all-accordions": "I-collapse ang lahat ng accordion",
  "expand-all-accordions": "I-expand ang lahat ng accordion",
  "collapse-all": "I-collapse ang lahat",
  "expand-all": "I-expand lahat"
}

#### Spanish
{
"error": "Error",  
"required:": "Requerido",  
"max-x-characters": "Número máximo de caracteres: {{number}} ",  
"date-of-birth": "Fecha de nacimiento",  
"month": "Mes",  "day": "Día",  "year": "Año",  
"please-enter-a-year-between-x-and-y": "Ingrese un año entre {{year1}} y {{year2}} ",  
"collapse-all-accordions": "Contraer todos los acordeones",  
"expand-all-accordions": "Expandir todos los acordeones",  
"collapse-all": "Contraer todo",  
"expand-all": "Expandir todo", 
"please-enter-your-last-name": "Ingrese su apellido",  
"please-enter-your-day-of-birth": "Ingrese su día de nacimiento", 
"please-enter-your-month-and-day-of-birth.": "Ingrese su mes y día de nacimiento.",  
"please-enter-your-month-of-birth.": "Ingrese su mes de nacimiento.",  
"please-enter-your-year-of-birth.": "Ingrese su año de nacimiento."
}

### Components
* memorable date field
* text input
* accordion

## Tasks
- [x] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Write any necessary tests
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json

## Acceptance Criteria
- [ ] Component documentation indicates there are translations available for this component
- [ ] Component has had code review
- [ ] design.va.gov has the latest version of component-library

**Comment by jamigibbs** [comment]
@humancompanion-usds The `va-text-input` component also has a "min length":

https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-text-input/va-text-input.tsx#L253

> Min. {minlength} characters

We have a [max-chars](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/core/src/i18n/translations/en.js#L4) but I don't see min-chars in the list above. Do you know if translations have been requested for this text? (we also do not have this value mapped for `es` as well).

**Comment by jamigibbs** [comment]
I've created two separate tickets related to this:

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1291

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1292
