### ISSUE TITLE
Devise a plan for making user visible changes to allow VFS teams to upgrade to USWDS v3-based Design System

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1290]
## Description
Once we have an application using USWDS v3-based Design System packages (base package and component-library) then we will have user-visible changes between that application and any application still using Formation, not to mention sitewide content. Thus we need to make a plan for adjusting user-visible diffs between Formation and v3 ahead of time so that as an application upgrades a user cannot tell the difference.

## Details
User visible diffs between versions that we are currently aware of are:

* Primary button and link color (different shade of blue)
* Slightly larger font-sizes for paragraphs and headers (larger in v3)
* Focus state (which may be hardcoded to our desired focus state design)

## Tasks
- [ ] Prototype these changes in Formation and review them in staging
- [ ] Make a plan for rolling out these changes and create another RFC or whatever other doc/request we need to make to have our plan approved.
- [ ] File issues to execute the plan

## Acceptance Criteria
- [ ] A documented and approved plan for rolling out user-visible changes that would allow VFS teams to adopt v3-based packages at their own pace and retain consistency across the site

**Comment by humancompanion-usds** [comment]
The rough plan at the moment would be to update Formation to change either all of the colors or just the biggest changes (primary blue which would change all links and buttons) plus the font-sizes and focus state in advance of opening up the flood gates to VFS Teams to adopt USWDS v3-based Design System packages (we really need a shorter name for that: VA Design System v3? I'd like to pick a version that is in-sync with USWDS). The alternative would be to override v3 to use our blue and font-sizes and keep those overrides in place across however long it takes for all VFS Teams to adopt v3. That's going to be error prone and difficult so I would prefer that we make the changes to Formation before we ask VFS Teams to adopt v3.

**Comment by humancompanion-usds** [comment]
A plan has been devised: https://vfs.atlassian.net/wiki/spaces/DST/pages/2731245815/Decision+PROPOSAL+Upgrade+rollout+steps

@caw310 and @micahchiang - The tasks and acceptance criteria are still relevant here. Do you want to turn this one into an initiative or close it and start fresh?

**Comment by caw310** [comment]
I would say we keep this open for now and we can turn it into an initiative. 
@humancompanion-usds are you thinking it should be a new initiative in addition to the phase 3 one or is this for next quarter?

**Comment by humancompanion-usds** [comment]
@caw310 and @micahchiang - I feel like Micah is doing this now with the RFC work but I can't find an issue tracking that. I'm going to assign this to Micah and he can close it once the RFC is done.
