### ISSUE TITLE
Tagalog translations for va-text-input & va-memorable-date

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1291]
## Description
We received Tagalog translations in #1282 but the provided translations don't include one for the "minLength" validation message or date hint text:

**va-text-input**
> (Min. {minlength} characters)

```
        {minlength && value?.length < minlength && (
          <small part="validation">(Min. {minlength} characters)</small>
        )}
```

![Screen Shot 2022-10-17 at 9 53 44 AM](https://user-images.githubusercontent.com/872479/196210594-c371341d-abc2-44db-93ea-6e49a3e91206.png)

**va-memorable-date**

> Please enter two digits for the month and day and four digits for the year.

```
<legend>
   {label} {required && <span class="required">{i18next.t('required')}</span>}
  <div id="dateHint">
    Please enter two digits for the month and day and four digits for
    the year.
  </div>
</legend>
```
![Screen Shot 2022-10-17 at 10 14 31 AM](https://user-images.githubusercontent.com/872479/196215734-d891eac4-4b5f-49cc-b53a-09e258a505e4.png)

Note: There is also a ticket created for the Spanish translation of this text as well #1292 

## Details
- Design documents: [add links to any design documents]
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storyboook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
I have the translations to pass on. They're in the DST google folder. 
https://drive.google.com/drive/folders/19Z8r7kZVpZqyKatgGNrHjHVTbMuVd6qx?usp=sharing

**Comment by jhonnyoddball** [comment]
@caw310 none of the missing translations are available in the google folder files.

We are still missing in Tagalog:
```
  'max-chars': '(Max. {{length}} characters)',
  'january': 'January',
  'february': 'February',
  'march': 'March',
  'april': 'April',
  'may': 'May',
  'june': 'June',
  'july': 'July',
  'august': 'August',
  'september': 'September',
  'october': 'October',
  'november': 'November',
  'december': 'December',
  'date-hint': 'Please enter two digits for the month and four digits for the year',
```

**Comment by caw310** [comment]
@humancompanion-usds , can you help get the missing translations?

**Comment by jamigibbs** [comment]
@jhonnyoddball In [this document](https://drive.google.com/file/d/1oiu6-MQc2rm-oYKRsOlRq1aPIhSXfLJm/view?usp=share_link) in the translation folder, I see the following translations. Isn't that what this ticket is needing?

```
"please-enter-memorable-date": "Mangyaring maglagay ang dalawang numero para sa buwan at sa araw at apat na numero para sa taon",
```

https://translate.google.com/?sl=auto&tl=en&text=Mangyaring%20maglagay%20ang%20dalawang%20numero%20para%20sa%20buwan%20at%20sa%20araw%20at%20apat%20na%20numero%20para%20sa%20taon&op=translate

```
"min-chars": "(Pinakamababa ang X (na) karakter)"
```

Google Translate: https://translate.google.com/?sl=auto&tl=en&text=(Pinakamababa%20ang%20X%20(na)%20karakter)&op=translate

**Comment by jhonnyoddball** [comment]
> @jhonnyoddball In [this document](https://drive.google.com/file/d/1oiu6-MQc2rm-oYKRsOlRq1aPIhSXfLJm/view?usp=share_link) in the translation folder, I see the following translations. Isn't that what this ticket is needing?
> 
> ```
> "please-enter-memorable-date": "Mangyaring maglagay ang dalawang numero para sa buwan at sa araw at apat na numero para sa taon",
> ```
> 
> https://translate.google.com/?sl=auto&tl=en&text=Mangyaring%20maglagay%20ang%20dalawang%20numero%20para%20sa%20buwan%20at%20sa%20araw%20at%20apat%20na%20numero%20para%20sa%20taon&op=translate
> 
> ```
> "min-chars": "(Pinakamababa ang X (na) karakter)"
> ```
> 
> Google Translate: https://translate.google.com/?sl=auto&tl=en&text=(Pinakamababa%20ang%20X%20(na)%20karakter)&op=translate

@jamigibbs We already have those two. The list is above your comment.

**Comment by jamigibbs** [comment]
@jhonnyoddball This ticket is specifically asking for `(Min. {minlength} characters)` and `Please enter two digits for the month and day and four digits for the year.` for the two components in the description (va-text-input & va-memorable-date). Do we need those other translations for either of those components right now? 

Also the max length/chars is already available: https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/core/src/i18n/translations/tl.js#L4

**Comment by jhonnyoddball** [comment]
Yes, for this ticket I think is only `(Min. {minlength} characters)` and `Please enter two digits for the month and day and four digits for the year.`

**Comment by jamigibbs** [comment]
https://drive.google.com/file/d/1oiu6-MQc2rm-oYKRsOlRq1aPIhSXfLJm/view

![Screenshot 2023-01-12 at 8 53 32 AM](https://user-images.githubusercontent.com/872479/212099448-ffa5e018-49c1-429a-963d-3fab11ddd993.png)
