### ISSUE TITLE
Spanish translation for va-text-input & va-memorable-date 

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1292]
## Description
The `va-memorable-date` component has Spanish translations for all text except for the hint text below. Once we have the translations for that text, we can add i18next to va-memorable-date. There is also a ticket created for the Tagalog translation for this text as well #1291 

> Please enter two digits for the month and day and four digits for the year.

![Screen Shot 2022-10-17 at 11 09 14 AM](https://user-images.githubusercontent.com/872479/196228127-07710796-6022-47a9-a39e-790cbc388253.png)

Additionally, the va-text-input component does not have Spanish translations for minLength:

**va-text-input**
> (Min. {minlength} characters)

```
        {minlength && value?.length < minlength && (
          <small part="validation">(Min. {minlength} characters)</small>
        )}
```

![Screen Shot 2022-10-17 at 9 53 44 AM](https://user-images.githubusercontent.com/872479/196210594-c371341d-abc2-44db-93ea-6e49a3e91206.png)

This was discovered while adding Tagalog translation: https://github.com/department-of-veterans-affairs/component-library/pull/554

## Details
- Design documents: [add links to any design documents]
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [x] Create web component and add to Storyboook
- [x] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by jhonnyoddball** [comment]
> As part of the Spanish translation updates for Memorable Date, we should see if we can add the feminine "Requerida" (Required) for it as well as described in [#45682 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45682)

I’m a native Spanish speaker and I don’t agree with this statement

Usually in forms we refer as a `required field`, not a `required date`. That applies to Spanish too. `Espacio requerido` not `Fecha requerida`

This can be seen in this example from the Maricopa County, Arizona's website:
https://recorder.maricopa.gov/Elections/EarlyVotingBallot/earlyvotingballotstatus_es.aspx/subscriptions/voterregistrationlookup.aspx

![Screen Shot 2022-11-04 at 12 06 32 PM](https://user-images.githubusercontent.com/55560129/200060696-7b6410e2-b445-4ac1-afa1-c4eb55bd4115.png)

I recommend to just keep `Requerido` only

**Comment by jhonnyoddball** [comment]
Analytics have been added in [PR 513](https://github.com/department-of-veterans-affairs/component-library/pull/513)
