### ISSUE TITLE
[Pattern update] - Add examples to "Help users recover from errors"

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1293]
## Description 
The Content team has identified the following types of errors and we need an example for each one:
- Sign in and identify verification
- System
- Engagement
- Access
- Feedback

## Details
Add screenshots with captions in the Examples section of [Help users recover from errors](https://design.va.gov/patterns/help-users-to/recover-from-errors).

## Tasks
- [ ] Get examples from Content team (Randi)
- [ ] Format examples if necessary and upload with captions
- [ ] Make sure the error categories are explained via captions or other text in Examples section
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by GnatalieH** [comment]
@allison0034 here's the ticket we're working on this sprint. I'm looking for hi-res examples of different types of error messages. If you look at my [PR draft](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/009258f9f078899626a6cd31a298721b224cab83/src/_patterns/help-users-to/recover-from-errors.md), you'll see placeholders I included under Examples for the different types of error messages we want to show.

**Comment by GnatalieH** [comment]
### Access / authorization warning:

![Screen Shot 2022-11-10 at 9.36.58 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/8a96a9f1-90d1-4c07-b946-d78920ef833e)

### Access / system downtime warning:

![Screen Shot 2022-11-10 at 10.03.08 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/1f30c461-5658-4e8f-8f43-c50dcb9e4431)

### Access / authorization error:

![Screen Shot 2022-11-03 at 9.08.19 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/373f0893-e299-4a6b-a669-81d0d5929bd8)

### Feedback errors:

![Screen Shot 2022-11-10 at 9.41.11 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/6fdc21be-097d-46b2-bdc3-729b22c1efe4)

### System / scheduled or unscheduled downtime warning:

![Screen Shot 2022-11-11 at 1.00.42 PM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/dc7c8973-4662-4d8f-a360-82692acd4afc)

**Comment by GnatalieH** [comment]
I left a comment with examples of System, Access, and Feedback error types (which are all of the error types in the Content style guide). Engagement messages are not actually errors.
