### ISSUE TITLE
USWDS v3 - Text input  - Accessibility review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1300]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add Design System component label (such as `va-alert`)
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Issue Description
We need to conduct a review of the accessibility guidance on USWDS for the Text input component  ([URL](https://designsystem.digital.gov/components/text-input/)) and compare it to the a11y guidance in the VA DS.  ([URL](https://design.va.gov/components/form/text-input)) 

## Tasks
- [ ] Full review of accessibility guidance for the component on both USWDS and VA DS. 
- [ ] Identify and document the differences between the two 
- [ ] Make a recommendation on which guidance to use and include brief explanation on why (feedback can be in this ticket)
- [ ] Review final recommendation with the team (can be done during standup) 
- [ ] Add a11y guidance updates to the documentation ticket (if needed) 

## Acceptance Criteria
- [ ] Differences of the a11y guidance for the component has been documented (can be in this ticket)
- [ ] Recommendation has been shared with the team
- [ ] Documentation ticket has been updated with the revised text for a11y guidance (if needed)

**Comment by SarahKay8** [comment]
After a11y stand up, it was agreed to keep `role-alert` as it is equivalent to `aria-live-assertive`
User would  expect an error announcement immediately after leaving the field by a TAB key, otherwise critical information could be potentially omitted, as it tends to happen with polite.
