### ISSUE TITLE
USWDS v3 Memorable Date - Accessibility review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1301]
## Issue Description
We need to conduct a review of the accessibility guidance on USWDS for the Memorable date component  [(URL)](https://designsystem.digital.gov/components/memorable-date/) and compare it to the a11y guidance in the VA DS. [ (URL)](https://design.va.gov/components/form/memorable-date) 

## Tasks
- [x] Full accessibility review of the component is completed
- [x] Add descriptions of any issues found to this ticket
    - [x] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [x] If necessary, discuss any accessibility issues found with the engineer who developed the component
- [ ] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [ ] Component has been reviewed for accessibility issues
- [ ] Any accessibility issues have been addressed

**Comment by SarahKay8** [comment]
USWDS Memorable Date Dropdown A11y concerns - ![Image 12-19-22 at 1.33 PM.jpg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/e8ff4a60-9754-4b8f-8850-e6adb4e56568)

 If the mouse cursor is outside of the drop-down, users will most likely scroll down the page instead of the drop-down, hiding the drop-down options from the screen. In some browsers, however, the drop-down will actually scroll as long as it has focus, likely leaving users with erroneous data.


3) Inconsistent UI. The UI of drop-downs differs from browser to browser and OS to OS, and the drop-down will not only look different, but will also work differently. For example, on a Mac, Safari and Chrome force users to hover on an arrow to scroll up and down, whereas Firefox provides a traditional scrollbar. Some sites also use custom-designed drop-down UIs, which are also frequently observed to cause issues. 

VA - Separate Text Inputs 

Separate inputs are suggested because there is a cognitive value in having the separation of the parts more explicit. People with dyscalculia especially but other reading concerns may not be good at parsing a larger number, especially if they have to correct an error.

Hint Text - 

![Image 12-19-22 at 1.11 PM.jpg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/2c0d4154-0039-4725-88a9-2c9627a66f90)

After testing with VO.  `dateHint` Description is nested in `legend`. Name of entire `fieldset` is reading out  "Date of Birth please enter two digits for month and four digits for the year" 

We should move `dateHint` to a `span` or a `p` outside of `legend` within our fieldset to replicate USWDS 


Final - Keep current separate input fields like we currently have on the VA because there is a cognitive value in having the separation of the parts more explicit. 
and to also move `dateHint` outside of `legend`

**Comment by GnatalieH** [comment]
@SarahKay8 so you actually recommend not using the select box (dropdown) in this component? We're not sure why USWDS made the change, because formerly they used three input fields like the current VA Memorable date component. This is worth investigating. I'll create a variation with three text inputs, so we have options. @humancompanion-usds

**Comment by SarahKay8** [comment]
Yep we can definitely investigate some more! Thanks for making the second variation.

**Comment by caw310** [comment]
@humancompanion-usds please take a look at Sarah's findings.

**Comment by humancompanion-usds** [comment]
@caw310 - Let's put this on our list of things to talk to the USWDS team about.

**Comment by caw310** [comment]
Moving this back to reviewed/needs prioritizing until we know next steps and have a11y support.

**Comment by rsmithadhoc** [comment]
- A11y scan (Axe), mouse, and keyboard looked good to me.

## Screen Reader (VoiceOver + Safari)

I tested in Safari with VoiceOver, as that is the typical setup for my OS. However, Firefox and Chrome handled these better with less redundant information being read.

[Video of Main Version](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/2f0d0b26-fefa-4690-85dc-166138c96e53)

- Main Version
    - _"Please enter 2 digits for the month and day and 4 digits for the year"_ reads out awkwardly, adding a comma is a little bit better: _"Please enter 2 digits for the month and day, and 4 digits for the year"_
    - It reads the following twice for the *Month* field _"Date of birth Please enter 2 digits for the month and day and 4 digits for the year"_. It may be reading the form group's legend, then reading the `aria-described-by`.
    - It reads the full legend when tabbing to each field, which can be verbose and repetitive. 
    - On validation, focusing the input seems to happen before the error message, so it starts reading the field information for *Month* (which is verbose), then tries to read the error, but often times gets interrupted.
- With Month Select
    - On the version with additional hint text under the input, that additional hint text does not get read out.
    [Video of With Month Select](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/bea9db6d-851c-4497-b2cd-736cac15ca49)
- Error/Error With Month Select
    - The initial state shows the invalid input styling and error message, but there is no announcement that it is invalid. `aria-invalid=true` isn't applied in this initial state.
        [Video of initial error state not being conveyed](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/7e8aa86c-69a1-40e9-9ed8-9686e03f70f0)

**Comment by rsmithadhoc** [comment]
Created https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/64212 to fix these issues, closing this one out.
