### ISSUE TITLE
Move to deprecation phase 3 - RadioButtons React component

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1310]
## Description

We will deprecate Radio button React component  January 20, 2023

With the completion of the [Phase 2 ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1114), we will need to move the RadioButtons React component into [Phase 3](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components#General-deprecation-strategy). This means that the following steps will need to happen:

- Begin migrating any remaining instances of the React component ourselves. 
- The pace of this work will depend on the team’s availability and the priority of this work over other planned work and obligations.
- Once there are no more uses, remove the React component from the component-library repository

## Tasks
- [x] Check if the component is still being used in vets-website
- [x] If it is...
    - [x] Reach out to teams to check if they have an update pending.
    - [x] Migrate any remaining instances of the React component ourselves. 
    - [x] Once there are no more uses, remove the React component from the component-library repository
    - [x] Remove the ESLint rule
    - [x] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
- [ ] If it is not...
    - [ ] Remove the React component from the component-library repository
    - [ ] Remove the ESLint rule

## Acceptance Criteria
- [ ] Deprecated component has been removed entirely.

**Comment by caw310** [comment]
Deprecating radio button React component delayed until Dec 21 as a team needed more time to switch to the web component.

**Comment by caw310** [comment]
Carrying over into sprint 19 since work on this hasn't started yet. Deprecating radio button is slated for Jan 20.

**Comment by jamigibbs** [comment]
## vets-website usage of `RadioButtons` and Code Owners

Codeowners sourced from: https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/CODEOWNERS

### Claims & appeals (Benefits Team 1)
- [department-of-veterans-affairs/vsa-authd-exp-frontend](https://github.com/orgs/department-of-veterans-affairs/teams/vsa-authd-exp-frontend)
- [department-of-veterans-affairs/benefits-team-1-frontend](https://github.com/orgs/department-of-veterans-affairs/teams/benefits-team-1-frontend)

- [ ] /vets-website/src/applications/appeals/996/wizard/pages/claimType.jsx 
- [ ] /vets-website/src/applications/vre/28-1900/wizard/pages/start.jsx
- [ ] /vets-website/src/applications/vre/28-1900/wizard/pages/service-member/01-yesHonorableDischarge.jsx
- [ ] /vets-website/src/applications/vre/28-1900/wizard/pages/service-member/02-noVaMemorandum.jsx
- [ ] /vets-website/src/applications/vre/28-1900/wizard/pages/service-member/isServiceMember.jsx
- [ ] /vets-website/src/applications/vre/28-1900/wizard/pages/veteran/01-yesHonorableDischarge.jsx
- [ ] /vets-website/src/applications/vre/28-1900/wizard/pages/veteran/isVeteran.jsx

- [ ] /vets-website/src/applications/vre/28-8832/wizard/pages/BeginFormNow.jsx
- [ ] /vets-website/src/applications/vre/28-8832/wizard/pages/DischargeStatus.jsx
- [ ] /vets-website/src/applications/vre/28-8832/wizard/pages/Start.jsx
- [ ] /vets-website/src/applications/vre/28-8832/wizard/pages/VaEducationBenefits.jsx
- [ ] /vets-website/src/applications/vre/28-8832/wizard/pages/VREBenefits.jsx

- [ ] /vets-website/src/applications/disability-benefits/wizard/pages/appeals.jsx
- [ ] /vets-website/src/applications/disability-benefits/wizard/pages/start.jsx

---


### CTO Health Products

- [department-of-veterans-affairs/va-cto-health-products](https://github.com/orgs/department-of-veterans-affairs/teams/va-cto-health-products)

- [ ] /vets-website/src/applications/coronavirus-research/sign-up/config/va-location/DynamicRadioWidget.jsx
- [ ] /vets-website/src/applications/coronavirus-research/sign-up/containers/LocationPage.jsx
- [ ] /vets-website/src/applications/coronavirus-research/update/config/va-location/DynamicRadioWidget.jsx

- [ ] /vets-website/src/applications/coronavirus-vaccination-expansion/config/va-location/DynamicRadioWidget.jsx
- [ ] /vets-website/src/applications/coronavirus-vaccination-expansion/containers/IntroductionPage.jsx

---

### VSA Debt

- [department-of-veterans-affairs/vsa-debt-frontend](https://github.com/orgs/department-of-veterans-affairs/teams/vsa-debt-frontend)

- [ ] /vets-website/src/applications/financial-status-report/components/ResolutionDebtCards.jsx
- [ ] /vets-website/src/applications/financial-status-report/wizard/pages/Decision.jsx
- [ ] /vets-website/src/applications/financial-status-report/wizard/pages/Recipients.jsx
- [ ] /vets-website/src/applications/financial-status-report/wizard/pages/Reconsider.jsx
- [ ] /vets-website/src/applications/financial-status-report/wizard/pages/Repayment.jsx
- [ ] /vets-website/src/applications/financial-status-report/wizard/pages/Request.jsx
- [ ] /vets-website/src/applications/financial-status-report/wizard/pages/Start.jsx

---

### My Education Benefits Team

- [department-of-veterans-affairs/my-education-benefits](https://github.com/orgs/department-of-veterans-affairs/teams/my-education-benefits)

- [ ] /vets-website/src/applications/fry-dea/components/VeteransRadioGroup.jsx
- [ ] /vets-website/src/applications/toe/components/FirstSponsorRadioGroup.jsx

---

### Unknown??

- [ ] /vets-website/src/applications/post-911-gib-status/components/EducationWizard.jsx

**Comment by saderagsdale** [comment]
@Mottie Hey there - can you confirm which components in the "Claims & appeals (Benefits Team 1)" section need to be handled by the appeals team?

**Comment by jamigibbs** [comment]
After running the component usage report, I noticed that the remaining count for `RadioButtons` was not matching what was listed above.

I noticed that there was a `script` folder (outside of `src`) that was not accounted for that is owned by the VSP QA Standards team so I think we'll want to check-in with them well.

## VSP QA Standards

[department-of-veterans-affairs/qa-standards](https://github.com/orgs/department-of-veterans-affairs/teams/qa-standards) - Slack Channel (?): #platform-qa-standards

- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/start.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/service-member/01-yesHonorableDischarge.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/service-member/02-noVaMemorandum.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/service-member/isServiceMember.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/veteran/01-yesHonorableDischarge.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/veteran/isVeteran.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/BeginFormNow.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/DischargeStatus.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/Start.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/VaEducationBenefits.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/VREBenefits.jsx

**Comment by pjhill** [comment]
Working through this list of files --
## VSP QA Standards

[department-of-veterans-affairs/qa-standards](https://github.com/orgs/department-of-veterans-affairs/teams/qa-standards) - Slack Channel (?): #platform-qa-standards

- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/start.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/service-member/01-yesHonorableDischarge.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/service-member/02-noVaMemorandum.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/service-member/isServiceMember.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/veteran/01-yesHonorableDischarge.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2a/wizard/pages/veteran/isVeteran.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/BeginFormNow.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/DischargeStatus.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/Start.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/VaEducationBenefits.jsx
- [ ] /vets-website/script/github-actions/daily-product-scan/tests/mocks/applications/app-2/app-2b/wizard/pages/VREBenefits.jsx

**Comment by caw310** [comment]
Carrying over due to just a few more React radio buttons.

**Comment by jamigibbs** [comment]
I am still seeing 1 usage of `RadioButtons` in vets-website but I believe this is a false positive. 

There is a custom built React component that was forked from DST also named `RadioButtons` in the GI Comparison Tool app but it is not related to the design system version. This is part of `/education/gi-bill-comparison-tool` here: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/gi/components/RadioButtons.jsx

**Comment by caw310** [comment]
This is done!!!
