### ISSUE TITLE
Create documentation on testing component changes on vets-website. 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1312]
## Description
This is an action item from retro for sprint 12. 
Create documentation on testing component changes on vets-website. 
Jhonny and Jami to work together on this  w/ Brooks to sign off.

## Tasks
- [ ] Find Slack messages that have information on testing component changes on vets-website
- [ ] Draft documentation with what's been described in Slack on testing component changes on vets-website
- [ ] Have Brooks review and sign off

## Acceptance Criteria
- [ ] Brooks has approved documentation 
- [ ] Documentation has been shared with the DST

**Comment by jamigibbs** [comment]
Slack reference: https://dsva.slack.com/archives/G01BJ3ESXL4/p1645627986332699

**Comment by caw310** [comment]
Moving back to reviewed/needs prioritizing as we aren't quite ready to work on this documentation.

**Comment by Andrew565** [comment]
My recent findings in trying to test component changes:

1. In the component-library repo, go to the packages/web-components folder.
2. Type in ` YARN_IGNORE_PATH=1 yarn link`. The YARN_IGNORE_PATH part tells yarn to use the older version of yarn link, necessary because component-library uses Yarn v3, but the vets-website repo is still using Yarn v1.
3. Switch over to the vets-website repo
4. Type in yarn link @department-of-veterans-affairs/web-components
5. (optional, I think) It may be wise to run yarn at this time to make sure it sets up the link properly, but this is probably unnecessary (YMMV, not a doctor)
6. Change imports to point to the new link, (e.g. change import { VaTextInput } from '@department-of-veterans-affairs/component-library/dist/react-bindings'; to import { VaTextInput } from '@department-of-veterans-affairs/web-components/react-bindings';) (note that when pointing to the web-component react-bindings, the ‘dist’ directory isn’t needed)
7. Run yarn watch in the vets-website repo and enjoy!

Unfortunately, webpack’s current configuration isn’t setup to properly detect changes in the ‘link’ folder, (followSymlinks probably needs to be turned on, but not going to mess with that right now as it’s my bed time). The solution for now when you want to test a new change is this:

1. Go to component-library/packages/web-components  and make your change
2. Run yarn build-bindings
3. Go to vets-website repo, use Ctrl-C to quit the webpack server if it’s running
4. Run yarn build && yarn watch to re-build with the latest updates and then serve them up again.

This is what Hot Module Replacement is supposed to fix, but it’s not quite there yet for our purposes. If I get annoyed at the manual re-building enough tomorrow I’ll see if I can find a way to smooth it out (like applying the followSymlinks flag). Heading to bed, hope all this makes sense in the morning!

**Comment by humancompanion-usds** [comment]
Is this issue still relevant @jamigibbs and @caw310? Can you update it? Thanks.

**Comment by jamigibbs** [comment]
We have [documentation for using Verdaccio](https://github.com/department-of-veterans-affairs/component-library?tab=readme-ov-file#local-testing-in-vets-website-with-verdaccio) so this can be closed.
