### ISSUE TITLE
Radio button option web component with description text- Development

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#1324]
## Description

- Update radio button option web component allow for description text.

## Details
- This will match [USWDS design of adding description text within the `label`](https://designsystem.digital.gov/components/radio-buttons/)

## Tasks
- [X] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Add description text property
- [ ] Update web component in Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review (if necessary) 
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and updated in Storybook
- [ ] Component has had design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by jamigibbs** [comment]
There was a duplicate issue created related to this: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1373 Completion of this work should close both of these issues.
