### ISSUE TITLE
Discovery: How to incorporate USWDS components into Storybook 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1331]
## Description
There's an issue in Storybook when incorporating a USWDS v3 component where Formation causes issues. Discovery work is needed to identify the best way to resolve this issue. 
Options that have been suggested:
- identify smallest piece of formation we need 
- Test different instance of Storybook 
- Would adding stylesheet toggle work - https://storybook.js.org/addons/storybook-stylesheet-toggle

## Tasks
- [ ] Identify the smallest piece of Formation that is needed and run test to see if there are impacts we don't want
- [ ] Look into feasibility of a different instance of Storybook 
- [ ] Look into Stylesheet toggle add on 
- [ ] Identify the pros and cons of each, and make a recommendation to present to the team 

## Acceptance Criteria
- [ ] Write up findings for each option 
- [ ] Present to the team the recommendation

**Comment by bkjohnson** [comment]
Since storybook doesn't have true pages for each component, I don't think that we'll be able to limit certain global CSS for the `html` element to particular pages with a CSS-only solution. Something I did come up with a bit of exploring that could work is to _dynamically_ undo the font-size changes from `formation` with a script like this:

```js
  // The condition would assume that we are at a path such as:
  // design.va.gov/storybook/?path=/docs/uswds-va-radio--default
  if (location.href.includes('uswds')) {
      // Set the root font-size to something that will be compatible with USWDS3
      document.documentElement.style.fontSize = "10px";
  }
```

**Comment by jamigibbs** [comment]
Having both Formation and v3 components on the same Storybook page was my biggest blocker. I like what where you're going with putting a USWDS v3 component on its own page that we can control though @bkjohnson. 

I think an entirely new Storybook instance would be too heavy handed but integrating them "separately" into the existing Storybook is a nice compromise. We might not necessarily need a completely new section (unless that ends up being the preferred way to present them). I can explore what that might look like as part of this discovery.

**Comment by jamigibbs** [comment]
### 1. Stylesheet toggle add-on

I installed the [Storybook Stylesheet Toggle](https://storybook.js.org/addons/storybook-stylesheet-toggle) add-on and what this does is it adds an additional menu item to Home page of Storybook. The toggle looks like this:

![Screen Shot 2022-11-14 at 12 50 34 PM](https://user-images.githubusercontent.com/872479/201742105-e2206f53-de95-4c58-8ca3-930318d03489.png)

- Useful for _global_ style changes. I don't believe we can override root elements this way though (`html` & `body`).
- Very low effort to integrate following the add-on's documentation.
- Requires a manual toggle for the style change.
- Has not been updated in 2 years.

### 2. Different instance of Storybook

- A new Storybook instance would be created just for USWDS v3 versions of components.
- The benefit of a dedicated Storybook instance would be that Formation styles would be entirely removed and all styles would be from USWDS v3.
- This would likely require a separate repo that would essentially just be a mirror of the component-library.
https://storybook.js.org/docs/react/get-started/install

![Screen Shot 2022-11-15 at 1 06 47 PM](https://user-images.githubusercontent.com/872479/202004564-dd2d3ef5-b3c6-48b0-b591-9fd5477b68fe.png)

- With two different instances, it's possible to [compose multiple Storybook instances](https://storybook.js.org/docs/react/sharing/storybook-composition#compose-published-storybooks) into one with a URL to a statically built Storybook. USWDS v3 would still be its own separate section though.

### 3. Dynamic CSS on current Storybook instance

- The Formation styles we need to toggle is relatively small although more may be revealed as we continue development:
   - `body`
   - `html`
   - `.usa-label`
   - `button`
- A new Storybook section would be created for the USWDS version of components so that we can control the full page.
- Low effort and quickly gets us going but adds some future maintenance (eventually we will want to clean this up when Formation is removed).

![Screen Shot 2022-11-15 at 10 22 24 AM](https://user-images.githubusercontent.com/872479/201972042-9462c509-f15f-4ff4-be4b-190449ab4283.png)

- Each would have their own storybook page but it's technically the same `va-radio` component:

![Screen Shot 2022-11-15 at 10 46 15 AM](https://user-images.githubusercontent.com/872479/201977641-1cd41d5f-d510-4e08-8297-0fb8599e4b57.png)

- Having a dedicated section for USWDS v3 makes it easier for us to display USWDS v3 specific examples. Mixing the v1 and v3 examples together could get confusing like here: https://1265-uswds-radio-button--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-radio--default#stories
- The USWDS example would be it's own page link (rather than just linking to the existing va-button). For example:
http://localhost:6006/?path=/docs/components-va-radio--default
http://localhost:6006/?path=/docs/uswds-va-radio--default

Example of what the "dynamic switcher" script might look like for `html` and `body` tags:

`packages/storybook/.storybook/preview.js`

```js
document.body.onload = function () {
  // Initial page load dynamic styles.
  location.href.includes('uswds') ? addUswdsStyles() : addFormationStyles();

  // Each time the page URL changes.
  window.addEventListener('locationchange', (event) => {
      location.href.includes('uswds') ? addUswdsStyles() : addFormationStyles();
  });
};
```

Other styles that can override globally can just be added to `packages/storybook/.storybook/preview-head.html`:

```css
  .usa-label { font-size: 16px!important; }
  button { padding: 10px 20px!important; }
  h1 {  font-size: 32px!important; }
```

**USWDS v3 Styles for Storybook**

```css
html { font-size: 16px; }
body { font-size: 16px; }
button { padding: 10px 20px; } 
h1 { font-size: 32px; }
.usa-label { padding: 1px 6px; font-size: 16px; }
```
**Formation Styles for Storybook**

```css
html { font-size: 10px; }
body { font-size: 1.6rem; }
button { padding: 1rem 2rem }
h1 { font-size 2em; }
.usa-label { padding: 0.1rem 0.7rem; font-size: 1.5rem; }
```

### Long Term Maintenance Considerations
- Dynamic styles: If we will continue to use the same Storybook instance, similar to how we have been deprecating React components, we will probably want to move USWDS examples back into the "Components" section when Formation is removed so there will be some cleanup down the road (including any external links to the USWDS section).
- Two Storybook Instances: Maintaining two different Storybook instances could have a lot of overhead if we need to manage two different repos or expand our monorepo even larger to accommodate two Storybooks.
