### ISSUE TITLE
Update va-textinput web component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1334]
## Description
The Textinput web component needs to be updated to include two more text input with hint text examples. 

## Details
Missing from Storybook are the hint text examples for text input (https://design.va.gov/components/form/#hint-text)
Text input with the “Default hint text”
Text input with “Inline within the label”

![Screenshot 2022-11-10 at 10 50 12 AM](https://user-images.githubusercontent.com/72393213/201208148-224c4390-ebfa-49bb-bf9f-caeb93efd3ed.png)
![Screenshot 2022-11-10 at 10 50 28 AM](https://user-images.githubusercontent.com/72393213/201208154-944df9c0-afde-44aa-a6ac-9beee0c3eada.png)

## Tasks
- [ ] update va-text input with Text input with the “Default hint text” and Text input with “Inline within the label” (see screenshots) 
- [ ] update Storybook with the examples 
- [ ] Review the updates with designer (confirm with Natalie that updates match Sketch library designs)
## Acceptance Criteria
- [ ] Component is updated in Storybook
- [ ] Component has had design review

**Comment by jaredcunha** [comment]
The default hint text pattern is something that has come across our radar recently, and I thought I might add a couple thoughts. 

The text input should have a programmatic link to the hint text with `aria-describedby`, which the [VA hint text example](https://design.va.gov/components/form/#default-hint-text) does not have. This will be very important for screen readers using tab navigation in order to ensure that the hint text is announced after the label, since this hint text is not in the tab order.

I think that would require more than just updating the hint storybook examples.

There are probably two approaches that can be taken here:

### Add `ariaDescribedby` prop to `va-text-input`:
```jsx
<va-text-input
  label="Veteran’s Social Security number"
  name="my-input"
  ariaDescribedby="my-input-hint"
>
  <span id="my-input-hint" class="vads-u-color--gray-medium vads-u-display--block">
        This is the hint text.
  </span>
</va-text-input>
```
- Pro: Can use `ariaDescribedby` to point to any `id`
- Con: Hint text HTML is error-prone because it requires two utility classes. Alternatively, you can create a `va-hint-text` component.

### Add a `hintText` prop to the component. 
```jsx
<va-text-input
  label="Veteran’s Social Security number"
  name="my-input"
  hintText="This is the hint text"
/>
```
- Pro: Easier for developers to implement
- Con: Lacks flexibility

I think if you went this route, it might be worth rewriting [this heading](https://design.va.gov/storybook/?path=/docs/components-va-text-input--default#with-hint-text) to avoid confusion in what **hint text** actually refers to. Or just use something `simpleHint` instead of `hintText`.

**Comment by joshkimux** [comment]
To add onto Jared's fantastic comments, would it be possible for us to also explore increasing the contrast of the hint text? As of now it barely scrapes past AA compliance and [may not be enough for folk with low vision looking at their mobile phone in daylight (who can use)](https://www.whocanuse.com/?bg=ffffff&fg=71767a&fs=16&fw=)

<img width="1040" alt="Screenshot 2023-02-09 at 11 10 00 AM" src="https://user-images.githubusercontent.com/14154792/217869600-2b66cd56-a8e6-4503-a8d0-21d76d13d807.png">

A small adjustment from AA (4.5) to AAA (7.0) may do the trick:

### Before
<img width="611" alt="Screenshot 2023-02-09 at 11 11 17 AM" src="https://user-images.githubusercontent.com/14154792/217869795-daf4c9a2-b578-421e-b1eb-c03274634420.png">

### After
<img width="592" alt="Screenshot 2023-02-09 at 11 12 41 AM" src="https://user-images.githubusercontent.com/14154792/217870178-62de9f73-5ae1-4673-98e4-b7f9fa109bde.png">

**Comment by jamigibbs** [comment]
Thanks for the feedback @joshkimux!

DST currently doesn't have a lot of resources to tackle this in the coming sprint but @jaredcunha I wonder if you or someone else familiar with this request had capacity to [submit a pull request](https://design.va.gov/about/developers/contributing#modifying-existing-components) for the design system? I know we recently did some work for `va-text-input` and `aria-describedby` recently that might help with a solution here as well: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24502

Also since this ticket was written and your solutions were suggested, [the `va-text-input` component has had a hint prop added](https://design.va.gov/storybook/?path=/docs/components-va-text-input--with-hint-text) so we will want to continue using that approach.

Lastly, the [`va-memorable-date` component is currently under development](https://github.com/department-of-veterans-affairs/component-library/pull/628) so we might want to pause any any significant changes until that work is merged in the coming week.

**Comment by humancompanion-usds** [comment]
Supplemental Claims has shipped. Did this get resolved?

**Comment by joshkimux** [comment]
@humancompanion-usds unfortunately no, [the major issue has launched with supplemental claims](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54215) as it wasn't launch-blocking. We'd want to address this asap when it's fixed in the design system.

**Comment by humancompanion-usds** [comment]
@joshkimux - RE: Hint text. We don't have a gray that passes at AAA that also is distinct enough from our label color (#212121). For example, here is $color-gray-warm-dark which passes AAA:

<img width="361" alt="Screen Shot 2023-04-19 at 10 24 20 AM" src="https://user-images.githubusercontent.com/52176351/233105881-9aa02a16-ae04-45bd-8d72-1afdf67f7553.png">

I'm not sure I can make out the difference. Perhaps I'm old and my eyesight is definitely terrible, but I struggle to differentiate the label and the hint text. Perhaps if we made the label color darker (#000000) we could get away with it:

<img width="337" alt="Screen Shot 2023-04-19 at 10 26 43 AM" src="https://user-images.githubusercontent.com/52176351/233106589-0bd42923-1799-485b-bfaa-8a677c37a230.png">

But then our labels would be slightly darker than our base text. Regardless we should separate the hint-text color out as a distinct issue for discussion.

**Comment by humancompanion-usds** [comment]
Also, #595959 isn't in the USWDS. If you want to suggest a gray in the USWDS that is distinct enough from our base color and passes AAA then we can look at this once we upgrade to v3.

**Comment by joshkimux** [comment]
@humancompanion-usds 

> I'm not sure I can make out the difference. Perhaps I'm old and my eyesight is definitely terrible, but I struggle to differentiate the label and the hint text. Perhaps if we made the label color darker (#000000) we could get away with it:

As someone who can barely see a computer screen, yes 😆 

> But then our labels would be slightly darker than our base text. Regardless we should separate the hint-text color out as a distinct issue for discussion.

This is really good feedback. I'll write out a separate bug ticket to explore this issue from a more holistic perspective. It's relatively less urgent compared to the primary issue at hand here (programmatic linking of hint text to input).

> Also, #595959 isn't in the USWDS. If you want to suggest a gray in the USWDS that is distinct enough from our base color and passes AAA then we can look at this once we upgrade to v3.

This was a potato brain moment for me, don't know why I suggested a non-USWDS color. I'll make sure the new ticket addresses this from the lens of a particular contrast requirement to leave the door open on how we approach it.
