### ISSUE TITLE
Set up CSS Class linting rule 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1343]
## Description
We need a way for VFS teams to easily update to the new CSS Class library based on USWDS v3. This ticket is to do the work to write a linting rule for this. 

## Tasks
- [x] Write a linting rule for teams to easily update to the new CSS Class library 
- [x] Test that this works 
- [ ] Review with DST engineers
- [ ] Draft announcement that is shared with DST for feedback

## Acceptance Criteria
- [x] Linting rule created for VFS teams

**Comment by bkjohnson** [comment]
The goal of this linting rule would be to identify uses of current `formation` [utility classes](https://design.va.gov/foundation/utilities/), like `vads-u-background-color--primary` and flag them. We may want to go with ESLint's Suggestions API that we've been using so far instead of an auto-fixable rule. The reason we might want to avoid an auto-fixable rule for this is that since these new utility classes lack the `!important` on their declarations, the reduced specificity could break styling [as this discovery showed](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/860#issuecomment-1170609546). Having the rule make a suggestion could help with migration while still providing more opportunity for FE developers to test the change instead of just assuming that whatever changes made by an auto-fix are working.

**Comment by jhonnyoddball** [comment]
@humancompanion-usds I added the instructions in the [open ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1404)'s description
