### ISSUE TITLE
Fix  va-radio button alignment 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1345]
## Description
There are alignment issues with the radio button web component. It has padding on the left that is not necessary and needs to be removed. 

## Details
The issue was brought to our attention by Robin who is using both the React radio button and va-radio on a form. It's causing some weirdness when going between pages. 

See Sack discussion with examples. 
https://dsva.slack.com/archives/C01DBGX4P45/p1668705952675849

Related design update ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1346

## Tasks
- [ ] Fix alignment of va-radio - remove the left padding
- [ ] Update all variations in Storybook  https://design.va.gov/storybook/?path=/docs/components-va-radio--default
- [ ] Touch base with designer fi you have any questions 

## Acceptance Criteria
- [ ] va-radio doesn't not have left padding
- [ ] Storybook examples are updated

**Comment by jamigibbs** [comment]
I'm doing a little discovery to understand the different radio component padding variations and I'm seeing an interesting divergence with the forms library that I'm not sure that I understand.

**Forms Library**
![Screen Shot 2022-11-29 at 3 57 22 PM](https://user-images.githubusercontent.com/872479/204657482-40ca8b04-3803-4395-9017-9bb7e3bccbb2.png)

**React Component ([as previously displayed in Storybook](https://storybook-move-va-privacy-agreement--60f9b557105290003b387cd5.chromatic.com/?path=/docs/deprecated-radiobuttons-react--aria-describedby))**

![Screen Shot 2022-11-29 at 3 57 13 PM](https://user-images.githubusercontent.com/872479/204657616-b5c0c3ac-8941-417f-bc79-0d7acfe0e118.png)

**Web Component ([currently in Storybook](https://design.va.gov/storybook/?path=/docs/components-va-radio--default))**

![Screen Shot 2022-11-29 at 3 57 45 PM](https://user-images.githubusercontent.com/872479/204657573-21c244e4-a1ac-451a-a32b-eb6cec533f5d.png)

What I'm seeing is that the React and Web Components both had/have the left padding on the options but the forms library does not for some reason. Also the forms library version does not have as much space between options as the React component in Storybook.

**Comment by caw310** [comment]
USWDS version doesn't indent. 
12 pixel margin in between the options.
