### ISSUE TITLE
Update Radio Button designs 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1346]
## Description
There are alignment issues with the radio button design screenshots on design.va.gov and in Sketch. It has padding on the left that is not necessary and needs to be removed.

## Details
The issue was brought to our attention by Robin who is using both the React radio button and va-radio on a form. It's causing some weirdness when going between pages. The va-radio button web component will be fixed but designs also need to be updated to reflect the correct alignment. 

See Sack discussion with examples.
https://dsva.slack.com/archives/C01DBGX4P45/p1668705952675849

## Tasks
- [ ] Update radio button alignment in Sketch library 
- [ ] Update radio button examples on design.va.gov  https://design.va.gov/components/form/radio-button
- [ ] Share updates with DST engineer who is working on the web component fix

## Acceptance Criteria
- [ ] Sketch library is updated
- [ ] Radio button examples on design.va.gov have been updated

**Comment by humancompanion-usds** [comment]
Please note that it looks like there is a difference in spacing between the radio buttons as well in the Forms library versus web-component. Please investigate and determine the correct course of action.

**Comment by GnatalieH** [comment]
[Here is a link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/R18WG5Z) to the new Radio button designs.

**Comment by humancompanion-usds** [comment]
Does 10px between radio options match the Forms library? That is what I need clarity on.

**Comment by GnatalieH** [comment]
> Does 10px between radio options match the Forms library? That is what I need clarity on.

@jamigibbs can you answer this? I'm not 100% sure if the radio buttons I can inspect on VA.gov are coming from the forms library or not.

**Comment by jamigibbs** [comment]
@humancompanion-usds @GnatalieH It looks like Forms Library style (which is coming from Formation) is calculating to 16px:

![Screen Shot 2022-11-30 at 12 53 14 PM](https://user-images.githubusercontent.com/872479/204884268-60c99d30-0c65-4534-9cd7-3d3ba68b8280.png)

USWDS v3 is showing 12px:

![Screen Shot 2022-11-30 at 12 55 08 PM](https://user-images.githubusercontent.com/872479/204884530-b0a9003f-ea18-47f2-9bee-08fdba5c419c.png)

**Comment by GnatalieH** [comment]
Thanks @jamigibbs. 16px is excessive and makes the radio button options almost look unrelated to each other. I'm fine with using 12px. I just am hoping we can use the same value between the legend and the first option as we do between the radio options themselves. That's what I wanted to resolve through my updated designs.

**Comment by GnatalieH** [comment]
Completed. [Here are the designs](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/R18WG5Z) in Sketch.
