### ISSUE TITLE
Audit of segmented progress bar component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1347]
## Description
The check-in team submitted an experimental design request to modify the segmented progress bar (https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1333). During DSC discussion, a number of questions came up that lead to the realization that we should do an audit to understand how this is used. 

https://design.va.gov/components/form/progress-bar-segmented

## Tasks
- [ ] Find examples of how segmented progress bar is currently used
- [ ] Compile screenshots of use
- [ ] Share findings with DST 

## Acceptance Criteria
- [ ] Link to screenshots shared with team
- [ ] Findings presented
