### ISSUE TITLE
Add ESLint warning for Radion Button React component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1353]
## Description
We need to move the Radio button  React component to phase 2 of the [deprecation process](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components).

## Tasks
- [ ] Check that all bugs related to radio button have been fixed 
- [ ] Create an ESlint warning for the React radio button component 

## Acceptance Criteria
- [ ] ESlint warning is active when React radio button is used

**Comment by caw310** [comment]
Closing as this work has been done already.
