### ISSUE TITLE
Deprecation - OMBInfo React component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1359]
## Description

Per team discussion, we are sunsetting our previous phased deprecation strategy in favor of directly migrating components ourselves. Migration steps look like this:

1. Submit PR, let the email go out, wait a day. If no action:
2. @ the team(s) directly with a comment on the PR. Wait a day. If no action:
3. Message the team(s) directly in slack, requesting a review.  Wait a day. If no action:
4. Merge pull requests.

## Tasks
- [x] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
- [x] Remove the React component from the component-library repo:
    - [react-components](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/react-components) package
- [x] Remove the related web component(s) from the [web component migrations list](https://design.va.gov/about/developers/using-web-components#web-component-migrations)
- [ ] Remove any ESLint rules from [vets-website](https://github.com/department-of-veterans-affairs/vets-website) and the [eslint-plugin](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/eslint-plugin).
- [ ] React Component deprecation has been completed following the above process

## Acceptance Criteria
- [ ] Deprecated component has either been removed entirely (if no longer in use) or moved to the next stage of the deprecation process.

**Comment by jhonnyoddball** [comment]
There are currently 25 instances of OMBInfo React component

![Screenshot 2023-03-24 at 3 15 57 PM](https://user-images.githubusercontent.com/55560129/227619286-c1ea389a-956c-4ec6-b8e3-7b01932ab6f0.png)

**Comment by micahchiang** [comment]
21 remaining instances. All of them take the 3 standard OMBInfo props. Some of the expiration dates are past, so we may want to do VFS teams the courtesy of letting them know, but it isn't our responsibility to update the expiration dates ourselves. 

All usages are on the introduction pages of various forms. Locally, these should be accessible by using the `rootUrl` in an application's `manifest.json` file to verify the update doesn't introduce any regressions. `<va-omb-info>` is already being used extensively, so we'll likely only need to do minimal testing.

**Comment by it-harrison** [comment]
vets-website app code PRs waiting for approval:
* [25716](https://github.com/department-of-veterans-affairs/vets-website/pull/25716)
* [25713](https://github.com/department-of-veterans-affairs/vets-website/pull/25713)
* [25718](https://github.com/department-of-veterans-affairs/vets-website/pull/25718)
* [25719](https://github.com/department-of-veterans-affairs/vets-website/pull/25719)

**Comment by it-harrison** [comment]
* [Component library PR](https://github.com/department-of-veterans-affairs/component-library/pull/854/files)
* component already removed from migration list
