### ISSUE TITLE
Move to Deprecation Phase 2 - System down view

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1361]
We need to move the System down view React component to phase 2 of the [deprecation process](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components).

This means we need to check to see if the component is still being used in vets-website. If it is, we need to update the ESLint rule to be an error instead of a warning, remove the Storybook story for the component (but leave it in the component-library repo), create a ticket for following up with the teams still using the component, and announce that in 6 weeks/3 sprints we will be deprecating the component completely and advise teams to upgrade to the web component ASAP.

**See "Deprecating React Components - DST Engineers" for additional guidance** https://vfs.atlassian.net/wiki/spaces/DST/pages/2537455918/Deprecating+React+Components+-+DST+Engineers

If it is no longer being used, we can remove the ESLint rule altogether and remove the component from the component library.

Note: We will not build a web component version. 

## Tasks
- [ ] Check if the component is still being used in vets-website
- [ ] If it is...
    - [ ] Set ESLint rule to an error
    - [ ] Remove deprecated component from Storybook (but keep the component in the component-library repo)
    - [ ] Create a ticket for advancing to [deprecation phase 3](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components) in 6 weeks.
    - [ ] Announce in #vfs-change-announcements that the React component will be deprecated in six weeks (three sprints).
- [ ] If it is not...
    - [ ] Remove the deprecated component from the component library and Storybook
    - [ ] Remove the ESLint rule

## Acceptance Criteria
- [ ] Deprecated component has either been removed entirely (if no longer in use) or moved to the next stage of the deprecation process.

**Comment by jhonnyoddball** [comment]
There are currently 2 instances of SystemDownView React component

![Screenshot 2023-03-24 at 10 54 41 AM](https://user-images.githubusercontent.com/55560129/227560216-4729ec3c-3683-4727-9b9c-3e70dc5687e5.png)

**Comment by caw310** [comment]
Deprecation phase 2 will be done as part of a ticket where all remaining React components will be in phase 2. [Deprecation Phase 2 of React components #1637](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1637)

Will write a ticket for moving this to Phase 3.

**Comment by caw310** [comment]
Closing as this was done as part of this overall work to put all remaining react components into Phase 2. https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1637
