### ISSUE TITLE
Maintenance Banner  - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1363]
## Description
Update Sketch artifacts for Maintenance Banner as/if needed as we will be building a Maintenance Banner web component. 

If this is a pattern or component that is already in existence, conduct a small-scale audit (3-5 examples) to make sure there aren't design issues that need to be addressed. Also, check the Design System Team backlog for outstanding design issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this design and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
[add links to any tickets or documents with details about the design]
[add links to any research documents related to the component]

## Tasks
- [x] Conduct small audit if necessary (if component already exists and we are building a new version)
- [x] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Merge with color scheme of MVP and determine if it should follow v3 of Alert or be it's own thing.

**Comment by babsdenney** [comment]
This is ready for review. 
[Sketch file](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/qbKabbd)

I used the style of the maintenance banner and the dimensions, spacing, and font styles of the USWDS.
[USWDS Alert](https://designsystem.digital.gov/components/alert/)
[VA Maintenace banner](https://design.va.gov/storybook/?path=/story/components-banners-maintenancebanner--before-maintenance)

**Comment by humancompanion-usds** [comment]
@babsdenney - Looks good. For the red maintenance banner I would stick to the darker red we use for our error Alert for now (or the USWDS red-warm-50v which is their error state).

**Comment by babsdenney** [comment]
@humancompanion-usds Thank you for the feedback! The color has been updated and will close this out.
