### ISSUE TITLE
Update v1 of radio button va-radio with tile prop

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1373]
## Description
There was a request from Robin to add description to the radio button component which is in USWDS v3 radio button which we are working on to add to DS but we need to add the tile prop to v1 so that it is available now for teams to use. 

## Details
Here are other tickets and PRs related to this work. 

- [https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/is[…]ent-of-veterans-affairs/vets-design-system-documentation/1324](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1324)
- https://github.com/department-of-veterans-affairs/component-library/pull/535
- https://github.com/department-of-veterans-affairs/component-library/pull/535#discussion_r976653771
- https://github.com/department-of-veterans-affairs/component-library/pull/535#discussion_r982951706
- https://github.com/department-of-veterans-affairs/component-library/pull/564

## Tasks
- [ ] Update va-radio with tile prop
- [ ] Update Storybook and design.va.gov
- [ ] Ping designer for design review if needed

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had a final review

**Comment by jamigibbs** [comment]
The [v3 version](https://github.com/department-of-veterans-affairs/component-library/pull/579) of `va-radio-option` has a prop for `tile` and `description` which we can use in the v1 markup too.
