### ISSUE TITLE
Discovery: Forms Library updates needed for React component deprecation

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1375]
## Description
The purpose of this work is to determine what needs to be updated in the [Forms Library](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/platform/forms-system) as well as the level of effort required to allow for the continued deprecation of Design System React components.

There are currently two different forms systems ([Forms System Core](https://github.com/department-of-veterans-affairs/va-forms-system-core) and [Forms Library](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/platform/forms-system)). What we are talking about here is the original Forms Library located within vets-website. We are not evaluating Forms System Core.

## Details
Some questions that need to be answered as part of this discovery:
- [x] How many React design system components (imported directly from the component library) are being used in the Forms Library? 
- [x] How are those React components being used and where are they located in Forms Library?
- [x] What would it take to allow us to continue our deprecation for these?
- [x] Do we need to incorporate any web components? If so, where?
- [x] For the widgets/components in the Forms Library, are all of these widgets/components just using styling from Formation (for example, [RadioButtons](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/widgets/RadioWidget.jsx) is not directly using the component library)? Are there any blockers with these types of components/widgets that would stop us from continuing our deprecation process? Or will it be fine to just allow them to continue using Formation?
- [x] Based on the results of the above questions, what would be an estimated level of effort to update the Forms Library so that our [deprecation plan](https://vfs.atlassian.net/wiki/spaces/DST/pages/2437349652/Deprecation+Plan+for+React+Components+2023) is not blocked?

## Tasks
- [x] Review the Forms Library so that the questions above are answered.

## Acceptance Criteria
- [x] We have a clear understanding of the work that needs to be done for updating the Forms Library with an estimated level of effort.

**Comment by jamigibbs** [comment]
I did a search for component imports using `@department-of-veterans-affairs/component-library/` and the results from that returned just these four React components:

- TextInput
- Checkbox
- AdditionalInfo
- Telephone

![Screen Shot 2022-12-02 at 10 10 54 AM](https://user-images.githubusercontent.com/872479/205336015-65331a50-265c-4f2d-850d-1e1075a43f48.png)

**Comment by humancompanion-usds** [comment]
@nickjg231 - Once you have this information please share with @ndsprinkle on the Veteran-facing forms team. Then the three of us should get together and discuss next steps. The two teams may be able to work together on this deprecation initiative.

**Comment by nickjg231** [comment]
Notes for this card can be viewed [in this document](https://docs.google.com/document/d/1Lw_BSpnePnKKWTR_pXlDEUqg9EPGLowGma6jpbGo5bg/edit). Andrew Steele to write up the subsequent cards related to each component.
