### ISSUE TITLE
Deprecation Phase 1: ExpandingGroup React component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1378]
## Description
We need to begin deprecation of the ExpandingGroup React component. This means we need to check to see if the component is still being used in vets-website. If it is, we need to add an ESLint rule to be a warning, remove the Storybook story for the component (but leave it in the component-library repo), and announce that in 6 weeks/3 sprints we will be deprecating the component and advise teams to upgrade to the web component ASAP.

If it is no longer being used, we can remove the ESLint rule altogether and remove the component from the component library.

## Details
- Address any bug tickets in the backlog.
- Announce that React component will be deprecated in six weeks (three sprints). Request that teams migrate to the web component as soon as possible. If there are issues with the web component that prevent teams from migrating, request that they file a bug ticket.
- If it doesn’t already exist, add an ESLint warning with an easy migration option if possible.  
- Address all bug tickets submitted for the corresponding web component that will replace the React component. We will not move forward with the next phase until all bug tickets have been addressed.

## Tasks

- [x] Check if the component is being used in vets-website
- [x] If it is...
    - [x] Create an ESLint rule and set it to warning.
    - [x] Move the deprecated component in Storybook to the deprecated section.
    - [x] Create a ticket for advancing to [deprecation phase 2](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components) in 6 weeks.
    - [x] Announce in `#vfs-change-announcements` that the React component will be deprecated in six weeks (three sprints).
- [ ] If it is not...
    - [ ] Remove the deprecated component from the component library and Storybook
    - [ ] Remove the ESLint rule

## Acceptance Criteria
- [ ] Deprecated component has either been removed entirely (if no longer in use) or moved to the next stage of the deprecation process.

**Comment by jamigibbs** [comment]
In previous discussions about which component should replace this one, we were thinking that either [va-additional-info](http://localhost:6006/?path=/docs/components-va-additional-info--default) or [va-accordion](http://localhost:6006/?path=/docs/components-va-accordion--default) could be used.

But there is a significant functional difference between what those components do and how ExpandingGroup is being used. va-additional-info and va-accordion trigger content based on a text label where this component is triggered based on other user interaction done outside of the component (it reveals elements that become relevant based on a user's response).

It's not clear if we have a path forward for developers if we deprecate this component with the way it's currently being used. 

**Some examples from vets website:**

1. https://staging.va.gov/burial-poc-v6/

    - Click "Continue"
    - Click "Other"
    - Another input field reveals.

![Screenshot 2023-02-10 at 11 13 09 AM](https://user-images.githubusercontent.com/872479/218155164-0c7891d7-daad-4559-9454-09b57c273217.png)

2. https://staging.va.gov/education/gi-bill-comparison-tool/?search=name&name=Northern%20Illinois%20University&excludedSchoolTypes%5B%5D=PUBLIC&excludedSchoolTypes%5B%5D=FOR%20PROFIT&excludedSchoolTypes%5B%5D=PRIVATE&excludedSchoolTypes%5B%5D=FOREIGN&excludedSchoolTypes%5B%5D=FLIGHT&excludedSchoolTypes%5B%5D=CORRESPONDENCE&excludedSchoolTypes%5B%5D=HIGH%20SCHOOL

    - Select "VET TEC Providers"
    - Another filter selection reveals

![Screenshot 2023-02-10 at 11 14 40 AM](https://user-images.githubusercontent.com/872479/218155177-22702a9b-12c2-47df-85c1-a19ac5b48bd7.png)

3. https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction

    - Select any radio option
    - More information about the select option appears.
   
![Screenshot 2023-02-10 at 11 17 25 AM](https://user-images.githubusercontent.com/872479/218155190-c37ecf87-2bc7-4161-ac6c-c5ed2c6e8dcc.png)

cc @humancompanion-usds @GnatalieH

**Comment by humancompanion-usds** [comment]
We don't but that's because this pattern presents a11y problems and we're trying to limit progressive disclosure wherever we can. I also can't see how we'd make this work in our web-components. Would we add progressive disclosure functionality to checkbox and radio? We could deprecate by just letting it die on the vine.

**Comment by jamigibbs** [comment]
Thanks @humancompanion-usds 

I think looking at the different ways the `ExpandingGroup` is being used, it does not make sense to add any additional functionality to any of our other web components (progressive disclosure functionality) and the correct approach for us is to simply remove the component (let it die on the vine). We would just be reinforcing this design pattern if we did that.

I don't think this deprecation will change or fix the problem of those apps having been designed with progressive disclosure though. The developer replacing it will likely just add the same "toggling" behavior that ExpandingGroup was doing for them with a `div` or whatever element makes sense in their implementation. We can add more details to the ESLint rule though to give a warning about this pattern though.

**Comment by humancompanion-usds** [comment]
@jamigibbs - An ESLint rule would be great. Also, progressive disclosure is not completely disallowed. We have some guidance on how to implement it thoughtfully: https://design.va.gov/patterns/wizards#retrofit-this-pattern But tracking down and altering code in applications to make them more accessible is not the responsibility of the Design System Team. Letting ExpandingGroup wither away is a fine strategy for now.
