### ISSUE TITLE
Audit USWDS icons for overlap with VA icons

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1388]
## Description
Audit USWDS icons for overlap with VA icons & flag what is missing

## Tasks
- [ ] Audit USWDS icons with VA icons
- [ ] Create a list of where there is overlap
- [ ] Create a list of missing icons 
- [ ] Write a ticket for creating the missing icons or next steps

## Acceptance Criteria
- [ ] Share  and review the list with information with the team 
- [ ] There are tickets for follow up work

**Comment by caw310** [comment]
Closing this as it is a duplicate of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1476
