### ISSUE TITLE
Header - Audit (for web component)

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1392]
## Description
Do an audit of the Header. 

## Details
[add links to any tickets or documents with details about the design]
[add links to any research documents related to the component]

## Tasks
- [ ] Conduct small audit if necessary 
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Review audit with PO and DST
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)

## Acceptance Criteria
- [ ] Audit has been completed and has been reviewed
- [ ] Content specifications have been added to this ticket, if necessary

**Comment by humancompanion-usds** [comment]
This will definitely need an audit first and Sketch artifacts. It does not need new design work however.

**Comment by GnatalieH** [comment]
[Here's a link](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1674501871901/f8721a9d3b1bf1b98255a1eb6040365b726dbb2c?sender=u851998f98038e0f1e2da4592) to the Mural board Header audit (in progress).

**Comment by GnatalieH** [comment]
@Andrew565 searched through the code with me today in a meeting and found only these header variations (which I've already documented in the audit):

- Signed in and signed out
- Small screen and desktop
 
He said there doesn't seem to be any other variation of the header living on VA.gov. I'm checking with @allison0034 to make sure. FYI: @humancompanion-usds and @caw310
