### ISSUE TITLE
Minimal Header web component - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1393]
## Description
Build a web component of Header. Be sure to add analytics if necessary, see [guidance](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
- Design documents: https://www.sketch.com/s/4558672b-741f-4d59-84f0-796020d3ef57 - reference V2 USA header - Minimal for the design
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by micahchiang** [comment]
@humancompanion-usds - We need a little more clarity on what this ticket is trying to achieve. I think it was last week, or maybe the week before where we talked about just creating a "skeleton" component for the minimal header, but it's unclear what that means. There are 3 distinct pieces of the minimal header according to the sketch file linked above:

**The USA Gov Website Here's How You Know thing:**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnNoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--339a95a177181c05fba655da4d94b0275854aa2e/Screenshot%202023-08-21%20at%2010.17.51%20AM.png)
- The [banner component](https://designsystem.digital.gov/components/banner/#latest-updates) on USWDS looks like the old one, so it's unclear to me where we would find the new one.
- Some of the mocks include the `An official website of the US government here's how you know` text, some don't. It's unclear if this is conditionally rendered or not, and if so, what conditions need to be met for it to be displayed?


**The white middle part with specific VA branding:**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0loIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b806f02ab1094421fc9dc1c5cdd5f306c809c27f/Screenshot%202023-08-21%20at%2010.18.08%20AM.png)
- This piece includes contact, search, and sign-in after certain breakpoints, and renders a User dropdown menu if a user is logged in. 
- Includes Dynamic H1 tags that display form names


**The Mega Menu:** 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1loIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8e3f1456edbb25288489a2a6347b590c382ce182/Screenshot%202023-08-21%20at%2010.18.14%20AM.png)
- Contains the mega menu, but then also contains search and signin on mobile
- Also contains this space on mobile. Unclear what that is. Is this a text input for search, or just a spacer?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2doIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--db9d79832455a1999ce40287eaf075247ce755a8/Screenshot%202023-08-21%20at%2010.29.13%20AM.png)

When we say skeleton component, what does that mean in the context of the above information? Is it just the middle white strip with VA branding? Is it something else?

**Comment by micahchiang** [comment]
Tabling this for now in favor of a #2030

**Comment by humancompanion-usds** [comment]
@micahchiang - I created a minimal header and footer Sketch file with both the current and Federal CIO versions: https://sketch.com/s/f5f91c9c-f5c5-41f6-8e7e-6cfe003299fa

**Comment by danbrady** [comment]
@humancompanion-usds  Should the background blue color of the minimal header span the entire width regardless of the browser size? 

I reviewed the [minimal footer](https://github.com/department-of-veterans-affairs/component-library/pull/937#discussion_r1388625648) and made that recommendation based on the [Sketch design](https://sketch.com/s/f5f91c9c-f5c5-41f6-8e7e-6cfe003299fa), but it doesn't look like that was done to the [minimal header](https://minimal-header-dst2030--60f9b557105290003b387cd5.chromatic.com/iframe.html?id=components-va-minimal-header--default&viewMode=story).

**Comment by caw310** [comment]
Closing this as it is a duplicate of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2030
