### ISSUE TITLE
USWDS v3 variations are displaying with small font size in vets-website

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1402]
## Description

During the development of the [USWDS v3 variation of va-radio](https://github.com/department-of-veterans-affairs/component-library/pull/579), we noticed that the component was displaying very small in Storybook when the v3 stylesheets were applied. (Note: This is specifically when Formation is still loading as a global resource)

For example:

<img width="673" alt="207380149-ce562135-8d94-431e-9fab-404e2c673f8d" src="https://user-images.githubusercontent.com/872479/207389741-ec17eb00-84bf-4dea-a0c5-e51972d8ec0f.png">

Review the [USWDS website](https://designsystem.digital.gov/components/radio-buttons/) for comparison.

We discovered that Formation was setting the root font to 10px on the `html` tag and 1.6rem on the `body` tag. We applied [this customization in Storybook to toggle the root style](https://github.com/department-of-veterans-affairs/component-library/pull/577) depending on if the Storybook page was for a USWDS v3 component so that those components would receive the correct root font size (16px).

The purpose of this ticket is to validate that teams that have opted into using USWDS v3 and opted out of Formation have the v3 components displaying as expected in their apps. 

Related Work:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1211

## Tasks
- [ ] Test the display of the va-radio v3 variation in vets-website (specifically the pre-check-in app `/health-care/appointment-pre-check-in`).
- [ ] Implement any fixes or update as needed.

## Acceptance Criteria
- [ ] The v3 variations display normally in vets-website for apps that have opted into using v3 components and opted out of Formation.

**Comment by caw310** [comment]
Putting this issue back to Reviewed/Needs prioritizing to be worked on in a future sprint as we aren't quite in a place to work on this issue right now.

**Comment by humancompanion-usds** [comment]
Looks like this was fixed and we just didn't close this issue.

This issue has been inactive for over two years and appears to be superseded by more recent events and updates. To keep our backlog manageable and relevant, we are closing this issue. If you believe this issue is still relevant and requires further attention, please feel free to reopen it or create a new issue with updated details.

Thank you for your understanding and contributions!
