### ISSUE TITLE
Turn on new CSS Class linting rule

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/vets-design-system-documentation#1404]
## Description
A new [CSS Class linting rule](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1343) was created for VFS teams to easily update to the new CSS Class library based on USWDS v3. This ticket is to turn on the eslint rule in `vets-website` and `content-build`.

Ensure that the newest version (1.7.0) is published to npm. PR with new eslint rule was created [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/900)

## Tasks
- [ ] Turn on CSS Class linting rule in `vets-website`
- [ ] Turn on CSS Class linting rule in `content-build`

## Acceptance Criteria
- [ ] @department-of-veterans-affairs/web-components is set to 1.7.0
- [ ]  CSS Class linting rule is turned on

**Comment by humancompanion-usds** [comment]
Pretty sure we did this.

This issue has been inactive for over two years and appears to be superseded by more recent events and updates. To keep our backlog manageable and relevant, we are closing this issue. If you believe this issue is still relevant and requires further attention, please feel free to reopen it or create a new issue with updated details.

Thank you for your understanding and contributions!
