### ISSUE TITLE
Source Sans Pro font should be loading for USWDS v3 components

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1411]
## Description
During the [`va-text-input` USWDS v3 variation development](https://github.com/department-of-veterans-affairs/component-library/pull/587#issuecomment-1360338885), we noticed that the font was not displaying in the same way that the USWDS website was displaying. We discovered that the font stack assigned to various CSS classes had "Source Sans Pro Web" but the font available in Storybook/Formation is "Source Sans Pro" so the font was falling back to "Helvetica Neue".

The USWDS v3 font stack looks like this:

` font-family: "Source Sans Pro Web", "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;`

[USWDS Site](https://designsystem.digital.gov/components/text-input/)

![Screenshot 2022-12-20 at 3 35 17 PM](https://user-images.githubusercontent.com/872479/209178188-3bebd88b-1cda-4a20-bcd7-26a8cdea5991.png)

[VA.gov Storybook](https://1266-text-input-us-wds-v3--60f9b557105290003b387cd5.chromatic.com/?path=/docs/uswds-va-text-input--default)

![Screenshot 2022-12-20 at 3 34 54 PM](https://user-images.githubusercontent.com/872479/209178191-90990bb2-56a4-4dd6-ae63-831b93e84c51.png)

## Other Details

This issue has also been verified in the [`va-radio` v3 variation](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--default) and we will likely see it in the [`va-memorable-date` development](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1267) as well. We should see if there's a way to get the "Source Sans Pro" font loading correctly in the most global way possible.

## Tasks
- [ ] Figure out the best way to get "Source Sans Pro" font loading correctly in components with a v3 variation.
- [ ] Implement that solution.

## Acceptance Criteria
- [ ] "Source Sans Pro" is loading correctly in all components with a USWDS v3 variation.

**Comment by jamigibbs** [comment]
### Formation and v3 font stack for Source Sans Pro
Currently we are relying on Formation to provide base style including the font imports. The font-stack in Formation is: `$font-sans: 'Source Sans Pro', $helvetica !default;`

https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/97382cc5d7f8327d2c1ebfb89b3c472cc222c30b/packages/formation/sass/base/_b-variables.scss

But the font stack in v3 is `"Source Sans Pro Web", "Helvetica Neue", Helvetica, Arial, sans`.

https://github.com/uswds/uswds/blob/develop/packages/uswds-core/src/styles/tokens/font/typefaces.scss#L100

Because we are relying on Formation to import the font and it's named "Source Sans Pro" instead of "Source Sans Pro Web", I think it's just not finding the font.

### Relying on Formation Base Styles
A larger issue is that we do not yet seem to be using the v3 base styles. This is not just limited to fonts but also things like CSS resets, base elements like header tags, and any core styles that set the HTML foundation. We are relying on Formation for those things at the moment. This is why when the v3 font family is looking for it's primary font to load, it's not finding it because we are not actually importing it yet.
