### ISSUE TITLE
Add USWDS v3 Error color to `css-library` 

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/vets-design-system-documentation#1417]
## Description
Add the error color variable to the `css-library`  package and update the mixins that used hard-coded colors in the new USDWS v3 components.

Ex:

[uswds-error-border.css](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/mixins/uswds-error-border.css#L2)

```
:host([error][uswds]:not([error=''])) {
    border-left: 0.4rem solid #b50909; /* USWDS red-60v, $theme-color-error-dark */
    padding-left: 1rem;
    position: relative;
}
```

## Details
After creating the `_variables.scss` file in `web-components` in [PR](https://github.com/department-of-veterans-affairs/component-library/pull/594), we will need to add the red color used in the [error class from USWDS v3](https://github.com/uswds/uswds/blob/develop/packages/uswds-core/src/styles/settings/_settings-color.scss#L86)

```
$theme-color-error-dark: "red-60v" !default; 
```

Once this is done. We will need to update all the necessary files where this error token should be used.

## Tasks
- [ ] Add the error color variable to the `css-library`  package
- [ ] Update error colors with new variable

## Acceptance Criteria
- [ ] New error variables have been added to the `css-library`  package
- [ ] New variables are being used in the new USWDS v3 components
