### ISSUE TITLE
Tagalog translations for va-date

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1423]
## Description
The [`va-date` component](https://design.va.gov/storybook/?path=/docs/components-va-date--default) needs Tagalog translations for all of the currently hard coded English text and that text updated in the component to display using `i18next` (if it has not been updated yet). Use the [va-text-input](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-text-input/va-text-input.tsx) component as an example of how to integrate the `i18next` functionality.

This is not an exhaustive list so please confirm in the component itself ([some translations may already be available](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/core/src/i18n/translations/tl.js)):

- (*Required)
- Please enter two digits for the month
- Month
- Please enter two digits for the day
- Please enter four digits for the year
- All months (January, February, March, etc)

Please update the [component translations spreadsheet](https://docs.google.com/spreadsheets/d/1iIg9pP5GG-QFk7DrsyoKJv9GebtYmDuzKf_heqxWks4/edit#gid=0) when complete.

Related Spanish translation ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1422

## Details
- Design documents: [add links to any design documents]
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storyboook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo
