### ISSUE TITLE
USWDS Pagination - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1436]
## Description
We need to incorporate the designs for the [USWDS Pagination component](https://designsystem.digital.gov/components/pagination/) into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not. 

## Details
USWDS Pagination component - https://designsystem.digital.gov/components/pagination/ 
VA DS Pagination component - https://design.va.gov/components/pagination

## Tasks
- [x] Conduct small audit if necessary 
- [x] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [x] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist (if there is a11y support available)
- [ ] Review designs with DST members (during a weds standup)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs 

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket

**Comment by babsdenney** [comment]
@humancompanion-usds @LillyBoot This is ready for review. I have two questions that we can go over next week. 

1. Does the last page of the default state look correct? I'm not sure what should happen when the page is on 23 vs. 24. Would the ellipsis go away once you are at the end? 
2. Does the hover state for the next and previous buttons look accurate? Our link button seems to use the base color for hover, but on USWDS, they use a darker blue color instead. Wondering which way we should go with that? 

- [Desktop Example](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/vREjYzd)
- [Mobile Example](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/4om7yJ3)

**Comment by babsdenney** [comment]
I found this interactive example of the USWDS pagination that answers the first question and updated the symbols to match this component. 
[Trussworks USWDS Pagination example](https://trussworks.github.io/react-uswds/?path=/story/components-pagination--sandbox&args=currentPage:1;totalPages:24)

**Comment by babsdenney** [comment]
This is complete.
- [Desktop Pagination](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/vREjYzd)
- [Mobile Pagination](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/4om7yJ3)
