### ISSUE TITLE
Conversion to USWDS v3 - Select box - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1443]
## Description
We need to incorporate the designs for the [USWDS Select component](https://designsystem.digital.gov/components/select/) into the VA Sketch library. 

## Tasks
- [ ] Audit differences between the USWDS version and ours and present to the DST
- [ ]  Incorporate designs for USWDS Select into our select box component in Sketch
- [ ]  Review designs with PO
- [ ]  Review designs with DST members (Carol can help schedule this)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ]  Where necessary, USWDS Text input designs have been incorporated into our Sketch library
- [ ] Designs have been presented to the DST

**Comment by GnatalieH** [comment]
Here's the link to the artboard with the Select assets. I named this Select to match the USWDS name. Ready for your review @humancompanion-usds.

**Comment by humancompanion-usds** [comment]
Looks good. We should show all of the same states that we show for our current Select box. Thus we should include required and optional fields as well.

**Comment by GnatalieH** [comment]
I updated the mockups to include Required and Optional label variations.
