### ISSUE TITLE
USWDS v3 - Select - Accessibility review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1447]
## Issue Description
We need to conduct a review of the accessibility guidance on USWDS for the select component  [(URL)](https://designsystem.digital.gov/components/select/) and compare it to the a11y guidance in the VA DS. [ (URL)](https://design.va.gov/components/form/select) 

## Tasks
- [x] Full accessibility review of the component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] If necessary, discuss any accessibility issues found with the engineer who developed the component
- [ ] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [ ] Component has been reviewed for accessibility issues
- [ ] Any accessibility issues have been addressed

**Comment by rsmithadhoc** [comment]
- I found one small issue where the help text does not get read out. I believe this needs an `aria-describedby` for that to happen. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTg3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8a3c8144040717313bbebc512af84ce5375df5d7/image.png)

**Comment by rsmithadhoc** [comment]
Follow up for the fix was created from staging review: https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/64284

Closing this.
