### ISSUE TITLE
Audit icons in VA Design System and icons in USWDS icons

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1476]
## Description
Audit icons in VA Design System and the icons in USWDS. 

## Tasks
- [ ] Do an audit of the icons in USWDS and compare it with the icons in VADS. 
- [ ] Add screenshots of icon differences onto a Mural board  
- [ ] Gather feedback on findings from the DST PO 
- [ ] Respond to feedback from DST
- [ ] Add link to Mural board as a comment in this ticket and to the component design ticket if applicable

## Acceptance Criteria
- [ ] Identified differences have been put on on a Mural board and a link to the board has been added to this ticket
- [ ] Audit findings have been shared with the DST and all feedback has been addressed.

**Comment by caw310** [comment]
I've got this going into the next sprint. Would be great if you can get started on this. Thanks!

**Comment by GnatalieH** [comment]
Hi @caw310. Unfortunately I won't be able to begin this audit in the current sprint due to my PTO this week and the other three tickets I have in progress currently. But I can begin it next sprint. Thanks.

**Comment by caw310** [comment]
@GnatalieH , I think this is actually slated for sprint 23. It was probably a stretch that carried into this sprint. Sorry about that. Moving it to the next sprint.

**Comment by GnatalieH** [comment]
Thank you so much @caw310. No worries at all! I just want to make sure I get everything done.

**Comment by GnatalieH** [comment]
[Here's the link](https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1678830068825?sender=u851998f98038e0f1e2da4592&key=1220cc4b-5b00-4e71-8b7c-409dc8927d84) the Mural board I started.

**Comment by GnatalieH** [comment]
@caw310 is there an older ticket with more details included? I feel like I saw one that described what the goal of this audit is, like identifying gaps between USWDS vs. VA icon sets, etc. Are we looking for parity so we can convert to USWDS icons wherever possible? Thanks.

**Comment by caw310** [comment]
@GnatalieH here is the other ticket. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1388

**Comment by GnatalieH** [comment]
[Here is a link](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1678830068825/553b0ef0eb59ba6e26ad03692dc255f43c852737?sender=u851998f98038e0f1e2da4592) to the Mural board where I've started the audit. CC @LillyBoot

**Comment by GnatalieH** [comment]
@humancompanion-usds [this is ready for review](https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1678830068825?sender=u851998f98038e0f1e2da4592&key=1220cc4b-5b00-4e71-8b7c-409dc8927d84). Carol mentioned we could talk about this today in our design meeting. Thx.

**Comment by LillyBoot** [comment]
There are 13 VA icons that do not have a USWDS equivalent

**Comment by LillyBoot** [comment]
Finished breakdown of "No Equivalent" icons. Six icons have no replacement

**Comment by LillyBoot** [comment]
@GnatalieH Here is the breakdown: 
![Screen Shot 2023-03-27 at 4 46 50 PM](https://user-images.githubusercontent.com/123974487/228299479-f8f9eed8-64cf-43af-a761-1d0a6353b358.png)

**Comment by GnatalieH** [comment]
Thanks so much @LillyBoot! This is great.

**Comment by caw310** [comment]
@LillyBoot , can you write 3 tickets for each category before closing?
