### ISSUE TITLE
DSP P0 - Discovery: Determine what problems Formation is causing to the V3 component

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1491]
## Description

This will require determining the underlying causes of the 'Formation problem', which currently interrupts a V3-compatible components' styling by applying Formation's styles so globally and broadly that the styling from USWDS V3 is overwritten.

## Details
- Known: Formation is currently being brought in via the site-wide folder/app
- Known: a "useLocalStylesAndComponents" config flag was recently added to the Webpack config and the app registries
- Unknown: does enabling the useLocalStylesAndComponents flag prevent the loading of Formation?
- Unknown: if Formation cannot be excluded from an individual app using the flag above, what styles are affected and will need to be compensated for in the 'clash' between Formation and USWDS' style rules?

## Tasks
- [ ] Answer if an app can effectively 'opt out' of loading Formation, despite it loading at the site-wide level
- [ ] Determine what mitigations can be applied to compensate for the Formation Problem
- [ ] Discern what solution is the most effective with the least impact to the app and the greatest ease of implementation for other teams

## Acceptance Criteria
- [ ] A strategy has been discovered and chosen as effective (to be implemented in a following ticket)

**Comment by jamigibbs** [comment]
Some additional context:

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1402
- Formation `font-size` applying to `body` and `html` tags: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/base/_va.scss#L7-L16
- Current workaround in Storybook: https://github.com/department-of-veterans-affairs/component-library/pull/577

**Comment by jamigibbs** [comment]
@Andrew565 I have a theory for a possible approach to mitigating the Formation conflict. The issue as I understand it is that Formation is setting the base font of the HTML tag as `10px`. This means that every time a `rem` or `em` is used throughout the library, it's basing it off of `10px`.

USWDS v3 on the other hand is setting the base font of the HTML tag as `1rem` (this is based on their `$root-font-size` which defaults to 16px) but it is lower in the cascade in our components and gets overridden by Formation's `10px` (making everything appear small in our v3 variations).

Assuming we can't "turn of" the base styles of Formation that are creating this conflict, is it worth exploring updating Formation to use the same root font size as USWDS v3 (`1rem/16px`) and then update all of Formation where a `rem` or `em` is used to pixels instead (ie. 1.3rem x 10 = 13px)? I did a very light exploration of this in browser and it seemed to work for the elements I changed but there are probably other complications here that I have not considered (not to mention the level of effort to update the entire library and the risk involved with that).

**Comment by Andrew565** [comment]
Here is the strategy we have decided on for solving this problem:

For each component that we migrate to V3, including the ones we’ve already done, we’ll add `@import '../../global/formation_overrides';` to the stylesheet.

In the formation_overrides.scss file, we’ll specify all of the rem-based values that will need to be converted to px-based values, using a new function I created. It will look like this:

```
.usa-label {
  font-size: rem-override(1.06rem);
}
```

The rem-override function takes the provided value and multiplies it by a new variable called `$base-font-size` (in global/_variables.scss), which is currently set to 16px.

This will allow us a single file to ‘keep track of’ when we’re ready to hand over stuff to USWDS, and strip out the single import from each of the individual component stylesheets. This process can be automated easily. Because the overrides are available at the global level, it allows us to redefine the styles for each class once, rather than per component, maximizing efficiency.
