### ISSUE TITLE
Conversion to USWDS v3 - Step Indicator (Progress bar -segmented) - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1504]
## Description
Adapt the va-segmented-progress-bar component to match the [USWDS Step Indicator](https://designsystem.digital.gov/components/step-indicator/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

Add converted component to playground

## Details
Design documents: [add links to any design documents]
See these examples for guidance. 
* va-radio: https://github.com/department-of-veterans-affairs/component-library/pull/579
* va-select: https://github.com/department-of-veterans-affairs/component-library/pull/610
* va-textarea: https://github.com/department-of-veterans-affairs/component-library/pull/654
* va-button: https://github.com/department-of-veterans-affairs/component-library/pull/645

[USWDS Step Indicator component](https://designsystem.digital.gov/components/step-indicator/)
[VA DS Progress bar - segmented component](https://design.va.gov/components/form/progress-bar-segmented)

## Tasks
- [x] Create a version of this component that imports and uses the USWDS CSS
- [x]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [x]  Check with Natalie to make sure the component and the design match
- [x]  Add a USWDS story to Storybook
- [x]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [x] Write ticket to add Step indicator (progress bar - segmented) to DS playground

## Acceptance Criteria
- [x]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library
- [ ] Ticket created to add Step indicator (progress bar - segmented) to DS playground

**Comment by caw310** [comment]
There is a chance this could be more complicated.

**Comment by caw310** [comment]
This work may require two sprints.

**Comment by caw310** [comment]
@powellkerry just an FYI, that we have now added task to "Add converted component to playground" as part of the tasks and acceptance criteria for converting  USWDS v3 components.

**Comment by davidakennedy** [comment]
@powellkerry asked for a [second look on this in Slack](https://dsva.slack.com/archives/C8E985R32/p1682625645335849). I wanted to add my feedback here. Overall, it's solid in my quick testing. I didn't test extensively.

- No real interactive controls, so not much complexity here.
- I'm assumed we're trying to keep parity with the existing progress bar.
- The biggest thing I see is out of order headings. The "Step 2 of 5" part is in a h4, which follows a h1. It should be a h2 to maintain hierarchy, but it can still look like a h4 visually. That would also match how it is currently on VA.gov.

**Comment by powellkerry** [comment]
@davidakennedy I will update the storybook story to remove the h1 heading, that was an artifact from the v1 version. @LillyBoot I don't know the use cases for this component, is an h4 correct or should it be a h2 or h3?

**Comment by LillyBoot** [comment]
@powellkerry the "Step 2 of 5" isn't using a header font. It is a custom on just for this component. It is supposed to be source sans pro, regular, 22px. We have been having some discussions about font sizes. So if what you currently have in storybook is the default don't worry about changing it right now.

**Comment by powellkerry** [comment]
@LillyBoot it looks like that is brought in from USWDS and matches what they have: https://designsystem.digital.gov/components/step-indicator/ On sketch the font size is 22px, should we overwrite their style?

**Comment by powellkerry** [comment]
@davidakennedy The v1 version of this component has the following aria-attributes: aria-valuenow, aria-valuemin, aria-valuemax, aria-valuetext
These are not on the USWDS version. Should they be added to our v3 version?

**Comment by davidakennedy** [comment]
@powellkerry 

> The v1 version of this component has the following aria-attributes: aria-valuenow, aria-valuemin, aria-valuemax, aria-valuetext
> These are not on the USWDS version. Should they be added to our v3 version?

It depends. 😁 In the [USWDS component](https://designsystem.digital.gov/components/step-indicator/) is built more like fancy breadcrumbs, meaning the markup is a list with `aria-current` to help screen readers know where in the list someone is at. Our step indicator is [created with a progress bar](https://design.va.gov/storybook/iframe.html?id=components-va-progress-bar--default&viewMode=story). It uses that `role` and it has some advantages.

If our goal is to keep things the way they are, with our existing progress bar component, we could keep those values. They help assistive technology understand the progress bar. But if we're looking to maintain parity with USWDS, we could leave them off. But we'd want the markup to be more in line with the way it is in USWDS now. Because both ways allow screen readers to kind of know where they are in a series of steps. But both the USWDS markup with those progress bar attributes together probably don't make sense.

Does that make sense? Let me know if you have any follow up questions.
