### ISSUE TITLE
Add Templates > Forms > Intro page and template

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1512]
## Description
Add a page in Templates > Forms for the Introduction page. Move content over from github.

## Details
Jeana on the Veteran-facing Forms team has provided an annotated template. 

## Tasks
- [ ] Create a page for the Introduction page of Forms
- [ ] Create a page for Introduction in Sketch Templates library.

## Acceptance Criteria
- [ ] New page exists at https://design.va.gov/templates/forms/introduction
- [ ] New page exists in Sketch Templates library under Forms

**Comment by humancompanion-usds** [comment]
Templates > Forms > Introduction: https://design.va.gov/templates/forms/introduction

I also created Templates > Forms > How to apply: https://design.va.gov/templates/forms/how-to-apply
