### ISSUE TITLE
Create web components that remove dependency on Formation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1528]
## Description
As part of the VA Design System to USWDS v3, the DST needs to remove the dependency on Formation. The team has already built web components to replace the React components but there are still a few remaining React components that need to be replaced with a web component version. Also, we will update the Forms library with web components to re

As part of this epic, we will need to deprecate the remaining  React components. This means VFS team will need to update any applications using a React component to the web component version.

## Details
There are the areas of work that are to be done as part of this epic: 
- Build web components for: maintenance banner, header, footer and icons
- Deprecate React component library [Plan for deprecation](https://vfs.atlassian.net/l/cp/86bgiY8p)
- Update Forms library with web-components [See discovery ticket for details](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1375)  

## Tasks
- [ ] Build web component for maintenance banner
- [ ] Build web component for header
- [ ] Build web component for footer 
- [ ] Build web component for  icons
- [ ] Deprecate React component library 
- [ ] Update Forms library with web components (Tickets to be written up) 

## Acceptance Criteria
- [ ] Web components built for maintenance banner, header, footer and icons
- [ ] React components have been replaced with web component versions 
- [ ] Forms library is using web components
