### ISSUE TITLE
EPIC: Deprecate React components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1529]
## Description
Deprecate React components.  [Plan for deprecation](https://vfs.atlassian.net/l/cp/86bgiY8p)
As part of the deprecation of the remaining React components we will have ask VFS teams to update any of their applications using a React component to the web component version.

## Tasks
- [ ] Deprecate React components 
- [ ] Work with teams to have them update their applications with web components

## Acceptance Criteria
- [ ] DS React components are deprecated

**Comment by annekerr49** [comment]
Is there any update on the progress of this effort?

**Comment by caw310** [comment]
DST has completed deprecation of React components except for expanding group and modal. 
There are 5 instances of expanding group that will need to be replaced with another component. That work is in the DST backlog. 
There are 16 instances of modal. Due to some complexities with the modal, we are holding off on deprecation.

**Comment by humancompanion-usds** [comment]
@micahchiang and @caw310 - Is there a way for us to do the following?

1. File new issues for modal and expanding group 
2. Move modal and expanding group out of the component library
3. Deprecate for once and for all the React portion of the component-library

It's that last one that is the acceptance criteria on this and the point was reducing the overall size of the component-library. Is there a way to achieve this given the blockers of the remaining instances? Let's discuss. I'd really like to close this initiative.

**Comment by caw310** [comment]
@humancompanion-usds  
Micah and I discussed the remaining work to be done to deprecate React components for Modal and Expanding group. Here are the tickets. Both issues are associated with this epic - https://github.com/department-of-veterans-affairs/va.gov-team/issues/53436

- Modal work: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1634) 
- Expanding group work: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1659  (decision was to replace the one instance with plain HTML)
Both tickets are part of Sprint 46 plan (Feb 1 to 13).

**Comment by humancompanion-usds** [comment]
@micahchiang - Are there more React components we can remove from component-library? The remaining components in [Storybook](https://design.va.gov/storybook/?path=/docs/about-introduction--page#deprecated) should match [what is in the repo](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/react-components/src/components).

**Comment by caw310** [comment]
There are a few more tickets remaining to deprecate React Components. 

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1634
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1659
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2439

That work is part of the [Create web components that remove dependency on Formation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53436) initiative.
