### ISSUE TITLE
Forms Lib - Replace Checkbox Component

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1531]
## Description

As part of [this epic](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1530), we will replace all instances of the React Checkbox component in the Forms Library with the Web Component version.

## Details

The checkbox component is currently being used in the following files:

- /vets-website/src/platform/forms/components/review/PreSubmitSection.jsx
- /vets-website/src/platform/forms/components/PrivacyAgreement.jsx
- /vets-website/src/platform/forms-system/components/FormSignature.jsx

## Tasks

- [x] Replace the React component with its Web Component component, updating any necessary props and/or logic related to the smooth operation of the component
- [x] Ensure the web component works correctly - likely, by either finding an existing app that makes use of it or by creating a new, temporary form
- [x] Update any accompanying tests
- [ ] Get design sign-off to ensure that the new Web Component looks and feels 'correct'

**Comment by caw310** [comment]
Work is completed but will carry over due to failing unit tests which require looking into before closing this ticket.

**Comment by caw310** [comment]
Will carry over due to more unit testing issues.

**Comment by nickjg231** [comment]
Experiencing e2e test failures on GitHub that are unrelated/untouched by this ticket. A support ticket has been created to address this, currently awaiting support ticket resolution. Link to the support ticket/issue here:
https://dsva.slack.com/archives/CBU0KDSB1/p1679335784213049
https://github.com/department-of-veterans-affairs/va.gov-team/issues/55423

**Comment by caw310** [comment]
Will carry over into the next sprint as there is still an issue with unit testing.
