### ISSUE TITLE
Forms Lib - Replace ProgressButton Component

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1533]
## Description

As part of [this epic](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1530), we will replace all instances of the React ProgressButton component in the Forms Library with the Web Component version.

## Details

The ProgressButton component is currently being used in the following files:

- /vets-website/src/platform/forms/save-in-progress/ApplicationStatus.jsx
- /vets-website/src/platform/forms/save-in-progress/FormStartControls.jsx
- /vets-website/src/platform/forms/save-in-progress/SaveInProgressDevModal.jsx

## Tasks

- [x] Replace the React component with its Web Component component, updating any necessary props and/or logic related to the smooth operation of the component
- [x] Ensure the web component works correctly - likely, by either finding an existing app that makes use of it or by creating a new, temporary form
- [x] Update any accompanying tests
- [x] Get design sign-off to ensure that the new Web Component looks and feels 'correct'

**Comment by caw310** [comment]
Will carry over into the next sprint.

**Comment by caw310** [comment]
Transferring over from Andrew to Kerry.

**Comment by Mottie** [comment]
`ProgressButton` is [used in a few more places](https://github.com/department-of-veterans-affairs/vets-website/search?q=progressButton), including 5 apps and a few more components in the platform folder. Is the `ProgressButton` component being updated, or are the specifically named uses of it (in the OP) being updated?

**Comment by powellkerry** [comment]
@Mottie Those occurrences will be replaced with a future card.

**Comment by powellkerry** [comment]
Merged 4/5/2023
