### ISSUE TITLE
EPIC: Convert form components to USWDS v3 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1539]
## Description
The initiative [Create DS demonstration application for USWDS v3-based Design System#1473](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1473) includes converting more components to USWDS v3 with a focus on components used in forms. 

- text-input - DONE
- radio-button - DONE
- select - DONE
- memorable-date
- checkbox
- textarea
- button
- button-pair
- file input
- progress bar - segmented

## Details
This epic will be used to track the conversion of the form components listed above. 

## Tasks
- [ ] Convert the component
- [ ] Compare design and update Sketch library
- [ ] Compare a11y guidance and update accessibility guidance as necessary 

## Acceptance Criteria
- [ ] Converted component is in Storybook
- [ ] Sketch library as assets for the component 
- [ ] A11y guidance has been reviewed and updated as necessary
