### ISSUE TITLE
Prefill - Documentation

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1540]
## Description
Add documentation and guidance for Prefill from Profile on design.va.gov. 

## Details
We currently talk about the Prefill message in our patterns on asking users for emails and addresses:
* https://design.va.gov/patterns/ask-users-for/email-address#prefill-information
* https://design.va.gov/patterns/ask-users-for/addresses#prefill-information

Annoyingly, I failed to put it in [Help users to know how their information is updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated), which is where it really needs to be. However, we should also add it as a component to Components > Form. While it may be just an instance of Alert - Background-only - Informational, it does have specific language that we want to codify in order to make it consistent across forms. Step 1 is to document.

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Add to [Help users to know how their information is updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated) pattern
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov
