### ISSUE TITLE
Create set of demonstration pages built in vets-website

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1545]
## Description
The initiative [Create DS demonstration application for USWDS v3-based Design System#1473](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1473) includes the creation of a set of demonstration pages. These should be built in vets-website, though not deployed to production, in order to reproduce what VFS teams will need to do in order to configure their applications to use the new Design System.

There are 3 phases that have been outlined for the demonstration pages
- MVP - Phase 1: Formation-sans Forms plus v3-based forms components
- Phase 2: USWDS v3-based base design system + USWDS v3-based Form components & 5 most used web-components + Minimal Formation
- End goal: USWDS v3-based base design system + USWDS v3-based components built to-date

## Tasks
- [ ] Set up DS playground for DST engineers to use 
- [ ] Address any issues that arise in each phase 
- [ ] Demo progress to PO and the rest of the DST

## Acceptance Criteria
- [ ] The Design System Team has the ability to demonstrate a page or pages that show the scenarios listed above with the MUST requirements met.
