### ISSUE TITLE
Discovery: How could we show code for a pattern?

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1547]
## Description
The patterns in the DS currently provide only guidance on how the pattern works, how to design and build it. It would be very helpful to all teams if patterns also included reusable code for the pattern. This work is just a discovery to identify how we could show code for patterns and if we could incorporate patterns with the code into Storybook. 

## Details
Take a look at the address pattern and use it as an example. How might we provide code for an address pattern? 
https://design.va.gov/patterns/ask-users-for/addresses

## Tasks
- [ ] Research how to codify a pattern
- [ ] Find out if pattern code could be incorporated into Storybook
- [ ] Write up your findings either in this ticket or include link in this ticket
- [ ] Present findings to DST 

## Acceptance Criteria
- [ ] Findings are recommendation are documented
- [ ] Findings have been presented to the team

**Comment by humancompanion-usds** [comment]
We link to code now in the top section of patterns. This is done.
