### ISSUE TITLE
DSP P1 - Mitigate select component Formation problem

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1568]
As a VA Developer, I want to use the V3-compatible variant of the select component because it is the new standard for the VA Website. In order to do so, the select component must have its conflicting styles with Formation mitigated using the strategy previously determined.

## Tasks

- [ ] Apply the sizing mitigations to the .usa-select class and any associated classes (including option elements, if needed)

## Acceptance Criteria

- [ ] The v3 variant of the select component renders correctly in Storybook
- [ ] The v3 variant of the select component renders correctly in the DS Playground

**Comment by caw310** [comment]
Will carry over into the next sprint pending PR review and approval.
