### ISSUE TITLE
Add GA4 mapping for va-additional-info, va-alert, and va-alert-expandable

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1575]
## Description
The analytics team is needing to start connecting [Google Analytics 4](https://support.google.com/analytics/answer/10089681?hl=en) (GA4) before the current Google Analytics (GA) is sunset by Google (July 1, 2024). In preparation for that cutoff date, we will need to maintain both GA and GA4 analytics tracking until eventually we are only needing to track GA4 events.  

What that means for us right now is that we will need both GA and GA4 events pushed into the datalayer. All of the design system web components should already have GA events setup so we just need to map that to GA4.

## Details
The work required in this ticket is to add GA4 mapping for the following components:

- [ ] `va-additional-info`
    - expand
    - collapse
- [ ] `va-alert`
   - click (close)
- [ ] `va-alert-expandable`
    - expand
    - collapse

Updates should only be happening in `vets-website` in the [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js) file. The web components should already have an analytics event setup and firing. If it doesn't, please flag that as additional work.

**Additional guidance on how to complete the GA4 integration**

https://vfs.atlassian.net/wiki/spaces/DST/pages/2544173086/Adding+GA4+details+for+Google+Analytics

## Other Details

See Michelle's GoogleSheet for additional info
https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit?usp=sharing

va-additional-info | int-additional-info-expand
va-additional-info | int-additional-info-collape
va-alert | nav-alert-box-link-click
va-alert-expandable | int-alert-expandable-expand
va-alert-expandable | int-alert-expandable-collape

## Tasks
- [ ] Add Data Layer Code Specifications for Interaction events for va-additional-info, va-alert, and va-alert-expandable
- [ ] Let Michelle now this work has been done so she can test 

## Acceptance Criteria
- [ ] Data Layer Code Specifications for Interaction events have been added and tested

**Comment by caw310** [comment]
DST is focused on the upgrade to USWD v3 so we will push this off to a future sprint.

**Comment by jamigibbs** [comment]
## va-alert-expandable

**GA**
<img width="413" alt="Screenshot 2023-05-11 at 2 47 29 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/c21ac51e-f780-4d65-9696-99c442e5c125">

**GA4**

<img width="407" alt="Screenshot 2023-05-11 at 2 47 36 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/66e71ced-d120-4643-b6e3-b7ac1a399d6a">

**Comment by jamigibbs** [comment]
## va-additional-info

**GA (expand)**
<img width="448" alt="Screenshot 2023-05-11 at 2 53 23 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/ec36d388-bba0-4edd-b077-cb76c735b2b0">


**GA4 (expand)**
<img width="428" alt="Screenshot 2023-05-11 at 2 53 31 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/094dc00c-d458-4690-af07-2157101cfff5">


**GA (collapse)**
<img width="464" alt="Screenshot 2023-05-11 at 2 54 12 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/f21c63e8-dfd8-40a7-a79b-15032002c4db">

**GA4 (collapse)**
<img width="417" alt="Screenshot 2023-05-11 at 2 54 21 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/2d9e03ba-ce4f-4f2a-bace-4ce15999a3a3">

**Comment by jamigibbs** [comment]
## va-alert

```
{
	event: "interaction",
	component_name: "va-alert",
	custom_string_1: "component-library",
	action: "nav-alert-box-link-click",
	custom_string_2: "Start your application without signing in",
	heading_1: "Sign in now to save time and save your work in progress",
	status: "info",
	component_version: undefined
}
```

**Comment by jamigibbs** [comment]
Hi @michelle-dooley! The following three web components have been added to the analytics setup file for GA4 compatibility:

https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js

 - va-alert
 - va-additional-info
 - va-alert-expandable

I tested it locally and have commented above with the results.
