### ISSUE TITLE
Discovery: Component-specific design tokens

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1588]
## Description

The [W3C Design Tokens Format Module](https://design-tokens.github.io/community-group/format/) draft provides an example of using design tokens so that they are composed to be component specific. In that document they provide and [example for a card component](https://design-tokens.github.io/community-group/format/#example-advanced-composite-token-example) that is composed of other design tokens to create a token that is specific to a card:

```
{
  "space": {
    "small": {
      "$type": "dimension",
      "$value": "0.5rem"
    }
  },

  "color": {
    "shadow-050": {
      "$type": "color",
      "$value": "#00000080"
    }
  },

  "shadow": {
    "medium": {
      "$type": "shadow",
      "$description": "A composite token where some sub-values are references to tokens that have the correct type and others are explicit values",
      "$value": {
        "color": "{color.shadow-050}",
        "offsetX": "{space.small}",
        "offsetY": "{space.small}",
        "blur": "1.5rem",
        "spread": "0rem"
      }
    }
  },

  "component": {
    "card": {
      "box-shadow": {
        "$description": "This token is an alias for the composite token {shadow.medium}",
        "$value": "{shadow.medium}"
      }
    }
  }
}
```

One of the advantages with this approach (as opposed to adding all of these styles directly in each web component stylesheet) is that it makes it very clear those are the values for the web component. Not only with naming but also adding a description.

Our [css-library](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library) is already using [Style Dictionary](https://amzn.github.io/style-dictionary/#/) so we should be considering the feasibility of this approach using those tools.

Original Slack convo: https://dsva.slack.com/archives/G01BJ3ESXL4/p1677681881846759

## Tasks
- [ ] Explore if and how Style Dictionary supports component-specific design tokens. This [Style Dictionary example](https://github.com/amzn/style-dictionary/blob/main/examples/advanced/component-cti/tokens/component/button.json) might be a place to start.
- [ ] Document the pros and cons, advantages and disadvantages, of this approach in the component library vs. using vanilla CSS like what was suggested in the [Slack convo here](https://dsva.slack.com/archives/G01BJ3ESXL4/p1677684330717429?thread_ts=1677681881.846759&cid=G01BJ3ESXL4).

## Acceptance Criteria
- [ ] Discovery findings have been prested to the DST.
