### ISSUE TITLE
[Pattern] - Help users to stay informed of their application status

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1594]
## Description
This work follows the audit completed in [#1128](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1128). Mural audit [is here](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1661355714382/20b034bd9720885de162064c435f5a86f4222449?sender=u851998f98038e0f1e2da4592).

The audit uncovered several ways that Veterans/caregivers are informed of an application status update:

1. Status update on the intro page of the form they completed.
2. Update in the Claims Status Tool.
3. Certificate of Eligibility (letters) sent. 

The first part of this work will focus on number 1 above. We are looking for examples of status updates shown in an alert on the intro page of the form. So far we know the 10-10EZ uses this pattern. If we can confirm that two other forms use this pattern we'll document it as a Template:

![Screenshot 2023-03-07 at 10.42.00 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/2966b6c6-69d4-4c5a-832a-029dd37fa0cf)

## Tasks
- [ ] Work with engineers and the Governance team to find examples of this type of component
- [ ] Add screenshots of component usage examples to a Mural board, including links to sources
- [ ] Gather feedback on findings from the DST (Carol can help schedule a session for this). Questions to ask include:
    - Are any changes to current implementations needed?
    - Are there any variations that can be consolidated?
    - Are there any accessibility considerations that should be taken into account as part of the design?
- [ ] Respond to feedback from DST
- [ ] Add link to Mural board as a comment in this ticket and to the component design ticket if applicable

## Acceptance Criteria
- [ ] Examples have been collected on a Mural board and a link to the board has been added to this ticket.
- [ ] Audit findings have been shared with the DST and all feedback has been addressed.

**Comment by caw310** [comment]
This will carry over into the next sprint.

**Comment by GnatalieH** [comment]
Hi @humancompanion-usds. Can you help @taylojill and I find point of contacts within the teams responsible for these forms?

- VA40-10007 - eligibility for VA Nat cemetery burial (app)
- 21P-527EZ - pension (app)
- 29-1546 - application for cash surrender Govt Life Insurance (app)

We'd like to find out how the status is communicated to the user after the form is submitted. Thanks!

**Comment by humancompanion-usds** [comment]
Okay, so here are the steps I take so that you can do the same:

1. Look in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)
2. Find the OCTO Product Owner and/or VFS PM for the form in question. You will likely need to know the name of the form. I usually find this by searching va.gov for it where you'll likely get the [Find a form page](https://www.va.gov/find-forms/) for that form first. The page for a form tells you if it is digitized yet, or not.
3. Reach out to the PO and/or PM and ask them who the current designer is.
4. If there is a designer, have a discussion with them. If there is not, use the documentation link in the Product Directory. That should have Sketch files and flows for the application. 
5. If there is a URL, use that in Staging to get to the part of the application that you want to document.

Here is what I found:

### Pre-need burial (40-10007)
* https://depo-platform-documentation.scrollhelp.site/getting-started/pre-need-burial
* PO is Matt Self
* PM is Veronica Henry (Ronnie)
* Docs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/pre-need/README.md

### Pension Benefits Application (21P-527EZ)
* https://depo-platform-documentation.scrollhelp.site/getting-started/pension-benefits-application-21p-527ez
* PO is Beth Potts / Dave Conlon
* No PM is listed
* Docs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/README.md

### Cash Surrender (29-1546)

This isn't even on the platform. It links to here: https://insurance.va.gov/home/ We can't use this for a pattern. So, in future, if you find an application or form that isn't in the Product Directory and IS on VA.gov then we should file an issue to have that product added. If it's not on VA.gov then we can't use it for a pattern and can ignore it.


Should you hit a dead end then the next strategy would be to get some time from an engineer on our team to look in code to see how this application works. They may be able to tell you what status appears when. You won't be able to get a screenshot but it will at least tell you the contents of the message and when it appears, which is helpful for guidance. 

After that our best bet is to try to reproduce this the state we want in staging. For that I would ask in Slack. Appropriate channels might be #design or #vfs-frontend. You can also reach out to Naomi (I'm working with Naomi to find out who else you can talk to as well). 

If that fails then I would document your efforts in the issue for the pattern noting that we hit a dead-end and move onto the next pattern. We can take those that have stalled out back to DSC and raise a flag with that group.

**Comment by taylojill** [comment]
Slack messages sent to Matt Self (Pre-need burial (40-10007) and Beth Potts/Dave Conlon (Pension Benefits Application (21P-527EZ). Requested information on how status is communicated to the user after the form is submitted.

**Comment by GnatalieH** [comment]
Notes from 3/24 meeting with Beth Potts:

- There is not a lot of commonality between product teams for checking the status of an application, and this is a problem.
- There is a potential pattern with the link/button to the Claims Status Tool under What should I do while I wait? section on the Confirmation page.
- Letters tool for Education is new and diverges from another COE tool. This is also a problem.
- Beth and Danielle will sync and get back to us on Confirmation page content guidance. We all think this is the best potential spot to provide guidance.
- Beth thinks there is value in documenting the different ways status is checked because product teams should try to get on the same page.

**Comment by humancompanion-usds** [comment]
Let's discuss in our Thursday meeting. You've gathered a lot of useful information so I'd rather not close this until we publish and share some of it. I'm inclined to say this falls under our rubric of Design System as Library and Design System Team as Librarians. In other words, we don't have to have an opinion on whether it is good or not that we don't have a 1 size fits all solution. I'd be for documenting these 3 solutions:

1.  Claims Status Tool (CST)
2. Status is updated on the intro page of the form (10-10EZ)
3. Certificates of Eligibility (letters) 

Part of the way we can help teams all get on the same page is to explain what is out there today and detail what the technical limitations are. We've done that now with the Ask users for multiple responses pattern (list and loop) and that has resulted in greater clarity and a new variation coming to DSC. I think we have a similar problem here and need a similar solution. But let's talk more on Thursday and determine a path forward.

**Comment by GnatalieH** [comment]
Sounds good @humancompanion-usds.

**Comment by caw310** [comment]
Will carry over into the next sprint.

**Comment by caw310** [comment]
@GnatalieH to write ticket for follow up work based on work done here.
