### ISSUE TITLE
Investigate if useLocalStylesAndComponents is excluding formation correctly

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1599]
## Description
When Brooks added the useLocalStylesAndComponents flag to the webpack.config.js file (vets-website/config/webpack.config.js), the idea was to prevent Formation from loading for apps that opted-out using this flag. This does not yet appear to be the case, prompting this ticket to investigate if Formation is being excluded, and if it is not, to determine why.

## Tasks
- [x] Determine if Formation is being excluded by locally enabling this flag on an app within the site
- [x] If Formation is not being excluded, determine why.
- [x] If the cause for 'why' is easily resolved, resolve it. Otherwise, create a new ticket to cover the work for fixing this issue.

## Acceptance Criteria
- [ ] The root cause for Formation being excluded or not is determined.

**Comment by caw310** [comment]
For reference - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1211

**Comment by Andrew565** [comment]
Determined that the 'useLocalStylesAndComponents' flag is indeed working correctly, although it's possible to say it works a little "too well". As nearly every part of the website currently uses formation styles, excluding formation "resets" the site to an essentially bare state, which is for all intents and purposes "broken".

Further research would need to be done to determine what the level of effort would be to get the website to not load Formation but still functionally look good. The short answer is, it won't work well and look correct until the entire site is migrated to USWDS V3.
