### ISSUE TITLE
Audit and update design system React to Web Component migration documentation

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1608]
## Description
It's been a little while since we've reviewed our guidance for developers to convert DS React components to web components. The task here is to check what documentation we have available for developers and determine if we need to make updates or additions to them in order to make the migration task easier for them to get started.

Also one common question we have received is that developers are not clear about how the React binding of web components work. This might be an area of our documentation that we can improve.

Approach this task from the perspective of a new engineer that has not used the VA Design System before.

https://github.com/department-of-veterans-affairs/vets-design-system-documentation

## Tasks
- [x] Review the [How to migrate to Web Components](https://design.va.gov/about/developers/using-web-components#how-to-migrate-to-web-components) section and check if the list of components is accurate and update as needed.
- [x] Review the [Using Web Components](https://design.va.gov/about/developers/using-web-components#react-applications) section for clarity and update as needed.
- [x] Review the [React and Web Compnents](https://design.va.gov/about/developers/using-web-components#react-and-web-components) section for clarity and update as needed.
- [ ] Check any other documentation that might be relevant.
- [x] Create a "quick reference guide" in a Google Doc or somewhere easily accessible that we can share with teams and pin to the dst Slack channel.

## Acceptance Criteria
- [ ] Design system documentation for developers has been reviewed and updated for clarity.

**Comment by jamigibbs** [comment]
FAQ document to assist teams in migrating React components to Web Components: https://docs.google.com/document/d/1sjR-KkSwKFECNFM8Cen6myu93VflXrp9xf52EBRMMNk/edit#
