### ISSUE TITLE
DS Playground - Phase 1 - Add Checkbox and Checkbox Group to the Forms Demo Page

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1610]
## Description
In order to demonstrate compatibility between v1 and v3 components when loaded on the same page, the Checkbox and Checkbox Group components should be added to the DS Playground's "V1 and V3 Side-by-Side Demo" page.

## Tasks
- [x] Add the Checkbox and Checkbox Group components to the V1 and V3 sides of the demo page (vets-website repo)
- [x] Add 'value displays' to each component so that it can be demonstrated that the components function correctly
- [x] Add/modify appropriate formation overrides within the component-library repo
- [x] Verify that these styles render correctly

## Acceptance Criteria
- [x] The V1-compatible and V3-compatible versions of these components render correctly and function correctly when loaded simultaneously within the DS Playground app.

**Comment by powellkerry** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/23633
