### ISSUE TITLE
DS Playground - Phase 1 - Add Memorable Date to the Forms Demo Page

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1611]
## Description
In order to demonstrate compatibility between v1 and v3 components when loaded on the same page, the Memorable Date component should be added to the DS Playground's "V1 and V3 Side-by-Side Demo" page.

## Tasks
- [x] Add the Memorable Date component to the V1 and V3 sides of the demo page (vets-website repo)
- [x] Add 'value displays' to the component so that it can be demonstrated that the component functions correctly
- [ ] Add/modify appropriate formation overrides within the component-library repo
- [ ] Verify that these styles render correctly

## Acceptance Criteria
- [ ] The V1-compatible and V3-compatible versions of this component render correctly and function correctly when loaded simultaneously within the DS Playground app.
