### ISSUE TITLE
USWDS  v3 - Modal  - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1622]
We need to incorporate the designs for the USWDS Modal (VA DS Modal) into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Modal component](https://designsystem.digital.gov/components/modal/)
[VA DS Modal component](https://design.va.gov/components/modal)

## Tasks
- [ ] Conduct small audit if necessary
- [ ]  Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [x]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by LillyBoot** [comment]
The desktop and mobile standard versions are ready for review. Will be creating two different types of special modals (info, continue, success, warning and error). One will be for the MVP (uswds modal measurements + va colors and icons) and the second will be the future uwsds verison

Latest Sketch version: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/184wpO/symbols

**Comment by caw310** [comment]
This will carry over into the next sprint for review and sign off.

**Comment by LillyBoot** [comment]
@caw310 @humancompanion-usds this is ready for review. 

Here is the link to the latest version: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols?g=Modal%252Fuswds-DO%2520NOT%2520USE#Version

**Comment by caw310** [comment]
May carry over into the next sprint for final review and sign off.

**Comment by humancompanion-usds** [comment]
@LillyBoot - I finally got to this. There is a ton of work here. Thank you. A few questions:

1. I'm not seeing an MVP state for a default modal. I do see all of the Alert-based modal variations. We do need the MVP state for our current modal: https://design.va.gov/storybook/?path=/docs/components-va-modal--default In general, double check that we have symbols for all of the variations that we have in Storybook, where needed (there is not quite a 1:1 always but usually that is the case) 

2. We haven't had a chance to discuss font sizing decisions and whether we want to stick to 16px as our base size or use 16.96px or 17px. Let's talk about that on Thursday. We seem to have gone close and rounded up on some of the headers in the modals to get closest to what USWDS has for Merriweather in Sketch. However, in Storybook, for example, for the MVP Success - Large variation we have our h2 header overridden to 21.44px, not 30px as it is in Sketch, nor the USWDS Merriweather value of 27.36. For reference, we use 20px currently. Thus I'm kinda lost as to how we're choosing to interpret USWDS font sizes.

**Comment by LillyBoot** [comment]
@humancompanion-usds I completely forgot to add the default modal for the MVP! I will go ahead and add those. 

In regards to the font sizes my understanding, from Natalie, was that I was to select the font size in sketch that matched the USWDS system the closest.

**Comment by LillyBoot** [comment]
Added the MVP default modal version
