### ISSUE TITLE
Conversion to USWDS v3 - Modal - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1623]
## Description
Adapt the va-modal component to match the [USWDS Modal](https://designsystem.digital.gov/components/modal/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See the [Textarea discovery](https://github.com/department-of-veterans-affairs/component-library/pull/493) for an example
According to the [plan](https://vfs.atlassian.net/wiki/spaces/DST/pages/2366275704/Plan+-+Aligning+VA+Design+System+components+with+their+USWDS+v3+equivalents), we will be using a prop if necessary to differentiate between our version of this component and the USWDS version. It may not be necessary for this component, this can be decided on a case-by-case basis

[USWDS Modal component](https://designsystem.digital.gov/components/modal/)
[VA DS Modal component](https://design.va.gov/components/modal)

## Tasks
- [ ] Create a version of this component that imports and uses the USWDS CSS
- [ ]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ]  Check with Natalie to make sure the component and the design match
- [ ]  Add a USWDS story to Storybook
- [ ]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Write a ticket to add converted component to DS playground

## Acceptance Criteria
- [ ]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library

**Comment by LillyBoot** [comment]
Here is what the modals look like so far. I have updated the header text, body text and button styles. Still working on finalizing the padding. I can upload .svg finals when I'm done if that would be helpful? 

![USWDS Modal_Default ](https://user-images.githubusercontent.com/123974487/229857104-08e23c8f-3625-419e-8c63-c29fd8d0d390.png)
![USWDS Modal_Large ](https://user-images.githubusercontent.com/123974487/229857107-ac64c73f-67e0-4096-84e4-5cd5c120a980.png)
![USWDS Modal_With Foreced Action](https://user-images.githubusercontent.com/123974487/229857108-64d86f8f-48a3-4037-b073-bf98fefdd728.png)

**Comment by jhonnyoddball** [comment]
DST doesn't use `Unstyled` buttons. [Slack discussion about it](https://dsva.slack.com/archives/G01BJ3ESXL4/p1680628850948599)

**Comment by LillyBoot** [comment]
Latest Sketch version: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/184wpO/symbols

The desktop and mobile standard versions are ready. I will be creating two different types of special modals (info, continue, success, warning and error). One will be for the MVP (uswds modal measurements + va colors and icons) and the second will be the future uwsds verison

**Comment by caw310** [comment]
This will carry over into the next sprint as it was more complicated than anticipated with more variations.

**Comment by LillyBoot** [comment]
Here is the link to the MVP modal states (info, continue, success, warning and error): https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/2nG0vp/symbols/?g=Modal%252Fuswds-DO%2520NOT%2520USE%252FMVP
