### ISSUE TITLE
Conversion to USWDS v3 Text input & Input mask to Number Input - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1625]
## Description
Adapt the va-number-input component to match the [USWDS Text input & Input mask](https://designsystem.digital.gov/components/step-indicator/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See the [Textarea discovery](https://github.com/department-of-veterans-affairs/component-library/pull/493) for an example
According to the [plan](https://vfs.atlassian.net/wiki/spaces/DST/pages/2366275704/Plan+-+Aligning+VA+Design+System+components+with+their+USWDS+v3+equivalents), we will be using a prop if necessary to differentiate between our version of this component and the USWDS version. It may not be necessary for this component, this can be decided on a case-by-case basis

[USWDS Text input component](https://designsystem.digital.gov/components/text-input/)
[USWDS Input mask component](https://designsystem.digital.gov/components/input-mask/)
[VA DS Number component](https://design.va.gov/components/form/number-input)

## Tasks
- [ ] Create a version of this component that imports and uses the USWDS CSS
- [ ]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ]  Check with Natalie to make sure the component and the design match
- [ ]  Add a USWDS story to Storybook
- [ ]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Write a ticket to add converted component to DS playground

## Acceptance Criteria
- [ ]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library

**Comment by jamigibbs** [comment]
Discussed with with @humancompanion-usds and @Andrew565, we are going to do a little more discovery around input mask and how masking is currently being used on va.gov. We are already aware that SSN is one way so we should check to how that's being implemented:

- https://staging.va.gov/health-care/apply/application/introduction
- https://design.va.gov/patterns/ask-users-for/social-security-number#examples

We also want to do some exploration on how much effort it would be to update the [USWDS input mask script]( https://github.com/uswds/uswds/blob/develop/packages/usa-input-mask/src/index.js) to work with web components.

For now on this ticket we will just add the v3 styling to `va-number-input` and discuss next week with the USWDS team their reasoning for making [input mask](https://designsystem.digital.gov/components/input-mask/) its own unique component. We may want to make that a separate web component as well.

**Comment by jamigibbs** [comment]
Follow-up ticket for Input Mask development: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1676
