### ISSUE TITLE
DSP - P1 - Add TextArea Component to Playground

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1626]
## Description
In order to demonstrate compatibility between v1 and v3 components when loaded on the same page, the TextArea component should be added to the DS Playground's "V1 and V3 Side-by-Side Demo" page.

## Tasks
- [x] Add the TextArea component to the V1 and V3 sides of the demo page (vets-website repo)
- [x] Add 'value displays' to the component so that it can be demonstrated that the component functions correctly
- [x] Add/modify appropriate formation overrides within the component-library repo (if needed)
- [x] Verify that all styles render correctly

## Acceptance Criteria
- [x] The V1-compatible and V3-compatible versions of this component render correctly and function correctly when loaded simultaneously within the DS Playground app.

**Comment by powellkerry** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/23836
