### ISSUE TITLE
Remove `part` from web components and replace with custom property

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1628]
## Description
As a follow-up to [CSS custom property discovery](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1523), this ticket is to replace `part` with custom property's for approved CSS style overrides as well as update vets-website.

## Details
Part of the work in this ticket will be to decide which of the current style overrides should have a mapped custom property. The [current style overrides can be reviewed here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1523#issuecomment-1474299965) (or just search vets website for `::part` styles). In our discovery discussion, we agreed that `height` should not be included here.

## Tasks
- [ ] Remove `part` from design system web components
       - va-button
       - va-radio
       - va-select
       - va-text-input
       - va-textarea
- [ ] Add CSS custom properties for approved styles. See the [discovery ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1523#issuecomment-1476538955) for naming convention.
- [ ] Update vets-website where `part` was being used but should now be using a custom property

## Acceptance Criteria
- [ ] The `part` attribute has been removed from design system web components
- [ ] Custom properties have been added to components that were previously using `part` for style overrides.
- [ ] Where `part` styles were being overridden in vets-website, it has been updated to use the custom property instead.
