### ISSUE TITLE
Documentation for custom properties

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1630]
## Description
As a follow-up to the [CSS custom property discovery](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1523), this ticket is to create documentation for design system custom properties (both public facing and for the DST).

This ticket should be done after or in tandem with https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1628

## Details

There is a POC in the discovery PR that provides a suggested way to display custom properties on Storybook stories. Maybe there is a cleaner way to do it otherwise, that might be a good place to start: 
- https://github.com/department-of-veterans-affairs/component-library/pull/655

This ticket should also add documentation for DST engineers on our agreed naming convention of custom properties. The discovery suggests the following pattern based on the [Salesforce Styling Hooks](https://www.lightningdesignsystem.com/platforms/lightning/styling-hooks/#site-main-content) approach:

--[namespace]-[scope]-[component]-[element]-[category]-[property]-[attribute]-[state]

```
// Namespace + Scope + Component + Category + Property
--vads-c-button-sizing-height
```

## Tasks
- [ ] Custom properties are displayed in Storybook for components that have them available.
- [ ] There are instructions on how to use custom properties for developers on design.va.gov
- [ ] The [component library readme](https://github.com/department-of-veterans-affairs/component-library) has been updated with a section for DST engineers on how to create and implement a new custom property.

## Acceptance Criteria
- [ ] All of the tasks above have been completed.
