### ISSUE TITLE
Deprecation - Breadcrumb React component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1632]
## Description

Per team discussion, we are sunsetting our previous phased deprecation strategy in favor of directly migrating components ourselves. Migration steps look like this:

1. Submit PR, let the email go out, wait a day. If no action:
2. @ the team(s) directly with a comment on the PR. Wait a day. If no action:
3. Message the team(s) directly in slack, requesting a review.  Wait a day. If no action:
4. Merge pull requests.

## Tasks
- [x] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
- [x] Remove the React component from the component-library repo:
    - [react-components](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/react-components) package
- [x] Remove the related web component(s) from the [web component migrations list](https://design.va.gov/about/developers/using-web-components#web-component-migrations)
- [x] Remove any ESLint rules from [vets-website](https://github.com/department-of-veterans-affairs/vets-website) and the [eslint-plugin](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/eslint-plugin).
- [ ] React Component deprecation has been completed following the above process

## Acceptance Criteria
- [ ] Deprecated component has either been removed entirely (if no longer in use) or moved to the next stage of the deprecation process.

**Comment by jhonnyoddball** [comment]
There are currently 24 instances of Breadcrumbs React component

![Screenshot 2023-03-24 at 1 56 49 PM](https://user-images.githubusercontent.com/55560129/227603754-d5f504b9-ebe9-4818-a95c-5fddd44640d3.png)

**Comment by caw310** [comment]
Will carry over as the direct swap is not as simple for one instance so more work is needed.

**Comment by micahchiang** [comment]
11 instances left in vets-website: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFUvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a31f981dfc513a351e8ef74df6d49933eb33c5f/image.png)

**Comment by micahchiang** [comment]
@harshil1793 - just noticed your associated PR has approvals from everyone needed. Any idea when this can be closed out? Anything you need help with?

**Comment by harshil1793** [comment]
The merge was delayed due to a failing test within an unrelated application named 'pensions.' Consequently, this item will be carried over as we could not complete the merge.
