### ISSUE TITLE
Deprecation - Modal React Component (ticket 1)

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1634]
## Description

Per team discussion, we are sunsetting our previous phased deprecation strategy in favor of directly migrating components ourselves. Migration steps look like this:

1. Submit PR, let the email go out, wait a day. If no action:
2. @ the team(s) directly with a comment on the PR. Wait a day. If no action:
3. Message the team(s) directly in slack, requesting a review.  Wait a day. If no action:
4. Merge pull requests.

## Considerations
- This ticket should aim to deprecate all modals **except** those in `/platform/forms/save-in-progress` and `/platform/user/authentication`:
  - /combined-debt-portal/medical-copays
  - /edu-benefits/1990s/content
  - /edu-benefits/components
  - /gi/components
  - /gi/containers/search
  - /medical-copays/components
  - /personalization/dashboard
  - /personalization/profile/components/connected-apps

This ticket will focus on deprecating 
/combined-debt-portal/medical-copays
/edu-benefits/1990s/content
/edu-benefits/components

There will be separate tickets to deprecate modal from 
Ticket 2:
/gi/components
/gi/containers/search

Ticket 3:
/medical-copays/components
/personalization/dashboard
/personalization/profile/components/connected-apps

## Tasks
- [ ] Remove any existing uses of the React component vets-website and content-build.
- [ ] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
- [ ] Remove the React component from the component-library repo:
    - [react-components](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/react-components) package
- [ ] Remove the related web component(s) from the [web component migrations list](https://design.va.gov/about/developers/using-web-components#web-component-migrations)
- [ ] Remove any ESLint rules from [vets-website](https://github.com/department-of-veterans-affairs/vets-website) and the [eslint-plugin](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/eslint-plugin).
- [ ] React Component deprecation has been completed following the above process

## Acceptance Criteria
- [ ] Deprecated component has either been removed entirely (if no longer in use) or moved to the next stage of the deprecation process.

**Comment by micahchiang** [comment]
WIP:
- `VAPServiceEditModal`: Sort of a black box right now, may require some additional investigation 
- These Modals are rendered in the Header. Migrating them to `va-modal` breaks teamsites because teamsites cannot handle web components:
	- `SignInModal`: click the sign in button to login, modal should pop
	- `TransitionSuccessModal`: open react dev tools locally, in the component tree find the `TransitionSuccessModal.Main` component. Set the `visible` prop to `true` and the modal should pop.
	- `TransitionModal`: open react dev tools locally, in the component tree, find the `Main` component and switch these props to `true`: `mhvTransition`, `mhvTransitionModal`, `showAccountTransitionModal`. This should pop the `TransitionModal`
	- `FormSignInModal`
	- We should look at whether or not it'd be possible to have these pop somewhere other than the header.
	- Creating a some sort of header that works on Teamsites would mean not using our existing va-modal for sign in. 
- `SessionTimeoutModal`: 
- `useDowntimeApproachingRenderMethod`: Only used in the profile, should be safe to migrate
- `ConnectedAppDeleteModal`: Only used in profile to delete connected apps. To test this, run `yarn watch --env entry=profile` in one terminal, then `yarn mock-api --responses src/applications/personalization/profile/mocks/server.js` in another terminal. Visit `localhost:3001/profile/connected-applications` and click `disconnect` on one of them. The modal should pop. NOTE: if your browser is doing some sort of weird redirect, you need to mock session in local storage. Open your browser console and run this: `localStorage.setItem('hasSession', true)`

**Comment by micahchiang** [comment]
Adam Whitlock mentioned the authenticated experience team can do the work for removing all profile instances of `Modal` in their next sprint, which begins on Wednesday. The ticket for tracking this work can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65289). 

We should hold off on attempting to migrate the Modals listed above which render in the header, since that was attempted before and it impacted Teamsites applications. 

Modal imports in `coronavirus-vaccine-expansion`, `/edu-benefits/0994`, and `/edu-benefits/1990s` can be accessed locally by running those applications and accessing them at the root Url.

**Comment by caw310** [comment]
Moving to the next sprint due to complexity.

**Comment by micahchiang** [comment]
<img width="679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGpwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82528591e8de303fc6b44b4a736ffe99562c7419/Screenshot%20from%202024-01-22%2008-19-27.png" alt="Screenshot from 2024-01-22 08-19-27.png" />

**Comment by caw310** [comment]
This ticket will focus only on deprecating modal from 
/combined-debt-portal/medical-copays
/edu-benefits/1990s/content
/edu-benefits/components

Changing estimate to 3.
