### ISSUE TITLE
[Discovery] - Identify best way to organize Sketch libraries and example pages

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1636]
## Description
Conduct discovery work to determine the best way to organize the Sketch libraries and their example pages between:

- Original VA components
- MVP components (USWDS v3 styles + Formation colors)
- USWDS v3 components

## Details
Shared symbols should be organized in their own library files and placed as instances in artboards in separate example pages. These example pages are often linked to from design.va.gov component pages, so URLs will need to be replaced in the documentation.

This work should include engaging VFS designers in order to identify their workflows and how they place component symbols in their mockups. Reach out on #design in Slack and 1:1 to designers. Consider piloting the separated libraries.

## Tasks
- [ ] Create artifacts to demo libraries and example files organization
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary

## Acceptance Criteria
- [ ] Proposed organization is complete and has been reviewed by PO and vetted with VFS designers
- [ ] Work has been started to separate libraries and example pages

**Comment by caw310** [comment]
Closing as this was done in this ticket https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1723
