### ISSUE TITLE
Deprecation Phase 2 of React components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1637]
## Description
We need to begin deprecation of the the remaining React components. Here is information on the [deprecation process](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components).

This means we need to check to see if the component is still being used in vets-website. 
We need to create an ESLint rule to be an error, remove the Storybook story for the component (but leave it in the component-library repo), 
If it is no longer being used, we can remove the ESLint rule altogether and remove the component from the component library.
Here are the remaining React components:
- System down view
- Text input
- Alert Box
- Checkbox group
- Expanding group
- Additional Info
- Breadcrumbs
- Dropdown panel
- Loading indicator
- Modal
- OMB Info
- Pagination
- Progress button
- ProgressButton / button pair React component
- Table
- Telephone
- Select
- Fileinput

See this google sheet for tracking
https://docs.google.com/spreadsheets/d/18PqifqLKODbf_FshTf2e8ftOra86SdGW8xhVNSMAXOQ/edit?usp=sharing

## Details
These are the things that need to be done: 
- Address any bug tickets in the backlog if there are any
- Announce that React component will be deprecated. Request that teams migrate to the web component as soon as possible. If there are issues with the web component that prevent teams from migrating, request that they file a bug ticket.
- Address all bug tickets submitted. We will not move forward with the next phase until all bug tickets have been addressed.

## Tasks

- [ ] Check if the component is being used in vets-website
- [ ] If it is...
    - [ ] Set ESLint rule to an error
    - [ ] Remove deprecated component from Storybook (but keep the component in the component-library repo)
- [ ] If it is not...
    - [ ] Remove the deprecated component from the component library and Storybook
    - [ ] Remove the ESLint rule

## Acceptance Criteria
- [ ] Deprecated component has either been removed entirely (if no longer in use) or moved to the next stage of the deprecation process.
