### ISSUE TITLE
Deprecation Phase 3 System down view

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1640]
## Description

We will deprecate System down view React component.

With the completion of the [Phase 2 ticket]([Deprecation Phase 2 of React components #1637](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1637)), we will need to move the [COMPONENT] React component into [Phase 3](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components#General-deprecation-strategy). This means that the following steps will need to happen:

- Begin migrating any remaining instances of the React component ourselves. 
- The pace of this work will depend on the team’s availability and the priority of this work over other planned work and obligations.
- Once there are no more uses, remove the React component from the component-library repository

## Tasks
- [x] Check if the component is still being used in vets-website
- [x] If it is...
    - [x] Reach out to teams to check if they have an update pending.
    - [x] Migrate any remaining instances of the React component ourselves. 
    - [x] Once there are no more uses, remove the React component from the component-library repository
    - [x] Remove the ESLint rule
    - [x] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
- [ ] If it is not...
    - [ ] Remove the React component from the component-library repository
    - [ ] Remove the ESLint rule

## Acceptance Criteria
- [ ] Deprecated component has been removed entirely.
