### ISSUE TITLE
Deprecation Phase 3 Text Input

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1645]
## Description
We will deprecate Text Input React component.

With the completion of the [Phase 2 ticket]([Deprecation Phase 2 of React components #1637](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1637)), we will need to move the Text Input React component into [Phase 3](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components#General-deprecation-strategy). This means that the following steps will need to happen:

- Begin migrating any remaining instances of the React component ourselves. 
- The pace of this work will depend on the team’s availability and the priority of this work over other planned work and obligations.
- Once there are no more uses, remove the React component from the component-library repository

## Tasks
- [ ] Check if the component is still being used in vets-website
- [ ] If it is...
    - [ ] Reach out to teams to check if they have an update pending.
    - [ ] Migrate any remaining instances of the React component ourselves. 
    - [ ] Once there are no more uses, remove the React component from the component-library repository
    - [ ] Remove the ESLint rule
    - [ ] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
- [ ] If it is not...
    - [ ] Remove the React component from the component-library repository
    - [ ] Remove the ESLint rule

## Acceptance Criteria
- [ ] Deprecated component has been removed entirely.

**Comment by caw310** [comment]
Closing as this is a duplicate of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1805
