### ISSUE TITLE
Replace VA Icon with Combination of USWDS Icons (Icons Audit follow up 1/3)

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1648]
## Description
Follow up to the Icons Audit. This is 1 out of 3 categories for what to do with the VA icons that do not have a USWDS equivalent. 

## Details
(VA Icons = USWDS Icons Combination) 
File alt = menu + upload file (replace paperclip w/menu)
Calendar check = calendar_today + check
File invoice dollar = attach_money + upload_file (replace paperclip w/ attach_money)
File medical = upload_file + add (replace paperclip w/add)
User check = check + person

## Tasks
- [ ] Combine USWDS Icons menu + upload file to create a replacement for VA Icon "file alt" 
- [ ] Combine USWDS Icons calendar_today + check to create a replacement for VA Icon "calendar check"
- [ ] Combine USWDS Icons attach_money + upload file to create a replacement for VA Icon "file invoice dollar" 
- [ ] Combine USWDS Icons add + upload file to create a replacement for VA Icon "file medical" 
- [ ] Combine USWDS Icons check + person to create a replacement for VA Icon "user check" 

## Acceptance Criteria
- [ ]Sketch file has been updated 
- [ ] Icons have been approved by PO

**Comment by caw310** [comment]
Closing as ticket 1800 encompassed work in this issue. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1800
