### ISSUE TITLE
Edit Existing USWDS Icons (Icons Audit follow up 2/3) 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1650]
## Description
Follow up to the Icons Audit. This is 2 out of 3 categories for what to do with the VA icons that do not have a USWDS equivalent.

## Details
(VA Icons = edit USWDS Icons)
Clipboard List = list icon + create clipboard icon
Deaf = hearing icon, add line going through

## Tasks
- [ ] Create a clipboard icon and add USWDS list icon to replace VA icon "clipboard list" 
- [ ] Add a line going through the USWDS hearing icon the replace the VA icon "deaf" 

## Acceptance Criteria
- [ ]Sketch file has been updated
- [ ] Icons have been approved by PO

**Comment by caw310** [comment]
Closing as ticket 1800 encompassed work in this issue. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1800
