### ISSUE TITLE
Create new Icon for VA Icons that do not have a USWDS Replacement (Icons Audit follow up 3/3)

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1651]
## Description
Follow up to the Icons Audit. This is 3 out of 3 categories for what to do with the VA icons that do not have a USWDS equivalent.

## Details
(Icons that do not have a USWDS replacements) 
Road
Handshake
Dot Circle*
Play Circle*
Clipboard Check
Prescription Bottle

## Tasks
- [ ] Create new icon for each one of the icons listed above 

## Acceptance Criteria
- [ ] Sketch file has been updated
- [ ] Icons have been approved by PO

**Comment by caw310** [comment]
Closing as ticket 1800 encompassed work in this issue. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1800
