### ISSUE TITLE
VA Icons Audit Part 2

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1653]
## Description
Follow up to the [Icons Audit](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1476). Discover which of the 13 VA icons that do not have USWDS equivalents can be replace with Material Icons. 

## Details
The 13 VA Icons that do not have USWDS Equivalents: 
File alt
Calendar check
File invoice dollar
File medical
User check
Clipboard List
Deaf
Road
Handshake
Dot Circle
Play Circle
Clipboard Check
Prescription Bottle

Mural Board link: [https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1678830068825/553b0ef0eb59ba6e26ad03692dc255f43c852737?invited=true&sender=ucdde6a5c31c67de71bfb6448]

## Tasks
- [ ] Discover which Icons can be replaced by Material Icons 
- [ ] List the icons that cannot be replaced in the Mural boards (new section)  

## Acceptance Criteria
- [ ] Review with PO

**Comment by LillyBoot** [comment]
10 VA Icons have a Material Icon replacement, 2 Icons have a replacement that is visually different but could work and 1 (road Icons) has no replacement at all.

**Comment by humancompanion-usds** [comment]
Our road icon is for driving directions so I'd recommend the [Directions icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adirections%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048). If you let me know what the 2 are that are different I can make a recommendation.

**Comment by LillyBoot** [comment]
@humancompanion-usds Handshake and Prescription bottle are the one that have replacements but are visually different. I put screenshots in the mural board if you want to take a look. 

https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1678830068825/553b0ef0eb59ba6e26ad03692dc255f43c852737?invited=true&sender=ucdde6a5c31c67de71bfb6448

**Comment by humancompanion-usds** [comment]
@LillyBoot - I think Pill for Prescriptions would be better than the bottle:
https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Apill%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

**Comment by LillyBoot** [comment]
@humancompanion-usds I changed the prescription bottle to the pill. It is very different from what we currently have. Do you think it will be too big of a jump?

**Comment by LillyBoot** [comment]
@humancompanion-usds Ok makes sense. Do we need to create any new tickets based on this audit?

**Comment by LillyBoot** [comment]
Icons will need to be added to V3 Sketch library
