### ISSUE TITLE
Deprecation - Expanding Group React component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1659]
## Description

Per team discussion, we are sunsetting our previous phased deprecation strategy in favor of directly migrating components ourselves. Migration steps look like this:

1. Submit PR, let the email go out, wait a day. If no action:
2. @ the team(s) directly with a comment on the PR. Wait a day. If no action:
3. Message the team(s) directly in slack, requesting a review.  Wait a day. If no action:
4. Merge pull requests.

## Tasks
- [x] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
- [x] Remove the React component from the component-library repo:
    - [react-components](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/react-components) package
- [x] Remove the related web component(s) from the [web component migrations list](https://design.va.gov/about/developers/using-web-components#web-component-migrations)
- [x] Remove any ESLint rules from [vets-website](https://github.com/department-of-veterans-affairs/vets-website) and the [eslint-plugin](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/eslint-plugin).
- [x] React Component deprecation has been completed following the above process

## Acceptance Criteria
- [x] Deprecated component has either been removed entirely (if no longer in use) or moved to the next stage of the deprecation process.

**Comment by micahchiang** [comment]
Hold off for now since we don't have an expanding group web component. I'll look at what some viable alternate solutions are.

**Comment by caw310** [comment]
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1378

**Comment by micahchiang** [comment]
5 instances of the ExpandingGroup react component:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84fc2ee259eeeed6e582a5d51464861f7706e0bc/image.png)

**Note**: The forms library uses a separate react component also called ExpandingGroup which has no dependency on the design system react component of the same name. We are leaving the forms library component alone for the time being.

**Comment by micahchiang** [comment]
Remove instances in burial POC

**Comment by micahchiang** [comment]
The above instance of  ExpandingGroup in the GI application should just be replaced with custom react component  markup using va-radio buttons. The ExpandingGroup React component does not have a direct web component equivalent.
