### ISSUE TITLE
Checkbox - Development - Tile variation in MVP and current state

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1667]
## Description
Build the Tile variation from USWDS of the Checkbox component va-checkbox, as we have done with Radio button tile variation. The va-checkbox-group already has this variation in our MVP of that component.

## Details
- Design documents: https://www.sketch.com/s/3b4400f7-22e8-47fd-aa73-ede5598176b5
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [x] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storyboook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by humancompanion-usds** [comment]
May I also ask that we fix the left alignment of checkbox to match radio button, please? USWDS does not indent their checkboxes nor radio buttons. We addressed this in radio button but not checkbox. They should be consistent both in our current state and in the MVP. Thanks!

**Comment by caw310** [comment]
This will carry over as approvals still needed

**Comment by ndsprinkle** [comment]
@humancompanion-usds @caw310 We had a recent request to add an instance of tiled checkbox group to one of our forms, but from what I can tell, it is not available. I checked storybook as well as the code:

https://design.va.gov/storybook/?path=%2Fdocs%2Fcomponents-va-checkbox-group--default
https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx

Am I misunderstanding this ticket or is the functionality supposed to currently be available? The linked pull request only adds the functionality to va-checkbox, which again seems to line up with the request in this issue, so this is why I'm wondering if there is some misunderstanding of features going on

**Comment by caw310** [comment]
@ndsprinkle , It's actually under checkbox. https://design.va.gov/storybook/?path=/docs/components-va-checkbox--tile

**Comment by ndsprinkle** [comment]
@caw310 Thanks, yeah I knew it existed for checkbox, but what about va-checkbox-group? The description of this issues says "The va-checkbox-group already has this variation in our MVP of that component" which is what's confusing me as I don't see any support for tile in the va-checkbox-group component

**Comment by caw310** [comment]
@ndsprinkle , let me see what engineers recall about that.
