### ISSUE TITLE
USWDS v3 Alert - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1671]
## Description
We need to incorporate the designs for the USWDS Alert component into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Alert component](https://designsystem.digital.gov/components/alert/)
[VA DS Alert component](https://design.va.gov/components/alert)

## Tasks
- [ ] Conduct small audit if necessary
- [ ]  Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [x]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [x]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by LillyBoot** [comment]
Alerts sketch file link: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols?g=Alert%252Fuswds-DO%2520NOT%2520USE 

Alerts - Expandable sketch file link: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols?g=Alert%2520-%2520expandable%252Fuswds-DO%2520NOT%2520USE

**Comment by caw310** [comment]
May carry over into the next sprint for final review and sign off.

**Comment by humancompanion-usds** [comment]
@LillyBoot - Again, great work on all of this. Two things I noticed here:

1. The artboards contain Modal, which I don't think is correct. For example, "Modal - Alerts". 
2. I feel that for the Alert - Expandable it's a little odd to not have the border continue down the left-hand-side of the alert when the content is expanded. Do you agree?

**Comment by humancompanion-usds** [comment]
We landed on bar down the left and text indented to align with the header for the Alert - Expandable. Once that change is made we can close this.

**Comment by LillyBoot** [comment]
Alert - Expandable has been updated
