### ISSUE TITLE
Bring plain language entry to the top level and add examples as 10 child pages

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/vets-design-system-documentation#1675]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Description
Currently in the style guide the [plain language entry](https://design.va.gov/content-style-guide/content-principles/plain-language) nests under content principles. I'd like to bring it up to the top level and place it in the left nav between "Page titles and section titles" and "Punctuation." 

Then create 10 sub pages with [these examples](https://dvagov-my.sharepoint.com/:w:/r/personal/beth_potts_va_gov/Documents/plain%20language%20examples%20for%20entry%20final.docx?d=w76308718e4994b1b83509a9646793c89&csf=1&web=1&e=50ZUNv).

## Details
There are 3 screen shots I'd like to show for the last standard, **Structure your content**. These screen shots are in the sharepoint file linked to above. I just wanted to call this out in case there's guidance you could provide for Megan, who will add most of the examples. Or it may be faster for you to add the screen shots, Matt, rather than explain how to do that.

## Tasks
- [x] Change the placement of the plain language entry - move it to the top level (Matt D.)
- [x] Add 2-3 examples for Megan to use as a jumping off point for the rest of the examples. (Matt D.)
- [ ] Add the rest of the examples (Megan Z.)

## Acceptance Criteria
- [ ] Examples are live in the content style guide.

**Comment by megzehn** [comment]
Update: I created a PR with the remaining examples.

**Comment by humancompanion-usds** [comment]
@megzehn - Is this done? May we close this issue?

**Comment by megzehn** [comment]
Yes @humancompanion-usds ! We can close. Thank you!
