### ISSUE TITLE
Input Mask USWDS v3 - Development

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1676]
## Description
The USWDS system has added an [Input Mask](https://designsystem.digital.gov/components/input-mask/) component that we would like to use. At a minimum, we would like to use the SSN mask since that is currently being used on the 1010EZ form and we also provide SSN guidance as well:

- https://staging.va.gov/health-care/apply/application/introduction
- https://design.va.gov/patterns/ask-users-for/social-security-number#examples

If it's possible to use the [USWDS input mask script](https://github.com/uswds/uswds/blob/develop/packages/usa-input-mask/src/index.js) to work with web components, then we should do that. We may need to take other approaches for this to work though so part of this ticket will be to explore the best approach to scripting since it's not written with web components in mind ([as was already discussed/discovered previously](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1035#issuecomment-1220080964)).

We will be having a meeting with the USWDS team that should provide additional clarity on our approach.

## Tasks
- [ ] (TBD) Create a new input mask component, or, integrate SSN masking into va-number-input (or va-text-input)
- [ ] Write any necessary tests

## Acceptance Criteria
- [ ] Input mask has been added to the component library

**Comment by jamigibbs** [comment]
The USWDS team is working on an updated version of input mask: https://github.com/uswds/uswds/pull/5227

**Comment by caw310** [comment]
Work on this could take 2 sprints

**Comment by Mottie** [comment]
Not sure if it's applicable for this new component, but I tested the new SSN web component field (`web-component-fields/SsnField`). It replaces the value with a masked value on blur, which then led to e2e test failures - the Cypress command that fills in the input also checks the resulting value of the input.

<img width="265" alt="Timed out retrying after 4000ms expected '345678900', actual '●●●-●●-8900'" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/e36e52b7-037f-4512-9c20-129792abfeef">

**Comment by tbaker1026** [comment]
@jamigibbs can we close this one since we have an SSN pattern now and the ez should be updated to use the SSN pattern not text input or am I reading this one wrong?
