### ISSUE TITLE
Update Privacy Agreement with USWDS v3 checkbox - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1678]
## Description
Adapt the va-privacy-agreement component to use the [USWDS Checkbox](https://designsystem.digital.gov/components/checkbox/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See these examples for guidance. 
* va-radio: https://github.com/department-of-veterans-affairs/component-library/pull/579
* va-select: https://github.com/department-of-veterans-affairs/component-library/pull/610
* va-textarea: https://github.com/department-of-veterans-affairs/component-library/pull/654
* va-button: https://github.com/department-of-veterans-affairs/component-library/pull/645

[USWDS Checkbox component](https://designsystem.digital.gov/components/checkbox/)
[VA DS Privacy agreement](https://design.va.gov/components/form/privacy-agreement)

## Tasks
- [x] Create a version of this component that imports and uses the USWDS CSS
- [x]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [x]  Check with Natalie to make sure the component and the design match
- [x]  Add a USWDS story to Storybook
- [ ]  Merge component
- [x]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ]  Write a ticket to add converted component to DS playground

## Acceptance Criteria
- [ ]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library

**Comment by jamigibbs** [comment]
@harshil1793 The v3 variation for `va-checkbox` was added here:
- https://github.com/department-of-veterans-affairs/component-library/pull/624

**Comment by humancompanion-usds** [comment]
Sketch design for Privacy agreement: https://sketch.com/s/3b4400f7-22e8-47fd-aa73-ede5598176b5
