### ISSUE TITLE
Discovery: Migration scripts for Modal, Breadcrumbs, OMB info and Telephone

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1692]
## Description
Take a look at the previous migration scripts and determine whether or not the following components can also be migrated automatically using a similar script.

- Modal
- Breadcrumbs
- OMB Info
- Telephone

## Details

The public facing migration script page links to components that have existing scripts:
https://github.com/department-of-veterans-affairs/vets-website/tree/main/script/component-migration

ESLint Plugin
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/eslint-plugin

See previous tickets related to migration scripts 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/33180
 - https://github.com/department-of-veterans-affairs/va.gov-team/issues/32872

There is also this confluence page with information: https://vfs.atlassian.net/l/cp/Np0WVbuL

## Tasks
- [x] Review the previous tickets with information on creating migration scripts for specific components
- [x] Review confluence page Manual Component Migration Guide -  https://vfs.atlassian.net/l/cp/Np0WVbuL
- [x] Share findings with the team
- [x] make recommendation on which of the 4 components could have a migration script written 

## Acceptance Criteria
- [ ] Discovery findings shared with the engineers 
- [ ] Share recommendation with the team
- [ ] Write corresponding tickets if needed

**Comment by jamigibbs** [comment]
**ESLint Rules Completed with Migration "Quick Fix" (click to convert)** 🎉 

✅ Modal
✅ Breadcrumbs
✅ OMB Info
✅ Telephone
 
**Other components with ESLint "Quick Fix" migration available** 🎉 
✅ TextInput
✅ Table
✅ Pagination

https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/e37233f7ed059c91bf43e92f825390bbf5991298/packages/eslint-plugin/lib/rules/prefer-web-component-library.js

## Component Deprecation Migration Overview

### 1. `eslint.changed.js` and `.eslintrc.js` (vets-website)

**What this does:**
- Displays a warning (1) or error (2) on the _component import_, and
- Flags a linting warning (1) or error (2) when the file is attempted to be committed with that import.
  - If the rule is set to error (2), they will not be able to commit the file until the error is resolved.
- Underlines the component import and provides guidance on what to use instead when hovered.

**PR Example**
- https://github.com/department-of-veterans-affairs/vets-website/pull/23737

**Code Editor Example**

![Screenshot 2023-05-04 at 9 28 19 AM](https://user-images.githubusercontent.com/872479/236238266-c7bdc311-032e-4bcc-b8aa-53e00f651a37.png)


### 2. [ES Lint Plugin](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/e37233f7ed059c91bf43e92f825390bbf5991298/packages/eslint-plugin) - Migration "Quick Fix" and/or deprecation details

**What this does:**
- Displays a linting error/warning on the _component_ itself
- Hovering over the component will display more information
- Click to migrate is possible.

**Examples**
- Click to migrant OMB Info: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/867
- Component flagged and hovering displays more info: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/877
- See also other scripts in [prefer-web-component-library.js](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/lib/rules/prefer-web-component-library.js)

Note: We shouldn't offer an automated suggestion/click to migrate if we know that it would be a breaking change. An example of a breaking change is if we have added a custom event that is different from the React component and we are not able to change the way the previous event response was being handled (ie. a different event response structure). See the following PR for an example and discussion about this:

- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/868#pullrequestreview-1106078057

**Code Editor Example**

![Screenshot 2023-05-04 at 11 40 40 AM](https://user-images.githubusercontent.com/872479/236269825-75c5960e-f32c-45ef-ba53-811827df99db.png)

![Screenshot 2023-05-04 at 11 40 46 AM](https://user-images.githubusercontent.com/872479/236269824-f69b73eb-7887-4e84-a0f4-b36d1eead4ea.png)

### 3. Component Migration Script

- https://github.com/department-of-veterans-affairs/vets-website/tree/main/script/component-migration

It does not appear that we should be adding to this custom script any longer because the `eslint-plugin` rules can do the same thing with the added benefit of having a "Quick Fix" click to migrate option in the code editor directly.

There are three components already added to this script though and we should continue to offer this migration approach for those components but going forward, we should be leveraging `eslint.changed.js`, `.eslintrc.js`, and the `eslint-plugin` to manage deprecations.

✅ AdditionalInfo
✅ AlertBox
✅ LoadingIndicator

**Comment by jamigibbs** [comment]
Presented findings in our weekly engineering meeting so marking this case closed.
