### ISSUE TITLE
Audit of Forms components 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1696]
## Description
Do an audit of the form components that have been converted for the MVP. Compare guidance, Sketch and Storybook to make sure everything is aligned for the following components 

- memorable-date, 
- button
- button-pair
- text-input
- select
- radio button
- checkbox
- textarea
- Modal

conversions for these are not complete yet 
- Additional Info 
- file input
- progress bar - segmented  

## Tasks
- [ ] Compare guidance, Sketch and Storybook for the components listed above
- [ ] Identify and document where there are discrepancies
- [ ] Review audit with PO and DST team
- [ ] Write tickets for follow up work

## Acceptance Criteria
- [ ] Audit has been reviewed with PO and team
- [ ] Tickets have been written for follow up work

**Comment by caw310** [comment]
Barb has just started with the team this week so this work will start in sprint 25 and carry over into sprint 26.

**Comment by babsdenney** [comment]
The audit is complete.
You can view the mural with the comparisons and summary here. 

[MVP Mural Audit](https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1682022611049?sender=ucf13c21d112482a4c5766770&key=19765ef2-df74-42ae-826c-92a04952d753)

**Comment by humancompanion-usds** [comment]
We decided that Barb and Carol would file a number of issues. Once that is done we can close this.

**Comment by caw310** [comment]
The list of tickets from this audit are in this Slack thread. 
https://dsva.slack.com/archives/G01BJ3ESXL4/p1683234828520909

**Comment by caw310** [comment]
Here are the tickets for the component updates
Align MVP memorable date in Sketch with USWDS #1742 - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1742 

Align MVP Button  in Sketch with USWDS - Design - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1743  

Align MVP Button Pair  in Sketch with USWDS- Design - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1744 

Align MVP Text-input in Sketch with USWDS - Design - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1745 

Align MVP Select in Sketch with USWDS - Design - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1746 

Align MVP Radio Button in Sketch with USWDS - Design - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1747 

Align MVP Checkbox in Sketch with USWDS - Design - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1748 

Align MVP Textarea in Sketch with USWDS - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1749

**Comment by caw310** [comment]
Here is the ticket for discovery work on aligning examples
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1751

**Comment by caw310** [comment]
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1752
