### ISSUE TITLE
Conversion to USWDS v3 - Breadcrumbs - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1716]
Adapt the va-breadcrumb component to match the [USWDS Breadcrumb](https://designsystem.digital.gov/components/breadcrumb/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See these examples for guidance. 
* va-radio: https://github.com/department-of-veterans-affairs/component-library/pull/579
* va-select: https://github.com/department-of-veterans-affairs/component-library/pull/610
* va-textarea: https://github.com/department-of-veterans-affairs/component-library/pull/654
* va-button: https://github.com/department-of-veterans-affairs/component-library/pull/645

[USWDS Breadcrumb component](https://designsystem.digital.gov/components/breadcrumb/)
[VA DS Breadcrumbs component](https://design.va.gov/components/breadcrumbs)

## Tasks
- [x] Create a version of this component that imports and uses the USWDS CSS
- [x]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ]  Check with Natalie to make sure the component and the design match
- [x]  Add a USWDS story to Storybook
- [ ]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [x] Write a ticket to add component to DS playground

## Acceptance Criteria
- [x]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library
- [ ] Ticket written to add component to DS playground

**Comment by caw310** [comment]
Will carry over due to complexity.

**Comment by caw310** [comment]
Will carry over again. Development is almost completed but review is needed.

**Comment by caw310** [comment]
This will carry over due to unexpected PTO for an emergency.

**Comment by harshil1793** [comment]
The logic has been optimized and cleaned up. However, due to the time it took to complete these modifications, the pull request (PR) was submitted later than expected. As a result, the PR is unlikely to be reviewed today.
