### ISSUE TITLE
Update "Contributing" Documentation

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1717]
## Description
Update documentation and guidance of the "[Contributing](https://design.va.gov/about/developers/contributing)" section of the "For Developers" section of design.va.gov, as well as the [Contributing to the Design System](https://design.va.gov/about/contributing-to-the-design-system/) section.

## Details
Both sections should be updated to point users to upload code to the component-library repo, along with help and instruction for how to setup a new web component. Include any helpful docs on writing web components, or find some if none are immediately available. Include at a minimum links to [Sass](https://sass-lang.com/documentation/) and [Stencil's "My First Component" docs](https://stenciljs.com/docs/getting-started#my-first-component).

## Tasks
- [ ] Write or update documentation for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Documentation is published on design.va.gov

**Comment by caw310** [comment]
Will carry over into the next sprint for completion and sign off.
