### ISSUE TITLE
USWDS v3 - Accordion - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1718]
Design
We need to incorporate the designs for the USWDS Accordion component into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Accordion component](https://designsystem.digital.gov/components/accordion/)
[VA DS Accordion component](https://design.va.gov/components/accordion)

## Tasks
- [x] Conduct small audit if necessary
- [x]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
This is planned for sprint 28 but Barb is getting started on this in sprint 27. :)

**Comment by babsdenney** [comment]
@humancompanion-usds @LillyBoot This is complete. I used the USWDS spacing and styles with the VA font and colors. You can view the new Accordion component here.
- [UWDS Accordion](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/x0gD7w8)

**Comment by humancompanion-usds** [comment]
Looks good to me! Are we moving this into the appropriate library?

**Comment by babsdenney** [comment]
Thanks for the feedback! I moved the maintenance banner and accordions to the USWDS v3 Component Library. 
- [Accordion](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7/p/52A7877D-E58C-48AF-923C-D1955C5BCE7D/canvas)
- [Maintenance banner](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7/p/D413251A-9268-4E48-9E4C-8E8A3A6B31F9/canvas)
