### ISSUE TITLE
Conversion to USWDS v3 - Accordion - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1719]
Adapt the va-accordion component to match the [https://designsystem.digital.gov/components/accordion/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See these examples for guidance. 
* va-radio: https://github.com/department-of-veterans-affairs/component-library/pull/579
* va-select: https://github.com/department-of-veterans-affairs/component-library/pull/610
* va-textarea: https://github.com/department-of-veterans-affairs/component-library/pull/654
* va-button: https://github.com/department-of-veterans-affairs/component-library/pull/645

[USWDS Accordion component](https://designsystem.digital.gov/components/accordion/)
[VA DS Accordion component](https://design.va.gov/components/accordion)

## Tasks
- [x] Create a version of this component that imports and uses the USWDS CSS
- [x]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ]  Check with Natalie to make sure the component and the design match
- [x]  Add a USWDS story to Storybook
- [ ]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Write a ticket to add component to DS playground

## Acceptance Criteria
- [ ]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library
- [ ]  Ticket written to add component to DS playground

**Comment by babsdenney** [comment]
Here are designs for the Accordion
[Sketch](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/E65548E2-EFDF-4CC9-A6FB-FC0D14B66C1B/canvas)
