### ISSUE TITLE
Create New Sketch Workspaces / Library

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1723]
## Description
We need to create new Sketch workspaces for the MVP, v3 and an icons library. 

## Tasks
- [ ] Create a Sketch Workspace for the MVP 
- [ ] Create a Sketch Workspace for the v3 future state
- [ ] Create a Icons Library separate from the Components library 

## Acceptance Criteria
- [ ] Reviewed by PO

**Comment by LillyBoot** [comment]
@humancompanion-usds @babsdenney I created 4 separate libraries. I decide to separate out the components from foundations (icons, font, color, etc.) and patterns. The goal of this was to declutter the design library. 

1.  USWDS MVP Component Library - contains all of the web and form components we have done so far for the MVP. https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4

2.  MVP Foundations & Pattern Library - contains the VA patterns, colors, grids, iconography, typography, header and footer. We can add any changes to this library without affecting the current design library i.e if we want to change font sizes. https://www.sketch.com/s/998b1585-ba60-474f-ba5d-85729b247f3c

3.  USWDS v3 Component Library - contains the future state of the components we have be working on. https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7

4.  USWDS Foundations and Pattern Library - contains future changes we will make to foundations and patterns i.e the material/uswds icons. https://www.sketch.com/s/4771ada9-af5a-4946-b6c3-3dea9806a6f4

**Comment by humancompanion-usds** [comment]
This all looks good. Let's just also break out the symbols as well.

**Comment by babsdenney** [comment]
@humancompanion-usds Thank you! I moved the following patterns
- Ask users for multiple responses
- Ask users for signature

from the following libraries

-  [MVP Foundations & Pattern Library](https://www.sketch.com/s/998b1585-ba60-474f-ba5d-85729b247f3c)
-  [USWDS Foundations and Pattern Library](https://www.sketch.com/s/4771ada9-af5a-4946-b6c3-3dea9806a6f4)

and placed in [Templates library](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)

**Comment by humancompanion-usds** [comment]
We haven't broken out the symbols. Either we need a new issue for that or this is still in progress.

**Comment by babsdenney** [comment]
Here's the ticket to break out the examples from the Sketch component libraries. 

[Ticket #59048](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/59048)
