### ISSUE TITLE
Epic: Footer - Web Component - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1724]
## Description
Build a web component of the Footer. Be sure to add analytics if necessary, see [guidance](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
- Design documents: https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=1702%3A14515&mode=design&t=norzpSpbicSFZxaP-1 
- Review this PR for the minimal footer variation used by VAOS: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1431
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Check with designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Work on this will be at least 2 sprints as it will need to go through staging review.

**Comment by jamigibbs** [comment]
A few questions asked in the team Slack channel:

Q: Should we include the [minimal footer variation](https://github.com/department-of-veterans-affairs/content-build/pull/1436) as part of this work right now?
A: The minimal footer is an experiment proposed by the check-in team and will work on that after we have the main/full footer that we have today.

Q: Does the footer data need to be generated and managed [from Drupal](https://github.com/department-of-veterans-affairs/vets-website/pull/24155) in this [JSON file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/landing-pages/header-footer-data.json)? Or can we just bring it in to the web compnent for DST to manage?
A: We don't know yet. We need to discuss with sitewide folks (Dave and Will) who will know if there is a requirement there or not. But link consistency across all uses is a goal so if we can also start managing those links, we think that would be ideal.

We will also likely want to do a discovery ticket for this first before dev can start to understand the existing architecture a little more across different teams.

**Comment by caw310** [comment]
Work on this will be paused in Sprint 27 as discovery work is needed before moving forward.

**Comment by caw310** [comment]
Based on discovery findings, we will focus on building only on a minimal variation for use in applications. 
New ticket for that work - 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1777

**Comment by caw310** [comment]
Moving this back to prioritize at a later time.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1724?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Closing as this is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/80493
