### ISSUE TITLE
Epic: Build Web Components 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1725]
## Description
This epic is to track web component design and development work which is part of the initiative to Create web components to remove the dependency on Formation. 

## Details
DST will do design and development to build web components for
- maintenance banner 
- footer 
- header
- icon

## Tasks
- [ ] Create Sketch assets for the components
- [ ] Review designs with DST
- [ ] Get approval of designs from PO
- [ ] Build web component version of the components 
- [ ] Draft any documentation needed for the components 
- [ ] Update design.va.gov with the new web components

## Acceptance Criteria
- [ ] Designs are approved and in Sketch Library
- [ ] Component is updated on design.va.gov 
- [ ] Web components are in Storybook

**Comment by caw310** [comment]
Closing as the work is complete and was tracked in another initiative.
