### ISSUE TITLE
Create "Sign in to start your application" variation in Alert

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1731]
## Description

We use a particular variation of an Alert - Info on the [Intro page](https://design.va.gov/templates/forms/introduction#save-work-in-progress-alert) for all forms. We've captured an image of it in the Intro page template but we don't offer the variation in Sketch or as a specific variation in Storybook or guidance. We should provide it just like we do for the "Sign-in tool prompt" variation which is used much less frequently.

## Details
@jeana-adhoc has already [created a symbol for this](https://www.sketch.com/s/9766bff3-3825-49af-a417-e018bf3e0e87/p/AADC4C8B-95C4-43E1-A429-17126ED57237/canvas)

## Tasks
- [x] Create example and symbol in Sketch
- [x] Create variation in Storybook
- [ ] Add variation to design.va.gov

## Acceptance Criteria
- [ ] Symbol and example exist in Sketch library
- [ ] Variation exists in Storybook
- [ ] Variation exists in guidance
