### ISSUE TITLE
USWDS v3 - Number input masking - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1733]
We need to incorporate the designs for the USWDS Input Mask (VA DS Number input) into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Input mask component](https://designsystem.digital.gov/components/input-mask/)
https://designsystem.digital.gov/components/input-prefix-suffix/
[VA DS Number component](https://design.va.gov/components/form/number-input)

## Tasks
- [x] Conduct small audit if necessary
- [x]  Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [x]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by babsdenney** [comment]
This is ready for review. 

- [Here is the audit](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7/a/P1Rlk1P) to compare the different number input options within USWDS and VADS
- [Input mask symbols](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7/a/g17gd1a)
- Broke out the [suffix and prefix example](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7/a/9l5Y8lp) on the number input page to a separate artboard
- Redid the [number input](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7/a/QDRZkAL) and [text input](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7/a/vRgoLl4) form fields to use a single symbol.
  - Increased width of form fields to 320px to match USWDS
