### ISSUE TITLE
Update "Releasing" Documentation

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1734]
## Description
Andrew to type up discussion results from release cadence meeting, as well as make sure instructions for creating new releases of the component-library repo are up-to-date.

## Details
* Moving to a regular release cycle, starting at the beginning of each new sprint.
* Creation of a 'release manager' role - Andrew to perform this duty for now

## Tasks
- [ ] Update release instructions
- [ ] Add guidance on release cadence

## Acceptance Criteria
- [ ] Documentation updated/created
- [ ] Engineers are in agreement with proposed changes
