### ISSUE TITLE
USWDS v3 - Process List - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1736]
We need to incorporate the designs for the USWDS Process List component into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Process List component](https://designsystem.digital.gov/components/process-list/)
[VA DS Process List component](https://design.va.gov/components/process-list)

## Tasks
- [x] Conduct small audit if necessary
- [x]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Will carry over, most likely for review and sign off.

**Comment by LillyBoot** [comment]
@babsdenney @humancompanion-usds this is ready for review

Sketch file links: 
[Process List Symbols](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/symbols?g=Process%2520List%252Fstep)
[Process List Examples](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/6C4E1C75-E50B-4690-AB3F-27F7C3F297C6/canvas)

**Comment by LillyBoot** [comment]
@humancompanion-usds @babsdenney 
Updated Sketch Links: 
[Process List Symbols](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/v/V5Pwdq/symbols?g=Process%2520List#Version)
[Process List Examples](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/6C4E1C75-E50B-4690-AB3F-27F7C3F297C6/canvas)

What was updated: 
1. Removed the link from the active header and made it the primary color #0071BB
2. Created a pending state for the number and header
3. The default version will not contain status options. There is now a separate status version

**Comment by babsdenney** [comment]
@LillyBoot This looks so good! The only thing I saw was it looks like some symbols have been added to the example library. They might be duplicates. 
![image.png](https://images.zenhubusercontent.com/5b85b0ec5088171524080d7b/1c8ed104-d633-4374-9cd4-1ba736c1aeb1)

**Comment by LillyBoot** [comment]
@babsdenney thank you for catching that! It should be fixed now

**Comment by humancompanion-usds** [comment]
Looks good!
