### ISSUE TITLE
Conversion to USWDS v3 - Process List - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1737]
## Description
Adapt the va-process-list component to match the [USWDS Process List component](https://designsystem.digital.gov/components/process-list/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See these examples for guidance. 
* va-radio: https://github.com/department-of-veterans-affairs/component-library/pull/579
* va-select: https://github.com/department-of-veterans-affairs/component-library/pull/610
* va-textarea: https://github.com/department-of-veterans-affairs/component-library/pull/654
* va-button: https://github.com/department-of-veterans-affairs/component-library/pull/645

[USWDS Process List component](https://designsystem.digital.gov/components/process-list/)
[VA DS Process List component](https://design.va.gov/components/process-list)

## Tasks
- [ ] Create a version of this component that imports and uses the USWDS CSS
- [ ]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ]  Check with Lily to make sure the component and the design match
- [ ]  Add a USWDS story to Storybook
- [ ]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Write a ticket to add component to DS playground

## Acceptance Criteria
- [ ]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library
- [ ]  Ticket written to add component to DS playground

**Comment by LillyBoot** [comment]
[Process List Examples](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/6C4E1C75-E50B-4690-AB3F-27F7C3F297C6/canvas)

**Comment by LillyBoot** [comment]
Updated Sketch Links: 
[Process List Symbols](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/v/V5Pwdq/symbols?g=Process%2520List#Version)
[Process List Examples](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/6C4E1C75-E50B-4690-AB3F-27F7C3F297C6/canvas)

What was updated: 
1. Removed the link from the active header and made it the primary color #0071BB
2. Created a pending state for the number and header
3. The default version will not contain status options. There is now a separate status version
