### ISSUE TITLE
Align MVP Radio Button in Sketch with USWDS - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1747]
## Description
The following work was identified from the audit of the converted form components. 

## Details
1. Change name from ‘Radio Button’ to ‘Radio Buttons’
2. Design
    * Make sure the width is correct
    * Fix the radio button circle size
    * Make sure the padding and margins are correct
    * Add all variations to Sketch
3. Code
    * Internationalization example differs between USWDS and Sketch

## Tasks
- [ ] Make the updates identified in the audit
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

 reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack
