### ISSUE TITLE
Discovery: Document how Storybook, DS, USWDS and Sketch align examples of a component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1751]
## Description
This discovery originates from the Audit of the forms components. 

## Details
Finding from audit: 
Example alignment The examples between the different sources of truth vary. Align examples between Storybook, the VADS, and Sketch. Lily suggested alphabetically reordering all the examples to align with USWDS while keeping Default at the top.

    * Audit
    * Document findings
    * Share findings
    * Make a recommendation  

## Tasks
- [ ] Conduct small audit if necessary 
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Make a recommendation to PO and DST
- [ ] Write tickets for next steps of work to be done

## Acceptance Criteria
- [ ] Audit is complete and has been reviewed
- [ ] Findings and recommendation shared with PO and team 
- [ ] Tickets written for follow up work

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
