### ISSUE TITLE
Template library - Discovery 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1752]
## Description
The following work was identified from the Audit of the Form Components.

## Details
Question that came from Audit: 
How do teams use the template library?

## Tasks
- [ ] Reach out to Forms team
- [ ] Discover how designers use the template library
- [ ] Create recommendations on the next steps to make the template library more user-friendly

## Acceptance Criteria
- [ ] Discovery has been completed and reviewed 
- [ ] Findings and recommendations shared with PO and team
- [ ] Ticket written for follow up work

**Comment by caw310** [comment]
Closing as this is old.
