### ISSUE TITLE
Align Guidance between VA v1 and USWDS v3

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#1753]
## Description
Currently, the guidance could fit into three different buckets. 
1. Aligned with USWDS guidance
2. Additional guidance specific to VADS
3. Guidance that does not follow the USWDS for specific reasons

## Details
[USWDS Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1682022611049/4b1687a42956d2d286f66411af7611a0aee1946b?sender=ucf13c21d112482a4c5766770) 

## Tasks
Do a discovery on how guidance is structured on VADS and how to create more clarity around the guidance and where the VA differs from USWDS and where there is alignment.

- [x] Use USWDS form audit to see differences between the USWDS and VADS.
- [x] Review discovery with PO and DST team

### Update guidance for MVP components
1. [x] Memorable date
2. [x] Select
3. [x] Breadcrumbs
4. [x] Button
5. [x] Button Pair
6. [x] Modal
7. [x] Accordion
8. [x] Alert
9. [x] Process list
10. [x] Privacy agreement
11. [x] Pagination
12. [ ] Icon

## Acceptance Criteria
- [x] Discovery has been reviewed with PO and team
- [ ] Guidance has been updated for MVP components

**Comment by humancompanion-usds** [comment]
I'm going to pick up this issue and start working through aligning the guidance. I'm just changing the title slightly to drop the discovery bit given that Barb already did that in the Mural file. Now I've just got the make it so in the guidance itself.

**Comment by humancompanion-usds** [comment]
* Pagination is not in Storybook yet. 
* Icon isn't available yet. 

Thus I'm going to create a PR for the 5 components I have merged with USWDS guidance.
