### ISSUE TITLE
Add width types for number input

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1771]
## Description
Add width types for number input component based on USWDS width sizes. 

## Details
https://designsystem.digital.gov/components/text-input/#component-variants-text-input

usa-input--[width]
Displays an input at a specific width. Accepts 2xs (4ex), xs (7ex), sm or small (10ex), md or medium (20ex), lg (30ex), xl (40ex), and 2xl (50ex).

Reference this ticket for text input: 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1712 

## Tasks
- [ ] add variant sizes for number input to va-number-input
- [ ] update storybook 
- [ ] show variants to DST and PO
- [ ] address any fixes / changes

## Acceptance Criteria
- [ ] Component is updated Storybook
- [ ] Component has been reviewed and has gotten sign off

**Comment by caw310** [comment]
Added to sprint as unplanned work.
