### ISSUE TITLE
Minimal Footer - Web Component - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1777]
## Description
Build a minimal footer web component. Be sure to add analytics if necessary, see [guidance](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
- Design documents: https://sketch.com/s/f5f91c9c-f5c5-41f6-8e7e-6cfe003299fa  (same file as minimal header)
- Review this PR for the minimal footer variation used by VAOS: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1431
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)
- [Prior discovery ticket + convo to move forward with minimal footer](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1767)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Check with designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1777?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010

**Comment by micahchiang** [comment]
The sketch file link is set to private so I can't access. Can we verify who ever picks up this ticket has access to the sketch file mocks, and that those mocks are as up to date as possible?

**Comment by it-harrison** [comment]
@humancompanion-usds @danbrady @LWWright7 do you know where I can locate the circled asset below?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenlNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48cea20aa354babfd99e7418b97b34ed0d40a114/Screenshot%202023-10-31%20at%202.48.43%20PM.png)

**Comment by danbrady** [comment]
@it-harrison Here's one with a transparent background:

![transparent background](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/3ddf4409-a8ed-4c72-af56-2cbe544673e4)

If the anti-aliasing looks too pixelated, here's another on primary-darker (#112e51) background.

![solid background](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/e6ca36ad-d5a8-428d-bf38-f9792100904e)

(Let me know if there is a better place to put them.)

**Comment by it-harrison** [comment]
@rtwell do you know where the asset(s) are to implement the sketch design? I see [this file in vets-website ](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/site/assets/img/seal/seal-footer.svg) but the colors are wrong on the seal. The png Dan provided seems a little low-res so I wanted to double check with you. Thanks!

**Comment by danbrady** [comment]
FWIW: I pulled those graphics from the Header/Footer Sketch file that which only has raster images at those sizes.

I did some digging around to see where vector logos are stored... 

(TL;DR I didn't find it.)

On the [logos page](https://design.va.gov/foundation/logos) of the doc site, we reference and link to [Graphic Standards PDF](https://www.va.gov/vapubs/viewPublication.asp?Pub_ID=683&FType=2). That PDF has guidance on logo usage with references to assets in a "VA Brand Graphics Repository". However, it doesn't actually have that link in the PDF and I can't seem to find that anywhere publicly. (Note that PDF is dated Aug 2012.)

[VA Mobile Branding Requirements and Resources](https://mobile.va.gov/va-mobile-app-compliance-requirements#vamobilebrandingrequirementsandresources) references an "App Logo Library".  However, it's not a link.

Wikimedia has an [SVG of the full color version](https://commons.wikimedia.org/wiki/File:US_Department_of_Veterans_Affairs_logo.svg). However, they don't have the single color version that is used in this component.

**Comment by danbrady** [comment]
@it-harrison I rebuilt the logo as an SVG. Here is a compressed, transparent version:

![va-logo-white_transparent](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/1f8a390e-d327-491d-bbb3-ab460c0ce6e1)

It is a lot clearer, but note that the file size is a bit bigger than the blurry PNG. SVG is ~80k/26k gzipped.

**Comment by it-harrison** [comment]
PR is [HERE](https://github.com/department-of-veterans-affairs/component-library/pull/937)

**Comment by it-harrison** [comment]
@danbrady thanks much for your help on this issue!

**Comment by it-harrison** [comment]
This will carry over to fix a problem in storybook where the code is not being displayed when the show code button is clicked.

**Comment by caw310** [comment]
@danbrady , please review from design perspective.

**Comment by danbrady** [comment]
Left [comments](https://github.com/department-of-veterans-affairs/component-library/pull/937#discussion_r1388625648) on the PR.
