### ISSUE TITLE
Document how VFS teams can use USWDS v3 MVP components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1784]
## Description
Create documentation for teams so they can achieve build configurations in their own applications  to use the flag in the build
in order to use the USWDS v3 MVP components. 

## Tasks
- [ ] Draft documentation that describes how to use USWDS v3 MVP components
- [ ] Review documentation with PO (Matt) and DST
- [ ] Make edits 
- [ ] Identify where to post this information to share with VFS team

## Acceptance Criteria
- [ ] Documentation has been reviewed and approved
- [x] Documentation is posted in a place where VFS teams can access it

**Comment by Andrew565** [comment]
@humancompanion-usds @caw310 I'm pretty certain the only thing required at this time is the inclusion of the `uswds` flag on every component that a team wants to render in v3-mode. I can write this up somewhere if helpful, but that's the only requirement right now.

**Comment by humancompanion-usds** [comment]
That's fine. Let's create a sub-section on this page to tell developers that: /about/developers/using-web-components

We'll need a similar update to /about/designers/design-libraries to tell designers about the new Sketch libraries. You can hand this ticket to me once we've added the developer portion.

**Comment by humancompanion-usds** [comment]
Deployed the guidance this morning.
