### ISSUE TITLE
Add a green background color option to va-button and update va-alert slot content

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1789]
## Description

Additional context in Slack: https://dsva.slack.com/archives/C01DBGX4P45/p1685029135087739?thread_ts=1685024080.164349&cid=C01DBGX4P45

We would like to change the slot content for `va-alert` to use `va-button` (where applicable) but there is not currently a green background color for va-button. Right now it is using the Formation class with an HTML button:

```html
<button class="va-button-primary">Sign in to VA.gov</button>
```

```css
.va-button-primary {
  background: $color-green;

  &:hover,
  &:focus {
    background-color: $color-green-darker;
    text-decoration: none;
  }
}
``` 

The task would be to add an option to the va-button component so that it displays similar to the way the `.va-button-primary` class is in Formation. That way we can just use va-button when a green background is required instead of the Formation class.

Example:  https://design.va.gov/storybook/?path=/docs/components-va-alert--sign-in-or-tool-prompt

![Screenshot 2023-05-25 at 12 03 25 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/308350d8-58e5-44cf-9272-490a4f1b570b)

## Tasks
- [x] Add a green background option to va-button.
- [x] Add a new Storybook story for va-button for the green background.
- [x] Update the va-alert Storybook examples (v1 & v3) to use va-button in the slot content instead of the HTML button.

## Acceptance Criteria
- [x] The va-button component button has been updated.
- [ ] Design has reviewed.
- [x] Storybook slot examples have been updated to use va-button.
