### ISSUE TITLE
Document new CSS utility classes 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1790]
## Description
Document new CSS utility classes so that other teams understand how to use them. 

## Tasks
- [ ] Write documentation on how to use the new CSS utility classes
- [ ] Share and review with DST engineers and Matt
- [ ] Make any edits to the documentation based on feedback
- [ ] Post on design.va.gov 

## Acceptance Criteria
- [ ] Documentation has been reviewed and signed off by DST engineers and Matt
- [ ] Documentation is posted on design.va.gov

**Comment by Andrew565** [comment]
NPM package: `@department-of-veteran-affairs/css-library`
Source Code: `component-library/packages/css-library/src/stylesheets/utilities.scss`
Distribution Code: `component-library/packages/css-library/dist/utilities.css`

There are also 'placeholder' files for fonts and elements, but these are left intentionally blank at the moment.

Examining the `utilities.scss` file gives the list of what kinds of utilities are being generated (border, color, flex-grid, etc) and could be used as a 'checklist' for what documentation to create.
