### ISSUE TITLE
Update the memorable date component

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#1791]
## Description
During a [recent midpoint review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58946), content (Megan Zehnder) asked the VFS team to change "two" and "four" to "2" and "4" to follow our content guidelines. Beth Potts confirmed this change in a [Slack thread](https://dsva.slack.com/archives/G01DXP10GCA/p1685018547969019).

## Tasks
- [x] Change "two" and "four" to "2" and "4" on the [memorable date component](https://design.va.gov/components/form/memorable-date) in both storybook and the design system
- [x] When we have it, update the image in storybook

## Acceptance Criteria
- [ ] The memorable date component in the design system has correct guidance and images with "2" and "4"
- [x] The memorable date component in storybook has correct code "2" and "4"

**Comment by powellkerry** [comment]
The design system will be updated when core is released.
