### ISSUE TITLE
Audit the components looking for numerals that are text instead of numbers

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#1792]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Description
Recent feedback in a midpoint review discovered that the memorable date component has numerals that are text instead of numbers. There is another ticket to fix that specific component, this ticket is to audit all components in the design system for numerals that are text instead of numbers and confirming which should display. And changes should be applied to Storybook as well.

## Details
_optional, delete section if not needed_

## Tasks
- [ ] Audit components in the design system and document any that have numerals that are text instead of numbers
- [ ] Confirm with content what should display
- [ ] Create tickets for components that need to change

## Acceptance Criteria
- [ ]All components on the design system have been auditing and there is a list of components that need to be changed.

**Comment by babsdenney** [comment]
@humancompanion-usds @LillyBoot The audit is complete and need to confirm with the content what should stay and what should be changed. We can review this at the Design weekly chat tomorrow. 

[Numerals in text audit in Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1687789869583/21af4dd94421157b4d1dcdd42fa7dbd70818cc9d?sender=ucf13c21d112482a4c5766770)
