### ISSUE TITLE
Icon (web component) - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1800]
## Description
Create design for icon and/or update Sketch artifacts for icon.

If this is a pattern or component that is already in existence, conduct a small-scale audit (3-5 examples) to make sure there aren't design issues that need to be addressed. Also, check the Design System Team backlog for outstanding design issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this design and link to this issue from the original issue. If not, indicate that in the original issue.

## Tasks
- [x] Conduct small audit if necessary (if component already exists and we are building a new version)
- [x] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [x] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by babsdenney** [comment]
Looking at the backlog I think we might be able to close the following tickets based on this work.

- [Create new Icon for VA Icons that do not have a USWDS Replacement (Icons Audit follow up 3/3) #1655](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1655)
- [Combine Existing USWDS Icons (Icons Audit follow up 2/3) #1654](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1654)
- [Create new Icon for VA Icons that do not have a USWDS Replacement (Icons Audit follow up 3/3) #1651 ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1651)
- [Edit Existing USWDS Icons (Icons Audit follow up 2/3) #1650](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1650)
- [Replace VA Icon with Combination of USWDS Icons (Icons Audit follow up 1/3) #1648](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1648)
- [Reverse phone icon #1595](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1595)

**Comment by babsdenney** [comment]
This ticket is ready to review at the design check-in. There are a few questions I have before finalizing this ticket. 

- What features should the sketch components have?
  - Adjustable size
  - Change colors
- What features should the web component have? Match UWDS features?
- The pill icon is strange, initially I only found the outline version on Material UI, once I discovered the filled-in option of the icon I went back to the [Material Icon page](https://fonts.google.com/icons) and now the pill icon is gone. 
- Verify naming the icons after what is in the VA

**Comment by caw310** [comment]
@babsdenney would you mind closing those tickets referencing this one? Thanks!

**Comment by babsdenney** [comment]
This is ready for review. I added the USWDS icons to MVP and v3 libraries.
- [MVP Iconography](https://www.sketch.com/s/998b1585-ba60-474f-ba5d-85729b247f3c/p/82DED6E8-D91E-4CB6-971F-58EA2B795AA9/canvas)
- [V3 Iconography](https://www.sketch.com/s/4771ada9-af5a-4946-b6c3-3dea9806a6f4/p/92FDF2C3-B0FD-4B77-B1DA-512D95C4714C/canvas)

**Comment by LillyBoot** [comment]
Looks good to me! 

One quick note, we only need USWDS v3 icons in the v3 libraries because we will be sticking with Font Awesome icons for the MVP

**Comment by babsdenney** [comment]
Thank you for the feedback! I removed the icon symbols from the MVP library.
