### ISSUE TITLE
Add analytics event to va-notification web component

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1803]
## Description

We want to add a `component-library-analytics` event to the new `va-notification` component. This work should also include updating the `analyticsEvents` object in [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/component-library-analytics-setup.js).

## Details

We should capture the link click from va-link so that we don't double log an analytics event. Similar to va-button-pair:

https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-button-pair/va-button-pair.tsx#L78-L103

And we will need to determine which analytics details we want to capture for va-notification. I think this is what makes sense but confirm with DST:

```
const detail = {
  componentName: 'va-notification',
  action: 'click',
  details: {
    type: this.symbol, // `symbol` prop which indicates the type of notification
    header: this.headline, // `headline` prop
    ...event.detail?.details // Merging the va-link GA event details.
}
```

Other references:
- [Adding GA4 details for Google Analytics](https://vfs.atlassian.net/wiki/spaces/DST/pages/2544173086/Adding+GA4+details+for+Google+Analytics)

## Tasks
- [ ] Determine which analytics details we want to capture for va-notification
- [ ] Add analytics to the web component
- [ ] Update the component-library-analytics-setup.js file in vets-website for GA & GA4
- [ ] Reach out to Michelle with the analytics team to makes sure she has this component on her radar and has done any setup required on her end.

## Acceptance Criteria
- [ ] The va-notification web component has an anlytics event.
- [ ] vets-website is updated to route the events for GA and GA4
- [ ] Michelle with analytics has been notified.
