### ISSUE TITLE
Deprecation Phase 3  Textinput REACT Component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1805]
## Description
We will deprecate Textinput React component.

We need to move the Textinput React component into [Phase 3](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components#General-deprecation-strategy). This means that the following steps will need to happen:

- Begin migrating any remaining instances of the React component ourselves. 
- The pace of this work will depend on the team’s availability and the priority of this work over other planned work and obligations.
- Once there are no more uses, remove the React component from the component-library repository

## Tasks
- [ ] Check if the component is still being used in vets-website
- [ ] If it is...
  - [ ] Reach out to teams to check if they have an update pending.
  - [ ] Migrate any remaining instances of the React component ourselves.
  - [ ] Once there are no more uses, remove the React component from the component-library repo:
    - [react-components](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/react-components) package
    - [design system dashboard cli](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/design-system-dashboard-cli) package
    - [storybook](https://github.com/department-of-veterans-affairs/) package
  - [ ] Remove any ESLint rules from [vets-website](https://github.com/department-of-veterans-affairs/vets-website) and the [eslint-plugin](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/eslint-plugin).
  - [ ] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
  - [ ] Remove the related web component(s) from the [web component migrations list](https://design.va.gov/about/developers/using-web-components#web-component-migrations)
- [ ] If it is not...
  - [ ] Remove the React component from the component-library repo:
    - [react-components](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/react-components) package
    - [design system dashboard cli](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/design-system-dashboard-cli) package
    -  [storybook](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/storybook) package.
  - [ ] Remove any ESLint rules from [vets-website](https://github.com/department-of-veterans-affairs/vets-website) and the [eslint-plugin](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/eslint-plugin).
  - [ ] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
  - [ ] Remove the related web component(s) from the [web component migrations list](https://design.va.gov/about/developers/using-web-components#web-component-migrations)

## Acceptance Criteria
- [ ] Deprecated component has been removed entirely.
