### ISSUE TITLE
Deprecation Phase 3  Checkbox Group REACT component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1806]
## Description
We will deprecate Checkbox Group React component.

With the completion of the [Phase 2 ticket]([Deprecation Phase 2 of React components #1637](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1637)), we will need to move the Checkbox Group React component into [Phase 3](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components#General-deprecation-strategy). This means that the following steps will need to happen:

- Begin migrating any remaining instances of the React component ourselves. 
- The pace of this work will depend on the team’s availability and the priority of this work over other planned work and obligations.
- Once there are no more uses, remove the React component from the component-library repository

## Tasks
- [x] Check if the component is still being used in vets-website
- [x] If it is...
    - [x] Reach out to teams to check if they have an update pending.
    - [x] Migrate any remaining instances of the React component ourselves. 
    - [x] Once there are no more uses, remove the React component from the component-library repository
    - [x] Remove the ESLint rule
    - [x] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
- [ ] If it is not...
    - [ ] Remove the React component from the component-library repository
    - [ ] Remove the ESLint rule

## Acceptance Criteria
- [ ] Deprecated component has been removed entirely.

**Comment by caw310** [comment]
Please update this google sheet to indicate the component has been deprecated. https://docs.google.com/spreadsheets/d/18PqifqLKODbf_FshTf2e8ftOra86SdGW8xhVNSMAXOQ/edit?usp=sharing

**Comment by it-harrison** [comment]
Waiting for my-benefits team to review [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24847). Once merged the following draft PRs will be converted to ready for review:
* [remove component from component library](https://github.com/department-of-veterans-affairs/component-library/pull/753)
* [eslint/analytics in vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/24886)

**Comment by it-harrison** [comment]
still waiting for review from benefits after pinging them again today

**Comment by it-harrison** [comment]
My-benefits team has replaced all references to the react component so we can proceed with the deprecation.

**Comment by caw310** [comment]
The work is done but is pending the publishing of a new component library release so automatically is carrying over for 1 day.
