### ISSUE TITLE
Create a V3-only Playground

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1809]
## Description

As a developer, I want a version of the DS Playground that is V3-only, so that I can test and see what V3-compatible components will look like when there is no longer any support for Formation (V1) styles.

## Tasks
- [ ] Create a v3-playground app
- [ ] Ensure that `useLocalStylesAndComponents` is enabled for this app in the registry (vets-website/config/webpack.config.js)
- [ ] Populate the app page with V3-compatible components (ensure the `uswds` flag is still present for now)

## Acceptance Criteria
- [ ] All available V3-compatible components render on the v3-playground page
- [ ] Components do not necessarily need to look correct or work correctly at this time.
