### ISSUE TITLE
Reorganize Sketch Libraries Part 1: Design System Libraries 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1822]
## Description 

We need to reorganize the following Sketch Libraries:

1. [DS: USWDS MVP Component Library](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/symbols)
2. [DS: MVP Foundations & Pattern Library](https://www.sketch.com/s/998b1585-ba60-474f-ba5d-85729b247f3c/symbols)
3. [DS: USWDS v3 Component Library](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7)

Continuation of this ticket to create New Sketch workspaces
[Ticket #59048](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/59048)

## Details

DS Libraries should use this structure for organization guidance: 
![Screen Shot 2023-06-20 at 1.08.57 PM.png](https://images.zenhubusercontent.com/63d7f10a208bb87a62f4e744/6634ac58-f757-4076-84ce-4e2c7aae9c6f)

## Tasks
- [x] Reorganize DS: USWDS MVP Component Library
- [x] Reorganize DS: MVP Foundations & Pattern Library
- [x] Reorganize DS: USWDS v3 Component Library

## Acceptance Criteria
- [ ] Review with other DS designer 
- [ ] Review with PO

**Comment by LillyBoot** [comment]
Reviewed during weekly design chat. Will create new ticket to add v1 components to MVP symbols library and example library

**Comment by LillyBoot** [comment]
Ticket for adding v1 components to MVP libraries [ #1854](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1854)

**Comment by babsdenney** [comment]
Looks great! Designs approved.
