### ISSUE TITLE
Reorganize Typography in Sketch Libraries 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1825]
## Description 

We need to reorganize the typography in each Symbol library and get rid of what we are not using. 

Continuation of this ticket to create New Sketch workspaces
[Ticket #59048](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/59048)

## Tasks
- [ ] Conduct audit to discover what font sizing we should be using 
- [ ] Reorganize typography in the [DS: MVP Foundations & Pattern Library](https://www.sketch.com/s/998b1585-ba60-474f-ba5d-85729b247f3c/symbols) 
- [ ] Reorganize the typography in the [DS: USWDS Foundations & Pattern Library](https://www.sketch.com/s/4771ada9-af5a-4946-b6c3-3dea9806a6f4)
- [ ] Link DS: MVP Foundations & Pattern Library colors to [DS: USWDS MVP Component Library](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/symbols)
- [ ] Link DS: USWDS Foundations & Pattern Library to [DS: USWDS v3 Component Library](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7) 

## Acceptance Criteria
- [ ] Review with other DS designer 
- [ ] Review with PO
