### ISSUE TITLE
Add width to guidance for textinput and number input - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1826]
## Description
Add width variations to guidance for text input and number input. Reference USWDS text input widths. https://designsystem.digital.gov/components/text-input/#component-variants-text-input

## Details
**Text input**
design.va.gov - https://design.va.gov/components/form/text-input
Storybook -  https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--default

**Number input** 
design.va.gov - https://design.va.gov/components/form/number-input
Storybook -  https://design.va.gov/storybook/?path=/docs/components-va-number-input--default

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov
