### ISSUE TITLE
Discovery: Adding 'custom header' and 'custom footer' flags to content-build

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1828]
## Description

As a developer implementing a design in the vets-website space, I want to be able to use a custom/minimal header and/or footer on some pages. To do that I need to utilize the `useLocalStylesAndComponents` flag in tandem with a proposed `customHeader` and/or `customFooter` property in the App Registry, which would then need to trigger something in content-build to utilize a different header and/or footer in the app's build process. This ticket's goal is to determine how easy and/or feasible it might be to provide custom headers and footers in this way, or if there is another method that would be preferable.

## Details

[This is where useLocalStylesAndComponents is processed in content-build](https://github.com/department-of-veterans-affairs/content-build/blob/17f6a09372caec1169bf0230f8d1fddc9b32cab1/src/site/includes/header.html#L46)
[Potential "noHeader" flag we could use, compare with "noNavOrLogin" flag](https://github.com/department-of-veterans-affairs/content-build/blob/17f6a09372caec1169bf0230f8d1fddc9b32cab1/src/site/includes/header.html#L178)

## Tasks
- [ ] What would it take for a custom header/footer to be passed into the content-build space so that it could be used instead of the default header/footer?
- [ ] Is there a way to utilize a custom header/footer that doesn't require adding new flags to content-build?
- [ ] Are there any examples of custom headers/footers already in use? (Check with the check-in app team and their minimal header)

## Acceptance Criteria
- [ ] A strategy is determined for how to go about utilizing custom headers and footers

**Comment by Andrew565** [comment]
# Discovery Findings for Custom Header and Footer

## Problem Summary

The current Header and Footer on vets-website are fragile, dependent on Formation (USWDS V1), and do not support Web Components.

## Finding 1: Two different templates

For 'deployed' apps, there is the [page-react.html](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page-react.html) file in the `content-build` repo. This file includes [header.html](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/header.html) and [footer.html](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/footer.html). The header.html includes logic for whether or not to render the header widgets on mobile and desktop. The footer.html includes logic on whether to render a full footer or a minimal footer, but no way of 'turning off' the footer completely. Neither currently provides a way to include a 'custom' header or footer. All of these files utilize the **Liquid** template language for control flow.

For 'local' apps - that is, when testing `vets-website` locally using `yarn watch` - there is the [dev-template.ejs](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/landing-pages/dev-template.ejs) file, which includes a 'translation' of what is rendered by content-build, and which also includes most of the same logic for showing/not-showing the header and rendering the full/minimal footer. Use the word 'translation' instead of 'copy' because the dev-template.ejs file uses "Embedded JavaScript" (**EJS**) template instead of Liquid.

## Finding 2: Registry files control flow

Control flow inside both apps is done via a `registry.json` file (for content-build) and `registry.scaffold.json` file (for vets-website). These files are identical in syntax, with each entry allowing for an optional `template` object where arbitrary properties can be defined, including `customHeader` and `customFooter` properties (which is what I added to support custom headers and footers during my discovery).

The registry entry for `ds-v3-playground` looked like this after my experimentation:

```
{
    "appName": "DS V3 Playground",
    "entryName": "ds-v3-playground",
    "rootUrl": "/ds-v3-playground",
    "template": {
      "vagovprod": false,
      "layout": "page-react.html",
      "noHeader": true,
      "customHeader": true,
      "customFooter": true
    },
    "useLocalStylesAndComponents": true
  }
```

The first three properties are standard, followed by the `template` property. This includes the following:

- `vagovprod`: When set to `false` it prevents this app from being deployed to production.
- `layout`: Sets which page template to use. "page-react.html" might be the default, but I felt it prudent to spell it out here.
- `noHeader`: Turns off the default header, this property was defined by Brooks Johnson at an earlier date but it doesn't appear to be in use anywhere else.
- `customHeader`: I added this, it specifies that a custom header should be used.
- `customFooter`: I added this, it specifies that a custom footer should be used.

`useLocalStylesAndComponents`, when set to `true`, prevents Formation and the 'standard' web-components loader from being called and loaded. This necessitates manually calling the web-components loader from within the app. In `ds-v3-playground`, this is done in the [defineWebComponents.js](https://github.com/department-of-veterans-affairs/vets-website/blob/ds-playground/src/applications/ds-v3-playground/utils/defineWebComponents.js) file (which is itself called from within the [app-entry.js](https://github.com/department-of-veterans-affairs/vets-website/blob/ds-playground/src/applications/ds-v3-playground/app-entry.jsx) file).

## Finding 3: Developing in content-build is slow

Developing locally in content-build is really really slow. Pulling down a locally-cached copy of the Drupal content took a one-time investment of almost 1.5 hours. Building using `yarn build` takes about 18 minutes. Running with `yarn watch` was slightly faster at 18 minutes for the initial load, but then only 10 minutes for each reload.

Vets-website, when running `yarn watch --env entry=[your app's entryName]`, can process reloads in about 30 seconds or less.

## Option 1: Develop everything twice

Develop locally, copy finished headers and footers to content-build, code has to be updated in two places every time.

Pros:

- Benefit of faster initial development time
- Would yield fully-rendered header and footer, rather than a dynamically-loaded one (FOUC potential)

Cons:

- Requires manually keeping the custom header and footer in sync between the two repos

## Option 2: Develop once locally, many times on content-build

Use a minimal placeholder in the local dev-template, 'real' custom headers and footers would live in content-build.

Pros:

- Only have to update content once, in the content-build repo

Cons:

- Development in content-build is painfully slow

## Option 3: Develop once on content-build, many times locally

Use the same minimal placeholder in content-build and vets-website, and dynamically 'inject' the header from the vets-website repo.

Pros:

- Fastest development turn-around time
- Allows for multiple custom headers, as many as one per app if desired

Cons:

- Would require a minimal header placeholder to prevent a FOUC - Flash of Unstyled Content - while the app loads each page
- Because each app could load a different header, would lose control over what header was loaded for each app

**Comment by micahchiang** [comment]
Thanks for the write up @Andrew565! When you have a moment, would you mind creating a doc in our [confluence plans, designs, ADRs, RFCs, Discoveries](https://vfs.atlassian.net/wiki/spaces/DST/pages/2181726211/Plans+Design+Docs+RFPs+ADRs+Discovery) page so your findings are codified there? Just want to make sure we have them in a more IA - minded space so they don't get lost as a comment. Thank you! :pray:

**Comment by Andrew565** [comment]
After discussing with Matt, Option 1 is the solution we want to implement, with the addendum of making "customHeader" and "customFooter" properties `string` values instead of `boolean`, so that we can specify multiple different custom headers and footers. These will be developed initially within the dev_template.ejs file, and then move over to content-build once ready to 'go live'.

**Comment by Andrew565** [comment]
Draft PR with vets-website proposed changes: https://github.com/department-of-veterans-affairs/vets-website/pull/25275

**Comment by Andrew565** [comment]
Draft PR with content-build proposed changes: https://github.com/department-of-veterans-affairs/content-build/pull/1671
