### ISSUE TITLE
Find  all instances of the old wizard pattern 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1836]
## Description
Find instances of the old wizard pattern so that we can identify which teams are using the old wizard pattern which needs to be deprecated. 

## Details
This is in reference to this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17766#issuecomment-1582649903

## Tasks
- [ ] Find all instances of the old wizard pattern in VFS applications
- [ ] Identify which teams are using the old wizard pattern
- [ ] Work with me (Carol) to file bugs to have the teams remove the wizard pattern

## Acceptance Criteria
- [ ] Create a list of instances of the old wizard pattern
- [ ] Write tickets for the teams to deprecate the wizard pattern

**Comment by humancompanion-usds** [comment]
We didn't do this and now it is 2 years in the rear-view mirror. Closing as will not fix.
