### ISSUE TITLE
Discovery: Style Dictionary 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1837]
## Description
Do discovery work on a style dictionary to define design tokens that allows you to export them to be used in other tools and to use code right out of component library. Should be able to use the design tokens in Sketch, UXPin and Figma.

## Tasks
- [ ] Research style dictionary to define design tokens that allows you to export them to be used in other tools. use code right out of component library. 
- [ ] Share findings with DST (designers, developers and PO) 
- [ ] Make a recommendation and write any necessary follow up tickets

## Acceptance Criteria
- [ ] Make a recommendation on next steps
- [ ] Write any necessary follow up tickets

**Comment by humancompanion-usds** [comment]
Being able to support react-native has emerged as a requirement for the Mobile app team. I was able to generate a react-native variables file for them (I have the transform on a branch but haven't pushed it up yet). Their feedback was:

> Generally speaking, that format is fine, but we can’t use the unit-base spacing like `export const unitsNeg1p5 = "-1.2rem";` The React Native version of that would be -19.2 (if my math is correct and they’re using a base of 16), but totally fine, I understand why it’s generated like that (for the Web). The biggest thing for us in there is the color hexcodes anyway.

> They can also just output a JSON format for us to consume, we’ll ultimately remap the variables anyway. With the JSON format we can also try and worm it into Figma to sharing at that level.

I did provide a pointer to our JSON token files. Tim on the mobile team is the person to talk to (I'll get his details and add it here).

**Comment by jamigibbs** [comment]
Hi @timwright12! I've started to do some discovery work for generating different token formats. Style Dictionary does provide [some pre-made transformers](https://amzn.github.io/style-dictionary/#/transform_groups?id=react-native) to help us generate one for React Native but reading Matt's comment above, it sounds like it might need some additional work?


Here is an example of what that [pre-made transformer outputs for our tokens to react-native](https://github.com/department-of-veterans-affairs/component-library/pull/766/files#diff-bbf3b3e7c7bf8acf8c482f45fa2e64d5c7b2d2e99f3b954158b11f5532ee9273).

```js
export const colorBase = "#212121";
export const colorWhite = "#ffffff";
export const colorBlack = "#000000";
export const colorOrange = "#eb7f29";
export const colorLinkDefault = "#004795";
export const colorWarningMessage = "#fac922";
export const colorGibillAccent = "#fff1d2";
export const colorPrimary = "#0071bb";
....etc
```

And this is an example they've provided on how to use that in a react-native project: https://github.com/amzn/style-dictionary/blob/main/examples/advanced/create-react-native-app/src/App.js#L4


```js
import * as variables from "./style-dictionary-dist/variables";

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Testing! Testing!</Text>
      <Text style={styles.p}>All done!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: variables.colorBrand01,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: PixelRatio.getFontScale() * variables.sizeFontMd.scale,
    color: variables.colorBrand02,
  },
  p: {
    fontSize: PixelRatio.getFontScale() * variables.sizeFontSm.number,
    color: variables.colorBrand02,
  },
});
```

If the tokens don't look exactly right for your needs, we should be able to do [custom filtering](https://github.com/amzn/style-dictionary/tree/main/examples/advanced/custom-filters) or even create our own [custom transforms](https://amzn.github.io/style-dictionary/#/transforms?id=defining-custom-transforms) but I wanted to check in with you first to see if that was even necessary based on the output we're receiving above.

**Comment by jamigibbs** [comment]
Thanks @timwright12! I think it would be pretty straightforward effort for us to make those modifications. [Here's a quick POC with a couple of custom transforms](https://github.com/department-of-veterans-affairs/component-library/pull/766/commits/e1824dbe1b5557ff9e0f223a33011544e40e54d5) that will convert `rem` and remove `px` from matching values.

And we can output that as either `json` or `js` formats (or both!):

- [react-native/tokens.js](https://github.com/department-of-veterans-affairs/component-library/blob/e1824dbe1b5557ff9e0f223a33011544e40e54d5/packages/css-library/dist/react-native/tokens.js)
- [react-native/tokens.json](https://github.com/department-of-veterans-affairs/component-library/blob/e1824dbe1b5557ff9e0f223a33011544e40e54d5/packages/css-library/dist/react-native/tokens.json)

I think that's gets you everything you need?

**Comment by timwright12** [comment]
JSON + React Native should do it. Transforms look good too! Thank you!

**Comment by jamigibbs** [comment]
## Discovery Notes

### CSS Library Quick Overview

The CSS Library has two types of resources available:

1. Design tokens (css/scss/json/js)
2. Utility classes (stylesheets)

The design tokens are what this discovery has focused on.

### Can we generate different token formats for React Native, UXPin, Sketch, etc?

With style-dictionary, we should be able to generate any format that we need. They provide a number of [pre-defined formats](https://amzn.github.io/style-dictionary/#/formats?id=pre-defined-formats), [transform groups](https://amzn.github.io/style-dictionary/#/transform_groups), and [transforms](https://amzn.github.io/style-dictionary/#/transforms). And if those pre-defined formats don't get us exactly what we want, we can create our own [custom formats](https://amzn.github.io/style-dictionary/#/formats?id=custom-formats) or [custom transforms](https://amzn.github.io/style-dictionary/#/transforms?id=defining-custom-transforms).

**React Native**

The mobile team are a good example of needing something more custom than what style-dictionary can provide. They need `rem` values converted to pixel and no units appended to the value (ie. `fontSize: 1rem` would be `fontSize: 16`). They also are requesting the tokens in `js` and `json` formats (see convo above).

A working example of this has been added to the discovery PR which includes two custom transforms: https://github.com/department-of-veterans-affairs/component-library/pull/766

**Figma**

An NPM package exists that we could use for Figma: [style-dictionary-to-figma](https://www.npmjs.com/package/@divriots/style-dictionary-to-figma). I connected this package and [generated a tokens file](https://github.com/department-of-veterans-affairs/component-library/blob/37b576f1ba88d9839daac99fbd1ce507be8232dd/packages/css-library/dist/figma/tokens.json) with it as part of this discovery work but this will need to be verified that it's working as expected as part of the development ticket.

The [Figma documentation](https://www.figma.com/community/plugin/1128196356923537195/Sync-Design-Tokens) says that you can import/use that file just by linking to its [public source](https://raw.githubusercontent.com/department-of-veterans-affairs/component-library/37b576f1ba88d9839daac99fbd1ce507be8232dd/packages/css-library/dist/figma/tokens.json).

**UXPin**

Looking at some UXPin tutorials, I believe we can import a standard tokens CSS file directly into the service and it will automatically generate those values.

![Screenshot 2023-07-26 at 12 33 59 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/ad34274f-5ef6-445a-ade7-a99c4fcf2a6e)

I don't have access to a UXPin dashboard to verify this though (or found any specific UXPin documentation that confirms) but with the flexibility of style-dictionary, I believe we could make adjustments as needed.

**Sketch**

Importing tokens into Sketch might be more complicated. There are some [Sketch plugins](https://www.sketch.com/extensions/plugins/) we could leverage ([colors specifically](https://github.com/ziyafenn/sketch-json-color-palette-importer)) but we might need to create our own [custom Sketch plugin](https://developer.sketch.com/plugins/create-a-plugin) in order to import all tokens (color, fonts, and spacing).

The [CMD Design system did build their own Sketch plugin](https://github.com/CMSgov/design-system/blob/main/packages/design-system-tokens/sketch/cmsds-token-importer/README.md) but it seems like it's also handling color tokens.

```js
  const colorSwatches = makeColorSwatches(tokenData.color);
  colorSwatches.forEach((swatch) => {
    doc.swatches.push(swatch);
  });
```

Do we need more than color tokens in sketch? If not, then I believe we can just use one of the pre-made sketch plugins.

## How do we organize all of this?

With so many different token file types (including some with the same file extension), I propose we organize based on the interface it's meant to be used with:

```
packages
└── css-library
    ├── config.js             -- style-dictionary config file
    ├── package.json          -- commands for generating CSS Library (tokens and stylesheets)
    ├── dist                  -- generated token files and stylesheets
    │   ├── css
    │   │   └── tokens.css    -- general use tokens in css format
    │   ├── figma
    │   │   └── tokens.json   -- figma tokens processed with a transform
    │   ├── json
    │   │   └── tokens.json   -- general use tokens in json format
    │   ├── react-native
    │   │   ├── tokens.json   -- react-native tokens processed with custom transforms
    │   │   └── tokens.js     -- figma tokens processed with custom transforms
    │   └── scss
    │       └── tokens.scss   -- general use tokens in scss format
    ├── src                   -- classes for generating utility stylesheets
    └── tokens                -- the design tokens to be generated
        ├── colors.json
        ├── fonts.json
        └── spacing.json
```

**Example usage in the component-library**

We can start using the generated tokens file now in the component library if we'd like. We will just need publish the latest updates [to NPM](https://www.npmjs.com/package/@department-of-veterans-affairs/css-library) and add the package.

The existing `_variables.css` file should be removed and the css tokens file imported.

`@import '~@department-of-veterans-affairs/css-library/dist/css/tokens.css';`

![Screenshot 2023-07-26 at 2 33 11 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/8201c3ea-0c73-4a33-920c-1adeaafd7e32)

## When can everyone start using the CSS Library token files?

We will need to figure out how the releases are going to work for the component library repo now that we have both the `component-library` and `css-library`. We are not going to want updates to the CSS Library included in the release notes for the component-library. They are two separate packages and releases.

Some discovery work was already started to explore publishing multiple packages in a monorepo which I think we need to revisit. We left off wanting to do some additional discovery work with [Lerna](https://lerna.js.org/): https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1068

## Follow-up tickets

1. Discovery: Re-evaluate component-library package releases (test lerna) - Figure out how to enable separate release and release notes for this package - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1068
2. Prepare css-library package run scripts. Generate css, sass, and general json token files. Reference the [discovery PR](https://github.com/department-of-veterans-affairs/component-library/pull/766/files).
3. Generate the react-native token files (js & json). Reference the [discovery PR](https://github.com/department-of-veterans-affairs/component-library/pull/766/files).
4. Generate the Figma token file. Reference the [discovery PR](https://github.com/department-of-veterans-affairs/component-library/pull/766/files).
5. Generate a UXPin token file (check with UXPin team for format by probably something standard)
6. Generate a Sketch token file (might require a custom plugin)

**Other tickets?**
- Create a manual release of the CSS Library (until we figure out monorepo package publishing) and replace the static `_variables.css/scss` files in the component-library.
- Do we need to explore how or when we are introducing the utility classes? We might want a discovery ticket for this.
- We have placeholders for [fonts and elements stylesheets](https://github.com/department-of-veterans-affairs/component-library/tree/37b576f1ba88d9839daac99fbd1ce507be8232dd/packages/css-library/src/stylesheets). Do these need tickets?

### Other Useful Links

- [Plan - Design System CSS Utility Class Library Rebuild](https://vfs.atlassian.net/wiki/spaces/DST/pages/2181857291/Plan+-+Design+System+CSS+Utility+Class+Library+Rebuild)
- [Discovery for design token library](https://github.com/department-of-veterans-affairs/component-library/pull/476)
