### ISSUE TITLE
Investigate vets-website use of i18n-setup file

### ISSUE THREAD

**Issue by ataker** [department-of-veterans-affairs/vets-design-system-documentation#1839]
## Description
Currently the `i18n-setup.js` file is being imported to the vets-website though react components still in use (`Select` and `TextInput`). With the planned removal of React components, we need to decide how this file should be replaced in the vets-website. 

## Tasks
- [ ] Determine `i18n-setup.js` purpose
- [ ] How should we load `i18n-setup.js` in vets-website?
- [ ] Should the design system team still own this?

**Comment by caw310** [comment]
Due to unanticipated PTO from a few engineers, this will need to carry over.
