### ISSUE TITLE
Discovery: How to Implement V3 Icon Web Component

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1850]
## Description

As a developer, I want to know which way of implementing the Icon Web Component will be the least complex and most maintainable.

## Details

The USWDS V3 Icon web component is implemented using a sprite sheet. Generating sprite sheets usually requires a build step of some kind, and it is currently unknown whether or not USWDS has a tool available for generating these sprite sheets, and whether it can use 'custom' icons or only the ones that USWDS has chosen.

Because we want to include several icons that are different or in addition to the icons provided by USWDS, we must examine the overhead of implementing a sprite sheet generation system ourselves vs. utilizing individual SVGs or some other graphic type. This would have to start with ascertaining where we are currently storing our icon assets, and if they are already in a form that would be easily transferable into the Design System.

## Tasks
- [ ] Find out how many 'custom' icons there are (compared to USWDS defaults)
- [ ] Determine what format custom icons are currently stored in and how easy it would be to include them in DS
- [ ] Determine pros and cons of using a sprite sheet
- [ ] See if it is possible to use USWDS' tools to compose our own sprite sheet
- [ ] Determine pros and cons of using individual SVGs or another graphic type
- [ ] Is there another way or a hybrid approach that could work well?

## Acceptance Criteria
- [ ] A solution is agreed upon

**Comment by Andrew565** [comment]
1. The uswds-compile tool works well for generating a new sprite sheet with all of the ‘base’ USWDS icons, plus our 14 ‘custom’ icons. The resulting sprite sheet file is about 75kb in size. This should take less than a second to download for nearly all users.
2. The uswds-compile tool itself relies on npm, npx, and gulp in such a way that I was unable to get it to work within the yarn workspaces setup of our component-library repo, meaning that if we want to keep a copy of the tool around for generating new sprite sheets in the future it will have to live in its own repo. The biggest advantage to doing this would be not having to re-collect the ‘custom’ icons any time a change was desired, the biggest disadvantage to having this in a separate repo is the risk that we’d forget about it by the time we needed it again.
3. With the sprite sheet weighing in at 75kb in size, we would want it to be loaded by the browser as few times as necessary. In order to effect this, we would need to add it to the public assets directories of our storybook, design.va.gov site, and vets-website. We would also need to upload it to the public assets directory of any other site that would use a design system icon web component.
4. Alternatively, we could abandon the use of the large sprite sheet and instead create 256 individual icon web components. Each component would include its individual SVG code within it, making each download 1kb or less for almost all of the icons (median file size about 275kb).
  a. If we went this route of individual icons, it would create more files to maintain and bundle, and increase our bundle size overall, but it would allow us to maintain our current strategy of encapsulating everything a component needs within the component itself (no external dependencies like uploading to the public assets directories).
  b. This strategy would also negate the need to keep and maintain a separate uswds-compile repo, as all of the svg code would live inside the components, which live in the component-library repo.

**Comment by Andrew565** [comment]
Jami found this: https://stenciljs.com/docs/assets which should allow us to include the sprite sheet in the component in a way that is both encapsulated and cacheable, so that should solve most of the problems. The recommendation now is to use a sprite sheet, add it to web-components/src/assets folder, and reference it using something like `const imageSrc = getAssetPath('./assets/sprite.svg#name_of_icon')`. Actual asset path may vary and will need to be worked out when developing the actual component.

**Comment by Andrew565** [comment]
Here’s how to generate a new sprite sheet with all of our ‘custom’ icons added to it:

1. Clone from https://github.com/department-of-veterans-affairs/dst-uswds-compile
2. Run `npm run init` - This sets up all of the ‘base’ files
3. Run `npm run compileIcons`
4. Find and copy the sprite.svg file (./sprite.svg)
5. Paste it into the web-components/src/assets directory
