### ISSUE TITLE
va-checkbox: Add message-aria-describedby prop for supporting custom screenreader text

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1852]
## Description

[Colab cycle feedback for Supplemental Claims Form 20-0995](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56080) identified an issue with the use of `va-checkbox`. They need to be able to pass custom text in addition to the existing label to be read by screen readers. Currently, the va-checkbox component does not support this.

We [recently added this functionality to `va-text-input`](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24502) so we will just want to replicate that solution for va-checkbox as well.

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/56080

## Tasks
- [ ] Add the prop `message-aria-describedby` to va-checkbox. Note: The prop **must** be pre-pended with "message" otherwise it will not pass Axe tests.
- [ ] Update `aria-describedby` in the component's input element to handle both the error message ID and the message prop ID. Reference the [solution from va-text-input](https://github.com/department-of-veterans-affairs/component-library/pull/615/files#diff-9c0c303b16e6ba30480c740e75cc1fc4e41d26368760450030b65cc962507e9e).
- [ ] Test with a screenreader

## Acceptance Criteria
- [ ] The va-checkbox component allows for custom text to be read by a screenreader

**Comment by rhasselle-oddball** [comment]
note: message-aria-describedby only works on v1 web components for va-text-input currently (testing using React binding). Can we get message-aria-describedby for v3 web components as well?  would that be a separate issue or can that be handled as part of this?

**Comment by rhasselle-oddball** [comment]
Created separate ticket for issue mentioned in previous message: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1893
