### ISSUE TITLE
Reorganize Sketch Libraries Part 2: Example Libraries

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1853]
# Description 

We need to reorganize the following Sketch Libraries:

4. [Example Library: USWDS MVP Components](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c)
5. [Example Library: MVP Foundations & Patterns](https://www.sketch.com/s/a45277e9-2516-4041-815f-bdfa16da4953)
6. [Example Library: USWDS v3 Components](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3)

Continuation of this ticket to reorganize the design system libraries 
[Ticket #1822](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1822)

## Details

Example Libraries should use this structure for guidance: 
![Modal Desktop Examples](https://images.zenhubusercontent.com/63d7f10a208bb87a62f4e744/3ad9e237-3d96-4d7e-a9f3-706e543e772b)

## Tasks
- [x] Replace all components with corresponding DS libraries 
- [x] Reorganize Example Library: USWDS MVP Components
- [x] Reorganize Example Library: MVP Foundations & Patterns
- [x] Reorganize Example Library: USWDS v3 Components

## Acceptance Criteria
- [x] Review with other DS designer 
- [x] Review with PO
