### ISSUE TITLE
Add v1 components to MVP Sketch libraries 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1854]
## Description
We need to move v1 components from the Pattern Library to the MVP symbols library that are not being adopted from the USWDS. We want have all the component symbols in one library when the MVP is released. 

## Tasks
- [x] Determine which components from v1 will need to move to the MVP libraries
- [x] Move v1 components symbols from [VA-gov-Pattern-Library](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols) to [DS: USWDS MVP Component Library](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/symbols)
- [x] Add v1 components to [Example Library: USWDS MVP Component Library](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c)

## Acceptance Criteria
- [ ] Review with other DS designer
- [ ] Review with PO

**Comment by LillyBoot** [comment]
@humancompanion-usds @babsdenney this is ready for review

**Comment by humancompanion-usds** [comment]
I just glanced at it but, looking good! Thank you! Psyched to see this.

**Comment by babsdenney** [comment]
This looks great! Thank you @LillyBoot
