### ISSUE TITLE
Conversion to USWDS v3 Borderless table component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1860]
## Description
Adapt the va-table component to match the [USWDS Borderless Table component](https://designsystem.digital.gov/components/table/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See these examples for guidance. 
* va-radio: https://github.com/department-of-veterans-affairs/component-library/pull/579
* va-select: https://github.com/department-of-veterans-affairs/component-library/pull/610
* va-textarea: https://github.com/department-of-veterans-affairs/component-library/pull/654
* va-button: https://github.com/department-of-veterans-affairs/component-library/pull/645

[USWDS Table component](https://designsystem.digital.gov/components/table/)
[VA DS Table  component](https://design.va.gov/components/table)

Convert the Borderless Table

## Tasks
- [ ] Create a version of this component that imports and uses the USWDS CSS
- [ ]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ]  Check with a designer (Dan or Lucas) to make sure the component and the design match
- [ ]  Add a USWDS story to Storybook
- [ ]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Write a ticket to add component to DS playground

## Acceptance Criteria
- [ ]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library
- [ ]  Ticket written to add component to DS playground

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1860?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by danbrady** [comment]
Adding the [Figma design](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=6089%3A652&mode=design&t=JeYi030O5Yqh5msK-1) here.

**Comment by it-harrison** [comment]
@danbrady @humancompanion-usds do we want to support putting things other than text in the table cells? There are a few instances of links and buttons in `vets-website` right now but want to double-check we want to continue this in v3 since doing so adds complexity to the component.

**Comment by humancompanion-usds** [comment]
@it-harrison - Stick to what the v1 component supports today.

**Comment by it-harrison** [comment]
this will carryover to account for additional testing of ability to support links

**Comment by it-harrison** [comment]
PR is [here](https://github.com/department-of-veterans-affairs/component-library/pull/1128/)
