### ISSUE TITLE
Conversion to USWDS v3 - Search - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1862]
## Description
Adapt the va-search component to match the [USWDS Search component](https://designsystem.digital.gov/components/search/) and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See these examples for guidance. 
* va-radio: https://github.com/department-of-veterans-affairs/component-library/pull/579
* va-select: https://github.com/department-of-veterans-affairs/component-library/pull/610
* va-textarea: https://github.com/department-of-veterans-affairs/component-library/pull/654
* va-button: https://github.com/department-of-veterans-affairs/component-library/pull/645

[USWDS Search component](https://designsystem.digital.gov/components/search/)
[VA DS Search input component](https://design.va.gov/components/search-input)

## Tasks
- [ ] Create a version of this component that imports and uses the USWDS CSS
- [ ]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ]  Check with Lily and Barb to make sure the component and the design match
- [ ]  Add a USWDS story to Storybook
- [ ]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Write a ticket to add component to DS playground

## Acceptance Criteria
- [ ]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library
- [ ]  Ticket written to add component to DS playground

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1862?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
