### ISSUE TITLE
[va-notification] - Add guidance and Sketch library examples for new notification component

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1864]
## Description
va-notification is live in Storybook and needs to be added to Sketch and to Guidance.

## Details
Sketch: https://sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov
- [ ] Component is available in Sketch

**Comment by humancompanion-usds** [comment]
I lost track of the issue we already have for this: #1181
