### ISSUE TITLE
va-table: Clarify the right alignment of numerical data

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1871]
## Description
During the [PR review of the React Table component migration](https://github.com/department-of-veterans-affairs/vets-website/pull/24622), it was noted that a column that was previously left aligned is now right aligned by the va-table web component.

| React | Web Component |
| ------ | ----- |
|  ![Screenshot 2023-06-06 at 12 08 58 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/872479/d564a672-dae7-430f-8876-39363ec773eb) |   ![Screenshot 2023-06-06 at 12 03 48 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/872479/039808dc-6631-4d8b-8012-9e018f1b6e7f) |

Our utility function that determines if a column should be right aligned is:

```js
export function isNumeric(value: string): boolean {
  return !Number.isNaN(parseFloat(value));
}
```

As [Jerek pointed out](https://github.com/department-of-veterans-affairs/vets-website/pull/24622#issuecomment-1604611357), it's being identified as numeric because `parseFloat('534-K90HEWN')` evaluates to 534.

The [design system documentation for table](https://design.va.gov/components/table#how-to-use-tables) just says that "Numerical data is right-aligned" but we weren't exactly sure what is meant by "numerical" and if there's situations (like with the table above) where it wouldn't be right aligned.

Another possible issue is that the component is only checking the first instance of column data and it assumes the other column values are the same type. For example, if a columns data set is `123, 45b3, hello world`, these would all be right aligned because the first one evaluates to a number.

**Some questions to answer**

- Does right alignment include alpha numeric values? 
- Does it matter if the first column cell is a number but others are strings?
- Should we add examples to the documentation site for what is and isn't considered numerical?

## Tasks
- [ ] Confirm the design systems preferred styling for columns that contain numbers
- [ ] Update documentation to clarify the points above if needed.
- [ ] Update the component if any changes in the logic need to be made.

## Acceptance Criteria
- [ ] There is clarity around the logic for right aligning numerical data.
- [ ] Documentation has been updated if needed.
- [ ] Component has been updated if needed.

**Comment by humancompanion-usds** [comment]
I don't think we should be determining this automatically. We should just provide the ability to set the alignment to left or right (we don't want centered).

**Comment by jamigibbs** [comment]
Related issue created to add right alignment to the USWDS variation: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2846

**Comment by caw310** [comment]
Closing as this work will be done in #2846
