### ISSUE TITLE
Establish a QA process for components

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1878]
## Description
We need to establish a QA process for our components so that we don't miss important verification steps and so we can ensure a certain level of quality for the components in the system. 

## Details
Recently we've missed some bugs in components that has caused some churn. But more importantly, we don't have a documented QA process for components nor a checklist that code reviewers and code authors can refer to. We cannot depend on the CollabCycle or folks outside the team to catch issues nor should we expect others to help us maintain a high quality bar. 

Ensuring quality starts with the design of the component and continues on through to the implementation. 

Here are the chapters I would expect the documentation to address ([cribbed from Nathan's article on this](https://eightshapes.com/articles/component-qa-in-design-systems/)):

1. Visual quality: color, typography, icons, space, borders, etc.
2. Tokens: Are we using tokens whenever possible? That should be happening in Sketch/Figma/UXPin AND in the code
3. States: Default, hover, active, focus, inert, et. al.
4. Variations: Default + whatever else we need to show
5. Responsiveness: Needs to flex and not break at each defined breakpoint in the system and all points between.
6. Content Resilience: Check for long labels, word wrapping, etc.
7. Composability: Does it fit when placed next to or layered with other components to form a larger composition?
8. Functionality: Do the JS props control the component as expected?
9. Accessibility: This has to be broken up into sub-sections. We largely have this documented already in the [staging review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&projects=&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D) which also references the [prep for staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review):
  * [Color and color contrast](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#use-of-color)
  * [Automated testing with Axe](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#axe)
  * [Content zoom and reflow](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#content-zoom)
  * [Keyboard navigation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#keyboard-nav)
10. Browsers & Device Compatibility: Tested in at least one of Safari, Chrome, Firefox, or Edge. Also tested in iOS & Android. Tested in one of VoiceOver on Mac, JAWS, NVDA or Narrator on Windows.

## Tasks
- [x] Co-design QA process (collect what we do today then discuss as a team what is missing)
- [x] Document the QA process by chapter (chapters are the sections mentioned above)
- [x] Determine who is doing what and when
- [x] Determine what we can automate and file issues to do so
- [ ] Visualize the workflow and process
- [ ] Document on design.va.gov (overview) and in Platform documentation (detailed)

## Acceptance Criteria
- [ ] We have a repeatable process and shared understanding of roles and responsibilities related to component quality
- [ ] We have documented what we do in terms of component testing and when

**Comment by Andrew565** [comment]
Somewhat related, @jamigibbs created this PR Reviewing checklist for component-library PRs:

DST PR Reviewing Checklist
- [ ] Click the Chromatic link
   - Confirm it works. If it doesn't the branch name is too long or has strange characters. Tell them to rename the branch (make a new PR) so that it works.
- [ ] Is the PR label correct for release notes? (patch, minor, major, ignore-for-release)
- [ ] Is the PR title descriptive enough for release notes?
- [ ] Visually/manually QA in Storybook via the Chromatic link.
- [ ] Review the code. Ask questions. Give kudos. Profit.

**Comment by caw310** [comment]
Stretch item for sprint 35

**Comment by micahchiang** [comment]
Closing this issue. I've created a couple of follow up tickets seen in the event history above that take care of a couple of things needed to implement our new QA process.
