### ISSUE TITLE
Discovery: Allowing components to be extended/inherited

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1879]
## Description
We have started some discussion about how the component library could be used by other design system teams so that they can extend web component functionality and styles for their own use (USWDS and the VA Clinician Design System specifically).

We are using [Stencil](https://stenciljs.com/docs/introduction) to build our web components which uses classes that theoretically [should be able to be extended using inheritance](https://github.com/ionic-team/stencil/issues/172) but this is something that the Stencil library has intentionally decided not to support. It was [recommended instead to use composition](https://github.com/ionic-team/stencil/issues/1060). 

Ideally, the goal here is to find a way to "inherit/import" (i.e. not copy and paste) a component and then add/remove a property even with that limitation.

There are a couple of different approaches we want to explore related to composition:

1. Nesting existing components in a parent/child way. An example of this is the [va-notification component](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-notification/va-notification.tsx#L113-L143) which also uses va-card.
2. Programmatically [like in this example](https://github.com/ionic-team/stencil/issues/1060#issuecomment-1430328192) where a base class is composed with a component that is essentially just building off of the original.

Some questions to answer:
- [ ] If another DS team wanted to create a new component based off of a VA component (va-button for example), what would that look like for both of those approaches mentioned above (nesting and composition)? Build an MVP for both if possible.
- [ ] Are there any limitations with either of those approaches?
- [ ] Are there any other technical approaches to try other than those listed above?

## Tasks
- [ ] Read/explore the links above to the Stencil issue discussions about inheritance and composition.
- [ ] Build MVP examples for the difference approaches mentioned above and any other possible solutions that might be relevant.
- [ ] Present findings to the DST.

**Comment by humancompanion-usds** [comment]
I'll add use cases here as I think of them. 

### Defeat variations that we don't want to support

One that has come up is that the USWDS Button currently offers accent color variations that we do not, at the moment, intend to expose to VA. When we get va-button as usa-button from USWDS, how do we defeat those variations (which I'd imagine they will add)? 

### Defeat properties we don't want to support

One theoretical use case is if USWDS wants a property on a component that we do not want. While I think we all agreed that we won't allow for disabling form fields, let's just use that as an example. Say there was a property that disabled a component and we didn't want to offer that property. How would we defeat it?

### Add and/or alter properties we do want to support

Essentially the reverse of the above. Let's say we wanted to add inert as our preferred method of disabling a field. We might even want to use the same property name but have it do a different thing. How would we add a property and how might we alter a property to behave differently?

**Comment by jamigibbs** [comment]
This will carry over because of unexpected PTO.

**Comment by caw310** [comment]
@humancompanion-usds assigning to you to review.

**Comment by Andrew565** [comment]
One strategy I thought of for 'defeating' properties or variations we didn't want to support would be to capture them and return our preferred 'default' instead. For example, if we wanted to prevent big buttons, we could do something like:

```
// va-small-button.tsx
// changes big buttons to regular

<Host>
  <va-button 
    ...other props...
    big={false}
  </va-button>
</Host>
```
And it would be used as `<va-small-button props={props}>` and if they tried to pass in the 'big' prop it would just be automatically re-assigned to "big=false". This is with the nesting strategy, but it could also work with the @use strategy I believe.
