### ISSUE TITLE
Reorganize Sketch Libraries Part 3: v1 Components 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1880]
## Description 

We need to move the v1 components, the one we are not adopting from the USWDS, to the new sketch MVP libraries. 

Continuation of this ticket to reorganize the design system libraries part 1 & 2:  

Part 1: [Ticket #1822](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1822)

Part 2: [Ticket #1853](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1822)

## Tasks
- [ ] Move v1 components from [Va-gov-Pattern-Library](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156#Version) to [USWDS MVP Components Library](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/symbols)
- [ ] Add components examples to [Example Library: USWDS MVP Components](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c)
- [ ] Organize components 

## Acceptance Criteria
- [ ] Review with other DS designer 
- [ ] Review with PO

**Comment by LillyBoot** [comment]
Duplicate of [Ticket #1854](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1854)
