### ISSUE TITLE
Maintenance banner - Design - Update banner with feedback give from staging review

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#1881]
## Description
There was a staging review completed for the maintenance banner and some changes were requested. The web component will be updated and the Sketch symbol will need to be updated to match the web components updates. 

## Details
These updates are related to this ticket. 

[Design System Staging Review - IA Feedback - Maintenance Banner web component #60910](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/60910)

## Tasks
- [ ] Update the Sketch component to match the web component once it has been updated
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by babsdenney** [comment]
@humancompanion-usds @LillyBoot This is ready for review.

[Maintenance banner MVP Sketch library](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/4E0B82E3-AA6E-4FEF-9A5E-F00AE31A31BE/canvas)
