### ISSUE TITLE
Figma Exploration

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1882]
## Description
We need to explore what moving our design library to Figma would entail. 

## Tasks
- [x] Explore [Truss version of USWDS library](https://www.figma.com/community/file/836611771720754351)
- [x] Document what changes would need to be made to the Truss Library 
- [x] Import symbol from Sketch to Figma
- [x] Document what transferred to Figma and what broke
- [x] Rebuild a DS component in Figma
- [x] Export Figma component and Import it into Sketch Library 
- [x] Document what transferred to Sketch and what broke 

## Acceptance Criteria
- [x] Documentation has been added to a Mural board 
- [x] Findings have been shared with the DST 
- [x] Reviewed by PO

**Comment by humancompanion-usds** [comment]
I would add exploring the [Truss version of USWDS library](https://www.figma.com/community/file/836611771720754351) to see if their work could be a jumping off point or not.

**Comment by bouayabenmehdi** [comment]
Can you explain more what the objectif of the task ?

**Comment by LillyBoot** [comment]
Create the following tickets: 

1. Explore Anima plugin 
2. Explore variable/design tokens

**Comment by LillyBoot** [comment]
[Mural Board](https://app.mural.co/t/test703663/m/test703663/1690391956115/d824f50a04204eab8d9d521c2a47a20164508477?sender=ucdde6a5c31c67de71bfb6448)
