### ISSUE TITLE
Explore Anima & story.to.design plugins in Figma

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1883]
## Description
[Anima](https://www.animaapp.com/design-system-automation/component-management) purports to provide similar functionality as UXPin Merge in that we can sync from Storybook to Figma. We can also go from Figma to a React component, if we want. It also claims to manage design tokens.

## Details
I'm going to start by digging into CLI sync: https://dsa.animaapp.com/guide/manage-components/sync-components.html#sync-from-an-storybook-url-sync-from-url

## Tasks
- [ ] Test sync from Storybook to Figma using Anima plugin
- [ ] Determine if imported components are usable by designers (i.e. all of the properties translate into Figma and can be used as we are using them in UXPin)

## Acceptance Criteria
- [ ] A Figma file that demonstrates several components functioning which were imported/synced from Storybook

**Comment by humancompanion-usds** [comment]
I ended up making faster progress with [story.to.design](https://www.figma.com/community/plugin/1075741140914731351/story.to.design) and I have [a Figma file](https://www.figma.com/file/pzoI0RGkPkUv6L8h6YZ4RY/story.to.design-Test?type=design&node-id=1%3A260&mode=design&t=D4gdur5i9nxOfNZV-1) for @LillyBoot to look into. However, it has some odd behavior so I'm still going to give Anima a try.
