### ISSUE TITLE
Add v3 Step Indicator component to UXPin

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1891]
## Description
The Veteran-facing Forms team would like to test the v3 Step Indicator component in a UXPin prototype.

## Details
The component needs to be added to UXPin.

## Tasks
- [x] Add the component
- [x] Verify in UXPin that it appears properly

## Acceptance Criteria
- [ ] Veteran-facing Forms team is able to use the component in a UXPin prototype

**Comment by humancompanion-usds** [comment]
PR is here: https://github.com/department-of-veterans-affairs/dst-uxpin-merge/pull/16

I haven't been able to get ZenHub to add dst-uxpin-merge as a repo to our workspace.

**Comment by humancompanion-usds** [comment]
Deployed.
