### ISSUE TITLE
Review GA4 component updates with analytics team

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1892]
A meeting has been scheduled for **July 19th** to review the following component analytic updates:

- va-notification (new component)

https://github.com/department-of-veterans-affairs/vets-website/pull/24770

- va-checkbox
- va-checkbox-group
- va-date
- va-memorable-date

https://github.com/department-of-veterans-affairs/vets-website/pull/24661

- va-link
- va-loading-indicator
- va-modal (custom_string_3?)
- va-number-input

https://github.com/department-of-veterans-affairs/vets-website/pull/24699

- va-select
- va-radio

https://github.com/department-of-veterans-affairs/vets-website/pull/24792

 - va-pagination
 - va-progress-bar
 - va-segmented-progress-bar

https://github.com/department-of-veterans-affairs/vets-website/pull/24870

## Tasks
- [ ] Review GA4 analytics mapping with Michelle Dooley
- [ ] Make any updates necessary to the component mapping

## Acceptance Criteria
- [ ] The listed components have been ok'd by Michelle.

**Comment by jamigibbs** [comment]
Michelle let me know that `custom_string_3` is an available GA4 mapping parameter now. 🥳

**Comment by caw310** [comment]
Closing as the analytics team now needs to review. DST work is complete. 
@michelle-dooley , if there is any work you need from DST, either reopen this ticket or write a new one or reach out to us. Thanks.
