### ISSUE TITLE
Add USWDS V3 Grid Styles to V3 Playground

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1914]
## Description

Previously, an attempt was made to load the USWDS V3 "Layout Grid" styles via importing their global stylesheet (uswds.css). This caused a webpack error: "Conflict: Multiple assets emit different content to the same filename sourcesanspro-light-webfont.woff2" as well as the regular, bold, and italic versions of those files. It is believed by @Andrew565 that this is because the uswds.css file is trying to load the same font that is already being loaded by the `vets-website/src/applications/proxy-rewrite/sass/style-consolidated.scss` file. This error prevents the build from building, effectively preventing the uswds.css stylesheet from being usable.

## Details

The V3 Playground was setup initially to make use of USWDS V3's "Layout Grid" in order to present a nice-looking page. Without being able to load uswds.css, the alternative is to import and make use of `@uswds/uswds/packages/usa-layout-grid/src/styles/_usa-layout-grid.scss`. It is unclear to Andrew if this can be done using a simple "@import" command, or if they need to be used as mixins as suggested [here](https://designsystem.digital.gov/utilities/layout-grid/#mixins-2).

## Tasks
- [ ] Determine how to 'bring in' the layout grid styles
- [ ] Apply the grid styles

## Acceptance Criteria
- [ ] V3 Playground page is making correct use of the grid styles to present content in a V3-compatible way.

**Comment by Andrew565** [comment]
Looking at building a 'base' package of USWDS styles - probably from the CSS Library - instead of worrying about the grid styles specifically.
