### ISSUE TITLE
Deprecation - Alert Box

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1917]
## Description

Per team discussion, we are sunsetting our previous phased deprecation strategy in favor of directly migrating components ourselves. Migration steps look like this:

1. Submit PR, let the email go out, wait a day. If no action:
2. @ the team(s) directly with a comment on the PR. Wait a day. If no action:
3. Message the team(s) directly in slack, requesting a review.  Wait a day. If no action:
4. Merge pull requests.

## Tasks
- [ ] Remove it from the [vets-website GA script](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js#L67-L73).
- [ ] Remove the React component from the component-library repo:
    - [react-components](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/react-components) package
- [ ] Remove the related web component(s) from the [web component migrations list](https://design.va.gov/about/developers/using-web-components#web-component-migrations)
- [ ] Remove any ESLint rules from [vets-website](https://github.com/department-of-veterans-affairs/vets-website) and the [eslint-plugin](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/eslint-plugin).
- [ ] React Component deprecation has been completed following the above process

## Acceptance Criteria
- [ ] Deprecated component has either been removed entirely (if no longer in use) or moved to the next stage of the deprecation process.

**Comment by caw310** [comment]
This issue may take 2 sprints.

**Comment by caw310** [comment]
There is a failing CI issue that is being worked on to resolve. If it is not an easy fix, this will carry over into the next sprint.
