### ISSUE TITLE
Normalizing VA fonts with USWDS settings - Design

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#1923]
## Description
Compare the VA Bitter font and Source Sans Pro to the USWDS settings to normalize the fonts using the USWDS normalization settings. Present results and provide recommendations for creating type settings for size and line height. Update the typography Sketch Library with the new Vertical Rythem settings. Provide recommendations on any updates that would be needed to the VADS in both documentation and code. 

If this is a pattern or component already in existence, conduct a small-scale audit (3-5 examples) to ensure there aren't design issues that need to be addressed. Also, check the Design System Team backlog for outstanding design issues. If you find any, link to them in a comment on this ticket. Please address any outstanding issues with this design and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
[Using USWDS font](https://designsystem.digital.gov/design-tokens/typesetting/overview/)
[Design check-in notes](https://vfs.atlassian.net/wiki/spaces/DST/pages/2699362869/2023-07-13+Meeting+notes)

## Tasks
- [ ] Conduct a small audit if necessary (if a component already exists and we are building a new version)
- [ ] Compare the VA Bitter font and Source Sans Pro to the USWDS normalization settings
- [ ] Present results and provide recommendations for creating type settings for size and line height
- [ ] Update the typography Sketch Library with the new Vertical Rythem settings
- [ ] Provide recommendations on any updates that would be needed to the VADS in both documentation and code 
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] New settings for typography have been documented and updated in Sketch example library
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by babsdenney** [comment]
This is complete. This ticket has a follow-up ticket to try and diagnose a bug in the USWDS where font normalization isn't being applied. 
[Ticket #2025](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2025)

The bitter font normalization settings for a 24px font-size would be
`font-size: 1.6rem;
line-height: 1.3;`
