### ISSUE TITLE
Add Step Indicator to V3 Hard Fork

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1924]
## Description

In addition to the V3 Textarea, add V3 Step Indicator to https://github.com/department-of-veterans-affairs/v3-web-components for USWDS to be able to review and provide feedback on how to use design tokens.

## Tasks
- [x] Add V3-only version of Step Indicator to the v3-web-components repo

## Acceptance Criteria
- [x] Should 'strip out' all V1 code
- [x] Add to stencil's index.html for demo purposes
- [x] Renders correctly

**Comment by humancompanion-usds** [comment]
@Andrew565 - I think that indicates there is a bigger issue to investigate here. My understanding is that our current components in the component-library can exist independently of the foundational design system styles. Do you believe that to be the case today? If so, then we'd want to retain that in the v3-based version of our components. In which case, if there are dependencies in the USWDS components that depend on base styling we'll need a strategy for handling that. If it isn't the case, then we'll just need a way to view v3 components with a v3-foundational system, which I believe we are working towards in the playground.

**Comment by Andrew565** [comment]
I share your concern, my understanding was also that all of the styles needed to correctly render a V3-mode component should be encapsulated within that component. I'll investigate what's missing here.

**Comment by Andrew565** [comment]
Looks like it's related to rem vs pixel height/width measurements again. I can add a style override to manually set the size of the circle to either 25px (font-size 10 * 2.5rem) or 1em (which is slightly smaller but would scale with any font changes).

**Comment by Andrew565** [comment]
Nevermind, it looks like the real culprit is that it's still not loading Source Sans Pro, looking into how to add that now.

**Comment by Andrew565** [comment]
After much experimenting and looking at USWDS' site, I think there's a bug somewhere in their code. I got Source Sans Pro to load in my local Stencil Dev Server, but the step indicator/segmented progress bar still didn't look right. So I looked at all of the values I could, and I found that on [USWDS' site](https://designsystem.digital.gov/components/step-indicator/#default) the `.usa-step-indicator__heading` class has a font-size of 1.33rem, but on my local Stencil (using @uswds/uswds v3.5.0), that same class renders at 1.46rem. I figured out how to fix it so it looks correct using CSS, but as you can see from the attached screenshot, it requires quite a few lines of overrides to get the desired result. ![Screenshot 2023-08-02 at 4.23.05 PM.png](https://images.zenhubusercontent.com/564a129d638e718c995e91b2/4b016596-e61a-4623-aba4-cca3ef85bdb3)

**Comment by Andrew565** [comment]
Our storybook renders correctly, but only because the font-size and width and height, et al, is being calculated using the rem-to-px function I created, and even there it's got the height and width at 2.5 * 16px, but the heading font-size at 1.13 * 16px (instead of 1.33 or 1.46). So something is not right somewhere.
