### ISSUE TITLE
Move header & footer to Symbols library 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1931]
## Description

We need to move the header & footer components from the MVP Foundations & Pattern Library to the MVP USWDS Component Library. 

## Details
- (MVP Foundations & Pattern Library)[https://www.sketch.com/s/998b1585-ba60-474f-ba5d-85729b247f3c/symbols]
- (MVP USWDS Component Library)[https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/symbols

## Tasks
- [x] Move header symbols to component library 
- [x] Move footer symbols to component library 
- [x] Delete symbols from foundations library 

## Acceptance Criteria
- [ ] Reviewed by other DS designer 
- [ ] Reviewed by PO

**Comment by LillyBoot** [comment]
@humancompanion-usds @babsdenney this is ready for review.

**Comment by babsdenney** [comment]
@LillyBoot It looks like the Header and Footer in the example library are pointing to the old location.

**Comment by LillyBoot** [comment]
@babsdenney Thank you for catching that! They should point to the MVP library now
