### ISSUE TITLE
Formation Deprecation - Step 1 - Discovery: Publishing multiple packages from the component-library

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1954]
## Description

We want to make a decision on how releases are going to work for the component library monorepo now that we have both the `component-library` and `css-library`. We are not going to want updates to the CSS Library included in the release notes for the Component Library. They are two separate packages and releases. Currently the component-library package gets published to NPM 

Some [discovery work was already started](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1068) for this that we should leverage. We left off wanting to do some additional exploration with [Lerna](https://lerna.js.org/). Lerna was disregarded because it had a new maintainer but it has been almost a year and a lot can change in that time so I think it would be worthwhile evaluating it as an option too.

## Details

Some things to keep in mind as we're working through this (taken from the original discovery ticket):

- We want to make the process as easy as possible for engineers. There should be very little that we have to remember to do manually to make the publishing process happen correctly.
- Whatever we choose it should be well-supported and well-documented
- While for now we are only looking to publish two packages, in the future we may want to do something like publishing each of our components as an individual package. Whatever tool we choose should be able to handle that.

## Tasks
- [x] Review the previous discovery work done in this ticket https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1068
- [x] Setup a dummy repo for experimenting with Lerna. Document its viability as an option.

## Acceptance Criteria
- [x] Discovery details have been added to this ticket and presented to the team.
- [x] The team has a made a decision and has a path forward for how we will publish multiple packages from the component-library

**Comment by micahchiang** [comment]
I wonder if we could modify [our github action](https://github.com/department-of-veterans-affairs/component-library/blob/bb1bcb44d2eb724fbbe70da96f8e3bb06f7eb551/.github/workflouws/publish.yml#L36-L39) to only conditionally build and publish the css library. That probably doesn't solve the issue of needing separate release notes, but I wonder if that could be automated with a github action as well 🤔

**Comment by jamigibbs** [comment]
> That probably doesn't solve the issue of needing separate release notes

@micahchiang Yes I think the release notes were a big concern (although maybe not a major blocker if we need to get this package out the door sooner rather than later).

I'm not entirely sure the history or conversations in the past that pushed for Lerna or other monorepo build systems but we are not beholden to that direction (the original discovery work was done over a year ago). At one point too there was some discussion with bringing in this [documentation repo to the component-library repo](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1219) too (not everyone was entirely on board with that direction though).

If there is a simpler solution that we think will be easier to manage though, I'm all for it.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1954?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Will carry over so that the findings from discovery can be shared with the team.

**Comment by it-harrison** [comment]
[Discovery document](https://vfs.atlassian.net/wiki/spaces/~96033397/pages/2840100872/Discovery+Publishing+multiple+packages+from+the+component-library)
