### ISSUE TITLE
CSS Library: Setup and generate CSS, SCSS, and JSON token files

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1955]
## Description

Reference discovery ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1837

This ticket is to update the [CSS Library](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library) configuration and generate the base token files. Reference the [discovery ticket PR](https://github.com/department-of-veterans-affairs/component-library/pull/766/files#diff-1c40d3600debc345902064e33f34f49a99e1230a0a9ec56e6aa590bd93188d11) if necessary.

**package.json**

- [ ] Update the existing packages to the latest versions.
- [ ] Update the scripts so that the tokens and stylesheets are generated. For example:

```
  "scripts": {
    "build:tokens": "style-dictionary build",
    "build:stylesheets": "sass --load-path=../../node_modules/@uswds/uswds/packages/ src/stylesheets:dist/",
    "build:minify": "yarn build:tokens && yarn build:stylesheets --style compressed --no-source-map",
    "build": "yarn build:tokens && yarn build:stylesheets"
  },
```

In the above example, running `yarn build` would generate the tokens and stylesheets to the `dist` folder.

**style-dictionary config**

- [ ] generate CSS
- [ ] generate SCSS
- [ ] generate JSON

[This is the config file from the discovery PR](https://github.com/department-of-veterans-affairs/component-library/blob/37b576f1ba88d9839daac99fbd1ce507be8232dd/packages/css-library/config.js). This should provide enough guidance on how to add a general CSS, SCSS, and JSON token files. We are not adding any of the custom token files yet (react-native or Figma) so don't include any of those imports, transforms, or settings. Those will be separate tickets.

## Tasks
- [ ] Update package.json and style-dictionary config files
- [ ] Generate CSS, SCSS, and JSON token files.

## Acceptance Criteria
- [ ] The CSS Library package has CSS, SCSS, and JSON token files available.
