### ISSUE TITLE
CSS Library: UXPin token file

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1958]
## Description
Reference discovery ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1837

We might not need to create anything custom for UXPin to import a token file. It's possible we just need to use one of the general CSS files already in the CSS Library. Looking at some [UXPin](https://www.uxpin.com/) tutorials, I believe we can import it directly from their settings and it will automatically generate those values.

![Screenshot 2023-07-26 at 12 33 59 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/ad34274f-5ef6-445a-ade7-a99c4fcf2a6e)

A public link can be taken from github by navigating to a file's [raw output like this](https://raw.githubusercontent.com/department-of-veterans-affairs/component-library/37b576f1ba88d9839daac99fbd1ce507be8232dd/packages/css-library/dist/css/tokens.css).

![Screenshot 2023-07-31 at 3 21 48 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/70fad4be-4f48-4aa2-b31d-cbc1c6e7d917)

## Tasks
- [ ] Test the existing CSS token file in the CSS Library to confirm that it imports into UXPin
- [ ] If UXPin is requiring a different format, create that format if necessary with style dictionary

## Acceptance Criteria
- [ ] A tokens file exists for UXPin in the CSS Library
