### ISSUE TITLE
 CSS Library: How to import/pass-through specific USWDS tokens?

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1967]
## Description

Reference discovery ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1837

This could be worked on in tandem with:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1968

Currently the [tokens in the CSS Library](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library/tokens) are VA specific. We would like to see how we can import or "pass-through" specific USWDS tokens to that they are available in the CSS Library tokens file(s).

- https://github.com/uswds/uswds/tree/develop/packages/uswds-tokens/colors
- https://designsystem.digital.gov/utilities/color/

We should also identify if any of the existing color tokens in the CSS Library could be mapped to USWDS colors tokens. 

For example, the following tokens that have been manually added to the CSS Library would ideally be pulled in directly from USWDS:

https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/tokens/color.json#L58-L64

```
  "v3-color": {
    "error": {
      "dark": { "value": "#b50909"}
    },
    "base": {
      "darkest": { "value": "#1B1B1B"}
    }
  }
```

## Tasks
- [ ] Identify a technical solution for importing specific USWDS tokens in the CSS Library
- [ ] Setup the solution in the CSS Library

## Acceptance Criteria
- [ ] The CSS Library has the ability to import specific USWDS tokens that we define and those tokens are generated with the existing base tokens file which uses style-dictionary.

**Comment by humancompanion-usds** [comment]
@jamigibbs (and whomever works on this) - I finally got to the Interagency Design System Knowledge Share meeting today (it moved to a time where I could attend) and talked to SSA who are:
* Also using tokens
* Also using Style Dictionary
* Also consuming tokens from USWDS

They confirmed what I suspected: They simply copy the JSON file over from USWDS into their Design System (UEF). They do it in a build step. Thus I'd like to do the same. 

They also told me that to "pass tokens along" they just expose all of the USWDS values in their tokens. Unfortunately, none of their stuff is open source and so I didn't see if or how they namespaced those tokens. But what I'd like to explore is doing the same and namespacing the USWDS tokens with "uswds" and our own tokens with "vads" for each token. For example:

uswds-system-color-blue-50

If we cannot namespace them then we'll get:
system-color-blue-50

That's fine but slightly less obvious. I'll have the full taxonomy ready next week but I'm certain of this now.

**Comment by humancompanion-usds** [comment]
An addendum: Acceptance criteria for this issue would be 2 things:

1. An example of at least one of our tokens referencing a USWDS token. For example:

`vads-core-color-primary = uswds-system-color-blue-vivid-50`

(Taxonomy of tokens to come in issue #1973 

2. Output of the USWDS tokens within our token files, ideally namespaced. This would allow other platforms and systems access to the USWDS tokens via our Design System.

**Comment by Andrew565** [comment]
It looks to me like the only tokens that USWDS is providing in JSON format currently are their colors, so going to start by including those.
