### ISSUE TITLE
Test Figma plugin Anima 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1972]
## Description
We are looking for an easier way to move our Design System to Figma. Anima is plugin that can turn design into code and code into design. We want to test this plugin to see if it will be helpful in the move to Figma  

## Details
[Anima Plugin](https://www.animaapp.com/figma)
[Mural Board](https://app.mural.co/t/test703663/m/test703663/1690391956115/d824f50a04204eab8d9d521c2a47a20164508477?sender=ucdde6a5c31c67de71bfb6448)

## Tasks
- [ ] Use the Plugin on a DS component in Figma and export it to code 
- [ ] Document what worked and what didn't 
- [ ] Use the plugin on a coded component and import it to Figma 
- [ ] Document what worked and what did not 

## Acceptance Criteria
- [ ] Documentation has been added to a Mural board
- [ ] Findings have been shared with the DST
- [ ] Reviewed by PO

**Comment by humancompanion-usds** [comment]
I had already started an issue but I will close it out: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1883

**Comment by LillyBoot** [comment]
@jamigibbs will create a Dev discovery ticket to further explore this
