### ISSUE TITLE
Discovery: Importing web components into Figma

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1990]
## Description

We are moving from Sketch to Figma and we are looking for an easier way to import our existing Design System components to Figma. We would like to explore the [Anima DSA](https://dsa.animaapp.com/guide/introduction/) workflow for doing this. 

The Anima DSA docs describe [two different methods](https://dsa.animaapp.com/guide/manage-components/cli-vs-url.html) to connect:

- (Basic) By providing a URL to your Storybook - great for seeing the results instantly
- (Advanced) By using CLI command on your local or CI machine - great for a continuous automated workflow

These are the packages we might be able to leverage for the automated approach:

1. [@animaapp/anima-cli](https://github.com/AnimaApp/anima-dsa/blob/master/packages/anima-cli):  A command line tool that works in conjunction with the [Anima Figma Plugin](https://www.figma.com/community/plugin/857346721138427857) to transform [Storybook](https://storybook.js.org/) stories into Figma components and design tokens into Figma styles.
2. [@animaapp/style-dictionary](https://github.com/AnimaApp/anima-dsa/tree/master/packages/style-dictionary): This package contains transformers and parsers for design token workflows that use Style Dictionary. This package may be useful for when we generate a [Figma token file](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1957) in the [CSS Library](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library).

Related designer discovery: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1972

## Tasks
- [ ] Create a free [Figma account](https://www.figma.com/) for testing.
- [ ] Explore how to connect our Storybook with your test Figma account.
- [ ] Import a v3/MVP component into the Figma testing account using either the method above or another discovered way.
- [ ] Import design tokens into the Figma testing account using either the method above or another discovered way

## Acceptance Criteria
- [ ] An approach on how to import existing design system components has been discovered
- [ ] Sign-off and validation from @LillyBoot on that approach.
- [ ] A follow-up ticket has been created to connect that approach with our actual Figma instance.

**Comment by caw310** [comment]
Work with Matt and Lily on this please.

**Comment by ataker** [comment]
We've decided on using [story.to.design](https://story.to.design/blog/from-storybook-to-figma#how-to-link-storybook-to-figma) to import the components. (Will have full write-up on that, but bottom line is this is the only plugin I've found that imports components, the rest connect fully designed Figma components with their Storybook counterpart, but have no shortcuts on getting them into Figma.)

Here's the basic instructions on importing a component:

1. In Figma, go to to Plugins -> Find more plugins…
2. Search for story.to.design.
3. In the pop-up, enter our [Storybook URL](https://design.va.gov/storybook/?path=/story/about-introduction--page).
4. Click Connect.
5. Wait for it to load the stories, then click Import new component.
6. In the new pop-up, select the component you want to import, then select the default version.
7. You can add variants based on the arguments our components have.
8. Click Import and wait for it to load.
9. Once loaded you can add the component to the canvas.

At this point I need designer to know what is missing or not working as expected. @LillyBoot @humancompanion-usds 

One drawback of story.to.design is that it is a subscription service, so we will need to pay after the first 15 components have been imported.

**Comment by LillyBoot** [comment]
@ataker we have tested story.to.design before and unfortunately we found that the components did work the way we wanted them to. I recorded our findings on this [Mural board](https://app.mural.co/t/test703663/m/test703663/1690391956115/d824f50a04204eab8d9d521c2a47a20164508477?sender=ucdde6a5c31c67de71bfb6448). Let me know if you need any additional information

**Comment by ataker** [comment]
Anima DSA is no longer supports importing from Storybook to Figma.

story.to.design imports from Storybook to Figma, but does not import in a way that wouldn't cause a lot of rework to be done by the designers.

We didn't find other apps that would help with the import to Figma.

We may in the future get some value out of [Storybook Connect](https://www.figma.com/community/plugin/1056265616080331589/Storybook-Connect) or [Contrast](https://uxdesign.cc/how-to-connect-storybook-figma-toppling-the-great-divide-6c1923182653) which help compare the component in Storybook to the component in Figma, but they do not help import.

**Comment by jamigibbs** [comment]
I'm adding some guidance here on how to import components on a local vanilla build of Storybook with story.to.design.

1. Clone the [Vanilla Storybook](https://github.com/jamigibbs/storybook-vanilla) repo
2. Download, install, and sign in to the [story.to.design agent](https://story.to.design/docs/agent)
4. Run the storybook build and start the storybook static server:
```
yarn run build-storybook
npx serve storybook-static
```
5. Connect to your locahost in the story.to.design plugin in Figma using `http://localhost:3000/`:

![Screenshot 2023-08-30 at 4 00 47 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/c4740fb6-cc0b-45f4-bb86-1364a854c732)

6. Follow the plugin screens for importing/updating components.

If you're receiving errors, check this [Discord support thread](https://discord.com/channels/744781525119139859/1146131735868866610/1146131735868866610) to see if it resolves any of the issues.

Note: Because it's a static build of Storybook, any changes you make to the local Storybook files will need to be re-built so you will need to run `yarn run build-storybook` and `npx serve storybook-static` again after the change.
