### ISSUE TITLE
Add USWDS V3 Base CSS package to V3 Playground

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#1993]
## Description
A base package of USWDS styles should be added to the V3 playground in order to assess the impact of using USWDS styles over existing formation styles. 

## Details
- A [previous issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1914) to import USWDS V3 grid styles uncovered some challenges around importing USWDS styles. 

## Tasks
- [ ] Determine what a base package of USWDS styles is comprised of
- [ ] Import the base package into the V3 playground

## Acceptance Criteria
- [ ] V3 playground is using imported base package

**Comment by jamigibbs** [comment]
This PR might be a useful reference: 
- https://github.com/department-of-veterans-affairs/vets-website/pull/22667

**Comment by micahchiang** [comment]
Let's talk about this as a team in the engineering meeting next week (which I've moved to Tuesday so @jamigibbs can attend). We should try and come to a consensus on what constitutes a base package at this point in our migration process. Is it typography, spacing, and color? Just one or two of those?
