### ISSUE TITLE
Figma Transition: Understanding Figma   

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#2002]
## Description
In order to prepare for the switch to Figma we need to get ourselves more familiar with it. Below is a list of tutorial videos that will help us learn how to set up and build a design system in Figma. We also what to get an understanding of this Pro account limitations. 

## Details
[Figma for Beginners](https://help.figma.com/hc/en-us/sections/4405269443991-Figma-for-Beginners-tutorial-4-parts-)
[Building Components](https://help.figma.com/hc/en-us/articles/360038662654-Guide-to-components-in-Figma) 
[Component Variants](https://help.figma.com/hc/en-us/articles/360056440594-Create-and-use-variants)
[Component Properties](https://help.figma.com/hc/en-us/articles/5579474826519-Explore-component-properties)
[Quick Overview of Variables](https://help.figma.com/hc/en-us/articles/15339657135383-Guide-to-variables-in-Figma)
[Deep Dive: Variables](https://www.youtube.com/watch?v=M0NU5QFLCl4) 
[Building Design System](https://help.figma.com/hc/en-us/articles/14548865734679-Lesson-3-Build-your-design-system)
[Document, improve and update your design system](https://youtu.be/_sTWtnNU1L0?si=hVcSAY7__f20UaGJ)

## Tasks
- [ ] Discover and document what the limitations of the Pro account are
- [ ] Watch videos 
- [ ] Read documentation 
- [ ] Practice building components in the free version of Figma 

## Acceptance Criteria
- [ ] Share Pro account findings with team/PO
- [ ] Finished watching videos
- [ ] Built at least 1 component in Figma using auto layout, properties and variants 
- [ ] Review by Lilly?

**Comment by caw310** [comment]
Will be done over two sprints.

**Comment by naomimarcussen** [comment]
These are great resources Lilly! We might want to add [Document, improve and update your design system](https://youtu.be/_sTWtnNU1L0?si=hVcSAY7__f20UaGJ). We already do a lot of this, but it has a lot of great tips and best practices as well.

**Comment by LillyBoot** [comment]
@naomimarcussen thats a good idea, thank you! I will add it to the list

**Comment by LillyBoot** [comment]
Here is the [Mural board](https://app.mural.co/t/test703663/m/test703663/1692890274595/42f7c7487590cb1dc7cdf7d817fbada44a88e3ee?sender=ucdde6a5c31c67de71bfb6448) with my current finding for what we can get with a Pro account. I'll be able to update this further once the DST has accounts

**Comment by caw310** [comment]
Closing this as this for now.
