### ISSUE TITLE
Figma Transition: List of components that need to be rebuilt 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#2003]
## Description
In order to make the move to Figma we need to figure in what order we need to rebuild components. Take into consideration what components are most used, used as nested components and the time they'll take to create. 

## Details
[List of most used components](https://docs.google.com/spreadsheets/d/1aSdKzTJLql8kn0sgLIq4MlT9y_Jclf_nFecY1UT47Xs/edit#gid=0)
[List of Components both VA and USWDS](https://airtable.com/appF4FJKBeNVNGrlm/tblRMaKxvyPn6F0qe/viw6WoPXgF8g0sNFy?blocks=hide)

## Tasks
- [ ] Create a list of components we need to build
- [ ] List them in the order they should be built

## Acceptance Criteria
- [ ] Review with DS designers 
- [ ] Review with PO

**Comment by LillyBoot** [comment]
@humancompanion-usds @babsdenney this is ready for review. We can discuss during the design chat today if we have time. 

[Component Priority Build list](https://docs.google.com/spreadsheets/d/1itqyJWmgVft1FNZZ3IeXCSyhTgS0n_hTujZE3-HLz1E/edit?usp=sharing)

**Comment by LillyBoot** [comment]
@babsdenney this is ready for review again. I add the atoms you listed and put them in the build order. We can edit this as we go along if needed

**Comment by babsdenney** [comment]
@LillyBoot This looks great! Thank you!

**Comment by babsdenney** [comment]
@LillyBoot Thanks! I was wondering about that. The reasoning was that the MVP was a set amount of components that teams should be using and then the rest would be V3. I'll get those moved over.
