### ISSUE TITLE
Default version of Memorable date should be select month 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2011]
## Description
The default for memorable date should have month be a select box. The month text input should be a variation. 

## Details
Update Storybook: https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--with-month-select 
Update design.va.gov: https://design.va.gov/components/form/memorable-date

## Tasks
- [ ] Update Memorable Date in Storybook so that the default version of Memorable date has month as a select. 
- [ ] Update design.va.gov with screenshot of the default version of Memorable date has month as a select

## Acceptance Criteria
- [ ] Storybook has been updated
- [ ] design.va.gov has been updated
