### ISSUE TITLE
Add custom header and footer support

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#2017]
## Description

This ticket is for implementing the discovery work completed in [#1828](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1828). The developer will add support for custom headers and footers to the vets-website and content-build repos. This support will utilize new registry values - `customHeader` and `customFooter` - which will accept a string value representing the name of the header or footer which should be included and rendered. These headers and footers can be added at a later date.

## Details

Draft PR for vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/25275
Draft PR for content-build: https://github.com/department-of-veterans-affairs/content-build/pull/1671

## Tasks
- [ ] Add customHeader and customFooter support to vets-website's dev-template.ejs
- [ ] Create "placeholder" custom header and footer on vets-website in the dev-template.ejs file
- [ ] Add customHeader and customFooter support to content-build's header.html and footer.html
- [ ] Create "placeholder" custom header and footer on content-build in order to verify that support works there

## Acceptance Criteria
- [ ] Custom header and footer support works
