### ISSUE TITLE
Add CSS type (element/tag) selectors to the CSS Library

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2042]
## Description

We have identified several element/tag selectors in Formation that can be moved into the CSS Library. Those selectors can be copied into the [elements.scss](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/elements.scss) stylesheet.

Review the related discovery for more context: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1025

### Identified selectors

  - [article > h1](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L309-L311)
  - [hr](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L190-L194)
  - [abbr, a, headings, ol/ul, figure, etc](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L72-L179)
  - [html and body (**except font-size**)](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L1-L17). **We don't want the font-size's because it conflicts with USWDS v3**
  - [mobile typography h1, h2](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/mobile-typography.scss#L7-L15)
  - [print header, footer, nav](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-print.scss#L7-L9)
  - [print a[href]](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-print.scss#L23-L30)

## Tasks
- [ ] Move the identified selectors to the CSS Library elements.scss stylesheet.
- [ ] Double check Formation for any other selectors that might have been missed.
- [ ] Check to make sure that the styles compile correctly and working (any color variables, etc. are working or mapping updated).
- [ ] Generate the stylesheet and check it in to the repo

## Acceptance Criteria
- [ ] Identified element/tag selectors from Formation have been added to the CSS Library

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2042?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
