### ISSUE TITLE
Audit Formation base styles for parent class > child element/tag's for CSS Library

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2043]
## Description

We need to check if any of the parent class > child tag base styles in Formation are still in use and if so, add those styles to the CSS Library:

https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base

Here is [an example of parent class > child tag styles](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L332-L352) where the classes feature-list and va-list--feature are not found/used any more so we don't need to bring that over. 

## Considerations
- related discovery https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1025
- Recent audit of _shame.scss - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2044

## Tasks
- [ ] Identify any base parent class > child tag styles in Formation
- [ ] Check if those styles are still being used in `vets-website` or `content-build`
- [ ] If the style is still being used, add it to the CSS Library (part of this work is determining the best place for it in the CSS Library. elements.scss? separate stylesheets?)
- [ ] If the style is not being used, remove it from Formation

## Acceptance Criteria
- [ ] Formation base styles have been audited for any active parent class > child tag styles.
- [ ] Any styles still being used have been added to the CSS Library

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2043?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
