### ISSUE TITLE
Audit _shame.scss stylesheet in Formation

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2044]
## Description

We need to audit the [_shame.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/_shame.scss) file currently in Formation to determine which styles are still relevant and which ones can be removed.

We are doing this as part of our work to transition off of Formation and on to USWDS v3 (by extension, the CSS Library).

related discovery https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1025

## Tasks
- [ ] Go through each of the styles in the _shame.scss file and check if the style is still being used in either `vets-website` or `content-build`.
- [ ] If it's still being used, leave it there.
- [ ] If it's not being used, remove it.

## Acceptance Criteria
- [ ] The _shame.scss file has been audited for active styles and updated.
- [ ] A new version of Formation has been created and vets-website updated.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2044?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
