### ISSUE TITLE
Create an ESLint Rule to use va-button instead of button and va-table instead of table

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2046]
We would like to encourage the use of `va-button` instead of `button`. The task here is to create an autofixable ESLint Rule similar to the [telephone rule here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/lib/rules/prefer-telephone-component.js).

The rule should trigger on the element `button` and provide a fix path to replace it with `va-button`.

related discovery https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1025

## Tasks
- [ ] Create an ES Lint rule to help developers use `va-button` instead of `button`
- [ ] Create an ES Lint rule to help developers use `va-table` instead of `table`

## Acceptance Criteria
- [ ] An ES Lint rule exists for using va-button instead of button that auto fixes.
- [ ] An ES Lint rule exists for using va-table instead of table

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2046?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010
