### ISSUE TITLE
Figma Foundations: Color 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#2051]
## Description
Before we can begin building components in Figma we need to create the foundations of the design library. We will need to add the following foundations: 

- Color
- Typography 
- Icons 
- Spacing 
- Grids  

## Details
[VA Colors](https://design.va.gov/foundation/color-palette)
[Ticket for Generating Figma Token file](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1957)

## Tasks
- [x] Import VA colors into Figma 
- [x] Import USWDS colors into Figma 
- [x] Create a Variable primitive collection for colors 
- [x] Add colors to to collection 
- [x] Create Token collection for colors 
- [x] Link token colors to primitive colors 

## Acceptance Criteria
- [ ]Reviewed by PO

**Comment by caw310** [comment]
Work on this will carry over as more work and review is needed before setting up colors in Figma Foundation.

**Comment by LillyBoot** [comment]
The colors will need updating in the future, but the foundation is complete.
