### ISSUE TITLE
Evaluate if we need/want the component_version value for Google Analytics

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2053]
## Description
In the [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js ) file, we have a `component_version` key that does not appear to be sending any information to the analytics dashboard.

The work in this ticket is to:
1. decide if we even need to be sending that information at all
- is there a reason we would need that info? 
- vets-website and content-build could be on different version but does the library version matter for analytics tracking?
2.  based on the above either connect it, or, remove it.

## Tasks
- [ ] Decide if we need the component_version tracking in the component library analytics setup file
- [ ] Make necessary adjustments to the script depending on if we are keeping it or not.

## Acceptance Criteria
- [ ] The component-library-analytics-setup.js for the component_version key.

**Comment by randimays** [comment]
Noticed this when implementing analytics on our va-links: the `component-library-version` is undefined. Seems to be the same issue here 👍🏻 

<img width="585" alt="Screenshot 2024-06-17 at 9 25 23 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/19175324/a477109e-a075-426e-8ba6-6bbef6068419">
