### ISSUE TITLE
Figma Foundations: Icons 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#2064]
## Description
Before we can begin building components in Figma we need to create the foundations of the design library. We will need to add the following foundations: 

- Color
- Typography 
- Icons 
- Spacing 
- Grids  

## Details
[VA FA Icons](https://design.va.gov/foundation/icons)
[Sketch file - Icons](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/p/AD020A9B-09E9-4F65-B70B-F1D2C1BA3615/canvas)

## Tasks
- [x] Import FA icons into Figma 
- [x] Make icons into components 
- [x] Link icons to variable token color 
- [x] Add documentation for usage 

## Acceptance Criteria
- [ ]Reviewed by PO
