### ISSUE TITLE
Figma Component Rebuild: Modal 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#2066]
## Description
We have to rebuild our components in Figma since they do not transition well from Sketch. This is the [list of components we will need to rebuild](https://docs.google.com/spreadsheets/d/1KVANmign6_HofQGkX_sYJeamsFe_9X9z6WWpJ030zq8/edit?usp=sharing).  The goal with rebuilding the components is to make them as reactive as possible using auto layout and properties. 

## Details
[Truss USWDS library](https://www.figma.com/community/file/836611771720754351)
[Story.to.design Ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1990)
 - You will need developer help to import using story.to.design Plugin 

## Tasks
- [x] Pull in component design from either Truss (USWDS) or story.to.design
- [x] Break component to rebuild 
- [x] Link to variable tokens 
- [x] Add auto layout 
- [x] Determine which Properties to add to design (Variants, Boolean, Instance swap and text) 
- [x] Test the component

## Acceptance Criteria
- [x] The design is the same as what is in the Component Symbol Library in Sketch 
- [x] Reviewed by other DS designer 
- [ ] Review by PO?

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2066?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by babsdenney** [comment]
@danbrady @LWWright7 This is ready for review. I tagged you in a comment in the Example Library.

**Comment by danbrady** [comment]
Looks pretty good, @babsdenney! I'll leave comments in the Figma file.

**Comment by caw310** [comment]
Dependency on button. Dan will close this ticket once he is done with the button.

**Comment by danbrady** [comment]
@LWWright7 This is ready for testing! 

Modal ([Component](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=613%3A630&mode=design&t=IyW0YvtFw6jDDZa5-1), [Examples](https://www.figma.com/file/JDFpGLIojfuQwANXScQjqe/VADS-Example-Library?type=design&node-id=230%3A6782&mode=design&t=E2oiddFBtgYxSIWc-1))

**Comment by LWWright7** [comment]
Finished testing!!
