### ISSUE TITLE
Figma Foundations: Spacing 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#2081]
## Description
Before we can begin building components in Figma we need to create the foundations of the design library. We will need to add the following foundations: 

- Color
- Typography 
- Icons 
- Spacing 
- Grids  

## Details
[VADS Spacing Airtable](https://airtable.com/appF4FJKBeNVNGrlm/tblVoDslTYpAh7dr1/viw5VK18YcZe6E4vq?blocks=hide)

## Tasks
- [x] Add spacing to a Primitive collection (Number variable) 
- [x] Link token spacing to primitive spacing 
- [x] Determine what we want the the spacing to be applied to i.e text, width & height, radius, etc.  

## Acceptance Criteria
- [x] Reviewed by PO
