### ISSUE TITLE
Tokens - Add Hub colors

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2084]
## Description

These color variables need to be added as tokens:
$red-70v: #8b1303;
$red-60v: #b51d09;
$indigo-cool-60: #3f57a6;
$red-60: #a23737;
$mint-cool-50: #21827f;
$orange-warm-50: #bd5727;
$green-cool-50: #3e8520;
$gold-50: #8e704f;
$green-warm-50: #6f7a41;
$blue-50: #357ab2;
$violet-warm-60: #864381;

// Contextual variable names
$color-hub-health-care: $indigo-cool-60;
$color-hub-education: $mint-cool-50;
$color-hub-disability: $red-60;
$color-hub-careers: $orange-warm-50;
$color-hub-pension: $green-cool-50;
$color-hub-housing: $gold-50;
$color-hub-life-insurance: $green-warm-50;
$color-hub-burials: $blue-50;
$color-hub-records: $violet-warm-60;
$color-hub-family-member: $color-primary-darker;
$color-hub-service-member: $color-primary-darker;

## Tasks
- [ ] Add color tokens
- [ ] Hand off to development

## Acceptance Criteria
- [ ] vets-website is using color token values
