### ISSUE TITLE
v3 of number input should support prefix and suffix

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2105]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Description
The v3 version of number input is missing the current variation. Number input component needs to support  prefix/suffix.  

## Tasks
- [ ] Update v3 version of number input to support prefix and suffix 
- [ ] Update Storybook with currency variation

## Acceptance Criteria
- [ ] Number input component supports prefix and suffix
- [ ] Storybook is updated

**Comment by rhasselle-oddball** [comment]
Adding a note - please be sure to test with a screen reader too, for example, if dealing with a currency, you probably want that read out. thanks!

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2105?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010

**Comment by micahchiang** [comment]
We should talk about deprecating number input and instead relying on optional pattern validation for text input.

**Comment by ToddWebDev** [comment]
I agree the number input probably isn't the best approach for entering a currency. The existing 'currency' widget uses a text input to allow a more natural way to input a currency that is validated with a Regex pattern. Ideally, we could add a 'currency' input to the VA Forms library via a text input with an optional prefix '$' and custom validation.

**Comment by caw310** [comment]
Closing this as va-number-input will be deprecated. Instead va-text-input will be updated to support prefix and suffix.

**Comment by Dr-Pongo** [comment]
> Closing this as va-number-input will be deprecated. Instead va-text-input will be updated to support prefix and suffix.

Hey @caw310 is there a ticket for the prefix/suffix (currency) implementation for `va-text-input`? I just want to follow along so we know when it's available for use!

**Comment by caw310** [comment]
@Dr-Pongo this is the ticket to add prefix/suffix to va-text-input. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2882
