### ISSUE TITLE
Setup Storybook to include Mobile app components

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2109]
## Description
In order to make it easier for designers and developers to reference the mobile application we need to show flagship mobile app components in the Design System. The first step of that is showing mobile components in Storybook. The mobile team has created [an instance of Storybook](https://department-of-veterans-affairs.github.io/va-mobile-library/), which was necessary in order to get mobile components to show up on the web.

[Storybook supports composition](https://storybook.js.org/docs/react/sharing/storybook-composition) which will allow us to pull mobile components in from the [mobile component library](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/components).

## Tasks
- [ ] Work with @timwright12 to verify that I captured the Storybook and mobile component library repo URLs correctly
- [ ] Read up on Storybook composition
- [ ] Configure our Storybook to show a mobile app component
- [ ] Give mobile a section in our Storybook

## Acceptance Criteria
- [ ] We can view a mobile app component at https://design.va.gov/storybook/

**Comment by jamigibbs** [comment]
Related discovery work:

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3716
