### ISSUE TITLE
Publish QA checklist for design assets for components

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2119]
## Description
We should have an agreed upon process for testing components that we build out in Figma as we transition from Sketch to Figma. The agreement should be between myself and the designers on the team. 

## Details
The mobile app team has published a guide that may serve as a jumping off point: 
https://department-of-veterans-affairs.github.io/va-mobile-app/docs/UX/How-We-Work/figma-components

We'll likely want to document:
* "How to build"
* "How to QA" 
* "What makes an acceptable, quality component"

## Tasks
- [ ] Gather input from the designers on the Design System Team
- [ ] Write a draft document
- [ ] Have draft reviewed for content and clarity
- [ ] Public

## Acceptance Criteria
- [ ] A document in about/designers/ (perhaps contributing/) that details how to create and test components in Figma

**Comment by humancompanion-usds** [comment]
I dropped this into the current sprint because of Lilly's impending departure but this work can carry over into the next sprint, if need be.

**Comment by humancompanion-usds** [comment]
Some things that should definitely be on the list:

* Visual quality: color, typography, icons, space, borders, etc. are all inline with the foundations of the Design System
* Tokens: Are we using variables in Figma whenever possible? Are we using the correct semantic or primitive tokens?
* States: Default, hover, active, focus, inert, et. al.
* Variations: Default + whatever else we need to show
* Responsiveness: Mobile and desktop shown in examples, at minimum
* Content Resilience: Check for long labels, word wrapping, etc. and ensure that the component doesn't break and that spacing is maintained.

**Comment by LillyBoot** [comment]
@humancompanion-usds @babsdenney @danbrady This is ready for review 

https://vfs.atlassian.net/wiki/spaces/~63d7ed0df1475ad42c577ae0/pages/edit-v2/2774073655?draftShareId=ebad8c7f-05fe-4aa9-8386-65e4801c60e9

**Comment by humancompanion-usds** [comment]
@LillyBoot -I'm getting an error from Confluence that "We can't open that page."

**Comment by LillyBoot** [comment]
@humancompanion-usds try this link https://vfs.atlassian.net/l/ce/E3sqEqLU

**Comment by humancompanion-usds** [comment]
Approved. I'm going to publish this to design.va.gov. So leave it here in Review for now. Thanks.
