### ISSUE TITLE
Apply Font Normalization settings from USWDS

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2120]
## Description

This normalization bug has had a few different moving parts to get to this point. 

1. Nick was able to find a bug in the USWDS that was preventing the font normalization settings. He submitted an issue to the USWDS to fix the bug. We are waiting for that fix to be applied. You can [track that issue on the USWDS here](https://github.com/uswds/uswds/issues/5501). 
2. There are some Design requirements that should be completed in this Design ticket below. The design ticket will provide the Bitter font files and cap-height to be applied. 
3. When the USWDS has applied the fix and Design ticket is complete, we can continue with this ticket.  

## Details

Design - [Normalizing the Bitter font and fixing USWDS normalization settings #2074](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2074)
Initial bug solution/ticket - [USWDS Font normalization settings bug#2025](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2025)

## Tasks
- [ ]   Integrate Bitter fonts into the project
- [ ] Add normalization settings

## Acceptance Criteria
- [ ] Bitter font has been added
- [ ] Normalization settings are applied

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2120?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010

**Comment by caw310** [comment]
Closing. Will reopen if this is still needed.
