### ISSUE TITLE
Figma Component Rebuild: Button and Button group

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2127]
## Description
We have to rebuild our components in Figma since they do not transition well from Sketch. This is the [list of components we will need to rebuild](https://docs.google.com/spreadsheets/d/1KVANmign6_HofQGkX_sYJeamsFe_9X9z6WWpJ030zq8/edit?usp=sharing). The goal with rebuilding the components is to make them as reactive as possible using auto layout and properties.

The buttons and button group are components that are already created by the VES team in VES component library. This component will need to be rebuilt within the VADS component library. The buttons and button pairs are used in multiple places within the VADS component library. Ensure that it will adapt to many different components. 

Components to complete:

- [x] Button
- [x] Button group

## Details
The buttons are already found in the VADS but need to be rebuilt with VADS variables and states. Compare them to what is in Storybook and Sketch to make sure they are aligned with our current buttons and button states. 

## Tasks

- [X]  Compare current Figma buttons to [Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-button--primary) and [Sketch](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/5317C603-D6BD-4AFF-84E6-151F7A197B91/canvas) and what is in the [VADS component library](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=0%3A1&mode=design&t=ouWPO4ahvHX1GtzW-1).
- [X]  Break component to rebuild (if needed)
- [X]  Link to variable tokens
- [X]  Add auto layout
- [X]  Determine which Properties to add to design (Variants, Boolean, Instance swap and text)
- [X]  Test the component (Try to break component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch

- [x]  Reviewed by other DS designer
- [ ]  Review by PO?

**Comment by danbrady** [comment]
Additional info was used in some of the form inputs, so I handled that one already.

**Comment by danbrady** [comment]
@LWWright7 @babsdenney This is ready for review!

Button - ([Component](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=199%3A1198&mode=design&t=ftIZzAG5z3lkfaIx-1), [Examples](https://www.figma.com/file/JDFpGLIojfuQwANXScQjqe/VADS-Example-Library?type=design&node-id=35%3A152&mode=design&t=nEyrEQ8EZtjPAWBd-1))
Button Group - ([Component](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=618%3A5091&mode=design&t=ftIZzAG5z3lkfaIx-1), [Examples](https://www.figma.com/file/JDFpGLIojfuQwANXScQjqe/VADS-Example-Library?type=design&node-id=35%3A153&mode=design&t=nEyrEQ8EZtjPAWBd-1))

**Comment by danbrady** [comment]
Ready for you, @humancompanion-usds. (I set up some instances in the Example Library to demo buttons on mobile.)
