### ISSUE TITLE
Figma Component Rebuild: Linking variables - spike ticket "research component dependencies" 

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2128]
## Description
We need to link current Figma components that are already in the Figma VADS library to the variables that are already created in the current library. Use the list below to go through and connect the components with the correct variables. 

@LWWright7 will do an assessment of the components below to see if there are any dependencies on other components and will create appropriate tickets to address those dependencies: 

- [ ] Collection Link 
- [ ] Accordion 
- [ ] OMB Info 
- [ ] Back to top 
- [ ] File Input Banner 
- [ ] Maintenance Banner
- [ ] US Privacy Agreement 
- [ ] Progress Bar 
- [ ] Autosave 
- [ ] Address block 
- [ ] Penalty Notice 
- [ ] Prefill 
- [ ] Need Help? 
- [ ] Tag 
- [ ] Divider

Look at the components in [storybook](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default) and also in [Sketch](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4) to make sure all the variables are matching the colors and styles.

## Tasks

- [ ]  Link to variable tokens
- [ ]  Verify these components are setup with auto layout and the correct properties
- [ ]  Test the component (Try to break the component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch

- [ ]  Reviewed by other DS designer
- [ ]  Review by PO?

**Comment by LWWright7** [comment]
@LWWright7 I will do an audit to see which of these items have dependencies on other components.

**Comment by caw310** [comment]
Based on the audit, we will pick 3 to work on and create a new ticket for the rest.

**Comment by LWWright7** [comment]
@babsdenney @caw310 @danbrady Here is my assessment of the items from above:
OMB Info & Back to Top have a dependency on Button
The 2 banner components have a dependency on header.
Collection Link, Accordion, Privacy Agreement, Progress Bar, Autosave, Address Book, Penalty Notice, Prefill, Need Help?, Tag, Divider appear to be done 

I'll create tickets that have OMB Info & Back to Top grouped together, the 2 banners grouped together and then create tickets with 3-5 items grouped together as some of these are really easy quick things to do.

**Comment by LWWright7** [comment]
@caw310  - I made this ticket a spike ticket for the assessment / research on component dependencies, changed the estimate to a 2, closed the ticket to document this work as done...other tickets created as listed above.

[2232 - autosave, address block, et al](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2232)
2231 - [banners (dependency on banner)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2231)
2230 - [Collection Link, Accordion, et al](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2230)
2229 - [OMB & Back to Top (dependency on button)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2229)
