### ISSUE TITLE
Figma Component Rebuild: Checkbox and Radio buttons

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2136]
## Description
We have to rebuild our components in Figma since they do not transition well from Sketch. This is the [list of components we will need to rebuild](https://docs.google.com/spreadsheets/d/1KVANmign6_HofQGkX_sYJeamsFe_9X9z6WWpJ030zq8/edit?usp=sharing). The goal with rebuilding the components is to make them as reactive as possible using auto layout and properties.

Form fields to create in this ticket:

- [x] Radio Button 
- [x] Checkbox

Each of the form fields will need hover states, error states, and any special states that apply to that specific form field. Look at the instance in [storybook](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default) and also in [Sketch](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4) to make sure all states are able to be shown in the Figma component. 

## Details

Compare the different options for importing the component to the VADS component library. Below are some different sources that might help you rebuild the component in the VADS component library. You will need developer help to import using story.to.design Plugin

- [Truss USWDS library](https://www.figma.com/community/file/836611771720754351)
- [Story.to.design Ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1990)
- [VES Component Library](https://www.figma.com/file/YoxxGwySGwSbFIkajc0vuO/VA-Design-System?type=design&node-id=0%3A1&mode=design&t=hlWGk2fLGnGav5l9-1)

Ideally, it would be nice to think of all the form fields as atom elements that can be used for multiple form fields. Think of the label, error fields, and hint texts as something that will be used in multiple places. How can we set up these different form fields to be resilient to future updates and changes?

## Tasks

- [x]  Pull in component design from either Truss (USWDS), story.to.design, or the VES component library
- [x]  Break component to rebuild
- [x]  Link to variable tokens
- [x]  Add auto layout
- [x]  Determine which Properties to add to design (Variants, Boolean, Instance swap and text)
- [x]  Test the component (Try to break component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch

- [x]  Reviewed by other DS designer
- [ ]  Review by PO?

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2136?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady I looked it over and didn't see any issues. Looks good to me!

**Comment by caw310** [comment]
Carrying over as review needed
