### ISSUE TITLE
Header - a11y Documentation for not turning headers into links in most contexts

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2146]
## Description
Update guidance on headings in the typography section and for Link to state that headings that are also links are to be avoided in the normal flow of text. An exception can be made for Cards where there is limited space. See this [slack thread](https://dsva.slack.com/archives/C023ZKDJJK1/p1688595889940609) for more details. 

## Tasks
- [ ] Update Link component documentation and Typography documentation for design.va.gov
- [ ] Request documentation draft review

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by caw310** [comment]
@rsmithadhoc , would you please draft guidance for Matt to post?
