### ISSUE TITLE
va-radio & va-checkbox: Document headers inside of labels - when to use and when not to use

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2151]
## Description
The va-radio and va-checkbox-group components support the option of using a header inside their top-level label:
https://design.va.gov/storybook/?path=/docs/uswds-va-radio--label-header
https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--label-header

It's also an option in v1. We need to document this option in va-checkbox-group

## Details
Add [details from Jeana](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2078#issuecomment-1743566807) on when and when not style a label as a header. This will also need to touch on fieldsets, legends, aria-labelledby, et. al. Ideally this would also show annotated examples and connect to templates for the One Thing Per Page content principle that we are using now within our forms.

## Tasks
- [ ] Update va-checkbox-group component documentation for design.va.gov
- [ ] Update accessibility guidance on labels inside of headers
- [ ] Add annotated examples of various "One thing per page" scenarios in Template - Forms
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Guidance is published on design.va.gov

**Comment by jeana-adhoc** [comment]
Just adding a note here that I think I might be taking care of this when I merge this [draft documentation](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Accessibility/heading-legends.md) into the [Accessibility Cookbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/accessibility-cookbook.md).

We can point to the cookbook from various VADS pages as needed.

**Comment by humancompanion-usds** [comment]
From @jeana-adhoc:

### Content updates
* [Headings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#headings-and-accessibility-best-practices) 
  * Update https://design.va.gov/content-style-guide/plain-language/structure-your-content and replace the heading screenshots with this cookbook article
* [Buttons vs Links](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#choose-the-right-element-buttons-vs-links)
  * Expand https://design.va.gov/components/link/action#links-vs-buttons

#### NEW Expand Accessibility Section on platform in developer doc area

Current url: https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-testing

* We should remove "testing" from the url because it won't all be testing
* Add these cookbook articles
  * [When to use ARIA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#when-to-use-aria)
  * [Visually hidden link / button text best practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#visually-hidden-link--button-text-best-practices)

#### NEW Add pages to [design.va.gov/about/accessibility/](http://design.va.gov/about/accessibility/) And point relevant component and pattern guidance to these accessibility considerations

* [Fieldsets, Legends, Labels](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#visually-hidden-link--button-text-best-practices)
* [When a screen reader needs to announce content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#when-a-screen-reader-needs-to-announce-content)

**Comment by jeana-adhoc** [comment]
Good call out. I'll see what I can do about both.  Maybe simplify the html in the codepen for visuals only (doesn't need to render workable code) The videos were really impactful for teams to understand what's happening.

**Comment by jeana-adhoc** [comment]
Just adding a note of where all these cookbook pieces end up. I'll update it as more gets moved/published


| Cookbook article | New Location  |
| ----------------- | -------------- |
| [Buttons vs Links](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#choose-the-right-element-buttons-vs-links) | [Choose the right element (Button)](https://design.va.gov/components/button/#choose-the-right-element-buttons-vs-links), [Choose the right element (Link)](https://design.va.gov/components/link/#choose-the-right-element-buttons-vs-links) |
| [Fieldsets, legends, labels](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#visually-hidden-link--button-text-best-practices)  | [Fieldsets, legends, and labels](https://design.va.gov/components/form/#fieldsets-legends-and-labels) in the form section of components|

**Comment by jeana-adhoc** [comment]
Yes! these are fully integrated into VADS and platform now


| Cookbook article | New Location  |
| ----------------- | -------------- |
| [Buttons vs Links](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#choose-the-right-element-buttons-vs-links) | [Choose the right element (Button)](https://design.va.gov/components/button/#choose-the-right-element-buttons-vs-links), [Choose the right element (Link)](https://design.va.gov/components/link/#choose-the-right-element-buttons-vs-links) |
| [Fieldsets, legends, labels](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#visually-hidden-link--button-text-best-practices)  | [Fieldsets, legends, and labels](https://design.va.gov/components/form/#fieldsets-legends-and-labels) in the form section of components|
| [Headings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#headings-and-accessibility-best-practices) | [Structure your content](https://design.va.gov/content-style-guide/plain-language/structure-your-content#headings) |
| [When a screen reader needs to announce content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#when-a-screen-reader-needs-to-announce-content) | [When a screen reader needs to announce content](https://design.va.gov/about/accessibility/when-a-screen-reader-needs-to-announce-content) |
| [Visually hidden links / button text best practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#visually-hidden-link--button-text-best-practices) |[Visually hidden links and button best practices](https://depo-platform-documentation.scrollhelp.site/developer-docs/visually-hidden-link-and-button-text-best-practice) |
| [When to use ARIA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#when-to-use-aria) | [When to use ARIA](https://depo-platform-documentation.scrollhelp.site/developer-docs/when-to-use-aria)|
