### ISSUE TITLE
New Tokens Needed

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2154]
## Description
New tokens needed for:
- [x] Input Prefix Color
- [x] Input Suffix Color
- [x] Input Border Color
- [x] Input Background Color?
- [ ] Page background Color?
- [x] Alternate button colors (green button)

Color tokens
- [x] $color-orange
- [x] $color-green-light
- [x] $color-black

## Tasks
- [ ] Create new tokens in Airtable

## Acceptance Criteria
- [ ] Tokens are viewable in Airtable

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2154?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by humancompanion-usds** [comment]
* color-orange should be dropped from Figma.
* color-black is on row 19 in AT.
* color-green-light - vads-color-gree-light is on row 43 in AT

* Input Border Color: vads-input-border-color-on-light is on row 87 in AT
* Input prefix color: Added vads-input-prefix-color-text-on-light for text and vads-input-prefix-color-fill-on-light for icon fills.
* Input suffix color: Added vads-input-suffix-color-text-on-light

**Comment by humancompanion-usds** [comment]
@danbrady - Okay, I've added button component tokens. Notably for the primary-alt (green) button. This required updated the vads-color-green-dark and darker tokens and removing the darkest token. The USWDS scale is generally color, color-dark, color-darker. They dropped the "darkest" throughout.

vads-button-color-background-primary-alt-on-light = vads-color-green
vads-button-color-background-primary-alt-hover-on-light = vads-color-green-dark
vads-button-color-background-primary-alt-active-on-light = vads-color-green-darker

vads-color-green = uswds-system-color-green-cool-50v - #008817
vads-color-green-dark = uswds-system-color-green-cool-60v - #216e1f
vads-color-green-darker = uswds-system-color-green-cool-70v - #154c21

**Comment by danbrady** [comment]
@humancompanion-usds Ok, added those variables to Figma and updated the values in the "Figma Value" column in [AirTable](https://airtable.com/appF4FJKBeNVNGrlm/tblVoDslTYpAh7dr1/viw5VK18YcZe6E4vq?blocks=hide) with what's currently in Figma. 

FYI: I noticed that Figma exports any hex or rgba color value as the 8-digit hex code equivalant. For example, `rgba(27,27,27,.3) = #1b1b1b4d` and `#ffffff = #ffffffff`.

**Comment by humancompanion-usds** [comment]
@danbrady - Should we keep this open or are we okay to close?
