### ISSUE TITLE
Additional Info Vertical bar Width Update - Design

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2156]
## Description
The vertical, blue bar in the expanded Additional Info component is currently 7px in the sketch pattern library as well as in the developed component. Upon discussions with @humancompanion-usds, we decided this should be updated to 4px to align better with our sizing scale.

Sketch Component Library:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/4f6b7ddd-796f-472a-a02a-c97785f85ddf)

Component:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/8e7ec12e-2d7a-45df-b9a2-bce4195e54c7)
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/72e304fa-cf43-4c8a-9f34-fc96dfab9ade)

## Tasks
- [ ] Update Sketch library
- [ ] Update web component

## Acceptance Criteria
- [ ] Validate all instances in Sketch library are correctly sized
- [ ] Validate all instances in web component are correctly sized

**Comment by caw310** [comment]
@danbrady is this still needed?

**Comment by babsdenney** [comment]
This was [updated in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=203-1254) already, I created a PR to update this in the component-library. Here is the [PR](https://github.com/department-of-veterans-affairs/component-library/pull/1638).
