### ISSUE TITLE
Create report with data with use of v3 version of the components.

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2157]
## Description
We need to get usage of v3 components. This data should be added to the component usage report in DOMO. 

## Details
If we cannot add this data easily within the time frame that this information is needed, run a manual report to pull this information. 

## Tasks
- [ ] Update component usage report to include v3 components
- [ ] Show a draft to Matt, Micah and Carol for review
- [ ] Make any necessary edits. 

## Acceptance Criteria
- [ ] Domo component usage report includes v3 components

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2157?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010

**Comment by micahchiang** [comment]
Weird, I thought I left a comment on this with an update. In any case, there's a link to the PR associated with this ticket that adds support to search for components using the `uswds` prop. Running the report today yields these results: 

```
VaTextInput: 5
    Request a Board Appeal: 2
    Platform(ish): 1
    DS Playground: 1
    DS V3 Playground: 1

VaMemorableDate: 2
    Request a Board Appeal: 1
    Platform(ish): 1

va-button: 6
    Request a Board Appeal: 5
    Platform(ish): 1

VaCheckboxGroup: 4
    Request a Board Appeal: 1
    DS Playground: 1
    DS V3 Playground: 1
    Platform(ish): 1

va-checkbox: 6
    Request a Board Appeal: 1
    Find a Local Representative: 3
    Simple Forms Patterns: 1
    Platform(ish): 1

va-telephone: 6
    Request a Board Appeal: 6

VaModal: 4
    Request a Board Appeal: 1
    DS Playground: 1
    DS V3 Playground: 1
    Financial Status Report: 1

VaRadio: 3
    Request a Board Appeal: 1
    DS Playground: 1
    DS V3 Playground: 1

va-radio-option: 5
    Request a Board Appeal: 2
    Platform(ish): 3

va-on-this-page: 2
    Request a Board Appeal: 2

VaPrivacyAgreement: 2
    Request a Board Appeal: 2

va-segmented-progress-bar: 3
    Request a Board Appeal: 1
    Mock Form - Alternate header - 21-0845 Authorization to Disclose Personal Information to a Third Party: 1
    Platform(ish): 1

VaBreadcrumbs: 2
    Request a Board Appeal: 1
    DS Playground: 1

va-featured-content: 1
    Request a Board Appeal: 1

va-process-list: 2
    Request a Board Appeal: 1
    Request a Presidential Memorial Certificate: 1

va-additional-info: 14
    Request a Board Appeal: 4
    Platform(ish): 3
    Financial Status Report: 6
    Find a Local Representative: 1

va-omb-info: 1
    Request a Board Appeal: 1

va-alert: 15
    Request a Board Appeal: 1
    Claims Status: 1
    10-10EZR Update health benefits info form: 7
    Financial Status Report: 2
    MHV Medications: 1
    Static pages: 1
    VA online services terms of use: 2

va-accordion: 2
    Platform(ish): 1
    Pre-check-in: 1

va-accordion-item: 2
    Platform(ish): 1
    Pre-check-in: 1

VaNumberInput: 2
    DS Playground: 1
    DS V3 Playground: 1

VaSelect: 2
    DS Playground: 1
    DS V3 Playground: 1

VaRadioOption: 6
    DS Playground: 3
    DS V3 Playground: 3

VaCheckbox: 7
    DS Playground: 3
    DS V3 Playground: 3
    VA Profile: 1

VaButton: 2
    DS Playground: 1
    DS V3 Playground: 1

VaAlert: 24
    DS Playground: 12
    DS V3 Playground: 12

VaSegmentedProgressBar: 2
    DS Playground: 1
    DS V3 Playground: 1

VaAdditionalInfo: 2
    DS Playground: 1
    DS V3 Playground: 1

VaAccordion: 1
    DS Playground: 1

VaAccordionItem: 3
    DS Playground: 3

VaProcessList: 2
    DS Playground: 1
    DS V3 Playground: 1

va-table: 1
    Financial Status Report: 1

va-checkbox-group: 1
    Find a Local Representative: 1

Total: 142
```

So as of 10/16/2023 there are 142 instances of design system components on USWDSv3 settings, and 2315 web components instances in total, which gives us about 6.6% usage today.

**Comment by micahchiang** [comment]
Reached out to platform analytics for direction on integrating a new query into BigQuery and Domo - https://dsva.slack.com/archives/CKCRMLGAC/p1697493394318429

**Comment by humancompanion-usds** [comment]
@micahchiang - Can you take the DS Playground out of the count? Thanks. This is very helpful data.

**Comment by caw310** [comment]
@micahchiang , is it possible to get the number of applications using v3 components?

**Comment by micahchiang** [comment]
@humancompanion-usds here are the numbers and breakdown without the ds playgrounds included:

```
VaTextInput: 3
    Request a Board Appeal: 2
    Platform(ish): 1

VaMemorableDate: 2
    Request a Board Appeal: 1
    Platform(ish): 1

va-button: 6
    Request a Board Appeal: 5
    Platform(ish): 1

VaCheckboxGroup: 2
    Request a Board Appeal: 1
    Platform(ish): 1

va-checkbox: 6
    Request a Board Appeal: 1
    Find a Local Representative: 3
    Simple Forms Patterns: 1
    Platform(ish): 1

va-telephone: 6
    Request a Board Appeal: 6

VaModal: 2
    Request a Board Appeal: 1
    Financial Status Report: 1

VaRadio: 1
    Request a Board Appeal: 1

va-radio-option: 5
    Request a Board Appeal: 2
    Platform(ish): 3

va-on-this-page: 2
    Request a Board Appeal: 2

VaPrivacyAgreement: 2
    Request a Board Appeal: 2

va-segmented-progress-bar: 3
    Request a Board Appeal: 1
    Mock Form - Alternate header - 21-0845 Authorization to Disclose Personal Information to a Third Party: 1
    Platform(ish): 1

VaBreadcrumbs: 1
    Request a Board Appeal: 1

va-featured-content: 1
    Request a Board Appeal: 1

va-process-list: 2
    Request a Board Appeal: 1
    Request a Presidential Memorial Certificate: 1

va-additional-info: 14
    Request a Board Appeal: 4
    Platform(ish): 3
    Financial Status Report: 6
    Find a Local Representative: 1

va-omb-info: 1
    Request a Board Appeal: 1

va-alert: 15
    Request a Board Appeal: 1
    Claims Status: 1
    10-10EZR Update health benefits info form: 7
    Financial Status Report: 2
    MHV Medications: 1
    Static pages: 1
    VA online services terms of use: 2

va-accordion: 2
    Platform(ish): 1
    Pre-check-in: 1

va-accordion-item: 2
    Platform(ish): 1
    Pre-check-in: 1

va-table: 1
    Financial Status Report: 1

VaCheckbox: 1
    VA Profile: 1

va-checkbox-group: 1
    Find a Local Representative: 1

Total: 81
```

@caw310: Here is the number of applications using v3 components and their names:
```
platform_ish_, 
request_a_board_appeal, 
total, simple_forms_patterns, 
find_a_local_representative, 
financial_status_report, mock_form___alternate_header___21_0845_authorization_to_disclose_personal_information_to_a_third_party, request_a_presidential_memorial_certificate, 
va_online_services_terms_of_use, static_pages, 
mhv_medications, 
_10_10ezr_update_health_benefits_info_form, 
claims_status, 
pre_check_in, 
va_profile

total: 13
```

**Comment by micahchiang** [comment]
@humancompanion-usds - for getting v3 component usage data into BigQuery and Domo, what information are you looking for? Are you looking for just total count of each v3 component, or a further breakdown into which applications are on v3?

**Comment by humancompanion-usds** [comment]
I'll take whatever I can get! Ideally both, but a total count is a great start.

**Comment by caw310** [comment]
Carrying over into the next sprint as the data was manually pulled but DOMO still needs to be setup.

**Comment by caw310** [comment]
@micahchiang , could you pull this info manually once a week - maybe on Fridays until it's set up in DOMO?

**Comment by micahchiang** [comment]
@caw310 - yeah, we can do that. If we want to, we can close this ticket and write another one for the domo work, since it requires collaboration with analytics and insights. The report can be run from the command line already 👍
