### ISSUE TITLE
Design for expanding group 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2161]
## Description
There are a few instances of the Expanding Group React component that need to be replaced. The DST will not be building an expanding group web component so we need a design using existing DS components that can be used in place of the expanding group. 

## Tasks
- [ ] Work with engineer to get links to pages where expanding group is currently used
- [ ] Create a design using DS components as a replacement
- [ ] Review with PO, other designers to get feedback and input
- [ ] Make necessary edits
- [ ] Review with accessibility specialist and engineers 
- [ ] Share final design assets with engineers / or add to the development ticket

## Acceptance Criteria
- [ ] Created a design to replace expanding group

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2161?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
@caw310 Where can I see this component?

**Comment by caw310** [comment]
@micahchiang , would you be able to provide links to examples of expanding group?

**Comment by caw310** [comment]
Closing as not needed.
