### ISSUE TITLE
Figma Component Rebuild: Adding USWDS icons

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2163]
## Description
The Font Awesome icons were already added to the Figma component library but the new MVP and V3 components use a mixture of both. For example, most of the MVP components are using the Font Awesome but the MVP alerts are using the USWDS, the select dropdown, and the radio buttons are using USWDS. We need to add the USWDS to VADS Figma component library as a separate collection or styles from the Font Awesome library so that the Designer will have both icon sets to choose from when rebuilding or creating components. 

## Details
- [USWDS icons in Sketch](https://www.sketch.com/s/59d7aef5-4fbe-4904-bc92-2e1a7b28ea29/p/92FDF2C3-B0FD-4B77-B1DA-512D95C4714C/canvas)
- Font Awesome icons in Figma (add link)

## Tasks
- [x] Import icons from Sketch to Figma
- [x] Add icons to styles in Figma

## Acceptance Criteria
- [x] Reviewed by other DS designer
- [ ] Review by PO
