### ISSUE TITLE
Inconsistent treatment of form element hint text in error state

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2164]
## Description
The text treatment of the hint text when the component is in an error state is inconsistent between form elements. Some times it's bold, sometimes it's not. 

Textarea:
![Screenshot 2023-10-05 at 2 35 16 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/b509ebed-e62e-435f-8ed7-cecaa47f1e6a)

Select:
![Screenshot 2023-10-05 at 2 33 58 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/434fedae-9c53-4e1f-b6ef-28d2402b4501)

## Tasks
- [x] Conduct small audit on all components with error states and hint text in Storybook
- [x] Conduct small audit on all components with error states and hint text in Sketch/Figma
- [x] Determine correct approach
- [x] Validate with PO/Accessibility/Others
- [x] Check if screenshots need to be updated
- [x] Update Figma/create branches
- [x] Review & merge Figma Branches
- [ ] Engineering: Update telephone-input, text-input and memorable-date

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Screenshots in [Component Library > File Input](https://design.va.gov/components/form/file-input#single-file-error) are updated

**Comment by LWWright7** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2164?planning-poker) with Zenhub @danbrady

**Comment by Mottie** [comment]
Somewhat related... if you add a `label-header-level` property to `va-textarea`, the hint is also inside and remains bold all the time

<img width="1094" alt="Image" src="https://github.com/user-attachments/assets/73bf9f04-dffc-461a-a430-ffde9ebd84ce" />

**Comment by caw310** [comment]
@danbrady is this still needed?

**Comment by caw310** [comment]
Storybook  need to be updated for telephone-input, text-input and memorable-date - all need updating.
