### ISSUE TITLE
Figma Component Rebuild: Crisis line modal

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2167]
## Description
We have to rebuild our components in Figma since they do not transition well from Sketch. This is the [list of components we will need to rebuild](https://docs.google.com/spreadsheets/d/1KVANmign6_HofQGkX_sYJeamsFe_9X9z6WWpJ030zq8/edit?usp=sharing). The goal with rebuilding the components is to make them as reactive as possible using auto layout and properties.

Form fields to create in this ticket:
- [ ] [Crisis line modal](https://design.va.gov/components/modal#crisis-line-modal)

## Details
Compare the different options for importing the component to the VADS component library. Below are some different sources that might help you rebuild the component in the VADS component library. You will need developer help to import using story.to.design Plugin

- [Truss USWDS library](https://www.figma.com/community/file/836611771720754351)
- [Story.to.design Ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1990)
- [VES Component Library](https://www.figma.com/file/YoxxGwySGwSbFIkajc0vuO/VA-Design-System?type=design&node-id=0%3A1&mode=design&t=hlWGk2fLGnGav5l9-1)

Make sure to include all variations on states. 

## Tasks
- [ ]  Pull in component design from either Truss (USWDS), story.to.design, or the VES component library, or build from scratch
- [ ]  Break component to rebuild (if necessary)
- [ ]  Link to variable tokens
- [ ] Link to styles and icons
- [ ]  Add auto layout
- [ ]  Determine which Properties to add to design (Variants, Boolean, Instance swap and text)
- [ ]  Test the component (Try to break component)

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by danbrady** [comment]
I think this can be achieved as an example of a default modal with custom content and not a new component. I set it up in the [figma example file](https://www.figma.com/file/JDFpGLIojfuQwANXScQjqe/VADS-Example-Library?type=design&node-id=230%3A6782&mode=design&t=prWWJPzhcaiFlpIY-1).

**Comment by danbrady** [comment]
I'm reopening this issue because we have to create the button that launches the modal. An instance of that button needs to go into the Header.
