### ISSUE TITLE
Figma Component Rebuild: Footer

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2169]
## Description
We have to rebuild our components in Figma since they do not transition well from Sketch. This is the [list of components we will need to rebuild](https://docs.google.com/spreadsheets/d/1KVANmign6_HofQGkX_sYJeamsFe_9X9z6WWpJ030zq8/edit?usp=sharing). The goal with rebuilding the components is to make them as reactive as possible using auto layout and properties.

Component to create in this ticket:
- [ ] [Footer](https://www.sketch.com/s/f5f91c9c-f5c5-41f6-8e7e-6cfe003299fa)

Note: Please verify this is the best source for the Sketch. There might be a better source to start with the header. This one might be a good option to import from code. 

## Details
Compare the different options for importing the component to the VADS component library. Below are some different sources that might help you rebuild the component in the VADS component library. You will need developer help to import using story.to.design Plugin

- [Truss USWDS library](https://www.figma.com/community/file/836611771720754351)
- [Story.to.design Ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1990)
- [VES Component Library](https://www.figma.com/file/YoxxGwySGwSbFIkajc0vuO/VA-Design-System?type=design&node-id=0%3A1&mode=design&t=hlWGk2fLGnGav5l9-1)

Make sure to include all variations on states. 

## Tasks
- [ ]  Pull in component design from either Truss (USWDS), story.to.design, or the VES component library
- [ ]  Break component to rebuild (if necessary)
- [ ]  Link to variable tokens
- [ ] Link to styles and icons
- [ ]  Add auto layout
- [ ]  Determine which Properties to add to design (Variants, Boolean, Instance swap and text)
- [ ]  Test the component (Try to break component)

## Acceptance Criteria
- [x] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Changing to stretch due to people being out sick

**Comment by danbrady** [comment]
@LWWright7 Ready for testing!
[Footer](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=1702%3A14515&mode=design&t=nsApJFZPNViL5wwo-1) (Includes desktop, mobile, and minimal.)

**Comment by LWWright7** [comment]
@danbrady This looks good! Ready to go!
