### ISSUE TITLE
Figma Component Rebuild: Date input

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2174]
## Description
We have to rebuild our components in Figma since they do not transition well from Sketch. This is the [list of components we will need to rebuild](https://docs.google.com/spreadsheets/d/1KVANmign6_HofQGkX_sYJeamsFe_9X9z6WWpJ030zq8/edit?usp=sharing). The goal with rebuilding the components is to make them as reactive as possible using auto layout and properties.

Component to create in this ticket:
- [ ] [Date input](https://design.va.gov/components/form/date-input)

## Details
Compare the different options for importing the component to the VADS component library. Below are some different sources that might help you rebuild the component in the VADS component library. You will need developer help to import using story.to.design Plugin

- [Truss USWDS library](https://www.figma.com/community/file/836611771720754351)
- [Story.to.design Ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1990)
- [VES Component Library](https://www.figma.com/file/YoxxGwySGwSbFIkajc0vuO/VA-Design-System?type=design&node-id=0%3A1&mode=design&t=hlWGk2fLGnGav5l9-1)

Make sure to include all variations on states. 

## Tasks
- [ ]  Pull in component design from either Truss (USWDS), story.to.design, or the VES component library
- [ ]  Break component to rebuild (if necessary)
- [ ]  Link to variable tokens
- [ ] Link to styles and icons
- [ ]  Add auto layout
- [ ]  Determine which Properties to add to design (Variants, Boolean, Instance swap and text)
- [ ]  Test the component (Try to break component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If code and Sketch aren't aligned, follow what's in code first.

- [ ]  Reviewed by other DS designer
- [ ]  Review by PO?

**Comment by LWWright7** [comment]
@danbrady Looks good! I don't see any issues.  Ready for Matt.
