### ISSUE TITLE
Figma Component Rebuild: Process list

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2175]
## Description
We have to rebuild our components in Figma since they do not transition well from Sketch. This is the [list of components we will need to rebuild](https://docs.google.com/spreadsheets/d/1KVANmign6_HofQGkX_sYJeamsFe_9X9z6WWpJ030zq8/edit?usp=sharing). The goal with rebuilding the components is to make them as reactive as possible using auto layout and properties.

Component to create in this ticket:
- [x] [Process list](https://design.va.gov/components/process-list)

**Note:** 
Design update - A color change is needed from a staging review. You can read more about the details in this ticket. 

[Design System Staging Review - Accessibility Feedback - Accordion, Process List and Privacy Agreement](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65235)

From the ticket:

> Must: Pending items are gray-light (#aeb0b5), which against a white background has a contrast ratio of 2.17:1. There are probably scenarios where a user will want to read what the pending steps are (if not, why include them at all?) and that contrast level will exclude at least some low vision users. If we can bump that up to gray-medium (#757575) that gets us to 4.6:1, which meets WCAG AA requirements.

## Details
Compare the different options for importing the component to the VADS component library. Below are some different sources that might help you rebuild the component in the VADS component library. You will need developer help to import using story.to.design Plugin

- [Truss USWDS library](https://www.figma.com/community/file/836611771720754351)
- [Story.to.design Ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1990)
- [VES Component Library](https://www.figma.com/file/YoxxGwySGwSbFIkajc0vuO/VA-Design-System?type=design&node-id=0%3A1&mode=design&t=hlWGk2fLGnGav5l9-1)

Make sure to include all variations and states. 

## Tasks
- [x]  Pull in component design from either Truss (USWDS), story.to.design, or the VES component library
- [x]  Break component to rebuild (if necessary)
- [x]  Link to variable tokens
- [x] Link to styles and icons
- [x]  Add auto layout
- [x]  Determine which Properties to add to design (Variants, Boolean, Instance swap and text)
- [x]  Test the component (Try to break component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If code and Sketch aren't aligned, follow what's in code first.

- [x]  Reviewed by other DS designer
- [ ]  Review by PO

**Comment by danbrady** [comment]
@LWWright7 Have at it!

Process List ([Component](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=798%3A1778&mode=design&t=nuHXaHv6SPo8TLxm-1), [Examples](https://www.figma.com/file/JDFpGLIojfuQwANXScQjqe/VADS-Example-Library?type=design&node-id=396%3A9&mode=design&t=ZmMWrjk4BMHkGy4x-1))
