### ISSUE TITLE
Figma Component Rebuild: Link

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2181]
## Description
We have to rebuild our components in Figma since they do not transition well from Sketch. This is the [list of components we will need to rebuild](https://docs.google.com/spreadsheets/d/1KVANmign6_HofQGkX_sYJeamsFe_9X9z6WWpJ030zq8/edit?usp=sharing). The goal with rebuilding the components is to make them as reactive as possible using auto layout and properties.

Component to create in this ticket:
- [x] [Link](https://design.va.gov/components/link/)

## Details
Compare the different options for importing the component to the VADS component library. Below are some different sources that might help you rebuild the component in the VADS component library. You will need developer help to import using story.to.design Plugin

- [Truss USWDS library](https://www.figma.com/community/file/836611771720754351)
- [Story.to.design Ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1990)
- [VES Component Library](https://www.figma.com/file/YoxxGwySGwSbFIkajc0vuO/VA-Design-System?type=design&node-id=0%3A1&mode=design&t=hlWGk2fLGnGav5l9-1)

Make sure to include all variations and states. 

## Tasks
- [x]  Pull in component design from either Truss (USWDS), story.to.design, or the VES component library
- [x]  Break component to rebuild (if necessary)
- [x]  Link to variable tokens
- [x] Link to styles and icons
- [x]  Add auto layout
- [x]  Determine which Properties to add to design (Variants, Boolean, Instance swap and text)
- [x]  Test the component (Try to break component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If code and Sketch aren't aligned, follow what's in code first.

- [x]  Reviewed by other DS designer
- [ ]  Review by PO

**Comment by LWWright7** [comment]
@babsdenney @danbrady This one is ready for [testing](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=646%3A1271&mode=design&t=U9FBHg4fNGrMXxl0-1)

**Comment by danbrady** [comment]
Looking good! Few minor items:

- [ ] Let's use the Body/Link text style instead of Body/Base. That'll give the text the underline treatment.
- [ ] Let's use the FA icon components instead of the vector shapes. That will keep them a consistent size. (Also, that'll make it easier to swap if we need to.) 
- [ ] The chevron in the active state looks a lot bigger than what's in the component. Can you confirm the icons are the right size? Can you also confirm the spacing between the icon and text? 
- [ ] I think the hover state is missing the background color?

**Comment by babsdenney** [comment]
This is looking great! A lot more variations and states that is necessary. Thank you for making all this. I think the only thing I saw was the text doesn't wrap when the bounding box is changed. Also, the text is centered vs. left-aligned. I think maybe left-aligned might be a more expected behavior for text. This might just be my personal preference though. 
<img width="638" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/4505990/dfcb5e4b-80b4-4623-bb88-00ceecd1ca60">

**Comment by LWWright7** [comment]
@danbrady @babsdenney - OK, I think I've got all these items corrected! thanks for reviewing them :)
