### ISSUE TITLE
Figma Component Rebuild: Linking 3 variables 

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2192]
## Description
We need to link current Figma components that are already in the Figma VADS library to the variables that are already created in the current library. Use the list below to go through and connect the components with the correct variables. 

- [x] Action Link 
- [x] Telephone 
- [x] Loading Indicator 

Look at the components in [storybook](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default) and also in [Sketch](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4) to make sure all the variables are matching the colors and styles.

## Tasks

- [x]  Link to variable tokens
- [x]  Verify these components are setup with auto layout and the correct properties
- [x]  Test the component (Try to break the component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch

- [x]  Reviewed by other DS designer
- [ ]  Review by PO

**Comment by caw310** [comment]
Adding to sprint 38 to do a trial of this with 3 components to determine difficulty.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2192?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@babsdenney @danbrady - [Action Link ](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=199%3A1227&mode=design&t=3BJKntmCJsiXL7rU-1)is ready for QA. For "Reverse" I wasn't sure whether to have one large block for background color or if the way I did it with individual background blocks was the correct way....

**Comment by LWWright7** [comment]
@danbrady @babsdenney - [Action Link](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=199%3A1227&mode=design&t=MYGxryEeAJATRhoI-1) is ready for QA!

**Comment by danbrady** [comment]
@LWWright7 Looking good! A few minor things:
* Let's hook up to the typography styles we have set up
* There's a few colors being used that we have tokens set 
* The focus ring for the focus state looks a little bit thicker than others
* It looks like there's an individual text property for every variation. Since the text is the same for all variations, that can be a single "Text" property, no? (Doing so will maintain the text if a designer switches the properties.)

**Comment by LWWright7** [comment]
Just need OK from @humancompanion-usds (Matthew Dingee) on this one...
