### ISSUE TITLE
Figma rebuild: Foundation pages

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2193]
## Description
Creating the foundational pages in Figma. Pages to recreate from Sketch to Figma.

- [ ] Grids page
- [ ] Typography page
- [ ] Templates page
- [ ] Colors page

## Details

- [Sketch Grids page
- ](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/3E55BC1C-08E9-4B5A-A740-4B18360638C8/canvas)
- [Sketch colors page
- ](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/E1D23FB1-06B7-464B-86FF-033014922A6D/canvas)
- [Sketch typography page
- ](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/C280FEA6-F279-4BCB-898C-42BCBFC6B808/canvas)

## Tasks
- [ ]  Pull in component design from either Truss (USWDS), story.to.design, or the VES component library
- [ ]  Break component to rebuild (if necessary)
- [ ]  Link to variable tokens
- [ ] Link to styles and icons
- [ ]  Add auto layout
- [ ]  Determine which Properties to add to design (Variants, Boolean, Instance swap and text)
- [ ]  Test the component (Try to break component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Review by PO

**Comment by babsdenney** [comment]
This ticket might need to broken out into seperate tickets to address each foundational page to be looked at in greater detail. We will need to finalize tokens and typography styles before completing this ticket.

**Comment by LWWright7** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2193?planning-poker) with Zenhub @danbrady

**Comment by humancompanion-usds** [comment]
We have colors, grid, logos, and typography. @danbrady - Is there more work to be done here?

I do find it a little odd that these foundational elements are in the Component Library but not the Examples, where we had them in Sketch. Mainly because I'm fine with folks opening the Examples library as often as they want but, generally we want folks to stay out of Component Library.

**Comment by danbrady** [comment]
I think this issue was created before we broke down each page into their own issue. So I think we can close this one.

There are additional foundational items that I don't think existed in Sketch before but we could consider adding: breakpoints, spacing units, border radii, elevation/shadow (although not much here).

Regarding the placement, there might have been some confusion about the correct placement of these foundational items. Looking back at sketch, it looks like they [were](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/p/C258CA59-FCB5-4B73-A4AA-723ACA440299/canvas) [in](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/3E55BC1C-08E9-4B5A-A740-4B18360638C8/canvas) [every](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/3C1D41FC-679C-4A2F-8D77-881FB204A664/canvas) [file](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/p/C258CA59-FCB5-4B73-A4AA-723ACA440299/canvas). 😄 It shouldn't be much effort to move these to the Example library if we want. It would be easier to maintain if we keep them in one place. However, we have to be sure to not move any main components that are defined in Component library to a different file. (I think this only applies to the Logos.)
