### ISSUE TITLE
Switch any non v3 components to use USWDS icons

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2198]
## Description
All VA design system components should use USWDS icons. 
Ticket[ 2577 ]([#2577 Remove Font Awesome icon overrides in USWDS components](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2577)) updated v3 components with USWDS icons. 
Any non v3 components need to be using USWDS icons.

## Details
These are the components which are known to need converting:
- [x] va-accordion-item (e2e tests)
- [x] va-alert (v1, but used by va-banner)
- [x] va-alert-expandable
- [x] va-back-to-top
- [x] va-link
- [x] va-maintenance-banner
- [x] va-modal
- [ ] va-notification (Deprecated, so skipping for now)
- [x] va-on-this-page
- [x] va-promo-banner
- [x] va-search-input

## Tasks
- [X] audit  components with icons to identify which are not using USWDS icons (most likely non v3 components) 
- [X] create a list of the components that are NOT using USWDS v3 icons
- [x] Update those components with USWDS v3 icons
- [ ] Have designer and/or PO review and approve

## Acceptance Criteria
- [ ] All components are using USWDS v3 icons

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2198?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
Quick search in web-components shows ~53 font awesome instances, but a lot of these are either in e2e tests or v1 components.
