### ISSUE TITLE
Figma Rebuild - Typography styles

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2203]
## Description
We need to add more typography styles to Figma to account for different variations. Here is a current list but this might not be complete. Please add more styles that you feel are needed. 

- [x] Headers
- [x] Body styles
- [x] Mobile styles
- [x] Ordered/unordered list styles
- [x] Utility font sizes

## Details

- [Figma Typography styles](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=402%3A4850&mode=design&t=C9JiKMuyMeq2cYFW-1)
- [Typography styles on VADS](https://design.va.gov/foundation/typography)

## Tasks
- [x] Add typography styles to Figma
- [x] Document styles added in Figma to this ticket so we can look at what tokens might be needed in the future

## Acceptance Criteria

- [ ]  Reviewed by other DS designer
- [ ]  Review by PO

**Comment by danbrady** [comment]
Updated list with text styles.

@babsdenney @LWWright7 This is ready for review. (There are no components, just text styles.)
