### ISSUE TITLE
Alert - Add "Sign In To Start Your Application" variation that is for auth-only

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2211]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add Design System component label (such as `va-alert`)
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
We need to add an Alert variation for Sign In To Start Your Application that drops the link that allows users to proceed unauthenticated. Some forms don't allow users to fill out the form unauthenticated. We don't show that option in our Alerts today but, it is valid and a variation used in a few forms. We need to add the variation to Sketch and the guidance so that everyone understands it is valid. We do not need it in Storybook since we already have one of the 3 variations of Sign In To Start Your Application captured there already (and the differences are largely in content).

## Tasks
- [ ] Update Sketch
- [ ] Update Alert component documentation for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is updated on design.va.gov
