### ISSUE TITLE
Font Size utility page has incorrect font families

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2212]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add Design System component label (such as `va-alert`)
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description

The font family for the first column of of examples on the [font size utility page](https://design.va.gov/foundation/utilities/font-size) is incorrect. Both columns are rendering the same font family.

## Details

Screenshot below:
<img width="955" alt="Screenshot of two columns of font sized text" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/169a12e4-23ae-468d-9122-0f21d5ed3b9b">

I believe the the first column should be Bitter (or using the "serif" utility) and the second to be Source Sans (or the "sans-serif" utility).

## Tasks
- [ ] Update utilities used in examples

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by caw310** [comment]
@danbrady is this still needed?

**Comment by danbrady** [comment]
Fixed.
