### ISSUE TITLE
Add service branch images to assets

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2214]
## Description
The mobile and Auth. Experience teams would like us to make the military service branch images available to them. We can grab the images from here: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/site/assets/img 

The files that are used in that folder for the nametag are:
export const SERVICE_BADGE_IMAGE_PATHS = new Map([
  [USA_MILITARY_BRANCHES.army, '/img/vic-army-symbol.png'],
  [USA_MILITARY_BRANCHES.coastGuard, '/img/vic-cg-emblem.png'],
  [USA_MILITARY_BRANCHES.airForce, '/img/vic-air-force-coat-of-arms.png'],
  [USA_MILITARY_BRANCHES.navy, '/img/vic-navy-emblem.png'],
  [USA_MILITARY_BRANCHES.marineCorps, '/img/vic-usmc-emblem.png'],
]);

An image for the Space Force is forthcoming. 

Reach out to Tim Wright to see how the mobile team would like to consume these icons. I'm not sure if they just want the raw PNGs to be somewhere or if they want a sprite or something else.

## Tasks
- [ ] Add SVG images to assets for use by va.gov
- [ ] Add SVG images to assets for use by VA mobile flagship app
- [ ] Add images to Sketch
- [ ] Adds images to guidance for icons

## Acceptance Criteria
- [ ] Military branch icon images are available to everyone

**Comment by aagosto90** [comment]
@humancompanion-usds 
Here's the Space Force logo in a white circle that we agreed on in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67953#issuecomment-1802694686) to be used for the nametag.
![space-force-logo-for-nametag](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/97965610/49757719-12a8-4b79-b7e3-922d7975e14a)
CC @Samara-Strauss @ajakabcin

**Comment by ajakabcin** [comment]
hey @humancompanion-usds just wanted to let you know that the Space Force emblem auth experience developed is now available [here](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/site/assets/img) (`vic-space-force-logo.png`).
