### ISSUE TITLE
Table Deprecation - debt letters, disability benefits, discharge wizard, financial status report

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2216]
## Description
Related to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2045

The following usages of table need to be deprecated:
- https://github.com/department-of-veterans-affairs/vets-website/blob/28ef91a9b9fdd9e18181a9d3be1f53fdc9b70a65/src/applications/debt-letters/components/HistoryTable.jsx#L7
- https://github.com/department-of-veterans-affairs/vets-website/blob/e4a72db68e39eb4dae2360f5dfabc2f813259d9d/src/applications/disability-benefits/all-claims/content/waiveRetirementPay.jsx#L21
- https://github.com/department-of-veterans-affairs/vets-website/blob/e8e475e40e640b957445c5e6eaac4a097c97665f/src/applications/discharge-wizard/components/AnswerReview.jsx#L31
- https://github.com/department-of-veterans-affairs/vets-website/blob/e66872a4d24eb0b552ac55ad4aa7400172fcd933/src/applications/financial-status-report/components/shared/ItemLoop.jsx#L393

## Tasks
- [ ] update the above table usages to `va-table`
- [ ] address any tests that need to be fixed

## Acceptance Criteria
- [ ] Tasks have been completed

**Comment by caw310** [comment]
Moving to next sprint

**Comment by caw310** [comment]
This is a stretch for sprint 40.
