### ISSUE TITLE
[Icons] - Update Accessibility Considerations Documentation

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2226]
## Description

Update [Icons - Accessibility Considerations](https://design.va.gov/foundation/icons#accessibility-considerations) to clarify how to use icons in an accessible way.

## Details

Based on the current page and what I see in the code, I believe we are advising the use of [FontAwesome's web font with CSS](https://fontawesome.com/v5/docs/web/other-topics/webfont-vs-svg#web-fonts-css) and _not_ [FontAwesome's SVG with JavaScript](https://fontawesome.com/v5/docs/web/other-topics/webfont-vs-svg#svg-js). 

**Recommended Structure Changes:**

Here are the steps I advise and included content recommendations below this.

- **Accessibility Considerations** - update bullet points under this heading.
- Remove the _**When to use role="img"**_ section
    - This is not applicable when using the FontAwesome web font. This section may apply to the `IconHelp` examples and might be outdated.
- Remove the _**When to use**_ section
    - This is not applicable when using the FontAwesome web font. This section may apply to the `IconHelp` examples and might be outdated.
- Add a **Using Decorative Icons** section
- Add a **Using Semantic Icons** section
- Remove `IconHelp` examples. I don't see any references to this in the code, it might be an old method of using icons. I included examples inside the usage sections, so I don't believe this is necessary.

**Recommended Content:**

---

> 
> 
> ## Accessibility Considerations
> 
> - Icon usage typically falls into two categories, decorative and semantic.
>     - **Decorative icons** are icons that are only used for visual reinforcement. If these were removed from the page, users would still be able to understand and use the page.
>     - **Semantic icons** are icons that convey meaning, rather than only being decorative. This includes icons without text next to them that are used as interactive elements such as buttons.
> 
> ## Using Decorative Icons
> 
> If your icons are only decorative, manually add an `aria-hidden` attribute to the icon for accessibility.
> 
> ## Using Semantic Icons
> 
> If your icons have semantic meaning, you have to manually add a few things to make it accessible. There are two methods, non-interactive and interactive, so choose the one that suits your use case.
> 
> ### Non-interactive Icons
> 
> Ideally, any icon would also have a visible label associated with it. But if you must use an icon without a visible label, follow the guidance below to make it accessible.
> 
> For icons used on non-focusable elements, manually add the following for accessibility:
>     - `aria-hidden="true"` attribute.
>     - A text-alternative inside of a `<span>` tag. Include a CSS class to visually hide this text, while keeping it visible to assistive technology.
>     - `title` attribute on the icon to provide a tooltip for sighted mouse users.
> 
> ```html
> <i aria-hidden="true" class="fas fa-car" title="Time to complete"></i>
> <span class="sr-only">Time to complete:</span>
> <span>4 minutes</span>
> ```
> 
> ### Interactive Icons
> 
> If an icon is a focusable interactive element, you do not need to add visually hidden alternative text as described above. In this case, an `aria-label` with a text description on the interactive element is sufficient. A `title` attribute can also be added to provide a tooltip for sighted mouse users.
> 
> ```html
> 
> <a href="#" aria-label="View inbox, you have unread messages">
>     View inbox <i aria-hidden="true" class="fas fa-circle"></i>
> </a>
> 
> 
> <a href="#" aria-label="View calendar">
>     <i aria-hidden="true" class="fas fa-calendar" title="View calendar"></i>
> </a>
> ```

---

## Tasks
- [x] Write or update component documentation for design.va.gov
- [x] Coordinate with accessibility specialist to create or update accessibility guidance
- [x] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov
