### ISSUE TITLE
Quality Assurance - Update process and documentation on NPM linking

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2227]
## Description
In order to properly QA design system components, they need to be tested in vets-website which is where they are used the most. Historically, the guide for NPM linking found [here](https://vfs.atlassian.net/wiki/spaces/DST/pages/1929379847/Component+library#How-to-Link-component-library-and-vets-website-repos) has been finicky. We need to find a reliable way to NPM link our local instances of vets website and the component library. 

## Considerations 
- [old npm linking guide](https://vfs.atlassian.net/wiki/spaces/DST/pages/1929379847/Component+library#How-to-Link-component-library-and-vets-website-repos)
- [previous QA process ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1878)

## Tasks
- [ ] Find a way to reliably link vets-website and component library locally for better testing
- [ ] Update the guide linked above

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by jamigibbs** [comment]
@rmessina1010 has done some research on doing this with [Verdaccio](https://verdaccio.org/) that might be a viable alternative to NPM linking. Can you add your steps here, Ray?

**Comment by rmessina1010** [comment]
### Notes on Verdaccio:
Verdaccio can be used to create an NPM locally. We can leverage this to develop an NMP of our USDWS-updated CSS styles. With Verdaccio we can test that the import of said package locally. 
 A think to keep in mind however is that vets-website  uses node 14.15.0 and the LSV of Verdaccio  is not compatible with that version. For our purposes, v.5.5.0 should suffice.
 
### Running Verdaccio  
**CHECK**:
`python3 --version`
If not, install Python3
If not check for Verdaccio, just to be thorough
`verdaccio -v `
If not 5.5.0, 
**install verdaccio**
`yarn global add verdaccio@5.5.0`
(my set up is with yarn, but if you have npm, the equivalent install should work)
**Run verdaccio**
`verdaccio`
Verdaccio should now be running on` localhost:4873`; please note 
**you must have this running in the background when installing/publishing**
**Make a user, choose login**
`npm adduser --registry http://localhost:4873/`
We can make namespace for our packages in the package.json file (in this example I use: @raytest)
At this point, you can opt to set global settings for publishing to verdaccio, however
`npm config set @raytest:registry http://localhost:4873/`
OR It can be done directly on each publish this way:
`npm publish publish --@raytest:registry=http://localhost:4873/`
Not doing either will try to actually publish to npm!

**Comment by jamigibbs** [comment]
After Verdaccio is installed and running from Ray's steps above, I did the following to get my local version of Formation published and installed. 

In the Formation folder:
- make sure the package version is incremented (ie. 7.0.9-rc1)
- run `npm publish --registry http://localhost:4873  `

In the vets-website folder:
- run `yarn config set registry http://localhost:4873`
- run `yarn add -W @department-of-veterans-affairs/formation`

After my packages were published locally, Verdaccio looks like this to me:

![Screenshot 2023-11-06 at 10 16 31 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/2c7a7b0b-4f96-44d7-8ca8-c76288967bd6)

And after adding the local version of formation to vets-website, my yarn-lock linked to the local version:

![Screenshot 2023-11-06 at 10 18 10 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/67172998-4129-4394-9b80-6a48149451da)

**Comment by micahchiang** [comment]
Nice, this is a pretty straightforward process, all things considered! Looks like we may have to remember to revert the registry in vets-website in the event we're submitting a PR that updates formation. Otherwise, this is nice!

**Comment by micahchiang** [comment]
Updated the confluence page with a summary of the steps Ray and Jami added above - https://vfs.atlassian.net/wiki/spaces/DST/pages/1929379847/Component+library#How-to-Link-component-library-and-vets-website-repos-using-Verdaccio
