### ISSUE TITLE
OMB & Back to Top (button component dependency) - Figma component rebuild

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2229]
## Description
We need to link current Figma components that are already in the Figma VADS library to the variables that are already created in the current library. Use the list below to go through and connect the components with the correct variables. 

- [x] OMB Info 
- [x] Back to top 
(dependency on Button component)

Look at the components in [storybook](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default) and also in [Sketch](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4) to make sure all the variables are matching the colors and styles.

## Tasks

- [x]  Link to variable tokens
- [x]  Verify these components are setup with auto layout and the correct properties
- [x]  Test the component (Try to break the component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch

- [x]  Reviewed by other DS designer
- [ ]  Review by PO?

**Comment by caw310** [comment]
Changing this to a stretch item since folks are out sick.

**Comment by danbrady** [comment]
@LWWright7 Ready for your review:
- [ ] OMB Info ([Component](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=199%3A1232&mode=design&t=RTVmAkxyHq881d9V-1), [Examples](https://www.figma.com/file/JDFpGLIojfuQwANXScQjqe/VADS-Example-Library?type=design&node-id=35%3A164&mode=design&t=udpcWKZlhSBgwYRa-1))
- [ ] Back to Top ([Component](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=199%3A1190&mode=design&t=RTVmAkxyHq881d9V-1))

**Comment by LWWright7** [comment]
@danbrady - Done reviewing.  No issues with Back to Top. 1 Comment on OMB info.
