### ISSUE TITLE
Collection Link, Accordion, Privacy Agreement, Progress Bar - Figma component rebuild

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2230]
## Description
We need to link current Figma components that are already in the Figma VADS library to the variables that are already created in the current library. Use the list below to go through and connect the components with the correct variables. 

- [x] Collection Link 
- [x] Accordion 
- [x] US Privacy Agreement 
- [x] Progress Bar 

Look at the components in [storybook](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default) and also in [Sketch](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4) to make sure all the variables are matching the colors and styles.

## Tasks

- [ ]  Link to variable tokens
- [ ]  Verify these components are setup with auto layout and the correct properties
- [ ]  Test the component (Try to break the component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch

- [ ]  Reviewed by other DS designer
- [ ]  Review by PO?

**Comment by LWWright7** [comment]
@danbrady  -  This one is ready for QA! thanks

**Comment by danbrady** [comment]
- [x] US Privacy Agreement
- [x] Progress Bar
- [ ] Accordion: Left comments
- [ ] Link/Collection: Waiting for ready for testing

**Comment by LWWright7** [comment]
- [x] US Privacy Agreement
- [x] Progress Bar
- [x] Accordion: Left comments
- [x] Link/Collection: Ready For Testing!
- [x] Ready for PO

**Comment by caw310** [comment]
Will carry over due to lots of DST folks getting sick. :(

**Comment by danbrady** [comment]
I did some tweaks to the Collection. @LWWright7 should test it but this is close to done.
