### ISSUE TITLE
Copy of Figma Component Rebuild: Linking variables

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2231]
## Description
We need to link current Figma components that are already in the Figma VADS library to the variables that are already created in the current library. Use the list below to go through and connect the components with the correct variables. 

- [ ] Collection Link 
- [ ] Accordion 
- [ ] OMB Info 
- [ ] Back to top 
- [ ] File Input Banner 
- [ ] Maintenance Banner
- [ ] US Privacy Agreement 
- [ ] Progress Bar 
- [ ] Autosave 
- [ ] Address block 
- [ ] Penalty Notice 
- [ ] Prefill 
- [ ] Need Help? 
- [ ] Tag 
- [ ] Divider

Look at the components in [storybook](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default) and also in [Sketch](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4) to make sure all the variables are matching the colors and styles.

## Tasks

- [ ]  Link to variable tokens
- [ ]  Verify these components are setup with auto layout and the correct properties
- [ ]  Test the component (Try to break the component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch

- [ ]  Reviewed by other DS designer
- [ ]  Review by PO?

**Comment by caw310** [comment]
Carrying over as review is still needed

**Comment by LWWright7** [comment]
@danbrady This is ready for testing, however still having issues with the flow / auto layout and the icon displaying inline (that were discussed in the demo).

**Comment by LWWright7** [comment]
@danbrady Yes, that's it! I remember this method now....haven't done it in a few years! Genius! Thank you!

**Comment by LWWright7** [comment]
@danbrady - Please check these 2 again - [Maintenance Banner](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=199%3A1192&mode=design&t=54xyNMj3p3f9qzOF-1)  [US Gov Banner](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=1921%3A12513&mode=design&t=54xyNMj3p3f9qzOF-1)
