### ISSUE TITLE
Autosave, Address Block, Penalty Notice, Prefill, Need Help?, Tag, Divider - Figma component rebuild

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2232]
## Description
We need to link current Figma components that are already in the Figma VADS library to the variables that are already created in the current library. Use the list below to go through and connect the components with the correct variables. 

- [x] Autosave 
- [x] Address block 
- [x] Penalty Notice 
- [x] Prefill 
- [x] Need Help? 
- [x] Tag 
- [x] Divider

Look at the components in [storybook](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default) and also in [Sketch](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4) to make sure all the variables are matching the colors and styles.

## Tasks

- [x]  Link to variable tokens
- [x]  Verify these components are setup with auto layout and the correct properties
- [x]  Test the component (Try to break the component)

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch

- [x]  Reviewed by other DS designer
- [ ]  Review by PO?

**Comment by LWWright7** [comment]
@babsdenney @danbrady - These are ready for review. For Tag, there isn't a style for the text used on that component (which is the base Source Sans Pro, 15 pt, all caps) so not sure if we need to consider adding one or just leaving it as is, with no style.

**Comment by danbrady** [comment]
These all look good to me, @LWWright7! I'm jotting down a couple notes here based on some of the comments:

Autosave - Looks to be an instance of a slim V1 Alert. We didn't build v1 components in Figma, but we should probably note that this can be re-built in the Example Library using the the v3 Alert.
Address Block - Do we need the non-indented version? It doesn't look possible in current state of the component.
Penalty Notice - Is this body copy saved as it's own component?
Prefill - This also looks to be instances of the v1 Alert. Similar observations to Autosave.
Need Help - This looks to be a heading 2 title (with an extended underline) followed by some body copy. 
Tag - Similar to buttons and inputs, I made a local style for the text here so it matches what's developed. It will likely have to be updated when all the fonts are normalized.
Divider - Do we need to guidance on when to use the star vs non-star version?

**Comment by LWWright7** [comment]
This one is ready for review by @humancompanion-usds (Matt D)
