### ISSUE TITLE
Formation Deprecation - Step 1 - Move css variables from web-components/global to css library

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2236]
## Description
Related to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2190

As mentioned in the ticket linked to above, there are a couple different places where css variables are being declared. In an effort to make Design Tokens originating in Figma our source of truth for how css variables are generated, we need to consolidate our existing css variable usage into CSS Library. 

## Considerations
- There's a lot of overlap between the [variables in packages/web-components/src/global/_variables.scss](https://github.com/department-of-veterans-affairs/component-library/blob/8b051ae90dce58d567a1f77cb84525a701e707bf/packages/web-components/src/global/_variables.scss#L5) and the [variables generated in css-library/dist/tokens/scss](https://github.com/department-of-veterans-affairs/component-library/blob/bef641ef2c85077d4a013d5fe32030fd176912bc/packages/css-library/dist/tokens/scss/variables.scss#L5). The ones in `web-components/src/global` should be removed, and our existing web components should instead import and use the ones generated in CSS Library. 
- Right now, CSS Library isn't really being used. This ticket should implement a way of importing css variables into web components

## Tasks
- [ ] Import css variables from css-library instead of `web-components/src/global` 
- [ ] Remove `web-components/src/global/_variables.scss`

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2236?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
During the [discovery of exporting tokens](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1837) into different formats, the CSS Library was imported like this to the component-library:

![256351655-8201c3ea-0c73-4a33-920c-1adeaafd7e32](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/1700c3e5-cd44-45bd-a3e7-64aa89462f8e)

**Comment by it-harrison** [comment]
* [PR for css-library](https://github.com/department-of-veterans-affairs/component-library/pull/946)
* [PR for web-components](https://github.com/department-of-veterans-affairs/component-library/pull/945)
