### ISSUE TITLE
Formation Deprecation - Discovery - Step 1 - Rename Component Library repository to Design System

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2242]
## Description 
Once [#1218](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1218) has been completed, we should investigate and evaluate the level of effort required to rename the component library repository to "Design System", since the monorepo contains more than just a component library. 

## Considerations
- Renaming our mono repo from component-library to something else may break existing import declarations in vets-website
- May have to update all component library references in vets-website 
- May have to update imports in the component library mono-repo itself 
- Might have implications for publishing to NPM

## Tasks
- [ ] investigate steps and effort necessary to change the name of component library to design system
- [ ] write up findings and steps 

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2242?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by harshil1793** [comment]
Discovery document link: https://vfs.atlassian.net/wiki/spaces/DST/pages/2834628609/Discovery+-+Rename+Component+Library+repository+to+Design+System
