### ISSUE TITLE
Deprecate Notification component

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2248]
## Description
The team that created the Notification component asked that we deprecate it. I can handle the guidance portion. I need a dev to mark it as deprecated in Storybook as well.

## Details
Deprecate the Notification component.

## Tasks
- [x] Deprecate notification component in guidance.
- [ ] Deprecate notification component in Storybook.

## Acceptance Criteria
- [ ] Notification component is deprecated.

**Comment by humancompanion-usds** [comment]
Deprecated in guidance. This now needs to be deprecated in the component-library. When we do that I'd like us to move the closeable prop to va-card. Happy to create another issue for that.

@caw310 - Can you reassign this to a developer to make the component-library change? Thanks.

**Comment by caw310** [comment]
Added to sprint 40 as unplanned.
