### ISSUE TITLE
Formation Deprecation: Root font-size rem value approach (global vs app-by-app)

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2252]
## Description

After completing the [discovery work](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2223) on migrating the base font size, we want to decide which approach we should take for preparing vets-website to display USWDS v3.

There is some related work done already for both of these approaches as well as pro's and con's written in the Confluence document.

Confluence document:
- https://vfs.atlassian.net/wiki/spaces/DST/pages/2817130631/Discovery+Formation+base+font-size

App-by-app approach code examples:
- https://github.com/department-of-veterans-affairs/vets-website/pull/26353

Global approach code examples:
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/987
- https://github.com/department-of-veterans-affairs/vets-website/pull/26606

## Tasks
- [ ] review all of the discovery and code example work done related to global and app-by-app updates for root font-size issue
- [ ] discuss with the team as needed

## Acceptance Criteria
- [ ] an approach has been decided and documented here
- [ ] follow-up tickets have been created

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2252?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
Dropping this PR here - https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/987 we can possibly revive this and use it as a jumping off point.

**Comment by caw310** [comment]
Closing. 2431 will be the follow up work for this effort.
