### ISSUE TITLE
Formation Deprecation - Step 2 - Transition remaining global color variables to USWDS3 colors

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2260]
## Description
One group of global styles that need to be migrated from Formation to CSS Library is our color palette. The first part of color migration [proposed in the migration strategy RFC](https://vfs.atlassian.net/wiki/spaces/DST/pages/2775253429/RFC+Migration+Strategy+Formation+to+CSS-Library#2.-Migrate-global-base-styles-from-Formation-to-css-library) is to update the hex values for color variables directly to USWDS hex values, in Formation itself. #2228 updated all of the primary blue colors in Formation. With this ticket, our goal is to update the remaining variables in Formation. 

## Considerations
- #2228 handled all the primary blues
- [Airtable containing token names and values](https://airtable.com/appF4FJKBeNVNGrlm/tblVoDslTYpAh7dr1/viw5VK18YcZe6E4vq?blocks=hide)

## Tasks
- [ ] Update all remaining color variables to their USWDS equivalent hex values in Formation
- [ ] Submit and merge a PR into vets-website updating the version of Formation

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by powellkerry** [comment]
@humancompanion-usds There are some colors that don't appear in AirTable that I have found in formation. Most of these seem like they are not used or are deprecated. Do we need to update these colors?

```
//===================================
// Formation colors that override (or restate) USWDS values
// Also see: https://standards.usa.gov/components/colors/
//===================================

$color-focus:                #3e94cf;

$focus-outline:              2px solid $color-gold-light;

$color-cool-blue:           #205493;
$color-cool-blue-light:     #4773aa;
$color-cool-blue-lighter:   #8ba6ca;
$color-cool-blue-lightest:  #dce4ef;
//===================================
// DSVA colors
// Places where DSVA is going rogue!
//===================================

$color-link-default-hover:   rgba($color-black, 0.05);

$color-va-modal-bg:          rgba($color-gray-dark, .8);

$color-white-alpha70:        rgba(255,255,255,.7);

$color-sidebar-nav-bg:   rgba($color-black, 0.25);

//===================================
// Hub Icon colors for BC
//
//===================================

$red-70v: #8b1303;
$red-60v: #b51d09;
$indigo-cool-60: #3f57a6;
$red-60: #a23737;
$mint-cool-50: #21827f;
$orange-warm-50: #bd5727;
$green-cool-50: #3e8520;
$gold-50: #8e704f;
$green-warm-50: #6f7a41;
$blue-50: #357ab2;
$violet-warm-60: #864381;

// Contextual variable names
$color-hub-health-care: $indigo-cool-60;
$color-hub-education: $mint-cool-50;
$color-hub-disability: $red-60;
$color-hub-careers: $orange-warm-50;
$color-hub-pension: $green-cool-50;
$color-hub-housing: $gold-50;
$color-hub-life-insurance: $green-warm-50;
$color-hub-burials: $blue-50;
$color-hub-records: $violet-warm-60;

//===================================
// Deprecated Colors;
// Please avoid using.
//===================================

$polar:       #E8F5FA;
$wild-sand:   #f6f6f6;
$green-white: #eff0e6;
$olso-gray:   #849097;
$light-blue:  #e1f3f8;
$mm-gray:     #f1f1f1;
```

**Comment by powellkerry** [comment]
Here is the color comparison of colors being updated:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40da9ea43c30a3b81260da6a2f4e65aced846a85/localhost_8080_color-diff%20%285%29.png)

**Comment by humancompanion-usds** [comment]
Okay, most of these seem to align to their USWDS values. Those names are USWDS primitive colors:
```
$red-70v: #8b1303;
$red-60v: #b51d09;
$indigo-cool-60: #3f57a6;
$red-60: #a23737;
$mint-cool-50: #21827f;
$orange-warm-50: #bd5727;
$green-cool-50: #3e8520;
$gold-50: #8e704f;
$green-warm-50: #6f7a41;
$blue-50: #357ab2;
$violet-warm-60: #864381;
```

Of course, there has to be an exception, and it's that first value, which is just plain wrong. It should be #8b0a03. So I will add these next week as tokens for the hubs. oslo-gray, light-blue, and mm-gray I'll have to find values for or suggest a suitable existing token.

**Comment by caw310** [comment]
Might carry over due to clarification on colors.

**Comment by humancompanion-usds** [comment]
Okay, here are some new colors. These can all use the USWDS primitives directly and they really, really should get removed entirely.

$wild-sand: #f6f6f6; This gray-3.
$green-white: #f5f0e6; This is gold-5.
$oslo-gray: #8d9297; This is gray-cool-40.

These should map to their VADS token:
$light-blue: #e1f3f8; This is vad-color-primary-alt-lightest
$polar: #e7f6f8; This vads-color-info-lighter
$mm-gray: #f0f0f0; This is gray-5 or vads-color-gray-lightest

The rgba values don't change for the moment. I'll add the hubs in issue #2084.

**Comment by powellkerry** [comment]
Dev work is done on this task. It will remain open until we are ready for a formation release, probably the first week of January.
