### ISSUE TITLE
Move any individual tokens or variables in components to the CSS Library

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2266]
## Description

The `va-crisis-line-modal` has [a color variable in its stylesheet](https://github.com/department-of-veterans-affairs/component-library/blob/5aefd6dcbff87864fae2ef21af98a18cc6acef90/packages/web-components/src/components/va-crisis-line-modal/va-crisis-line-modal.scss#L4) `$red-70v: #8b1303;`. 

Now that the [CSS Library](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library) is available, we should consider moving it to that package instead of keeping it in an individual component.

## Tasks
- [ ] review the component library for any individual tokens or variables that could be moved or referenced from the CSS Library
- [ ] move those tokens or variables to the CSS Library if necessary
- [ ] discuss with design or the team to determine the token name if necessary

## Acceptance Criteria
- [ ] any lone tokens or variables in the web-components package are being imported from the CSS Library.

**Comment by jamigibbs** [comment]
This work has been completed.
