### ISSUE TITLE
va-search-input: update the v3 type ahead background blue hover color to USWDS color

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2275]
## Description
The hover background blue color on the [type ahead dropdown](https://design.va.gov/storybook/?path=/docs/uswds-va-search-input--with-typeahead) in the v3 variation should match the USWDS v3 button color blue.

Part of this work is to verify the color but when doing a browser inspect on the v3 variation button, I believe it to be `005EA2`.
In CSS Library, this is: `--uswds-system-color-blue-vivid-60`

![Screenshot 2023-11-21 at 3 17 09 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/a80947b9-107e-4a65-a096-94023788f31a)

## Tasks
- [ ] Verify which USWDS blue color to use.
- [ ] Update the type ahead dropdown hover color to match the USWDS blue button color in the v3 variation

## Acceptance Criteria
- [ ] Using the CSS Library USWDS token value, the look ahead hover background blue is display as the correct USWDS v3 color

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2275?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by nickjg231** [comment]
Currently on the [va-search-input with Typeahead](https://design.va.gov/storybook/?path=/docs/uswds-va-search-input--with-typeahead) page on design.va.gov, the hovered dropdown element has a background color of `#005ea2`:
code:
<img width="409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDIxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fea7ee6440fbca9ec42e9e98806421c9c10f0ae0/image.png" alt="image.png" />
page:

<img width="541" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCsxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c96ed168eed05976ab27158ae140bb0817ec774/image.png" alt="image.png" />



<hr>
This matches the button, which uses the primary color of `rgb(0, 94, 162)`,which is equal to the hex code `#005ea2`
<img width="293" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGExQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7e15fec93a8a1f06adcd08b203c570badd82c9f/image.png" alt="image.png" />
<hr>

I believe this has been resolved from a previous ticket since these values are now matching. Closing this
