### ISSUE TITLE
CSS Library: Fix the minify script

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2295]
## Description

In the CSS Library there is a [stylesheet minify script](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/package.json#L12) that would generate `.min.css` files like this but now doesn't seem to be working:

![Screenshot 2023-12-04 at 1 43 24 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/935ffe9f-d09e-47c4-85fa-07c820eaea1b)

## Tasks
- [ ] Investigate why the minified stylesheets are not updating and fix the script
- [ ] Update the package [README.md](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/README.md) file if needed.

## Acceptance Criteria
- [ ] The stylesheet minification script works

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2295?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
