### ISSUE TITLE
Update Chromatic project token account connection

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2308]
## Description

Right now the Chromatic preview for Storybook is being generated from an account that can not be accessed by anyone on the design system team.

What we will likely need to do is:

1. Create a new [Chromatic](https://www.chromatic.com/start?startWithSignup=true) account. Ideally this will be connected to some sort of VSP github service account.
2. Link the new account with our GitHub org to help manage permissions easier in the future
3. Update the CHROMATIC_PROJECT_TOKEN [secret](https://github.com/department-of-veterans-affairs/component-library/settings/secrets/actions) which is being used in the [chromatic workflow](https://github.com/department-of-veterans-affairs/component-library/blob/main/.github/workflows/chromatic.yml#L39) so we are no longer relying on the old account.

See this Slack convo for more information: https://dsva.slack.com/archives/G01BJ3ESXL4/p1701960948474229?thread_ts=1701879504.129039&cid=G01BJ3ESXL4

## Tasks
- [ ] Check if there is a VSP github service account we can use when creating a new Chromatic account.
- [ ] Update the component-library repo so that it's using a Chromatic account we can access.
- [ ] Test that the Chromatic link is still working for our Storybook preview.

## Acceptance Criteria
- [ ] The design system's Chromatic workflow functions using a Chromatic account that we can access

**Comment by caw310** [comment]
Carrying over as it took more time to identify how to resolve this.

**Comment by caw310** [comment]
@micahchiang @Andrew565 , can this be closed or is there work that still needs to be done?
