### ISSUE TITLE
Formation Deprecation: Replace instances of .va-button-primary

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2312]
## Description

We are starting to decide what VA specific styles from Formation should be moved to the CSS Library. There is a class in Formation for `.va-button-primary` that has been deprecated in favor of using [va-button](https://design.va.gov/storybook/?path=/docs/components-va-button--primary) but instances of this class still exist in vets-website and content-build. 

So that we don't need to bring this class over to the CSS Library, we should replace instances of it and remove it. Once this class is no longer being used, then we can remove it from [Formation `sass/base/_va.scss` stylesheet](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c95a7a9ae6e554aeb2af2cab5836bd927302436d/packages/formation/sass/base/_va.scss#L1041-L1062):

```css
.va-button-primary {
  background: $color-green !important;

  &:hover,
  &:focus {
    background-color: $color-green-darker !important;
    text-decoration: none !important;
  }

  svg {
    display: inline-block;
    height: 1.2rem;
    margin-left: 0.5rem;
    width: 1.2rem;
    vertical-align: -1px;
  }
}
```

There is already an [ES Lint warning](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/lib/rules/deprecated-classes.js) in place:

![Screenshot 2023-12-08 at 8 53 21 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/fedcd99a-cba9-4a47-984b-76b7974e399d)

There are currently 31 results in vets-website and 2 in content-build:

![Screenshot 2023-12-08 at 9 08 48 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/d2d9ca65-d9ca-49ab-a119-278927d2e372)

![Screenshot 2023-12-08 at 9 08 52 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/5f81b3fd-32a1-4c4b-949b-1935965cc515)

## Tasks
- [ ] Replace any instances of `.va-button-primary` with the equivalent `va-button` variation in both vets-website and content-build
- [ ] Remove the `.va-button-primary` CSS from Formation.
- [ ] Remove/Update the `.va-button-primary` ES Lint rule.

## Acceptance Criteria
- [ ] `.va-button-primary` is no longer being used in either vets-website or content-build
- [ ] `.va-button-primary` is removed from Formation. 
- [ ] The ES Lint rule has been removed/updated

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2312?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
This will carry over because we are still needing a couple of reviews from vets-website code owners.
