### ISSUE TITLE
Change the default for memorable date back to three inputs

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2316]
## Description
Based on research done by the Forms Team, there are some issues with memorable date, so during the DSC meeting on Dec 8, it was decided to revert the default back to 3 input fields. 

## Details
Here is the PR that made the select the default for memorable date. We need to revert this. 
https://github.com/department-of-veterans-affairs/component-library/pull/869

## Tasks
- [ ] Set the default for memorable date to the version with 3 input fields

## Acceptance Criteria
- [ ] Default for memorable date in storybook is 3 input fields
- [ ] Default on design.va.gov for memorable date in storybook is 3 input fields
- [ ] Default in Figma for memorable date is 3 input fields

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2316?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
@danbrady , please make sure memorable date default is 3 inputs in Figma.

**Comment by it-harrison** [comment]
PR is [here](https://github.com/department-of-veterans-affairs/component-library/pull/1014)

**Comment by danbrady** [comment]
> @danbrady , please make sure memorable date default is 3 inputs in Figma.

FYI: Figma was updated to set the three text inputs to be default to match the web component.
