### ISSUE TITLE
Formation Deprecation - Update CSS Library color tokens to V3

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2324]
## Description 
We recently updated primary blue colors in CSS Library to USWDS3 token values in [#2292](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2292). In a similar fashion, we need to update all remaining colors to use USWDS3 tokens. 

## Considerations
- [PR for 2292](https://github.com/department-of-veterans-affairs/component-library/pull/974/files#diff-5adf51640c36ace982f86344c0ed73aa56b0e19a321713483ce12933fff6b0dcR6). 
- All updates will happen in [packages/css-library/tokens/color.json](https://github.com/department-of-veterans-affairs/component-library/blob/15682dd26fed97f3bf9d7c983e4cc0f2f1009e8a/packages/css-library/tokens/color.json#L2)

## Tasks 
- [ ] Update token values to use USWDS token names
- [ ] Perform a global search and replace in the Component-Library repo for any hard coded hex values
- [ ] Publish a release for the component library repository to NPM (actual release into vets-website will be in a separate ticket)

## Acceptance Criteria
- [ ] All tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2324?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by humancompanion-usds** [comment]
vads-color-blue-cool - uswds-system-color-blue-warm-60 - #345D96
vads-color-blue-cool-light - uswds-system-color-blue-warm-50 - #4a77b4
vads-color-blue-cool-lighter - uswds-system-color-blue-warm-30 - #98afd2
