### ISSUE TITLE
Formation Deprecation - Release remaining USWDS3 Global color variables to vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2325]
## Description
Once [2324](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2324) is completed, we'll release a version update for Formation and CSS Library to vets-website. For the added effort required to QA this, we're keeping it in a distinct issue. 

## Tasks
- [ ] Update versions of Formation and CSS Library in the vets-website package.json to the version numbers that include remaining global USWDS3 color changes
- [ ] Perform a global search and replace for all old hex values and update any instances to USWDS3 equivalents

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2325?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
