### ISSUE TITLE
Discovery: What will it take to Upgrade Storybook to Latest

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#2328]
## Description
Currently, our Storybook is still using version 6.4. The latest version as of this writing is 7.6. Migrating from 6.4 to 6.5 is trivial, but migrating from 6.5 to 7.X is not. There are automigration scripts that help with some of the initial setup, but then there are additional tweaks that will need to be made.

This ticket is a discovery to identify what would break or need to be done to upgrade Storybook. 

## Details
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-65x-to-700

## Tasks
- [ ] Identify plan to upgrade to latest 7.X version
- [ ] Identify any fixed that need to be addressed for migration

## Acceptance Criteria
- [ ] Draft plan for how to upgrade Storybook

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2328?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by ataker** [comment]
Discovery doc: https://vfs.atlassian.net/wiki/spaces/DST/pages/3035594769/Discovery+Upgrading+Storybook+to+7+or+8
