### ISSUE TITLE
[va-featured-content] - Update naming to Summary Box

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2336]
## Description
In order to align with the [USWDS component](https://designsystem.digital.gov/components/summary-box/), we need to update the naming of this component to be Summary Box.

## Tasks
- [x] Update component name to `va-summary-box`
- [x] Ensure existing `va-featured-content` doesn't break?
- [x] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).
- [ ] Update design.va.gov with name change

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2336?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
Found instances in vets-website:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/15097156/ac412f8b-b77b-4f00-8ee4-b1a2971fd5de)

Doesn't look like the react binding for this is being imported.

**Comment by micahchiang** [comment]
I'm going to close this ticket since we have [#2338](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2338) in our backlog which covers renaming components in vets-website and the work required in component library has been completed. Alex also already has a PR out that can be referenced in 2338 for the work required in vets-website.
