### ISSUE TITLE
Formation Deprecation - replace .card class with va-card web component

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2337]
## Description 
In a [recent audit](https://github.com/department-of-veterans-affairs/component-library/pull/981#discussion_r1423156467) it was discovered that usages of the `.card` utility class could potentially be replaced with the `<va-card>` web component. This ticket will verify if that's true or not. If it is, then all instances where it is being used will be replaced with `<va-card>`

```css
.card {
  position: relative;
  margin: 0 0 1.5em 0;
  padding: 1em;
  border: 1px solid $color-gray-lightest;
  dt {
    font-weight: 700;
  }
  dd {
    padding: 0;
    margin: 0;
  }
  &.templates {
    height: 338px;
  }
  &:after {
    visibility: hidden;
    display: block;
    font-size: 0;
    content: " ";
    clear: both;
    height: 0;
  }

  h4,
  h5 {
    margin-top: 0;
  }
}
```

https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/f78cc125b45f07273409046fea7c4e21af71f46d/packages/formation/sass/base/_va.scss#L656-L736

## Considerations
Found instances of `.card` in vets-website: 
<img width="1102" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenhoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef44e62df3c87c79e5421b5c8fcd0ebca787a9cd/image.png" alt="image.png" />

<img width="633" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fbb089d1baea8a71cf57f94d26dceb602685f05c/image.png" alt="image.png" />

## Tasks
- [ ] verify instances of `card` above can be replaced with va-card
- [ ] update instances of `card` with `va-card`
- [ ] update any tests that look for the `.card` selector

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2337?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Moving to the next sprint as we need to add a gray card prop.
