### ISSUE TITLE
Fix Alert colors 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2339]
## Description
Update colors in all Alert Banner status types

From Matt: 
The info alert has 2 background colors, which you can't see until it reaches a certain width. In Figma we are using the component level tokens (vads-alert-color-background-info-on-light), which I realize adds a level of complexity because we're not yet using those in the components themselves. USWDS switched from primary-alt to info ([state tokens](https://designsystem.digital.gov/design-tokens/color/state-tokens/): info, info-light, info-lighter, etc.) in Alert. We're not using those tokens yet either in the component itself. So we need to fix that so that our info Alert actually matches USWDS.

## Details
Figma - Alert - https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=539%3A4085&mode=design&t=nDqXz5T9BrUSbxTi-1 

## Tasks
- [ ] Update the info alert background colors to to match USWDS info alert 

## Acceptance Criteria
- [ ] Info Alert web component matches USWDS info alert
- [ ] Info Alert in Storybook is updated

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2339?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by humancompanion-usds** [comment]
In addition, the following Alert colors are incorrect:

* Warning border should be vads-alert-color-border-warning-on-light which points to vads-color-warning (#ffbe2e)
* Error border color should be vads-alert-color-border-error-on-light which points to vads-color-error (#d54309)
* Success border color should be vads-alert-color-border-success-on-light which points to vads-color-success (#00a91c)

**Comment by harshil1793** [comment]
@humancompanion-usds I've noticed that like info alert others doesn't match the USWDS colors. Would you like the other alerts to be fixed as well?

**Comment by caw310** [comment]
@danbrady , since you're working on Alerts, can you chime in since Matt is out?

**Comment by danbrady** [comment]
Yeah, I think we should be updating all the colors in alert to the USWDS colors. You might want to check with @powellkerry who is working on updating the tokens/vars (#2324) which I think would be needed here?

**Comment by harshil1793** [comment]
@danbrady, I've noticed that the tokens were already in place, and I'm able to use them.
