### ISSUE TITLE
Update component min-widths to 284px in Figma

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2345]
## Description
Update component min-widths to 284px to support mobile screens with gutters.

Reference: See [slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1702672226195539?thread_ts=1702657339.972889&cid=C01DBGX4P45) on details of 284px decision.

## Tasks
- [ ] Create new `vads-size-min-width-body` token to standardize value 
- [ ] Update component min-widths pointing to variable

## Acceptance Criteria
- [ ] Components that have min-width supplied should allow resizing down to value of `vads-size-min-width-body` variable
