### ISSUE TITLE
Deprecate max length text input variation, convert to character count variation

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2349]
## Description

Per this [thread](https://dsva.slack.com/archives/C01DBGX4P45/p1702410868353069?thread_ts=1702321865.054929&cid=C01DBGX4P45), we want to stop using the [**Max length**](https://design.va.gov/components/form/text-input#max-length) variation for text input and use [**Character count**](https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--default#with-character-count) instead.

See https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2323 for additional context.

## Tasks
- [ ] Deprecate the max length variation - **unsure if we need to change instances that use it, or just mark it as deprecated and advise against future use**
- [ ] Update documentation to show the character count variation instead

## Acceptance Criteria
- [ ] Character count variation is the new standard for this functionality

**Comment by Andrew565** [comment]
@humancompanion-usds A few hopefully quick questions for you regarding this transition away from the "Max Length" variation:

1. The 'charcount' prop requires that the 'maxlength' prop also be set. Since we're deprecating the 'Max Length' variation, should I just default the component to showing the "Character Count" variation if the 'maxlength' prop is set? This would preclude the need to specify the 'charcount' prop separately. For what it's worth, there are currently 0 instances of the "Max Length" or "Character Count" variations in use in vets-website, so there would be no changes needed there whatever we decide API-wise.
2. The V1 component doesn't currently have a "Character Count" variation, should I add this at the same time and deprecate the "Max Length" variation for V1 as well?

**Comment by humancompanion-usds** [comment]
@Andrew565 

1. Yes, that sounds fine.
2. No, no need. By next month we'll default to v3 and teams will be able to opt out. After that we'll start deprecating v1 components.
