### ISSUE TITLE
Update the guidance template to include mobile

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2391]
## Description
Update the component guidance page template on design.va.gov to include guidance and usage for mobile components

## Details
Review examples of mobile component guidance from Jessica and use those examples to update our templates and our guidance for a few components.

## Tasks
1. [ ] Bring the following components into VADS:
  * [x] Button
  * [x] Link 
  * [x] Alert
2. [ ] Update component template to have spots for mobile
3. [ ] Create a mobile-only component template for components that don't yet have a web equivalent

## Acceptance Criteria
- [ ] Component guidance page has section for mobile

**Comment by humancompanion-usds** [comment]
@caw310 - I'd like us to create a new Epic for integrating the flagship mobile app with the VA Design System. This is more than Maintenance. Also, I'd really like maintenance to get phased out as an epic. 52 issues is too many for one epic. It's a dumping ground. Thanks.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2391?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by humancompanion-usds** [comment]
From @jessicawoodin:  Here are 3 examples of components that have shared documentation with VADS. For each component, I've linked to the documentation on the mobile doc site and the Google doc. In the Google doc, I copied in the VADS documentation and used track changes to see where mobile might be different.

* Button ([Mobile doc site](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Components/Buttons%20and%20links/Button) | [Google doc](https://docs.google.com/document/d/1oZgsJytSN3GNVAPN9wzfOz3WOeoMuNG0CWDTg2BRehs/edit#heading=h.vj9zwf7j22yt))
* Link ([Mobile doc site](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Buttons%20and%20Links/ClickForActionLink) | [Google doc](https://docs.google.com/document/d/1ak2hC3ceOla5hMG9sjjCRloup2Ee-D0D_grsWbJMfwk/edit#heading=h.vj9zwf7j22yt))
* Alert ([Mobile doc site](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Alerts%20and%20Progress/AlertBox) | [Google doc](https://docs.google.com/document/d/1CK18qCqFL-342WyG3l0lwmn31Th67ceJTmBufobVIno/edit#heading=h.vj9zwf7j22yt))

If you need an example of a component that does not have shared documentation with VADS, the [Segmented Control](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Components/Navigation/Secondary/SegmentedControl) or [Snackbar](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Alerts%20and%20Progress/Snackbar) components would be good ones to reference.

**Comment by humancompanion-usds** [comment]
I'm working on updating Button. Mobile has 2 buttons for on-dark mode that we'll need to add.

**Comment by humancompanion-usds** [comment]
This is blocked on updating our Storybook instance so putting back into the upcoming column.

**Comment by humancompanion-usds** [comment]
I've added mobile buttons and updated the guidance:
https://design.va.gov/components/button/#mobile

I was, disappointingly, not able to reference our instance of Storybook in the example iFrames. Thus when folks click through, they will go to the Mobile Design System (e.g. https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/docs/button--base). That's not what I had hoped and a bug we need to address.
