### ISSUE TITLE
Fix link on Storybook for Header - Minimal 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2393]
## Description
The link to guidance in Storybook for Header - Minimal is broken.. 
Also, the name of the component should be Header - minimal instead of minimal header. 

## Details
Storybook: https://design.va.gov/storybook/?path=/docs/components-va-minimal-header--default 
Documentation:  https://design.va.gov/components/header/header-minimal

## Tasks
- [ ] Fix the Header - Minimal link to guidance in Storybook 
- [ ] Update the component name in Storybook to Header - Minimal (same as on design.va.gov)

## Acceptance Criteria
- [ ] Link to guidance goes to https://design.va.gov/components/header/header-minimal
- [ ] Name of the component in Storybook is Header - Minimal

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2393?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by harshil1793** [comment]
The component has been renamed from `va-minimal-header` to `va-header-minimal`. This renaming ensures uniformity and clarity in our component library, making it more intuitive for developers to find and implement this component.
