### ISSUE TITLE
Update component usage data report

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2413]
## Description
Update component usage data report to include React vs. v3 component vs. v1 components. Each should have it's own tab in the google sheet. 

## Details
Google sheet 
https://docs.google.com/spreadsheets/d/1IKi_kNSQtasTb3hHbcKbhHLv7BCYCmRqsUtaRPcrtG8/edit?usp=sharing . 

Confluence page with instructions on Updating Component usage data 
https://vfs.atlassian.net/wiki/spaces/DST/pages/1962213425/Updating+component+usage+data?atlOrigin=eyJpIjoiNjUyMjEyOGI0MGIyNGM4MTg1MjU5ZjU0YjdlNGFiYmEiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ 

## Tasks
- [x] Update component usage report to include React vs. v3 component vs. v1 components
- [x] Update the google sheet so there is a tab for each 
- [x] Review with the team and PO
- [x] Update confluence page with instructions on updating component usage report 

## Acceptance Criteria
- [x] Component usage report has a tab for each of these:  React vs. v3 component vs. v1 components
- [x] Confluence page with instructions on updating component usage report is updated as needed.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2413?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
@Andrew565 , for my purposes, a count for each kind of component should be fine. Although I could see it being helpful to know where components are being used in the future.

**Comment by caw310** [comment]
@Andrew565 , we would like to know where components are being used. Please add that.
