### ISSUE TITLE
Swap v3 examples to the top/default for component pages on design.va.gov (part 1)

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2422]
## Description
Make v3 examples the default for the following component pages on design.va.gov

- Accordion
- Additional Info
- Alert
- Breadcrumb
- Button
- Button Pair
- Featured Content (aka Summary Box)
- Checkbox
- Memorable Date
- Number Input

## Tasks
- [ ] Swap v3 examples to be the top one show on these component pages
  - [ ] Accordion
  - [ ] Additional Info
  - [ ] Alert
  - [ ] Breadcrumb
  - [ ] Button
  - [ ] Button Pair
  - [ ] Featured Content (aka Summary Box)
  - [ ] Checkbox
  - [ ] Memorable Date
  - [ ] Number Input

## Acceptance Criteria
- [ ] v3 components are shown at the top for the components specified

**Comment by danbrady** [comment]
@caw310 Looking closer at these I see a lot of component pages don't need to be updated because  they either don't have storybook examples or don't have both v1 and v3 examples called out differently. So I think we can merge the Part 2 (#2498) issue with this one and I can submit a PR for all of the pages that needs to be updated. Thanks.

**Comment by caw310** [comment]
@danbrady Okay. I thought I only listed the v3 components. If we can do both sets in one sprint, all the better.

**Comment by danbrady** [comment]
Combining list from and #2498 issues:

- [x] Accordion
- [ ] ~Additional Info~ (Only has v3)
- [ ] ~Alert~ (Already done)
- [x] Breadcrumb
- [x] Button
- [x] Button Pair
- [x] Featured Content (aka Summary Box)
- [x] Checkbox
- [x] Memorable Date
- [ ] ~Number Input~ (Only has v3)
- [x] Privacy Agreement
- [x] Progress bar - Segmented
- [x] Radio button
- [x] Select
- [ ] ~Statement of Truth~ (Only has v3)
- [x] Text Input
- [x] Text Area
- [x] Modal
- [x] Pagination
- [x] Process List
- [x] Search Input

**Comment by danbrady** [comment]
My mistake, I misunderstood the requirements. Per Matt:

> We also want to swap the variations to all be v3, not just the default, and then make v1 just show the default option (as we had done for v1). I did this in Alert, as an example...

@caw310 Reverting this back to being two tickets with the items you specified.

**Comment by caw310** [comment]
Moving this to the next sprint as there is higher priority work to be done in file input.

**Comment by humancompanion-usds** [comment]
No worries. I will take this one over for this sprint so that Dan can focus on File input.
