### ISSUE TITLE
Federal CIO - Authenticated Header includes current functionality

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2436]
## Description
When a user signs in, three links get dynamically rendered: sign out, My VA, and My HealtheVet. In our effort to inject a flat header into teamsites comprised only have vanilla js, html, and css, functionality needs to be added that provides this experience. The current header relies on accessing the Redux Store through the react-redux `connect` and `mapStateToProps` API. 

<details><summary>Current authenticated drop down menu with sign out button</summary>

<img width="402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1MQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dc9dcb705592a4b1d823de40a84c660636d2e90/Screenshot%202024-01-29%20at%2010.08.26%20AM.png" alt="Screenshot 2024-01-29 at 10.08.26 AM.png" />

</details>

<details><summary>My VA & My HealtheVet links</summary>

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6415281bf05251e65c638aea81ff85c24c65375/Screenshot%202024-01-29%20at%2010.08.22%20AM.png" alt="Screenshot 2024-01-29 at 10.08.22 AM.png" />

</details>

## Considerations
- Verify whether or not any authenticated header work can be done by injecting react into the flat header similar to what we do for [other applications on VA.gov](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/startup/react.js). If it can, try and leverage existing work. If not then: 
- [Using Redux without React](https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files)
- Sign out button uses Redux to see which Auth Broker (IAM or SiS) and CSP (ID.me, Login.gov, DS Logon, or MHV) the user signed in with.
- [Current user nav dropdown](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/user-nav/components/PersonalizationDropdown.jsx) where Redux is checked
- My HealtheVet link relies on feature toggle to render title and link. We may need to clarify how much access Teamsites has to feature toggles, and whether this should get render on the header itself or in the dropdown menu. 
- [Sign out handler](https://github.com/department-of-veterans-affairs/vets-website/blob/df369df4de1766d29813ba865f72c4b6d746adc4/src/platform/site-wide/user-nav/components/PersonalizationDropdown.jsx#L27-L37)

## Tasks
- [ ] Create signed-in drop down menu with the existing sign out button. This should include the authenticated user's name as button label.
- [ ] Sign out button should function the same way it does currently
- [ ] Add partials for My VA and My HealtheVet links
