### ISSUE TITLE
File input a11y visual updates

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2441]
## Description

- Update to use the VA yellow outline.
- Update the click target to match the visual dotted line and the focus outline.

<img width="1030" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e11aa33b636294b0f7c00389c30564b07e6643a4/image.png" alt="image.png" />

## Tasks
- [ ] Make visual updates

## Acceptance Criteria
- [ ] Focus outline looks as expected
- [ ] Click target matches the button's appearance

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2441?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
