### ISSUE TITLE
Modal - Fix icon position in large version

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2445]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When using the large version of the modal, the icon position is not correct.

<img width="893" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/fcc3f39f-6999-4a88-b9a1-01ca867bc375">

## What I expected to happen

Screenshot from Figma:

<img width="822" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/ad8dbcdf-a446-44ba-b147-093a897eb894">

## Tasks
- [ ] Fix icon position
- [ ] Validate with a DS designer

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2445?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
