### ISSUE TITLE
Update forms pattern headings to correct serif font

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2474]
## Description

For the new forms pattern, the form headings are sans-serif fonts. Per [VA.gov Design System - Typography](https://design.va.gov/foundation/typography), these should be serif fonts (except for `h6`).

<img width="762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejhyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c8e21c0c0761704b091502da74ba883ae6f094c/image.png" alt="image.png" />

Heading styles have not been migrated to the css-library and currently only exist in formation. Part of this task will be to migrate these styles to css-library and then update each of the components below to consume those styles.

## Tasks
- [ ] Ensure the right styles are being applied to the new forms pattern headings:
  - [ ] Text and number input
  - [ ] Textarea
  - [ ] Radio
  - [ ] Checkbox
  - [ ] Memorable date

## Acceptance Criteria
- [ ] `h1-h5` are serif, per our guidelines.
- [ ] `h6` is sans-serif, per our guidelines.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2474?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by powellkerry** [comment]
@micahchiang It looks like heading styles are still in formation. Should we take this opportunity to migrate them over to css-library instead of hard coding a bunch of heading styles in each of these components?

**Comment by micahchiang** [comment]
@powellkerry - I like this idea! Could you update the description body for this ticket to outline the work required to do this? Thank you!

**Comment by jamigibbs** [comment]
[font-family tokens already exist in the CSS Library](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/tokens/fonts.json). Is the extra task to move something else related to fonts from Formation?
