### ISSUE TITLE
Merge PR to set uswds to true on all web components

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2476]
## Description 
This is a follow up ticket to #2405. Work has been done to update all components to v3 using the uswds prop. [This PR](https://github.com/department-of-veterans-affairs/component-library/pull/1043) needs to be merged and a component library release needs to be cut and added to vets-website. 

## Tasks
- [ ] Merge [this pull request](https://github.com/department-of-veterans-affairs/component-library/pull/1043)
- [ ] Perform a component library release
- [ ] Submit a pull request for the new release into vets-website.

**Comment by caw310** [comment]
Moving out sprint 47 as a team requested we hold off and CI issues is blocking this as well.

**Comment by it-harrison** [comment]
PR is [here](https://github.com/department-of-veterans-affairs/component-library/pull/1043)

**Comment by micahchiang** [comment]
[PR into content-build](https://github.com/department-of-veterans-affairs/content-build/pull/1971) has been merged, so I'm closing this ticket.
