### ISSUE TITLE
Update Chromatic token in Github

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2481]
## Description
In #2308 we provisioned a new va-dst-bot account and stored its credentials in parameter store. Now that this is complete, we need to replace the chromatic token secret in github with updated credentials so we can link our github CI/CD with Chromatic for visual regression testing.

What we will likely need to do is:.
1. Link the new account with our GitHub org to help manage permissions easier in the future
2. Update the CHROMATIC_PROJECT_TOKEN [secret](https://github.com/department-of-veterans-affairs/component-library/settings/secrets/actions) which is being used in the [chromatic workflow](https://github.com/department-of-veterans-affairs/component-library/blob/main/.github/workflows/chromatic.yml#L39) so we are no longer relying on the old account.

See this Slack convo for more information: https://dsva.slack.com/archives/G01BJ3ESXL4/p1701960948474229?thread_ts=1701879504.129039&cid=G01BJ3ESXL4

## Tasks
- [ ] Update the component-library repo so that it's using a Chromatic account we can access.
- [ ] Test that the Chromatic link is still working for our Storybook preview.

## Acceptance Criteria
- [ ] The design system's Chromatic workflow functions using a Chromatic account that we can access

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2481?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
va-dst-bot has already been added to the department-of-veterans-affairs org, for what that's worth.

We'll also need to get everyone who wants access to the UI tests to sign up for a free Chromatic account and then make sure they can access the UI tests generated by the bot account.

Finally, we'll need to set up the process of uploading to Chromatic and checking UI tests as part of our QA workflow.
