### ISSUE TITLE
Formation Deprecation - Typography base size migration QA Formation

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2494]
## Description
With the completion of #2431, thorough QA needs to be conducted in vets-website prior to any pull request being merged in. This likely means local testing with verdaccio and sandbox testing with the preview instance that gets generated when a pull request is submitted to vets-website and content-build

## Considerations
- [Pull request](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/987) into formation. This should ultimately bump the version number for Formation as well. 
- [Pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/26606) into vets-website. This should include the version change from the above PR, and QA should be conducted using the preview instance and/or verdaccio.

## Tasks
- [ ] Submit PR into content-build and conduct QA
- [ ] Conduct QA on vets-website PR above
- [ ] Address any visual issues in Formation

## Acceptance  Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2494?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
@jamigibbs - Good call out. Yes, that would need to be part of the vets-website PR.

**Comment by powellkerry** [comment]
This will carry over due to complexity and dependencies with the other Typography tickets. It is taking a while to QA and figure out where defects should be fixed.
