### ISSUE TITLE
Swap v3 examples to the top/default for component pages on design.va.gov (part 2)

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2498]
## Description
Make v3 examples the default for the following component pages on design.va.gov 

- Privacy Agreement
- Progress bar - Segmented
- Radio button
- Select
- Statement of Truth
- Text Input
- Text Area
- Modal
- Pagination
- Process List
- Search Input

## Tasks
- [ ] Swap v3 examples to be the top one show on these component pages
  - [ ] Privacy Agreement
  - [ ] Progress bar - Segmented
  - [ ] Radio button
  - [ ] Select
  - [ ] Statement of Truth
  - [ ] Text Input
  - [ ] Text Area
  - [ ] Modal
  - [ ] Pagination
  - [ ] Process List
  - [ ] Search Input

## Acceptance Criteria
- [ ] v3 components are shown at the top for the components specified

**Comment by humancompanion-usds** [comment]
I'm just handling this all in 2422 thus closing this issue.
