### ISSUE TITLE
Expand radio button and checkbox max widths - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2507]
## Description
Increase the the max width to a line-length token and update Figma artifacts  for radio buttons and checkboxes.

## Details
Slack threads for reference
https://dsva.slack.com/archives/G01BJ3ESXL4/p1708018513319609
https://dsva.slack.com/archives/C01DBGX4P45/p1707845066268259

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Update designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2507?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by danbrady** [comment]
Some research to help us figure out the right token to use...

I used [Sign VA claim forms as an alternate signer](https://staging.va.gov/supporting-forms-for-claims/alternate-signer-form-21-0972/preparer-qualifications-1b) (on staging) to test.

This is the current day form:

<img width="1200" alt="Screenshot 2024-02-16 at 10 03 15 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/bf65cd9c-44f9-4a86-850e-2bf34f6b1098">

---

Note: The form is wrapped in `.form-panel` from shame.css that restricts the width to 32em/512px:

<img width="1200" alt="Screenshot 2024-02-16 at 10 03 57 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/9cd3bfdb-00c3-4a6f-a77d-742cf7fbc153">

---

Disabling `.form-panel` and the existing 320px max-width on labels will allow them to fill the container which is in a 2/3rd grid that is ~658px wide:

<img width="1200" alt="Screenshot 2024-02-16 at 10 12 54 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/92741e34-b4c4-4ec2-ade9-8e280067ce92">

---


Here's how the line-length token values will size the labels. (I added a light yellow background to see the actual containing width):

**68ex**

<img width="1200" alt="Screenshot 2024-02-16 at 11 11 42 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/e1b9b986-df5e-48ff-92fb-5b23553aadbc">

---


**64ex**
<img width="1200" alt="Screenshot 2024-02-16 at 10 22 24 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/2b7bd0e6-7522-47c2-8ceb-79186135ef65">


---

**60ex**
<img width="1200" alt="Screenshot 2024-02-16 at 10 23 13 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/160b0cce-3be0-4469-ad62-538579ad8ec0">


---

**44ex**
<img width="1200" alt="Screenshot 2024-02-16 at 10 25 37 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/adb53526-b679-474f-bf93-edea37f78e21">

**Comment by rhasselle-oddball** [comment]
hi, just adding an example. I was investigating migrating an old form to web components, and this would have been the difference:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/797a9cef-dfb2-441c-b677-08d6d9158899)

**Comment by danbrady** [comment]
@humancompanion-usds The USWDS does not limit label length within their components, but states in [Measure (line length)](https://designsystem.digital.gov/components/typography/#measure-line-length-2):
> Most lines of text should be 45–90 characters. The current standard range for readable line length is 45 ([measure 1](https://designsystem.digital.gov/design-tokens/typesetting/measure/)) to 90 characters per line ([measure 5](https://designsystem.digital.gov/design-tokens/typesetting/measure/)). A good target for long texts is 66 characters ([measure 2](https://designsystem.digital.gov/design-tokens/typesetting/measure/)).

As well as:

> Short passages can have measure outside the ideal range.

If we want to enforce line length within the components, my preference is to use the 64ex token. That gives the line length in the approximate 60-70 character range.

**Comment by danbrady** [comment]
After some more research and working with @rhasselle-oddball and @jeana-adhoc on the forms team, we think we can align with the USWDS to use 480px as the new max-width for checkboxes and radios. A developer should reach out to the forms team to validate as well once implemented. (I can help with QA here too.)

@humancompanion-usds FYI: 480px is not one of the line-length token values, but USWDS doesn't use them in these components either. After you jump through their token chain, the USWDS uses the "mobile-lg" breakpoint value to set this max-width.
