### ISSUE TITLE
Discovery: researching best practices for using tokens with modes

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2509]
## Description
Research best practices for using tokens with modes

## Tasks
- [ ] Research using tokens with modes
- [ ] Write up findings
- [ ] Share findings with PO/Designer/TL
- [ ] Write ticket to update documentation on tokens (if needed)

## Acceptance Criteria
- [ ] Findings have been written up and shared with team
- [ ] Ticket written up if documentation update is needed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2509?planning-poker) with Zenhub @danbrady @LWWright7
