### ISSUE TITLE
[List] - Add Figma components for Lists

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2510]
## Description
Create a new List component that provides the [Experimental design request](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1330). Also, lists have moved from Foundation > Typography to Components > List. 

## Details
Confluence page with instructions: https://vfs.atlassian.net/l/cp/JR0BtAa1

Please ensure the following:

- [ ] Remove Lists from Typography section in Figma
- [ ] Create a new List component section in Figma
- [ ] Show unordered and ordered lists in the List component
- [ ] Also add this new Experimental request for a [more complex unordered list](https://design.va.gov/components/list#more-complex-unordered-and-ordered-lists)
- [ ] Create a property for a rule line at the bottom of each list item specifying color, line width and spacing

Designs for the more complex experimental list can be found here:
https://www.figma.com/file/lbRZz68qGRGTdUigcoJq3a/Local-BMT-Components?type=design&node-id=91-371&mode=design&t=7wTQB0Y5TCIBKNhl-0

https://www.figma.com/file/FmPqyjeCs4shI0oXQiuWLD/CST---Decision-Letter-Download?type=design&node-id=0-12067&mode=design&t=vqoNRSHtri3A6PrA-4

https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=80-1335&mode=design&t=johV8B4Ax0nesGFj-4

Skylar is the designer so sync with him as needed.

## Tasks
- [ ] Create designs for component in Figma
- [ ] Review designs with PO and/or other DST designers
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members 
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
Styles & Variables/Token 
- [ ] All components should be connected to VADS Component Library styles & Variables 
- [ ] All components should be connected to the proper style or variable/token 
    - [ ] Colors: connected to the correct color token (not primitive!) - can be found in local variables library 
    - [ ] Typography: connected to the correct text style - under local styles
    - [ ] Spacing: connected to the correct spacing token or primitive 
    - [ ] Icons: connected to correct icon - can be found on foundation page 
Auto layout
- [ ] Components should be as reactive as possible. Most, if not all, components should be able to be resize for either mobile, tablet, or desktop sizes 
- [ ] The correct spacing should be applied to auto layout 
Properties
Note: Not all components need every property. It will differ component to component 
- [ ] Variants: Should be used when the component has several states i.e primary, secondary, error 
- [ ] Boolean: Should be used if the component has a part that does not always need to be shown i.e icons, nested components and mobile view
- [ ] Text: Should be used when the test on a component needs to be changed. There are some exceptions to this if the component has several variants that need to have different/specific text. When you change the text on the parent component it will change all of the variants 
- [ ] Instance Swap 
    - [ ] Should be used if there is a part of the component that needs to be switched out but nothing else needs to change i.e. icons Color contrast (Pro Tip: The plugin “Contrast” can help with this.)
- [ ] Test as a DS library user 
    - [ ] Connect your Figma design file to the DS library found in the Assets panel, Team Library (open book icon)
    - [ ] After connecting to the library, use the Assets panel to view all components
    - [ ] Does the component naming make sense and follow storybook?
    - [ ] Try to break the component! Test on asset NOT parent component 
    - [ ] Expand/shrink the asset and put into containers 
    - [ ]  change body text and/or header from a sentence to paragraph
    - [ ]  make sure text wraps correctly
    - [ ] the component should expand or shrink with text 
    - [ ]  Test all combinations of properties

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2510?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by danbrady** [comment]
@babsdenney @LWWright7 The [component](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=8183%3A45886&mode=design&t=JrjFxcEsDNiFxFMc-1) and [examples](https://www.figma.com/file/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?type=design&node-id=2855%3A36182&mode=design&t=T73mZLN2k3hyfA3J-1) are ready for review. Thanks!
