### ISSUE TITLE
Update USWDS dependencies in component-library

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/vets-design-system-documentation#2512]
## Description
The current version of USWDS used in component-library is out of date and needs to be updated.

## Details
Update the @uswds/uswds version required by web-components and css-library to the latest (currently 3.7.1) version

## Tasks
- [ ] Update and install the newest USWDS version
- [ ] Perform regression testing to make sure components look and operate correctly
- [ ] Have a designer review 
- [ ] Remove css declaration for `.usa-pagination__overflow` in va-pagination.scss (see https://github.com/department-of-veterans-affairs/component-library/pull/1060 and comment in code)

## Acceptance Criteria
- [ ]

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2512?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
