### ISSUE TITLE
Formation Deprecation - Typography base size migration QA vets-website, content-build and vagov-content

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2525]
## Description
With the completion of #2494 , thorough QA needs to be conducted in vets-website prior to any pull request being merged in. This likely means local testing and sandbox testing with the preview instance that gets generated when a pull request is submitted to vets-website and content-build

## Considerations
- [Pull request](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/987) into formation. This should ultimately bump the version number for Formation as well. 
- [Pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/26606) into vets-website. This should include the version change from the above PR, and QA should be conducted using the preview instance and/or verdaccio.

## Tasks
- [ ] Submit PR into content-build and conduct QA
- [ ] Conduct QA on vets-website PR above
- [ ] Scale any rem values applications are using with the rem override functions
- [ ] Merge PRs into vets-website and content-build

## Acceptance  Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2525?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by powellkerry** [comment]
content-build branch: [66753-formation-typography-updates](https://github.com/department-of-veterans-affairs/content-build/tree/66753-formation-typography-updates)

**Comment by powellkerry** [comment]
vagov-content branch: [66753-formation-base-font-bugs](https://github.com/department-of-veterans-affairs/vagov-content/tree/66753-formation-base-font-bugs)

**Comment by powellkerry** [comment]
This ticket will not be completed by March 27th. The work should be completed within the next week. A seperate card will be created to merge this effort into vets-website after team approvals.

**Comment by powellkerry** [comment]
Closing this ticket with a successful CI run in vets-website. This will be merged in upcoming work.
