### ISSUE TITLE
Component-Library: import elements.css globally

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/vets-design-system-documentation#2527]
## Description
The elements.css file is currently imported on a few, forms pattern, components. These imports need to be removed and an import needs to be included globally here: https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/global/main.css

## Details
This change will mainly affect the look of any component that has headings (h1-h6). Regression testing will need to be done to make sure that components maintain their intended styles.

## Tasks
- [ ] Remove existing imports on checkbox-group.scss, memorable-date.scss, number-input.scss, va-radio.scss, va-text-input.scss, va-textarea.scss
- [ ] Add import to https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/global/main.css
- [ ] Validate that this change does not adversely affect other components. Components with headers that may be affected: alert, modal, process list, statement of truth, and summary box

## Acceptance Criteria
- [ ] @import '~@department-of-veterans-affairs/css-library/dist/elements.css'; is imported globally in main.css
- [ ] Regression testing has been performed and design has verified the changes

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2527?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
