### ISSUE TITLE
Update Divider component in Storybook 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2532]
## Description
The divider component needs the following updates: 
- Update "Stars" to be an `<hr/> `rather than a div.
- Show a regular "non-stars" version of a divider.

## Details
Experimental design request this stems from [https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1785](url)
Ticket that has the Figma updates [https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2510](url)

## Tasks
- [ ] Update divider component in Storybook
- [ ] Get a designer to review 
- [ ] Post update 

## Acceptance Criteria
- [ ] Divider component has the two updates

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2532?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
