### ISSUE TITLE
Formation Deprecation - Icon Migration Script

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2534]
## Description
With the issues around va-icon being resolved in [this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2353), we can now provide teams with guidance for migrating onto using `va-icon`. One aspect of this is making it as easy as possible to migrate off of font awesome and onto `va-icon`. We previously provided migration scripts teams could use for components, and we should do something similar here. 

## Considerations
- [Existing Migration script](https://github.com/department-of-veterans-affairs/vets-website/blob/626c613e16198ffa5591494168c03d0dc5bd6e95/script/component-migration/index.js#L2) for components

## Tasks
- [ ] Write a migration script that converts font awesome icon usages to `va-icon` 
- [ ] Include a JSDOC comment for how to use the script

## Acceptance Criteria
- [ ] Script has been created and documentation has been written for how to use it.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2534?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Could we do something like what we did for auto-fixing `<a href="tel:...` to `va-telephone` using an ESLint rule like this?

- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/863

This would be a one-click convert from within the ES Lint pop-up.

If so, if feels like this other ticket might be a duplicate:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2535
