### ISSUE TITLE
Injected Header - Add eslint warning & inline comments for React Modals that should not be touched

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2541]
## Description
The injected header for teamsites recently broke again due to a React Modal Component being replaced with a web component. In order to alert teams that they shouldn't touch specific Modal Components, we should add an eslint warning and inline comments for each instance. 

## Tasks
- [x] Add eslint warning for React Modal components. This should warn teams not to touch any modals in `/platform/forms/save-in-progress` and `platform/user/authentication`. 
- [x] Add inline comments above each React Modal import at the above paths saying something along the lines of `// React Modal Component used in Injected Header DO NOT MIGRATE to Modal web component`

## Acceptance Criteria
- [ ] Above tasks have been complete

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2541?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
