### ISSUE TITLE
Add an ignore or threshold to false UI diffs in va-banner and va-loading-indicator

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2547]
## Description

The Chromatic Visual Testing tool is flagging dynamic elements as UI regressions and we need to approve them each time a PR is updated. It's expected that these changes would happen though and they are not actually regressions.

![Screenshot 2024-02-28 at 11 57 20 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/9fd3ad90-2687-4ad6-b9b4-17a754b9fe73)

![Screenshot 2024-02-28 at 11 57 13 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/a5dd67b2-3c53-470d-9141-428362a459bf)

We should be able to tell Chromatic to ignore these changes, or, change the threshold so that it is not so sensitive according to these docs:

- https://www.chromatic.com/docs/ignoring-elements/
- https://www.chromatic.com/docs/threshold/

## Tasks
- [ ] Review the instructions linked above on how to ignore DOM elements or change the threshold for elements.
- [ ] Make the necessary updates.
- [ ] Review with a designer to make sure we are not ignoring too much or too little.

## Acceptance Criteria
- [ ] False positive UI regressions are no longer being flagged in the UI Tests PR check.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2547?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by danbrady** [comment]
Capturing some things that came up in discussion:
1. We don't want to flag animations (ex. Loading indicator)
2. We don't want to flag text changes (ex. timestamp in banner)
3. We do want to capture slight color changes
4. What amount of pixel differences is "ok"?

As mentioned and linked to above, there are two options to explore: Ignore DOM elements and adjusting difference Threshold. 

Ignoring DOM elements could fix these, however it can be heavy-handed. For example, if we ignore the loading indicator spinning icon element, Chromatic would not catch if its color was changed.

Adjusting threshold could these as well, however it might inadvertently ignore cases where small pixel differences could be problematic. For example, an inline icon position shifting. (This leans into 4 above.)

Ideally, it would be nice if we could do both - Adjust the threshold for particular DOM elements, but I don't think that's a possibility?

We can probably debate 4 more, but I think it'll come down to trial-and-error with the tool to find what is acceptable. 

@jamigibbs, @rmessina1010 - Please correct me if I misrepresented or simply missed anything. 😄

(Additional resource on [animations in Chromatic](https://www.chromatic.com/docs/animations/).)
