### ISSUE TITLE
Formation Deprecation - Typography base size migration QA component-library

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2566]
## Description
In addition to #2494, #2525, and #2431, we need to ensure the formation overrides in component-library are properly scaled so visual parity is maintained on VA.gov. 

QA needs to be conducted in vets-website prior to any pull request being merged in. This likely means local testing and sandbox testing with the preview instance that gets generated when a pull request is submitted to vets-website and content-build. 

## Considerations
- [Pull request](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/987) into formation. This should ultimately bump the version number for Formation as well. 
- [Pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/26606) into vets-website. This should include the version change from the above PR, and QA should be conducted using the preview instance and/or verdaccio.
- [component library formation overrides](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/global/_formation_overrides.scss)
- Some components, such as [va-accordion-item](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-accordion/va-accordion-item.scss#L42) also declare rem values directly in their respective stylesheets. These need to be updated as well. 

## Tasks
- [ ] Conduct QA on vets-website PR above
- [ ] Scale any rem values in component library that need to be scaled
- [ ] Merge PRs into vets-website and content-build

## Acceptance  Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2566?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
The `_formation_overrides.scss` stylesheet will need to be removed as part of this work:

https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/global/_formation_overrides.scss

This stylesheet is what we used to "correct" the old Formation base font size.

**Comment by caw310** [comment]
More than one engineer will work on this effort.

**Comment by powellkerry** [comment]
component-library branch: [66753-formation-typography](https://github.com/department-of-veterans-affairs/component-library/tree/66753-formation-typography)

**Comment by powellkerry** [comment]
This will carry over due to delays in the Formation QA ticket. A PR should be spun up in the next couple of days and this ticket should be closed soon after.

**Comment by powellkerry** [comment]
PR: https://github.com/department-of-veterans-affairs/component-library/pull/1096
