### ISSUE TITLE
Add Eyebrow Component to Figma - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2579]
## Description
Create Eyebrow component in Figma. Touch base with Christina to get the design file. 

## Details
Confluence page with instructions: https://vfs.atlassian.net/l/cp/JR0BtAa1
Experimental Design Request [url](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2186)

We aren't sure how this design will be implemented in code which determines how it would be implemented in Figma. We need to have a discussion with the Engineering team to figure out how this will coded. 

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2579
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2580
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2581

## Tasks

- [ ] Discuss with Engineers on how they will implement this design
- [x] Create designs for component in Figma
- [ ] Review designs with PO and/or other DST designers
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members 
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
Styles & Variables/Token 
- [ ] All components should be connected to VADS Component Library styles & Variables 
- [ ] All components should be connected to the proper style or variable/token 
    - [ ] Colors: connected to the correct color token (not primitive!) - can be found in local variables library 
    - [ ] Typography: connected to the correct text style - under local styles
    - [ ] Spacing: connected to the correct spacing token or primitive 
    - [ ] Icons: connected to correct icon - can be found on foundation page 
Auto layout
- [ ] Components should be as reactive as possible. Most, if not all, components should be able to be resize for either mobile, tablet, or desktop sizes 
- [ ] The correct spacing should be applied to auto layout 
Properties
Note: Not all components need every property. It will differ component to component 
- [ ] Variants: Should be used when the component has several states i.e primary, secondary, error 
- [ ] Boolean: Should be used if the component has a part that does not always need to be shown i.e icons, nested components and mobile view
- [ ] Text: Should be used when the test on a component needs to be changed. There are some exceptions to this if the component has several variants that need to have different/specific text. When you change the text on the parent component it will change all of the variants 
- [ ] Instance Swap 
    - [ ] Should be used if there is a part of the component that needs to be switched out but nothing else needs to change i.e. icons Color contrast (Pro Tip: The plugin “Contrast” can help with this.)
- [ ] Test as a DS library user 
    - [ ] Connect your Figma design file to the DS library found in the Assets panel, Team Library (open book icon)
    - [ ] After connecting to the library, use the Assets panel to view all components
    - [ ] Does the component naming make sense and follow storybook?
    - [ ] Try to break the component! Test on asset NOT parent component 
    - [ ] Expand/shrink the asset and put into containers 
    - [ ]  change body text and/or header from a sentence to paragraph
    - [ ]  make sure text wraps correctly
    - [ ] the component should expand or shrink with text 
    - [ ]  Test all combinations of properties

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2579?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by LWWright7** [comment]
@caw310 Can you please tell us who the Christina is from this ticket? thanks

**Comment by LWWright7** [comment]
@babsdenney @danbrady This is ready for review

**Comment by LWWright7** [comment]
@cgednalske Since you were the one who brought this design to DSC, how do you feel about the incorporation of the Eyebrow component with a title?  @danbrady  Had the idea (see above post) and I have fleshed out his creation in the world of Figma [here](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=13259-10&t=aLSOkhGt5mSZDcc6-1).    Also, would a "bottom" eyebrow be useful / beneficial for the purposes you are using the eyebrow here? And final question, is all caps formatting/styling necessary or vital to this eyebrow component? Could it be regular VADS paragraph / body type?

Also, @rachelshearerux / @jeana-adhoc , wanted to get your 2 cents here as this may be used in Forms, possibly? Please give your feedback here. 

Final thought, would this be H1 and possibly H2 titles only? Or only H1?  H3 looks pretty small and unnecessary in that Figma component.

**Comment by cgednalske** [comment]
@LWWright7 interesting questions! Incorporating the title as part of the component is not something we considered, but that does seem like a helpful change that would further clarify where and how the eyebrow can be used. 👍 

I'm less sure about the other questions, though I do think they're somewhat entwined. We intended for the H1 to be the only heading the eyebrow could go with - to clarify that an entire page's contents belongs to a certain flow if Veterans are completing a sub-task within it that might seem unrelated, but I'd be curious about other scenarios that could call for an eyebrow for H2s and H3s. 

Similarly, when it comes to the top or bottom placement, consistency above the title seems key if it's meant to represent "what you're doing on this page is still under the umbrella of the eyebrow topic" (unless there are a11y improvements with the bottom placement that I'm not aware of).

But, all that being said, if there are good use cases for any of those, we are of course open to changes!

**Comment by LWWright7** [comment]
@rachelshearerux and @jeana-adhoc I meant to touch on this topic this morning in our meeting about the release process....but totally spaced it off 

Any input here on this??

**Comment by jeana-adhoc** [comment]
Within a form flow, I haven't encountered a need for this. I could see future needs in cards that might be in forms; but we haven't encountered them yet. @rachelshearerux - have you see any?   

In regards to Dan's comment - the "toenail"/Subtitle as he describes it in relation to the form title, wouldn't be included in an <h1>. It's a separate subtitle.  

Let me know if I missed anything that I should respond to.

**Comment by rachelshearerux** [comment]
I second @jeana-adhoc's comment that I haven't run across a need for this either. 

> We intended for the H1 to be the only heading the eyebrow could go with - to clarify that an entire page's content belongs to a certain flow if Veterans are completing a sub-task within it that might seem unrelated, but I'd be curious about other scenarios that could call for an eyebrow for H2s and H3s.

I can see this being an interesting approach, but so far we've used other components and patterns. 

We had a use-case for a subtask in the context of VA Form 21-4138, and we just wrapped research into our design that used an experimental `subtask` pattern in VA Form 21-4138. We also implemented the minimal header, which meant our form title lived elsewhere from our page-level H1s. We wrapped [research](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/research/2024-03-reduce-4138-submissions) recently, and the new designs are [here in this figma](https://www.figma.com/design/w2tRlZ5qJSOF968XoWzBRg/Staging-%7C-21-4138---Submit-a-statement-to-support-a-claim?node-id=2961-56377&t=76dhHutZREjLmAdF-1). We'll present our findings on 9/16 in the design all-hands meeting. 

We've relied on the `progress indicator` component to communicate with folks where they are in the flow, though past research on that particular component showed mixed results in terms of how helpful it is for folks. (Finding #2 [here](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/research/2023-09-form-header-usability-testing/research-findings.md#key-findings:~:text=Users%20are%20confused%20by%20the%20relationship%20between%20a%20section%20and%20a%20given%20page.%20They%20expected%20the%20stepper%20component%20to%20reflect%20incremental%20progress%20on%20each%20new%20page%2Dload))

**Comment by cgednalske** [comment]
I should also clarify that our team uses the eyebrow to clarify a side task belongs to the same flow because other form patterns/components do not work with our application (progress indicator, form title in the minimal header, etc.). Check-in is not a true form in the traditional sense, so it was necessary to create something new that could call this out.

**Comment by jinaryu** [comment]
Hi @cgednalske I found this ticket digging through some slack threads.. my team (disability benefits experience) is also using the eyebrow for the same purpose as your team. (Figma example [here](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-86069&t=Z4ORuAESTJLFgtlg-1))

How did using the eyebrow work out for your team?
