### ISSUE TITLE
Add Eyebrow Component to Storybook - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2580]
## Description
Add Eyebrow Component (which is an experimental design request) to Storybook . Be sure to add analytics if necessary, see [guidance](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
- Design documents: [add links to any design documents] Design ticket [https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2579](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2579)
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)
- Experimental Design Request [https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2186](url)

## Tasks
- [ ] **Regroup with designer to sync on dev/accessibility approach (in case it affects figma library)**
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Contact designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2580?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Please add your estimate of 1, 2, 3, 5, 8 or 13
@Andrew565 
@ataker 
@harshil1793 
@it-harrison 
@jamigibbs 
@micahchiang 
@powellkerry 
@rmessina1010 
@rsmithadhoc

**Comment by jamigibbs** [comment]
Figma link: https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=14311-5553&p=f&t=VYNKqHwJUa15JLK8-0

**Comment by Andrew565** [comment]
Decision was made to explore implementing this in CSS-Library rather than making a full web component. Consider a CSS Module.

**Comment by humancompanion-usds** [comment]
Sadly, looking at the notes from DSC, this was implemented in Check-in as a span within the heading. But we didn't make it a block element so....

![Image](https://github.com/user-attachments/assets/54c7b9fa-315d-45e7-8f07-42f54417e292)

I believe it was implemented that way so that it would be read out along with the heading. Essentially, I believe this has to be a span styled to be a block element to meet the a11y needs and be valid HTML.
