### ISSUE TITLE
Add Language toggle to Figma DS Library - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2582]
## Description
Create Language Toggle component in Figma. 

## Details
Confluence page with instructions: https://vfs.atlassian.net/l/cp/JR0BtAa1
[Experimental Design Request for Language toggle for multi-lingual content](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/667)

## Tasks
- [x] Create designs for component in Figma
- [x] Review designs with PO and/or other DST designers
- [x] Review designs with an accessibility specialist
- [x] Review designs with DST members 
- [x] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
Styles & Variables/Token 
- [ ] All components should be connected to VADS Component Library styles & Variables 
- [ ] All components should be connected to the proper style or variable/token 
    - [ ] Colors: connected to the correct color token (not primitive!) - can be found in local variables library 
    - [ ] Typography: connected to the correct text style - under local styles
    - [ ] Spacing: connected to the correct spacing token or primitive 
    - [ ] Icons: connected to correct icon - can be found on foundation page 
Auto layout
- [ ] Components should be as reactive as possible. Most, if not all, components should be able to be resize for either mobile, tablet, or desktop sizes 
- [ ] The correct spacing should be applied to auto layout 
Properties
Note: Not all components need every property. It will differ component to component 
- [ ] Variants: Should be used when the component has several states i.e primary, secondary, error 
- [ ] Boolean: Should be used if the component has a part that does not always need to be shown i.e icons, nested components and mobile view
- [ ] Text: Should be used when the test on a component needs to be changed. There are some exceptions to this if the component has several variants that need to have different/specific text. When you change the text on the parent component it will change all of the variants 
- [ ] Instance Swap 
    - [ ] Should be used if there is a part of the component that needs to be switched out but nothing else needs to change i.e. icons Color contrast (Pro Tip: The plugin “Contrast” can help with this.)
- [ ] Test as a DS library user 
    - [ ] Connect your Figma design file to the DS library found in the Assets panel, Team Library (open book icon)
    - [ ] After connecting to the library, use the Assets panel to view all components
    - [ ] Does the component naming make sense and follow storybook?
    - [ ] Try to break the component! Test on asset NOT parent component 
    - [ ] Expand/shrink the asset and put into containers 
    - [ ]  change body text and/or header from a sentence to paragraph
    - [ ]  make sure text wraps correctly
    - [ ] the component should expand or shrink with text 
    - [ ]  Test all combinations of properties

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2582?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by babsdenney** [comment]
@danbrady @LWWright7 This is [ready for review](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=10077-912).

**Comment by danbrady** [comment]
@babsdenney The design looks great. The spacing helps a lot!

We might be able to simplify the properties a little. Instead of having 5 properties for each language and divider, can we group the language name with its leftmost divider and put the show/hide boolean on that group? This way, that toggle controls both the divider and the language together.

Also, do we need to hide English? Or said another way, are there any pages that do NOT have an English version? If that's not the case, We can get the properties down to 3:

* Active Language (select with 3 options)
* Show Spanish (This controls the layer group of "Espanol" and the divider to it's left)
* Show Tagalog (This controls the layer group of "Tagalog" and the divider to it's left)

Thoughts?

**Comment by babsdenney** [comment]
@danbrady That's a great idea! I did try that initially but now I'm realizing reading your feedback that I grouped the dividers in the wrong way causing extra dividers if you hid things incorrectly. 

I like the idea of removing the hide english option. That will make things cleaner. 

Great ideas! I'll get started on this.

**Comment by babsdenney** [comment]
@danbrady @LWWright7 This is ready for review again.

**Comment by LWWright7** [comment]
@babsdenney This looks good to me! Great work Barb!

**Comment by danbrady** [comment]
@babsdenney Looks good to me too!

**Comment by babsdenney** [comment]
@humancompanion-usds @danbrady @LWWright7 

[This is ready for review again](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=10077-912). I remembered that we have the breadcrumbs that we recently converted the bold links to blue links so I think we have to follow that same design here. I found the example of the underline link example on MyHealthVet portal and used the same gray they are using for the dividers on the language toggle as well.

**Comment by danbrady** [comment]
Looks good to me, @babsdenney! Those underlines are 🔥!

**Comment by LWWright7** [comment]
@babsdenney Good to go Barb! 🚀

**Comment by babsdenney** [comment]
@rsmithadhoc Do you see any accessibility issues with the [new design of this language toggle](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=10077-912)?

**Comment by rsmithadhoc** [comment]
> @rsmithadhoc Do you see any accessibility issues with the [new design of this language toggle](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=10077-912)?

@babsdenney No issues here. We should be able to code it so that the currently selected language is announced when using a screen reader and also appropriately label the vertical separator between languages. Thanks!
