### ISSUE TITLE
Language toggle component- Update documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2585]
## Description
Add documentation and guidance for Language toggle web component on design.va.gov. When adding a new component, use the [component documentation template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/src/_components/template.md).

## Details
- [Experimental Design Request for Language toggle for multi-lingual content](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/667)
- [Design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2582)
- [Accessibility review ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2584)

Be sure to use the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option. If this is a new component that has not yet gone through Staging Review, use the "Use with Caution: Candidate" label.

## Tasks
- [X] Write or update component documentation for design.va.gov
- [X] Coordinate with accessibility specialist to create or update accessibility guidance
- [X] Request documentation draft review
- [ ] Update the guidance with the Storybook example 
- [ ] Remove the production example for now since it will be the old design
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
To be clear, I already [created documentation](https://design.va.gov/components/language-toggle). I'm guessing this issue is to update it once the component has been turned into a web-component.

**Comment by caw310** [comment]
@danbrady there is a dev ticket. I believe this should be in a sprint after development is done. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2583
