### ISSUE TITLE
Update components section in Storybook 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2589]
## Description
Move the components that do not have a v3 version up and under "Components" in Storybook. 

## Details
Here are some of the components that may need to be moved but an audit should be done to make sure this is accurate and if there are others not on this list:

- Alert - expandable
- Back to top
- Banner - Official Gov
- Banner - Promo
- Card
- Date input
- Header - Minimal
- Link
- Loading indicator
- Memorable date
- Minimal Footer
- Need help?
- OMB Info
- On this page
- Telephone

## Tasks
- [ ] Identify which components do not have a v3 version that should be moved to the Components section of Storybook (see list in details and check if there are any others)
- [ ] Move those to Components section in Storybook
- [ ] Get designer to review and confirm
- [ ] Update Storybook

## Acceptance Criteria
- [ ] Components in Storybook have both v3 components and ones that do not have a v3 version that can be used by VFS teams

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2589?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
