### ISSUE TITLE
va-icon: add option for changing the icon color

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2601]
## Description

Some teams are using the Font Awesome icons with a color override so to allow them a migration path to the `va-icon` web component, we should add a color option to the web component.

### Consideration

We may want to try and only allow a color token to be passed into the prop that is currently available in the CSS Library. This might be possible by importing the JSON token file that the CSS Library generates and just doing a match against whatever value is added to the prop.

https://design.va.gov/storybook/?path=/docs/uswds-va-icon--default

Because the `.usa-icon` class has `currentColor` set for the fill value, I think we can just apply `fill` to the svg element in the component:

<img width="791" alt="Screenshot 2024-03-18 at 4 51 15 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/0107f26f-3452-4165-9bdc-c9e044220442">

## Tasks
- [ ] add a color option to the `va-icon` web component
- [ ] write tests for the new option
- [ ] update the icon migration guidelines if necessary

## Acceptance Criteria
- [ ] the va-icon web component allow the icon color to be changed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2601?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by pmclaren19** [comment]
Using the `va-accordion` and each item has a `va-icon`. This icon should be a specific color given how far in the claim phases a user is. In this example I want the checkmarks to be green and the flag to be blue. I cant pass in `'vads-u-color--green'` or `'vads-color-primary'` to the className and there is no color prop. So the only way to do this is to have a customized classname that sets the color. 
Image of what I want (Figma Design):
![Screenshot 2024-05-13 at 8 35 13 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/141954992/457e7421-c0d4-45a2-8f56-e003846c865f)
Image of what I currently have without setting customized class names and then setting the color:
![Screenshot 2024-05-13 at 8 34 11 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/141954992/742b8ada-b9b7-4351-b0f5-c3debc2b61d0)

**Comment by jamigibbs** [comment]
Peri was able to apply a color to the SVG by assigning a `color` to the va-icon element. [See Slack convo here](https://dsva.slack.com/archives/C01DBGX4P45/p1715613590750909?thread_ts=1715375749.388949&cid=C01DBGX4P45).

It looks like because USWDS has this style applied..

```css
.usa-icon {
  fill: currentColor
}
```

...the SVG will accept `color` from the parent element. So we may not need to add a prop here at all.

**Comment by Andrew565** [comment]
```
<va-icon class="color-class-name" icon="someIcon"></va-icon>

.color-class-name {
  color: red; // or whatever color you want
}
```

**Comment by jamigibbs** [comment]
@humancompanion-usds Feel free to take over this PR if you need to edit anything: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/2866

**Comment by humancompanion-usds** [comment]
Guidance has been updated. Styling via a class is the way to go.
