### ISSUE TITLE
Add number input functionality to text input

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2613]
## Description
In order to deprecate number input in favor of using text input, any existing number input functionality that doesn't already exist in text input needs to be migrated over. A brief look at `va-number-input` suggests that we'll need to move: 
- `inputmode?: 'decimal' | 'numeric'` 
- `min` and `max` number values
- `currency`

We may want to reuse the regex pattern currently used in `va-number-input`. 

## Considerations
- existing number input tests can likely be modified and reused for the extended text input

## Tasks
- [x] Add non-overlapping number input functionality to text input
- [x] Update text input tests
- [ ] Update number input storybook entry with messaging about upcoming deprecation

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2613?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by it-harrison** [comment]
@danbrady - currently the v3 version of `va-number-input` does not include a currency option, but v1 does; just checking do we want to include currency in the v3 version of `va-text-input`?

**Comment by danbrady** [comment]
If I'm reading [this issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2613) regarding the transition strategy right, I believe we do:

> step one: adding all non-overlapping functionality to va-text-input

However, we'd likely get more mileage out of adopting the [USWDS input prefix/suffix](https://designsystem.digital.gov/components/input-prefix-suffix/), but perhaps that's a follow-up step.

@humancompanion-usds What do you think?

**Comment by it-harrison** [comment]
PR is [here](https://github.com/department-of-veterans-affairs/component-library/pull/1143)

**Comment by humancompanion-usds** [comment]
@caw310 - Please be sure that an issue to add USWDS prefix/suffix to va-text-input exists and is slated for an upcoming sprint. Adding support for currency is a pre-req to deprecating va-number-input. Thanks!
