### ISSUE TITLE
Number input deprecation strategy

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2614]
## Description
In order to diligently prepare teams for number input deprecation, we need to provide them with proper strategy. This includes communicating out a timeline for when the deprecation will happen and guidance on how existing instances of `va-number-input` can be migrated to `va-text-input` 

## Considerations
- We probably want to take a multi-step approach to deprecating number input which might include:
  - step one: adding all non-overlapping functionality to `va-text-input` but keeping both components in production, allowing for some transition time
  - step two: conduct a follow up release that completely removes `va-text-input`
 
## Tasks
- [ ] Establish a future date for steps one and two under considerations
- [ ] Write a guide for how teams can migrate from `va-number-input` to `va-text-input`
- [ ] Send out communication in #vfs-change-announcements for the above information

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2614?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
