### ISSUE TITLE
Remove number input from component library

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2615]
## Description
Once #2613 and #2614 have been completed, and the overlap time determined in #2614 has elapsed, we need to remove `va-number-input` from the component library, the documentation site, and storybook. 

## Tasks
- [x] Remove number input from component library
- [x] Remove storybook entry in storybook package

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2615?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
We may want to resolve this issue before removing:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3112
