### ISSUE TITLE
Discovery: Research and propose aria-describedby alternatives

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2619]
## Description

Recently, a change was made to Mac that means `aria-describedby` text is no longer read out by default when tabbing to an associated input field. We use this for important hint text as well as error messages. This is to determine the impact on users and propose alternative solutions.

[Related issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2572).

## Details

- Look into the impact:
    - Which devices - is it just Mac/Safari or iOS too?
    - How many places do we use `aria-describedby` for what? Is there guidance we can provide to reduce its usage?
- Look into some options:
    - Putting all of the hint and error text within the `label` tag.
    - Error summary box.
- Propose solutions
    - What should we change?
    - Is this something to bring to USWDS?

## Tasks
- [ ] Research impact, options.
- [ ] Write up proposals on how we can solve this to share with stakeholders.

## Acceptance Criteria
- [ ] Potential options have been documented for the team to review.
