### ISSUE TITLE
Create documentation about web component analytics

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2625]
## Description
There have been a couple of occasions recently where there has been confusion or incorrect assumptions about how design system web component analytics works. Specifically the `component-library-analytics` event and the `enable-analytics` or `disable-analytics` props as well as what information the components are sending by default.

The design system doesn't currently have any clear documentation to point teams to on how all of this works which is what this ticket should do.

[Per Jamie Stutt](https://dsva.slack.com/archives/CKCRMLGAC/p1709660356752259?thread_ts=1709653964.294149&cid=CKCRMLGAC) in Platform Analytics, teams have one of two options

1. Use the web component's default events (no further action necessary), or,
2. Set `disable-analytics` to true to turn off the component's tracking and re-implement a custom event

The very strong preference is the first option to let components do the analytics work. Custom events tends to be where the bigger risks of upstream/future issues come from as well as adding more maintenance overhead to teams.

It's often misunderstood how that first option works though and how to do something different like option two so the documentation task here is to add some clarity for those two different approaches (but **not** to do a deep dive into the larger topic of Google Analytics).

### Other considerations

Form components (input, select, textarea, etc) have analytics turned **off** by default. That is why they have the prop `enable-analytics`. Non-form components (button, alert, etc) have analytics turned **on** by default. That is why they have the prop `disable-analytics`. This is the type of information that should go into the documentation.

## Tasks
- [x] Write public documentation for teams to reference how to use design system web component analytics
- [x] Document the analytics data that individual components are sending. [For example](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-alert/va-alert.tsx#L145-L153).
- [ ] Review with the platform analytics team as needed (Jamie Stutt)

## Acceptance Criteria
- [ ] design system analytics doumentation exists

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2625?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Update Platform documentation has been drafted below:

- https://docs.google.com/document/d/1rnM6J6z-CHZDH7URpw-ORHnibvqPbn3MjdpgD0Tlrs8/edit?usp=sharing

**Comment by Andrew565** [comment]
Documentation looks good to me!

**Comment by ataker** [comment]
Small feedback left, but looks good to me 👍
