### ISSUE TITLE
Update the "Icon Found" bot in vets-website and content-build for va-icon

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2626]
## Description

There are workflows that check PRs in vets-website and content-build for `<i` elements and flags that element to remind the developer to add semantic meaning to the icon if necessary.

![Screenshot 2024-03-25 at 12 08 04 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/79e7ff0e-5661-416a-8c93-2812dde20937)

## Details

Since the design system is moving from Font Awesome to `va-icon`, we should consider updating those workflows to accommodate that change.

- [vets-website icon workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/bd0b3284b4759846a84a417b9ae97420014f45d7/.github/workflows/pull-request.yml#L138-L194)
- [content-build icon workflow](https://github.com/department-of-veterans-affairs/content-build/blob/34a836d2104038f8dc6c5f24a8691b98911504e3/.github/workflows/manual-review.yml#L71-L130)

## Tasks
- [ ] add a check to both workflows to check for `va-icon` as well as `<i`
- [ ] Add a message that Font Awesome is deprecated and to use `va-icon` instead with a link to the migration documentation

## Acceptance Criteria
- [ ] both icon workflows are updated for va-icon and Font Awesome deprecation
- [ ] the workflow still displays a message to check that the icon has semantic meaning
