### ISSUE TITLE
Create ESLint rules  for required slotted elements in web-components 

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/vets-design-system-documentation#2627]
## Description
The ticket [https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2557](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2557) exposed a need to communicate to VFS teams the requirement of specific slotted elements and while we cursively solved this with an update to DST documentation, a more robust system of enforcement, such as eslint rules  would provide a better developer experience. It would be most efficient if said eslint rules were generalized to components and configurable to add details of present and future  components. 

## Tasks
- [ ] For each  audit allow composition rules ( slotted components) for each v3  component in the design system to access what slotted elements  required or recommended
- [ ] Write eslint rules that encompass the findings of the audit and 
- [ ] Announce to VA engineers

## Acceptance Criteria
- [ ]
