### ISSUE TITLE
va-summary-box  - Update Documentation to reflect that header slot is required

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/vets-design-system-documentation#2632]
## Description
Add or update documentation and guidance for  `va-summary-box` on design.va.gov. When adding a new component, use the [component documentation template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/src/_components/template.md).

## Details
This issue is regarding  [2557](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2557). Update this documentation to reflect that we _require_   a header slot be passed in.

Current docs usage states:

> Features should use a h3 or h4 heading depending on what the appropriate heading level is for your page based on the content of your page.
If this language is not strong enough, update to something stronger?

## Tasks
- [ ] Update component documentation for design.va.gov as described, plus any related details
- [x] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov
