### ISSUE TITLE
Upgrade Storybook to 7

### ISSUE THREAD

**Issue by ataker** [department-of-veterans-affairs/vets-design-system-documentation#2634]
## Description
Upgrade Storybook to the latest version 7 release (currently 7.6.17).

## Details
Our discovery process is detailed in [this doc](https://vfs.atlassian.net/wiki/spaces/DST/pages/3035594769/Discovery+Upgrading+Storybook+to+7+or+8) to help out line how to do the upgrade. Also you can start from [this branch](https://github.com/department-of-veterans-affairs/component-library/tree/storybook-7-test) to pick up where discovery left off.

## Tasks
- [ ] Upgrade Storybook to 7.6.17
- [ ] Update mdx files to ensure compatibility with Storybook 7
- [ ] Find a replacement for the [html previewer we were previously using](https://www.npmjs.com/package/@whitespace/storybook-addon-html)
- [ ] Test components to make sure they look and function correctly

## Acceptance Criteria
- [ ] Working Storybook 7 build

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2634?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Work on this is done but this ticket will carry over due to issues with tests.
