### ISSUE TITLE
File Input - Update v3 component to align with Figma

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2642]
## Description
After [2641](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2641) is complete, V3 file input needs to be updated to align with [designs in Figma](https://www.figma.com/file/UZys4hvw2Vwuo7U0pwbKbq/File-Input-v3?type=design&node-id=71-25203&mode=design). Specifically, it needs to include: Change File button, delete button, and cancel upload button. It also needs an upload progress bar. Finally, it needs to be updated to include a slot that can be filled with a select input, text input or something else to convey additional information about the file. 

## Screenshots

<details><summary>Icon Buttons for file input</summary>

<img width="310" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c0fdb55ac28e590dd3d6901a470ebc689c30dea/Screenshot%20from%202024-03-29%2012-18-15.png" alt="Screenshot from 2024-03-29 12-18-15.png" />

</details>

<details><summary> Additional information file input </summary>

<img width="310" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0FoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce125d7a3745e00aebb9c3b816e8ae893ce51281/image.png" alt="image.png" />

</details>

## Tasks
- [ ] Add buttons and progress bar to file input
- [ ] Add additional information slot

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2642?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Work on this was also impacted by sick leave.

**Comment by nickjg231** [comment]
A first draft of this is finished but there are additional questions we as a team need to discuss, so this will carry over. Some of these questions include:

1. Should we find a way to handle the progress bar, or look into whether users can use the slot to implement their own
2. When should we truncate the file name for long files
3. The math for the file size is calculating a slightly smaller value than the file system's file size
4. Should we use the file logic that already exists for displaying previews of files users are uploading

**Comment by nickjg231** [comment]
Ticket is done but waiting approval from Matt. If approved, it can be merged. Otherwise, it'll carry over.

**Comment by humancompanion-usds** [comment]
@nickjg231 - Where can I see the component in order to review it?
