### ISSUE TITLE
Remove V1 Components from Component Library and Storybook

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2645]
## Description
On May 3 the design system team will permanently sunset all V1 components that have a V3 equivalent EXCEPT va-table and va-file-input. 

All web components that do not have a V3 will remain. 

## Considerations
- Leave va-table and va-file-input alone

## Tasks
- [ ] Remove V1 components from component library
- [ ] Remove storybook entries for V1 components

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2645?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
+1 for separate tickets, maybe 1-3 components per ticket at most?

**Comment by jamigibbs** [comment]
> +1 for separate tickets, maybe 1-3 components per ticket at most?

Or at the very least, separate PRs for each component so it can be reviewed and tested easier.

**Comment by micahchiang** [comment]
Closing in favor of #2657 - #2667
