### ISSUE TITLE
[va-checkbox] - Add Indeterminate State - Design

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2653]
## Description
In [USWDS 3.8.0](https://github.com/uswds/uswds/releases/tag/v3.8.0), the checkbox has a new [indeterminate state](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes). We should bring this capability into VADS.

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [x] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2653?planning-poker) with Zenhub @danbrady @LWWright7 @babsdenney

**Comment by danbrady** [comment]
Adding link to the [USWDS Storybook](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-form-inputs-checkbox--default&args=indeterminate_state:true) that shows an example of an indeterminate state. (FYI, we noticed their doc site has subtle differences from the OOTB USWDS. So we should always be referencing their storybook when investigating styles.)

**Comment by babsdenney** [comment]
@danbrady @LWWright7 This is ready for review. 

[Indeterminate checkbox - Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=137-17116)

**Comment by LWWright7** [comment]
@babsdenney Hey Barb! This looks good to me!
