### ISSUE TITLE
Migrate v1 va-alert to v3 in vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2657]
## Description
At the end of July all v1 component code will be removed. To do this we need to migrate the remaining instances of v1 va-alert to v3.

Remaining Instance paths: 
va-alert	src/applications/burials
va-alert	src/applications/disability-benefits/686c-674
va-alert	src/applications/lgy
va-alert	src/applications/static-pages/facilities
va-alert	src/applications/vre

## Tasks
- [x] migrate all v1 va-alerts to v3
- [x] update any tests that break

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2657?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
`va-alert` is a child component of `va-banner`

**Comment by it-harrison** [comment]
All instances have been updated except those in `/burials` where the PR could not pass CI but this app is shortly [scheduled for removal](https://dsva.slack.com/archives/C057W3N9K2S/p1721685811098329?thread_ts=1721684028.373489&cid=C057W3N9K2S) from `vets-website`.
