### ISSUE TITLE
Migrate remaining V1 Breadcrumbs to V3 in vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2658]
## Description
Our goal is to remove v1 component code at the end of July. To do this, we need to update the remaining instances of V1 components in vets-website. This ticket is for migrating the remaining V1 breadcrumbs to v3.

## Considerations
Remaining instances:

va-breadcrumbs | src/applications/accredited-representative-portal/components/common | va-platform-cop-frontend
-- | -- | --
va-breadcrumbs | src/applications/ask-va/components | va-platform-cop-frontend
va-breadcrumbs | src/applications/fry-dea | my-education-benefits
va-breadcrumbs | src/applications/health-care-supply-reordering | va-cto-health-products
va-breadcrumbs | src/applications/ivc-champva/10-7959f-1/containers | va-platform-cop-frontend
va-breadcrumbs | src/applications/ivc-champva/10-7959f-2/containers | va-platform-cop-frontend
va-breadcrumbs | src/applications/simple-forms | platform-va-product-forms
va-breadcrumbs | src/applications/static-pages/manage-va-debt | vsa-debt-frontend
va-breadcrumbs | src/applications/verify-your-enrollment | govcio-vye-codereviewers
va-breadcrumbs | src/applications/virtual-agent | orchid

VaBreadcrumbs | src/applications/disability-benefits/2346 | va-cto-health-products
-- | -- | --
VaBreadcrumbs | src/applications/gi | govcio-vfep-codereviewers

## Tasks
- [x] Migrate remaining v1 breadcrumbs to v3
- [ ] Update any tests that need to be updated

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2658?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
- `va-breadcrumbs` has some mixed functionality that will need to be cleaned up and tested.
- `va-button` is a child component in `va-file-input`, `va-modal`, and `va-omb-info`

**Comment by Andrew565** [comment]
Will carry over due to not having enough third-party reviews yet.
