### ISSUE TITLE
Remove V1 Memorable Date from Component Library and Storybook

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2660]
## Description
On May 3 all V1 components will be fully retired except for va-table and va-file-input. To manage the significant amount of work to do this, we'll split the effort into several tickets. 

This ticket is for removing V1 Memorable Date from component library and storybook. 

## Tasks
- [ ] Remove the components listed above
- [ ] Remove their corresponding storybook entries

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2660?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
