### ISSUE TITLE
Migrate number input to v3 va-text-input

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2662]
## Description
We're removing all v1 component code at the end of July. To do so, we need to migrate all instances of v1 components to v3. This ticket is for updating all va-number-input components to v3 text input, since the text input now includes all va-number input functionality.

## Considerations
Remaining instances: 
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/15097156/a15413cf-3d12-4c27-951a-8ec04b6e2a8e)
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/15097156/e15cc83d-6df6-4b31-9eba-baf812cfbf89)

## Tasks
- [ ] Migrate va-number-input to va-text-input in vets-website
- [ ] Update any tests that need to be updated

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2662?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by harshil1793** [comment]
The PR was not reviewed by one team as they stated they want to discuss something with their team, which is the cause for the carryover.
