### ISSUE TITLE
Migrate v1 radio-option to v3 in vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2663]
## Description
We're removing v1 component code at the end of July. To do so, we need to migrate all remaining v1 instances to v3. This ticket is for migrating v1 va-radio-options to v3.  

## Considerations
Remaining Instances:

VaRadioOption | src/applications/disability-benefits | DBEX-TREX
-- | -- | --

va-radio-option | src/applications/disability-benefits | DBEX-TREX
-- | -- | --
va-radio-option | src/applications/vre | benefits-non-disability

## Tasks
- [ ] Migrate V1 va-radio-option to V3
- [ ] Update any tests that need to be updated

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2663?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
