### ISSUE TITLE
Migrate V1 Process List to V3 in vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2664]
## Description
We're removing v1 component code at the end of July. In order to do so, we need to migrate the remaining v1 process list components to v3. 

Remaining instances: 
va-process-list	src/applications/burial-poc-v6
va-process-list	src/applications/burials
va-process-list	src/applications/fry-dea
va-process-list	src/applications/lgy
va-process-list	src/applications/my-education-benefits
va-process-list	src/applications/travel-pay/containers

## Tasks
- [ ] Migrate v1 process list to v3
- [ ] update any tests that may break

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2664?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
