### ISSUE TITLE
Migrate v1 additional info to v3 in vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2665]
## Description
At the end of July all v1 component code will be removed from component library. To do this, the remaining instances of v1 additional info need to be migrated to v3.

Remaining instances: 
va-additional-info	src/applications/disability-benefits/686c-674
va-additional-info	src/applications/lgy

## Tasks
- [ ] Migrate v1 additional info to v3
- [ ] update any tests that may break

## Acceptance Criteria
- [ ] Above tasks have been completed
