### ISSUE TITLE
Move murals from Natalies Mural room to a VA Mural account

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2677]
## Description
Many of the research tasks that Natalie completed reside in her personal mural which limits visibility and controls access. We need to move all these boards from this Ad Hoc account to a VA account.

## Details

- [Natalies Mural Room Research](https://app.mural.co/t/adhoccorporateworkspace2583/r/1629742485730)
- [Confluence audit space](https://vfs.atlassian.net/wiki/spaces/DST/pages/2061336609/Audits)

## Tasks
- [ ] Request a mural account connected to your VA email
- [ ] Move the audits and research that is in Natalies Mural Room to a VA mural account
- [ ] Update the confluence doc to direct to the new location
- [ ] Update any tickets to the new location if the ticket has a mural audit referenced

## Acceptance Criteria
- [ ] All mural boards are moved to a VA account
- [ ] All the confluence docs are updated to the new location
