### ISSUE TITLE
Typography - Update Header and Footer `rem` values to `px`

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2730]
## Description

We would like to update the injected header and footer so that the styles will work for both `10px` and `16px` root font size. In order to do that, we would like to update any `rem` values to the `px` equivalent.

Here is an online calculator that will help determine the px value: https://nekocalc.com/px-to-rem-converter

This will probably require an update to Formation and possibly also vets-website.

### Testing the Injected header/footer locally (TeamSites)
- start vets-website with `yarn watch local-proxy-rewrite` (content-build might need to be running too)
- go to a TeamSite url like http://localhost:3001/?target=https://www.va.gov/health/

## Tasks
- [ ] Update any `rem` styles that the injected header and footer use to `px`. 
- [ ] Using Verdaccio, test VA.gov and TeamSites to make sure that the header does not look visually different after the change.
- [ ] Create a new release of Formation and update the [Formation Global Update pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/26606) with the new release version.
- [ ] Add screenshots of a tested TeamSite header and footer to the [Formation Global Update pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/26606)

## Acceptance Criteria
- [ ] The injected header and footer are displaying without any visual changes in both vets-website and TeamSite sites.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2730?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by it-harrison** [comment]
Formation [PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/1032) (merged) and [published](https://www.npmjs.com/package/@department-of-veterans-affairs/formation)
Vets-website [commit](https://github.com/department-of-veterans-affairs/vets-website/pull/26606/commits/2f63b6dc23847149ad20963fd9b6b2c2b9fe1d7b)
