### ISSUE TITLE
Add translation support to `va-button`

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2762]
## Description

We have received Spanish translations for "Continue" and "Back" strings which are used in `va-button` for `va-button-pair`. We should add `i18n` support to that component so that they can be translated with the following values:

**Spanish**

- continue = Continuar
- back" = Atrás

Slack convo for reference: https://dsva.slack.com/archives/C01DBGX4P45/p1713890235904039

## Details

The translation files are located here:

https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/core/src/i18n/translations

You can look at other components that have translation support already as a reference for how to add it to `va-button` too.

## Tasks
- [ ] Add `i18next` to `va-button`.
- [ ] Add the provided translations to the translation file(s)
- [ ] Add a `va-button-pair` Storybook story that demonstrations the translation support

## Acceptance Criteria
- [ ] va-button supports the provided translations
- [ ] Storybook has been updated to demonstrate

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2762?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by loripusey** [comment]
@jamigibbs Here are the Tagalog translations for "Continue" and "Back":
- "continue": "Magpatuloy",
- "back": "Bumalik",

**Comment by caw310** [comment]
@RyanMunsch Sorry just seeing this. We should add translation for loading as well.
