### ISSUE TITLE
Borderless table with sorting  - Accessibility review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2772]
## Issue Description
We need to conduct a full accessibility review of the Borderless table with sorting component. The component can be viewed in Storybook here: [insert Chromatic link here]

## Tasks
- [x] Full accessibility review of the component is completed
- [x] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [x] If necessary, discuss any accessibility issues found with the engineer who developed the component
- [ ] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [ ] Component has been reviewed for accessibility issues
- [ ] Any accessibility issues have been filed in a ticket

**Comment by rsmithadhoc** [comment]
@caw310 I created https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3455 for fixes.
