### ISSUE TITLE
Figma update: Add white link variation to va-link 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2776]
## Description
There's a request to allow <va-link> to be a white link instead of default blue [#2602](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2602). We need to add this to Figma

## Tasks
- [ ] Update va-link component with a white link instead of the default blue
- [ ] Get review from designer(s) 

## Acceptance Criteria
- [ ] va-link design has a variation with a white link

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2776?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
@LWWright7 Thanks for taking this on, Lucas! This is looking great. I think we should restructure a bit though, because "reverse" is more of a "variation" (or maybe a "theme") than a "state". In other words, for example, the link can be both "reverse" and have a "hover" state. Or it can be "reverse", "active", and "visited" at the same time.

So every combination that currently existed before, needs to be reverses. The end result essentially double the total number of combinations.

**Comment by LWWright7** [comment]
@danbrady Yep, totally. makes sense  One question though....for the variant, would it make sense to just create a boolean value for the reverse variations (ex: Reverse? T/F) or how do you think that should be handled?

**Comment by danbrady** [comment]
@LWWright7 How does the web component currently handle it? I don't think we would want that purple as it would be hard to see on dark backgrounds. (BTW, I think majority of the time dark backgrounds are either "primary dark" or "primary darker".) Maybe run the contrast reqs by Ryan to get an accessibility standpoint?

**Comment by LWWright7** [comment]
@danbrady That's why I ask...the web component doesn't even seem to have a "visited" state...the text stays the same color (white) and nothing changes.  It behaves that way in storybook and on va.gov live atm.  So I'm guessing that's the expected behavior....so no visited variation/state?

**Comment by danbrady** [comment]
Yeah, that seems like a potential error to me but maybe accessibility weighed in on that? It's probably better that we find out if that's acceptable or not.

**Comment by LWWright7** [comment]
@rsmithadhoc Would you happen to know the answer to this question? Is this behavior mentioned above normal and expected (that is, no visited state for link in reverse/dark mode?) or is there another color that would meet a11y as the normal state for visited doesn't seem that it would pass contrast testing?

**Comment by rsmithadhoc** [comment]
@LWWright7 

I think the issue here is it would have to pass WCAG AA on the lightest background that it would be used on. I think that might be the light blue used in the gradient on the hero section on va.gov, `--vads-color-primary: #005ea2;`.
<img width="333" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/9d737889-6813-453c-86fe-db04ef6dbf62">

To achieve that for normal-sized text with the purple, it would need to have a 4.5:1 contrast ratio. If we went with our visited link purple, it would need to be #DBD0E7. The action link had a white link before we updated this, it also doesn't have a visited state. I'm thinking that visited state may have been intentionally kept white for the action link, because the color would have to be pretty close to white anyway, so the contrast between active and visited links would be insufficient.
<img width="333" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/0d0e6493-c13b-4dad-b40b-e526baed45ea">


According to [WCAG 2.2](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color), setting a link's visited status is not a responsibility of the author. However, if we do, it has to meet contrast ratio requirements. I'm okay with omitting the visited state from this (keep it white), unless we have a suitable color that looks good.

**Comment by LWWright7** [comment]
@babsdenney & @danbrady This one is ready for another look!

**Comment by danbrady** [comment]
Thanks for tackling all those variations! We should remove "reverse" from the "state" property because we're using the "mode" property instead. Also, even though the visited reverse link is visually the same as default, I think we still need to create those variations. This way there is no confusion for a designer who's looking to set those specific properties in their local design file. If those properties are not there, they might think it's a DS error.

**Comment by LWWright7** [comment]
@danbrady ahh.....good call about that reverse state!  I neglected to clean that up after my first attempt at tackling this ticket.  Should be all cleaned up now. 

And good point about the visited variation.  I went ahead and added that too.  Oh, and also changed the background to the primary blue...since, as you said before, that's the color mostly used instead of black.

**Comment by danbrady** [comment]
It looks like the focus/active states are bigger than the other states. Can we make them all consistent sizes so the component doesn't shift around as a designer changes the properties?

**Comment by babsdenney** [comment]
@danbrady This is ready for [review](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199-1227)!

**Comment by danbrady** [comment]
Thanks for hopping on this so quick, @babsdenney! It's looking a lot better!

One minor thing is the Focus and Active states are slightly different sizes. The Active state has a 2px whitespace border between the element and the focus ring. Can we do that same thing to the Focus states too? (The Reverse/Active state needs this too, but the other Reverse states look good.)

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/3667f2b9-5ea5-4d15-bee1-8a871744689a)

**Comment by babsdenney** [comment]
@danbrady Good catch! I wasn't accounting for the border on the outside. I think I fixed this, if you want to give it another look. 👀  Thank you 🙏

**Comment by danbrady** [comment]
LGTM!
