### ISSUE TITLE
Bug - va-search-input suggestion box doesn't close

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2795]
## Description 
We recently [added a fix](https://github.com/department-of-veterans-affairs/component-library/pull/1122/files#diff-bb83edbd951e5962088a3a7171570a6e6a2c53b2ffd55e5654108b01da19b272) for va-search-input that resolved an issue sitewide was having, but inadvertently added a regression where the suggestion box stays open. 

This is likely because `isTouched` is never reset to `false`, and needs to be. Possibly in the [handleBlur](https://github.com/department-of-veterans-affairs/component-library/blob/52ba93cc10ae6a3077ba8e96506f405abe6e0a90/packages/web-components/src/components/va-search-input/va-search-input.tsx#L127) function.

<details><summary>Screen cap</summary>

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWF3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d370adca29c0b21f63441074456e78a14791841/Screen%20Recording%202024-05-02%20at%2010.26.16%20AM.mov)

</details>

## Considerations
- [ongoing slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1714663661141389?thread_ts=1714054912.852109&cid=C01DBGX4P45)
- @randimays [pull request with branch](https://github.com/department-of-veterans-affairs/vets-website/pull/28812)

## Tasks
- [x] Fix suggestion box
- [x] Test locally in vets-website

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2795?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
