### ISSUE TITLE
Remove code identified as for "GA4" from the component-library-analytics-setup.js file

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2827]
## Description

Based on feedback from the Analytics Team, we no longer need the custom "GA4" code in the [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js) file. See this [Slack thread for confirmation](https://dsva.slack.com/archives/CBU0KDSB1/p1715699214181899?thread_ts=1715630717.214569&cid=CBU0KDSB1) of that.

## Tasks
- [ ] Remove the `ga4: { ... }` details from each component in that file.
- [ ] Remove the condition block starting at line 805 `if (!environment.isProduction() && action?.ga4) { ... }`

## Acceptance Criteria
- [ ] the experimental ga4 code has been cleaned up from the component-library-analytics-setup.js file
