### ISSUE TITLE
Design: Add monospace font to Figma and Table component

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2847]
## Description

The USWDS table requires numerical data use a monospace font. We currently don't have a monospace font in the Design System and will need to do research to figure out how we want to add a monospace font to the DS.

[USWDS Table guidance ](https://designsystem.digital.gov/components/table/#guidance)

> Use a monospace font for numerical data. For even better readability of dense, numerical data, consider formatting numbers that convey amounts, such as percentages, currency, or tallies, in a [monospace](https://designsystem.digital.gov/design-tokens/typesetting/font-family) font. (There’s no need to apply monospace formatting or alignment to phone numbers, zip codes, dates, or other number content that can’t be totaled.)

## Details

[Slack thread for more context](https://dsva.slack.com/archives/G01BJ3ESXL4/p1715891286641149)
Connected

## Tasks
- [x] Research what monospace font to add to the DS
- [x] Add the monospace font to Figma to the appropriate pages like the typography page
- [x] Modify the table component to have numerical data use the monospace font
- [ ] Make a ticket for development so the font can be added to the repo

## Acceptance Criteria
- [ ] Review with Designers, PO, Accessibility, and Development

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2847?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by babsdenney** [comment]
This ticket is complete -
- [Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1721767299262339) - Discuss monospace font options
- [Table examples](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=1879-677)
- [Typography examples](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199-1182)



Two tickets were created to add the font to the DS and then a documentation ticket to update the typography pages in the DS site. 
- [Monospace font updates - Documentation #3103](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3103)
- [Add monospace font - Development #3104](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3104)

**Comment by caw310** [comment]
See #2925 for additional info if needed.

**Comment by babsdenney** [comment]
@danbrady @LWWright7 This is ready for review. 
- Add monospace text styles
- Added examples to the typography page
- Added an [example table with numerical data](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=1879-677) and right-aligned properties
  -   I didn't add a stacked table example, looking at examples on USWDS and it looks like any table with numerical data wasn't stacked and was made scrollable instead. I don't know if that is the route we should recommend.

**Comment by danbrady** [comment]
LGTM!

**Comment by LWWright7** [comment]
Good work Barb!  Let 'er rip!! 🚀
