### ISSUE TITLE
Military address pattern discrepancy between Figma library and design.va.gov guidance

### ISSUE THREAD

**Issue by Jenny-yw** [department-of-veterans-affairs/vets-design-system-documentation#2848]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Military mailing address on the design system guidance website  (https://design.va.gov/patterns/ask-users-for/addresses#mailing-address---military-base) is different from the military address details in the Figma VADS library (https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2987-36363). 
![Screenshot 2024-05-20 at 10 45 44 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/65574620/09c589fc-3a17-410d-ac02-0fec0557c288)
![Screenshot 2024-05-20 at 10 45 38 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/65574620/25f666bc-9453-4b92-844a-cbf048b1fbf8)

## To-do

- Determine which one is the accurate patter, then update both the Figma library or design system website to reflect one source of truth.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2848?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by humancompanion-usds** [comment]
This is a duplicate of https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2482 I will bring that one into the sprint instead.

**Comment by LWWright7** [comment]
@caw310 This can be closed....it's a duplicate of the ticket I'm working on now, as Matthew pointed out it looks like as well...not seeing his comment in the thread.
