### ISSUE TITLE
Formation deprecation - Typography Migration - bump paragraph base font from 16px to 16.96px

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2854]
## Description
With the recently completed work to get va.gov on a 16px root font size, we're ready to increment all paragraph typography to 16.96px. This work should take place after #2538. 

## Considerations
- css-library currently makes use of [uswds theme settings]
- Many of our components are already on 16.96px font sizing as they inherit directly from uswds. For example: [va-accordion](https://github.com/department-of-veterans-affairs/component-library/blob/d55ab7f40a7683fecf8784c9630d264539d45a7b/packages/web-components/src/components/va-accordion/va-accordion.scss#L3) does `@use usa-accordion/src/styles/usa-accordion` which imports [uswds accordion styles](https://github.com/uswds/uswds/blob/85d12c980e65094cb35ee99896b6904305c77c7d/packages/usa-accordion/src/styles/_usa-accordion.scss#L141) which includes [typeset settings](https://github.com/uswds/uswds/blob/7996dfbc243d20b55fb8a528ee90aa57d2452c99/packages/uswds-core/src/styles/mixins/typography/typeset.scss#L20) that specify font-family, font-size, and line-height.
- (https://designsystem.digital.gov/documentation/settings/#introducing-uswds-settings-2) our first pass should be to check if we can add the following rules to our [settings config](https://github.com/department-of-veterans-affairs/component-library/blob/55f806ae1c295b2f95aa3c5bcccfd471114b82ad/packages/css-library/src/stylesheets/_core.scss#L3-L7): 
```  
$theme-global-paragraph-styles: true,
$theme-global-link-styles: true,
$theme-root-font-size: 16px 
```
- We may be able to get away with just directly adding `$theme-global-content-styles: true`, but that includes style rules for headings, lists and tables as well, which may be too much. 
- If updating theme settings doesn't work, then our next step should be to attempt an import of [usa-paragraph-style](https://github.com/uswds/uswds/blob/b4a1b1c38350cad60bb000adcb05da58013ae757/packages/uswds-core/src/styles/mixins/typography/usa-content-styles.scss#L6-L10) and [usa-link-style](https://github.com/uswds/uswds/blob/b4a1b1c38350cad60bb000adcb05da58013ae757/packages/uswds-core/src/styles/mixins/typography/usa-content-styles.scss#L12-L16) directly into our own stylesheet, likely [elements.scss](https://github.com/department-of-veterans-affairs/component-library/blob/d55ab7f40a7683fecf8784c9630d264539d45a7b/packages/css-library/src/stylesheets/elements.scss#L3-L7)

## Tasks
- [x] Update css library typography settings to bump content from 16px to 16.96px
- [x] Test changes with verdaccio in vets-website to verify computed font-size is 16.96px

## Acceptance Criteria
- [ ] Above Tasks have been completed

**Comment by jamigibbs** [comment]
The value `16.96px` is coming from `1.06rem` x  `16px`  where 1.06 is the normalized value of Source Sans Pro and 16px is the base-font size.

`1.06 x 16 = 16.96`

More information on font normalization is here: https://designsystem.digital.gov/design-tokens/typesetting/overview/

**Comment by jamigibbs** [comment]
Adding some discovery notes:

The theme settings `$theme-global-paragraph-styles: true`, adds the following styles but only when the full USWDS source code is also loaded: `@forward "uswds";`


```css
p {
  line-height: 1.5;
  max-width: 68ex;
  margin-bottom: 0;
  margin-top: 0;
}
* + p {
  margin-top: 1em;
}
p + * {
  margin-top: 1em;
}
```
Because we're still transitioning off of Formation, we don't necessarily want to import the entire source code right now so in the PR linked above, we are importing those base `p` styles with more precision using`@include usa-paragraph-style;` and **not** setting the `$theme-global-paragraph-styles` variable in the theme settings.
