### ISSUE TITLE
Formation Deprecation - CSS Library Utility class rename

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2855]
## Description
In order to prevent disruption in the switch from Formation to css-library, we need to maintain the existing utility naming convention. This can be done at the same time as #2538, but won't really be testable until that ticket is finished.

## Considerations
- Current utility naming conventions include the prefix `vads-u-`, followed by the css property, and then suffixed with `--<unit-value` for example border top is `vads-u-border-top--1px`. 
- We currently rely on uswds theme settings to [generate utilities](https://github.com/department-of-veterans-affairs/component-library/blob/99ef26a80ab6180fe4f67a858b98dacb0b91c2f7/packages/css-library/src/utilities/border.scss#L6) for us. 
- We should be able to change our utility settings to get what we need. Taking borders as an example again, this is what we currently have in css library: 
```
$u-border-base: (
  border: (
    base: 'vads-border',
    modifiers: (
      noModifier: '',
      'top': '-top',
      'right': '-right',
      'bottom': '-bottom',
      'left': '-left',
    ),
    values: map-collect($tokens-border),
    settings: $border-settings,
    property: 'border',
    type: 'utility',
  ),
);
```
This currently outputs a list of classes that looks like this: `vads-border-top-1px`
- Updating the `base` property with `vads-u-border` should get us the prefix. 
- Updating the property names in [tokens/border.scss](https://github.com/department-of-veterans-affairs/component-library/blob/bfe41fa783cb75b5f3803f82e64b39c7be316dd5/packages/css-library/src/tokens/border.scss#L3) to include a `-` prefix _might_ get us what we need for our existing suffix convention. Experimentation may be required
- We'll have to check that all the utility classes generated from css library **cover existing use cases provided by formation**. For example if Formation gives us a `vads-u-border-top--2p5px` utility class, then the same should be generated in css library
- [Documentation on our current utility classes](https://design.va.gov/foundation/utilities/)

## Tasks
- [ ] update naming convention settings in all [css-library utility class](https://github.com/department-of-veterans-affairs/component-library/blob/8e80295be8a003232b1bae837f9e9fefb7f2ae31/packages/css-library/src/utilities/_index.scss#L1) functions. 
- [ ] Test updates with verdaccio in vets-website

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2855?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Here is the ESLint rule that was written to map the Formation utility names to the new utility names that might be helpful: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/issues/900
