### ISSUE TITLE
Add new icons to va-icon 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2872]
## Description
The following icons need to be added 
Fact Check - For submitted items
Acute - For In Progress
Local Shipping - For shipped items
Inbox - For messaging (mobile)
Refresh - Webview (mobile)

## Details
They have been added to FIgma. 
https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=293-6211&t=8JPlGPOhMpIrxRDf-1

## Tasks
- [ ] Add the 5 icons listed above to the sprite sheet
- [ ] Add the 5 icons listed above to the va-icon Storybook story
- [ ] Have a designer review 
- [ ] Make any necessary edits if needed

## Acceptance Criteria
- [ ] Icons above have been added to sprite sheet
- [ ] Storybook updated
- [ ] Component-library, vets-website, and content-build repos have latest sprite sheet

**Comment by danbrady** [comment]
These are icons:

<img width="234" alt="Screenshot 2024-06-05 at 3 35 48 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/b5b4840c-c4ce-40da-b04f-6a06771a1c65">

SVGs: [Archive.zip](https://github.com/user-attachments/files/15652973/Archive.zip)
