### ISSUE TITLE
Icons - Replace font awesome icon variables with va-icon

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2879]
## Description
vets-website contains a scss file called [iconography.scss](https://github.com/department-of-veterans-affairs/vets-website/blob/d281feef157ad8850e24156199d218398988d43a/src/platform/site-wide/sass/iconography.scss#L11) which creates a mixin that relies on font awesome icon variables. With our goal of moving off of font awesome, we need to replace these instances with inline va-icon instances instead. There are also some instances in the personalization directory that need to be updated. 

<img width="443" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af1441b4e1ef3b89420ae25bf0a8a4dfc2d42c26/image.png" alt="image.png" />

## Considerations
- It may be easier to create our own variable icons and use those as drop in replacements for all the `fa-var...` icons if it's determined that replacing them with `va-icon` proves too complex

## Tasks
- [ ] Determine if these icons are still being used, and if so replace them with instances of `va-icon` containing the corresponding icon
- [ ] Remove the associated styles since they'll no longer be used

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2879?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
