### ISSUE TITLE
va-link - add props for icon name and icon size

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2880]
## Description
va-link currently has several instances where va-icons are hard coded into it as conditionally rendered markup. Rather than be prescriptive in what we provide, we'll allow teams the flexibility of adding whatever link they want, at whatever size they want. Teams should rely on their own user research to determine whether or not they should be using icons with a link. 

## Tasks
- [ ] add props to va-link for icon name and icon size
- [ ] Update va-link render markup to reflect this change

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2880?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Cross referencing bug reported that is a duplicate but has info on this issue. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2890

**Comment by Andrew565** [comment]
Note that it was decided in the DST planning meeting that whoever works on this task will *add* the icon name and size props, but *will not remove* any of the existing variations (calendar, channel, etc) at this time.
