### ISSUE TITLE
Add prefix/suffix to va-text-input

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2882]
## Description
Add USWDS prefix/suffix to va-text-input. Adding support for currency is a pre-req to deprecating va-number-input. 

## Details
USWDS Input prefix or suffix: https://designsystem.digital.gov/components/input-prefix-suffix/

## Tasks
- [ ] Update va-text-input to allow for prefix and suffix 
- [ ] Review updated va-text-input with a designer 
- [ ] Make any changes as neeeded
- [ ] Update Storybook 

## Acceptance Criteria
- [ ] va-text-input allows for prefix and suffix

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2882?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
