### ISSUE TITLE
Move icon sprite sheet compiler to the component-library

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2883]
## Description
Right now the compiler that we use to create the sprite sheet for `va-icon` is in a separate repo:

- https://github.com/department-of-veterans-affairs/dst-uswds-compile

We'd like to move that into the [component-library repo](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages) as its own package for ease of use.

Some testing [mentioned in this Slack convo](https://dsva.slack.com/archives/G01BJ3ESXL4/p1716921064826459?thread_ts=1716918165.840109&cid=G01BJ3ESXL4) makes it seem like this is possible.

Additionally, we should update the package README to include the steps necessary to add the newly generated sprite sheet to the various places it's being used:

- vets-website
- content-build

## Tasks
- [ ] integrate the sprite sheet compiler into the component-library
- [ ] update the README file with complete steps for what to do with the sprite sheet after it's generated

## Acceptance Criteria
- [ ] the sprite sheet compiler from the dst-uswds-compile repo has been moved to the component-library packages
- [ ] instructions on how to handle the generated sprite sheet have been added
