### ISSUE TITLE
Update Experimental Design Process Guidance

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2896]
## Description
Update experimental design process guidance on design.va.gov

## Details
Allison's Mural board with the steps for reference. 
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715279885465/a8a7701ed5948be8cd98f972ee930a16b9e7444b?sender=u870c8d9c6b47768924793768 

## Tasks
- [ ] Update experimental design guidance for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] experimental design guidance  is published on design.va.gov

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2896?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7
