### ISSUE TITLE
Font Normalization - Update components that don't use uswds style modules

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2900]
## Description
Some of our web components do not use USWDS style modules, so they won't get the font normalization typography bump to 16.96px by default. These need to be manually updated.

## Considerations
- All components in storybook not appended with `USWDS` likely need to be updated manually to get the normalization font-size bump to 16.96px. 
- This should be done in the component stylesheet by importing our uswds-typography stylesheet: 
`@import "~@department-of-veterans-affairs/css-library/dist/uswds-typography";`
- List includes: back-to-top, banner, maintenance-banner, promo-banner, crisis-line-modal, va-date, va-link, va-loading-indicator, va-need-help, va-omb-info, va-on-this-page, va-telephone
- if a component is explicitly setting font-size to 16px, it will need to be replaced with 16.96px. 

## Tasks
- [ ] import the `uswds-typography` style sheet into all components listed above

## Acceptance Criteria
- [ ] imports have been added
- [ ] components have been tested to verify computed font-size is 16.96px
