### ISSUE TITLE
Forms templates clean up - Figma 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2907]
## Description
The forms templates alignment is a bit off and requires clean up. 

## Tasks
- [ ] Add layout grid to all templates for all devices, 
- [ ] Remove duplicate templates, 
- [ ] Align elements to layout grid, 
- [ ] Validate no property errors, 
- [ ] Clean up layer names, 
- [ ] Validate links to/from doc site
- [ ] Get review and sign off from another DST designer

## Acceptance Criteria
- [ ] All of the above tasks have been completed so that forms templates alignment is correct

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2907?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady & @babsdenney  [This one](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-66785&t=JgoJY2lhl9f5r6wP-1) is ready for review!!! Thanks

**Comment by caw310** [comment]
Will carry over as there are fixes that came up after designer was on PTO.

**Comment by caw310** [comment]
This will not carry over into sprint 5 as there is other higher priority design work. Will pick up this work in a future sprint.

**Comment by caw310** [comment]
Closing for now
