### ISSUE TITLE
USWDS Typography: QA for Source Sans Pro normalization

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2909]
## Description

QA will need to be completed for the USWDS typography vets-website import that is applying font normlization to Source Sans Pro content. This import will increase the calculated font-size for content elements from 16px to 16.96px (1.06 x 16 = 16.96px).

**Vets Website PR for review**

- https://github.com/department-of-veterans-affairs/vets-website/pull/30089

original issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2854

## Tasks
- [ ] have teams conduct QA on their apps and provide feedback if there's a questionable change visually with the content
- [ ] make updates to the [uswds-typography](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/uswds-typography.scss) CSS Library stylesheet if needed
- [ ] make updates to Formation if needed

## Acceptance Criteria
- [ ] the vets-website PR has been approved and merged

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2909?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Giving this a 5 point estimate as it will take time to follow up with various teams.
