### ISSUE TITLE
Formation Deprecation - Swap vets-website imports - Merge vets-website PR

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/vets-design-system-documentation#2911]
## Description
This ticket is to finalize the vets-website PR which updates imports from formation to css-library. 

component-library PR: https://github.com/department-of-veterans-affairs/component-library/pull/1167
vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/30031

## Details
- Once the component-library PR is merged and css-library is published we need to update the css-library dependency in the vets-website PR with the new version number and mark the PR as ready for review.
- There are a lot of code-owners for this PR, not all of them need to review it, but there should be enough reviews that we are confident that there are no visual regressions.

## Tasks
- [ ] Update css-library version in vets-website
- [ ] Work to get CI passing
- [ ] Get PR reviews
- [ ] Merge the PR

**Comment by caw310** [comment]
This will carry over as there are some issues that still need to be resolved.
