### ISSUE TITLE
VA Label - Design

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2924]
## Description
Create design for VA-label and update Figma artifacts for [VA Label](https://design.va.gov/components/form/label).

We currently have each of the labels as a single component on the form elements page. We should create a Label component to align with the documentation. This new component could be used within the VA form elements to provide alignment with code and also make it easier to make changes to spacing within the form inputs. 

We recently got [a question in the #design Slack channel](https://dsva.slack.com/archives/C0NGDDXME/p1717782668536509) that showed some of the spacing between form elements in Figma are not aligned. Having the label as a single component would help with solving this issue.

## Details

- Ticket in backlog related to VA-Label Dcoumentation - [[Label] - Documentation update: Make Components > Forms > Label a full-fledged component #855](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/855)
- [Form elements in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=205-1261)

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Replace labels in all relevant form elements for VADS components in Figma
- [ ] Review designs with PO and DST designers 
- [ ] Review designs with developers and accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility and development considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack
