### ISSUE TITLE
Copy of Design: Add monospace font to Figma and Table component

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2926]
## Description

The USWDS table requires numerical data use a monospace font. We currently don't have a monospace font in the Design System and will need to do research to figure out how we want to add a monospace font to the DS.

[USWDS Table guidance ](https://designsystem.digital.gov/components/table/#guidance)

> Use a monospace font for numerical data. For even better readability of dense, numerical data, consider formatting numbers that convey amounts, such as percentages, currency, or tallies, in a [monospace](https://designsystem.digital.gov/design-tokens/typesetting/font-family) font. (There’s no need to apply monospace formatting or alignment to phone numbers, zip codes, dates, or other number content that can’t be totaled.)

## Details

[Slack thread for more context](https://dsva.slack.com/archives/G01BJ3ESXL4/p1715891286641149)

## Tasks
- [ ] Research what monospace font to add to the DS
- [ ] Add the monospace font to Figma to the appropriate pages like the typography page
- [ ] Modify the table component to have numerical data use the monospace font
- [ ] Make a ticket for development so the font can be added to the repo

## Acceptance Criteria
- [ ] Review with Designers, PO, Accessibility, and Development
