### ISSUE TITLE
va-icon: Add eslint error rule back to vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2931]
## Description
On June 20th, we'll be re-introducing the [eslint icon error rule](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/lib/rules/prefer-icon-component.js) back into vets-website to enforce icon migration. 

## Considerations
- Rule already exists [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/lib/rules/prefer-icon-component.js) but needs to be re-added to [this index file](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/index.js). 

## Tasks
- [ ] add above linked rule to above linked index file
- [ ] bump the version number for the eslint rule in [this package.json file](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/package.json#L3)
- [ ] submit and merge a PR for the above things
- [ ] update the eslint-plugin in vets-website [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/package.json#L129)
- [ ] Replace the prefer-icon-component-message rule with `prefer-icon-component` in the vets-website [eslintrc.changed.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.eslintrc.changed.js#L11) file
- [ ] verify the above change works by opening up a file that uses font-awesome and checking that the error + quickfix option function as expected

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2931?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
