### ISSUE TITLE
USWDS Typography: Merge Source Sans Pro normalization PR

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2943]
## Description
After QA has been completed, the Source Sans Pro normalization PR will need to be merged based on the remaining [announcement dates](https://dsva.slack.com/archives/C03R5SBELQM/p1717618603508049):

- June 18th - 25th: Final review window
- June 26th: [PR to be merged](https://github.com/department-of-veterans-affairs/vets-website/pull/30089).

Other related issues:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2854
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2909

## Tasks
- [ ] address any additional feedback between June 18th - 25th
- [ ] merge the normalization PR on June 26th

## Acceptance Criteria
- [ ] the typography PR has been merged
