### ISSUE TITLE
Breadcrumbs - Update breadcrumbs.html liquid partial to use va-breadcrumbs

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2945]
## Description
Applications on va.gov that rely on the `page-react.html` template have an inherent dependency on the [breadcrumbs.html](https://github.com/department-of-veterans-affairs/content-build/blob/0487c9e913ca56e0623f18400a4a95c9bb2eb3c9/src/site/includes/breadcrumbs.html#L11) liquid partial. This partial relies on an unordered list to render breadcrumbs, and it needs to be updated to use va-breadcrumbs. 

Initially, this ticket should be treated as a discovery ticket to determine whether or not v3 breadcrumbs can directly replace the existing logic. The concern here is that v3 breadcrumbs uses an array of objects to render individual crumbs, but the current implementation directly renders anchor tags itself. 

## Considerations
- current logic in [breadcrumbs.html](https://github.com/department-of-veterans-affairs/content-build/blob/0487c9e913ca56e0623f18400a4a95c9bb2eb3c9/src/site/includes/breadcrumbs.html#L11) keeps track of current page and renders markup that includes an `aria-current` attribute. 
- V3 breadcrumbs uses an array of objects to render individual breadcrumbs, it may need to be modified for use in `breadcrumbs.html`, though this will need to be verified during work on this ticket. 

## Tasks
- [x] Discovery: determine if v3 breadcrumbs can be used as-is in [breadcrumbs.html](https://github.com/department-of-veterans-affairs/content-build/blob/0487c9e913ca56e0623f18400a4a95c9bb2eb3c9/src/site/includes/breadcrumbs.html#L11) to render crumbs
- [ ] **If v3 breadcrumbs cannot be used:** create a follow up ticket to extend v3 breadcrumbs so it can be used, create another follow up ticket to migrate breadcrumbs.html once v3 breadcrumbs has been extended
- [x] **If v3 breadcrumbs can be used**: Complete the migration work in this ticket

## Acceptance Criteria
- [ ] Above tasks have been completed as needed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2945?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by DLarson-Oddball** [comment]
Hey team, is the `wrapping` attribute is being considered as part of this work?

My understanding is once this is released, teams will be able to configure breadcrumbs in content-build and they will be rendered with <va-breadcrumbs />. We have been updating the breadcrumbs on burials, and have to use some fairly long text, so the `wrapping` attribute is required to make content accessible. 

We are currently working to understand if this will solve our desire to use va-breadcrumbs on burials, and still allow us to define the values in content-build (with the `wrapping` attribute enabled). Thanks!

**Comment by Andrew565** [comment]
@DLarson-Oddball I'll make sure `wrapping` is enabled by default.

**Comment by Andrew565** [comment]
Progress delayed and/or stalled due to lack of SOCKS access for myself. Working to resolve this currently, but the contact person I need to interface with at the VA is on military leave until the 16th.

**Comment by Andrew565** [comment]
Will carry over due to aforementioned lack of SOCKS access.

**Comment by Andrew565** [comment]
Will carry over again due to aforementioned lack of SOCKS access.
