### ISSUE TITLE
content-build style inheritance discovery

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2953]
## Description
We recently completed work to deprecate some old hub icons that relied on font-awesome. A portion of this work removed a stylesheet that content-build relied on for sizing some hub page icons that were actually still in use. This was hard to determine at the time because of the messy coupling between vets-website and content-build. 

In an effort to avoid this in the future as we continue to work on css-library and the removal of Formation, we should do some discovery work to figure out what other css classes content-build relies on that live in vets-website. 

## Considerations
- [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1718906568437409) containing the original regression. Contains information about the class that was removed and how it impacted things in content-build

## Tasks
- [x] Go through content-build markup to check what gets inherited from vets-website
- [x] Determine whether or not there is content from Drupal that also contains class names inherited from formation or vets-website
- [x] Compile a list of class names that have a dependency on vets-website in google sheets

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2953?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
List of names [here](https://docs.google.com/spreadsheets/d/1bkdjXasWkgSHCeTPMpUyex7FunUKjDDr1Uj3FIr_M6w/edit?gid=0#gid=0)
