### ISSUE TITLE
Create new GitHub templates for Designer issues

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2959]
## Description
We are updating our ticket creation process for Designers on the DST. We currently have 2 GitHub templates that are used for Design work and we believe that these generalized templates could have more specificity for the different task that Designers do. Some ticket templates could be:

- [ ] Discovery/Research
- [ ] Doc site updates/Documentation
- [ ] New component/Updating a component
- [ ] Pt.2 of new components or updates (ex. publishing changes/examples)
- [ ] Adding a tokens or icons

Note: One thing to make sure we emphasize in the new tickets is making the Designer to Engineer process more formal to make sure that handoff is happening for each design ticket. 
 

## Details

- You can see the c[omponent design process map](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712767191559/62f5e4ccb617c862cd7379cbfea66522c1ea00f2?wid=0-1718998935427) here
- A d[ocument to compare the two current design templates on Github](https://docs.google.com/document/d/1OigOy4lFbiJGwxJ7Y28CPslI0ESHIiinyvn73MhGZn0/edit?usp=sharing)
- [View all DST github templates](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new/choose)
- [Instructions on how to edit or create a GitHub template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

## Tasks
- [ ] Figure out how we want to rework the github ticket templates.
- [ ] Think about if there are any other ways to make the ticketing process easier for Designers (Reach out to the other DST designers for advice or ideas)
- [ ] Update the current templates and merge the current templates into one template (Do we need to look at Engineering tickets as well to bridge the design/engineering handoffs?)
- [ ] Create the new templates

## Acceptance Criteria
- [ ] Review with DST Designers
- [ ] Review with DST PO/PM's
- [ ] The current issue template for Designers is updated and any new issue template have been created
- [ ] Any other updates to the GitHub process have been created or ticketed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2959?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7
