### ISSUE TITLE
[File input] Read only variation - Development

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2960]
## Description
We discovered a new use case for the file input. There is a team that is requesting a read only version of the file input that has all buttons and options removed. 

## Details
- Original Design ticket - [[File Input] - Design: Read only version of File Input#2877](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2877)
- Design documents: [Ready only file input in Figma](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=1360-85508&t=eGlujMSaiFyxKNdA-1)
- Review accessibility considerations added to component design ticket (if any)- 
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [x] Review DST backlog for outstanding issues with this component, if necessary
- [x] Create web component and add to Storybook
- [x] Write any necessary tests
- [x] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [x] Contact designer for design review
- [x] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [x] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [x] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [x] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2960?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Looks like there is a [PR ](https://github.com/department-of-veterans-affairs/component-library/pull/1300) for this.

**Comment by Andrew565** [comment]
Resumed work on this today, implemented design changes. Next will be porting the readonly changes over to the va-file-input-multiple component.

**Comment by Andrew565** [comment]
Will carry over due to needing to add E2E (Cypress) tests and will need time to review once those tests have been added.
