### ISSUE TITLE
Move v3 File input design variations in Figma

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2961]
## Description
Move the v3 File Input variations from explorations to the components section in Figma.
Rename the variations to Additional form inputs

## Tasks
- [ ] move the v3 file input variations from explorations to components in Figma
- [ ] Rename the variations to Additional form inputs

## Acceptance Criteria
- [ ] v3 file input variations are showing in components in Figma
- [ ] Variations are named Additional form inputs

**Comment by babsdenney** [comment]
This is complete. @danbrady @LWWright7 

[File Input Example library](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=1360-85508)
