### ISSUE TITLE
Padding specifications for breadcrumb component - Design 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2969]
## Description
Establish sitewide padding specifications for breadcrumb component on Desktop and mobile per this experimental design request. 
[Experimental Design: Establish padding for breadcrumb component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2808#top) 

## Details
_optional, delete section if not needed_

## Tasks
- [x] Review experimental design request and comments to establish padding specifications for breadcrumb 
- [ ] Update breadcrumb component in Figma 
- [x] Review with PO and DST designers 
- [x] Make any necessary updates

## Acceptance Criteria
- [ ] Breadcrumb component has padding specifications in Figma
- [ ] Add link to Figma in the development ticket

**Comment by babsdenney** [comment]
This is almost complete but I got behind on getting the approvals completed to finalize the padding.

**Comment by babsdenney** [comment]
See [Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1721245934030259) for more context. The final breadcrumb spacing will be -

**Desktop** - 20px on top (no change) and 48px on bottom
**Mobile** - 20px on top and 32px bottom
