### ISSUE TITLE
Update padding of breadcrumb component - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2970]
## Description
Update the breadcrumb component padding. 
For reference, this is the experimental design request this work stems from:
[Padding specifications for breadcrumb component - Design](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2969#top)

## Details
The final breadcrumb spacing will be -
Desktop - 20px on top (no change) and 48px on bottom
Mobile - 20px on top and 32px bottom 

[Slack thread for more details](https://dsva.slack.com/archives/G01BJ3ESXL4/p1721245934030259)
See screenshots below

## Tasks
- [ ] Review new padding specifications
- [ ] If needed, sync with DST designer 
- [ ] Update breadcrumb component with new padding 

## Acceptance Criteria
- [ ] Breadcrumb padding is updated and viewable in Storybook

<img width="484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzcxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1525b19b1bf6043a8b4d834e209880bc276f036/Screenshot%202024-07-18%20at%203.26.06%E2%80%AFPM%20%281%29.png" alt="Screenshot 2024-07-18 at 3.26.06 PM (1).png" />

<img width="1660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3IxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--111e0f3f6009c5081e3e41038a35b2304c44fca8/Screenshot%202024-07-18%20at%203.24.19%E2%80%AFPM%20%281%29.png" alt="Screenshot 2024-07-18 at 3.24.19 PM (1).png" />

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2970?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by babsdenney** [comment]
See [Slack thread ](https://dsva.slack.com/archives/G01BJ3ESXL4/p1721245934030259)for more context. The final breadcrumb spacing will be -

Desktop - 20px on top (no change) and 48px on bottom
Mobile - 20px on top and 32px bottom
