### ISSUE TITLE
Bug - Header width doesn't scale with large font browser settings

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2987]
## Description
In doing recent font normalization work, we recently discovered the header for VA.gov doesn't scale properly when browser font settings are set to large or extra large. To fix this, the width values for the header menus need to be in relative units instead of pixels. 

## Considerations
- [slack thread](https://dsva.slack.com/archives/C06V7AAFVH7/p1719243755794759) with more context and proposed fix
- Per [Laura Flannery's comments](https://dsva.slack.com/archives/C06V7AAFVH7/p1719249827949959?thread_ts=1719243755.794759&cid=C06V7AAFVH7), there are 2 issues at play that need to be addressed:
  1. The first dropdown has a set width of 250px so at the larger font sizes, when the arrows end up further right, the white background cannot expand. But if this were to change to a relative width (I used 15.5rem because that aligns with the individual buttons sizes but then gives a little bit of additional padding) that should allow for the correct resizing at various font sizes - I looked at Medium, Large and Very Large
  2. For the "View all in {hub}" hub links, this is again positioned using pixel sizes but if we change this to the same rem value that the white section is using as well as the padding the gray section is using, this should respond and flex appropriately when the text grows

## Tasks
- [ ] For point 1 above: update the value for [proxy-rewrite](https://github.com/department-of-veterans-affairs/vets-website/blob/80ad96a1eb55611f59aa9f0e87b0600b661c1d40/src/applications/proxy-rewrite/sass/consolidated-patches.scss#L210) and [everywhere else](https://github.com/department-of-veterans-affairs/vets-website/blob/80ad96a1eb55611f59aa9f0e87b0600b661c1d40/src/platform/site-wide/sass/modules/_m-vet-nav.scss#L348) to 15.5 rem
- [ ] For point 2 above: Update formation [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/77a98348dfd84e558f1700ba941b4b07ee4c164d/packages/formation/sass/modules/_m-megamenu.scss#L313) and [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/77a98348dfd84e558f1700ba941b4b07ee4c164d/packages/formation/sass/modules/_m-megamenu.scss#L343) to 15.5rem. In css-library update the value [here](https://github.com/department-of-veterans-affairs/component-library/blob/ff8d9cfaa01e5c01ed85dbb4e2d053830f4932e9/packages/css-library/src/stylesheets/modules/m-megamenu.scss#L320) and [here](https://github.com/department-of-veterans-affairs/component-library/blob/ff8d9cfaa01e5c01ed85dbb4e2d053830f4932e9/packages/css-library/src/stylesheets/modules/m-megamenu.scss#L350) to 15.5rem
- [ ] Test with verdaccio that container scaling has been resolved using verdaccio

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2987?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
Since this ticket was written, the proxy-rewrite injected header has been split from the rest of vets-website, so it's possible work there is no longer needed.
