### ISSUE TITLE
Update va-text-input component - Figma

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2995]
## Description
Update design in Figma for Text Input to include guidance for prefix and suffix.

## Tasks
- [ ] Update text-input design to include prefix and suffix 
- [ ] Get another DST designer to review 
- [ ] Publish update in Figma

## Acceptance Criteria
- [ ] Text-input component design has prefix and suffix

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2995?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
@babsdenney @LWWright7 [This is ready for review](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199-1223&t=TvL1z9QuTR0pXG2K-1). Thanks!
