### ISSUE TITLE
Fix CSS source maps

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2998]
## Description
CSS source maps are currently broken in staging and production such that when inspecting an element, the stylesheet referenced is not accurate. This contributes to an increased time in debugging and needs to be fixed. This is in contrast with local development, where sourcemaps for CSS work as expected. 

For example: the `Get Benefits` button is a `usa-accordion-button`. In staging it points to an incorrect css source, `va-pagination.css`: 
<details><summary>Staging Get Benefits Button</summary>
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cc948bc952aa8de719544cb3c0ba76ee71df46a/image.png" alt="image.png" />

</details>
<br>
Compared to local development, where the same element is mapped to the correct css source, `m-nav-sidebar.css`: 

<details><summary>Local Get Benefits Button</summary>

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0hIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e1031f2c483228ef3694094b448f02959e0b79c/image.png" alt="image.png" />

</details>

## Tasks
- [ ] Determine why sourcemaps work locally but not in staging and production
- [ ] Fix whatever configuration needs to be fixed so sourcemaps are accurate

## Acceptance Criteria
- [ ] Above tasks have been completed
