### ISSUE TITLE
Automatically publish Component Library release notes to Slack

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2999]
## Description
Notifying teams that a new component library release has been published is a manual process that requires a member of DST to send a message in slack which includes a link to the latest release notes. There's already precedent for automated slack notifications which we see with the vets-website and content-build daily deploys. We should automate the publishing of  component library release notes to communicate with teams more effectively when changes roll out. 

## Considerations
- [The github action](https://github.com/department-of-veterans-affairs/vets-website/blob/6a1fa8f95462ef0788a24dc15abe245c81677b42/.github/workflows/slack-notify/action.yml#L0-L1) that vets-website uses in the daily deploy workflow
- [The vets-website daily deploy workflow step](https://github.com/department-of-veterans-affairs/vets-website/blob/b2a36929f183f3b38a1a6424f4c7bc9441dfa313/.github/workflows/daily-deploy-production.yml#L76) responsible for pushing a message to slack when deploy starts.
- [The vets-website daily deploy workflow steps](https://github.com/department-of-veterans-affairs/vets-website/blob/b2a36929f183f3b38a1a6424f4c7bc9441dfa313/.github/workflows/daily-deploy-production.yml#L196-L232) for notifying success or failure
- We should be able to reuse much of the above github action code
- `channel_id` is set as an environment variable, so we'll need to figure out which channel we want to push to and possibly get permission to do so. Then, we'll need to store this as an [environment variable](https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow).
- The vets-website daily deploy workflow sets the environment variables for channel ID [directly in the workflow file](https://github.com/department-of-veterans-affairs/vets-website/blob/b2a36929f183f3b38a1a6424f4c7bc9441dfa313/.github/workflows/daily-deploy-production.yml#L17-L18), so we're probably safe to do the same. 

## Tasks
- [ ] Come up with messaging that will get pushed to slack each time a new release is published. This should include a link to the release notes
- [ ] Create a notify slack workflow similar to the one mentioned above, and add it as a step to the component library [publish workflow](https://github.com/department-of-veterans-affairs/component-library/blob/99846cf2cc594cb5375d1d99e2abe0bf2a57fc56/.github/workflows/publish.yml#L10) after the publish step has successfully completed

## Acceptance Criteria
- [ ] Above tasks have been completed
