### ISSUE TITLE
Fix the Select component default text 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3000]
## Description
In this [Slack conversation](https://dsva.slack.com/archives/C01DBGX4P45/p1720537587563149), Skyler pointed out that the Select component, the color for the "Required" text looks like it's vads-color-error by default, and to my eye it looks like it should be vads-color-error-dark based on the Storybook component.

## Tasks
- [ ] Check if the Select component required text is the correct color 
- [ ] If it is not, then change it to the correct base color
- [ ] Have a DST designer confirm color is correct
- [ ] Update Storybook 

## Acceptance Criteria
- [ ] Select component required text color is correct

**Comment by powellkerry** [comment]
It looks like the (*Required) text is styled using the `usa-label--required` class from uswds which sets the color to error-dark/#b50909. Figma has the color as vads-color-error/#d54309

This inconsistency needs to be fixed, the question is where should it be fixed. If the color is fixed in the component it would mean that we are deviating from uswds and would need to write code to overwrite the color for all components with the required text.

error-dark/#b50909 is also used on the error text and error states of form components, if the decision is to overwrite we probably should have a discussion on whether to overwrite those styles as well.

@danbrady @micahchiang

**Comment by danbrady** [comment]
Good catch, @powellkerry. Our Figma components need to be updated. They also have inconsistent left padding in different components. I made #3338 to capture that work. 

If the color of the "required" and error states in the web components are the same as USWDS then there is no engineering work needed. Thanks!

**Comment by powellkerry** [comment]
Closing this as the work to update figma is captured in 3338
