### ISSUE TITLE
Design needed for va-pagination on mobile 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3003]
## Description
There is a dev ticket [va-pagination: Can't navigate to next and prev page on mobile](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2597#top)  that needs design guidance for pagination on mobile. 

## Details
[Pagination doesn't fit on the 320px screen size in Storybook](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2199) is also related. 

## Tasks
- [ ] Define spacing and design for pagination component on mobile 
- [ ] Update pagination component design in FIgma 
- [ ] Get review from a DST designer and VADS PO
- [ ] Update Figma 
- [ ] Add link to Figma file in the developent tickets

## Acceptance Criteria
- [ ] Pagination component has design spacing for mobile in Figma 
- [ ] Development tickets are updated with link to Figma

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3003?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
Submitted issue to [USWDS](https://github.com/uswds/uswds/issues/5981) to see if they will fix the issue.  
Since it may take them a long time to do it, should we just do our solution and submit to USWDS??

@caw310 @humancompanion-usds

**Comment by humancompanion-usds** [comment]
Yes we should make our updates to solve this problem and then update the issue with USWDS detailing what we did.

**Comment by humancompanion-usds** [comment]
The dev issue that spawned this has been closed thus this can close as well. According to the team, this issue has been resolved.
