### ISSUE TITLE
Update Files pattern - Documentation

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3009]
## Description
Update documentation and guidance for [File pattern](https://design.va.gov/patterns/ask-users-for/files) on design.va.gov to include guidance for uploading multiple files. 

Review the [content considerations](https://design.va.gov/components/form/file-input#content-considerations) and [accessibility](https://design.va.gov/components/form/file-input#accessibility-considerations) and compare those sections to the file input component documentation to make sure they align. 

## Details
[Update File Input - Documentation#2655](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2655)

[File input component in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199-1212)

## Tasks
- [ ] Write or update component documentation for [Files pattern on design.va.gov](https://design.va.gov/patterns/ask-users-for/files)
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
We can't really work on this until a team ships it. The Forms team has this in the Upload PDF functionality they are building. But that just finished testing and won't ship until later this month. Moving this to a later sprint.

**Comment by humancompanion-usds** [comment]
This functionality has shipped! Form Upload is in production. We can play around with it in staging here:
https://staging.va.gov/find-forms/upload/21-0779/introduction
