### ISSUE TITLE
V1 Component Code Removal - va-alert, va-banner

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3012]
## Description
With migration to v3 complete there are no v1 component instances left in vets-website or content-build. We should remove v1 component code from the component library repo to prevent teams from inadvertently using them. This ticket is for the removal of v1 va-alert

## Considerations
- `va-banner` currently just renders a `va-alert`, but it has uswds explicitly set to false. Will need to update this and verify va-banner continues to work as expected.
- V3 component code is currently housed in an `if` statement. That code needs to become the default component code, and everything else needs to be removed. 
- Some components rely on css selectors that target the `uswds` property on the host, such as `:host([uswds='false'])` These should also be removed
- Some e2e test specs for components still rely on the uswds prop. These should be cleaned up and removed if necessary. 

## Tasks
- [x] Remove v1 component code for va-alert
- [x] Update css and test files where v1 is no longer needed
- [x] Update va-banner to remove `uswds={false}` and any associated v1 code

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3012?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
