### ISSUE TITLE
Add VA.gov logos to VADS - Documentation

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3033]
## Description
Add VA.gov logo to design.va.gov. This ticket has a bit of discovery to make sure we are implementing this the most efficient way. 

## Details
We have a [request for Figma access so that a team can download the official VA.gov logo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88317). To make it easier for teams that are not using Figma to access to the VA.gov logo we should add a option to access the VA.gov logo through VADS without requiring Figma. There might be a few different ways you could implement this.

Some options to consider -
- A logo component
- A link to the source file
- Tokens

Discuss best solutions to share the logo with the DST. 

- [VADS Logo guidelines](https://design.va.gov/foundation/logos)
- [VA.gov logo in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=894-4586)

## Tasks
- [ ] Discuss with the team possible solutions for making the VA.gov logo easier to share and use on VFS
- [ ] Once a solution is determined, decide steps to implement solution
- [ ] Update [Logo documentation](https://design.va.gov/foundation/logos) for design.va.gov
- [ ] Update Figma Example library to include a logos page
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Approval from DST designers, engineers, PO, and PM
- [ ] Component documentation is published on design.va.gov
- [ ] Component examples are published on the Figma Example Library

**Comment by babsdenney** [comment]
Duplicate ticket #3101.  Closing this ticket.
