### ISSUE TITLE
Add grid for the Tablet and Mobile templates in Figma

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3034]
## Description
Add layout grid for the Tablet and Mobile templates in Figma. Currently there is only desktop 

## Details
Grid in Figma
https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2607-29262&t=3j17oazf90lv2J94-1 

## Tasks
- [ ] Update mobile template to include a 1-column layout grid and standardized page gutter size
- [ ] Update tablet to include a 6-column layout grid
- [ ] Column gutters should match to what is possible today with the DS
- [ ] Get review from DST Designer or PO 
- [ ] Make any necessary updates 
- [ ] Publish Figma updates

## Acceptance Criteria
- [ ] Tablet and Mobile templates can toggle on/off appropriate layout grid
- [ ] Grid should be consistent upon resizing template frames
- [ ] Components should "snap" to grid columns upon placement

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3034?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady & @babsdenney - this one is ready for [review](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2607-30164&t=bi0OCe3FlTKzWb89-1)!
