### ISSUE TITLE
Update documentation for ARIA label on telephone numbers

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#3040]
## Description

Update the guidance on the [design system documentation for the telephone number label](https://design.va.gov/content-style-guide/dates-and-numbers#links-and-aria-labels) based on the changes and new guidance outlined in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2884

## Tasks
- [ ] Update guidance on the site to remove the notes about ARIA labels for telephone.
- [ ] Get it reviewed by CAIA, they maintain the Content sections.

## Acceptance Criteria
- [ ] Design system documentation has been updated to remove the telephone label notes.

**Comment by megzehn** [comment]
Hi @rsmithadhoc! Could you confirm whether or not we want to keep the a href tags that we currently have on phone numbers?

For example, if we have this coding:

`<a href="tel:2021231234" aria-label="2 0 2. 1 2 3. 1 2 3 4."> 202-123-1234 </a> (<a href="tel:711" aria-label="TTY. 7 1 1.">TTY: 711</a>)`

under the new guidance, should it be this?

`<a href="tel:2021231234"> 202-123-1234 </a> (<a href="tel:711">TTY: 711</a>)`

We're starting to roll out this guidance in production on our Drupal pages. There are many places where we've added aria labels to phone numbers, so I want to make sure we're making the right changes. 

CC @RLHecht @saratorres2 @laurwill

**Comment by megzehn** [comment]
Update: @artsymartha68 confirmed we're keeping the `<a href>` tags on phone numbers and TTY: 711. We're just removing the `<aria-label>`

**Comment by artsymartha68** [comment]
Correct, @megzehn , thanks for verifying!
