### ISSUE TITLE
CSS Library - Utilities - Update rem values for spacing.json and fonts.json

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3044]
## Description
Formation margin and padding utilities use a `$spacers` map that hard codes an 8px base. This is also used to provide a `$units` map that converts the 8px base values into rem. This is a challenge because it's predicated on the idea of a 10px root font size. VA.gov now uses 16px as its root font-size. To keep consistent pixel values, rem values in css-library's [spacing.json](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/tokens/spacing.json) and [fonts.json](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/tokens/fonts.json#L19-L25) files need to be updated using the coefficient we used in our `scale-rem` function, 0.625. 

## Considerations
- [confluence doc](https://vfs.atlassian.net/wiki/spaces/DST/pages/3305504860/Plan+-+Formation+to+CSS+Library+Utilities+Swap#Considerations) with a couple more thoughts on the coversion

## Tasks
- [ ] Update rem values in [spacing.json](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/tokens/spacing.json) and [fonts.json](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/tokens/fonts.json#L19-L25) files using the coefficient we used in our `scale-rem` function, 0.625.
- [ ] regenerate the `dist/utilities.css` 

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3044?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
