### ISSUE TITLE
CSS Library - Utilities - add medium-screen to utilities.css output

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3045]
## Description
vets-website has a `medium-screen` breakpoint with a value of 768px which is used extensively throughout the repo. Our utilities stylesheet has [breakpoints](https://github.com/department-of-veterans-affairs/component-library/blob/ac97fbb876018eb991205dfd1466679c38d08b30/packages/css-library/src/stylesheets/_uswds-theme.scss#L18-L26) which are, for the most part, direct swaps in terms of pixel values. USWDS doesn't have a `medium-screen` breakpoint, the closest one being `tablet` which has a value of 640px. We added this earlier in the year and decided to keep the old 768px breakpoint as well. 

Because of its broad use, we need to add all responsive utility class names for `medium-screen:` to our utilities.css output. We get these for all other breakpoints for free from uswds, and the output looks like this: 
```css
 .mobile\:vads-u-border--0 {
    border-: 0;
  }
  .mobile\:vads-u-border-top--0 {
    border-top: 0;
  }
  .mobile\:vads-u-border-right--0 {
    border-right: 0;
  }
  .mobile\:vads-u-border-bottom--0 {
    border-bottom: 0;
  }
```
## Considerations
[slack convo with more context](https://dsva.slack.com/archives/G01BJ3ESXL4/p1721152333492749?thread_ts=1721056516.943829&cid=G01BJ3ESXL4) 

One approach may be to adapt what Formation does by looping through a breakpoint map: 
```scss
@each $bp_name, $bp_value in $breakpoints {
  @media (min-width: $bp_value) {
    @each $name, $size in $font-sizes {
      .#{$bp_name}\:vads-u-font-size--#{$name} {
        font-size: $size !important;
      }
    }
  }
}
```
But instead of breakpoints, the map is comprised of key-value pairs for all utilities that require the `medium-screen` breakpoint, since that is the constant in this situation. 

Another approach could be to figure out how to modify the uswds [system-properties tokens](https://github.com/uswds/uswds/blob/369cf3fdf9abf721a357e864a0f6adbf667ba862/packages/uswds-core/src/styles/_properties.scss#L157-L165) in our own stylesheet. This may save us a bunch of manual work, since then we'd theoretically be able to just add `"medium-screen": true` to our [theme-utility-breakpoints map](https://github.com/department-of-veterans-affairs/component-library/blob/ac97fbb876018eb991205dfd1466679c38d08b30/packages/css-library/src/stylesheets/_uswds-theme.scss#L17-L27)

This is the list of all utilities the require the `medium-screen` breakpoint: 
- [border.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_border.scss#L35-L59)
- [display.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_display.scss#L22-L40)
- [flexbox.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_flexbox.scss#L43-L57) - multiple instances for each flex property
- [font-size.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_font-size.scss#L26-L34) - not sure we need this after our typography migration
- [height-width.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_height-width.scss#L19-L27) - multiple instances height, width, and min/max properties
- [line-height.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_line-height.scss#L22-L30) - not sure we need this after our typography migration
- [margins.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_margins.scss#L83)
- [measure.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_measure.scss#L22)
- [padding.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_padding.scss#L36)
- [position.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_position.scss#L11)
- [text-align.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_text-align.scss#L16)
- [visibility.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/utilities/_visibility.scss#L25) 

Note: the above links also indicate what utilities for each property are needed. For example, the [padding utility loop](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/6bc6d59ae3fb119ac3ec1bb27995cd973301a70d/packages/formation/sass/utilities/_padding.scss#L36-L71) includes all of the class names appended to the responsive prefix: `vads-u-padding--, vads-u-padding-x--, vads-u-padding-y--, etc`. Our css library utilities generate these using [uswds utility helpers](https://github.com/department-of-veterans-affairs/component-library/blob/ca594dabb0862defb44a2374b30cd2eab8957322/packages/css-library/src/utilities/padding.scss#L5). 

## Tasks
- [ ] Determine the best way forward for adding `medium-screen` to the list of responsive breakpoints that generates utility classes that are prefixed with `medium-screen\:`
- [ ] Verify that `css-library/dist/utilities.css` is build with all `medium-screen\:` utilities based on the decided upon solution

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3045?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
