### ISSUE TITLE
Update the close icon in the modal

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3047]
## Description
The close icon is incorrect. It should just be an x in the corner. 

## Details

**Currently**

![Image](https://github.com/user-attachments/assets/57880c9c-8bb6-4d5f-b3f1-e40ef63571ae)

**Update to Match Figma**

![Image](https://github.com/user-attachments/assets/d8841394-8ed8-4d41-ab18-3e0426fef7af)

Modal component in Figma with the correct close icon. 
https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=496-1719&t=1ePojRgbe6Pb724g-1

## Tasks
- [ ] Update the modal close icon to match the icon used in the Figma file. 
- [ ] Have a a designer review and approve 
- [ ] If needed, make updates 

## Acceptance Criteria
- [ ] Modal is close icon is the x and matches the Figma file

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3047?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
