### ISSUE TITLE
Update breadcrumb spacing in Page templates - Design

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3049]
## Description
We have updated the breadcrumb spacing and need to update the spacing in mobile and desktop page templates to match the new spacing requirements.

The final breadcrumb spacing will be -

Desktop - 20px on top (no change) and 48px on bottom
Mobile - 20px on top and 32px bottom

## Details
- [Padding specifications for breadcrumb component - Design #2969](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2969)
- [Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1721245934030259) for more context

## Tasks
- [ ] Conduct small audit of the breadcrumb spacing in Figma
- [ ] Update page template spacing for the breadcrumbs
- [ ] Review designs with PO and DST designers 
- [ ] Review designs with developers and accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Page template spacing for the breadcrumbs is complete and has been reviewed
- [ ] Accessibility and development considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3049?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by caw310** [comment]
Taking this out of the sprint as no work can be done until there is clarity from the forms team on a pattern they're working on.

**Comment by babsdenney** [comment]
@danbrady @LWWright7 This is ready for review. I made a header component that has breadcrumbs embedded inside the component and replaced all the header components with a new local component called "Header with breadcrumbs". 

I haven't fixed the margins yet but have an idea to make that easier to keep track of and update. 

[Figma form template components in the Pattern library](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=112-11074)

**Comment by LWWright7** [comment]
@babsdenney Looks good to me!! Thanks for the review during our sync too!

**Comment by caw310** [comment]
This may carry over as there is still pending review feedback.

**Comment by danbrady** [comment]
@babsdenney LGTM!
