### ISSUE TITLE
Update the Check eligibility screenshot 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3052]
## Description
Update the screenshot on the Check eligibility pattern page. 
https://design.va.gov/patterns/help-users-to/check-eligibility

## Tasks
- [x] Find a screenshot of the current check eligibility pattern 
- [x] Update the documentation page for that pattern with the new screenshot
- [x] Publish the page that has been updated

## Acceptance Criteria
- [ ] Check eligibility pattern page has an updated screenshot

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3052?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady @babsdenney  This is ready for review!!!

**Comment by danbrady** [comment]
@LWWright7 LGTM!
