### ISSUE TITLE
Update Check personal information pattern 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3053]
## Description
Update the Check personal information pattern. Make it reflect what check-in and replace this with that. 
https://design.va.gov/patterns/help-users-to/check-personal-information

Note: we don't need a Figma template for it. 

## Details
Touch base with Ben Brasso about what the check-in team does. 

## Tasks
- [x] Reach out to Ben Brasso (or someone from check-in team) 
- [x] Update the pattern to reflect what the check-in does 
- [x] Have a DST designer and/or PO review 
- [x] Make updates as needed
- [x] Update the documentation page

## Acceptance Criteria
- [ ] The Check personal information pattern page is updated

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3053?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@babsdenney @danbrady This one is ready for review...submitted pull requests (that need approval) to update 4 screenshots.

**Comment by LWWright7** [comment]
Confirmed that the new screenshots have been updated on the doc site!
