### ISSUE TITLE
Update guidance for Keep a record of submitted information pattern

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3054]
## Description
Update guidance for Keep a record of submitted information pattern. 
- Should point to confirmation page template 
- Should update to have a link to the confirmation page template. 
- This one doesn't need a new template, we just need to do a guidance change. This should point to a confirmation page template. We need a link to the confirmation page template
https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information

## Tasks
- [ ] Update guidance for Keep a record of submitted information
- [ ] Have DST designer and/or PO review 
- [ ] If edits are need, make those
- [ ] Publish updated guidance

## Acceptance Criteria
- [ ] guidance for Keep a record of submitted information pattern has been updated

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3054?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by rachelshearerux** [comment]
👋 Hi @caw310 , [here's a direct link to the confirmation page](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2601-126236&t=rjIguwDRXDJ3BkbJ-1) template in the VADS Templates, Patterns, and Forms library.

**Comment by LWWright7** [comment]
@jeana-adhoc  Since we are not creating a pattern "Keep a record of submitted information" would it make more sense to have the Figma link provided in the Description above point to the Confirmation page instead??

**Comment by LWWright7** [comment]
@babsdenney & @danbrady - Ready for review / Pull request initiated.
