### ISSUE TITLE
Update Stay informed of their application status screenshot 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3055]
## Description
Update Stay informed of their application status screenshot with the Claim Status screenshot once they ship it. 
Does not need a template. 

## Details
https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status

## Tasks
- [ ] Find Claim status screenshot 
- [ ] Update screenshot Stay informed of their application status page 
- [ ] Publish the update

## Acceptance Criteria
- [ ] Stay informed of their application status screenshot has been updated

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3055?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by babsdenney** [comment]
Awaiting completion of this epic to finish this ticket. 

Epic: Confirmation Page [#1424](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1424)

**Comment by humancompanion-usds** [comment]
@babsdenney - Please reach out to @skylerschain for a screenshot. Thanks!

**Comment by skylerschain** [comment]
Here's our current silent failure email for CST

![Image](https://github.com/user-attachments/assets/2a9c5653-b4e4-4a18-accc-bfe99413e34f)

**Comment by jeana-adhoc** [comment]
I was asked to add my notes here...

The VFF team has worked to provide templates for other teams to start their emails from.

You can see these templates already shown on this page under "[Email examples](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status#email-notifications)"

However, the screenshots are now out of date as CAIA has updated them.  

[I have the emails in this figma file](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=15-69411&node-type=frame&t=3M0iJ15u4cEH0iVa-11).

Let me know if it'd be helpful to make a PR to update the screenshots
