### ISSUE TITLE
Update  Navigate a long list pattern with Show more 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3056]
## Description
 Update in Figma Navigate a long list with show more. 

Use these experimental tickets as guidance for updating the screenshots on the navigate long list pattern page.
- [Update Navigate long list pattern with correct images #2363](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2363)
- #3185 

## Tasks
- [ ] Update designs  for the pattern
- [ ] Review designs with PO and/or other DST designers
- [ ] If updates are needed, make those
- [ ] Update documentation with the updated screens

## Acceptance Criteria
- [ ] The pattern screenshots have been updated.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3056?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by babsdenney** [comment]
@caw310 Do you have any more information about this ticket?
