### ISSUE TITLE
[Design] - Standardize icon components anatomy in Figma [DRAFT]

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#3058]
## Description
Currently, many icon components in Figma have different structures and layer names. For example, nested icons layers may be called "Shape", "Fill", or "Vector". This causes unnecessary issues when icons are swapped in designs. For example, if a designer adds an icon prefix to the text input, the default icon color uses `vads-input-prefix-color-on-light`, which is the correct fill color. If they change that icon to use `iphone_phone`, the icon fill color reverts to default icon color, `vads-color-base` instead. 

## Tasks
- [ ] [Reference this video from Figma support](https://www.youtube.com/watch?v=98uovRi3qMY)
- [ ] Define the standard naming structure for each icon component
- [ ] Update all Figma icon components have a consistent layer anatomy
- [ ] Update all Figma icon components have a consistent default color applied
- [ ] Validate all icons have the correct scaling applied (so they can be resized)

## Acceptance Criteria
- [ ] Validate swapping icons doesn't not change the icon color, or size in any component that uses icons (i.e. text input, icon button, link, etc.)

**Comment by danbrady** [comment]
This will be fixed from #2930
