### ISSUE TITLE
Update DST Onboarding video for developers

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3062]
## Description
The VADS onboarding video needs to be updated so that there are no longer references to v1 components once all v1 components have been deprecated. 

## Details
Currently DST still has updates to be made to va-table, va-text-input and va-file input. Once we are done with those updates we will record the new onboarding video. 

## Tasks
- [ ] Record onboarding video to explain to how to use the VADS to new VFS developers. 
- [ ] Update presentation slides if needed
- [ ] If you have access, update link to the video on the platform orientation page or ask governance team to update it

## Acceptance Criteria
- [ ] New onboarding orientation on how to use the VADS recording is available

**Comment by shiragoodman** [comment]
@caw310 do you have a timeline planned for when you want to rerecord this?

**Comment by jeana-adhoc** [comment]
Now a duplicate of
- #4452
