### ISSUE TITLE
Add icon to suffix for va-text-input web component - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3063]
## Description
Add the ability to have an icon as a suffix in the `va-text-input` web component. USWDS guidance for input includes prefix and suffix so we should match that. 
https://designsystem.digital.gov/components/input-prefix-suffix/

## Tasks
- [ ] Add ability to have suffix for va-text-input component 
- [ ] Update storybook
- [ ] Have a designer review 
- [ ] Make any necessary changes 
- [ ] Push to prod

## Acceptance Criteria
- [ ] va-text-input component allows for suffix

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3063?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by harshil1793** [comment]
This task is already completed. Here is the [prod storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--docs#with-suffix).

**Comment by caw310** [comment]
Great. I will close this ticket since suffix is added.

**Comment by jamigibbs** [comment]
I think there is a misunderstanding about what needs to be done still. This ticket was created from @danbrady's [comment yeterday here](https://github.com/department-of-veterans-affairs/component-library/pull/1217#issuecomment-2246052259):

> After discussing with Matt, we should stay aligned with the USWDS for this component. So while they don't show examples for suffix icon, it is possible to achieve with their component. They also have the following documentation:

> **Use text or icons. Input prefixes and suffixes can accept either plain text or icons.**

> So VADS should have the same features.

Right now, the component does not accept both **plain text or icons** for both prefix and suffix so we need to add that functionality still for suffix I believe.

Can you verify that @harshil1793?

**Comment by harshil1793** [comment]
@caw310 I saw Dan's comment, and it seems like we need this ticket to add support for an icon suffix for the `va-text-input`. Can I update the description if you're okay with that?

**Comment by caw310** [comment]
@harshil1793 Yes update the ticket as needed. Thanks!
