### ISSUE TITLE
Update memorable date default guidance  - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3067]
## Description
Uupdate documentation and guidance for memorable date on design.va.gov to make the default the text input version. 

## Details
Guidance page for memorable date: https://design.va.gov/components/form/memorable-date
Figma: https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=1534-2806&t=enjzsaX6LbUWIITX-1

## Tasks
- [x] Update memorable date component documentation for design.va.gov
- [x] Coordinate with accessibility specialist to create or update accessibility guidance
- [x] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3067?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7
