### ISSUE TITLE
[Design] - Implement button line height in Figma

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#3089]
## Description
Depending on the outcome of [the research ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3088), design team needs to implement the proper solution which could include creating a new set of variables for button(s) in Figma that includes 2 lines of text

We have a new button variation to account for buttons where the button text wraps to two lines. We need to add that variation to current button. 

## Details
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3088

[Button comment thread in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk?node-id=199-1198#915017480)

## Tasks
- [ ] Update the button in figma for the 1.15 option
- [ ] Rename the button 1.15 to something that Designers will understand to use when button text wraps to two lines. 
- [ ] Review designs with PO and DST designers 
- [ ] Review designs with developers and accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] The button has a variation that will change the current button to the two line variation
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility and development considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by LWWright7** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3089?planning-poker) with Zenhub @babsdenney @danbrady

**Comment by LWWright7** [comment]
see also #3232
