### ISSUE TITLE
Monospace font updates - Documentation

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3103]
## Description
Add or update documentation and guidance for Roboto mono font on design.va.gov. 

There are few places that need the documentation updated and there might be other places not accounted for in this list.  

- [ ] [Typography page](https://design.va.gov/foundation/typography)
- [ ] [Utilities > Font family](https://design.va.gov/foundation/utilities/font-family)
- [ ] [Table component](https://design.va.gov/components/table)

## Details

- [Table component in Figma](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=1879-677)
- [Typography page in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199-1182)
- [Design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2847) to add Roboto mono to DS (complete)
- [Development ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3104) to update table component (to do)
- [Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1721767299262339) to discuss Monospace font options

## Tasks
- [ ] Do a thorough review of the Design System doc site to make sure all the documentation is correctly updated. 
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
@caw310 - I'm moving this ticket into sprint 26 so we can deliver on adding the monospace font faster. Health portfolio is waiting on this from us and it was #3 on their prioritized list (which I'll share in Slack momentarily). Thanks! Ping me if I need to move something out of sprint 26 to make room for this.

**Comment by amyleadem** [comment]
We've drafted some accessibility considerations in the [Monospace font - accessibility review doc](https://docs.google.com/document/d/1dtmgFRjCKoDcJRyEZAhzUhZCIAKuYD7ik_31i7rSwkA/edit?tab=t.0) (Google doc :lock:). There is a little more content in doc, but I'm copying the likely publishable recommendations for the pageshere: 

Considerations for the typography page:
 > **Use monospace fonts sparingly.** Monospace fonts can be difficult to read, especially at small sizes or with poor color contrast. Use monospace fonts only for numerical data in tables, code examples, or when precise horizontal alignment is needed. For body text, choose a sans serif typeface.

Considerations for the table component page:
> **Use monospace fonts for numerical data in tables, such as percentages, currency, or totals.** Do not use monospace fonts for phone numbers, zip codes, dates, or other data that can’t be added up.
