### ISSUE TITLE
Add monospace font - Development

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3104]
## Description
The USWDS table requires numerical data use a monospace font. We have decided to use **Roboto mono** as the monospace for the VADS.

[USWDS Table guidance ](https://designsystem.digital.gov/components/table/#guidance)

We will need to add the Roboto mono font to the VADS and update the table examples to use the Roboto mono font. See [USWDS](https://designsystem.digital.gov/components/table/#sortable-table-rows-2) for guidance on where to apply the mono font. 

## Details

- [Table component in Figma](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=1879-677)
- [Typography page in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199-1182)
- [Design ticket](https://github.com/orgs/department-of-veterans-affairs/projects/768/views/21?sliceBy%5BcolumnId%5D=77483206&sliceBy%5Bvalue%5D=Design&pane=issue&itemId=65034260) to add Roboto mono to DS (complete)
- [Documentation ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3103) to update table component (to do)
- [Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1721767299262339) to discuss Monospace font options

## Tasks

- [ ] Add roboto mono font with regular and bold font variations to VADS
- [ ] Update the table examples to use Roboto mono where appropriate
- [ ] Update any developer documentation
- [ ] Contact designer for design review
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3104?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
