### ISSUE TITLE
Fix styling of official government banner

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#3109]
## Description

1. In Safari, the "Here's how you know" button has a different background color. This should match the background of the official gov. banner.
<img width="1453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEloQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7acbfc7bd189aa65bc44c2b637658f35fde2d5d/image.png" alt="image.png" />

2. All browsers - The text and buttons in the official gov. banner are not aligned vertically.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3326d9e8fe9978154f4ac9cc54c153b74b74a097/image.png" alt="image.png" />
I believe it should look closer to this:
<img width="886" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dce9f81abb9660147b0b057c28c17d5fdfe60344/image.png" alt="image.png" />

## Tasks
- [ ] Fix styling issues

## Acceptance Criteria
- [ ] Button background is correct on Safari
- [ ] Vertical alignment is fixed
