### ISSUE TITLE
Discovery: prototyping options 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3110]
## Description
This ticket is to do discovery work about prototyping options that factor in cost and accessibility. This stemmed from a design weekly chat meeting when Barb suggested considering a VADS component and template library in Codepen. 

## Tasks
- [ ] Look into prototyping options
- [ ] When reviewing options and making suggestions, consider cost and accessibility
- [ ] Write up recommendation
- [ ] Share and review with PO and DST

## Acceptance Criteria
- [ ] Tasks above are completed and there is a recommendation for a prototype tool

**Comment by caw310** [comment]
closing for now
