### ISSUE TITLE
[Design] Release notes process 

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3121]
## Description
One of the weakest scores in the [Design System Survey](https://docs.google.com/presentation/d/1rutEBWkTo2Mk0LlOfjQ91xeYB9To5sGp11OJBMIJ7IU/edit?usp=sharing) we completed was around communication. When we were upgrading components from the USWDS v1 to v3 components we had a huge focus on that goal. Now that we have some time to regroup and plan things out we can figure out what future communications processes can look like. 

- How do we want to communicate out releases to different roles like Designers, Product Owners, and Engineers? 
- Are there ways we can automate this process as well?
- How do DST users prefer to have release notes communicated?
- Are there updates to the doc site that could help with communication?
- Are there some quick wins we could implement as well as longer term goals?
- What are other Design Systems doing for release note and communication processes?

## Details

This might be an epic ticket to figure out some options. Maybe talking more to the DST users on preferred communication options and pain points in the current process. This ticket can be used as the initial starting point to branch out into different focus areas. 

## Tasks
- [ ] Use the [Design System Survey](https://docs.google.com/presentation/d/1rutEBWkTo2Mk0LlOfjQ91xeYB9To5sGp11OJBMIJ7IU/edit?usp=sharing) and [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712767191559/62f5e4ccb617c862cd7379cbfea66522c1ea00f2?sender=uc445c662daeb45814b8d8356) as a starting point to figure out what communication feedback has been received
- [ ] Research options for communication processes that could improve communication with DST designers
- [ ] Collaborate with the DST team on any findings
- [ ] Review any ideas you would like to implement with DST Designers, PO, and PM's
- [ ] Create any ongoing tickets for work after this ticket

## Acceptance Criteria
- [ ] Presented your findings to the team and have created tickets for any future work

**Comment by babsdenney** [comment]
@danbrady @LWWright7 This is ready for review.

[Figma release note process](https://docs.google.com/document/d/13LBsGqkJbtLILvET7PbUjOyxObRjPsPeHxCNxv-Mzr0/edit?usp=sharing)

**Comment by caw310** [comment]
Carrying over as review is needed.
