### ISSUE TITLE
Document how visual regression testing works

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3125]
## Description
Create a confluence page with a write up on how visual regression testing works so that the process is documented. 

## Details
Slack thread: https://dsva.slack.com/archives/G01BJ3ESXL4/p1722543223788309

## Tasks
- [ ] Draft document on how visual regression testing works
- [ ] Have DST engineers review and provide feedback
- [ ] Update document if needed 
- [ ] Finalize document 

## Acceptance Criteria
- [ ] There is a confluence page with a description of how visual regression testing works
