### ISSUE TITLE
[Design] Research & Design - Recognize + serve LOA1 users a "Verify your identity" alert upon sign-in

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#3131]
## Details
_optional, delete section if not needed_
See ticket [2556](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2556)

## Tasks
- [ ] Contact the team that created the experimental request to see if there are any unanswered questions or assets for designers
- [ ] Research to see if the experimental request is appropriate or if it needs update to design / color theory / etc
- [ ] Determine the specific Figma updates and publishing needed (updated component or new component)
- [ ] Create design (mobile / desktop) that align with USWDS / Platform Design system guidelines 
- [ ] Validate that the verbiage, wording and content is appropriate length, etc

## Acceptance Criteria
- [ ] Validate the Figma component is up to standards for Platform Design System (tokens, spacing, layer names, etc)
- [ ] Review by other designers on the team
- [ ] Validated by Matthew Dingee
- [ ] Publish to Figma

**Comment by caw310** [comment]
Closing as these two experimental design tickets are to be worked on together so this is no longer relevant. 
[Experimental Design - Recognize + serve LOA1 users a "Verify your identity" alert upon sign-in](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2556) 

[New component: Sign-in widget (breaking out from general alert component)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76785)
