### ISSUE TITLE
[Developer] Research & Design - Recognize + serve LOA1 users a "Verify your identity" alert upon sign-in

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#3132]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Description
Refer to Experimental Design ticket #2556 also the research / design ticket #3131 

## Details
_optional, delete section if not needed_

## Tasks
- [ ] 

## Acceptance Criteria
- [ ]

**Comment by caw310** [comment]
Closing as design work for this will be done in [(experimental design request) Sign-in Alert - Design](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3151)
