### ISSUE TITLE
[Documentation] Research & Design - Recognize + serve LOA1 users a "Verify your identity" alert upon sign-in

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#3133]
## Description
Refer to Experimental Design ticket #2556 / Discovery ticket [#3141](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3141) / Design ticket #3151  / Dev ticket #3132 

## Details
We met with @sterkenburgsara and @laurwill to understand some of the details of the requirements for the sign-in alert design. While we were able to figure out the sign-in alert design but the documentation still needed somethings figured out.

You can see the [notes](https://docs.google.com/document/d/1gfyxxr6sIjrvSPpKFNuCWTlr_V4m1ld4I1VUif1b9QE/edit#heading=h.cou621uxyymd) from our meeting to understand some of what we went over when it came to guidance. 

They suggested reviewing guidance with CAIA and the identity team. 

## Tasks
- [ ] Figure out what guidance should be included with the alert sign-in component
- [ ] Update any existing content necessary
- [ ] Review with CAIA

## Acceptance Criteria
- [ ] Sign in alert guidance is complete

**Comment by caw310** [comment]
closing as I believe this is not needed since we built Alert sign-in.
