### ISSUE TITLE
[Design] Table variations

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3137]
## Description
We have added the borderless table and the mobile stack table Figma but are missing some of the table variations that [USWDS](https://designsystem.digital.gov/components/table/) offers.

Create designs for table variations and update the example library with the new table examples.

Table variations to add for both desktop and mobile:

- [Striped table](https://designsystem.digital.gov/components/table/#striped-table-2) 
- [Scrollable table ](https://designsystem.digital.gov/components/table/#scrollable-table-2)

Also to include - You can see in the comments below @josephrlee has added a use case to include a option of adding components within the cells. 

## Details

- [Table in VADS Component library (Figma)](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=1879-677)
- [Table in VADS](https://design.va.gov/components/table)
- [Table in USWDS](https://designsystem.digital.gov/components/table/)

## Tasks
- [ ] Create table variations for both mobile and desktop
- [ ] Add options to include custom components inside the table cell
- [ ] Review designs with PO and DST designers 
- [ ] Publish and update the table variations in the design system example library 
- [ ] Review designs with developers and accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility and development considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3137?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by josephrlee** [comment]
Hi @babsdenney! I was working on a table for the debt portal, and I have one feature request for the table cell. It'd be great to be able to use a custom component inside of it besides just text, as you can with many of the other vads components. 

For context, here's a screenshot of what I'm trying to do in my version of the table: 
<img width="701" alt="Screenshot 2024-08-06 at 4 35 52 PM" src="https://github.com/user-attachments/assets/cc094a0b-72c7-4097-a483-f910845e5822">

**Comment by babsdenney** [comment]
@josephrlee That is great feature to add to the table. We can include that work here. Thank you for letting us know. 🥇

**Comment by caw310** [comment]
@josephrlee Your suggestion would be a feature request. You may want to submit an experimental design request. 

cc: @humancompanion-usds

**Comment by danbrady** [comment]
@babsdenney @LWWright7 [Table updates](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=6089-652&t=PFLqMKtNZQPejcRo-1) are ready for review. Thanks!

**Comment by babsdenney** [comment]
@danbrady This looks great! Very thorough examples and like the at you used a VADS component to show the steps in the process. Great work!
