### ISSUE TITLE
[Design] Sign-in alert discovery

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3141]
## Description
We have three experimental design tickets that have similar request.  
- Experimental Design - Recognize + serve LOA1 users a "Verify your identity" alert upon sign-in[#2556](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2556)
- New component: Sign-in widget (breaking out from general alert component)[#76785](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76785)
- Experimental Design [Alert: need alt. version of sign-in alerts + lock icon] [#3105](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3105)

Overall this is a variation of the alert with specific content for signing in. A content component. 

## Details
We need to understand the requirements a bit more: 
- Are these different request/tickets the same?
- Can the tickets be combined into one ticket?
- What are the requirements?
- Are there any variations?
- New icons?
- Will this need support from CAIA?

## Tasks
Do a discovery for this experimental request
- [ ] Reach out to the people who submitted the tickets to go over the requirements for the different design request
- [ ] Figure out the requirements and review with the team
- [ ] Create tickets for the work 

## Acceptance Criteria
- [ ] Requirements are finalized 
- [ ] Tickets are updated/created for any work that is discovered

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3141?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by sterkenburgsara** [comment]
I am also having issues with needing to detach the component in Figma in order to add a button or action link to any of them for these sign-in and id-verification alerts. Not sure if that's related or not to how we want to handle this ticket, but just FYI.

**Comment by babsdenney** [comment]
@LWWright7 @danbrady and I met with @sterkenburgsara and @laurwill to understand the requirements. 

Here are the [notes](https://docs.google.com/document/d/1gfyxxr6sIjrvSPpKFNuCWTlr_V4m1ld4I1VUif1b9QE/edit?usp=sharing) from the meeting.

Based on the feedback from the meeting, the design and documentation tickets have been updated. We have three tickets to complete the sign-in alert work. 

- #3131 
- #3133 
- #3132
