### ISSUE TITLE
[Documentation] - Remove Font Awesome

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#3156]
## Description
Now that we've migrated to USWDS/Material icons, we should remove all mentions of FA on the doc site.

## Tasks
- [ ] Update foundation and component icon pages
- [ ] Search doc site for any other mentions of FA

## Acceptance Criteria
- [ ] No mentions of FA should be on design.va.gov
