### ISSUE TITLE
[Design] - Remove Font Awesome from Figma

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#3157]
## Description
Now that we've migrated to USWDS/Material icons, we should remove all mentions of FA in Figma.

## Tasks
- [x] Ensure other components do not use FA icons
- [x] Move FA icons to a deprecated page

## Acceptance Criteria
- [x] Validate FA icons are not on the icons page
- [x] Validate FA are on a page in the deprecated section

**Comment by danbrady** [comment]
@babsdenney @LWWright7 [This is ready to review](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199-1181&t=2MFNMfocL5queAAj-1). 

Note: The icons are not fully removed from Figma. Similar to when we deprecated number input, this component has a garish purple box on top of the each icon component. Should a designer attempt to use a FA icon, they'll see that first and will have to "opt-in" to hide that in order to use it. After some time we should be able to fully remove these icons and unpublish them completely.

**Comment by LWWright7** [comment]
@danbrady LGTM!!! I like that little shape...looks like a little germ or virus! lol   🦠
