### ISSUE TITLE
Focus Management - Documentation

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#3164]
## Description
Add or update documentation and guidance for focus management on design.va.gov. 

## Details

See discussion on: https://github.com/department-of-veterans-affairs/va.gov-team/issues/457

We want to detail focus management, this should include:
- Details on the focus indicator.
- When you should or should not use `outline: 0` or `outline: none` (never?)
- Dos and Don'ts of focus management. 
  - When to manually set focus. 
  - What are interactive elements/what are not interactive elements.

## Tasks
- [x] Write or update documentation for design.va.gov
- [x] Request documentation draft review
- [x] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by rsmithadhoc** [comment]
PR created for this https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3330
