### ISSUE TITLE
va-button-pair: Allow for custom button labels 

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#3167]
## Description

From the design system council meeting, the `va-button-pair` component should allow for custom button labels.

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2362

## Tasks
- [ ] keep the existing button variations as-is but allow for custom label text
- [ ] ask questions in team Slack if anything is unclear

## Acceptance Criteria
- [ ] va-button-pair allows for custom button labels

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3167?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
