### ISSUE TITLE
Update approved button labels - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3168]
## Description
Add or update documentation and guidance for va-button-icon on design.va.gov. When adding a new component, use the [component documentation template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/src/_components/template.md).

Add list of approved button labels to the Button Labels page in Content Style Guide

## Details
See this experimental design ticket 
[Experimental Design [va-button-pair] (USWDS v3) - Allow for custom button labels](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2362#top)

## Tasks
- [ ] Add list of approved button labels to the Button Labels page in Content Style Guide
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
I've got a PR in flight that adds the button lables shared content to button group and button icon. However, that shared content page doesn't have a whitelist of labels. If that's what we want then we need Danielle and the Content team to create it.

**Comment by humancompanion-usds** [comment]
I just reviewed our button label guidance and it's included on the Button group page. I think we're good here.
