### ISSUE TITLE
Update guidance for process list eyebrow - documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3178]
## Description
Update the examples for process list. See Slack thread for details. 
https://dsva.slack.com/archives/C01DBGX4P45/p1723483551152199

![Image](https://github.com/user-attachments/assets/767d5103-b181-4c91-ab15-07a394317fe5)

## Details
Process list guidance page [https://design.va.gov/components/process-list](https://design.va.gov/components/process-list)

## Tasks
- [ ] Update the examples and guidance for process list (eyebrow) 
- [ ] Get a DST designer to review
- [ ] Update as needed
- [ ] Publish changes

## Acceptance Criteria
- [ ] Process list has updated examples and guidance (if needed)

## Estimating
Designers: 
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@babsdenney
@danbrady
@LWWright7

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3178?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady & @babsdenney I created a pull request to update the screenshot for the example of education benefits (form 22-1995).  However, it looks like somebody has already updated the screenshots of the other two examples (default & status) to match the conversation that Dan & Skyler had in Slack.  

![Image](https://github.com/user-attachments/assets/5d7a0de1-9595-4737-ac3d-adba43fdbfee)

![Image](https://github.com/user-attachments/assets/cc29eefd-147d-4903-a2cb-84500d839c56)


Is this all that needs to be done??

Should anything be added to the usage section towards the bottom?? 

(Sorry, I haven't done many documentation tickets before)

**Comment by LWWright7** [comment]
@babsdenney & @danbrady   What do you think of this as an addition to the "Content considerations" section of the documentation?

![Image](https://github.com/user-attachments/assets/62151b8e-e4cb-4805-ab3e-18eddcd2e56f)

**Comment by LWWright7** [comment]
@danbrady & @babsdenney - New pull requests for the updated screenshot & verbiage.
