### ISSUE TITLE
Create video on how to use the DS component library in Figma

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3192]
## Description
New designers from VFS teams need instructions on how to use the VA DS component library in Figma. We need a video created for onboarding new VFS designers. 

## Details
Work with Allison and Naomi as needed. 

## Tasks
- [ ] Create a video showing a designer or engineer how to access the VA Design System components in Figma
- [ ] Create a power point presentation if needed
- [ ] Provide instructions on how the component library is organized in Figma
- [ ] Provide any tips on how to use Figma if possible 
- [ ] Have Allison and Naomi review, and/or DST designer 
- [ ] Make any updates as necessary
- [ ] Share the video and have it published

## Acceptance Criteria
- [ ] Video is published and accessible to new VFS designers for onboarding

**Comment by caw310** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3192?planning-poker) with Zenhub @danbrady
