### ISSUE TITLE
CSS Library - Utilities - Swap border import

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3199]
## Description
We need to import border utilities from css-library. This is broadly a two step process:
1. Update breakpoint names for the border classes to USWDS v3 equivalents
2. Comment out the border import in [formation/core.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/core.scss#L83), manually publish a new formation release, and then update the version of Formation in vets-website. 

| Current VADS Name | USWDS v3 Name |
| --------------------------- | ------------------------- |
| xsmall-screen (320px)          | mobile (320px) |
| small-screen (480px) | mobile-lg (480px) |
| small-desktop-screen (1008px) | desktop (1024px) 
| large-screen (1200px) | desktop-lg (1200px) |

## Considerations
- We won't need to touch the `medium-screen` breakpoint since we're keeping that in and have manually added it to our utilities.css file. 
- Likewise, `tablet` is identical across both stylesheets and doesn't need to be changed, so it isn't included in the table above. 
- There's a 16px difference between `small-desktop-screen` and its replacement, `desktop`, but this shouldn't matter. 
- Global search shows 1 instance of `xsmall-screen:vads-u-border-...` and 3 instances of `small-screen:vads-u-border-...`. None for larger breakpoints. 
- Above changes may be able to fit in one PR since it's only 4 updates total. 

## Tasks
- [x] Search and replace instances of `<vads-responsive-prefix>:vads-u-border-` with corresponding uswds v3 name in the table above. Example: `xsmall-screen:vads-u-border-bottom--0` becomes `mobile:vads-u-border-bottom--0`
- [x] run vets-website locally to verify that breakpoints are being applied from css-library `utilities.css`
- [x] specifically run the [proxy-rewrite](https://github.com/department-of-veterans-affairs/vets-website/blob/aab3a4bb7c55625604ce8f62b71097f16e858ef3/src/applications/proxy-rewrite/README.md#L1) application and test the injected header and footer
- [x] In formation, comment out the border import in [formation/core.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/core.scss#L83)
- [ ] Bump the version number for Formation and manually publish to NPM
- [x] Update the Formation version in vets-website. 

## Acceptance Criteria
- [x] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3199?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
