### ISSUE TITLE
Edit / publish video on how to use the DS component library in Figma

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#3221]
## Description
Take the raw video created by Dan Brady (#3192) and edit it, prepare for web, etc.

## Details
Work with Allison and Naomi as needed. 

## Tasks
- [ ] Create a video showing a designer or engineer how to access the VA Design System components in Figma
- [ ] Create a power point presentation if needed
- [ ] Provide instructions on how the component library is organized in Figma
- [ ] Provide any tips on how to use Figma if possible 
- [ ] Have Allison and Naomi review, and/or DST designer 
- [ ] Make any updates as necessary
- [ ] Share the video and have it published

## Acceptance Criteria
- [ ] Video is published and accessible to new VFS designers for onboarding
