### ISSUE TITLE
Update va-link External link variation guidance - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3224]
## Description
Update documentation and guidance for va-link on design.va.gov to include external links. 
Storybook [External link](https://design.va.gov/storybook/?path=/story/components-va-link--external) variation

## Details
There was a request to support external links. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2922

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3257
```

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3224?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
Removing "Back" link variation from this ticket as it has separate needs/tasks.

**Comment by rsmithadhoc** [comment]
@danbrady For the external link:

- Let's put the "(opens in a new tab)" text in there. That will be the most accessible. It also matches our existing guidance under content, some previous a11y work supports this (according to a11y specialists, they said this was the way to go), and [W3C recommends this](https://www.w3.org/TR/WCAG20-TECHS/G201.html) as well.
- For the icon, the guidance explicitly says don't use it, so I think we get rid of it. Having both the text and the icon may be redundant.

I can update the component with that, if that all sounds good to you.

Thanks!

**Comment by danbrady** [comment]
Thanks for review, Ryan. 

@humancompanion-usds We just added the [va-link variation with the external icon](https://github.com/department-of-veterans-affairs/component-library/pull/1269) about a month ago. Based on Ryan's decision, should we:
1) Remove that variation?
2) Update our Statement of Truth to use "(opens in a new tab)" instead of the icon?

**Comment by humancompanion-usds** [comment]
1. Yes. It's annoying but, yes.
2. Yes.
3. Deprecate the icon entirely (i.e. remove it)

**Comment by danbrady** [comment]
FYI @caw310
