### ISSUE TITLE
[Design]Update Alert spacing in Figma

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3231]
## Description
We are finding some discrepancies in spacing between the alert in Figma and in code. The 320px content section in Figma is 184px and the content width in code is 234px. We need to update Figma so that the content spacing is the same as in code.

Look through all the different variations to make sure that Figma is aligned to what is in the USWDS and the VADS. There are many variations of the alert. You have the dismissible alert, the expandable alert, the slim alert, and more. The alerts have different spacing depending on the variation.
Fix the alert in Figma so that the spacing aligns with the spacing in code.

## Details
- [Figma - Alert](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=539-4085)
- [Storybook - Alert](https://design.va.gov/storybook/?path=/story/uswds-va-alert--warning)

## Tasks
- [x] Audit the alert component and find any design discrepancies between the alert in code, the USWDS, and Figma.
- [x] Fix the alerts in Figma.
- [ ] Review with DST Designers, PM, PO's.
- [ ] Create any additional tickets for development changes if needed.

## Acceptance Criteria
- [ ] The alerts in Figma align with the alerts in code and the USWDS

![image](https://github.com/user-attachments/assets/99bae886-bfd8-4e14-9db5-856fbd5538ba)
![image](https://github.com/user-attachments/assets/0e9f1d09-e454-42a6-b9c9-39a07813e7c9)

https://github.com/user-attachments/assets/27e7a199-ab4e-40bf-86d1-9b9a0edaad0e

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3231?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@babsdenney & @danbrady This one is ready for review!!

**Comment by LWWright7** [comment]
Here are the items that were updated after an audit of the USWDS site:

1. The right padding for an alert with no close icon was incorrect in Figma, changed to 16 px per code on Storybook (fixed for both mobile and desktop):
(this IS the correct padding for an alert WITH a close icon, FWIW)
![Image](https://github.com/user-attachments/assets/0fbd637e-3de2-4a16-89a5-911454c66faa)
![Image](https://github.com/user-attachments/assets/d0f446d4-fcf2-4d27-8a03-7ff0cced37f8)
![Image](https://github.com/user-attachments/assets/6903a2e4-bc4b-438b-9cf9-65ae23a84b67)
![Image](https://github.com/user-attachments/assets/43dea499-6cea-4708-a37b-2aad73eb8062)
![Image](https://github.com/user-attachments/assets/47ab81e3-7f9a-4faa-a489-8e63fc872005)


2. The left padding between the icon and the left rule line was incorrect in Figma, changed it to 16 px per code on Storybook:
![Image](https://github.com/user-attachments/assets/4b601119-6931-4bba-b49d-7c028c8db34d)
![Image](https://github.com/user-attachments/assets/aceb3cb3-ff68-4898-9aac-fe6787b6547e)
![Image](https://github.com/user-attachments/assets/70f586a0-08e3-4dce-827f-4c669f223c14)

3. The padding around the close icon (x) was incorrect in Figma. It should be 16 px all the way around.
![Image](https://github.com/user-attachments/assets/552af88b-690b-4571-ae3e-eb225ccf5623)
![Image](https://github.com/user-attachments/assets/4beee959-fac8-4b9d-895f-bf0633fcdcfc)
![Image](https://github.com/user-attachments/assets/58dc696c-7d39-4cad-9b5e-8195049fd7e6)

4. For mobile screen size, in the alert with no close icon (x), the content area was slightly smaller than it should have been in Figma. Was updated to 249.34 px
![Image](https://github.com/user-attachments/assets/99eaee60-1d4f-4fc3-9633-106cc3499d50)
![Image](https://github.com/user-attachments/assets/b4431525-2660-4057-9e27-69b655e43f24)

5. For the slim alert, in the alert with no close icon (x), the content area was slightly smaller than it should have been in Figma. Was updated to 257.34 px
![Image](https://github.com/user-attachments/assets/84dcfb53-0e19-454c-ae8e-26ac1a085f3e)
![Image](https://github.com/user-attachments/assets/eccd2064-3512-4986-bd1a-7c02fae70e3d)

6. For the slim alert, in the alert with a close icon (x), the content area was slightly smaller than it should have been in Figma. Was updated to 216.34 px
![Image](https://github.com/user-attachments/assets/4dbcbf02-8057-4f81-ba3c-30c5851af629)
![Image](https://github.com/user-attachments/assets/9058f47d-67ef-4aef-a6a3-f8daa1c570a8)

7. The close icons were all too close to the right hand bounding box.  Instead of 16 px around the entire icon, there was 16 on the top, but only 8 on the right hand side.  This was updated on all instances with the close icon.
![Image](https://github.com/user-attachments/assets/b09fbeea-09ac-41c4-ae3d-c05d554d3d20)
![Image](https://github.com/user-attachments/assets/4ed3f811-519f-42e1-bb88-35d72e902081)


The one item that was not able to be fixed is that on the XL Desktop screen size there is another added margin that pushes the content of the alert further to the right.  Initially I believed that the content was centered in the extra wide alert space, but as you can see there is a 244 px margin on either side of the content area.  The only way I would know to solve this would be to create a 3rd size within the component to account for this extra padding:
![Image](https://github.com/user-attachments/assets/33bb8055-bdd3-40fe-8be5-d6bbf3f5196c)
![Image](https://github.com/user-attachments/assets/596a30e1-a332-484d-a3c8-1bc0a98cd767)
 ![Image](https://github.com/user-attachments/assets/285bec1c-ee55-4096-aa4a-a164f4f44513)

**Comment by caw310** [comment]
This will carry over because review is not done.

**Comment by LWWright7** [comment]
@danbrady & @babsdenney  Please let me know when this one is good so I can publish the updates in the Component Library.  Thanks! :)
