### ISSUE TITLE
Fix the desktop breakpoint to match USWDS

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3233]
## Description
There is a 16px difference between our current $small-desktop-screen (1024px), and the uswds $desktop (1008px) breakpoint. The VADS small desktop breakpoint should match the USWDS breakpoint and be 1008px. 

## Tasks
- [ ] Update the $small-desktop-screen to match USWDS $desktop which is 1008px
- [ ] Review with DST designer 
- [ ] Run any tests and make updates as necessary
- [ ] Publish the change 

## Acceptance Criteria
- [ ] VADS small desktop breakpoint matches  USWDS breakpoint at 1008px.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3233?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
We should take this opportunity to add the uswds named breakpoints to [breakpoints.json](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/tokens/breakpoints.json) alongside the existing ones. Doing so will give teams time to change over to the new ones. 

| name | value | 
| -------- | --------- | 
| mobile | 320px |
| mobile-lg | 480px |
| desktop | 1024px |
| desktop-lg | 1200px |
