### ISSUE TITLE
Update $small-desktop-screen  breakpoint - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3240]
## Description
Add or update documentation and guidance for $small-desktop-screen breakpoint to 1024px on design.va.gov. 

## Details
Once the development work is done, the guidance needs to be updated. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3233

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3233
```

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3240?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
This is blocked by #3233
