### ISSUE TITLE
Remove any React to web-component migration tools that are no longer needed

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#3244]
## Description

With the [React to web-component migration documentation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3241) now removed, we should do an audit and remove any scripts and eslint rules that were created to assist in the migration.

## Tasks
- [ ] Audit the [ESLint rules](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/eslint-plugin/lib/rules) and remove anything no longer being used.
- [ ] Check vets-website to make sure any previously removed ESLint rules aren't being loaded anywhere there too and cleanup.
- [ ] Check if the [component-migration script](https://github.com/department-of-veterans-affairs/vets-website/tree/main/script/component-migration) is still needed and if not, remove.

## Acceptance Criteria
- [ ] any React to web component tools that are no longer needed have been removed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3244?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc
