### ISSUE TITLE
[Design] QA/Release process

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3256]
## Description
We need some kind of QA process for what is being released. Things are getting released without knowledge. We might need to look into a process where the Designers are writing up the tickets with Developers so that the simple small things aren't getting released without QA. We need to stop putting things in storybook before we have a guidance. 

1. Every component change should go to Design first and then to Dev. We shouldn’t be throwing it over the wall. Figure out with where does accessibility come into play here. 
2. Then we should write the guidance and then we should ship it. 
3. There is a rare exception where we need to rush changes out before guidance. But ultimately it should be a slower process. Maybe accessibility should be introduced before development.  We are usually following the process for large things but for smaller changes it falls through the cracks. 

Work with Engineers to create a QA process that will

- Promote more communication and QA between Engineers and Designers. 
- Make sure changes aren't being released before guidance updates.
- Communicate information to the Council team

This ticket could go beyond just documentation and we could look into ways to make releases easier with Github Actions or new templates or processes for ticket create. There are ideas of making every part of a release combined into one ticket. There are also ideas of creating epics for even the smallest tickets that have multiple parts. Github is releasing new features soon to link tickets. We could look into ways that technology could help improve the QA/release process for the DS. 

## Tasks
- [ ]  Talk to Micah about the release process and any documentation that is currently out there
- [ ] Research best practices for QA for large teams
- [ ] Collect all your research and present the team
- [ ] Present your work to the DST for approval and guidance
- [ ] Figure out next steps and create any other tickets to result from this work

## Acceptance Criteria
- [ ] Your research and recommendations have been discussed and next steps have been set in motion and tickets have been created for any further work needed

**Comment by caw310** [comment]
Closing. Will reopen when we pick up this work.
