### ISSUE TITLE
External Link variation - Accessibility Review

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#3257]
## Description

We need to conduct a full accessibility review of the external link component to determine the correct guidance. The component can be viewed in [Storybook](https://design.va.gov/storybook/?path=/story/components-va-link--external)

## Details
Currently, our [content guidance](https://design.va.gov/storybook/?path=/story/components-va-link--external) states:

> Explain when a link is opening in a new tab with text, not an icon. Add “(opens in new tab)” to notify users when a link is opening in a new tab.

However, our external link variation does have an icon, does not use any aria-* attributes, or provide screen reader only content. 

## Tasks
- [x] Determine the correct guidance for external links
- [x] Update content guidance
- [ ] Update component usage guidance

## Acceptance Criteria
- [ ] Component follows guidance on both content and component pages

**Comment by caw310** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3257?planning-poker) with Zenhub @rsmithadhoc

**Comment by rsmithadhoc** [comment]
This variation looked good according to the accessibility testing checklist and I answered the pending questions on what to do about the icon. We will be updating this to match what's under the **Content** section of the site in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3303
