### ISSUE TITLE
Update the message for  file input - multiple

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3269]
## Description
Skyler shared feedback from research about text related to multiple file input. See [Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1726063352920509) 
Update the text for multiple file input to `Drag an additional file or choose from folder`. 

## Tasks
- [ ] Update text for File Input - Multiple https://design.va.gov/storybook/?path=/docs/uswds-va-file-input-multiple--docs
- [ ] Have a designer review 
- [ ] Make any edits based if needed
- [ ] Publish update 

## Acceptance Criteria
- [ ] Text for File Input - Multiple has been updated

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3269?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc
