### ISSUE TITLE
[Design] Discovery - Full-width buttons on mobile

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3288]
## Description
Currently, buttons don't expand to full-width in mobile but button groups do expand to full-width. We aren't consistent with button behavior on mobile and it would be helpful to do some research and figure out a direction for buttons on mobile. [USWDS buttons ](https://designsystem.digital.gov/components/button/)do expand to full-width. 

## Details
[VADS Buttons](https://design.va.gov/components/button/)

## Tasks
- [ ] Conduct a audit to figure out the current state of buttons on mobile. 
  - [ ] How are buttons being used in VFS?
  - [ ] Should all buttons expands to full-width on mobile? 
  - [ ] Are there exceptions?
 - [ ] Figure out a direction for buttons on mobile.
 - [ ] Discuss findings with team
 - [ ] Create tickets for any work that comes from this discovery process

## Acceptance Criteria
- [ ] Presented team with findings
- [ ] Created tickets for any future work necessary

**Comment by humancompanion-usds** [comment]
My preference at the moment would be that we provide an option that allows the buttons to expand to full width at mobile. Teams can use that to adopt the new behavior. Then we'd need to do a button usage audit to determine how many application interfaces would break if we change the default behavior. If that's super minimal then we could consider it. But I'd like to avoid system-wide forced adoption of changes for a quarter or two post-upgrade.

**Comment by tbaker1026** [comment]
@babsdenney is this still an issue?
