### ISSUE TITLE
Master Issue: Language Toggle

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3297]
## Description
This is the master ticket for work related to [Experimental Design (language toggle for multilingual content)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/667#top) 

## Details
This ticket will be used to track all the work that is needed to complete the work necessary to add the language toggle to the VADS. 

Figma: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2582 
Development: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2583 
A11 review: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2584 
Documentation: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2585 

## Tasks
- [ ] Design: Add component to Figma: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2582 
- [ ] Development: Build web component and add as component to Storybook https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2583 
- [ ] Accessibility review of the web component: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2584 
- [ ] Update documentation site with guidance for language toggle: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2585 
- [ ] Request Staging review 
- [ ] Publish announcement on #platform-design-system and #design Slack channels

## Acceptance Criteria
- [ ] Designs in Figma have been published 
- [ ] Component is published on Storybook 
- [ ] design.va.gov has been updated 
- [ ] Staging review has been completed and 'Must' issues are resolved
- [ ] Announcement published on slack

**Comment by caw310** [comment]
Closing as all work will be tracked in the original [Experimental Design (language toggle for multilingual content)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/667#top)
