### ISSUE TITLE
Remove external link variation [Development]

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#3303]
## Description
See [parent issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3302).

Per comments below: Keep the variation in Storybook but swap the icon for the "(opens in a new tab)" text.

## Tasks
- [ ] Replace va-link external variation icon with "(opens in a new tab)"
- [ ] Update va-link and va-statement-of-truth tests as necessary

## Acceptance Criteria
- [ ] Existing in-prod uses of external va-link should not break upon update

Engineers: 
## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 2
@ataker - 
@harshil1793 -  
@it-harrison - 2
@jamigibbs - 3
@micahchiang - 2
@powellkerry -
@rmessina1010 -
@rsmithadhoc -

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3303?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc

**Comment by rsmithadhoc** [comment]
We will still need to support external links with the prop. So should we:

1. Completely remove the variation from Storybook but swap the icon for the "(opens in a new tab)" text in the component.
1. Keep the variation in Storybook but swap the icon for the "(opens in a new tab)" text.
1. Remove the variation, remove the icon, and **do not** add the text to the component. Users of the component would add that themselves.

**Comment by jamigibbs** [comment]
> 2. Keep the variation in Storybook but swap the icon for the "(opens in a new tab)" text.

@rsmithadhoc I personally think `2.` is the direction that makes sense.

Another thing to keep in mind is [USWDS has an external link variation](https://designsystem.digital.gov/components/link/) that uses an icon (which is what we modeled ours after).

**Comment by humancompanion-usds** [comment]
Yes, this is a deviation from USWDS. @rsmithadhoc [weighed in](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3224#issuecomment-2377462666) earlier so #2 should be the option we are taking. Ryan - If you could drop some a11y guidance as to why we are deviating from the USWDS (which I'm fine with but we should documenet) that would be helpful to note in this variation of link. Thanks!

**Comment by rsmithadhoc** [comment]
I added a note on the accessibility considerations [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3346), but will hold off on merging until this is ready to avoid any confusion.
