### ISSUE TITLE
(Master issue) Add disabled variation to va-button

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3305]
## Description
This will be the master ticket for work related to [Experimental Design - improvements to va-button disabled variation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2792#top)

This ticket will be used to track all the work that is needed to complete the add a disabled variation to button. . 
Design: [(link to ticket)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3306) 
Development: [(link to ticket) ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3460)
A11 review: [(link to ticket)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3307) 
Documentation: [(link to ticket)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3309) 

## Tasks
- [ ] Design: Add component to Figma or update component in Figma
- [ ] Development: Build web component and add as component to Storybook or update component and Storybook
- [ ] Accessibility review of the web component
- [ ] Update documentation site with guidance 
- [ ] Request Staging review (if needed) 
- [ ] Publish announcement on #platform-design-system and #design Slack channels

## Acceptance Criteria
- [ ] Designs in Figma have been published 
- [ ] Component is published on Storybook 
- [ ] design.va.gov has been updated 
- [ ] Staging review has been completed and 'Must' issues are resolved (if applicable)
- [ ] Announcement published on slack

**Comment by caw310** [comment]
Closing as all work related to this will be tracked through [Experimental Design - improvements to va-button disabled variation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2792#top) which is the original request.
