### ISSUE TITLE
(Master issue) Add destructive button to va-button

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3310]
## Description
This will be the master ticket for work related to [Experimental Design - Destructive Button](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2486#top)
This ticket will be used to track all the work that is needed to complete the add the destructive button.  

Design: 
Development: (if needed) 
A11 review: 
Documentation: 

## Tasks
- [ ] Design: Add component to Figma or update component in Figma
- [ ] Development: Build web component and add as component to Storybook or update component and Storybook (if needed)
- [ ] Accessibility review of the web component
- [ ] Update documentation site with guidance 
- [ ] Request Staging review (if needed) 
- [ ] Publish announcement on #platform-design-system and #design Slack channels

## Acceptance Criteria
- [ ] Designs in Figma have been published 
- [ ] Component is published on Storybook 
- [ ] design.va.gov has been updated 
- [ ] Staging review has been completed and 'Must' issues are resolved (if applicable)
- [ ] Announcement published on slack

**Comment by caw310** [comment]
Closing as all work related to this will be tracked in the original request: [Experimental Design - Destructive Button](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2486#top)

**Comment by caw310** [comment]
@humancompanion-usds I reopened this epic so to address the remaining issues.

**Comment by tbaker1026** [comment]
Have not started work on this component - closing issue until we start working on destructive button
