### ISSUE TITLE
Step 2: destructive button  - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3311]
## Description
Create design for destructive button and/or update Figma artifacts for va-button.

If this is a pattern or component that is already in existence, conduct a small-scale audit (3-5 examples) to make sure there aren't design issues that need to be addressed. Also, check the Design System Team backlog for outstanding design issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this design and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Original experimental design request: [Experimental Design - Destructive Button](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2486#top)

## Tasks
- [x] Conduct small audit if necessary (if component already exists and we are building a new version)
- [x] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [x] Create designs for component
- [ ] Review designs with PO and DST designers 
- [ ] Review designs with developers and accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility and development considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by t-michaud** [comment]
For the initial pass for color options:

### Option for Web

- Default: **vads-color-secondary** `#d83933` (AA 4.61:1 contrast)
- Hover: **vads-color-secondary-dark** `#b50909` (AA 6.98:1 contrast)
- Active: **vads-color-secondary-darkest** `#8b0a03` (AAA 9.8:1 contrast)

We could create separate naming for each, and keep the same hex values

- Default: **vads-button-color-background-destructive-on-light** `#d83933`
- Hover: **vads-button-color-background-destructive-hover-on-light** `#b50909`
- Active: **vads-button-color-background-destructive-active-on-light** `#8b0a03`

### Drawing from Mobile

The mobile doesn't have hover, so the only two colors are

- Default: **vads-color-secondary-dark** `#B50909` (AA 6.98:1 contrast)
- Active: **vads-color-feedback-surface-error-on-dark** `#5C1111` (AAA 13.52:1 contrast)

If we keep with the mobile as a basis, the color options would be:

- Default: **vads-color-secondary-dark** `#b50909` (AA 6.98:1 contrast)
- Hover: **vads-color-secondary-darkest** `#8b0a03` (AAA 9.8:1 contrast)
- Active: **vads-color-feedback-surface-error-on-dark** `#5C1111` (AAA 13.52:1 contrast)


![Image](https://github.com/user-attachments/assets/96cf604c-3602-46a1-9856-0f04f264d2b7)

**Comment by t-michaud** [comment]
Talked during the design sync this morning, and the team chose the "Optional" designs.

- This helps keep with the VADS color design tokens
- Will add in documentation about choosing the "Optional" designs. 
- This will also update the Mobile default and active colors.

**Comment by danbrady** [comment]
Reviewed, approved, merged, and published! Thanks, Thomas!
