### ISSUE TITLE
Create pattern for destructive button variant use

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3314]
## Description
original experimental design request: [Experimental Design - Destructive Button](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2486#top)

## Details
_optional, delete section if not needed_

## Tasks
- [ ] Review designs and guidance for destructive button
- [ ] Draft pattern for use of destructive button 
- [ ] Review with DST designers and PO
- [ ] Make updates as needed

## Acceptance Criteria
- [ ] Tasks above are completed
- [ ] Publish and announce pattern

**Comment by tbaker1026** [comment]
Not picking up this new component - closing issue
