### ISSUE TITLE
Guidance for international phone numbers - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3316]
## Description
Add or update documentation and guidance for text-input on design.va.gov when used for an international phone number. 

## Details
Design ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3222
Development ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2673

## Tasks
- [x] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [x] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by caw310** [comment]
Carried over due to pending review.
