### ISSUE TITLE
Footer Component - Discovery - Build Process

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3321]
## Description
One of our goals is to componentize the current footer used on va.gov and abstract it out of vets-website and content-build. In order to do this we first need to understand the build process for the footer; where it gets data from, how that data is transformed, and finally the way in which it's consumed in vets-website and content-build. Understanding this will inform us on how we might be able to build a flexible and reliable footer component that isn't prone to breaking. 

## Considerations
- [Existing documentation on footer data](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer/engineering)
- [Current va-footer application](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/va-footer/index.js)

## Tasks
- [ ] Evaluate the current va-footer application and its data pipeline
- [ ] Provide a write up that proposes how it might be translated into a web component that consumes drupal data in the same structure it currently does. Propose whether or not there's validity in providing a footer that comes pre-built with menus already hydrated

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by jamigibbs** [comment]
[Confluence document with discovery notes](https://vfs.atlassian.net/wiki/spaces/DST/pages/3541532673/Discovery+Footer+Web+Component+-+Build+Process). The team will discuss in our weekly engineering meeting.
