### ISSUE TITLE
Review + Update Designing with Figma at VA Confluence page

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3325]
## Description
The Designing with Figma at VA confluence page was last updated in December 2023. It needs to be reviewed for accuracy and updated as needed. One of the DST designers will review and make edits to the page so that other designers know how to use Figma to design applications. 

## Details
Designing with Figma at VA Confluence page: https://vfs.atlassian.net/l/cp/mjFDpGoc 

Ryan already updated the accessibility checklist image so that is done. 

## Tasks
- [ ] Review the confluence page to identify what is outdated and needs updating
- [ ] Update text or images as necessary
- [ ] Get other DST designers to review 
- [ ] Publish updates to confluence page 

## Acceptance Criteria
- [ ] Confluence page has been updated

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3325?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by caw310** [comment]
closing. will reopen if we need to do this work.
