### ISSUE TITLE
CSS Library - Swap shared-variables import

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3328]
## Description
One of the last remaining things we need to do to get off of Formation is swap the shared-variables import that all applications use. In most instances this is a one line change that updates the import path. 

There are some applications that will require variable name updates, for example: the [ask-va-too app](https://github.com/department-of-veterans-affairs/vets-website/pull/32199/files#diff-c6cb36efde1a4f37765ad11c9bf6850038aec4544faa6806da937f5f96d32a5fR165) uses a `$color-gray-lightest` that css-library doesn't have, and this instead needs to be swapped to `var(--vads-color-base-lightest)`. 

Some applications will need additional imports from css-library because `css-library/dist/tokens/variables` no longer imports mixins and functions like `formation/shared-variables` did. For example: the [caregivers](https://github.com/department-of-veterans-affairs/vets-website/pull/32199/files#diff-4af540facf6903dd84f68c6f832ece48bc5846bee593c83b6d765773c75c36f4R2) application requires `css-library/dist/stylesheets/mixins` because one or more of it's partials uses [this media mixin](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/_mixins.scss#L12). Some applications will also need to import [css-library/_functions.scss](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/_functions.scss) because they rely on the `units()` and/or `units-px()` function, such as several [profile partials](https://github.com/department-of-veterans-affairs/vets-website/blob/73e75423a6627f5f9734c7940b6b9f0f97544710/src/applications/personalization/profile/sass/hub-cards.scss#L6). 

## Considerations
- [Draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/32199) with all necessary updates for each application
- Given the breadth of this work, multiple PRs may be required, it could be worthwhile to have more than 1 engineer contribute to this. 

## Tasks
- [x] Update shared-variables import path from `~@department-of-veterans-affairs/formation/sass/shared-variables` to `~@department-of-veterans-affairs/css-library/dist/tokens/variables`
- [x] Where necessary, add an import for `~@department-of-veterans-affairs/css-library/dist/stylesheets/mixins`
- [x] Where necessary, add an import for `~@department-of-veterans-affairs/css-library/dist/stylesheets/functions`
- [x] Test locally to ensure breakpoint styles continue to work, indicating variables are being properly read from css-library

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3328?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc

**Comment by it-harrison** [comment]
This will carry-over due to the large number of PRs that needed to be created and the difficulty in getting approvals for all of them.

**Comment by it-harrison** [comment]
Vets-website has been updated and all PRs merged. An [announcement](https://dsva.slack.com/archives/C5HP4GN3F/p1730400528368119) has been made to vfs frontend devs.

**Comment by micahchiang** [comment]
woohoo! Thanks Ian!
