### ISSUE TITLE
[Design] Contributing a template or pattern guidance

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3331]
## Description

We have guidance on how to contribute a new component but not guidance on contributing a template or pattern. Contributing a template or pattern has different specifications that would be nice to create and add to the VADS. 

## Details
[Contributing a component to VADS](https://design.va.gov/about/designers/creating-components)

## Tasks
- [ ] Create guidance for contributing a template or pattern
- [ ] Figure out how you want to add that guidance to VADS.
  - Would it be on a sub nav element on design contribution?
  - Combined with Contributing a component guidance?
  - Should the guidance be added as a help section in the Figma library?
- [ ] Review with Designers and PO

## Acceptance Criteria
- [ ] Contributing a template or pattern guidance has been created
- [ ] Guidance has been added to the VADS
- [ ] All changes reviewed and approved by other Designers and PO

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3331?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by humancompanion-usds** [comment]
Fixed in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/4419
