### ISSUE TITLE
Update the Confirmation page template - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3332]
## Description
Update the form [Confirmation page template](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Design/patterns/Application%20status#confirmation-page-updates) and [pattern](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information) based on Jeana's draft.

## Details
If needed, here is a link to the Slack thread where this originates from: https://dsva.slack.com/archives/G01BJ3ESXL4/p1727971861773339

Update design for https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information

## Tasks
- [x] Update the Confirmation template designs in Figma
- [x] Review designs with PO and DST designers 
- [ ] Review designs with developers and accessibility specialist, if necessary) 
- [x] Address any comments from reviews, if necessary
- [ ] Publish the designs in Figma

## Acceptance Criteria
- [x] Component design is complete and has been reviewed
- [x] Accessibility and development considerations have been added to this ticket, if necessary
- [x] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3332?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady & @babsdenney - This is ready for review

**Comment by jeana-adhoc** [comment]
Connecting the dots on a few things here that were simultaneously happening

- I have submitted a PR to update the screenshots and text for the "[Keep a record of submitted information](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3386)"
- I have a [Figma file that is set up for teams](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=1-17&node-type=canvas&t=PUYXGX6ZgYoi4G9A-11) to customize the confirmation page template to work for them

These things should override what's currently in VADS/Figma.

I still have an open question though as to what the difference will be between these two pages
- "[Keep a record of submitted information](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information)"
- "[Confirmation page template](https://design.va.gov/templates/forms/confirmation)"

**Comment by jeana-adhoc** [comment]
@danbrady / @babsdenney / @LWWright7 -

Here's the [figma files for the updated confirmation page](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=731-31085&node-type=section&t=PUYXGX6ZgYoi4G9A-11).  Let me know if you have any questions/concerns.

**Comment by LWWright7** [comment]
https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-66786&t=3upQrBgmFj1fEuor-1

Per @jeana-adhoc  this ticket is good to close!
