### ISSUE TITLE
Update guidance for Confirmation page - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3333]
## Description
Update documentation and guidance for Confirmation page template on design.va.gov. 

## Details
Update the form [Confirmation page template](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Design/patterns/Application%20status#confirmation-page-updates) and [pattern](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information) based on Jeana's draft.

If needed, here is a link to the Slack thread where this originates from: https://dsva.slack.com/archives/G01BJ3ESXL4/p1727971861773339

Update guidance for https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information

## Tasks
- [ ] Write or update Confirmation page documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3333?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
@jeana-adhoc updated the guidance as part of #3386. The only work that remains is bringing over the Figma assets to the Pattern file.
