### ISSUE TITLE
[Design] Add form components to patterns in Figma Pattern Library

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3339]
## Description
While doing a audit of the Patterns library we discovered that all the patterns that have a component slot had the form component removed. We will need to add all the form components back to the pattern templates. 

## Details
[Pattern Library Audit](https://docs.google.com/spreadsheets/d/1_E15HKftLiuJuQw9UWyASUWDFrtbwbDpuvvAxLF9CNI/edit?usp=sharing)
[Pattern Library in Figma](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?t=RKdnFdk6gYWLeg5V-0)

## Tasks
- [ ] Go through all the pages in Figma and add the form components that are missing
- [ ] Review with DS Designers and Forms team

## Acceptance Criteria
- [ ] All patterns and forms have the missing components added back
- [ ] Reviewed by Designers

**Comment by jeana-adhoc** [comment]
@babsdenney -

I've added the components back in on the margins and annotation pages.  I'll be looking for others that might be missing.
