### ISSUE TITLE
Issue with downloading logos (PNG format)

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3342]
## Description
Need to fix the logo download. It seems to be an issue with the PNG format. 

## Details
From email with description of the issue encountered. 
Christopher (included on this email) had tried to download the VA seal and parent signature from [this page](https://design.va.gov/foundation/logos) for use in his design work, and found that some of the PNGs looked to be rendering as squares rather than the intended shapes. Example attached. If there’s a quick answer or someone you could send him to for more info, that would be great.

## Tasks
- [x] Fix the download so that the VA seal and other assets are rendering in the correct shape
- [x] If needed, fix the logo asset 
- [x] Publish the change

## Acceptance Criteria
- [ ] VA seal and other assets on the logos page are rendering correctly.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3342?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
Created new PNG files for the 4 that had issues.  Uploaded them in the same VALogos.zip file and created a pull request to review. 

@danbrady & @babsdenney This is ready for review

**Comment by LWWright7** [comment]
Emailed Chris and Danielle to let them know that the link is updated and the .png files are fixed!
