### ISSUE TITLE
Research  Card components based on the audit

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3362]
## Description
Research the existing uses of the card component to define possible card component elements and card variations. 

## Details
Ticket for audit with screenshots and other info: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2447

## Tasks
- [ ] Review screens and examples in the audit 
- [ ] Identify elements the include in cards
- [ ] Identify variations for card component
- [ ] Share recommendations with DST designers and PO
- [ ] Create design ticket with recommendations to add to card component

## Acceptance Criteria
- [ ] Findings have been shared
- [ ] Design ticket written

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3362?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7
