### ISSUE TITLE
Audit of [va-checkbox] Indeterminate State

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3365]
## Description
In [USWDS 3.8.0](https://github.com/uswds/uswds/releases/tag/v3.8.0), the checkbox has a new indeterminate state that has been proposed we add to VADS. Before development begins, Jami suggested that we do an accessibility audit of this feature. 

## Details
Development ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2652
Ticket Jami found indicating some challenges with screen readers interacting with the indeterminate state : [[Checkbox] a11y - Indeterminate checkbox state announces only as ticked or unticked rather than mixed](https://github.com/mui/material-ui/issues/20476#top)

## Tasks
- [x] Review USWDS checkbox with indeterminate state 
- [x] Review the ticket with a11y issues
- [x] Draft a recommendation for how to implement this or if we should add this component
- [x] Share findings and recommendation with DST
- [x] Make a final recommendation

## Acceptance Criteria
- [ ] Audit completed
- [ ] Reviewed findings and recommendation with DST

**Comment by caw310** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3365?planning-poker) with Zenhub @rsmithadhoc

**Comment by rsmithadhoc** [comment]
My screen reader testing went well, here's what it said for each:

- Chrome/JAWS - "partially checked"
- Safari/VoiceOver - "mixed"
- Firefox/NVDA - "checkbox half-checked"
- Edge/Narrator - "checkbox indeterminate"
- Android Chrome/TalkBalk - "partially checked"

The only one of our criteria I didn't test was iOS Safari/VoiceOver since I don't have access to an iPhone, but confident that it probably works there too. Because of that, I believe we are good to proceed with implementing this.

For implementation, `input.indeterminate = true;` must be set in JavaScript, there is no HTML attribute for this. This is what [USWDS is also doing](https://github.com/uswds/uswds/pull/5713).
```html
<input type="checkbox" id="checkbox" />
<label for="checkbox">George Washington Carver</label>
```
```js
const inputs = document.getElementsByTagName("input");

for (let i = 0; i < inputs.length; i++) {
  inputs[i].indeterminate = true;
}
```
