### ISSUE TITLE
(Master Issue) Sign-in Alert

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3384]
## Description
This will be the master ticket for work related to Experimental design requests
- #2556  
- [**New component: Sign-in widget (breaking out from general alert component)** #76785](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76785)
- #2284 
- #3105 

This ticket will be used to track all the work that is needed to complete the add Alert - Sign-in. 

- Design: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3151 
 -- Figma file: https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=13356-315
- Development: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3364
- A11 review: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3385
- Documentation: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3239#issuecomment-2383259122 

## OCTO OKR
O1.1: Improve satisfaction with our web and mobile products by 5 points.
Improving the Alerts related to sign-in should reduce confusion for users stuck in IAL 1 who need IAL 3 in order to fill out forms. We'll measure this through qualitative research efforts.

## Tasks

- [x] Design: Add component to Figma or update component in Figma
- [ ] Development: Build web component and add as component to Storybook or update component and Storybook
- [ ] Accessibility review of the web component
- [ ] Update documentation site with guidance 
- [ ] Request Staging review (if needed) 
- [ ] Publish announcement on #platform-design-system and #design Slack channels

## Acceptance Criteria
- [x] Designs in Figma have been published 
- [x] Component is published on Storybook 
- [ ] design.va.gov has been updated 
- [ ] Staging review has been completed and 'Must' issues are resolved (if applicable)
- [ ] Announcement published on slack

**Comment by humancompanion-usds** [comment]
Just did a quick look at this and we have some issues we need to resolve before we can close this:

* The link from Storybook to design.va.gov is broken (The link to alert expandable is also broken)
* None of the examples in guidance point to Storybook.

I do think we want to keep the screenshots that show the actual button for Login.gov and ID.me. But, we should still link to Storybook for those and use an iframe example for those that don't have a customized button.

**Comment by caw310** [comment]
Work on this is done!
