### ISSUE TITLE
Change base font design token and add default font design token

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3388]
## Description
Change the base font design token to root font design token. Set the root font design token 16px. 
Add a default font design token for  16.96

## Tasks
- [ ] Rename the base font design token to root font 
- [ ] Set the root font design token to 16 pixels 
- [ ] Create default font design token
- [ ] Set the default font to 16.96

## Acceptance Criteria
- [ ] Root font design token is available at 16 pixels
- [ ] Default font design token is set to 16.96 and is available for use

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3388?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7
