### ISSUE TITLE
Add default font design token

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3389]
## Description
Add a default font design token for  16.96

## Tasks
- [ ] Create default font design token
- [ ] Set the default font to 16.96

## Acceptance Criteria
- [ ] Default font design token is set to 16.96 and is available for use

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3389?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by caw310** [comment]
Closing as this work will be done in this [ticket 3388](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3388).
