### ISSUE TITLE
[Design] - Release process for Doc site

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3391]
## Description
We have been working on creating a release process to track changes coming out of the Design System. We have already finalized a process for Figma and would like to do the same for the Documentation site. 

Currently, there isn't a good way to understand what is changing the documentation site. Ideally, it would be nice if this was an automated process some how, similar to releases of the component library where all the release notes are merged into one place.

## Details
[Figma release documentation](https://docs.google.com/document/d/13LBsGqkJbtLILvET7PbUjOyxObRjPsPeHxCNxv-Mzr0/edit?usp=sharing)
[Figma release process](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=14955-5025)

## Tasks
- [ ] Research best practices for creating a release note process for the documentation site
- [ ] Look into automation options
- [ ] Create guidance and finalize a process for release notes for the VADS doc site
- [ ] Review with DST

## Acceptance Criteria
- [ ] A release process has been established for the VADS doc site

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3391?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7
