### ISSUE TITLE
(master issue) Add process status icons and repeat symbol

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3393]
## Description
This will be the master ticket for work related to [Experimental Design for process status icons and repeat symbol] (https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2801#top)

This ticket will be used to track all the work that is needed to complete the add process status icon and repeat symbol. 

Design: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3394
Development: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3395
A11 review: 
Documentation: 

## Tasks
Design: Add component to Figma or update component in Figma
- [ ] Development: Build web component and add as component to Storybook or update component and Storybook
- [ ] Accessibility review of the web component
- [ ] Update documentation site with guidance 
- [ ] Request Staging review (if needed) 
- [ ] Publish announcement on #platform-design-system and #design Slack channels

## Acceptance Criteria
- [ ] Designs in Figma have been published 
- [ ] Component is published on Storybook 
- [ ] design.va.gov has been updated 
- [ ] Staging review has been completed and 'Must' issues are resolved (if applicable)
- [ ] Announcement published on slack

**Comment by caw310** [comment]
Closing this issue as all tickets related to this work are now sub issues off of the experimental design request.
