### ISSUE TITLE
[Development] Align List styles to USWDS

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3396]
## Description
The VADS has list styles that don't align with USWDS. We want to align our simple unordered and ordered list with the USWDS.

## Details
[USWDS List](https://designsystem.digital.gov/components/list/)
[VADS List](https://design.va.gov/components/list#simple-unordered-and-ordered-lists)
[Codepen example of both together](https://codepen.io/babsdenney/full/MWNpNpr)

## Tasks
- [ ] Remove all additional styling added to the [simple unordered and ordered list](https://design.va.gov/components/list#simple-unordered-and-ordered-lists) to include
  - [ ] Unordered list
  - [ ] Ordered list
  - [ ] Definition list
- [ ] Do not make changes to the [complex lists ](https://design.va.gov/components/list#more-complex-unordered-and-ordered-lists)
- [ ] Review changes with a Designer

## Acceptance Criteria
- [ ] The list have the same styling as [USWDS list](https://design.va.gov/components/list#simple-unordered-and-ordered-lists)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3396?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by jamigibbs** [comment]
The USWDS package for list is [usa-list](https://github.com/uswds/uswds/blob/develop/packages/usa-list/src/styles/_usa-list.scss) which has the `usa-list` and `usa-list--unstyled` classes. But I don't think we want to use those classes directly.

This might be a good example/opportunity for us to try importing those types of base style modules into the CSS Library directly from [USWDS mixins](https://github.com/uswds/uswds/blob/ae7129cafeeff2089e9ccfd4b286c50e8d7d0b5f/packages/uswds-core/src/styles/mixins/typography/usa-list.scss#L20-L38). Maybe something like this works?

```css 
@import 'uswds-core/src/styles/mixins/typography/usa-list-item';


li {
  @include usa-list;

  li {
    @include usa-list-item;
  }
}
```

I think this is where our current list style is coming which is just a port of the USWDS v1 list styles from Formation:

https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/formation-overrides/elements/lists.scss#L15-L28

**Comment by caw310** [comment]
Please add your estimate of 1, 2, 3, 5, 8 or 13
@Andrew565 
@ataker 
@harshil1793 
@it-harrison 
@jamigibbs 
@micahchiang 
@powellkerry 
@rmessina1010 
@rsmithadhoc

**Comment by micahchiang** [comment]
One other thing to consider is that our list tags are getting some things from our [uswds typography settings](https://github.com/department-of-veterans-affairs/component-library/blob/f7c77a5ba23c4ef2940e7dbfe66ee8e2d2e495db/packages/css-library/src/stylesheets/uswds-typography.scss#L24-L26), so we'll want to be cognizant of any unexpected overrides or behaviour we might be introducing, if any.
