### ISSUE TITLE
Formation Deprecation - Core import swap

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3397]
## Description
The last remaining step that needs to be done in order to remove the Formation package from vets-website is to replace the import path for [core.scss](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/sass/style.scss#L5). 

This Formation stylesheet has a [counterpart](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/core.scss) in css-library that brings imports the necessary styles vets-website relies on to maintain visual parity.

We need to replace the vets-website import path from Formation to css-library, ensure we've done visual regression testing in several high traffic applications, static pages, and the injected header, and then merge a PR into vets-website for this change.  

## Considerations
- [css-library pull request](https://github.com/department-of-veterans-affairs/component-library/pull/1359) that includes necessary updates to stylesheets in order to maintain parity with what is in production.
- [vets-website pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/32154) that updates the import path and adds grid classes to shame.scss
- For now, grid classes need to continue to be maintained manually. We can either leave them in shame.scss for the time being, or bring them into css-library and import them through core. Either way, the classes need to exist as they currently do because they do not rely on `!Important`, unlike utility classes. 
- Testing needs to be done thoroughly on this ticket. Even though the lines changed are relatively small, the impact on vets-website is potentially high. Screenshots of each thing tested need to be attached to the vets-website PR listed above. 
- At a minimum we should test: Profile, MHV Secure Messaging, Combined Debt Portal, Claims Status, content-build hub pages, at least one form application
- Content-build will inherit changes locally from vets-website as long as both repos are running locally at the same time. 

## Tasks
- [ ] Local testing with verdaccio, attach screenshots for applications tested
- [ ] Merge css-library PR and publish a new version so we can spin up a review instance in vets-website
- [ ] Review instance testing in vets-website to corroborate local diff testing
- [ ] Merge vets-website pull request

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3397?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
Work has started on this but this issue will carry over into sprint 14. Next step here is manual and review instance QA in vets-website. When that begins we can open a new ticket and close this one if we want to.

**Comment by caw310** [comment]
Work continues on this so it will carry over.

**Comment by micahchiang** [comment]
Merged in 🎉 https://github.com/department-of-veterans-affairs/vets-website/pull/32154
