### ISSUE TITLE
[Documentation] - Update list component documentation

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3399]
## Description
We are aligning the VADS list styles with USWDS. See the ticket below for more information. We need to update the list documentation to reflect that. 

## Details

- [[Development] Align List styles to USWDS #3396](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3396)
- [VADS List](https://design.va.gov/components/list)
- [USWDS List](https://designsystem.digital.gov/components/list/)

## Tasks
- [ ] Write or update component documentation for design.va.gov
  - [ ] Add unstyled lists to the documentation examples
  - [ ] Remove the guidance that refers to the previous styles (square bullets)
  - [ ] Remove description list from the examples
  - [ ] Update screenshots with new examples
  - [ ] Review USWDS guidance to see if most of guidance could be referred to USWDS instead
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov
