### ISSUE TITLE
CSS Library: add the USWDS utility breakpoint theme setting for `medium-screen`

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#3400]
## Description

The [v3.9.0 release of USWDS](https://github.com/uswds/uswds/discussions/6098) includes the `$theme-utility-breakpoints-custom` setting which should be used to generate custom breakpoint utility classes. We can use this for the VA Design System's `medium-screen` breakpoint.

The `medium-screen` breakpoint is **768px**.

The [CSS Library theme settings](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/_uswds-theme.scss) should have something like the following added to it and all of the [custom medium-screen Sass](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/utilities.scss#L30-L168) code removed. 

```sass
@use "uswds-core" with (
  ...
  $theme-utility-breakpoints-custom: (
    "medium-screen": 768px
  )
);
```

## Tasks
- [ ] Update the USWDS package in css-library to v3.9.0
- [ ] Update the CSS Library USWDS theme settings to use the `$theme-utility-breakpoints-custom` setting.
- [ ] Remove the custom medium-screen utility Sass code
- [ ] Generate the new utility classes

## Acceptance Criteria
- [ ] custom utility breakpoint classes for medium-screen are generating and tested
- [ ] code has been cleaned up

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3400?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
