### ISSUE TITLE
Update USWDS to v3.9.0 in component-library

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#3401]
## Description

[USWDS has released v3.9.0](https://github.com/uswds/uswds/discussions/6098) and we should update it in the component-library. We will want to make sure that the Chromatic visual diff is working so that we can review and visual updates, changes, or regressions.

We should also review any markup changes noted in the release notes and make those updates as well.

## Tasks
- [ ] Update the `@uswds/uswds` packages in the component-library to v3.9.0
- [ ] Review the release notes for any markup or visual changes and make changes if needed.
- [ ] Review any visual changes with a designer if necessary.
- [ ] Toggle the `onlyChanged` setting in the Chromatic workflow if needed to trigger visual diffs

## Acceptance Criteria
- [ ] USWDS has been updated to v3.9.0

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3401?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
