### ISSUE TITLE
Add line length tokens to css-library

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3404]
## Description
We need to add line-length tokens to css-library. 

## Details
- [line-length tokens](https://design.va.gov/foundation/typography#typography-tokens)
- [tokens directory in css-library](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library/tokens)

## Tasks
- [ ] Add a `.json` file to the tokens directory that contains values for the line-length tokens linked to above. 
- [ ] Generate new dist stylesheets so the new tokens are generated and available for use elsewhere

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3404?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
