### ISSUE TITLE
Discovery: Research gutters for existing pages and templates

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3411]
## Description
Research and identify the current gutters for existing pages and templates as the initial step for the initiative to normalize the gutters across the site. 

## Tasks
- [ ] Do an audit to Identify the current gutters for existing pages and templates
- [ ] Document your findings and recommendations
- [ ] Make a recommendation to either allow mobile app to stay at 10px gutters and add that to our spacing units or we get them to move to 8px or 12px gutter size
- [ ] Share findings with DST PO and team members

## Acceptance Criteria
- [ ] Normalized gutter spacing has been determined

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3411?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
Outputs from research and discussion with Matt:

* We should align to current USWDS margins:
  * Margins should be 16px initially
  * Margins should be 32px at 1024px breakpoint

* We should align to current USWDS grid max-width: 1024px
