### ISSUE TITLE
Determine the gutters for existing pages, forms and templates

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3412]
## Description
Based on the discovery work on gutters of existing pages and templates, determine what the normalized gutters should be. 

## Tasks
- [ ] based on discovery, define gutters 
- [ ] present proposed gutters 
- [ ] determine if gutters should be different for different viewports 
- [ ] Define the design tokens for the new gutters
- [ ] Add to air table 

## Acceptance Criteria
- [ ] Tasks above are complete

**Comment by caw310** [comment]
Closing as this work was done in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3411
