### ISSUE TITLE
Update documentation site with gutter design tokens

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3414]
## Description
Update the documentation site with the design tokens for normalized gutter spacing.. 

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Design token for gutters is published on design.va.gov

**Comment by caw310** [comment]
Dependent on https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3803 getting done.
