### ISSUE TITLE
Create a strategy to get teams to update normalized gutter spacing

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3416]
## Description
Create a strategy of filing bugs for teams to fix issues

## Tasks
- [ ] Identify which teams are most affected 
- [ ] Draft instructions on making updates (if needed) 
- [ ] Define a strategy for how to get teams to make the update 
- [ ] Review with DST PO and team

## Acceptance Criteria
- [ ] Strategy has been approved
