### ISSUE TITLE
[Design] Update phone pattern in Figma to include international phone numbers

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3442]
## Description
We have added an option for international phone numbers to the VADS and need to update the Figma file to include an international phone number variation. 

## Details

- [Patterns library in Figma - Phone number](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-9602)
- [VADS phone number documentation](https://design.va.gov/patterns/ask-users-for/phone-numbers#labels-error-messages-and-hint-text)

## Tasks
- [ ] Use the [international phone number labels and error messages](https://design.va.gov/patterns/ask-users-for/phone-numbers#labels-error-messages-and-hint-text) to create a new Figma variation

## Acceptance Criteria
- [ ] There is a new Figma variation for international phone numbers
- [ ] All changes approved by VADS Designers

**Comment by caw310** [comment]
Closing as the DS + F team are working on a new international phone number component now.
