### ISSUE TITLE
[Design] Remove word 'Home' from phone pattern in Figma and documentation

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3443]
## Description
This [spreadsheet with the text labels and errors](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/src/_data/content/patterns/ask-users-for/phone-numbers.csv) has a note (scroll to the right) that the word 'Home' has been removed from the text label for phone numbers. We need to update Figma and the VADS documentation to reflect that. 

Remove references to the word 'Home' in the phone number pattern in the VADS documentation and Figma library. 

## Details
- [Spreadsheet with phone number text labels and notes](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/src/_data/content/patterns/ask-users-for/phone-numbers.csv)
- [Phone number pattern VADS documentation ](https://design.va.gov/patterns/ask-users-for/phone-numbers#us-phone-numbers)
- [Phone number pattern in Figma](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-9602)

## Tasks
- [ ] Update the [Figma patterns library](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-9602) to remove the word from the phone number pattern
- [ ] Update the [phone number pattern documentation](https://design.va.gov/patterns/ask-users-for/phone-numbers#us-phone-numbers) with a new screenshot

## Acceptance Criteria
- [ ] Designs are reviewed and approved by VADS Designers

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3443?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7
