### ISSUE TITLE
Refactor the GitHub preview and deploy workflows to use a reusable workflow

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#3450]
## Description

On the documentation site (design.va.gov), we have two Github workflows [deploy.yml](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/.github/workflows/deploy.yml) and [preview.yml](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/.github/workflows/preview.yml) that are very similar. We would like to [create a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) so that we are not duplicating so many steps between them.

Some of this work was attempted in the [preview environment PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3435) but we decided to keep this as a separate task for now because of time contraints.

related issue:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/802

## Tasks
- [ ] Refactor the GitHub action for deployment to [create a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow)
    - [ ] Remove dev-design.va.gov from the environment matrix
    - [ ] Update existing deploy and preview workflows to use new reusable workflow for staging & production environments
- [ ] Test to make sure preview environments are still working on PRs
- [ ] Test to make sure production is deploying correctly

## Acceptance Criteria
- [ ] The deploy and preview workflows can both use a reusable github workflow.
