### ISSUE TITLE
Add loading disabled button variation - development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3460]
## Description
The disabled variation to va-button needs to be update.
- Only the Loading button for disabled variation.
- Icon should be standardized so it will not be changeable. 
- Loading should be default text. 

## Details
Link to Figma: https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=15460-5337&t=lqYqIx2f8QOr613j-1

## Considerations
- Accessibility: needs to announce statuses for loading and loading complete
- Consider a media query for reduce motion
- use autorenew icon

## Tasks
- [ ] Update va-button variation to only be used as Loading button 
- [ ] Make the loading text the default but allow for changes
- [ ] Use the loading icon and make it not changeable
- [ ] Review update with a designer to get feedback
- [ ] Publish the change

## Acceptance Criteria
- [ ] va-button disabled variation is the loading variation only

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 3
@ataker - 3
@harshil1793 -  3
@it-harrison - 3
@jamigibbs - 3
@micahchiang - 3
@powellkerry - 3
@rmessina1010 -
@rsmithadhoc - 3

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3460?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
Use the va-icon called "Autorenew", will need to animate it spinning with CSS. DO NOT USE "LOOP" ICON.
