### ISSUE TITLE
Add example to va-alert with primary action link - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3463]
## Description
This work originates from [Experimental Design [Alert with Secondary Link CTA]](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3340#top) and encompasses adding an example in Figma of an Alert using a primary action link (2nd screenshot).

This task is to add to the example library in Figma.

## Tasks
- [ ] Update va-alert component in Figma with an example using a primary action link
- [ ] Review with a DST designer 
- [ ] If needed, make updates
- [ ] Publish the change 

## Acceptance Criteria
- [ ] va-alert component has an example with a primary action link

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3463?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady / @babsdenney - This ticket is available for review [here](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=35-145&t=dB1HEM1lycBhjuA7-1).

**Comment by danbrady** [comment]
LGTM!

**Comment by babsdenney** [comment]
Same! Looks good!
