### ISSUE TITLE
[Design] Create tutorial video to preview doc site changes

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3466]
## Description
We added an option to preview doc sites changes before publishing changes. To benefit the most from this feature you will need to make changes locally because github doesn't allow you to bundle changes on the github website. The easiest way to do this is using github desktop and visual studio code to make changes. It would be helpful to create some instructions so that other Designers can benefit from the feature and hopefully make it easier to contribute to the VADS doc site. 

## Details
#3435 

## Tasks
- [ ] Create a video to demo the changes
- [ ] Create instruction documentation

## Acceptance Criteria
- [ ] Review with DST Designers

**Comment by caw310** [comment]
Instead of adding this as unplanned work, this is being put in a future sprint due to designer availability.

**Comment by LWWright7** [comment]
FYI, here is the link to the video for anyone looking for it: https://www.youtube.com/watch?v=kXwhzUg1lKA
