### ISSUE TITLE
Update alert on multiple response review page

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/vets-design-system-documentation#3471]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
The yellow warning alert that appears on the review page for the [multiple response] (https://design.va.gov/patterns/ask-users-for/multiple-responses) component is adding confusion to users when they have meet their maximum allow entries.  

## Details
[Finding # 6](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/10-7959a/research/user-research/2024-09-10-7959a-champva-claims-research-report%20report.md#finding-6-after-adding-the-correct-maximum-number-of-insurance-policies-allowed-on-the-form-participants-hesitated-to-move-forward-when-shown-the-alert-box-on-the-insurance-policy-review-page) on the CHAMPVA Claims research report has some further info. 

## Tasks
- [ ] Consider reformatting this alert to a blue info alert so it's informs the user rather than appearing that they did something wrong them. 

## Acceptance Criteria
- [ ] Update the component in the VADS and forms library

**Comment by jamiefiore** [comment]
@IMHieuVo @LoisLewisUSDS Just tagging you in on this so you can keep track of it.

**Comment by caw310** [comment]
@tbaker1026 @jeana-adhoc , I believe this is a Forms issue.
