### ISSUE TITLE
[Development] Left-align content inside alerts

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3473]
## Description
A designer submitted an issue with the alert alignment. On large screens the alerts center vs. staying left aligned. We need to left-align the alerts so the alerts are the same as USWDS. 

## Details

- [See main issue ticket for more details](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3419)
- [USWDS Alerts](https://designsystem.digital.gov/components/alert/)
- [VADS Alert](https://design.va.gov/components/alert/)

## Tasks
- [ ] Update alerts so that the alert content is left aligned vs. centered. See [USWDS for example](https://designsystem.digital.gov/components/alert/).
- [ ] Verify changes with DST Designers 

## Acceptance Criteria
- [ ] All alert variations have content aligned to the left on all breakpoints

**Comment by caw310** [comment]
Closing as this is fixed.
