### ISSUE TITLE
[Design] Left align alert content in Figma component

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3474]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Details
_optional, delete section if not needed_

## Tasks
- [ ] Left align all alerts in the Figma components. See [USWDS for alert examples](https://designsystem.digital.gov/components/alert/).
- [ ] Get approval from DST Designers

## Acceptance Criteria
- [ ] Changes approved by DST Designers

**Comment by danbrady** [comment]
In the USWDS 3.8.0, it appears when an alert is very wide the content still aligns with the body copy: 

Screenshot from 1440px browser: 
![Image](https://github.com/user-attachments/assets/2a7f9829-c6de-465a-b334-298b4cec99bf)

Also see #3545

**Comment by babsdenney** [comment]
https://vfs.atlassian.net/wiki/spaces/DST/pages/2699886742/Design+Weekly+Chat+Meeting+Notes#Agenda-%2B-Discussion.5

**Comment by caw310** [comment]
@babsdenney @danbrady is this fixed now?

**Comment by danbrady** [comment]
@caw310 Reviewing [the discussion](https://vfs.atlassian.net/wiki/spaces/DST/pages/2699886742/Design+Weekly+Chat+Meeting+Notes#%5Bdate%5D.14) we had, it's not clear to me if any action was taken. So I think this will still need some investigation first.

**Comment by caw310** [comment]
Figuring out if we need full width prop on alert. Coordinating with engineering.
