### ISSUE TITLE
Y

### ISSUE THREAD

**Issue by Soltan777** [department-of-veterans-affairs/vets-design-system-documentation#3479]
> [](url) 

 _Originally posted by @Soltan777 in [#3477](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3477#issuecomment-2452036206)_

---
## Configuring this issue
- [x] Add issue to appropriate epic
- [x] Add component label (such as `va-alert`), if applicable
- [x] Add `component-new` or `component-update` label, if applicable
- [x] Complete sections below
- [ ] Delete this section once complete
## Details
_optional, delete section if not needed_

## Tasks
- [ ] 

## Acceptance Criteria
- [ ]
