### ISSUE TITLE
Upgrade component-library to use node 20

### ISSUE THREAD

**Issue by ataker** [department-of-veterans-affairs/vets-design-system-documentation#3484]
## Description
Upgrade node version to 20

## Details
[This PR](https://github.com/department-of-veterans-affairs/component-library/pull/1385) introduced unused unit tests. These tests couldn't be used because our current version of node, 18, does not support the type `File` natively.

If node 20 can't be upgraded to, please add a polyfill to support `File` in the tests in `va-file-input-multiple.spec.todo.ts`.

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 5
@ataker - 5
@harshil1793 -  
@it-harrison - 5
@jamigibbs - 5
@micahchiang -
@powellkerry - 8
@rmessina1010 -
@rsmithadhoc - 5
 

## Tasks
- [ ] Upgrade node in component-library to 20
- [ ] If that's not possible, add polyfill to test file

## Acceptance Criteria
- [ ] The type `File` isn't causing tests in `va-file-input-multiple.spec.todo.ts` to fail

**Comment by ataker** [comment]
In a test run through upgrading to node 20, the only issue I ran into was in `packages/react-components/scripts/build.js`, line 18
`return new Buffer(`
needed to be updated to 
`return Buffer.from(`
as calling `new Buffer` has [been deprecated](https://nodejs.org/docs/latest-v14.x/api/buffer.html#buffer_new_buffer_array)

**Comment by ataker** [comment]
[PR](https://github.com/department-of-veterans-affairs/component-library/pull/1154/files) from the last time node was upgraded
