### ISSUE TITLE
Update Address Pattern for Users Without Mailing Addresses

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#3496]
## Description

Update guidance to include information for users that may not have stable housing and need to provide address information.

## Details

Based on research from the IVC team on the CHAMPVA program ([as mentioned in this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67576#issuecomment-2458324937)), we need to update the Address pattern to include an Additional Information component with details about using General Delivery and the National Call Center.

## Estimating
Designers: 
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@babsdenney 
@danbrady 
@LWWright7 - 3

## Tasks
- [ ] Update "Ask Users for... Address" in Figma Patterns Library and Form Builder components
- [ ] Update "Address" Pattern on doc site with example image and any necessary content
- [ ] Analyze "Housing Status" pattern to determine if updates are needed.
- [ ] Update "Housing Status" pattern in Figma and doc site, as necessary

## Acceptance Criteria
- [ ] Address pattern updated to include Additional information component in Figma Patterns library
- [ ] Address pattern on doc site updated to include example and content updates
- [ ] Housing Status pattern was analyzed for updates and Figma/Documentation updated, as necessary

**Comment by caw310** [comment]
Moving this to another sprint as other unplanned work has come up as a higher priority.

**Comment by danbrady** [comment]
@jamiefiore from the CHAMPVA team let me know that this content has not gone through the collabcycle and is not currently in use. Additionally, the team is not ready to mail packets via General Delivery at this time. We'll need to revisit this after further development...
