### ISSUE TITLE
[Design] Make updates to the Pattern Library (part 1)

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3499]
## Description
We have taken over ownerships of the Patterns, Templates and Forms library and need to do some final clean up to make it ready for the public. We have done some clean up but there are some final issues to resolve. 

## Details
[Patterns library - Figma](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=12851-100756&node-type=section&t=VPZQo8l7OiVfSHXg-0)

## Estimating
Designers: 
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@babsdenney 
@danbrady 
@LWWright7 

## Tasks
- [ ] Do a final review of issues
- [ ] Fix anything that would prevent public release of the patterns library
- [ ] Add [email templates to the pattern](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3055#issuecomment-2399765551)

## Acceptance Criteria
- [ ] Pattern library is ready to be released for public use

**Comment by LWWright7** [comment]
Pages that are not complete:

1. [email](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2607-31365&t=fr8C247NTM9OqN8s-1) - Jeana recently created a new email form.  Does it need to be updated?
2. [ask users for address](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2987-36363&t=fr8C247NTM9OqN8s-1) there but the annotations are off
3. [ask users for contact preferences](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-18553&t=fr8C247NTM9OqN8s-1)
4. [ask users for dates](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2987-30876&t=fr8C247NTM9OqN8s-1)
5. [ask users for email address](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2987-39070&t=fr8C247NTM9OqN8s-1)
6. [ask users for files](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-63596&t=fr8C247NTM9OqN8s-1)
7. [ask users for housing status](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=8905-15293&t=fr8C247NTM9OqN8s-1) - just needs annotations
8. [list and loop](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=5751-10777&t=fr8C247NTM9OqN8s-1)
9. [ask users for multiple responses](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-63598&t=fr8C247NTM9OqN8s-1)
10. [ask users for relationship to veteran](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-17640&t=fr8C247NTM9OqN8s-1)
11. [ask users for identification information](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2988-23560&t=fr8C247NTM9OqN8s-1)
12. [ask users for gender](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=4808-19469&t=fr8C247NTM9OqN8s-1)
13. ask for pronouns? (keep?)
14. ask for race, ethnicity, origin? (keep?)
15. [help users to check eligibility](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=5600-63720&t=fr8C247NTM9OqN8s-1)
16. [help users to check personal information](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=5600-63721&t=fr8C247NTM9OqN8s-1)
17. [help users to know how their information is updated](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=5600-63727&t=fr8C247NTM9OqN8s-1)
18. [help users to navigate a long list](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=5600-63727&t=fr8C247NTM9OqN8s-1)
19. [help users to navigate benefits applications](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=5600-63728&t=fr8C247NTM9OqN8s-1)
20. [help users to recover from errors](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=5600-63724&t=fr8C247NTM9OqN8s-1)
21. [help users to sign in](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=12776-124619&t=fr8C247NTM9OqN8s-1)
