### ISSUE TITLE
[Design][Discovery] Update the Wiki for contributing to the doc site

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3518]
## Description
We have this [wiki ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/wiki)linked on the '[Updating this site](https://design.va.gov/about/updating-this-site)' page that is out-of-date. It would be great to get this wiki up-to-date and have it become a source for information on contributing to the doc site. 

This ticket will probably be a little bit of discovery work and maintenance work to update it and also determine the next steps to make this wiki more helpful to people contributing to the doc site. 

## Details
[Updating this site](https://design.va.gov/about/updating-this-site)
[Contributing to the site wiki](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/wiki)

## Tasks
- [ ] Update the wiki to add, remove, and update any information that is relevant to contributing to the doc site
- [ ] Consider what else can be added to the wiki to improve the understanding of contributing to the doc site
- [ ] Reach out to other people within VA that might contribute to the doc site to figure out what might be useful to them on the wiki
- [ ] Write up any tickets for future work needed

## Acceptance Criteria
- [ ] Reviewed by PO, PM, and DST Designers
