### ISSUE TITLE
Update Figma components based on USWDS 3.9.0 update

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#3524]
## Description

[Updating VADS to USWDS 3.9.0](https://github.com/department-of-veterans-affairs/component-library/pull/1397) introduced some minor visual changes to a several components (all variations): 

- alert
- banner
- pagination
- prefill alert

View [Chromatic UI Tests build 1760](https://www.chromatic.com/test?appId=65a6e2ed2314f7b8f98609d8&id=67350d9d05bb5dc56486fe26) for visual diffs. 

## Tasks
- [x] Designer should use devtools to inspect the web component for actual values.
- [x]  Update the figma components identified
- [ ] Publish the figma component updates

## Acceptance Criteria
- [ ] In a new Figma file, place instances of all components identified onto the canvas. 
- [ ] Validate this file has the latest version of the component library.
- [ ] Inspect those component instances to validate they match the web components

**Comment by LWWright7** [comment]
Updated the spacing on the alert / banner / prefill alert but noting that it uses an odd spacing (not based on 8) of 20.   Since the autolayout already has 8px of padding I added another 12 to the left side of the container to make the padding match the 20 of USWDS
![Image](https://github.com/user-attachments/assets/e3b13b12-6b3b-4926-84d7-fac40837f699)

**Comment by danbrady** [comment]
Hey @LWWright7, I finally got around to checking this out. This is what I noticed:

## Alert
 - In slim the close button overlaps the text. That may not be from this update, but let's fix it up if we're going to publish:
![Image](https://github.com/user-attachments/assets/29583369-6670-4a8b-872d-040aaa6e45ff)
 - Can we straighten up the variations? There's some odd white space and staggering going on:
   <img src="https://github.com/user-attachments/assets/2b7d7355-7268-47a4-8e18-212a48f6cad0" width=256>

 - I see older Alert release notes on the component page but not in the change log. Were they ever published?
 - Missing release notes for this ticket. "Update designs to match USWDS 3.9.0" is good enough.


## Pagination
 - Next and previous links are missing underlines
 - Missing release notes for this as well. (Please do that for any components updated that will need to be published.)
 - I see a lot of variations for mobile, but I'm not sure those should be published? @babsdenney do you know?

Thanks all!

**Comment by LWWright7** [comment]
@danbrady @babsdenney The suggested updates in Figma and from the comments above have been made and this is ready to be reviewed again.

**Comment by danbrady** [comment]
@LWWright7 Are we able to fix the overlapping close button in Alerts?
![Image](https://github.com/user-attachments/assets/e4fe0054-0ecb-445d-9802-9700bf3a8498)


In pagination it looks like the default and active pages are positioned differently:
![Image](https://github.com/user-attachments/assets/08d1ee1c-e26d-452a-a355-9223564bc51c)

Thanks!

**Comment by danbrady** [comment]
@LWWright7 Pagination looks good now. Do we know the status of the mobile variations though? They are not currently published, but I'm not sure if they should be? I know we were working with USWDS a bit on them. @babsdenney, do you know the status of these?  (I don't want them to get accidentally published if they're not ready.)

Regarding the toggleable close button, how do we handle it in the normal (non-slim) Alert? We can probably do it the same way, right?

**Comment by LWWright7** [comment]
@danbrady Good point about the mobile pagination.  @babsdenney Please let me know if these mobile versions should be published. 

@danbrady - I think I got the slim closable version figured out!! :) It took some finagling but it should be working as intended now!

**Comment by LWWright7** [comment]
This ticket is carrying over because of some issues with the pagination component that were not sorted out and approved before the end of the sprint. 

Alert has been updated and published.
