### ISSUE TITLE
[Design] Make updates to the Pattern Library (part 2)

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3527]
## Description
We have taken over ownership of the Patterns, Templates and Forms library and need to do some final clean up to make it ready for the public. We have done some clean up but there are some final issues to resolve.

## Details
[Patterns library - Figma](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=12851-100756&node-type=section&t=VPZQo8l7OiVfSHXg-0)

## Estimating
Designers: 
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@babsdenney 
@danbrady 
@LWWright7 

## Tasks
- [ ] Do a final review of issues
- [ ] Fix anything that would prevent public release of the patterns library
- [ ] Publish library for public use

## Acceptance Criteria
- [ ] Patten library is read to be release for public use
