### ISSUE TITLE
Add `va-language-toggle` to `ds-v3-playground` for Analytics testing

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/vets-design-system-documentation#3532]
## Description
Analytics wants to test new web components that fire analytics events in dev/staging. The va-language-toggle fires an event so we need to prepare vets-website to make the testing possible.

## Details
_optional, delete section if not needed_

## Tasks
- [ ] if the `va-language-toggle` has not already been included as part of a `component-library` release, then cut a new release with it
- [ ] update the [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js) file in `vets-website'.
- [ ] bump version of `component-library` in `vets-website` if necessary
- [ ] push a PR with the `va-language-toggle` included in the `ds-v3-playground` app.
- [ ] notify #platform-analytics

## Acceptance Criteria
- [ ] va-language-toggle is included in the playground and analytics can test the component
