### ISSUE TITLE
Discovery: Promoting yarn workspaces

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3543]
## Description
An issue recently arose with the claims status team, where they had a need to roll back to the older v1 version of file input. Instead of adding v1 component code back to component library, we decided to leverage the use of yarn workspaces in vets-website by pinning the claims status tool to an older version of the package. 

This solution was enabled by the work Brooks' did a while back to allow an application to opt out of global components and styles, combined with the work Ray did to implement yarn workspaces in vets-website in the first place.

There are several compelling benefits of promoting the use of yarn workspaces: 
1. Our team would be off the hook for working in vfs app team code
2. App teams could control when they update their own dependencies and have a little more security in ensuring their applications function properly
3. Not all apps need every single web component. Where the global entry loads every single component, an app team could potentially just import the ones they need, theoretically reducing the bundle size of their application.

There are several drawbacks we should consider with yarn workspaces: 
1. Allowing teams to control the version they're on could potentially lead to a lack of consistency on VA.gov
2. Teams could choose to never update their dependency at all

## Considerations
Getting yarn workspaces to properly work requires these steps: 
1. Add an application specific package.json [like this one](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/package.json) that includes component library as a dependency, with a specified version.
2. Importing the web components locally [like this](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/claims-status-entry.jsx#L1-L5) and then defining them [like this](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/claims-status-entry.jsx#L14-L16). Claims status loads all of them, but components should be able to only load as needed, like in [this pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/22667/files#diff-2d15727208da5a1529aff2690f7f1a64f82360bf6ba8e973f6d519fa3aa2b237R4)
3. Add the app to the global package.json [packages array](https://github.com/department-of-veterans-affairs/vets-website/blob/main/package.json#L400)
4. Add an entry for that application's component-library dependency to the [nohoist array](https://github.com/department-of-veterans-affairs/vets-website/blob/main/package.json#L405)
5. Update the app's registry entry in content-build with `useLocalStylesAndComponents` [like this](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json#L357).

## Tasks
- [ ] Pick 2 applications in vets-website. Run a bundle analysis to determine bundle size. 
- [ ] Then, follow the process above to use yarn workspaces, and only import the web components needed, instead of all of them.
- [ ] Rerun the bundle analysis to determine if there's any noticeable reduction size. 

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 5
@ataker - 5
@harshil1793 - 5
@it-harrison - 5
@jamigibbs - 5
@micahchiang -
@powellkerry - 5
@rmessina1010 -
@rsmithadhoc - 5

**Comment by ataker** [comment]
[Testing yarn workspaces doc](https://vfs.atlassian.net/wiki/spaces/DST/pages/3891003415/Testing+yarn+workspaces)
