### ISSUE TITLE
[Design] Deprecate wiki for contributing to the site

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#3561]
## Description
We have this [wiki](https://design.va.gov/about/updating-this-site) for contributing to the VADS. It has some good info in it but it is out-of-date and might be too high level for the type of contributions that we would like.

## To do
Deprecate the wiki and add the helpful or useful content to the VADS directly.
@humancompanion-usds  gets questions about which template to use for contributing. We have templates for different parts of the VADS that people can use. We need to make that more apparent.

## Tasks
- [ ] Review the wiki and figure out what to bring over to the VADS
- [ ] Review the [Updating this site](https://design.va.gov/about/updating-this-site) page to make sure it is still helpful and relavent
- [ ] Add the content to the VADS either with a new page or a existing page
- [ ] Deprecate the wiki so it is no longer referenced on VADS

## Acceptance Criteria
- [ ] Changes have been review with DST
- [ ] PR is approved with changes to the VADS

**Comment by humancompanion-usds** [comment]
Wiki is deprecated and documentation guide added.
