### ISSUE TITLE
va-table not going full width of the container when there is minimal data

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#3563]
## Description

When there is a lot of information in the table, `va-table` will automatically go the full width of its containing element. For example:

![Image](https://github.com/user-attachments/assets/0e29c581-86d3-4fb0-a97e-e396d7394f24)

But when there isn't a lot of data in the table, the width gets truncated and there does not seem to be a way to manipulate that with CSS from outside of the web component:

![Image](https://github.com/user-attachments/assets/cff8fad0-a4af-4540-8a12-774dd1951dc7)

[original slack discussion](https://dsva.slack.com/archives/C5HP4GN3F/p1733254701304129)

## Details

It looks like this is default style from what the [USWDS table module](https://designsystem.digital.gov/components/table/) provides so it's possible this is intentional. We should discuss with the designers to confirm.

Otherwise, we probably just need to add some `flex` styling to the [va-table-inner markup](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx#L316-L317) like this:

```css
:host > div {
  display: flex;
}

:host > div table {
  flex: auto;
}
```

## Tasks
- [x] **Discuss with the DS designers** if we would like va-table to be full width in all data scenarios.
  - [ ] If the answer is yes, then update va-table to always adjust to the width of the parent container
  - [ ] If no, create a follow-up ticket to update the va-table documentation to specify width behavior for minimal data scenarios

## Acceptance Criteria
- [x] a decision has been made about the width auto-adjusting when it does not have a lot of content
- [ ] the follow-up task is completed depending on that decision

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 3
@ataker - 3
@harshil1793 -  3
@it-harrison - 3
@jamigibbs - 2
@micahchiang - 2
@powellkerry - 2
@rmessina1010 -
@rsmithadhoc - 2

**Comment by Andrew565** [comment]
Decision was made to make "full-width mode" an optional prop, rather than defaulting all tables to full-width.
