### ISSUE TITLE
Update Card component default gray   - documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3571]
## Description
Update the documentation Card default gray examples on https://design.va.gov/components/card. Change the text in the example to "Example card content" 

## Details
Figma: https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=1917-7471&node-type=canvas&t=9UeotyvWE7Acar47-0
Storybook: https://design.va.gov/storybook/?path=/story/components-va-card--with-background

## Tasks
- [ ] Update the va-card default gray example 
- [ ] Get DST designer to review
- [ ] Publish change

## Acceptance Criteria
- [ ] va-card documentation default example has "Example card content" with the gray background.

**Comment by caw310** [comment]
This is fixed so closing
