### ISSUE TITLE
Update platform utilities for node 22 compatibility

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/vets-design-system-documentation#3576]
## Description
Update `vets-website` utilities in `src/platform` to work with `node 22`

## Details
Some utilities are broken as a result of api changes from `node 14` to `node 22`. These must be updated alongside `node`.

## Tasks
- [ ] audit test output to look for tests that fail and see if they do so because of problems in platform-wide utilities and fix the broken utilities
- [ ] do a broader audit to check for utilities that may be broken but which were not affecting test output and fix anything found

## Acceptance Criteria
- [ ] utilities have been updated and tests don't fail as a result of utilities that are not compatible with `node 22`.

**Comment by caw310** [comment]
Will carry over until issues are resolved

**Comment by micahchiang** [comment]
Adding a link to https://github.com/department-of-veterans-affairs/va.gov-team/issues/96272 for better tracking from platform.
