### ISSUE TITLE
Get `yarn test:unit` to complete without hanging

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/vets-design-system-documentation#3577]
## Description
Get `yarn test:unit` to complete without hanging on `vets-website`  using  `node 22`

## Details
This PR attempt to fix  the  issue with the suit and individual app unit tests failing to complete. 
More specifically,  claims-status, which at the time of writting is the  only test  that does not complete.

## Tasks
- [ ] identify cause of hanging test
- [ ] confirm at all apps test can run  in sequence an individually
- [ ] confirm  PR  can run build successfully

## Acceptance Criteria
- [ ] Any and all test can be run to completion (tests  do not need to pass, simply complete. without hanging).

**Comment by rmessina1010** [comment]
updating  msw on vet-website  solved this issue. Closing.
