### ISSUE TITLE
Download link guidance update - documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3579]
## Description
During DSC meeting discussing this experimental design request, it came up that documenation on download link needs updating. Look into the behavior of the download link and add guidance on the behavior. 

## Tasks
- [ ] Review how download link works and review documentation
- [ ] Update guidance to reflect how download link should behave
- [ ] Have DST designer review 
- [ ] Publish update

## Acceptance Criteria
- [ ] Guidance on download link behavior has been updated,

**Comment by babsdenney** [comment]
We discussed this and determined that we need to verify if this download link should be a link or a button and this should go through an accessibility review first. Depending on if it is a link or button will dictate the design. 

[See the design chat notes for more information](https://vfs.atlassian.net/wiki/spaces/DST/pages/2699886742/Design+Weekly+Chat+Meeting+Notes)

**Comment by caw310** [comment]
@rsmithadhoc reassigning to you now.

**Comment by rsmithadhoc** [comment]
I updated the docs in [this PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3744). A download should use a link because it's a navigational action to access that separate file. 

W3C also provides a `download` attribute for links, but not buttons. So I think that also suggests links should be used for downloads.
    - However, I don't believe we need to add that to the component at this time. When testing this, I didn't see any difference in behavior or how screen readers announced the link.

**Comment by danbrady** [comment]
From a general experience standpoint, if it's a "download" link, then I'm thinking it *should* prompt the user with the browser download dialog (by using that `download` attribute). (Or at least have a prop to toggle this attribute.)

Thoughts, @humancompanion-usds?

**Comment by rsmithadhoc** [comment]
We can definitely add it, but I didn't see any difference with that attribute. I'll close this one out, but can open another ticket if we decide to add that to the component. Thanks!
