### ISSUE TITLE
Remove remaining references to Formation from vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3580]
## Description
Formation has officially been removed from vets-website in [this pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/32154), however there are still some remaining references to it in vets-website, mostly around event listeners being named using a formation path to fire analytics events. These should either be removed or updated since formation is no longer in use. 

## Considerations
A global search in vets-website for `@department-of-veterans-affairs/formation` shows that some pieces of code still use paths to formation for event types: 
![Image](https://github.com/user-attachments/assets/f641982e-48f5-4aa5-a918-51443b5afa9b)

Most of these are just used to fire analytics events and are several years old at this point. These listeners should either be removed or the types should be renamed. The one instance in `/platform/site-wide/legacy-components-js` is using a formation path with `initEvent`, a method that was deprecated a while ago. 

## Tasks
- [x] Determine if the analytics events found above are still in use. If not, remove them, if they are, then rename the type
- [ ] Determine if the event created in `initEvent` is still in use. If not, remove it, if it is, then rename it to remove formation
- [x] Remove the formation documentation from the readme file in the screenshot above

## Acceptance Criteria
- [ ] Above tasks have been completed

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 5
@ataker - 3
@harshil1793 -  5
@it-harrison - 5
@jamigibbs -
@micahchiang -
@powellkerry - 5
@rmessina1010 -
@rsmithadhoc - 5
