### ISSUE TITLE
Process List with status in eyebrow   - Accessibility review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3600]
## Issue Description
We need to conduct a full accessibility review of the Process List with status in eyebrow component. The component can be viewed in Storybook here: https://design.va.gov/storybook/?path=/story/uswds-va-process-list--custom-status-text
Figma: https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=798-1778&node-type=canvas&t=QpDPBcTxjmQhUfpr-0

## Tasks
- [x] Full accessibility review of the component is completed
- [x] Add descriptions of any issues found to this ticket
    - [x] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [x] If necessary, discuss any accessibility issues found with the engineer who developed the component
- [x] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [x] Component has been reviewed for accessibility issues
- [x] Any accessibility issues have been addressed or ticket has been written with issues that need to be fixed

**Comment by rsmithadhoc** [comment]
This looked good in testing, no follow up issues created.
