### ISSUE TITLE
[Design] Update search input with clear search variation.

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3608]
## Description

Update the search input in Figma to include the button that has the clear search button. We have an issue to move the search input to text field and build a custom button component so the button might change a bit from the current browser clear search button. 

## Details

- [Search input in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=3895-86985)
- [Slack message](https://dsva.slack.com/archives/C01DBGX4P45/p1733441915141889) with more context about this issue

## Tasks

- [ ] Update designs for component in Figma
- [ ] Review designs with PO and/or other DST designers

## Acceptance Criteria

- [ ] Designs reviewed by DST Design team

**Comment by babsdenney** [comment]
@danbrady @LWWright7 This is ready for review. 

[Figma link](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=3895-86985)

**Comment by LWWright7** [comment]
This looks great Barb! I only saw one small thing.  When I turned the toggle on for the focus ring, it didn't highlight the entire search bar, it looks like it stops right where the white box ends (see screen shot below).  I put the example below the publishing notes for you to take a look. 

<img width="646" alt="Image" src="https://github.com/user-attachments/assets/5e10a962-1c68-4b99-9363-223feefd650f" />
