### ISSUE TITLE
Update or swap imports for the documentation repo

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3621]
## Description
Now that we are done with formation deprecation, we need to update packages to make sure our style imports are coming from css-library. 

## Considerations
- We'll need to update [this css-library import](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/package.json#L41)
- The doc site still relies heavily on v1 grid, which we patched directly in vets-website. We'll need to migrate grid first before fully removing formation from the doc site. 
- There's extensive use of scss variables in `/assets/stylesheets/` throughout many stylesheets. It's possible there are some being used in here that we don't carry in css-library, such as `$font-bold` and `$font-sans` in the `_do-dont.scss` stylesheet. Instances like this will need to be updated to whatever their equivalents are from the variables we do generate. Running a `yarn watch` will likely throw variable errors for these once import paths are updated. 

## Tasks
- [ ] Update [these stylesheet imports to point to css-library](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/src/assets/stylesheets/application.scss#L6-L12). It's possible imports from css-library will need to include mixins, functions, and utilities.
- [ ] Update the css-library version in package.json

## Acceptance Criteria
- [ ] Import paths have been updated for the doc site so they point to css-library

**Comment by powellkerry** [comment]
There is a reference to an example of how to import base css styles in `src/_foundation/spacing-units.md`, it was temporarily removed when documentation was updated to remove mention of formation. This should be re-added as part of this work as the code in the example should reflect css-library imports.

**Comment by caw310** [comment]
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 
@ataker - 
@harshil1793 -  
@it-harrison -
@jamigibbs -
@micahchiang -
@powellkerry -
@rmessina1010 -
@rsmithadhoc -

**Comment by powellkerry** [comment]
I did a bit of work trying to see if I could quickly switch this out for testing out changes to list styles. See this [branch](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/tree/3621-replace-formation).

**Comment by powellkerry** [comment]
This PR should be merged after this work is complete: https://github.com/department-of-veterans-affairs/component-library/pull/1508
