### ISSUE TITLE
CSS Library: Fix font faces being loaded from uswds

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3631]
## Description
On December 5th the design system team merged in a [pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/32154) to swap the import path of core stylesheets in vets-website from [Formation](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/formation) to [css-library](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library). This change removed a reference to fonts managed in Formation, where USWDS v1 font-faces were imported directly into [Formation's core.scss file](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/core.scss#L23). Without the presence of this Formation stylesheet, source sans pro fonts were no longer being picked up and included in vets-website's [webpack build](https://github.com/department-of-veterans-affairs/vets-website/blob/main/config/webpack.config.js#L305), which outputs assets to a folder named `/generated`. 

Temporarily, a [fonts.scss](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/sass/fonts.scss) has been added to vets-website which patches necessary fonts and re-adds them to the `/generated` folder in a build that gets published from vets-website to S3. 

Additionally, css-library makes use of [this stylesheet](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/css-library/src/stylesheets/base/fonts.scss) which declares some  font-faces and imports others from `uswds-fonts`. We need to verify how we're using this, as it seems like the imported uswds font-faces aren't actually being used. 

## Considerations
- We may not be using `@use` properly. All `@use` does is namespace imports, which is distinctly different than what `@import` does. In order to use the font faces provided by uswds, we probably need to declare font faces and give them a value of whatever we get from uswds.
- The core issue here is that source sans pro ttf fonts were not being added to `/generated`, and they need to be. Their presence there can be verified by checking the `/generated` folder in the build directory of vets-website.  
- More context can be found [in this slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1733852575539749)

## Tasks
- [ ] Ensure font-faces are being used properly in css-library/base/fonts.scss when using `@use`
- [ ] Test changes locally in vets-website using verdaccio. We should be able to publish an updated css-library version to verdaccio that includes changes to /base/fonts.scss. A successful test here is the removal of [this vets-website stylesheet](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/sass/fonts.scss) and fonts still be added as expected to `vets-website/build/localhost/generated`
- [ ] Once fonts are successfully being generated given the above, write a follow up task to remove the fonts.scss stylesheet from vets-website. This can be done during the css-library release in which these changes get published to vets-website

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 
@ataker - 
@harshil1793 -  
@it-harrison -
@jamigibbs -
@micahchiang -
@powellkerry -
@rmessina1010 -
@rsmithadhoc -
