### ISSUE TITLE
va-file-input: Show a previously-uploaded file

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3634]
## Description
Update the va-file input component to include a way to show that a file has been uploaded that doesn't require the file itself.

## Details
Slack discussion: https://dsva.slack.com/archives/C085JHZMQ67

## Tasks
- [ ] Update va-file-input to show a previously-uploaded file
- [ ] Test that this is working 
- [ ] Push to prod 

## Acceptance Criteria
- [ ] va-file-input can show a previously-uploaded file without access to the file itself

**Comment by Thrillberg** [comment]
Can we fold into this ticket the behavior shown in this screenshot? Specifically we're looking for an ability to show "Uploading..." while the file is uploading. I've looked around here: https://design.va.gov/storybook/?path=/docs/uswds-va-file-input--docs and not found anything that looks quite like what we're looking for. I figured perhaps in addition to name and size we could provide an uploading boolean that would trigger some sort of Uploading... state (like shown in the screenshot here).

![Image](https://github.com/user-attachments/assets/f3374572-225a-4b18-b567-fd140b6e55e0)

**Comment by caw310** [comment]
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 
@ataker - 
@harshil1793 -  
@it-harrison -
@jamigibbs -
@micahchiang -
@powellkerry -
@rmessina1010 -
@rsmithadhoc -

**Comment by Thrillberg** [comment]
> [@Thrillberg](https://github.com/Thrillberg) This is not a bad idea, but it's out of scope for this ticket. Please submit a separate request.

Sure thing! Here is another issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3660

**Comment by Andrew565** [comment]
[Related Slack convo here.](https://dsva.slack.com/archives/C01DBGX4P45/p1736444557002429)

Ultimate goal of this ticket is to provide a way to show that a file has previously been uploaded, without requiring the file itself. The "name" and "size" props were suggested as a way to 'fill in the blanks' because those values are what are currently available to the developer from the Redux store.

Another option would be to override the existing "value" prop to accept an object (e.g. `{name: "File Name", size: "XXkb"}`) in addition to a File.

**Comment by Mottie** [comment]
I don't see a corresponding update to `va-file-input-multiple`. Will it be added in a separate ticket?
