### ISSUE TITLE
Create mockup of use eyebrow in card

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3636]
## Description
Create a mockup of eyebrow in card to help the Transition Experience team address issue raised during staging review. 

[Staging Review finding: Caps-case in card headers on results page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98574#top)

## Tasks
- [ ] Create mock up to show use of eyebrow in card
- [ ] Have DST designers review and provide feedback
- [ ] Share mock up with Transition Experience team in the staging review ticket 

## Acceptance Criteria
- [ ] Mockup is shared in staging review ticket

**Comment by babsdenney** [comment]
![Image](https://github.com/user-attachments/assets/2e62ca64-ddb9-41dd-af43-418525fdeea6)

[Figma file](https://www.figma.com/design/E3XD1cxDDnlF8cKPezgslV/Eyebrow-component-in-a-card?node-id=0-1&t=pYKNsqo2VKqEKDGw-1)
