### ISSUE TITLE
Remove ability to center text in va-alert - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3638]
## Description
Text in alerts should not be centered. Currently, va-alert has a prop or something that allows for that to happen. That needs to be removed. 

Add text align left to alert. 

## Tasks
- [ ] Remove ability to center text in va-alert 
- [ ] Test and have a designer review
- [ ] Publish change 

## Acceptance Criteria
- [ ] Text in va-alert cannot be centered.

**Comment by Andrew565** [comment]
@caw310 I looked into this and I'm not seeing anywhere where we are allowing an alert's text to be centered. Everything is encapsulated inside the shadow DOM. Do you happen to know of an example on the site where this is happening?

**Comment by caw310** [comment]
@humancompanion-usds do you remember the example that lead to this request?

**Comment by humancompanion-usds** [comment]
I sure don't
