### ISSUE TITLE
CSS Library: Refactor a simple vets-website application to only use uswds v3 grid classes

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3648]
## Description
To facilitate the migration from Foundation and uswds v1 grid to uswds v3 grid, we need to understand the process for converting an application to only use uswds v3 grid. 

We've already enabled uswds v3 grid in our  [uswds theme settings](https://github.com/department-of-veterans-affairs/component-library/blob/1fca0b6b271e560526cd472d228da462e53155d8/packages/css-library/src/stylesheets/_uswds-theme.scss#L9), and these classes are currently available in our generated utilities.css file in `dist/` with the prefix `vads-grid`. 

## Considerations 
- We may be able to use the [DS V1 - V3 playground](https://staging.va.gov/ds-playground/) as a comparison tool since it uses the old classes.
- One option may be to use the [DS V3 playground](https://staging.va.gov/ds-v3-playground/) since it already uses uswds v3 grid classes. It would likely need to be refactored to show the exact same content as the ds v1 - v3 app so equivalent layout functionality is demonstrated.
- We specifically want to make sure we're covering the core aspects of our [existing documentation](https://design.va.gov/foundation/layout/flexbox-grid), i.e. the replacement classes for `vads-l-grid-container` and `vads-l-grid-container--full`, etc. 

## Tasks
- [ ] Refactor the [V3 Playground](https://github.com/department-of-veterans-affairs/vets-website/blob/c61861895bfd6e21afee4ef95e7271ede1c3a366/src/applications/ds-v3-playground/manifest.json#L5) application so it has the same **content** as [V1 - V3 Playground](https://github.com/department-of-veterans-affairs/vets-website/blob/c61861895bfd6e21afee4ef95e7271ede1c3a366/src/applications/ds-playground/manifest.json#L5). The grid classes for the V1 - V3 app can stay as they are because they demonstrate responsiveness using the current (old) grid system. The grid classes for the V3 app will need to be updated to show the same amount of responsiveness, using the the new V3 grid classes.  
- [ ] We'll take this opportunity to refactor the V1 - V3 app, since we no longer need a side by side comparison of our v1 and v3 web components. Instead, we'll use the page to build a dummy UI that uses the old grid, then copy whatever new UI we come up with here to the V3 app and use the new grid. 
- [ ] Keep notes on any gotchas we might find along the way here. For example, `vads-l-grid-container` sets max-width to 1000px, and left and right padding to 1.875rem at the 768px breakpoint, where as `vads-grid-container` sets max-width to 64rem, and left and right padding to 1rem by default, but then updates left and right padding to 2rem at a `min-width: 64em` breakpoint. Since we're inheriting all of our v3 grid styles directly from USWDS, this behavior is all documented [here](https://designsystem.digital.gov/utilities/layout-grid/), but these _changes_ should be highlighted for our users. 

## Acceptance Criteria
- [ ] Above tasks have been completed.

**Comment by caw310** [comment]
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 
@ataker - 
@harshil1793 -  
@it-harrison -
@jamigibbs -
@micahchiang -
@powellkerry -
@rmessina1010 -
@rsmithadhoc -

**Comment by micahchiang** [comment]
this will carry over. It's turning out that this is a little bigger than just finding a simple application, and may need to focus more on guidance / documentation first.

**Comment by micahchiang** [comment]
Here's a draft PR that converts the combined debt portal app to v3 grid - https://github.com/department-of-veterans-affairs/vets-website/pull/34772. 

I'm working on compiling some notes of things I've found along the way.
