### ISSUE TITLE
[Name tag] Create a pattern for The header / hero area with the veteran's name and info

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#389]
## Issue Description
Create a pattern for The header / hero area with the veteran's name and info

---
## Tasks
- [ ] Add header/hero pattern to Sketch library
- [ ] Create documentation for header hero pattern
- [ ] Develop header/hero component if needed 

## Acceptance Criteria
- [ ] Sketch library update
- [ ] Pattern is on design.va.gov 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andaleliz** [comment]
Hi @caw310 I just came across this - is this referring to the component we use in profile and My VA? If it is, is the idea behind this ticket to adapt it to be part of the design system?

<img width="248" alt="image" src="https://user-images.githubusercontent.com/55992116/188907145-d105d752-c22b-4e34-9b21-7d40f7c2a245.png">

**Comment by GnatalieH** [comment]
@andaleliz the title of this ticket, which refers to the "hero" element with Veteran's name and info, leads me to believe that you are correct. Although I'm not sure about the intention to add this as a DS component because the ticket predates me joining the DST. So, do you use this as a shared symbol in the Authenticated Experience library? I haven't looked at it recently. Thanks. CC @caw310

**Comment by andaleliz** [comment]
Yes, we do use it as a shared symbol in the authenticated experience library. And now that logins from the homepage will be redirected to My VA, many people will see this early in their experience on VA.gov.
