### ISSUE TITLE
Update Meta Tags rubric for VAMCs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/vets-design-system-documentation#441]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [x] Content style guide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

[Writing for SEO](https://design.va.gov/content-style-guide/seo#meta-properties)

## What is the nature of this update?

Updating the meta tag order for VAMCs  

**Current format:** VAMC Plain Language System Name | H1 Page Title | Veterans Affairs
   - Example: VA Pittsburgh Health Care | Medical Records Office | Veterans Affairs

**Requested format:** H1 Page Title | VAMC Plain Language System Name |Veterans Affairs
   - Medical Records Office | VA Pittsburgh Health Care | Veterans Affairs

- [x] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

This change has already been blessed by Danielle/Beth. The Facilities and CMS teams will make this an automatic process, rather than VAMC editor control.

**Comment by mmiddaugh** [comment]
Closed as a duplicate to https://github.com/department-of-veterans-affairs/va.gov-team/issues/24386
