### ISSUE TITLE
Create design and documentation for card Pattern

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#572]
This work will include the following:

- Document card building blocks
- Produce minified card template for design.va.gov Pattern documentation
- Include accessibility considerations and links to Content style guide (if applicable)
- Produce Sketch templates

## This update is for:

- [ ] Content styleguide
- [ ] Component
- [x] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Cards pattern

## What is the nature of this update?

Create documentation for cards:
- [x] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usage guidance
- [x] Accessibility considerations
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

- Audit of cards can be found at this [Mural board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1635796660299/abfd719db54ed49269dbf8d4690e05ad774c6e35?sender=u851998f98038e0f1e2da4592)
- [Related ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/387)

## Tasks
- [x] Audit of current use
- [ ] Update Sketch file
- [ ] Document
- [ ] Add to design.va.gov

## Acceptance Criteria
- [ ] Updates Sketch file
- [ ] Accessible on design.va.gov

**Comment by GnatalieH** [comment]
@caw310 how do we want to handle the follow up work on this ticket? Based on the DSC feedback, I have refinement to do on the Cards pattern documentation. Should I create another ticket for that work?

**Comment by caw310** [comment]
@GnatalieH please create tickets for follow up work based on DSC feedback.

**Comment by GnatalieH** [comment]
> @GnatalieH please create tickets for follow up work based on DSC feedback.

I created [a ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/600) as a follow up to capture my work, which is why I closed this ticket.
