### ISSUE TITLE
Publish Accessibility strategy to design.va.gov

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#598]
### Description
Publish Accessibility strategy document to design.va.gov.

### Tasks
- [x] Review/copy edit Accessibility strategy [draft document](https://docs.google.com/document/d/11-ZLC69Ijk1Ai7FVxzFhIQ6TmcWU-QEtqRiCkS7uuXI/edit)
- [x] Make suggestions/changes as needed
- [x] Share suggestions/changes with Matt, Josh, and Martha via Slack
- [x] Incorporate feedback if required
- [x] Edit Accessibility standards and maturity model section of draft document
- [x] Review content edits with Matt 
- [x] Work with Matt to find a home for content on design.va.gov
- [x] Send final version to Martha Wilkes for review and feedback.
- [ ] Matt to publish content on design.va.gov

### Acceptance Criteria
Content published on design.va.gov

### Notes
The strategy document is being put together by the a11y community of practice. Ideally it would cover:

- What we test for
- How we test - including but not limited to specific devices & browsers and on which operating systems
- How we work in concert with our 508 office

**Comment by humancompanion-usds** [comment]
@CourtneyChambers77 - Did you or Sarah have a draft of this that is in work? No worries if not, I just thought I heard mention of this last month. Thanks.

**Comment by humancompanion-usds** [comment]
@taylojill - I have a more urgent task for you than the next pattern: Adding an accessibility section to our Design System! @joshkimux has worked with the a11y community of practice to [draft a document](https://docs.google.com/document/d/11-ZLC69Ijk1Ai7FVxzFhIQ6TmcWU-QEtqRiCkS7uuXI/edit?usp=sharing). Can you copy edit that document and work with me to get it added to the site? Thanks!

**Comment by taylojill** [comment]
Will do @humancompanion-usds Thanks!

**Comment by caw310** [comment]
Will carry over into the next sprint. Work will be done but won't be published until the next sprint.

**Comment by taylojill** [comment]
Word document (with tracked changes) shared via Slack with Martha, Josh, and Matt.

**Comment by taylojill** [comment]
I spoke to Matt after meeting with Josh Kim. I will update the Accessibility standards and maturity model section of the document. Once approved by Matt, we will find a home for the content on design.va.gov and publish.

**Comment by taylojill** [comment]
Sent draft content for review/feedback to Martha Wilkes via Slack. Once approved, I'll write a ticket for Matt to publish content in the "About" section on design.va.gov.

**Comment by humancompanion-usds** [comment]
@taylojill - We can use this ticket to track publishing the page.
