### ISSUE TITLE
Normalize the gutters across the site (design tokens for spacing)

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#5994]
## Status
_Update each sprint until completed_
| Date | Status | Launch Date (see above) | Notes |
| ----- | ------ | ------------------------- | ------ |
| 29 May 2025 | paused | on-track | No change.  |
| 22 May 2025 | paused | on-track | No change.  |
| 15 May 2025 | paused | on-track | No change.  |
| 8 May 2025 | paused | on-track | No change.  |
| 1 May 2025 | paused | on-track | No change. Still waiting to hear from CMS team on implementation of the v3 grid which they are piloting. |
| 17 April 2025 | paused | on-track | No change. Still waiting to hear from CMS team on implementation of the v3 grid which they are piloting. |
| 17 April 2025 | in progress | on-track | Still waiting to hear from CMS team on implementation of the v3 grid which they are piloting. |
| 10 April 2025 | in progress | on-track | Semantic tokens for gutters added to CSS Library. Waiting to hear from CMS team on implementation of the v3 grid which they are piloting. |
| 4 April 2025 | in progress | on-track | Adding semantic tokens for gutters to CSS Library is in progress. Also, the CMS team has created a script to help with implementation of the v3 grid. They will do QA and let us know how it goes.|
| 28 March 2025 | in progress | on-track | Will be adding semantic tokens for gutters to CSS Library in the current sprint 24. Micah wrote up guidance on replacing grid and gutters that CMS team will be using to do a pilot. |
| 20 March 2025 | in progress | on-track | Semantic tokens for gutters to be added to CSS Library. TL and PM working with Laura F about doing a pilot. Micah has written up guidance on replacing grid and gutters.  |
| 13 March 2025 | in progress | on-track | Semantic tokens for gutters created. TL and PM will be working on a strategy to get teams to update normalized gutter spacing.  |
| 28 Feb 2025 | in progress | on-track | Adding semantic tokens for gutters in progress. Designer and engineer to work together on this.  |
| 21 Feb 2025 | in progress | on-track | Adding semantic tokens for gutters planned for sprint 22.   |
| 7 Feb 2025 | in progress | on-track | Patterns in Figma updated. Dev work to be planned.  |
| 24 Jan 2025 | in progress | on-track | Figma work in progress.  |
| 13 Jan 2025 | in progress | on-track | Figma work on this is restarting  |
| 4 Dec | paused | paused | paused due to other higher priority work. Will pick up this work in Jan  |
| 26 Nov | in progress | on-track | Discovery work has been done.  |
| 17 Oct | not-started yet | on-track | Had meeting to define the work. Will be writing issues and starting work in sprint 14 |

## Problem statement

Currently, across VA.gov and flagship mobile app we do not have consistent gutters, the outside padding on the left and right between the edge of the viewport (browser or device edge) and the edge of the main content well. 

## OCTO OKR

This work does not directly impact an OCTO OKR. However, it degrades Veteran trust in the site and mobile application when we have inconsistent UI that makes either the site or app appear partially broken or otherwise unreliable. 

## Hypothesis or Bet
* Making the gutters consistent will make the UI consistent and thus the UX more consistent.
* Making the gutters consistent will make it easier for us to publish templates in Figma that will reflect code decisions more accurately.

## We will know we're done when... ("Definition of Done")
* [ ] Semantic design tokens are created and in the CSS library for relevant gutter spacing.
* [ ] Design tokens include tokens for forms, CMS pages, etc. 
* [ ] We decide to either allow mobile app to stay at 10px gutters and add that to our spacing units or we get them to move to 8px or 12px gutter size

## Known Blockers/Dependencies 
These are global changes that may impact teams thus we should attempt a strategy of filing bugs for teams to fix issues and give them a deadline rather than making the PR changes ourselves.

## Projected Launch Date
I'd like the decisions, mainly the spacing design tokens, to be made, documented, and available to teams as well as the issues for them to adopt those tokens filed by the end of FY25 Q1 (Dec 30).
