### ISSUE TITLE
Remove ProgressBar & SegmentedProgressBar React components

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#622]
## Description

These React components are no longer used as a result of DST migrations:

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/32868
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/32864

As a result, we should be able to safely remove them. This would simplify a tech debt PR (https://github.com/department-of-veterans-affairs/component-library/pull/260#discussion_r782540443) which is removing lodash from `SegmentedProgressBar`.

## Tasks
- [ ] Remove `ProgressBar` React component from library
- [ ] Remove `SegmentedProgressBar` React component from library
- [ ] Publish new `component-library` major version
- [ ] Remove `ProgressBar` & `SegmentedProgressBar` from the [`vets-website` analytics script](https://github.com/department-of-veterans-affairs/vets-website/blob/4bc1f49c16722588ab039604ca3c18db6ed9caf2/src/platform/site-wide/component-library-analytics-setup.js#L28)

**Comment by andresriveratoro** [comment]
If we remove those components from the library, we'll also have to remove the Storybook stories for them. Is that okay? I ask because it seems like we usually deprecate them instead of completely removing them.

**Comment by k80bowman** [comment]
We do usually deprecate, but I think since these aren't in use anymore it is OK to just delete. We'll want to make sure the documentation on design.va.gov is pointing to the web components, too, though.
