### ISSUE TITLE
Consider removing ProcessList React component

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#632]
## Description

The `<ProcessList>` React component is currently unused in `vets-website`. Instead, the `process` CSS class is applied to achieve the same styling. 

- [Sass module](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/9e560ae3f3f077a44799b90c5550046601ec2fcf/packages/formation/sass/modules/_m-process-list.scss)
- [Example in `vets-website`](https://github.com/department-of-veterans-affairs/vets-website/blob/d4529630dd999c8ff9679c0f3eb789bb434265f2/src/applications/pensions/components/IntroductionPage.jsx#L27-L152)

With the [`<va-process-list>` Web Component on the way](https://github.com/department-of-veterans-affairs/component-library/pull/265), we may want to consider removing the unused React component.

## Tasks
- [ ] Remove `ProcessList` from the build:
    - [`Component source`](https://github.com/department-of-veterans-affairs/component-library/blob/f2eaf37f4c0b0c688d1239ffbab7d379279b64aa/packages/react-components/src/components/ProcessList/ProcessList.jsx) 
    - [`index.js`](https://github.com/department-of-veterans-affairs/component-library/blob/f2eaf37f4c0b0c688d1239ffbab7d379279b64aa/packages/react-components/index.js#L70)
    - [`src/index.js`](https://github.com/department-of-veterans-affairs/component-library/blob/f2eaf37f4c0b0c688d1239ffbab7d379279b64aa/packages/react-components/src/index.js#L72)
- [ ] Remove `number-to-words` dependency
- [ ] Remove [Storybook file](https://github.com/department-of-veterans-affairs/component-library/blob/f2eaf37f4c0b0c688d1239ffbab7d379279b64aa/packages/storybook/stories/ProcessList.stories.jsx)
- [ ] Update [Process List component documentation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/6f8589449769ee22e20fcebd17d21f0f9fd73d08/src/_components/process-list.md?plain=1#L13) to point to Web Component story
- [ ] Bump major version for `react-components` sub-package and `core` package
- [ ] Tag new release

**Comment by pdavies88** [comment]
@bkjohnson since we are closing #34435 can we make sure that removing `number-to-words` as a dependency in the `react-components` package.json is also part of the AC for this ticket

**Comment by bkjohnson** [comment]
Good call, I just added that.
