### ISSUE TITLE
[Button] Deprecate green button

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#653]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [x] Component
- [x] Pattern
- [ ] Utility
- [ ] Other

## What is the name?

The green button is no longer being used, however we still have it on design.va.gov and in Sketch
https://design.va.gov/components/buttons
https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/dlwAYWb
https://design.va.gov/storybook/?path=/docs/components-buttons--primary

## What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [x] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Tasks
The green button should now only be used for sign in. Because of this, we are not going to delete the style, but there are still 22 other uses of it currently, so we need to announce that we are deprecating it and see if we can add an ESLint rule to help people migrate to an alternative.

- [x] Find out if we can create an ESLint rule that looks for the green button class (`va-button-primary`). If so, create an ESLint rule with a notification that the class has been deprecated and a link to the design.va.gov button guidance.
- [x] Add notice of the deprecation to "What's New" page on design.va.gov
- [x] Announce the deprecation of the green button in the following channels:
  - [x] #vfs-all-teams
  - [x] #vfs-frontend
  - [x] #design
  - [x] #cms-team
  - [x] #cms-design

Sample announcement:
>📢 The Design System Team is **deprecating the [class name] Design System CSS class and its associated styles.** Please see [design.va.gov]([link to alternative style documentation]) for alternative options.
>
>We have an ESLint warning in place now that will alert teams if this class is being used in a file they are editing. **In 6 weeks, we will fully deprecate the [class name] class and the ESLint warning will become an error. Please make plans to migrate to an alternative option for this class as soon as possible.**
>
>If you need any assistance removing this class from your applications, please reach out to the Design System Team in the #vfs-platform-support channel.

## Acceptance Criteria
- [x] The use of an ESLint rule has been explored and, if possible, implemented
- [x] Notice of the deprecation has been added to the "What's New" page on design.va.gov
- [x] The deprecation of the green button class has been announced in the appropriate Slack channels

**Comment by GnatalieH** [comment]
Thanks @allison0034 for making this ticket. :)

**Comment by caw310** [comment]
This was discussed in the 2/25 DSC meeting. Decision is to go ahead with the audit of the green button usage.

**Comment by allison0034** [comment]
We need to look at the documentation as well for buttons in general and make sure Storybook and design.va.gov match.

**Comment by GnatalieH** [comment]
@seanasewell confirmed that the green button is used correctly when it's on an alert that prompts the user to sign in, or do another action, in order to continue with a process. I think this is the only legit use case for the green button. Thoughts, @allison0034?
