### ISSUE TITLE
Documentation update: Horizontal rules

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#746]
Make updates to Horizontal rules on design.va.gov,  Storybook and Sketch library to fix the discrepancies that have been identified. 

## Tasks

- [ ] Add Horizontal rules to design.va.gov with user guidance
- [ ] Add View guidance for the Horizontal rules component in the Design System 
- [ ] Add a link in Storybook  that links back to Horizontal rules on design.va.gov  (See example on va-modal)
- [ ] Update link to Storybook on design.va.gov to "View Horizontal rules  in Storybook"
- [ ] Update Sketch file with  Horizontal rule/Stars component

## Acceptance Criteria
- [ ] Horizontal rules has a component on design.va.gov with guidance on usage
- [ ] Storybook has link “View guidance for Horizontal rules  component in the Design System” 
- [ ] Storybook has a link to the component page on design.va.gov 
- [ ] Horizontal rules  link to Storybook is labeled "View Horizontal rules in Storybook"
- [ ] Sketch file has Horizontal rules component

**Comment by humancompanion-usds** [comment]
I think the guidance we have for Divider is adequate. I've updated the initial comment on this issue to reflect what we've done and what work remains. @GnatalieH let me know that we'll need to recreate the stars divider in Sketch as we don't have it.
