### ISSUE TITLE
Documentation update:  Tags (formerly known as Labels)

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#747]
The following tasks are to resolve discrepancies in documentation on design.va.gov, Storybook and Sketch. 

## Tasks
- [x] Change the name Labels in Storybook to Tags
- [x] Add "View guidance for the Tags component in the Design System" to Storybook  that links back to Tags https://design.va.gov/components/tag  (See example on va-modal)
- [x] Update the link to Storybook on design.va.gov to "View Tags in Storybook"
- [ ] Sketch Label component symbol should be moved out of Card symbol menu hierarchy. Content presentation or Global components might make more sense. 
- [ ] Change Label in Sketch to Tags

## Acceptance Criteria
- [ ] Storybook has been updated so that labels is called Tags
- [ ] Storybook has link “View guidance for Tags component in the Design System” 
- [ ] Storybook has a link to the component page on design.va.gov  URL
- [ ] Tags link to Storybook is labeled "View Tags in Storybook"
- [ ] Sketch file has been updated

**Comment by humancompanion-usds** [comment]
Draft PR in flight that fixes the remaining work here in guidance. The Storybook and Figma items have already been handled.
