### ISSUE TITLE
Button web component - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#749]
## Description
Create design for Button web component.

## Details
[add links to any tickets or documents with details about the design]
[add links to any research documents related to the component]

## Tasks
- [x] Create designs for component
- [x] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [x] Review designs with DST members (Carol can help schedule this)
- [x] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [x] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [x] Link to design has been added to this ticket and shared in Slack

## Mockups
- [Mobile](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/ELZ71WR)
- [Desktop](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/jgazRMo)

**Comment by caw310** [comment]
Review items from this button component audit to make sure items are addressed. 
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/205

**Comment by andresriveratoro** [comment]
We would like to use icons instead of text to display arrows as unicode characters are difficult to read.

**Comment by GnatalieH** [comment]
@SarahKay8 hi. Would you mind reviewing the mockups for Buttons (links are in description of ticket) and letting me know if there are accessibility details that need attention? You will have to create a Sketch account if you haven't done so, yet, to access the mockups. Thank you!

**Comment by SarahKay8** [comment]
@GnatalieH Hi Natalie. Currently setting up a sketch account. Will have feedback for you EOD

**Comment by GnatalieH** [comment]
@SarahKay8 are the color variations not 3:1 for the hover states? I'm happy to explore options if @humancompanion-usds wants us to redesign our button hover states. FWIW, we're working on a new focus style right now. Thanks!

**Comment by humancompanion-usds** [comment]
@SarahKay8 - Are we saying that the USWDS buttons don't pass contrast because I find that hard to believe: https://designsystem.digital.gov/components/button/ If we deviate we'll need to maintain that deviation forever and I'd prefer not to do that unless we absolutely feel the USWDS buttons are significantly deficient. We are making the gold box for focus meet 3:1 contrast (that discussion is in issue #805). So is there a preference for a different hover state or is not meeting a particular guideline or rule?

**Comment by SarahKay8** [comment]
This is in regards to the yellow focus indicators itself. The button contrast is fine.

**Comment by GnatalieH** [comment]
Closing because we're addressing focus style in #805.
