### ISSUE TITLE
Update links to design.va.gov on the Platform website

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#763]
## Description
At least one link to our resources from the [Platform documentation site](https://depo-platform-documentation.scrollhelp.site/?internal-user-opt-out=true) has been flagged as no longer working. I would assume there are more. We need to review the documentation on the Platform site for links that need to be updated and make sure they are now pointing to the correct resource.

## Details
[Guidance on editing Confluence pages](https://vfs.atlassian.net/wiki/spaces/AP/pages/2046558209/Edit+Platform+website+documentation)
Each of the sections in the Platform site has its own Confluence Space. You can find a list with links to each space on [this page](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization). We need to check at least the following sections:
- Getting started
- Developer docs
- Research and design

## Tasks
- [ ] Review Platform website for links to design.va.gov that may be broken.
- [ ] Follow guidance on editing Confluence pages to get the broken links fixed.

## Acceptance Criteria
- [ ] All links to design.va.gov pages from the Platform site are directed towards the correct functioning pages

**Comment by k80bowman** [comment]
This link on the [Welcome](url)![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/5d9a6d8a-de72-44fd-a1e4-87edb568e3c8) page is broken:
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/a3a98f65-5760-446f-b15c-7f74ddb0dde5)

**Comment by k80bowman** [comment]
Updates are done for the Research and design section and I checked the Collaboration Cycle section. That should cover it.
