### ISSUE TITLE
Update documentation: Form controls - Text inputs

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#773]
## Issue Description
Make updates to Form Controls on on design.va.gov and Storybook to fix the discrepancies that have been identified. 

Discrepancies
Text inputs
-There is no "Text area" component (Non-Web component example in design.va.gov and Storybook) in Sketch.
-There is no "Success" state in design.va.gov or Storybook (green border on input field). This example only lives in Sketch.
-No "Required" example of text input in design.va.gov but it exists in Storybook.

---
## Tasks
- [x] Add Text area to Sketch library
- [x] Add Success state of the text input to design.va.gov  https://design.va.gov/components/form-controls#text-inputs
- [x] Add Success state of the text input to Storybook https://design.va.gov/storybook/?path=/docs/components-va-text-input--default

- [x] Add View guidance for the Text Input component in the Design System below label for va-text-input in Storybook  that links back to Text Input on design.va.gov   https://design.va.gov/components/form-controls#text-inputs  (See example on va-modal)
- [x] Update link to Storybook on design.va.gov to "View va-text-input in Storybook"

##### Storybook
- [x] Add subtitle `Text Input web component` for `va-text-input`
- [x] Add `View guidance for the Text Input component in the Design System` link with an url value of `https://design.va.gov/components/form-controls#text-inputs`
- [x] Add success state example in `va-text-input` story

##### design.va.gov
- [x] Update Storybook preview link text to `View va-text-input in Storybook`
- [x] Add success state Storybook preview

##### Sketch
- [x] Sketch library has Text area mock up for Text inputs

## Mockups

[Text Input in Sketch](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/4a07okJ)

**Comment by humancompanion-usds** [comment]
@GnatalieH - Looks good. A few comments:

* I would expect the text-input fields in a mobile layout to be full-width (12px of gutter on either side so 296px wide). I see you did text-area that way but not the other input fields. I'd make them all the same and then you don't need that text calling it out.
* I've been putting the state names in the headers above the fields. Take a look at how I did Additional Info.
* This leaves me asking what happens when you have hint-text and an error? I'm not sure what the ordering would be in that case. Might be worth adding or calling out in guidance.

**Comment by GnatalieH** [comment]
@humancompanion-usds I made your suggested changes, except I haven't yet figured out how to handle the error state with the hint text variation. I'll ask our engineers if that state can occur, and figure out what to do accordingly. 

[Here is the link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/V8kJwK/a/4a07okJ/r/EPlD9d) to the Text input page in the Sketch library so you can link from design.va.gov. Thanks.
