### ISSUE TITLE
Update documentation: Form controls: Select Box

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#774]
## Issue Description
Make updates to Form controls: Select box on design.va.gov, Storybook and Sketch library to fix the discrepancies that have been identified. 

Sketch Library
The Select box is called Dropdown in the Sketch Library, and nowhere else. Also, the Sketch symbol needs to be updated to show the focus halo when the menu is open (to match behavior of coded component).

---
## Tasks
- [ ] Update Sketch file - change Dropdown to Select box
- [x] Add View guidance for the Select Box component in the Design System below label for va-select in Storybook (See example on va-modal) that links back to Select box on design.va.gov  https://design.va.gov/components/form-controls#select-box 
- [x] Update link to Storybook for Select box on design.va.gov to "View va-select in Storybook"

## Mockups
[Select Box in Sketch](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/m1l9A0L)

## Acceptance Criteria
- [ ] Sketch library name is Select box 
- [x] Storybook has link “View guidance for Select Box component in the Design System” 
- [x] Storybook has link to Select Box  on design.va.gov  https://design.va.gov/components/form-controls#select-box 
- [x] Select box link to Storybook is labeled "View va-select in Storybook"

---
