### ISSUE TITLE
Improve search results on design.va.gov

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#776]
## Description
Accessibility improvements to the design.va.gov:
- Search page should show descriptions (use intro-text from yml front-matter)
- Search results should use h2s for page titles

## Details
This comes from feedback we received during a user research session with Angela Fowler.
Check with Natalie and Matt about design of search results when updating page titles to h2s.

## Tasks
- [x] Add page descriptions to search page results
- [x] Update search page result page titles to h2s
- [x] Verify design of search results with Matt and/or Natalie

## Acceptance Criteria
- [x] Search page results include page descriptions
- [x] Page titles are now h2 elements.
