### ISSUE TITLE
Use Github Deployments/Environments for deploying each PR

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#802]
# Description

Work for this ticket should happen after https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/793 is merged

In another ticket @humancompanion-usds [wrote](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33568#issuecomment-1111083326):

> I'd really like to be able to deploy to staging and then decide when to push to production. This would give us a chance to review what we're putting out, perhaps get feedback on it.

In an effort to allow a github-centric workflow instead of running a local jekyll server to verify changes, we could use [GitHub environments for deployment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment).

For a job could have something like this:

```yaml
on: pull_request

jobs:
  dev-deploy:
    environment: 
      name: development
      url: https://dev-design.va.gov/${{ github.event.number }}
    steps:
    # ...
    - run: aws s3 sync _site s3://dev-design.va.gov/${{ github.event.number }}
```

This would allow each PR to have its own dev/preview environment that can be accessed from the PR by clicking a button. Here's an [example from `vets-website`](https://github.com/department-of-veterans-affairs/vets-website/pull/20913) showing what that would look like:

!["View deployment" button visible in PR](https://user-images.githubusercontent.com/2008881/166598651-cd6b5079-f1d4-4ef6-82fb-343aa47a3fd6.png)

## Tasks

- [ ] Create a `development` environment in GitHub
- [ ] Refactor the GitHub action for deployment to [create a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow)
  - [ ] Remove `dev-design.va.gov` from the environment matrix
  - [ ] Update existing deploy workflow to use new reusable workflow for staging & production environments
- [ ] Create new workflow for deploying to dev
  - [ ] Should use reusable workflow
  - [ ] Deploys to dev s3 bucket with PR number as subdirectory

## Future work

An optional piece of future work could be to split up the deploys to staging & prod and:

1. Deploy to staging on a push to `master`
1. Have the prod deploy configured to [require an approval](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) before running

**Comment by jamigibbs** [comment]
It only took us 2.5 years but thank you @bkjohnson for paying it forward with the excellent description and guidance! 🙇‍♀ Hope you're doing well!

**Comment by bkjohnson** [comment]
Thank you, I'm glad my ancient work came in handy!
