### ISSUE TITLE
Search web component with type-ahead: Announcement

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#806]
## Description
Announce that the Search web component with type-ahead is ready for use and add it to the "What's New" page on design.va.gov.

## Details
Dependent on the completion of development, the creation of Sketch artifacts and component page, and documentation for the component on design.va.gov.

In the Slack announcement, please add links to the component page on design.va.gov and to the Design System Maturity Scale page on design.va.gov. Post the announcement in the following Slack channels:
- #vfs-all-teams
- #vfs-engineers
- #vfs-frontend
- #design

Sample announcement:
> :loudspeaker: The Design System has just published a new version of component-library which includes the new [component name] component, as well as made it available in vets-website. This component is rated Use with Caution: Available on the Design System Maturity Scale and the Design System Team will be monitoring its usage over the next few months.
>
> If you need any assistance using this component in your applications, please reach out to the Design System Team in the #vfs-platform-support channel.

## Tasks
- [x] Craft component announcement (be sure to add appropriate links)
- [x] Post announcement in Slack channels mentioned above
- [x] Add new component notification to "What's New" page on design.va.gov

## Acceptance Criteria
- [x] Component has been announced in appropriate Slack channels
- [x] New component notification has been added to "What's New" page on design.va.gov

**Comment by andresriveratoro** [comment]
:loudspeaker: The Design System has just published a new version of component-library which includes the new [va-search-input](https://design.va.gov/components/search-input) web component, as well as made it available in vets-website. You may view the component on [design.va.gov](https://design.va.gov/), in [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-search-input--default), and in Sketch.

If you need any assistance using this component in your applications, please reach out to the Design System Team in the #vfs-platform-support channel.
