### ISSUE TITLE
Button web component - Development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#817]
## Description
Build a va-button web component.

## Details
- Design documents: [Sketch](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/jgazRMo)
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [x] Review DST backlog for outstanding issues with this component, if necessary
    - Carol has pulled button-related tickets in #862
- [x] Create web component and add to Storyboook
- [x] Write any necessary tests
- [x] Add Chromatic link to #818 and request review from an accessibility specialist
- [x] Ping designer for design review
~~- [ ] Once accessibility and design reviews are complete, alert Carol that component is ready for staging review~~
~~- [ ] Address any staging review comments~~
- [x] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
- [ ] Merge component

## Acceptance Criteria
- [x] Component is written and added to Storybook
~~- [ ] Component has had accessibility and design reviews~~

**Comment by andresriveratoro** [comment]
Please see this [comment](https://github.com/department-of-veterans-affairs/component-library/pull/419#issuecomment-1123005073) by Brooks about how the component API could look like.

**Comment by k80bowman** [comment]
Let's do what we can to make sure [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36877) is not an issue with the web component.

**Comment by andresriveratoro** [comment]
TODO (per standup discussion)
- [ ] Update navigation props to continue and back
- [ ] Update Button web component documentation issue with width of back button
- [ ] Investigate ProgressButton text used in production
