### ISSUE TITLE
Button web component - Accessibility Review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#818]
## Issue Description
We need to conduct a full accessibility review of the va-button web component. The component can be viewed in Storybook here: https://design.va.gov/storybook/?path=/docs/components-va-button--primary

## Tasks
- [ ] Full accessibility review of the component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] Alert Katy and the developer who built the component when the review is complete
- [ ] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [ ] Component has been reviewed for accessibility issues
- [ ] Any accessibility issues have been addressed

**Comment by andresriveratoro** [comment]
@SarahKay8 This component is ready to be looked at. I've updated the issue with the Chromatic link. Thanks!

**Comment by SarahKay8** [comment]
Hi @andresriveratoro I have no further feedback to add. Buttons are solid

**Comment by andresriveratoro** [comment]
@SarahKay8 This component has been updated and will need to be looked at again. I've updated Storybook to include a story for a `disabled` button and updated the button to always have a value for aria-label. Thank you!

**Comment by SarahKay8** [comment]
> @SarahKay8 This component has been updated and will need to be looked at again. I've updated Storybook to include a story for a `disabled` button and updated the button to always have a value for aria-label. Thank you!

Gotcha!

**Comment by k80bowman** [comment]
@SarahKay8 were you able to take a look at the disabled state?

**Comment by SarahKay8** [comment]
Hi @andresriveratoro after syncing up with Brian there were a few questions..


(1) The <label> is correctly associated with the <textarea> using the for attribute, but there's also an aria-labelledby on the textarea that's referring back to the label. I don't think it hurts anything but these should be redundant --- if they have the for attribute on the label they shouldn't need aria-labelledby. Do you know if there was a specific reason that was included?

(2) When there's a https://design.va.gov/storybook/?path=/docs/components-va-textarea--default#max-length set for the textarea input, the message about the max number of characters is given as placeholder text inside the text input. Placeholder text isn't a great place for that message... but it's unclear looking in Storybook if they have that placeholder text auto-populating or if that's just how the example was configured in Storybook. Do you know anything about what the intention was there?

**Comment by SarahKay8** [comment]
Taking a look now! My apologies, I looked at the text area component first

**Comment by k80bowman** [comment]
No worries, thank you @SarahKay8!

**Comment by SarahKay8** [comment]
Hi @andresriveratoro disabled state is approved. JAWS and NVDA both announce the button as unavailable with the "disabled" attribute. ✅✅✅

**Comment by andresriveratoro** [comment]
@SarahKay8 I've updated the button to use `aria-disabled` and to be focusable while preventing clicks, simulating a disabled button.

The latest changes can be re-tested [here](https://818-button-disabled--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-button--primary#disabled). Thanks!

**Comment by k80bowman** [comment]
Thank you both! Closing this now.

**Comment by SarahKay8** [comment]
@briandeconinck See for reference
