### ISSUE TITLE
Button web component: Documentation and Sketch update

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#819]
## Description
Add or update documentation and guidance for the button web component on design.va.gov.

Coordinate with Natalie on any necessary Sketch updates

## Details

- [Link to Sketch mockups
](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/5317C603-D6BD-4AFF-84E6-151F7A197B91)

Be sure to use the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option.

## Tasks
- [x] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [x] Coordinate with Natalie on Sketch updates
- [ ] Request documentation draft review
- [x] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [x] Component documentation is up-to-date published on design.va.gov
- [x] Any necessary Sketch updates have been completed

**Comment by humancompanion-usds** [comment]
Natalie's changes in Sketch are spot on. However, it looks like we have a disconnect on naming within the Button pairs. Let's discuss in stand-up and get on the same page.

**Comment by humancompanion-usds** [comment]
I need to find the right icon for us to use in the Button pairs.

**Comment by humancompanion-usds** [comment]
We decided today in stand-up to create a va-button-pair component that is distinct and uses va-button.

**Comment by humancompanion-usds** [comment]
@andresriveratoro - The font-awesome icons to use for the button pairs are chevrons-right and chevrons-left. 

https://fontawesome.com/icons/chevrons-left?s=solid
https://fontawesome.com/icons/chevrons-right?s=solid

**Comment by caw310** [comment]
Natalie to update the chevron buttons in Sketch. 
Matt to write up guidance.

**Comment by GnatalieH** [comment]
> Natalie to update the chevron buttons in Sketch. Matt to write up guidance.

@caw310 I updated the icons yesterday, so that work is done now. Just FYI, thx.

**Comment by humancompanion-usds** [comment]
Documentation on button has been merged. New issues coming for the Button Pair component (web-component, Sketch update, and Documentation).
