### ISSUE TITLE
Add documentation about contributing new web components for frontend teams

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#829]
## Description
If we are going to ask/allow frontend teams to contribute web components as experimental designs, we need to provide some guidelines and instructions for what is required.

## Details
I think it would be good for this documentation to live in the component-library README, but I could also see some kind of checklist living on design.va.gov. We should discuss this as a team to decide on the best location(s).

Things that should be covered include, but are not limited to:
- Testing guidelines
- Instructions for adding analytics
- Adding component to Storybook
- Updating design.va.gov to point to Storybook component story

## Tasks
- [ ] Determine proper home for this documentation
- [ ] Write up documentation
- [ ] Review documentation with engineering team
- [ ] Publish documentation

## Acceptance Criteria
- [ ] Comprehensive documentation about how to contribute new web components exists and is easy to locate and follow

**Comment by humancompanion-usds** [comment]
We did update our contribution guidance: https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved
