### ISSUE TITLE
Add Maturity Scale to Storybook component stories

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#831]
## Description
We need to indicate the status of each component in Storybook with the appropriate Maturity Scale level, similar to what we have on design.va.gov.

## Tasks
- [ ] Determine how best to display the Maturity Scale status in Storybook
- [ ] Add the appropriate Maturity Scale indicator/label for each component

## Acceptance Criteria
- [ ] Each component in Storybook is labelled with the appropriate Maturity Scale
