### ISSUE TITLE
Get translations for all hardcoded text in components

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#834]
## Description
In order to get out ahead of translation requests, we would like to go ahead and get translations for all hardcoded text in our Design System components. Once we get the translations, we can go ahead and add them to our [translations files](https://github.com/department-of-veterans-affairs/component-library/tree/master/packages/core/src/i18n/translations).

## Details
- Gather text into a JSON file
- Coordinate with Danielle Thierry to get translations from the State department
    - Most likely we can start with just Spanish, but verify this with Danielle

## Tasks
- [ ] Add all untranslated hardcoded text to a JSON file
- [ ] Work with Danielle Thierry to get translations from the State department
- [ ] Add translations to translations files

## Acceptance Criteria
- [ ] All hardcoded component text has been added to the [translations files](https://github.com/department-of-veterans-affairs/component-library/tree/master/packages/core/src/i18n/translations) in at least English and Spanish.

**Comment by bkjohnson** [comment]
This [ESLint plugin](https://github.com/edvardchen/eslint-plugin-i18next) could help us identify all of the hardcoded text.

**Comment by bkjohnson** [comment]
Closing since now we are [waiting to receive the translations](https://dsva.slack.com/archives/C01DBGX4P45/p1658160625286439). Will open new tickets to make the appropriate engineering changes once we receive them.
