### ISSUE TITLE
Update CI build step order

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/vets-design-system-documentation#836]
## Description
The following files may need to be updated to include additional steps and correct the order of steps:
`.github/workflows/chromatic.yml`
`.github/workflows/node.js.yml`
`.github/workflows/publish-storybook.yml`

This doesn't appear to be an issue now, but may surface when `react-components` is bundled.

We would like to make sure that we are following the build order as seen in our README. We are using a StencilJS React binding in the Banner React component. This means that we must run `build` and `build-bindings` in `web-components` BEFORE running `build` in `react-components`.

## Tasks
- [ ] Install dependencies, run build and run build-bindings for `web-components` before running the `Install dependencies in react-components` step in `.github/workflows/chromatic.yml`
- [ ] Install dependencies, run build and run build-bindings for `web-components` before running the `Install dependencies in react-components` step in `.github/workflows/node.js.yml`
- [ ] Install dependencies, run build and run build-bindings for `web-components` before running the `Install dependencies in react-components` step in `.github/workflows/publish-storybook.yml`

## Acceptance Criteria
- [ ] Chromatic Github workflow runs build steps for `web-components` before `react-components`
- [ ] Node Github workflow runs build steps for `web-components` before `react-components`
- [ ] Storybook Github workflow runs build steps for `web-components` before `react-components`

**Comment by jamigibbs** [comment]
I'm a little unclear about what the issue was because I can't recall having any problems with the workflow build steps. 🤔 

I'll close this for now but I'll keep it in mind if we do end up running into some issues with the order.
