### ISSUE TITLE
Date web component with text inputs - Development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#843]
## Description
Build a new Date web component with text inputs instead of select inputs. This is being added separately from our regular Date web component as an experimental design for testing. Be sure to add analytics if necessary, see [guidance](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Details
- Design documents: [add links to any design documents]
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Create web component and add to Storyboook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews

**Comment by GnatalieH** [comment]
@pdavies88 and @k80bowman, where can I see an example of this component that has been developed? I need to create the Sketch artifacts, and right now I'm referencing the [Memorable date component](https://designsystem.digital.gov/components/memorable-date/) from USWDS. I also need to see an example of an error state. Thanks!

**Comment by pdavies88** [comment]
@GnatalieH yes here is the Chromatic Link: https://843-va-date-text-inputs--60f9b557105290003b387cd5.chromatic.com/
Go down to `va-date-text-input`

**Comment by GnatalieH** [comment]
@pdavies88 thanks for sharing the Chromatic link. I'm working on the Sketch assets, and I'm wondering why in our example the Month field is so wide, when it should actually be the Year field that is wider to accommodate four characters. Also, we should leave 8px margin on left and right sides in the smallest viewport, 320px. Can we follow USWDS's example of Memorable date? Thank you!

Our example:
<img width="341" alt="Screen Shot 2022-05-26 at 9 46 19 AM" src="https://user-images.githubusercontent.com/88347129/170512918-71164636-0c5c-4758-975e-4e7405356d83.png">

USWDS example:
<img width="345" alt="Screen Shot 2022-05-26 at 9 48 45 AM" src="https://user-images.githubusercontent.com/88347129/170513140-658fe0f5-395d-4abc-9b71-979f4dcd2500.png">

**Comment by k80bowman** [comment]
We've decided to add some validation to this component as follows:
1. Support single digit days and months (to match USWDS specs)
2. Valid month entry is 1-12
3. Valid day entry is dependent on month and will be between 1-29, 1-30, or 1-31 depending on the month
4. Invalid data entry should trigger the Please enter a valid date error message
6. Valid year entry should be limited from 1900 through 2200

**Comment by pdavies88** [comment]
Removing AC on ariadescribedby prop per: https://github.com/department-of-veterans-affairs/component-library/pull/438#discussion_r889013787
