### ISSUE TITLE
Date web component with text inputs - Sketch artifacts

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#846]
## Description
Create or update Sketch artifacts for the experimental version of the Date component with text inputs instead of select inputs and add to the VA Design System Sketch library if they are not already there.

## Tasks
- [x] Create or update Sketch artifacts for component
- [x] Add Sketch artifacts to Sketch library, if not already there
- [x] Create component page in Sketch, if necessary
- [ ] Add link to Sketch component page to documentation ticket

## Acceptance Criteria
- [x] Sketch component artifacts have been created or updated
- [x] Sketch component page has been created, if necessary
- [ ] Link to Sketch component page has been added to component documentation ticket

## Mockups
- [Sketch mockups](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/L1oOmW/a/g0KYaEq/r/EPmLQO)

**Comment by GnatalieH** [comment]
[Mockups are here](https://www.sketch.com/s/789c144c-98c6-4350-b9d5-9acb6112069d/a/nR2arjz). @humancompanion-usds and @pdavies88 can you review my work? Preston, I made some changes with the spacing between labels, and I also bolded the labels above the red inline error message because this is how the text input error state looks. Thoughts?

**Comment by pdavies88** [comment]
@GnatalieH had to request access to see the changes but I can definitely make them when I have access

**Comment by GnatalieH** [comment]
@pdavies88 OK cool, glad you got access. I didn't get a notification about that. Thanks!

**Comment by pdavies88** [comment]
@GnatalieH updates have been made to match the mocks and can be seen here: https://60f9b557105290003b387cd5-djkjfpydne.chromatic.com/?path=/docs/components-va-date-text-input--default

**Comment by GnatalieH** [comment]
@humancompanion-usds [here's the link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/L1oOmW/a/g0KYaEq/r/EPmLQO) to the Sketch artboard for this component. I added symbols for the hint text variations. I'm going to close this ticket before noon ET today unless you want additional changes. Thanks!

**Comment by humancompanion-usds** [comment]
Please update the hint-text color in each of the examples (or update the symbol and be sure those variations are using that symbol). Thanks.
