### ISSUE TITLE
Date web component with text inputs - Final review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#848]
## Description
Prior to a Staging Review, we need to make sure that all the tasks have been completed for the new experimental Date component with text inputs instead of select inputs. Please verify each task and fill in links where applicable below. Once everything is done, reach out to Carol to schedule a Staging Review.

## Details
Component completion checklist:
- [x] Documentation for the component has been published on design.va.gov
    - Link to component on design.va.gov: https://design.va.gov/components/form/memorable-date
- [x] Component has been developed and is available on Storybook
    - Link to component in Storybook: https://design.va.gov/storybook/?path=/docs/components-va-date-text-input--default
- [x] Component is represented in the Design System Sketch Library
    - Link to component page in Sketch Library: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/F8230127-0500-4C1A-BBBB-821299A5BDFF/canvas
- [x] Component has passed an accessibility check
    - Accessibility check ticket: #844

## Tasks
- [ ] Fill out checklist above
- [ ] Once all items are checked off, alert Carol that component is ready for staging review
- [ ] Address any staging review comments

## Acceptance Criteria
- [ ] All items on the checklist are checked off and links have been added
- [ ] Any comments from the staging review have been addressed

**Comment by k80bowman** [comment]
@caw310 this is ready for staging review
