### ISSUE TITLE
Date web component with text inputs - Announcement

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#849]
## Description
Announce that the experimental Date web component with text inputs is ready for testing, add it to the "What's New" page on design.va.gov, and update the Maturity Scale label to "Use with Caution: Available" on design.va.gov (and Storybook and Sketch, when we enable that feature). We will want to be clear in the announcement that this is an experimental design and that it is under consideration for inclusion in the Design System. We should also say that if teams are willing to conduct any usability testing with this component, we would love to hear about the results.

## Details
Dependent on the completion of development, the creation of Sketch artifacts and component page, and documentation for the component on design.va.gov.

In the Slack announcement, please add links to the component page on design.va.gov and to the Design System Maturity Scale page on design.va.gov. Post the announcement in the following Slack channels:
- #vfs-all-teams
- #vfs-engineers
- #vfs-frontend
- #design

Sample announcement:
> :loudspeaker: The Design System has just published a new version of component-library which includes the new [component name] component, as well as made it available in vets-website. You may view the component on design.va.gov, in Storybook, and in the Sketch Pattern Library. This component is rated [Use with Caution: Available on the Design System Maturity Scale](https://design.va.gov/about/maturity-scale#use-with-caution-available) and the Design System Team will be monitoring its usage over the next few months.
>
> If you need any assistance using this component in your applications, please reach out to the Design System Team in the #vfs-platform-support channel.

## Tasks
- [x] Craft component announcement (be sure to add appropriate links)
- [x] Post announcement in Slack channels mentioned above
- [x] Add new component notification to "What's New" page on design.va.gov
- [x] Update Maturity Scale label to "Use: Deployed" on design.va.gov, Storybook, and Sketch (where applicable)

## Acceptance Criteria
- [ ] Component has been announced in appropriate Slack channels
- [ ] New component notification has been added to "What's New" page on design.va.gov
- [ ] Component has the "Use: Deployed" Maturity Scale label on design.va.gov, Storybook, and in Sketch (where applicable)

**Comment by k80bowman** [comment]
@bkjohnson this is good to announce correct? If so, I can take care of adding it to the Confluence doc.

**Comment by bkjohnson** [comment]
Other than making it available in `vets-website`, it should be.

**Comment by bkjohnson** [comment]
The announcements have been made.
