### ISSUE TITLE
[Label] - Documentation update: Make Components > Forms > Label a full-fledged component

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#855]
## Description
Add documentation and guidance for va-label on design.va.gov. This will essentially be a new component and thus should use the [component documentation template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/_components/template.md). However, all sections may not apply given that this is limited to Form Labels.

## Details
* [x] Move hint-text from Components > Form into Components > Form > Label
* [x] Add basic guidance around Form Labels.
* [x] Show error states for labels and share that content 

[add link to Sketch component page]

Be sure to use the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option. If this is a new component that has not yet gone through Staging Review, use the "Use with Caution: Candidate" label.

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by caw310** [comment]
DS Workshop: Group 1 - Medium priority

**Comment by humancompanion-usds** [comment]
We did this but lost track of this issue. Done!
