### ISSUE TITLE
Patterns > Forms > Confirmation - Bring content considerations in from github 

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#857]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add Design System component label (such as `va-alert`)
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete

## Description
The Confirmation page has content guidelines hanging out in va.gov-team:
[Form Confirmation Page content guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/form-confirmation-page.md) (GitHub)

I'd like to bring those into the Confirmation pattern.

## Details
* [ ] Bring content considerations into Confirmation page.
* [ ] Add Content considerations as an h2 and anchor on the page

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
Let's compare the content in github to this page https://design.va.gov/templates/forms/confirmation and note what is different.

**Comment by taylojill** [comment]
Hi @humancompanion-usds I started working on this today (first one), and will discuss with Carol and Natalie on Monday.
cc @caw310

**Comment by taylojill** [comment]
Hi @humancompanion-usds There's a lot of overlap between the two pattern structures. One item, "Helpful content", number 6 below, is not in our GitHub pattern. Also, should accessibility be added to the page? I look forward to your feedback, and to making the updates once finalized.


1. The H1 for this page should carry over from H1 for the online form.
File for [benefit] or Apply for [benefit] and the VA paper form equivalency appears next to or below the H1.

2. Success alert
Use a success alert to let your user know that they’ve successfully submitted their form. Content for the success alert will depend on the form.

3. Print this page pattern
The print this page pattern consists of the Featured content component, content, and a “Print this page” blue button.

4. Other content elements
Content to include on the confirmation page will depend on the type of benefit. Some benefit confirmation pages might need more information than others. Some examples of other content or questions are:

    What happens after I apply?
    How long will it take VA to process the application?
    What can the applicant do while they wait?
    Are there any actions the applicant needs to take while they wait?
    What can the applicant do if they have additional questions after they apply?

5. Action link (CTA button)
The [action link guides the user back to the VA.gov homepage.

6. **Helpful content**
**Helpful content will vary depending on the form. Use the H3 highlight for the title and always label it “Need help?”. The content usually points the user to a number they can call if they need help with their form.**




![Image](https://user-images.githubusercontent.com/97645218/207705757-74613842-2636-4697-a779-0d49a189e68e.png)

7. **Should accessibility be mentioned?**

**Comment by humancompanion-usds** [comment]
@taylojill - This all looks great. Go ahead and add what is missing, especially item #6 (which we should turn into a component). We can ask Sarah to review for a11y but go ahead and make the changes you have and then we can pass this ticket along to her. Thanks!

**Comment by taylojill** [comment]
Hi @Saraharaba8 Can you review https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/857? In talking with @GnatalieH, we wondered if accessibility should be included on the page, and Matt recommended that you take a look. Thank you, let me know if you have questions.

**Comment by caw310** [comment]
@taylojill Sarah Koomson is no longer on DST.

**Comment by taylojill** [comment]
Thanks @caw310

**Comment by caw310** [comment]
PR approved by Matt so closing.
