### ISSUE TITLE
Discovery: What would it take to configure USWDS v3 CSS to work with the VA Design System?

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#859]
## Description
We want to get a better idea of what it would take to configure USWDS v3 CSS to work with the VA Design System. The ultimate goal is to create a new CSS library based entirely on the latest version of USWDS that would be easy to update in the future and configured in such a way that we could replace our current CSS Library with it with minimal disruption to frontend teams using our CSS classes.

## Details
For this part of the discovery, we'd like to see what it would take to configure the color utility classes from USWDS v3 to match the colors used in the VA Design System. Questions we would like answered include:
- What kind of configuration is necessary?
- Can we limit the colors available to the ones we have listed on design.va.gov?
- Can we use class names that match the class names in our current CSS class library?
- What are the differences between the CSS classes that are generated through USWDS v3 and our current CSS color-related classes?

The result of this discovery should be answers to those questions (and any others that arise as part of the work) and a file with USWDS v3-based color utility classes that we could use for the next piece of this discovery.

## Tasks
- [ ] Configure a set of USWDS v3-based color utility classes
- [ ] Answer above questions in this ticket (along with any others that arise as part of the work)

## Acceptance Criteria
- [ ] We have an understanding of what it would take to configure the USWDS v3 CSS classes to work with the VA Design System.

**Comment by bkjohnson** [comment]
Closing this issue as completed since discovery in the PR has been completed. I'm leaving the PR open for now to aid in a discussion tomorrow.
