### ISSUE TITLE
Discovery: What would it take to use USWDS v3-based utility classes on VA.gov?

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#860]
## Description
We want to get a better idea of what it would take to use CSS classes generated through USWDS v3 instead of our current Design System CSS classes. The ultimate goal is to create a new CSS library based entirely on the latest version of USWDS that would be easy to update in the future and configured in such a way that we could replace our current CSS Library with it with minimal disruption to frontend teams using our CSS classes.

## Details
In order to complete the discovery in #859, a file containing CSS classes for color utilities generated using USWDS v3 should have been created. For this part of the discovery, we would like to test what happens when we try to use this file instead of the CSS color utility classes from our current CSS library (Formation).

## Tasks
- [x] Try out using the USWDS v3-based color utility classes in the vets-website repo (replacing our current color utility classes)
- [x] Take note of any problems you notice based on this switch
- [x] Attempt to resolve these problems and take note of the resolutions. Also note any problems that you were not able to resolve or that would take too long to resolve.

## Acceptance Criteria
- [ ] We have an understanding of what it would take to replace our current CSS classes with CSS classes based on USWDS v3 in vets-website applications.

**Comment by bkjohnson** [comment]
The only problem I've noticed with using the new color utilities is that sometimes when using them in place of the formation color utilities, their lower specificity can get overridden by CSS which uses `!important`. Here is an example of that:

![vads-white utility class being overridden by `!important` on `va-button-link` class](https://user-images.githubusercontent.com/2008881/176564869-93573ced-0a3a-475e-8d6a-df8d6cc49d42.png)

In order for this to look right, I had to remove the `va-button-link` class in order to remove that `!important`, and then I had to add the padding/margin utilities to account for the other styling it was doing.

```diff
diff --git a/package.json b/package.json
index 39b03d18e7..9cb05175c6 100644
--- a/package.json
+++ b/package.json
@@ -262,6 +262,7 @@
   "dependencies": {
     "@babel/runtime": "^7.17.7",
     "@department-of-veterans-affairs/component-library": "^10.6.5",
+    "@department-of-veterans-affairs/css-library": "link:../component-library/packages/css-library",
     "@department-of-veterans-affairs/formation": "^7.0.2",
     "@department-of-veterans-affairs/react-jsonschema-form": "^1.2.5",
     "@department-of-veterans-affairs/va-forms-system-core": "0.0.2",
diff --git a/src/platform/site-wide/header/components/VeteranCrisisLine/index.js b/src/platform/site-wide/header/components/VeteranCrisisLine/index.js
index f9fef0ddeb..60df2d182f 100644
--- a/src/platform/site-wide/header/components/VeteranCrisisLine/index.js
+++ b/src/platform/site-wide/header/components/VeteranCrisisLine/index.js
@@ -4,9 +4,9 @@ import React from 'react';
 import recordEvent from 'platform/monitoring/record-event';
 
 export const VeteranCrisisLine = () => (
-  <div className="vads-u-background-color--secondary-darkest vads-u-display--flex vads-u-flex-direction--row vads-u-align-items--center vads-u-justify-content--center vads-u-text-align--center vads-u-padding--0p5">
+  <div className="vads-bg-secondary-darkest vads-u-display--flex vads-u-flex-direction--row vads-u-align-items--center vads-u-justify-content--center vads-u-text-align--center vads-u-padding--0p5">
     <button
-      className="va-button-link vads-u-color--white vads-u-text-decoration--none va-overlay-trigger"
+      className="vads-u-width--auto vads-bg-secondary-darkest vads-u-line-height--3 vads-u-font-weight--normal vads-u-padding--0 vads-u-margin--0 vads-white vads-u-text-decoration--none va-overlay-trigger"
       data-show="#modal-crisisline"
       onClick={() => {
         recordEvent({ event: 'nav-crisis-header' });
diff --git a/src/platform/site-wide/sass/style.scss b/src/platform/site-wide/sass/style.scss
index 0801cd2865..29de4c852f 100644
--- a/src/platform/site-wide/sass/style.scss
+++ b/src/platform/site-wide/sass/style.scss
@@ -24,6 +24,7 @@ $formation-image-path: "~@department-of-veterans-affairs/formation/assets/img";
 @import "~@department-of-veterans-affairs/formation/sass/modules/m-nav-sidebar";
 @import "~@department-of-veterans-affairs/formation/sass/modules/m-nav-linkslist";
 @import "~@department-of-veterans-affairs/formation/sass/shame";
+@import "~@department-of-veterans-affairs/css-library/dist/utilities";
 
 @import "modules/m-button";
 @import "modules/m-footer";
```

---

Additionally, importing the new utilities stylesheet in the site-wide stylesheet is just one option. We could also:

- Import it into specific apps, or
- Create a new stylesheet for it in the webpack config & use it in the HTML head

**Comment by bkjohnson** [comment]
Discovery complete.
