### ISSUE TITLE
Change auto-deploy of design.va.gov to staging and add manual trigger for prod deploy

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#861]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Description
In order to enable being able to more easily check work on the documentation site before deploying to prod, we'd like to change the auto deploy on merge to `master` to go to the dev and staging environments, rather than dev, staging, and prod. We would also like to have a manually-triggered CI task that would deploy to prod.

## Tasks
- [ ] Remove prod from deploy environments list on merge to `master` in the `vets-design-system-documentation` repo
- [ ] Create CI task for deploying to prod manually in the `vets-design-system-documentation` repo

## Acceptance Criteria
- [ ] On merge to `master`, changes are automatically deployed to dev and staging environments
- [ ] We are able to manually deploy `master` to prod

**Comment by bkjohnson** [comment]
Related ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/802
