### ISSUE TITLE
Discovery: How could we better manage releases of the component library?

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#863]
## Description
Problem: Sometimes we have work-in-progress that needs to wait before we release it (for example: the initial translation work). But at the same time we are working on longer-term initiatives, we may have smaller pieces of work that should be released right away. We need to figure out how we can better organize and/or schedule releases to be able to handle these types of situations. Are there things we could automate? If so, how? What other changes could we recommend?

## Tasks
- [ ] Do some research on managing releases
- [ ] Provide some suggestions on how our team could better manage releases for the component library in this ticket
- [ ] Discuss recommendations with the DS team
- [ ] Create ticket(s) for completing the work

## Acceptance Criteria
- [ ] The team has agreed on a path forward for better managing releases of the component library

**Comment by caw310** [comment]
Closing as the DST has a process.
