### ISSUE TITLE
Create Link - Collection: Documentation for major, related, and quick links

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#865]
## Description
We've got major, related, and quick link styles called out in Sketch but not setup as symbols nor text styles and not documented on Components > Link. They look like they are kind of a collection of links, sometimes below a header and sometimes within a card. At any rate, we missed these in the audit somehow and I missed them when looking for instances of the Link component because they are not symbols nor text styles. 

## Details
Sketch page: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/eKk0j8q

<img width="767" alt="Screen Shot 2022-05-13 at 4 31 25 PM" src="https://user-images.githubusercontent.com/52176351/168385111-72b173ff-67e3-4800-8066-e226097416ab.png">

<img width="751" alt="Screen Shot 2022-05-13 at 4 34 37 PM" src="https://user-images.githubusercontent.com/52176351/168385548-0cc14116-18dd-44c4-a7e2-a07a39910b00.png">

USWDS has Collections: https://designsystem.digital.gov/components/collection/

We should also add to this the Authenticated Experience collection style:
![image](https://user-images.githubusercontent.com/52176351/168390681-e98ea727-a013-4707-82df-7e812665b864.png)

There are symbols for those link and icon combinations (sort of a Link - Active with an icon) in the Auth Experience Pattern Library:
https://www.sketch.com/s/225eebbb-fb9a-42db-8655-75c30a9dc935/a/MyPzrEQ

## Tasks
- [ ] Write or update component documentation for design.va.gov. 
  - [ ] Create a sub-page of the Link component page for Collections named "Link - Collections"
  - [ ] Define when to choose each variation of Link - Collections
- [x] Update Sketch to put these variants on a new Link - Collections page and new artboards for mobile and desktop
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
![Screen Shot 2022-06-03 at 4.05.19 PM.png](https://images.zenhubusercontent.com/623c98bb27734da1243c0bb5/aaefdd22-0600-4a7b-aca4-9155eb6b0d77)
