### ISSUE TITLE
Add Code Usage to each component

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#866]
## Description
Add an anchor and the include for Code usage to each component that lacks it.

## Tasks
- [ ] Update all components that lack a Code usage section so that they have one

## Acceptance Criteria
- [ ] Each component has a Code usage section

**Comment by jamigibbs** [comment]
I did a quick audit and the following stories need to be updated with a code example:
 
- [ ] Eyebrow
- [ ] On this page
- [ ] Pagination (incomplete example)
- [ ] Tag

**Comment by jamigibbs** [comment]
On design.va.gov, these components need a Code Usage section:

- [ ] Alert - Expandable
- [ ] Alert - Sign-in
- [ ] Banner - Maintenance
- [ ] Button - Icon
- [ ] Link
- [ ] Link - Action
- [ ] Loading indicator (Needs "on this page" links at the top)
- [ ] Progress bar - Activity
- [ ] Search Input
- [ ]
