### ISSUE TITLE
Create custom 404 page for design.va.gov and work with Ops team to route 403 pages to it

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#867]
## Description
Since design.va.gov is served through AWS, when a user tries to go to a file path that does not exist on the site, they are sent a 403 error. We would like for these to go to a 404 instead, so that we can have a custom 404 page. This needs to be implemented through AWS, so we'll need to work with Ops to make this change.

At the same time, we only have the standard 404 page set up through Jekyll for design.va.gov. We should work with Natalie and Matt to figure out what we'd like a custom 404 page to look like and set that up as well.

## Tasks
- [ ] Coordinate with Ops to have 403 errors for design.va.gov from AWS S3 routed to 404s
- [ ] Coordinate with Natalie and Matt on custom 404 page
- [ ] Create custom 404 page for design.va.gov

## Acceptance Criteria
- [ ] Unknown page errors that were previously getting a standard AWS 403 error page are now routed to a custom design.va.gov 404 page.

**Comment by humancompanion-usds** [comment]
This issue is superseded by https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2912
