### ISSUE TITLE
Text Area web component - Final Review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#872]
## Description
Prior to a Staging Review, we need to make sure that all the tasks have been completed for a component. Please verify each task and fill in links where applicable below. Once everything is done, reach out to Carol to schedule a Staging Review.

## Details
Component completion checklist:
- [x] Documentation for the component has been published on design.va.gov
    - Link to component on design.va.gov: 
- [x] Component has been developed and is available on Storybook
    - Link to component in Storybook:
- [x] Component is represented in the Design System Sketch Library
    - Link to component page in Sketch Library:
- [x] Component has passed an accessibility check
    - Accessibility check ticket:

## Tasks
- [x] Fill out checklist above
- [x] Once all items are checked off, alert Carol that component is ready for staging review
- [ ] Address any staging review comments

## Acceptance Criteria
- [ ] All items on the checklist are checked off and links have been added
- [ ] Any comments from the staging review have been addressed

**Comment by k80bowman** [comment]
@humancompanion-usds There was no additional accessibility feedback, this should be ready for final review.

**Comment by humancompanion-usds** [comment]
I'm glad we have this step because we have some issues that need fixing:

1. The Sketch link goes to text input instead of text area. It should go here: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/C6340B6C-F41E-423B-BDEA-B340A81C9714

2. The 2nd a11y consideration doesn't, for me at least, seem to apply to this field:

> Avoid breaking numbers with distinct sections (such as phone numbers, Social Security Numbers, or credit card numbers) into separate input fields. For example, use one input for phone number, not three (one for area code, one for local code, and one for number). Each field needs to be labeled for a screen reader and the labels for fields broken into segments are often not meaningful.

That seems to be copied over from text-input as well. These items need to be addressed before staging review. Thanks.

**Comment by caw310** [comment]
I will submit staging review request.
