### ISSUE TITLE
Month/Year web component - Sketch artifacts

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#874]
## Description
Create or update Sketch artifacts for the Month/Year web component and add to the VA Design System Sketch library if they are not already there. We are changing this so that it is a variant of the Date component, rather than it's own component. Please reach out to the engineer who is developing this component for clarification.

## Details
[add links to any design documents]

## Tasks
- [x] Create or update Sketch artifacts for component
- [x] Add Sketch artifacts to Sketch library, if not already there
- [x] Create component page in Sketch, if necessary
- [ ] Add link to Sketch component page to documentation ticket

## Acceptance Criteria
- [ ] Sketch component artifacts have been created or updated
- [ ] Sketch component page has been created, if necessary
- [ ] Link to Sketch component page has been added to component documentation ticket

## Mockups

[Month/year Sketch mockups
](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/09yEdz2)

**Comment by GnatalieH** [comment]
Hi @humancompanion-usds, here are [the Month/year mockups](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/09yEdz2) for your review.

**Comment by GnatalieH** [comment]
Fixed margins and am closing this ticket.
