### ISSUE TITLE
Month/Year web component - Final Review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#875]
## Description
Prior to a Staging Review, we need to make sure that all the tasks have been completed for a component. Please verify each task and fill in links where applicable below. Once everything is done, reach out to Carol to schedule a Staging Review.

## Details
Component completion checklist:
- [x] Documentation for the component has been published on design.va.gov
    - Link to component on design.va.gov: https://design.va.gov/components/form/date-input#monthyear
- [x] Component has been developed and is available on Storybook
    - Link to component in Storybook: https://design.va.gov/storybook/?path=/docs/components-va-date--month-year
- [x] Component is represented in the Design System Sketch Library
    - Link to component page in Sketch Library: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols?g=Form%2520controls%252Fdate%2520text%2520inputs-MY
- [x] Component has passed an accessibility check
    - Accessibility check ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39727

## Tasks
- [ ] Fill out checklist above
- [ ] Once all items are checked off, alert Carol that component is ready for staging review
- [ ] Address any staging review comments

## Acceptance Criteria
- [ ] All items on the checklist are checked off and links have been added
- [ ] Any comments from the staging review have been addressed

**Comment by k80bowman** [comment]
@caw310 this is ready for staging review

**Comment by caw310** [comment]
Staging review scheduled for Tuesday, Aug 2.
