### ISSUE TITLE
Button web component - Final Review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#876]
## Description
Prior to a Staging Review, we need to make sure that all the tasks have been completed for a component. Please verify each task and fill in links where applicable below. Once everything is done, reach out to Carol to schedule a Staging Review.

## Details
Component completion checklist:
- [x] Documentation for the component has been published on design.va.gov
    - Link to component on design.va.gov: https://design.va.gov/components/button/
- [x] Component has been developed and is available on Storybook
    - Link to component in Storybook: https://design.va.gov/storybook/?path=/docs/components-va-button--primary
- [x] Component is represented in the Design System Sketch Library
    - Link to component page in Sketch Library: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/5317C603-D6BD-4AFF-84E6-151F7A197B91/canvas
- [x] Component has passed an accessibility check
    - Accessibility check ticket: #818

## Tasks
- [ ] Fill out checklist above
- [ ] Once all items are checked off, alert Carol that component is ready for staging review
- [ ] Address any staging review comments

## Acceptance Criteria
- [ ] All items on the checklist are checked off and links have been added
- [ ] Any comments from the staging review have been addressed

**Comment by humancompanion-usds** [comment]
* @GnatalieH  We're missing the disabled button in Sketch. I know we have had some back and forth here but, I think given that it's in Storybook and on design.va.gov it should also be in Sketch. Sorry if we got our signals crossed there. Essentially we decided that we'd show it and then [strongly discourage folks from disabling it](https://design.va.gov/components/button/#do-not-disable-buttons).

**Comment by GnatalieH** [comment]
@humancompanion-usds I'll add it back. I've been following the conversations in Slack, but I wasn't sure if we explicitly wanted to include it in the library, again. I can easily add it.

**Comment by GnatalieH** [comment]
@humancompanion-usds [here is a link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/5317C603-D6BD-4AFF-84E6-151F7A197B91) to the updated Button arboards with the disabled buttons added back. Does this look OK?

**Comment by humancompanion-usds** [comment]
@GnatalieH - Looks good. @caw310 - We are ready for staging review on this.

**Comment by humancompanion-usds** [comment]
I will use this ticket to address Brian's feedback
