### ISSUE TITLE
`va-date` web component updates

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#877]
## Error Messages

We have an error message pattern established where we don't show an error message until after a form element is blurred, e.g. error message shown for missing or invalid values.

With the `va-date` component, there are 3 elements (2 selects and 1 input), each of which fires off the `onDateBlur` callback (for the react-binding component) when blurred. This makes it difficult to determine when the combined fields should show an error message. I would have expected the `onDateBlur` to trigger once all 3 fields had been touched.

In our case, the `va-date` WC is being used within Form 526's wizard, and shows additional content below the date section once a complete date is entered, so, the `blur` callback isn't being used.

;tldr `onDateBlur` may work better if it was triggered after all fields have been touched

## Tasks

- [ ] Discuss/research when `onDateBlur` callback is fired
- [ ] Reach out to @Mottie to make sure the recommended solution addresses his concerns

## Definition of done

- [ ] Consensus reached on how to handle `onDateBlur`
- [ ] Documentation of decision

## Aria Describedby and Hint Text
Per conversation with @Mottie the `va-date` component should have the `ariadescribedBy` prop since it is being leveraged correctly to provide additional accessible information about the component being used inside a parent legend element. Additionally the component needs to have the ability to add html in between the label and select/input fields. This feature was added to `va-text-input` but is not implemented in `va-date`.

![Screen Shot 2022-05-05 at 1.28.01 PM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/8e7ec0cb-1cdd-4eb9-99fd-b1cec165b4e1)

## Validation
Per conversation custom validation should be added via a function like the React Component to allow for simplicity when doing multiple validations. Validation error messaging should only occur if all fields have been touched and the date is invalid when field is set as required.

## Acceptance Criteria
- [ ] Invalid data entry should trigger the Please enter a valid date error message
- [ ] Valid year entry should be limited from 1900 through 2200
- [ ] Add in a `slot` to the `va-date` component so that developers can add html between the label and input fields
- [ ] Add additional tests to cover these new features
- [ ] Move onBlur event handler to component level from children to fire once component blur fires instead of each field
- [ ] Required validation error should only fire onBlur
- [ ] Add in custom validation props to handle via component onBlur
- [ ] All validation for the component should only occur onBlur
- [ ] Handles validation for Leap Years
- [ ] Acceptable keys in the input fields are the following: 0123456789, Delete, Backspace, Tab, ArrowLeft, ArrowRight

**Comment by pdavies88** [comment]
Related issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/41002

**Comment by caw310** [comment]
Link to PR https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/892

**Comment by pdavies88** [comment]
Per conversation custom validation should be added via a function like the React Component to allow for simplicity when doing multiple validations. Validation error messaging should only occur if all fields have been touched and the date is invalid.

**Comment by pdavies88** [comment]
Removing AC on ariadescribedby prop per: https://github.com/department-of-veterans-affairs/component-library/pull/438#discussion_r889013787
