### ISSUE TITLE
Pilot: Test UXPin Merge integration to design with web-components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#906]
## Description
This is a discovery and pilot issue to explore this question: 
Do we think providing access to UXPin would reduce design/development effort associated with building apps on [VA.gov](http://va.gov/) via the nature of it's integration via github of web-components? 

## Tasks
- [x] Look at UXPin and Storybook integration features
- [x] Possibly create a UXPin trial account
- [x] Look at UXPin and Merge (github) integration
- [x] Add form web-components (the same list as the MVP) to be used in UXPin
- [ ] Import a form flow from Sketch into UXPin (to be provided by the Veteran-facing forms team)
- [ ] Provide a UXPin library of form components to the Veteran-facing Forms team

## Acceptance Criteria 
- [ ] Pilot building a prototype using UXPin, incorporating our form components, with the Veteran-facing Forms team

https://www.uxpin.com/merge

**Comment by Andrew565** [comment]
The components that will be made to work with UXPin Merge include the following:

- Radio button
- Button
- Text input
- Date (could be current Date that uses selects or Memorable Date)
- Select

**Comment by Andrew565** [comment]
@humancompanion-usds All of the listed components we wanted to add have now been added.

**Comment by humancompanion-usds** [comment]
Here is where we are at. The USWDS mode of each component is the target. Here is how that looks:

<img width="477" alt="Screen Shot 2023-05-09 at 3 20 10 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/d3b8d862-75a2-4063-8bef-42d50731f06a">

* Text input: Working!
* Select: Working, but how do I add options to the select?

<img width="396" alt="Screen Shot 2023-05-09 at 3 32 24 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/3605e751-3b4e-47e0-89a0-5be5ec766fb6">

* Checkbox and radio looking good
* The groups of both do not change. Maybe not using the options underneath?
* Memorable date is usable, no changes needed
* Button doesn't have a USWDS param

**Comment by caw310** [comment]
This will carry over into the next sprint to continue pilot with UXPin.

**Comment by humancompanion-usds** [comment]
@Andrew565 - Latest update where everything is set to uswds is looking good. 

Remaining issues:
* Can't resize the button. If that's intentional then we need to discuss. This is a blocker because we can't even make a button that is appropriate to mobile, which is where we try to do most of our testing.
* I still don't understand how to add options to Radio buttons or Checkbox groups. This may be a question for Jack.
* The typography component is helpful but it sets the block size of the headers to be enormous:

![Screen Shot 2023-05-15 at 5.17.57 PM.png](https://images.zenhubusercontent.com/623c98bb27734da1243c0bb5/64016d77-ce61-4e73-8e29-36813e227489)

Is there an internal line-height that is adjustable within the component? If so, can we set it to be our line-height rather than whatever it is currently set to? Essentially, there is built in top and bottom margin and I can't resize the headers to get rid of it. That's fine if it's set to something reasonable, but currently it's quite large.

* Button variations are a little wonky. Here the icons are big but the type size is small. They're out of proportion:

![Screen Shot 2023-05-15 at 5.23.36 PM.png](https://images.zenhubusercontent.com/623c98bb27734da1243c0bb5/53d4090a-5458-4b16-b8b7-495863a9aca7)

We're getting close though.

**Comment by Andrew565** [comment]
- The width on the buttons is set to "100%", so it will just be based on the content of the button. There do not appear to be any styles currently to set it to stretch to a different width, either automatically or manually.
- I don't know how to add extra radio options or checkbox group items, definitely a question for Jack. Alternatively, the RadioOption and Checkbox components could be dragged in manually, they just wouldn't be part of the groups without further intervention.
- I don't understand why there's the extra padding around items either, Jack would need to investigate that.
- The difference in the button's text and icon sizes is due to the text being manually set to 16.96px while the icons are still using 1.6rem, which is calculating off of the base font size being set to 16px, so they're displaying at (16 * 1.6)=25.6px. I'll look into correcting that.

**Comment by humancompanion-usds** [comment]
@Andrew565 - Yes, please do push it through and thanks for these fixes! I really want to unblock the Veteran-facing forms team on using UXPin and I have another component-library change that I want to get deployed thus would appreciate the deployment.

**Comment by humancompanion-usds** [comment]
Button is working! Awesome! Looking forward to the fix to the icons for button pair. I will ping Jack next week.

**Comment by humancompanion-usds** [comment]
@Andrew565 - Can we fix the typography line-height by removing the margin-top on line 15? That gets set to 0 later on in our CSS by `.article > h1 { margin-top: 0; }`:

https://github.com/Andrew565/dva-webcomponents-merge/blob/master/src/components/Typography/styles.scss#L15

I would do it myself but I forgot to accept your invitation and now that has expired. I'm fairly certain that is what is causing the issue I'm seeing in UXPin.

Also, can we bring this repo into the VA org and update the README so that I can make changes like this and know how to deploy them? That should be the final task to get this off your plate.

**Comment by caw310** [comment]
Will carry over into sprint 28

**Comment by Andrew565** [comment]
Got the migration completed: https://github.com/department-of-veterans-affairs/dst-uxpin-merge

**Comment by humancompanion-usds** [comment]
@Andrew565 - When I try to use the typography component in a project I get vastly different results:

![Screen Shot 2023-05-23 at 5.42.01 PM.png](https://images.zenhubusercontent.com/623c98bb27734da1243c0bb5/b290304c-3eaa-4133-af5c-4aa9e8292e16)

Do we need to make the updates available in some other way? It was working inside of the experimental mode.

Also, we'll need to add our h1 and h2 sizes for mobile, which are smaller (but we can open a new bug for that)

**Comment by humancompanion-usds** [comment]
Also, I tried to push it myself but got an error:

> dst-uxpin-merge [master] npm run merge:push

> my-app@0.1.0 merge:push
> uxpin-merge push --token 12345.....
> sh: uxpin-merge: command not found

**Comment by Andrew565** [comment]
Try running `npm i` before executing the merge:push, you may not have the uxpin-merge binary installed for this new repo yet.

I'm unsure what the problem might be for the Typography component, I'll try and load it up on my end and see if I can see anything helpful.
