### ISSUE TITLE
OMB Info - Design 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#911]
## Description
During the consistency audit, it was discovered that OMB info is not in the Sketch library. 

## Details
Add OBM Info to the Sketch library

## Tasks
- [ ] Review DST backlog for outstanding design issues with this component, if necessary
- [ ] Create designs for component and add to Sketch library
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack
