### ISSUE TITLE
On this page - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#912]
## Description
During the consistency audit, there were some issues found. 

## Tasks
- [x] Update link to Storybook to say "View va-on-this-page in Storybook"
- [ ] The links in the component cause a new page to be opened which should not happen

## Acceptance Criteria
- [ ] Link on design.va.gov has the correct text
- [ ] Links do not open a new page

**Comment by humancompanion-usds** [comment]
I've got a PR in flight to fix the storybook link but fixing the remaining issue means updating the example. I'm tempted to say that isn't really necessary. Folks can always hit the back button.

**Comment by humancompanion-usds** [comment]
Yeah, I'm fine with this.
