### ISSUE TITLE
Promo banner - Sketch artifacts

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#914]
## Description
During the consistency audit, there were some discrepancies identified with promo banner. 

## Details
We need symbols/versions of the promo banner at different breakpoints because it changes (and currently breaks upon resize)

## Tasks
- [ ] Create or update Sketch artifacts for component
- [ ] Add Sketch artifacts to Sketch library, if not already there
- [ ] Create component page in Sketch, if necessary
- [ ] Add link to Sketch component page to documentation ticket

## Acceptance Criteria
- [ ] Sketch component artifacts have been created or updated
- [ ] Sketch component page has been created, if necessary
- [ ] Link to Sketch component page has been added to component documentation ticket

**Comment by GnatalieH** [comment]
@humancompanion-usds [here is a link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/G4wZnb/a/zxv99Dl/r/QMkVQm/) to the Promo banner page in Sketch. I believe @seanasewell may have created these artifacts. I'll be out Friday 7/1, so if Sean is able to make any changes necessary (if he's available), that would be great. I see that the symbol should be renamed to remove the Global components parent category as we discussed today. Is there anything else? Thanks.

**Comment by seanasewell** [comment]
@GnatalieH I didn't create this component but I can take a look at it today to ensure it's consistent with what's in Storybook!

**Comment by seanasewell** [comment]
@GnatalieH I updated the component in Sketch

**Comment by GnatalieH** [comment]
@seanasewell thank you! I just saw the Sketch assets. Thanks so much, I didn't realize there were so many states and sizes!

**Comment by GnatalieH** [comment]
Approved with these caveats from Matt:

A couple of things to mention:

- For this component it makes sense to show all of these new viewport widths that Sketch has added as it would be difficult to re-size it otherwise for some of these widths. However, we probably don't want to set a precedent of showing every component at every possible viewport.

- For other components we've shown different viewport sizes on distinct art boards rather than all on one artboard. I'm okay with that here as well but, for other components let's continue to make distinct artboards.

Closing this ticket.
