### ISSUE TITLE
Telephone - Sketch artifacts

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#915]
## Description
During the consistency audit, it was discovered that Telephone isn't in the Sketch library. 

## Details
Add Telephone and variations to the Sketch Library.

## Tasks
- [x] Create or update Sketch artifacts for component
- [x] Add Sketch artifacts to Sketch library, if not already there
- [x] Create component page in Sketch, if necessary
- [ ] Add link to Sketch component page to documentation ticket

## Acceptance Criteria
- [ ] Sketch component artifacts have been created or updated
- [ ] Sketch component page has been created, if necessary
- [ ] Link to Sketch component page has been added to component documentation ticket

**Comment by GnatalieH** [comment]
@humancompanion-usds I've created a page for the [Telephone component here](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/WKjQYn0) in Sketch. Please let me know if I need to make any changes, thanks!

**Comment by GnatalieH** [comment]
@humancompanion-usds I am not sure how to make a symbol where part of the number is editable but part of it isn't. I am using Link / default symbols, but even when I combine two or more Link symbols in a Telephone / extension symbol (for example), Sketch only lets me allow/not allow overrides on the master symbol, and not the inherited symbols. It gets especially tricky because the link is underlined, and you have to manually adjust sections of the symbol to make the underline appear seamless. @seanasewell do you have any advice here?

**Comment by GnatalieH** [comment]
Closing this ticket because all tasks have been completed and the Sketch symbols are approved by Matt.
