### ISSUE TITLE
Promo banner- Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#916]
## Description
To be consistent on design.va.gov, we have changed labels and links to Storybook to use the component name in SB. 

## Tasks

- [ ] Update link on design.va.gov to "View va-promo-banner in Storybook"
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov
