### ISSUE TITLE
MonthYear web component: Announcement

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#917]
## Description
Announce that MonthYear is ready for use, add it to the "What's New" page on design.va.gov.

## Details
Dependent on the completion of development, the creation of Sketch artifacts and component page, and documentation for the component on design.va.gov.

The MonthYear React component is used in one application:
- [financial-status-report](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/financial-status-report/components/EmploymentRecord.jsx)

For this reason it is not necessary to create an es-lint rule for migration, we can just provide instructions to the team who would need to migrate this component.

The Forms Library Team is interested in using this component, so it would be good to reach out to them as well and let them know that it is ready for use.

In the Slack announcement, please add links to the component page on design.va.gov and to the Design System Maturity Scale page on design.va.gov. Post the announcement in the following Slack channels:
- #vfs-all-teams
- #vfs-engineers
- #vfs-frontend
- #design
- #cms-team
- #cms-design

Sample announcement:
> :loudspeaker: The Design System has just published a new version of component-library which includes the new [component name] component, as well as made it available in vets-website. You may view the component on design.va.gov, in Storybook, and in the Sketch Pattern Library. This component is rated [Use with Caution: Available on the Design System Maturity Scale](https://design.va.gov/about/maturity-scale#use-with-caution-available) and the Design System Team will be monitoring its usage over the next few months.
>
> If you need any assistance using this component in your applications, please reach out to the Design System Team in the #vfs-platform-support channel.

## Tasks
- [x] Craft component announcement (be sure to add appropriate links)
- [ ] Post announcement in Slack channels mentioned above
- [ ] Add new component notification to "What's New" page on design.va.gov

## Acceptance Criteria
- [ ] Component has been announced in appropriate Slack channels
- [ ] New component notification has been added to "What's New" page on design.va.gov

**Comment by k80bowman** [comment]
@bkjohnson this is good to announce correct? If so, I can take care of adding it to the Confluence doc.

**Comment by bkjohnson** [comment]
Other than making it available in `vets-website`, it should be.

**Comment by k80bowman** [comment]
Ah that's right. I forgot about that. :(

**Comment by caw310** [comment]
Just put this in the confluence doc. https://vfs.atlassian.net/l/cp/ritMfzpW

**Comment by bkjohnson** [comment]
I was updating it yesterday and I'd like to do some testing to make sure things still work, but if things still work fine then I can bring it out of draft.

**Comment by bkjohnson** [comment]
I just added "MonthYear" to the linked confluence doc, so I'm going to close this.
