### ISSUE TITLE
Discovery: Building a design token library

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#934]
## Description
We'd like to explore what it would take to build out a design token library and decide whether or not we feel like it is worth it to prioritize this work ahead of building out a CSS class library based on USWDS v3.

## Details
Questions we'd like to answer:
- What would the LOE be to complete this work?
- Is [Style Dictionary](https://amzn.github.io/style-dictionary/#/) the best tool for this or are there other options we should consider?
- What are the benefits of having a VADS token library? For our team? For other teams?
- What would be the benefits to beginning our work to transition to USWDS v3 with the development of a design token library?
- Would there be any drawbacks to doing this work first (as opposed to maybe doing it later)? What are they?

There may be other questions that come up over the course of the exploration. Please feel free to add them to this list if you'd like.

If the answers to these questions point us toward building out a design token library first, please add a plan for how this work should be broken down. Katy is happy to help with this if needed.

## Tasks
- [x] Explore building out a design token library for the VADS, answering the questions above
- [ ] Present findings to the DS Team
- [ ] If the decision is to move forward, create a work plan

## Acceptance Criteria
- [ ] A decision has been made about if/when we would like to move forward with building a VADS design token library
- [ ] If necessary, a work plan for building a VADS design token library has been created.
