### ISSUE TITLE
Button Pair - Sketch artifacts

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#938]
## Description
Create or update Sketch artifacts for button pairs component and add to the VA Design System Sketch library if they are not already there. These should be in good shape, but we'd like to double check that everything is in order.

## Details
[add links to any design documents]

## Tasks
- [x] Do an audit
- [x] Create or update Sketch artifacts for component
- [x] Add Sketch artifacts to Sketch library, if not already there
- [x] Create component page in Sketch, if necessary
- [x] Add link to Sketch component page to documentation ticket

## Acceptance Criteria
- [x] Sketch component artifacts have been created or updated
- [x] Sketch component page has been created, if necessary
- [x] Link to Sketch component page has been added to component documentation ticket

**Comment by GnatalieH** [comment]
@humancompanion-usds [here is the audit](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1656437118731/677750efbdccbb00e04aeaffff0620ba1dfec32a?sender=u851998f98038e0f1e2da4592) of the button pairs I found.

**Comment by humancompanion-usds** [comment]
@GnatalieH - I do not have access to that file.

**Comment by GnatalieH** [comment]
Closing as completed per [this Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1657116737103919).
