### ISSUE TITLE
Button Pairs - Final Review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#940]
## Description
Prior to a Staging Review, we need to make sure that all the tasks have been completed for a component. Please verify each task and fill in links where applicable below. Once everything is done, reach out to Carol to schedule a Staging Review.

## Details
Component completion checklist:
- [x] Documentation for the component has been published on design.va.gov
    - Link to component on design.va.gov: https://design.va.gov/components/button/button-pair
- [x] Component has been developed and is available on Storybook
    - Link to component in Storybook: https://design.va.gov/components/button/button-pair
- [x] Component is represented in the Design System Sketch Library
    - Link to component page in Sketch Library: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols?g=Button%2520pair
- [x] Component has passed an accessibility check
    - Accessibility check ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/941

## Tasks
- [x] Fill out checklist above
- [x] Once all items are checked off, alert Carol that component is ready for staging review
- [ ] Address any staging review comments

## Acceptance Criteria
- [x] All items on the checklist are checked off and links have been added
- [ ] Any comments from the staging review have been addressed

**Comment by k80bowman** [comment]
Everything looks good to me. The staging review is scheduled for July 28th.

**Comment by caw310** [comment]
Everything addressed in staging review so closing!
