### ISSUE TITLE
Remove excess padding above text input in error state

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#957]
## Description
Right now, there is a 3rem margin above the label in our va-text-input component. This causes the error state for that component to look like this:
![image](https://user-images.githubusercontent.com/12739849/174162378-a606da4f-e5ae-4361-b02b-3102d3b1f459.png)

We need to reduce the size of that margin so that the left border in the error state does not look so tall.

## Details
This will require design work, sketch updates, and development work.

## Tasks
- [ ] Update design to reduce margin above text input label
- [ ] Ensure that Sketch reflects this update
- [ ] Fix margin in web component to match designs

## Acceptance Criteria
- [ ] The margin above the text input label is smaller and the left border in the error state does not appear so tall

**Comment by andresriveratoro** [comment]
Our `va-number-input` component has this extra space as well.

**Comment by caw310** [comment]
For design, follow USWDS. Check with Natalie or Sean as well.

**Comment by k80bowman** [comment]
If possible, it would be good if we could address #1055 at the same time.

**Comment by bkjohnson** [comment]
Should we see if using uswds3 styles would fix this?

**Comment by k80bowman** [comment]
I'm open to trying it. We would still need to do the Sketch updates.

**Comment by GnatalieH** [comment]
@k80bowman and @bkjohnson I'm working on aligning our Form Sketch assets with USWDS styles. It dovetails with the work I was doing for #960.

**Comment by jamigibbs** [comment]
I've identified the following active components displaying the red left border as part of their error state. They will likely all need some CSS updates to align with USWDS: 

```

va-textarea
va-text-input
va-number-input
va-select
va-date
va-radio
va-memorable-date
va-checkbox-group
va-checkbox
fileInput
```

**Comment by GnatalieH** [comment]
[Here is a link](https://www.sketch.com/s/1cb56b0b-df7c-456b-a8e4-f08a3553a5d3) to the work I've done on removing the excess padding from our form control error states and better aligning with UWDS styles. I think I've got everything accounted for. If anything is missing, please let me know. FYI @jamigibbs @humancompanion-usds.

**Comment by humancompanion-usds** [comment]
Looks good to me.
