### ISSUE TITLE
Update publishing instructions for component library

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#962]
## Configuring this issue
- [ ] Add issue to appropriate epic
- [ ] Add component label (such as `va-alert`), if applicable
- [ ] Add `component-new` or `component-update` label, if applicable
- [ ] Complete sections below
- [ ] Delete this section once complete
## Description
The [instructions for publishing the component library to NPM](https://github.com/department-of-veterans-affairs/component-library/blob/e0a946371f3132351552110c051baeac1d8fbdd9/packages/core/README.md) need to be updated. We would like to have them written in such a way that encourages people to reach out to the DST in order to publish a new package version rather than doing it themselves.

## Tasks
- [ ] Update instructions for publishing the component library to NPM

## Acceptance Criteria
- [ ] Instructions for publishing the component library package to NPM reflect current procedures and encourage people to reach out to the DST if they need a new version published.
