### ISSUE TITLE
File Input - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#964]
## Description
Create design for File Input.

If this is a pattern or component that is alreday in existence, check the Design System Team backlog for outstanding design issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this design and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
[add links to any design documents]

## Tasks
- [x] Review DST backlog for outstanding design issues with this component, if necessary
- [x] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by GnatalieH** [comment]
[Here is a link](https://www.sketch.com/s/1cb56b0b-df7c-456b-a8e4-f08a3553a5d3/p/DA9643BD-6386-4CCD-9811-A654B306BBC6/canvas) to my mockups. Ready for review, @humancompanion-usds. Thanks.

**Comment by humancompanion-usds** [comment]
One adjustment I'd like to propose we make both in Sketch and in code: The 16px margin between label and button does not match every other form field we have where that margin is only 8px. Thus the plain text label doesn't really look all that associated with the button. I think it should be changed to be the standard 8px between label and button. Agree?

Otherwise this looks great to me.

**Comment by GnatalieH** [comment]
@humancompanion-usds I agree with you on the 8px margin. I updated the mockups accordingly. FWIW, the error state has a 12px margin between the label and the form control, so that's what I'm using.

**Comment by GnatalieH** [comment]
Closing as completed, as Matt has approved the latest update with the 8px margin.
