### ISSUE TITLE
File Upload - Sketch artifacts

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#965]
## Description
Create or update Sketch artifacts for File Upload  and add to the VA Design System Sketch library if they are not already there.

## Details
Reference file upload design https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/964

## Tasks
- [ ] Create or update Sketch artifacts for component
- [ ] Add Sketch artifacts to Sketch library, if not already there
- [ ] Create component page in Sketch, if necessary
- [ ] Add link to Sketch component page to documentation ticket

## Acceptance Criteria
- [ ] Sketch component artifacts have been created or updated
- [ ] Sketch component page has been created, if necessary
- [ ] Link to Sketch component page has been added to component documentation ticket

**Comment by caw310** [comment]
Closing as tasks here will be handled in the design ticket.
