### ISSUE TITLE
File Input web component - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#966]
## Description
Build a web component of File input. Be sure to add analytics if necessary, see [guidance](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
- Design documents: [add links to any design documents]
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to have the updated component-docs.json

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library

**Comment by jamigibbs** [comment]
The React version has the Formation error state style currently so let's make sure to update that to match the [USWDS style ](https://designsystem.digital.gov/components/file-input/#file-input-error-hint) in the web component.

Related: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/957

**Comment by GnatalieH** [comment]
@jamigibbs, @k80bowman and I met today (8/5) and here are the takeaways from that conversation:

- File input as a Component includes the label, secondary button and its error state
- Button text (whether to lock it for editing or not): we will have a decision from Danielle and Beth next week about this
- Surrounding content considerations should be addressed separately as a Pattern
- The Progress bar (determinate) should always appear in conjunction with the File input component
- We talked about preparing for the future and the ability to remove an uploaded file (and what that might look like)
- Natalie will see how the label + description might look

Katy and Jami feel free to add to this list.

**Comment by GnatalieH** [comment]
@jamigibbs here are some links for you:

- [File input audit](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1657212587413/e9c04daa4f509253154b2a1aa5dc6bbead180413?sender=u851998f98038e0f1e2da4592)
- [Sketch mockups](https://www.sketch.com/s/1cb56b0b-df7c-456b-a8e4-f08a3553a5d3/p/DA9643BD-6386-4CCD-9811-A654B306BBC6/canvas) (direct link)

**Comment by jamigibbs** [comment]
From [this Slack conversation](https://dsva.slack.com/archives/C01K37HRUAH/p1660240015362249?thread_ts=1659547593.525989&cid=C01K37HRUAH), the decision was made to allow the `buttonText` value to be dynamic and default to "Upload file".
