### ISSUE TITLE
File Input - Final Review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#969]
## Description
Prior to a Staging Review, we need to make sure that all the tasks have been completed for a component. Please verify each task and fill in links where applicable below. Once everything is done, reach out to Carol to schedule a Staging Review.

Once the Staging Review is complete and any issues have been addressed, announce the component in Slack and add the announcement to the "What's new" page on design.va.gov.

### Component completion checklist:
- [x] Documentation for the component has been published on design.va.gov
    - Link to component on design.va.gov: https://design.va.gov/components/form/file-input
- [x] Component has been developed and is available on Storybook
    - Link to component in Storybook: https://design.va.gov/storybook/?path=/docs/components-va-file-input--default
- [x] Component is represented in the Design System Sketch Library
    - Link to component page in Sketch Library: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/2EB04B39-CAE6-4D13-8655-4394F9A3F072/canvas

### Announcement
Add an item to the monthly [What's New update Confluence page](https://vfs.atlassian.net/wiki/spaces/DST/pages/2301100061/Monthly+DS+Updates+to+What+s+New) that says the Link web component is ready for use. It should include a link to the component on design.va.gov.

Sample announcement:
> The new [[component name] component](link to component on design.va.gov) is now available in the Design System. Guidance and design resources are now available on design.va.gov, in Storybook, and in the Sketch Pattern Library.

## Tasks
- [x] Fill out checklist above
- [x] Once all items are checked off, alert Carol that component is ready for staging review
- [x] Address any staging review comments
- [x] Add announcement to the monthly What's New update Confluence page

## Acceptance Criteria
- [ ] All items on the checklist are checked off and links have been added
- [ ] Any comments from the staging review have been addressed
- [ ] Component announcement has been added to the monthly What's New update Confluence page

**Comment by k80bowman** [comment]
If @humancompanion-usds doesn't have anything to add, this is ready for staging review.

**Comment by caw310** [comment]
Staging review on 9/13.

**Comment by caw310** [comment]
Closing as staging review comments were addressed by Jami.  
File input web component has been added to confluence page for September updates.
