### ISSUE TITLE
File Input  web component - Announcement

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#970]
## Description
Announce that File Input web component is ready for use and add it to the "What's New" page on design.va.gov

## Details
Dependent on the completion of development, the creation of Sketch artifacts and component page, and documentation for the component on design.va.gov.

In the Slack announcement, please add links to the component page on design.va.gov and to the Design System Maturity Scale page on design.va.gov. Post the announcement in the following Slack channels:
- #vfs-all-teams
- #vfs-engineers
- #vfs-frontend
- #design
- #cms-design
- #cms-team

Sample announcement:
> :loudspeaker: The Design System has just published a new version of component-library which includes the new [component name] component, as well as made it available in vets-website. You may view the component on design.va.gov, in Storybook, and in the Sketch Pattern Library. This component is rated [Use with Caution: Available on the Design System Maturity Scale](https://design.va.gov/about/maturity-scale#use-with-caution-available) and the Design System Team will be monitoring its usage over the next few months.
>
> If you need any assistance using this component in your applications, please reach out to the Design System Team in the #vfs-platform-support channel.
>
> We will also be deprecating the current [component name] React component. An ESLint warning rule has been added to help teams migrate to the new web component. In six weeks (three sprints) we will change this warning to an error and remove the React component documentation from Storybook (though the component will still be available for use), so we encourage you to migrate as soon as you are able. Please reach out in the #vfs-platform-support channel if you notice any bugs in the new web component or have any difficulties with the migration.

## Tasks
- [ ] Craft component announcement (be sure to add appropriate links)
- [ ] Post announcement in Slack channels mentioned above
- [ ] Add new component notification to "What's New" page on design.va.gov

## Acceptance Criteria
- [ ] Component has been announced in appropriate Slack channels
- [ ] New component notification has been added to "What's New" page on design.va.gov
