### ISSUE TITLE
Link - Sketch artifacts

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#973]
## Description
Create or update Sketch artifacts for Link and add to the VA Design System Sketch library if they are not already there.

## Details
[add links to any design documents]

## Tasks
- [ ] Create or update Sketch artifacts for component
- [ ] Add Sketch artifacts to Sketch library, if not already there
- [ ] Create component page in Sketch, if necessary
- [ ] Add link to Sketch component page to documentation ticket

## Acceptance Criteria
- [ ] Sketch component artifacts have been created or updated
- [ ] Sketch component page has been created, if necessary
- [ ] Link to Sketch component page has been added to component documentation ticket
