### ISSUE TITLE
Link web component - Final Review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#977]
## Description
Prior to a Staging Review, we need to make sure that all the tasks have been completed for a component. Please verify each task and fill in links where applicable below. Once everything is done, reach out to Carol to schedule a Staging Review.

## Details
Component completion checklist:
- [x] Documentation for the component has been published on design.va.gov
    - Link to component on design.va.gov: https://design.va.gov/components/link/
- [x] Component has been developed and is available on Storybook
    - Link to component in Storybook: https://design.va.gov/storybook/?path=/docs/components-va-link--default
- [x] Component is represented in the Design System Sketch Library
    - Link to component page in Sketch Library: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/D58429E9-064C-48EE-8681-0389401F887C/canvas
- [x] Component has passed an accessibility check
    - Accessibility check ticket: #975

### Announcement
Add an item to the monthly [What's New update Confluence page](https://vfs.atlassian.net/wiki/spaces/DST/pages/2301100061/Monthly+DS+Updates+to+What+s+New) that says the Link web component is ready for use. It should include a link to the component on design.va.gov.

Sample announcement:
> The new [[component name] component](link to component on design.va.gov) is now available in the Design System. Guidance and design resources are now available on design.va.gov, in Storybook, and in the Sketch Pattern Library.

## Tasks
- [x] Fill out checklist above
- [ ] Once all items are checked off, alert Carol that component is ready for staging review
- [x] Address any staging review comments
- [x] Add announcement to "What's New" Confluence page for the month

## Acceptance Criteria
- [x] All items on the checklist are checked off and links have been added
- [x] Any comments from the staging review have been addressed
- [x] Component announcement has been added to the "What's New" Confluence page for the month

**Comment by k80bowman** [comment]
We should also validate that this component handles department-of-veterans-affairs/va.gov-team#11852. If so, that ticket can be closed.

**Comment by k80bowman** [comment]
@humancompanion-usds this component is ready for review.

**Comment by k80bowman** [comment]
@andresriveratoro since you did the development on this component, would you be able to validate that [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11852) is not a problem with the web component?

**Comment by andresriveratoro** [comment]
@k80bowman The va-link web component includes [variants for download and video links](https://design.va.gov/storybook/?path=/docs/components-va-link--default). We can close https://github.com/department-of-veterans-affairs/va.gov-team/issues/11852 as part of this issue.

**Comment by k80bowman** [comment]
Fantastic, thank you!

**Comment by k80bowman** [comment]
@caw310 unless @humancompanion-usds has any other comments, this is ready for staging review.

**Comment by caw310** [comment]
On design.va.gov Link is deployed but on Storybook it says use with caution. Which should it be?

**Comment by k80bowman** [comment]
I think it's OK that they are different until the component goes through Staging Review. Once that process is complete, we'll update Storybook to match design.va.gov.

**Comment by humancompanion-usds** [comment]
Approved! Looking good.

My only minor complaint is about the height of the iframes. I see that I can set the height according to a param in the storybook-preview include. I'm going to tweak those in a PR. But don't let that hold up staging review.

**Comment by caw310** [comment]
Staging review scheduled for 9/9 at 2pm ET.

**Comment by caw310** [comment]
Closing as there was no feedback from staging review. I've added this to the September what's new confluence page.
