### ISSUE TITLE
OMB Info - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#981]
## Description
Create design for OMB Info.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding design issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this design and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
[add links to any tickets or documents with details about the design]
[add links to any research documents related to the component]

## Tasks
- [x] Review DST backlog for outstanding design issues with this component, if necessary
- [x] Create designs for component
- [x] Review designs with PO and/or DSC
- [x] Review designs with an accessibility specialist
- [x] Review designs with DST members (Carol can help schedule this)
- [x] Address any comments from reviews, if necessary
- [x] Comment on this ticket with any accessibility considerations engineers may need to know
- [x] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [x] Component design is complete and has been reviewed
- [x] Accessibility considerations have been added to this ticket, if necessary
- [x] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Closing as design is not needed since OMB info was updated during the consistency audit work.

**Comment by caw310** [comment]
There are Sketch updates needed to this.

**Comment by GnatalieH** [comment]
@andresriveratoro [here is the link](https://www.sketch.com/s/789c144c-98c6-4350-b9d5-9acb6112069d/a/VrO4bWa) to my mockup using a secondary button and updated button label text.

**Comment by GnatalieH** [comment]
@humancompanion-usds when you are back, would you please review the new design for [OMB info here](https://www.sketch.com/s/789c144c-98c6-4350-b9d5-9acb6112069d/a/VrO4bWa)? We replaced the link, which was actually a button styled as a link, with a secondary button. Thanks!

**Comment by GnatalieH** [comment]
Closing issue as completed since this was just a small update to make the component materially honest.
