### ISSUE TITLE
OMB Info web component - Final Review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#986]
## Description
Prior to a Staging Review, we need to make sure that all the tasks have been completed for a component. Please verify each task and fill in links where applicable below. Once everything is done, reach out to Carol to schedule a Staging Review.

Once the Staging Review is complete and any issues have been addressed, announce the component in Slack and add the announcement to the "What's new" page on design.va.gov.

### Component completion checklist:
- [x] Documentation for the component has been published on design.va.gov
    - Link to component on design.va.gov: 
- [x] Component has been developed and is available on Storybook
    - Link to component in Storybook:
- [x] Component is represented in the Design System Sketch Library
    - Link to component page in Sketch Library:
- [ ] Component has passed an accessibility check
    - Accessibility check ticket:

### Announcement
Add an item to the monthly [What's New update Confluence page](https://vfs.atlassian.net/wiki/spaces/DST/pages/2301100061/Monthly+DS+Updates+to+What+s+New) that says the Link web component is ready for use. It should include a link to the component on design.va.gov.

Sample announcement:
> The new [[component name] component](link to component on design.va.gov) is now available in the Design System. Guidance and design resources are now available on design.va.gov, in Storybook, and in the Sketch Pattern Library.

## Tasks
- [ ] Fill out checklist above
- [ ] Once all items are checked off, alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Since this was previously a React component and is set to "Use: Deployed" on design.va.gov, once the final review of the web component is complete, let's update Storybook to show "Use: Deployed" as well.
- [ ] Add announcement to "What's New" Confluence page for the month

## Acceptance Criteria
- [ ] All items on the checklist are checked off and links have been added
- [ ] Any comments from the staging review have been addressed
- [ ] Component announcement has been added to the "What's New Confluence page for the month
