### ISSUE TITLE
Privacy Agreement - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#989]
## Description
Create design for Privacy Agreement.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding design issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this design and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
[add links to any tickets or documents with details about the design]
[add links to any research documents related to the component]

## Tasks
- [ ] Review DST backlog for outstanding design issues with this component, if necessary
- [x] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by seanasewell** [comment]
@GnatalieH The component has been created in Sketch. I listed it as a form component. Let me know what you think (form / privacy agreement / state).

**Comment by GnatalieH** [comment]
Hi @seanasewell, thanks! I think I'd put Privacy agreement at the top level, rather than under Form, and include it on the Privacy agreement page in Sketch. Otherwise everything looks great, thanks!

**Comment by seanasewell** [comment]
@GnatalieH Thanks for reviewing. I made those updates!

**Comment by GnatalieH** [comment]
Thanks @seanasewell! Sorry to be a stickler, but shouldn't we be nesting the [checkbox symbols](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/ELAzjv2) in the Privacy agreement symbols? Did you have to break the checkbox symbols? I believe we should also not allow overrides for the Privacy agreement checkbox text, since it's standard, except for maybe the error message. Also, I noticed the error style for the checkbox symbol is different than any of the other form control error states. It doesn't quite match the [developed component](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--error), but that one also looks strange to me. I'll ping @bkjohnson in our team's Slack channel about the error style discrepancies between checkbox and the other form controls.

**Comment by seanasewell** [comment]
@GnatalieH The checkbox symbol has some padding built into it (padding-left: 24px; padding-top: 14px;). The padding between the checkbox itself and the label is 10px. This padding doesn't match the [privacy agreement padding in storybook](https://design.va.gov/storybook/?path=/docs/components-privacyagreement--default). The error state padding is a bit different than what's standard as well. I have some ideas around how to design components to help mitigate some padding issues we might face in the future if you want to connect at some point.

Update on text overrides have been made!

**Comment by GnatalieH** [comment]
Hi @seanasewell, we're deprecating that React Privacy agreement component. Can you design the new one at the specs you think it *should* be? It shouldn't match the React component if that's out of sync with our other form control states. Sometimes we optimize things when we go from React to Web components. Thanks!

**Comment by seanasewell** [comment]
@GnatalieH Ok, I updated it to match the padding in the checkbox component. I did have to break the checkbox and label symbol in order to accommodate the text, privacy policy link, and the required text. Does that work? It's a little difficult to make the checkbox and label symbol work here because I would have to add the privacy policy link styling (blue, underlined text) along with required text right next to one another which doesn't allow it to scale very well.

**Comment by GnatalieH** [comment]
@seanasewell thank you! Yes, it's fine to break the symbol in this case. I am familiar with how the different styles of text, including required and link text, make things complicated. Thanks so much!

**Comment by seanasewell** [comment]
@GnatalieH Sounds good to me! Thank you :)

**Comment by GnatalieH** [comment]
[Here is the link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/l13oDA7) to the Privacy Agreement page in the Sketch library, which we'll link to from design.va.gov.

**Comment by GnatalieH** [comment]
@seanasewell I presented the designs today at standup, and Katy reminded me about [this ticket's discussion](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/961). We should use the description field for the link text because we don't want to open up the checkbox to allow HTML elements. I feel like we should circle around with Content to find out if they have preferred text. I can do that.

**Comment by GnatalieH** [comment]
Hey @seanasewell. I updated the [Privacy agreement component](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/l13oDA7) so that it is formatted with the link in the description slot, rather than in the checkbox text. Can you give it a quick review? I tweaked some of the naming conventions to fit how Matt likes to name things. I don't have confirmation on the exact copy, yet, but I at least wanted to get things formatted correctly.

**Comment by seanasewell** [comment]
@GnatalieH Looks good to me. Thanks for diving into this!

**Comment by GnatalieH** [comment]
@seanasewell and @humancompanion-usds I updated [the Sketch file](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/l13oDA7) with the correct Privacy agreement verbiage. This should be ready to close pending Matt's review.

**Comment by humancompanion-usds** [comment]
@GnatalieH and @seanasewell - This looks good. One issue: We seem to have consistently used 12px of space below error text in other components, and in this one. But the space above - between the label and the error text - seems a little random here and in some of the other components I looked at (seems to be 0px in Privacy agreement, 8px in File Input, 8px in Date Input, 0px in Number input, etc.) It may just be an issue of line-heights being different but, can you take a look at tighten this up? Thanks!

**Comment by GnatalieH** [comment]
@humancompanion-usds good catch. I imagine that some of the inconsistent spacing came from older artifacts (Sketch or React components). And, when I updated some things on the form input symbols recently I noticed the previous designer had used 28px line heights for the input field labels (to automatically put in some spacing, I suppose). I changed this to 24px line height (which I checked against our components) but didn't increase any spacing. Select box has 4px spacing between the label and error message. USWDS uses 16px line heights with 4px space between the label and error message and 12px space between the error message and input. I can easily change our form components, but we'll need to make a ticket so the developed components will match. CC @seanasewell

**Comment by humancompanion-usds** [comment]
If you feel that 24px line-height with no spacing is equivalent to 16px line-height and 4px spacing then it sounds like we can just go with the Sketch changes you made without having to update our components. If you think that's not sufficient spacing then let's talk more.
