### ISSUE TITLE
Privacy Agreement web component - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#991]
## Description
Build a web component of Privacy Agreement. Be sure to add analytics if necessary, see [guidance](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
- Design documents: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/l13oDA7
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to have the updated component-docs.json

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library

**Comment by jamigibbs** [comment]
As part of this work, I discovered a design defect in the `va-checkbox` component where the checkbox label text was not wrapping correctly. Ideally, it should be aligned along the right edge of the checkbox square as shown here:

![Screen Shot 2022-09-08 at 8.57.19 AM.png](https://images.zenhubusercontent.com/606751e9782b4dd6d85cd9ac/23166882-3fb8-4a8b-9726-56887855fc12)

Instead, it is wrapped to the left edge:

![Screen Shot 2022-09-08 at 8.57.25 AM.png](https://images.zenhubusercontent.com/606751e9782b4dd6d85cd9ac/852b750e-b7ca-4413-81e1-72bf96f85ec6)

I'll make this update in the web component PR: https://github.com/department-of-veterans-affairs/component-library/pull/524

**Comment by humancompanion-usds** [comment]
I'm a little stuck on writing up guidance for this because it's unclear whether or not this component is required at the end of every form or just some based on some criteria. I need to get to the bottom of it so that we don't say it's required when it is not, or vice versa.
