### ISSUE TITLE
Privacy Agreement web component - Final Review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#994]
## Description
Prior to a Staging Review, we need to make sure that all the tasks have been completed for a component. Please verify each task and fill in links where applicable below. Once everything is done, reach out to Carol to schedule a Staging Review.

### Component completion checklist:
- [x] Documentation for the component has been published on design.va.gov
    - Link to component on design.va.gov: https://design.va.gov/components/privacy-agreement
- [x] Component has been developed and is available on Storybook
    - Link to component in Storybook: https://design.va.gov/storybook/?path=/docs/components-privacyagreement--default
- [x] Component is represented in the Design System Sketch Library
    - Link to component page in Sketch Library: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols?g=Privacy%2520agreement

### Announcement
Add an item to the monthly [What's New update Confluence page](https://vfs.atlassian.net/wiki/spaces/DST/pages/2301100061/Monthly+DS+Updates+to+What+s+New) that says the Link web component is ready for use. It should include a link to the component on design.va.gov.

## Tasks
- [x] Fill out checklist above
- [ ] Once all items are checked off, alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Add announcement to "What's New" Confluence page for the month

## Acceptance Criteria
- [ ] All items on the checklist are checked off and links have been added
- [ ] Any comments from the staging review have been addressed
- [ ] Component announcement has been added to the "What's New Confluence page for the month
